### ISSUE TITLE
Firefox rendering performance report

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1005]

**Comment by AoDev** [comment]
I arrived here because I just tried our app, which uses cytoscape.js, in Firefox. Performance is low compared to Chrome. Our graph has around 6 nodes and 6 edges. Panning and zooming are not smooth. I tried in the demos on cytoscape site, and it's the same behaviour.

I suppose it's more a problem of the browser but shouldn't this be mentioned in the docs? I think it would be useful to mention the expected performance on different browsers.

**Comment by maxkfranz** [comment]
Thanks for your feedback.

I suspect there may be some issue in your setup.  Maybe a graphics driver issue or a browser extension?  The examples run smoothly on Firefox on all the machines I have access to -- many of which are average performance-wise.

As for documenting relative browser performance, it's tricky.  We can't say that one browser is absolutely faster than another, because other factors come into play (e.g. hardware acceleration support).  In fact, from browser version to version, there are differences.  At at least one point that I recall, Firefox was much faster than Chrome.

You may find the rendering for unstable/2.5 to be smoother and faster.  I'll probably release a beta very soon to npm while I'm working on the docs -- which is pretty much all that's left for the release.

**Comment by maxkfranz** [comment]
And note that this issue is not meant to increase performance in our lib w.r.t. Firefox.  We're pretty much as optimised as possible. 

I was talking with some folks at Mozilla and they asked that I create a demo to benchmark their performance for canvas using Cytoscape.js.  The intention is that the benchmark could be used to help them increase the performance of their canvas implementation for larger, more complex usecases like ours.

**Comment by AoDev** [comment]
It's a mac book pro late 2013. I don't think there can be a driver issue.

On my machine most animations (whether CSS or canvas) are performing worst on Firefox (41.0.1) than on Chrome (45.0.2454.99 (64-bit)) so I don't think the machine has a problem.

**Comment by maxkfranz** [comment]
Performance enhancements in 2.7 work around Firefox's slower canvas drawing performance for many cases, especially general viewing.  Removing from 2.8 milestone, but it may be nice to have a FF report later when there's less to do
