### ISSUE TITLE
Created edges not displayed

### ISSUE THREAD

**Issue by dbeanm** [cytoscape/cytoscape.js#1007]
Hi,

We've updated to version 2.4.3 and now have a problem that edges created by users aren't displayed properly if there are edges in the opposite direction between a pair of nodes. The original edge still becomes curved but the second edge doesn't appear. Multiple edges do display correctly if they all have the same source and target.

In the image, the edges between n0 and n1 display correctly, but there should be two edges between n2 and n3. The problem is not present in the previous version we used, 2.3.3. We've tested 2.4.3 and 2.4.2, both of which don't work.

The edge is created using:

```javascript
cy.add([{
	group: "edges",
	data: {
	    id: "e" + setID,
	    source: "n0",
	    target: "n1",
	},
	classes: "normal"
}]) 
```

![screen shot 2015-07-10 at 16 25 09](https://cloud.githubusercontent.com/assets/6032552/8621933/4816d5b6-2720-11e5-8208-4ea74308edfd.png)

**Comment by maxkfranz** [comment]
Related to https://github.com/cytoscape/cytoscape.js/issues/985

**Comment by maxkfranz** [comment]
Snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-37e892af1b-1436548688457.zip

**Comment by dbeanm** [comment]
That fixed it, thanks!
