### ISSUE TITLE
IE10 doesn't remove label calc div properly -- results in error

### ISSUE THREAD

**Issue by jeannieincanada** [cytoscape/cytoscape.js#1014]
ERROR: 
SCRIPT5022: NotFoundError - cytoscape.js line 15422 character 7
 - -   document.body.removeChild(this.labelCalcDiv);

Note: This bug may have been introduced by : https://github.com/cytoscape/cytoscape.js/commit/e2784ab46582a41694f7835be0fc0e3d787c4814

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-7b37cb8260-1437497360388.zip

Try this.  This is an issue on IE's side.  Considering `.destroy()` shouldn't happen too often, the expense of a try-catch seems reasonable here.  Let me know if it works for you.
