### ISSUE TITLE
Reducing Compound Node Size During Layout

### ISSUE THREAD

**Issue by Richardsonke** [cytoscape/cytoscape.js#1016]
Is there a way with CoSE or cola to to minimize the size of the compound nodes, particularly when you have nodes with no edges?  When Cytoscape does a large layout, I often end up with compound nodes that are way larger than they need to be.  

Example with cola:

![image](https://cloud.githubusercontent.com/assets/860818/8810059/6379a84a-2fba-11e5-8faa-305c5882b5c1.png)

Example with CoSE:

![image](https://cloud.githubusercontent.com/assets/860818/8810152/0879eb0c-2fbb-11e5-97fb-2667171bb8f6.png)

The CoSE one looks the worst because I'm having difficulty finding the right values for the different settings with a large dataset (example dataset is 142 nodes and 76 edges).

**Comment by maxkfranz** [comment]
There isn't much you can do, apart from experimenting with different layout parameters.

There is an improved (and rewritten) version of CoSE (i.e. `cose2`) that produces more compact layouts in `unstable`/2.5.

**Comment by Richardsonke** [comment]
Thanks for the information!  Are there any automatic builds that run on the unstable branch, or do I need to build it myself?  It looks like the /dist folder on the unstable branch is out of date (6 months old).

**Comment by maxkfranz** [comment]
Only release builds are built automatically.  You'll have to build `unstable` yourself via `gulp build`.

**Comment by maxkfranz** [comment]
Closing for now

**Comment by kunalganglani** [comment]
I am facing the same issue, i want all nodes in the compound node in a straight vertical alignment, is there anyway to achieve this?
