### ISSUE TITLE
Is it possible to do 'silent' select?

### ISSUE THREAD

**Issue by ktei** [cytoscape/cytoscape.js#1019]
I know this might sound a bit weird, but in my project, one I `cyNode.select()`, I highlight the corresponding row in another UI list, where all the nodes are shown. I achieve this by listening to `select` event. In the meantime, if the user clicks on the row, the corresponding node gets selected too.

Now I have a problem that when the user clicks on the row, it triggers the cyNode to be selected, which then fires `select` event, which then triggers row highlighting behavior, which disrupts the user workflow.

Is there any way to 'silent' select a node, such that it only changes its state to 'selected', without firing up the `select` event? I need it to change to `selected` state because that can trigger the node to be highlighted (in bold circle, based on the cytoscape stylesheet I made)

Thank you @maxkfranz

**Comment by maxkfranz** [comment]
No, that's not possible.  This is a general problem with event cycles in any event-driven system.  There are several solutions for this, but you probably just want to disable your listeners when your app-level code is making a selection.  That will break the cycle.

**Comment by ktei** [comment]
Yeah that's what I am doing currently. Wanted to remove that code, lol..... Alright, thank you @maxfranz
