### ISSUE TITLE
Cytoscape.js License

### ISSUE THREAD

**Issue by bilginm** [cytoscape/cytoscape.js#1021]
We are experimenting with cytoscape.js and developed a working demo for our new product. 

Later on i noticed that cytoscape is LGPL v3, since we want to include cytoscape.js in our IOS app running inside UIWebView in IOS SDK our lawyers think we won't be LGPL v3 compliant. Is it possible to get an LGPL v2 license or some form of MIT/apache etc.. dual license option with cytoscape?

**Comment by maxkfranz** [comment]
I don't think the current licensing should be an issue, but your lawyers should be able to confirm this by reading through LGPL v3.

LGPL mostly concerns changes to the library being brought back to the open source community.  Cytoscape.js is currently already used in several commercial products.

**Comment by maxkfranz** [comment]
Closing for now
