### ISSUE TITLE
Dos cytoscape.js can draw this type of diagram

### ISSUE THREAD

**Issue by zhenyuan2015** [cytoscape/cytoscape.js#1022]
http://image79.360doc.com/DownloadImg/2014/10/1120/46042822_7.jpg
![292128b6-36d2-11e5-9336-4d4cf8e81d8e](https://cloud.githubusercontent.com/assets/12582196/9004332/b1770bc4-37a7-11e5-955e-50029fcab5d2.png)

and another type is sunburst
![3c713cda-36d2-11e5-9b97-891d50b870bb](https://cloud.githubusercontent.com/assets/12582196/9004337/b8e97b4e-37a7-11e5-84b0-72c91974e420.png)

http://image79.360doc.com/DownloadImg/2014/10/1120/46042623_7.jpg

I'd like to develop these two type diagram, other libraries I was considering are d3.js, gojs.js,arbor.js.

**Comment by maxkfranz** [comment]
Please refer to the documentation.  Cytoscape.js can create graphs as per graph theory, with nodes and edges.
