### ISSUE TITLE
Include labels in layout calculation

### ISSUE THREAD

**Issue by domoritz** [cytoscape/cytoscape.js#1023]
http://js.cytoscape.org/#collection/position--dimensions/eles.boundingBox seems to have an option includeLabels but I don't see how I would ask the algorithm such as dagre to use it.

**Comment by maxkfranz** [comment]
This required changes to several layouts themselves to take into account BB in lieu of simply w/h.  The lib only included w/h until more recent versions, so the layouts used those values.

You can build off `unstable` to see the changes.
