### ISSUE TITLE
Problem using dagre layout

### ISSUE THREAD

**Issue by MiguelAngelRG** [cytoscape/cytoscape.js#1026]
Hi guys, 

I am using dagre layout cause I would like to draw a tree. 
This is the code that I have done: 

  cy.add({
      group: "nodes",
      data: { id:"n0",name:"n0",weight: 75 },
  });
  $.ajax(url).done(function(jsonTree){

      for(var i=1;i<6;i++){
        var child = jsonTree.result[i];
        cy.add([
          { group: "nodes", data: { id: "n"+i,nname:child.label }},
          { group: "edges", data: { id: "e"+i, source: "n0", target: "n"+i } }
        ])

      }
I am trying to add nodes on the fly but the page does not shows the inserted nodes, any idea? I have to repaint something?.. thanks for your help

**Comment by maxkfranz** [comment]
A layout runs only when you call `layout.run()` or `cy.layout()`.  It will not proactively set positions for you as new nodes are added.
