### ISSUE TITLE
Arbor layout throws error for locked nodes

### ISSUE THREAD

**Issue by tomka** [cytoscape/cytoscape.js#1031]
If a node is locked and the arbor layout is used, a `TypeError` is thrown. To demonstrate this, I created a [jsfiddle](http://jsfiddle.net/7m89p6uL/) and attached the demo code below. Starting from an empty space, the problem seems to be in `ArborLayout.run()`:

- `sys.screenSize(bb.w, bb.h)` is called and the screen size is set. However, `_bounds` (or `p` in the minified version) is not set, because there are no nodes part of the particle system's state at this point.
- Then all nodes are added with `nodes.each(function(i, node) { addNode(node); })` and `addNode()` will try to get the node's position with the help of `sys.fromScreen()` with `sys` being arbor's particle system. This `fromScreen()` call will return `undefined` immediately, because there are no bounds set (and how could they, there are no nodes added yet).
- Then the next call is to `sys.addNode()` which will use the `x` and `y` component of what `sys.fromScreen()` returned if the node is locked (otherwise it will use `undefined`).  This of course fails, because `sys.fromScreen()` returned `undefined`.

This code demonstrates the problem:

```
window.onerror = function() {
    alert("Oops! Arbor layout failed.");
};

$('#cy').cytoscape({
  ready: function(){
      window.cy = this;
      
      var elements = {
        nodes: [
          { data: { id: 'n1', name: 'n1', size: 50} },
          { data: { id: 'n2', name: 'n2', size: 50} },
          { data: { id: 'n3', name: 'n3', size: 50} },   
        ],
        edges: [
          { data: { source: 'n1', target: 'n2' } }
        ]
      };
      
      cy.add(elements);
      var options = {
          name: 'arbor'
      };

      // If at least one node is locked, the cy.layout() call below will fail.
      // Everything works fine, if the 'locked' array below is empty.
      var locked = ['n1'];
      cy.nodes().each(function(i, node) {
          if (-1 !== locked.indexOf(node.id())) {
              node.lock();   
          }
      });

      cy.layout(options);
  }
});
```

**Comment by maxkfranz** [comment]
The issue is not with bounding boxes.  You called a layout *after* adding elements, so you have a defined BB -- as you'll notice if you step through the code in your debugger.

The issue is that you've specified a node as locked without any position at all.  Arbor can not assign a position because you've made position immutable.  But you've specified the node to be included in the layout.  Arbor can't set or get position.  We're in a contradictory state.

You need to set a defined position to a node if you're going to lock it.  Otherwise, locking doesn't make sense.  Either specify initial positions or use another layout to do so for you after adding.

**Comment by tomka** [comment]
Thanks for the quick reply and your explanation! Of course, locking doesn't make much sense without a position.

However, I actually had this problem with nodes having a position. When I stepped through the code, `_bounds` was never set in the particle system during `ArborLayour.run()`. Sorry for the incomplete example, in [this jsFiddle](http://jsfiddle.net/7m89p6uL/1/) I added a position for the node that is locked, i.e. the first node above is now defined like this `{ data: { id: 'n1', name: 'n1', size: 50}, position: {x: 0, y: 0} }`. So I hope I didn't misunderstand you, but the problem still shows up for me, even with a position provided.

**Comment by maxkfranz** [comment]
For some reason, the arbor `fromScreen()` call fails with that particular config.  I'm against patching arbor itself to behave correctly, since the authors don't accept PRs.  I've just added an extra null check on our side as a workaround.

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-6649ed0e00-1439400173334.zip

**Comment by tomka** [comment]
Thanks a lot! This fixes this issue for me. The `fromScreen()` call fails due to `_bounds` not being set, returning `undefined`, like explained in the initial post.
