### ISSUE TITLE
Declarative Graph Manipulation

### ISSUE THREAD

**Issue by OAGr** [cytoscape/cytoscape.js#1040]
I've been working to use cytoscape in a React application. In React I have one component that handles the graph, but this has created issues.  React views are declarative, but with cytoscape, individual changes need to be made to modify and move different nodes.

It would be really useful if there were a ``cy.update()`` command that would take in an array of nodes & edges (possibly with their positions) and figure out the changes needed to get there, and then perform those changes.  Kind of a shadow-dom equivalent, if you will. 

I've implemented a basic system for doing delta changes [here](https://github.com/OAGr/guesstimate/blob/3a97afb32e19efb2c0937a6ee4a07f796905bbbe/src/lib/components/cytoscape.jsx).  I use it [here](https://github.com/OAGr/guesstimate/blob/master/src/components/repo_editor/subcomponents/graph_pane.jsx)

It's in a react component that is close to being reusable by others.  It uses the jsondiffpatch library.

**Comment by maxkfranz** [comment]
This looks really interesting.  It would be great to have your React module as a separate package that we could link to on js.cytoscape.org.

It may be nice to have an `ele.json( obj )` API so you can set/change an existing element's state based on a JSON object (same format or subset of `ele.json()`).

The same could hold true for `cy.json( obj )`.  This one would take into account global state like pan/zoom and things like added/removed elements, with modified elements being delegated to `ele.json( obj )`.

It may also be nice to be able to smoothly transition between states using animation, rather than discrete/jumpy state changes -- though that would be more of a niche feature I think.

Does that make sense?

**Comment by maxkfranz** [comment]
Alternatively, it would be about that same cost to do this:

```js
cy.batch(function(){
  cy.elements().remove();
  cy.add( elesJsonForNewState );
});
```

The downside is you lose elements references and the possibility of smooth transitions, etc.

**Comment by OAGr** [comment]
I didn't realize that ``batch`` worked that way.  If it does, that would be a declarative way, assuming that it wouldn't result in a quick flash where everything disappears.  If that does work, I could imagine even making the function ``cy.json(obj)`` just do that.

I think that animations would be cool, but practically, may not be that important.  In my own application only one node is added/removed/moved at a time, and that's typically done by the user, so no external movements are necessary.

Making a react component with that in place is not too hard.  I'll look into making a separate module (agree it should probably be a separate npm package).

**Comment by maxkfranz** [comment]
The `batch()` option is simpler, but it's generally more limited.  It could also be more expensive in cases where you need lots of small state changes in succession.

I would imagine the `cy.json( obj )` etc APIs to do diff-style changes with corresponding emitted events -- whereas the `batch()` option is less flexible and just replaces all elements on every state change.

**Comment by OAGr** [comment]
Got it, and agreed. I think my diff algorithm may be a decent prototype, but it's probably a subset of what would be necessary.

**Comment by maxkfranz** [comment]
@OAGr  It looks like `ele.json( obj )` would work fine for setting/diffing elements.  `cy.json( obj )` looks like it would be too expensive to be practical for your usecase.  See https://github.com/cytoscape/cytoscape.js/issues/1042#issuecomment-133547903

**Comment by maxkfranz** [comment]
@OAGr It would work if you specified only `cy.json({ elements: ... })`, but specifying `style` would be prohibitively expensive, for example.  What do you think?
