### ISSUE TITLE
vee arrow shape

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1054]
![screen shot 2015-08-25 at 3 09 50 pm](https://cloud.githubusercontent.com/assets/989043/9476573/59c6933e-4b3b-11e5-9dcb-4aedcdf6aa91.png)

**Comment by maxkfranz** [comment]
Implementation of https://github.com/cytoscape/cytoscape.js/pull/1020 that seems to be a bit more flexible for large edge widths etc

**Comment by kompiro** [comment]
Thank you!
