### ISSUE TITLE
Transitions can exponentially speed up with style property caching

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1057]

**Comment by tangevin** [comment]
I asked the question about this on stackoverflow. It looks like this fixed it when making a node larger, but when making a node smaller again it is almost instant. Playing around with it a little, it looks like the node jumps back to the original size, and then animates to the correct size. I updated my original [fiddle](http://jsfiddle.net/5wLmfa5y/1/) with an example.

**Comment by maxkfranz** [comment]
@tangevin Try this, and let me know

Snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-659e852006-1441839611536.zip

**Comment by tangevin** [comment]
That appears to work as expected. Thanks.

**Comment by maxkfranz** [comment]
Great; closing
