### ISSUE TITLE
Shift + click to select multiple elements not working as of v2.4.7

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js#1067]
Hi, I recently updated my cytoscape.js library version to 2.4.<b>7</b> and suddenly the feature to use <b>Shift+click</b> to <b><i>select multiple elements</i></b> has stopped working. I had <i>disabled</i> <b>box</b> selection to allow dragging the entire graph container via the drag event instead of selecting multiple elements, which was instead done via Shift + click.

Kindly let me know if the feature is not available anymore.

**Comment by maxkfranz** [comment]
The demos are using 2.4.7 and shift+click works fine there; e.g. http://js.cytoscape.org/demos/2ebdc40f1c2540de6cf0/

**Comment by maxkfranz** [comment]
Closing for now as this is unreproducible

**Comment by AjitPS** [comment]
Hi Max, Apologies for the delayed response. I noticed that it's working in the demos. It was working fine for me as well, up to the previous version of cytoscapeJS.
I'll look into why it's failing now, tomorrow.
