### ISSUE TITLE
Selectors containing numbers represented using scientific notation not supported

### ISSUE THREAD

**Issue by DriesVanDaele** [cytoscape/cytoscape.js#1070]
I'm not certain if this qualifies as an 'issue', but I've noticed that the numbers used in selectors aren't allowed to be written in scientific notation, and this is not mentioned in the documentation.

This is somewhat annoying, since JavaScript defaults to scientific notation when writing small/large numbers as strings.

I've modified one of the examples to illustrate this: http://jsbin.com/kipicufehe/1/edit?js,console,output
I added an attribute for the nodes and used it in the following call:
```
    var threshold = 0.0000002;
    cy.remove(cy.filter('node[value < ' + threshold + ']'));
```
which throws an error, since the value associated with threshold gets rewritten to 2e-7 in the resulting String. I'm currently avoiding this error by rewriting these numbers to decimals according to http://stackoverflow.com/questions/16139452/how-to-convert-big-negative-scientific-notation-number-into-decimal-notation-str but that seems like a rather messy way to resolve this.

Kind regards,
Dries

**Comment by maxkfranz** [comment]
Note : Only seems to affect negative exponents, e.g. 2e-7 doesn't work but 2e7 does work

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-507bfa1237-1441744305034.zip
