### ISSUE TITLE
Arbor layout doesn't respect position of locked nodes

### ISSUE THREAD

**Issue by tomka** [cytoscape/cytoscape.js#1072]
As discussed in #1031, the arbor layout can't handle locked nodes very well. It doesn't crash anymore when nodes are locked (thanks to a fix by @maxkfranz), but will still not respect their position. In my opinion the the reason for this is still the one I supplied with #1031: Essentially, `fromScreen()` of the particle system of `arbor.js` won't work properly (returns `undefined`) if there are no nodes in it. Maybe this could be worked around (to not change `arbor.js`) by adding a bogus node first, let the particle system calculate its bounds and remove it again after adding all actual nodes.

This [jsFiddle](http://jsfiddle.net/xyduj693/4/) shows the problem. This is the relevant code to reproduce :

```
$('#cy').cytoscape({
  ready: function(){
      var cy = this;
      var elements = {
        nodes: [
          { data: { id: 'n1', name: 'n1', size: 50},
            position: {x: 0, y: 0} },
          { data: { id: 'n2', name: 'n2', size: 50} },
          { data: { id: 'n3', name: 'n3', size: 50} },   
        ],
        edges: [
          { data: { source: 'n1', target: 'n2' } }
        ]
      };
      
      // Add all nodes and edges
      cy.add(elements);

      // Lock node 1 to its initial position, (0,0)
      cy.nodes('#n1').lock();

      // The generated layout won't respect the lock on node 1
      cy.layout({
      	name: 'arbor'   
      });
  }
});
```

**Comment by maxkfranz** [comment]
Not reproducible on master/2.4.7

Have you looked at `cy.$('#n1').position()`?  It's not moved.

Have you taken viewport manipulations into account? Have you tried `fit: false`?

**Comment by tomka** [comment]
Indeed, node one's position isn't changed when checked with `cy.$('#n1').position()`. I just expected that node `n1` would end up at the same visual position with every run. Now this is exactly what happens with `fit: false`. Thanks for the pointer.

However, when I assign a position to every node, I'd expect their relative position to stay the same over multiple layout calls. This doesn't seem to happen, neither with `fit: false` nor with `fit: true`. I've created an updated  [jsFiddle](http://jsfiddle.net/xyduj693/5/) that gives a position to every node (and uses v2.4.7):

```
nodes: [
          { data: { id: 'n1', name: 'n1', size: 50},
            position: {x: 0, y: 0} },
          { data: { id: 'n2', name: 'n2', size: 50},
          	position: {x: 100, y: 100} },
          { data: { id: 'n3', name: 'n3', size: 50},
            position: {x: 0, y: 100} }
        ],
```

While the visual representation is different with every run, I can retrieve the initial coordinates with `cy.$('#n1').position()` (and similar calls for the other nodes) when `fit: false`. With `fit: true` the initial locked node's position is not respected at all. With `fit: false`, the retrieved positions are correct, but don't match what is displayed.

**Comment by maxkfranz** [comment]
Please note the difference between a model position and a rendered position as indicated in the docs: http://js.cytoscape.org/#notation/position

In your example, everything is working as expected.  In general, you can't expect a force layout to give deterministic results.  That will never certainly happen for Arbor since the authors have abandoned the lib (and Arbor isn't a very good force layout anyway; it's better than only Springy and only in certain cases).  

Neither can you expect that fitting the graph won't change the position of nodes relative to the viewport -- that would be contradictory for any graph but an already fitted one.

Cola tends to give more deterministic results.

**Comment by tomka** [comment]
Thanks for your input on this. I am sorry if discussion around Arbor layout isn't going to change much and I don't want to steal time from you. So please feel free to ignore my thoughts below and I come up with a solution for the problem on our side.

Yes, I read about the distinction of model position and rendered position. As I understood it, rendered positions are model positions with zoom and pan added (which could be introduced by e.g. `fit: true` or user action). This, however, would mean that rendered nodes would still maintain the same relative positions to each other like they do with their model position (ignoring the zoom here). So at least the direction from one node to another should be the same. This doesn't seem to hold with Arbor layout, though. To make more clear what I am referring to, I created to example image with the last jsFiddle (two different runs with `fit: false`):

![cy-arbor-layout-no-fit-1](https://cloud.githubusercontent.com/assets/112226/9764251/0e0edc6a-56dc-11e5-8e93-ae41072d23d6.png)
![cy-arbor-layout-no-fit-2](https://cloud.githubusercontent.com/assets/112226/9764250/0e0db704-56dc-11e5-9b1d-f2073c5ec98f.png)

The coordinates printed are the model positions (retrieved with `cy.$('#n1').position()` after each run). They remain constant, which is expected due to locking, but the output has not only zoom and pan added to them, their relative position to each other is completely different (except for n1).

> In general, you can't expect a force layout to give deterministic results

So are you saying that all force based layouts can't deal with locked nodes in a deterministic way and will always _possibly_ shuffle them around according to their model? If so, I might have been mistaken all along, because I thought locked nodes can't be moved no matter what (again, of course they can be zoomed/panned for rendering).

> Neither can you expect that fitting the graph won't change the rendered position of nodes

Of course not, this makes perfect sense.

> Cola tends to give more deterministic results.

Indeed, cola respects the locked nodes and they remain at their locked position. With `fit: true` only zoom and pan is applied (which is expected). And cola produces the result I would have expected with all nodes locked in Arbor layout:

![cy-cola-layout-no-fit-1](https://cloud.githubusercontent.com/assets/112226/9764520/8fe6dfe8-56dd-11e5-8de1-a5718703dba2.png)

**Comment by maxkfranz** [comment]
A force layout operates with a physics simulation.  The physics simulations use (pseudo)random number generation for things like initial node placement (e.g. `randomize: true`).  When those random numbers are used, the results are nondeterministic.  

Where psuedorandom number generators are used, you could make the results deterministic by controlling the seed.  That's not possible with Arbor.  I think Cola only uses random numbers for `randomize: true`, so it's probably a better layout to use.  It's also an active project, so it's probably possible to also add seed config by a PR or feature request.

A locked node has an immutable position, e.g. demo with locked nodes: http://jsfiddle.net/wvnoz1xm/1/  Arbor doesn't seem to move locked nodes -- as the `.position()` etc APIs wouldn't allow for it.

**Comment by tomka** [comment]
Indeed, Arbor doesn't move locked nodes. Thanks for your example. It made my mistake obvious: I locked only node n1 instead of all of them (which is what I meant to do). Sorry for the trouble. I didn't intend to have a deterministic layout with unlocked nodes, but thanks for the details.

Still, the discrepancy between model position and render position in my example above feels somewhat strange, because I would have expected the layout positions to be propagated back to the model.

Anyway, I now agree that this Github issue is invalid and Arbor does respect locked nodes.

**Comment by maxkfranz** [comment]
In general, I'd avoid Arbor.  Cola and CoSE are both much better.  CoSE is getting threading support in 2.5, and there's a separate CoSE2 implementation that provides even better layouts for compounds.
