### ISSUE TITLE
Improved compound lock/grab/drag behaviour

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1074]
- Revise compound grab/lock behaviour so it's easier to use
- Revise conflicts depending on state

**Comment by maxkfranz** [comment]
https://github.com/cytoscape/cytoscape.js/commit/6913921848605d9b513d9980f92206e38d843b2e

**Comment by SrMouraSilva** [comment]
I saw http://stackoverflow.com/a/32406098/1524997

Exists another mode to "lock the position of a cytoscape.js node within its parent node" without using

```javascript
cy.nodes().nonorphans()
  .on('grab', function(){ this.ungrabify(); })
  .on('free', function(){ this.grabify(); })
;
```

**Comment by maxkfranz** [comment]
You can either be granular with code, or you can turn all events off in style with `events: no`

**Comment by gopib23** [comment]
How to disable only drag event to child node. because i need tab event to the child node and also parent node must be move when drag on child node. please help me how to handle this Situation. `events: no` disable all events in child node so tab event not working.
