### ISSUE TITLE
Sugiyama's algorithm support for layered graph drawing

### ISSUE THREAD

**Issue by thoorp** [cytoscape/cytoscape.js#1075]
We tried cytoscape for rendering compound/cluster network diagrams like graphviz. 
example: http://www.graphviz.org/content/cluster

However, the end result is somewhat lagging and I believe it may have to do with the rendering algorithm (Sugiyama vs ?). 

Hoping someone in the core team can give an idea if there is more in the pipeline for compound diagrams.

**Comment by maxkfranz** [comment]
Rendering is already pretty much as optimised as it can be -- even for compound graphs.

There are two bottlenecks in general:

(1) Drawing, i.e. blitting, stroking, filling, etc.

(2) Calculating control points

For (1), there is nothing that can be done to make drawing to a HTML5 canvas faster.  The `Context2D` operations are taking up almost all of each frame's time.  You are comparing a desktop app that is presumably using Java's `Graphics2D` class to a JS library using web rendering technologies.  Apples and oranges.

The only way to make (1) faster using canvas is to push the browser vendors to improve their performance for 2D rendering in canvas.  2.5 will make it easier to add new renderers to the lib, so it may be possible to experiment with WebGL.  I'm not entirely convinced that using WebGL would make a big performance difference for complex 2D scenes, but it's probably something we'll be experimenting with anyway.

For (2), see https://github.com/cytoscape/cytoscape.js/issues/1065

**Comment by maxkfranz** [comment]
If you're looking for *layout* rather than rendering, you may be interested in Dagre: http://js.cytoscape.org/#layouts/dagre

The [Sugiyama paper](https://www.dropbox.com/s/lveora4u6o0ccbt/04308636.pdf?dl=0) describes a similar result as Dagre
