### ISSUE TITLE
Cytoscape ignores Dagre edge points

### ISSUE THREAD

**Issue by danielpes** [cytoscape/cytoscape.js#1078]
The dagre.js code calculates not only the positions for all the nodes in the graph but also a various number of control points for the edges so that they can avoid obstacles (an example can bee seen [here](https://github.com/cpettitt/dagre/wiki#an-example-layout)). 

However, it seems that the cytoscape code is ignoring these points since I noticed that only the nodes positions are obtained from the layout generated by dagre.js. 

Due to this behavior, some complex graphs plotted using cytoscape end with edges crossing obstacles (nodes), instead of avoiding them. A simple example is the graph linked [here](http://cpettitt.github.io/project/dagre-d3/latest/demo/interactive-demo.html?graph=digraph%20%7B%0Astart%20-%3E%20node0%0Anode4%20-%3E%20end%0Anode0%20-%3E%20node2%0Anode0%20-%3E%20node1%0Anode1%20-%3E%20node2%0Anode2%20-%3E%20node3%0Anode2%20-%3E%20node4%0Anode4%20-%3E%20node2%0Anode3%20-%3E%20node5%0A%7D). The result using cytoscape is shown in the following image:

![dagre](https://cloud.githubusercontent.com/assets/1709357/9747769/1dfd5128-5656-11e5-8512-e51377b897eb.PNG)

**Comment by maxkfranz** [comment]
The layout could set a `scratch` value for each edge, and you'd have to configure your stylesheet to use the `scratch` value.

However, an edge supports a single control point.  The Dagre "control points" aren't really bezier control points, but rather a definition of a series of line segments.  An [edge bend](https://github.com/cytoscape/cytoscape.js/issues/359) may help, but I'm not sure if they'll support more than one point.

**Comment by aschilling** [comment]
Hi Daniel,
I am struggeling with the same problem as you. Have you already found a solution to your problem?

**Comment by maxkfranz** [comment]
This is an extension issue, not a lib issue

Closing
