### ISSUE TITLE
Merge nodes ?

### ISSUE THREAD

**Issue by clemsos** [cytoscape/cytoscape.js#1089]
Hi, is there a specific way to merge nodes in Cytoscape.js ? 

Mostly, I would like to

* start drag a node
* release the node on the top of another node (hit test?) 
* merge both (after some confirmation?)

Any common approach or functions known to achieve this ?
Thanks !

**Comment by maxkfranz** [comment]
You could check for bounding box overlap on nodes.  The comparison of bounding boxes is straightforward and inexpensive.

To merge, you could remove one of the nodes and merge/put data from the other node (depending on how the semantics of merging works in your case).

**Comment by maxkfranz** [comment]
Closing for now

**Comment by clemsos** [comment]
Thanks. I was just working on a solution on this today. Draft here https://github.com/topogram/topogram-client/commit/6460b5e84225b6a9ea207ec0c9558020ac0dce45#diff-20da5320832913eb2fa0ae5ac34984eaR235
