### ISSUE TITLE
Style doesn't apply in Ember component

### ISSUE THREAD

**Issue by yaqwsx** [cytoscape/cytoscape.js#1090]
Hello,
I am trying to use cytoscape.js in my Ember app and I am observing weird behavior. I have created Ember Component for the graph. When I try to change the style, it makes no effect. However when I make transition to different route in Ember and than back, style magically appears.

Am I doing something wrong or is it a bug?

Here's the full description: http://stackoverflow.com/questions/32609588/cytoscape-js-style-doesnt-apply

**Comment by yaqwsx** [comment]
No bug here, just my silly mistake. Asynchronously loaded model, which determines the style of the node wasn't loaded when the nodes were pushed into the graph.

**Comment by maxkfranz** [comment]
OK, closing then.

All the best with your project
