### ISSUE TITLE
API revisions for 3.0

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1092]
Improvements to the API that break backwards compatibility (sorted by most-to-least significant amount of changes needed to update your app):

- Functions with the `function(i, ele)` signature become `function(ele, i)` etc, e.g. `eles.each()` #1531
 - `eles.bfs()`
 - `eles.dfs()`
 - `eles.each()`
 - `eles.filter()`
 - `eles.positions()`
 - `eles.layoutPositions()`
- `cy.layout()` and `eles.layout()` return the layout rather than chaining the calling object #1533
- Callbacks like `weight` should not set `this` #1535
 - `eles.each()`
 - `eles.filter()`
 - `eles.positions()`
 - `eles.layoutPositions()`
 - `eles.bfs()`
 - `eles.dfs()`
 - `eles.dijkstra()`
 - `eles.aStar()`
 - `eles.bellmanFord()`
 - `eles.kruskal()`
 - `eles.floydWarshall()`
 - `eles.pageRank()`
 - `eles.closenessCentrality()` & `eles.closenessCentralityNormalized()`
 - `eles.betweennessCentrality()` & `eles.betweennessCentralityNormalized()`
 - `eles.degreeCentrality()` & `eles.degreeCentralityNormalized()`
 - `concentric` layout (already deprecated)
 - `cose` layout (already deprecated)
- Remove `cy` prefix on event fields, because we don't merge with the original event (as left open); e.g. `cyTarget` => `target` #1537 
- Clarify interactivity and visibility #1544
- Remove `:touch` selector -- not reliable as some desktop browsers now implement touch APIs without hardware support #1540
- Replace `cy.onRender()` and `cy.offRender()` with a `render` event #1541
- `grab` event should happen on nodes being dragged; use `grabon` for differentiating which element the cursor or finger holds #1545
- Remove jQuery plugin (still allow passing a jQuery element to init, but don't allow `$('#cy-div').cytoscape(...)` syntax) #1539
- Remove the already deprecated `cy.load()` #1534
- Remove deprecated `layout()` and `scratch()` mapper support in code #1536
- Remove deprecated `cy.initrender()` #1538

**Comment by maxkfranz** [comment]
A version of Cytoscape.js should be published in 2.x that only adds warnings for these API changes.  That way, a dev can use 2.x with the warning version, fix all his warnings in a separate branch, and then update to 3.0

**Comment by mj3cheun** [comment]
@maxkfranz Did you remove the Thread method from the cytoscape.js object? I am getting `cytoscape.Thread` returning a function in 2.x but returning undefined in 3.x.

**Comment by maxkfranz** [comment]
@mj3cheun Yes, you should `require('weaverjs').Thread` in the extension instead

**Comment by mj3cheun** [comment]
Ok thanks
