### ISSUE TITLE
Is it possible to split the export into smaller images

### ISSUE THREAD

**Issue by ktei** [cytoscape/cytoscape.js#1095]
I have a problem at the moment that if the export image is too big, then its base64 data size will exceed the browser limit; also if it's too big, then when backend parses base64 to image file, memory overflow exception will be thrown.

So I'm thinking maybe I could split the export image into smaller images first and pass an array of base64 to backend and then let backend stitch them together.

Is it possible to have a method like this: `png({x: 100, y: 300, width: 300, height: 300})`? So `x` and `y` is actually the cropping starting point:
<img width="322" alt="capture" src="https://cloud.githubusercontent.com/assets/2195250/9990083/7aeeb6d8-60a1-11e5-958e-dbb5514bfa90.PNG">

In the screenshot above, the black rectangle is the full canvas and the brown rectangle is the parameters we pass in.

I think I will need to change `bufferCanvasImage` but I'm not sure how to do it properly.

Many thanks @maxkfranz

**Comment by maxkfranz** [comment]
You can either pan the graph around in stages and then call `cy.png({ full: false })` or you can use `cy.jpg()` which has a much lower file size.

**Comment by ktei** [comment]
@maxkfranz Thank you. I think `pan` will do it.
