### ISSUE TITLE
Is it possible to create custom widgets for nodes?

### ISSUE THREAD

**Issue by srg985** [cytoscape/cytoscape.js#1106]
I want to make graph widt different node widgets for each node depending of node type. Each widget should contain some custom visualizarions and control elements (sub-buttons, scrollbars, indicators etc). Is it possible to do such thing using standard cytoscape or I must create my own renderer or plugin?

**Comment by maxkfranz** [comment]
Cytoscape.js allows for rendering the graph itself.  If you want to display non-graph data, you can do so with your code and/or an external library.  You have the option to make the code more terse and reusable if you put it in an extension.

The qtip extension is a good example: https://github.com/cytoscape/cytoscape.js-qtip
