### ISSUE TITLE
Detect when panning or viewport has ended

### ISSUE THREAD

**Issue by jenicar** [cytoscape/cytoscape.js#1111]
Is it possible to detect when the viewport has ended?
I can access the viewport as below but want to know when the user has stopped panning/zooming 

This is so I can redraw my qtips as qtips currently don't update position as you pan when they're visible (I raised a separate issue for this - https://github.com/cytoscape/cytoscape.js-qtip/issues/8) 

tm.cy.on('viewport', function (evt) {
    console.log(evt)
});

**Comment by maxkfranz** [comment]
I don't think it makes sense for the library itself to give you events like `panstop` because panning and zooming are not always continuous events and it depends on how you use the API.

For simple user events, you can just debounce, i.e.:

```js
var threshold = 500; // delta t in ms for grouping events together
cy.on('viewport', _.debounce(function(){
  console.log('viewport done');
}, threshold));
```

See https://lodash.com/docs#debounce
