### ISSUE TITLE
Bug in pageRank() with dampingFactor use

### ISSUE THREAD

**Issue by ascholerChemeketa** [cytoscape/cytoscape.js#1113]
collection-algorithms2.js has a bug in reading the dampingFactor property of the options. Relevant code starts on line 879:
```
879      if (options != null &&
880       options.dampingfactor != null) {
881       var dampingFactor = options.dampingFactor;
882      } else {
883        var dampingFactor = 0.8; // Default damping factor
884      }
```
**options.dampingfactor** on 880 should be **options.dampingFactor**
Existing code ignores any attempt to set dampingFactor unless you also set dampingfactor.

**Comment by maxkfranz** [comment]
Thanks! I've pushed the changed.

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-33f822d189-1443733628847.zip
