### ISSUE TITLE
breadthfirst layout

### ISSUE THREAD

**Issue by redreamality** [cytoscape/cytoscape.js#1119]
when `circle: 'False'`, the default layout is from top to bottom, is it possible to support the feature of left-right, bottom-top   etc.

THX

**Comment by maxkfranz** [comment]
Thanks for your feedback.

The `breadthfirst` layout is meant to be a very simple hierarchical layout.  If you want more customisation, I suggest using the `dagre` layout which supports many more options, including LTR etc.
