### ISSUE TITLE
[bug report] the dfs path with the wrong order?

### ISSUE THREAD

**Issue by redreamality** [cytoscape/cytoscape.js#1122]
see the following demo, only changed the bfs demo into dfs

http://jsbin.com/kaviza/1/edit?js,output

**Comment by maxkfranz** [comment]
Thanks for the example

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-941cdc7567-1444756756259.zip
