### ISSUE TITLE
Hide edges based on distance

### ISSUE THREAD

**Issue by wiwie** [cytoscape/cytoscape.js#1124]
I haven't found a corresponding feature yet.

I am working with huge graphs and would like a style setting that allows me to hide edges if zoomed out a lot, i.e. if the distance to an edge is larger than a threshold, do not render it.

Is it already available or is it possible/reasonable to implement?

**Comment by maxkfranz** [comment]
App level features like that are up to the developer to implement.  It's very straightforward to implement with `cy.on('zoom')` and `cy.zoom()`.  You'll have to experiment with thresholds, debouncing, etc.
