### ISSUE TITLE
selector strings with multiple classes get corrupted in cy.json() output

### ISSUE THREAD

**Issue by smpaley** [cytoscape/cytoscape.js#1142]
If my stylesheet has a selector listing multiple classes, e.g. ".class1.class2", all works fine for the most part: as I would expect, only nodes. that have both classes get the specified styling.  However, when I call cy.json() on the graph, in place of that selector, the output instead contains ".class1.class1".

I verified this by extending your style demo (http://jsbin.com/gist/b7c65115947d9e0e8ec8?js,console,output), adding a single selector:

.selector('.faded.black')
      .css({'background-color':'black'})

The result after invoking cy.json() at the console contained the following instead:

{
  selector: ".faded.faded",
  style: [object Object] {
    background-color: "black"
  }

**Comment by maxkfranz** [comment]
This will make it into 2.5 but not 2.4, as I'm planning to release tomorrow

**Comment by smpaley** [comment]
Thanks!
