### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'prototype' of undefined(…)

### ISSUE THREAD

**Issue by mahe8116** [cytoscape/cytoscape.js#1147]
Firstly its an awesome layout extension....it works so perfectly on my local .....

but when I access it with my minified code (not the minified spread layout / cytoscape). It gives me the below error.

Uncaught (in promise) TypeError: Cannot read property 'prototype' of undefined(…)
protoreq @ cytoscape.js:7070
fnAsRequire @ cytoscape.js:7121
(anonymous function) @ cytoscape.js:7195
$$.Promise.then._p.running @ cytoscape.js:7194
$$.fn.thread.run @ cytoscape.js:7185
SpreadLayout.run @ layout.js:266
$$.fn.core.layout @ cytoscape.js:8667
callback @ cytoscape.js:8238

My minified code works with breadthfirst layout fine.

**Comment by maxkfranz** [comment]
The library (i.e. this repo) does not include that layout.  If you have an issue with a separate extension layout, please file your issues with that extension: https://github.com/cytoscape/cytoscape.js-spread/issues

Thanks
