### ISSUE TITLE
Cytoscape Crashing on Safari

### ISSUE THREAD

**Issue by chriscr** [cytoscape/cytoscape.js#1148]
I have a graph that works in FireFox, IE, and Chrome, but crashes in Safari. The error that shows up in Safari is

TypeError: 'undefined' is not a function (evaluating 's.setLineDash([])')

Here are the steps
0. Running cytoscape.js 2.3.3

1. I run my nodes through a layout extension and based on my console statements it runs all the way through with no errors
======== START 3-Column Layout ========
show center node=n1
show node=n2
show node=n3
show node=n4
3CL Execution Time =28
======== END 3-Column Layout ========

2. I run the nodes through some calculations that are application specific, and it runs all the way through with no errors
========START recalculateGraph()========
  ====================START buildEDepths()====================
  EDEPTH Execution Time =6
  ====================END buildEDepths()====================
  ========START proCondShading()========
  PRO-CON DEPTH=0 
  PRO-CON DEPTH=1 
  PRO-CON DEPTH=2 
  PRO-CON Execution Time =5
  ========END proCondShading()========
RECALC Execution Time =29
========END recalculateGraph()========

3. Basically at this point all my positioning and app specific calculations are done, and it looks like it is crapping out on the rendering.

**Comment by maxkfranz** [comment]
(1) You're using an old version of Safari.  You're not using Safari on Windows that Apple abandoned long ago, right?  `setLineDash()` is supported in any modern version of Safari.

(2) You're using an old version of the library.  Newer versions have had a check for this for a long time: https://github.com/cytoscape/cytoscape.js/blob/v2.5.0/src/extensions/renderer/canvas/drawing-edges.js#L95  2.3.3 is not even the latest version in the 2.3 line (2.3.16).

Address (1) or (2).  If you don't want to upgrade the lib, you'll have to fork an old version from its tag and patch yourself.

**Comment by chriscr** [comment]
Thank you.
I am using safari 5.1.7.

I am afraid to upgrade to cytoscape 2.5.0.
I am using several layout extensions and basically use the following
"template", but it seems as though this extension is no longer used in
2.5.0.
Can you direct me to the latest layout extension template.
Chris


// this class is adding a new layout using Cytoscape extension API
;
(function($$) {
    'use strict';

    // default layout options
    var defaults = {
        ready : function() {
        }, // on layoutready
        stop : function() {
        } // on layoutstop
    };

    // constructor
    // options : object containing layout options
    function ThreeColumnLayout(options) {
        this.options = $$.util.extend(true, {}, defaults, options);
    }

    // runs the layout
    ThreeColumnLayout.prototype.run = function() {

        var options = this.options;
        var eles = options.eles; // elements to consider in the layout
        var layout = this;

        // cy is automatically populated for us in the constructor
        var cy = options.cy; // jshint ignore:line

        layout.trigger('layoutstart');


        //code for calculating 3 column layout positions for nodes


        // trigger layoutready when each node has had its position set at
least
        // once
        layout.one('layoutready', options.ready);
        layout.trigger('layoutready');

        if (options.fit) {
            cy.fit(options.padding);
            cy.center();
        }

        // trigger layoutstop when the layout stops (e.g. finishes)
        layout.one('layoutstop', options.stop);
        layout.trigger('layoutstop');

        return this; // chaining
    };

    // called on continuous layouts to stop them before they finish
    //ThreeColumnLayout.prototype.stop = function(){ return this; //
chaining };
    ThreeColumnLayout.prototype.stop = function() {
        var options = this.options;
        var cy = options.cy;
        cy.one('layoutstop', options.stop);
        cy.trigger('layoutstop');
    };

    // register the layout
    $$('layout', 'trhree-column-layout', ThreeColumnLayout);

})(cytoscape);

**Comment by maxkfranz** [comment]
Old extensions should still work as long as they're not referencing private data.

This is the extension generator: https://github.com/cytoscape/slush-cytoscape-extension

**Comment by chriscr** [comment]
When I popped in cytoscape.js and cytoscape.min.js for version 2.5.0 it did
not like the $$.util in firefox now.

    function TruthSift3ColumnLayout(options) {
        this.options = $$.util.extend(true, {}, defaults, options);
    }

I get the error
TypeError: $$.util is undefined three-column-layout.js:22:3
TypeError: $$.is is undefined

**Comment by maxkfranz** [comment]
Those are both private under the `cytoscape` object.  You can implemented them yourself easily or use their counterparts in lodash.
