### ISSUE TITLE
Avoid zoom response for mouse-wheel event?

### ISSUE THREAD

**Issue by xiangshengyun** [cytoscape/cytoscape.js#1150]
By default, zoom response is triggered by mouse-wheel event, is it possible to avoid this ? I just want to add some elements to fixed graph for mouse-wheel event. Thanks.
And how can I distinguish zoom-in or zoom out?

**Comment by maxkfranz** [comment]
http://js.cytoscape.org/#cy.userZoomingEnabled

**Comment by felicity-iz** [comment]
cy.userZoomingEnabled(false) doesn't work.
