### ISSUE TITLE
Cytoscape 2.5.0 Compound (parent) nodes not draggable after adding child node.

### ISSUE THREAD

**Issue by Lenndev** [cytoscape/cytoscape.js#1151]
Hi there,

After updating Cytoscape.js from 2.4.9 to 2.5.0, compound nodes (parent) seem to be locked.
When dragging the parent node, the child node moves instead of the parent node. The selection is visible on the parent node, not on the child. 

It seems to happen, only to nodes that are added after the creation of cytoscape canvas.
when cy.elements.nodes is specified in the config, the compound node is draggable.

The child node is added in a custom extension after adding the node (parent) to cytoscape.
the position of te child is {x:parentX -20 y:parentY}

(I'm trying to create a compound node where the child node is set to a specific position on creation and not draggable after creation. so it will move when the parent node is moved. (using the child node as a menu (item)))

**Comment by maxkfranz** [comment]
I've confirmed that both child and parent nodes are draggable after adding child nodes.  You may have an issue with your code.  I'm going to close this for now.  

Re-open with a demo of your issue on codepen/jsbin if you like.

**Comment by Lenndev** [comment]
Hi Maxkfranz
Sorry for the slow response and sorry/happy to hear you cannot recreate the bug.
Since I do not have a codepen/jsbin account I've placed the code underneath  that is responsible for  adding a node and adding a deletebtn/childnode next to it.

function addNode(data) {
		var x = 100,
			y = 100,
			gewicht = 75;
	
		if (data && typeof(data) == 'object') {

			if (data.hasOwnProperty('x')) {
				x = data.x;

			}
			if (data.hasOwnProperty('y')) {
				y = data.y;

			}
			if (data.hasOwnProperty('weight')) {
				weight= data.weight;
			}
		}

		//add node at chosen location.
		var node = {
			group: "nodes",
			data: {weight: weight, id: 'n' + nodeCounter, type: $scope.selectedNodeType, label: 'hallow'},
			position: {x: x, y: y},
			classes: selectedNodeType
		};

		cy.add(node).afterAdd().addDeleteBtn();
		nodeCounter++;

		/**
		 * reset current drawtool -- some css stuff
		 */
		currentTool.removeClass('selected');
		presseddrawtool = null;
		currentTool = null;
		selectedNodeType = null;
	}

cytoscape('collection', 'addDeleteBtn', function () {
			var parentNode = this;
//get position parent node
			var ppos = parentNode.position(),
				px = ppos.x,
				py = ppos.y;
			var delbtnId = 'delbtn_' + parentNode.id();
			var deletebtn = {
				group: 'nodes',
				data: {
					id: delbtnId,
					weight: 50,
					parent: parentNode.id()
				},
				position: {x: px - 50, y: py},
				classes: 'deleteBtn'
			};
                       //save deletebtn in parentNode data
			parentNode.data('deleteBtn', deletebtn);
//time to add the deletebtn to the canvas
			cy.add(deletebtn);
			return this;//chainable
		});

		//after deleteBtn is added we set its listeners
		cytoscape('collection', 'afterDeleteBtnAdd', function (parent) {
			var delBtn = this;
			delBtn.hide();
		//delete parent node on deleteBtn.tap();
			delBtn.once('tap', function () {
				parent.remove();
			});

hope you, or any other developer can tell me what mistakes i've made :)
