### ISSUE TITLE
text-shadow, shadow, bezier curves not working

### ISSUE THREAD

**Issue by chriscr** [cytoscape/cytoscape.js#1152]
Max
I am working with cytoscape.js 2.3.3 but am upgrading to 2.5.0.
I am having some issues getting certain stylings to work.  Here are my node and edge stylings. The ones with   //CR  don't work. I have searched but can not find a way to fix them.

I also want to implement gradient backgrounds in the nodes.

$.Simplicio.GraphStyles = [
{
	selector: 'node',
	css: {
		'content': 'data(name)',
		'label': 'data(name)',
		'font-family': 'Arial',
		'font-size': 12,
		'line-height': 1.90,
		//'text-outline-width': 0,
		'text-valign': 'center',
		'color': '#000',
		'background-color': '#aea9a9',
		'width': 'data(width)',
		//'width': 'mapData(weight, 30, 80, 20, 50)',
		'height': 'data(height)',
		//'height': 'mapData(height, 0, 200, 10, 45)',
		'border-color': '#000',
		'border-width': 1,
			
        'text-shadow-blur': 5,  //CR
        'text-shadow-color': '#888',  //CR
        'text-shadow-offset-x': 5,  //CR
        'text-shadow-offset-y': 5,  //CR
        'text-shadow-opacity': 0.5,  //CR

		'shadow-blur': 5,  //CR
		'shadow-color': '#c0c0c0',  //CR
		'shadow-offset-x': 5,  //CR
		'shadow-offset-y': 5,  //CR
		'shadow-opacity': 0.5  //CR
	}
},{
	selector: 'edge',
	css: {
		'width': 1,
		'z-index':0,
                'target-arrow-shape': 'triangle',
                'curve-style': 'bezier'  //CR
	}
}
]

**Comment by maxkfranz** [comment]
The shadow styles may have a bug, but I'm certain bezier edges work fine.  There's even a demo: http://js.cytoscape.org/demos/18504640d9a03c178fff

**Comment by maxkfranz** [comment]
Confirmed shadows working just fine on 2.5: 

![screen shot 2015-11-24 at 12 18 18 pm](https://cloud.githubusercontent.com/assets/989043/11374725/7e59e12c-92a5-11e5-99d8-ee4200efbfdb.png)
