### ISSUE TITLE
Cytoscape 2.5: edge selection seems not working

### ISSUE THREAD

**Issue by ktei** [cytoscape/cytoscape.js#1154]
@maxkfranz  
I used to be able to click on an edge and highlight it. Now after upgrade to 2.5, I can't click an edge to make it selected anymore. However if I use `cy.edges()[0].select()`, the first edge is still selected and highlighted (by my stylesheet).

Just curious: is there anything I'm missing here?
Thank you very much.

**Comment by ktei** [comment]
I found that:
```javascript
if( r.hoverData.dragging ){
            // if panning, don't change selection state
```
If I click on an edge, `dragging` is always true, however I'm not dragging at all. So no selection state is changed in this case.

**Comment by maxkfranz** [comment]
I suspect this may have something to do with your code, because edge selection is working on both desktop and touch for 2.5.0 from my testing.
