### ISSUE TITLE
2.5.0 Changing colors/shapes of nodes not working properly

### ISSUE THREAD

**Issue by sepro** [cytoscape/cytoscape.js#1156]
The code below, that worked perfectly with version 2.4.5, is no longer working. I think it should. The data is loaded from a json file that contains for each node attributes with other colors (same name as attr in the html tag), a button allows users to select the colors they wish to see. 

With version 2.5.0 it will change the colors correct once and then it won't work anymore, same for shapes.

html:
```html
    <li><a href="#" class="cy-node-color" attr="depth_color">Depth</a></li>
    <li><a href="#" class="cy-node-color" attr="family_color">Family</a></li>
    <li><a href="#" class="cy-node-color" attr="neighbors">Neighbors</a></li>
```
javascript:
```javascript
    $('.cy-node-color').click(function() {
        var attr = $( this ).attr( 'attr' );
        cy.nodes().style('background-color', function( ele ){ return ele.data(attr)});
    })
```

**Comment by maxkfranz** [comment]
Not a bug.  A bypass is for a value.  You haven't specified a value.  You've specified a function.

Specify your function in your stylesheet.
