### ISSUE TITLE
Semantic zooming extension

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1157]
Change graph content based on zoom level.  Must be inexpensive, because zoom is a continuous operation.

e.g. http://www.zoompast.org/show_public_tree?tree_id=218

Edit : corrected link ; should be zoompast instead of fedwiki

**Comment by janblok** [comment]
Would the graph really change or element visibility style map to a zoom level?

**Comment by maxkfranz** [comment]
e.g. 

```
cy.semzoom({
  levels: [
    {
      minZoom: 1,
      maxZoom: 2,
      classes: 'foo bar',
      setup: function(){ /* ... */ },
      teardown: function(){ /* ... */ }
    }
  ]
});
```

It would be a mapping of zoom level to classes and/or manual edits.
