### ISSUE TITLE
style text-parts within a label differently

### ISSUE THREAD

**Issue by benjaminaaron** [cytoscape/cytoscape.js#1161]
I found the `text-wrap` option :+1: Now it would be great to have the ability to style parts of the label differently. One line *italic* and another one **bold** for instance. Any chance to make `font-style` that granular?

**Comment by maxkfranz** [comment]
In the shortterm, I don't think that this will be added.  It would quickly become an exercise in reimplementing text DOM rendering in canvas...

**Comment by benjaminaaron** [comment]
Ok thanks Max. Too bad, but understandable.

**Comment by vivekvs1** [comment]
Hi - is it possible now?
