### ISSUE TITLE
Drag event for nodes

### ISSUE THREAD

**Issue by tmullen71** [cytoscape/cytoscape.js#1162]
I posted this over at StackOverflow, but haven't gotten any response. I'm not sure whether it's a feature request, or a bug report, or just me not understanding how to do what I need to do.

I'm looking for an event that fires as a node is being dragged. 'tapdrag' behaves as mouseover, and doesn't fire when the mouse button is down. Is this as designed? I basically want to move a second node when a first node is dragged. 

In the meantime, I tried hacking together something using vmousedown the cy.onRender event, but the only way I could get it to work was to use a 0 timeout, so there's a delay. 

http://stackoverflow.com/questions/33763450/drag-event-for-nodes-in-cytoscape-js

**Comment by maxkfranz** [comment]
The drag event is builtin: http://js.cytoscape.org/#events/collection-events

**Comment by tmullen71** [comment]
Great, thanks!
