### ISSUE TITLE
mapper won't work when modifying style using cy.style(), cy.css()

### ISSUE THREAD

**Issue by DriesVanDaele** [cytoscape/cytoscape.js#1163]
I can't seem to use a mapping (numeric to color) within a style() statement. (Potentially related to https://github.com/cytoscape/cytoscape.js/issues/1156)

The following example illustrates my problem. It's a modification of the Linkout example. I added the 'expression' node attribute, and attempt to trigger a style change on node click.
http://jsbin.com/cesebeteke/1/edit?js,output

I'm aware that the ideal approach would involve stylesheets, but in specific, highly dynamic environments, the flexibility associated with the directly manipulating style attributes is desirable.

Kind regards,
Dries

P.S. for mapData, the documentation lists as an example: 'data(weight, 0, 100, blue, red)' instead of 'mapData(weight, 0, 100, blue, red)'

**Comment by maxkfranz** [comment]
That's explicitly not supported.  It does not make sense to use a mapper and a bypass together.  A bypass is an explicit value override.  A mapping is not an explicit value.

A bypass should be used only in *very exceptional cases*, just like using the `style` attribute in the DOM.

If you require more dynamism, then your *stylesheet* should be more dynamic.  Use custom functions that map to dynamic data in the elements.

http://js.cytoscape.org/#style/mappers
