### ISSUE TITLE
Box selection events

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1166]
Ref : https://github.com/cytoscape/cytoscape.js/issues/1145

On the core:

* `boxstart` : when the box is shown
* `boxend` : when the box is hidden

On the elements:

* `boxselect` : triggered on elements when selected by the box
* `box` : triggered on elements when inside the box on `boxend`

**Comment by maxkfranz** [comment]
TODO docs

**Comment by klysak** [comment]
Hi, maxkfranz! How to determine the selected nodes? Inside callback function i try to find selected nodes by `cy.$("node:selected")` but i get zero-length collection `Collection {length: 0, _private: {…}}`.
