### ISSUE TITLE
Alpha value ignored when using rgba to set background-color of node

### ISSUE THREAD

**Issue by IvanPozdnyakov** [cytoscape/cytoscape.js#1171]
Like the title says I can set the background color of the node using rgba but changing the alpha value produces no difference, using 2.4.9. Looking at the documentation rgba isn't explicitly mentioned so I don't know if it's supported.

*Colours may be specified by name (e.g. red), hex (e.g. #ff0000 or #f00), RGB (e.g. rgb(255, 0, 0)), or HSL (e.g. hsl(0, 100%, 50%)).*

 If not, is there another way to make a node transparent but it's image not, since this is the effect I'm trying to achieve. Setting opacity on the node will just make the background-image transparent as well which is not desired.

**simple handler**

*function onBackgroundImageReaderLoad() {
            saveState();
            var img = event.target.result;
            target.data('Type', "image");
            target.data("backgroundImage", img);
	    target.style("background-image", img);
}*

**stylesheet (reduced to what I think is relevant)**

*.selector('node').css({
        'content' : 'data(name)',
	'padding-left' : 2,
	'padding-right' : 2,
	'font-family' : 'data(LabelSize)',
	'background-image-opacity' : .75,
	'opacity' : 0.75,
	'text-opacity' : 0.75
}).selector('node[Type="image"]').css({
	'shape' : 'rectangle',
	'width' : 'data(Width)',
	'height' : 'data(Height)',
	'color' : 'black',
	'text-valign' : 'center',
	'background-color' : 'rgba(155,155,155,0)',
	'border-color' : 'white',
	'border-style' : 'solid',
	'border-width' : 1
}).selector('node:selected').css({
	'background-color' : 'green',
	'opacity' : 1.0,
	'text-opacity' : 1.0
})*

**Comment by maxkfranz** [comment]
As noted in the docs, each part of the style can be controlled separately w.r.t. opacity.

Use `background-opacity: 0`

**Comment by IvanPozdnyakov** [comment]
Crap... must have scrolled passed that multiple times... Anyways, thanks for the response and awesome library!

**Comment by maxkfranz** [comment]
No worries; good luck with your project
