### ISSUE TITLE
node font-size < 1?

### ISSUE THREAD

**Issue by cytoscapejsissues** [cytoscape/cytoscape.js#1173]
From: pshannon@fredhutch.org<br>
Subject: node font-size &lt; 1?<br>
First Attachment: http://ift.tt/19fNRe4<br>
Date: December 01, 2015 at 04:16PM<br><br>
Hi Max, I find great support for very small edge width and node border width, very useful when we zoom in deeply: cy.edges().style({"width": 0.01}) cy.nodes().style({&ldquo;border-width&rdquo;: 0.01}) but font-size is less malleable: any font-size less than 1 appears to be clamped to 1. Thus the last three of the following commands, executed from the javascript console, produce the same result: cy.nodes().style({"font-size": 10}) // big font cy.nodes().style({"font-size": 1}) // much smaller cy.nodes().style({"font-size": 0.1}) // unchanged cy.nodes().style({"font-size": 0.01}) // unchanged In each case (using the last as an example) the font-size property seems to be properly assigned: cy.nodes().style("font-size&rdquo;) // &ldquo;0.01px" Any ideas? Thanks! - Paul<br><br>
via Gmail

**Comment by maxkfranz** [comment]
@pshannon-bioc

This is a limitation of how browsers implement font rendering in canvas.  There's nothing we can do in this case.

The only suggestion I have is to scale up your styles.  Multiply your sizes by a factor such that the font size is at least 1px.  While font sizes can't scale, the zoom level can scale arbitrarily.  Your zoom levels will be different, but zoom is just a relative measure anyway.

**Comment by aravael** [comment]
Any updates according this issue in 2019?
