### ISSUE TITLE
Unable to map array data to control-point properties

### ISSUE THREAD

**Issue by danielpes** [cytoscape/cytoscape.js#1174]
I am using Cytoscape.js 2.5.1.

I added some control-point data as arrays for my edges, for example:
```javascript
edge.data('cpDistances', [ 1, 2, 3 ]);
edge.data('cpWeights', [ 0.25, 0.5, 0.75 ]);
```
Then I tried binding it to the unbundled-bezier control point properties:
```javascript
.css({
    'curve-style': 'unbundled-bezier',
    'control-point-distances': 'data(cpDistances)',
    'control-point-weights': 'data(cpWeights)'
})
```
It doesn't work because apparently the data is being converted to float and only the first value of the array is considered, raising the following error:
```console
Uncaught TypeError: style.control-point-distances.pfValue.join is not a function
```
I'm sorry if I'm misusing the feature.

**Comment by danielpes** [comment]
Just to inform, the problem also occurs when the curve-style is set to ```segments```, with the edge data mapped to the ```segment-distances``` and ```segment-weights``` properties.

Additionally, I tried setting the data to strings instead of arrays ( ```edge.data('cpDistances', '1 2 3')``` ) and then I tried using functions instead of data mapping, but I was not able to work around the problem.

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-0a1c546077-1449167198522.zip

**Comment by danielpes** [comment]
Now it works fine. Thanks a lot!
