### ISSUE TITLE
label animation?

### ISSUE THREAD

**Issue by dannymcpherson** [cytoscape/cytoscape.js#1176]
Should label animations work?  They currently do not for me:
```cy.nodes().animate({style: {label: 'data(label)'}}, {duration: 1000});```

**Comment by maxkfranz** [comment]
No, you can't morph text.  That would be hugely expensive.  It also wouldn't make sense at all for the case where there's no initial text.  

It only ever makes sense to animate numeric properties.  Animate something like opacity instead.
