### ISSUE TITLE
Bottom/top roundrect shapes (`shape: top-roundrectangle | bottom-roundrectangle`)

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1180]
![sbgnfigure copy](https://cloud.githubusercontent.com/assets/989043/11721987/85062300-9f34-11e5-8de1-8c9c0e6aac15.png)

`shape: top-roundrectangle | bottom-roundrectangle`

**Comment by d2fong** [comment]
Bottom implemented in pr
