### ISSUE TITLE
Lint for trailing commas

### ISSUE THREAD

**Issue by andygeiss** [cytoscape/cytoscape.js#1188]
In my current project I will use cytoscape to visualize data.
So I combined all my source files into one single JavaScript file.
I tried to compile with googles compiler to obfuscate and minimize file size.
I got some errors ... and fixed the following lines by removing the trailing commas.
Maybe its possible to remove them in the original code, too?

Error: Command failed: java -jar /opt/google/compiler.jar --compilation_level ADVANCED_OPTIMIZATIONS --js bundle.js > bundle.min.js

bin/js/viz-0.0.1.min.js:1649: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
      },
       ^

bin/js/viz-0.0.1.min.js:2052: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
  stop: define.stop(),
                     ^

bin/js/viz-0.0.1.min.js:2753: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
              y: ppos.y + origin.y,
                                  ^

bin/js/viz-0.0.1.min.js:7771: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
      y2: ( rb.y2 - pan.y )/zoom,
                                ^

bin/js/viz-0.0.1.min.js:11601: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
      0, -0.15,
              ^

bin/js/viz-0.0.1.min.js:11638: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
    },
     ^

bin/js/viz-0.0.1.min.js:22968: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
        'compound-sizing-wrt-labels': 'include',
                                               ^

bin/js/viz-0.0.1.min.js:24514: ERROR - Parse error. primary expression expected
 * @static
  ^

8 error(s), 0 warning(s)

    at checkExecSyncError (child_process.js:441:13)
    at Object.execSync (child_process.js:481:13)
    at /opt/dev/merge/merge:65:18
    at Object.<anonymous> (/opt/dev/merge/merge:103:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)

**Comment by maxkfranz** [comment]
For now you can just set your Google Closure options to ignore this.  It's not like you'll be running Cy.js on IE8 which has no canvas support, anyway.

**Comment by andygeiss** [comment]
Thx for your fast response!
I'm fine at the moment. These "warnings" are not a real pain for me.
