### ISSUE TITLE
IE10 mouse event errors

### ISSUE THREAD

**Issue by jsalankey** [cytoscape/cytoscape.js#1201]
Running version 2.5.3 on a desktop with a mouse, I am seeing a lot of errors resulting from the section in load-listeners.js that attempts to fix compatibility for IE mouse events. All of the bindings starting on line load-listeners.js:1771 (where it checks if TouchEvent is defined) are checking 

if ( e.pointerType === 'mouse' ) return;

In IE10, e.pointerType = 4, so these checks fail, and it ends up proceeding and throwing a null pointer exception on every mousemove event.

This happens only in IE10 for some reason. I do not see it in IE9 or IE11.

**Comment by maxkfranz** [comment]
Ya, it looks like Microsoft can't keep their enums straight : https://msdn.microsoft.com/en-us/library/windows/apps/hh466130.aspx

We'll add a workaround...

**Comment by maxkfranz** [comment]
Snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-b5cbfb6d52-1450452750185.zip

Try it out and let me know if that sorts it out.  Thanks

**Comment by jsalankey** [comment]
Looks good, thanks.
