### ISSUE TITLE
Wrong arrow position

### ISSUE THREAD

**Issue by yzohar** [cytoscape/cytoscape.js#1208]
Hi,

I noticed that when dragging nodes, in some the target position is not calculated right (the position is on the wrong side of the node) , which cause the target arrow to be displayed "disconnected". See attached.
![cyto_wrong_arrow](https://cloud.githubusercontent.com/assets/5755788/12047332/62a3b04a-aed2-11e5-9f79-7df3969d9062.png)

Thanks
Yuval

**Comment by yzohar** [comment]
This is happening in 2.5.3 as well as older versions

**Comment by maxkfranz** [comment]
I can confirm it working on 2.5.4

Are you using the supported shapes, or have you made modifications and forked the code?

**Comment by yzohar** [comment]
Thanks for checking it out.

I used the supported type RoundRectangle, but I forked and added a style parameter for the radius of the corners. Now I see that for some reason it causes the problem, I'll check it further.
Thanks

**Comment by maxkfranz** [comment]
OK; closing for now
