### ISSUE TITLE
API to get elements at a specified position

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1209]

**Comment by sathishpaul** [comment]
This is a very useful API, please consider implementing it.

**Comment by lsvih** [comment]
Is there any update?

**Comment by TimNZ** [comment]
@maxkfranz I can't see any API support for get elements at a point or inside a box - was this added and I am missing it?

I'm looking through https://github.com/cytoscape/cytoscape.js-compound-drag-and-drop and that code is just doing a search of nodes to test if within a region, which I guess what an API call would have to do anyway, unless some funky search optimisation was implemented.

**Comment by maxkfranz** [comment]
It looks like this isn't associated with any version milestone, so it probably doesn't exist.  The existing bounding box and position functions should suffice for many use cases.

**Comment by jado66** [comment]
My application could really use this functionality.
