### ISSUE TITLE
Springy and Cose-bilkent layout not working in new release

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js#1212]
@maxkfranz 
Hi, is there any documentation mentioning which of the new layouts no longer work, in the new release of cytoscapeJS.
I upgraded to cytoscapejs-2.5.4 this week and the <i>arbor, cola, springy, dagre</i> layouts no longer seem to work.

From what I can tell, <b>arbor</b> and <b>springy</b> layout don't seem to be supported any more (<i>spread</i> layout is now working fine) and they way to use <b>cola, dagre</b> layouts has now changed too.

**Comment by maxkfranz** [comment]
http://js.cytoscape.org/#extensions/layout-extensions

**Comment by AjitPS** [comment]
Thanks, I saw that now.
However, arbor, cola, springy, etc. now do not work by just specifying name: 'arbor' and some basic positioning parameters. Is there any example available to get <b>cola, arbor and springy</b> to work (like the new cose, dagre examples) ?

**Comment by AjitPS** [comment]
Using the new libs for the layout extensions, I now have arbor, spread and CoLa working.
However, for <b>cose-bilkent</b>, I included cytoscape-cose-bilkent.js in which this extension is registered as a layout. However, when I try to use the layout, I get:
````
Can not apply layout: No such layout `cose-bilkent` found; did you include its JS file?e.util.error
@ cytoscape.min.js:18
````

**Comment by AjitPS** [comment]
@maxkfranz : Also, the <b>Springy</b> layout still doesn't seem to work properly. It just places all the nodes on top of one another in a corner of the cytoscapeJS viewport.
I am using the new <i>springy.js</i> and the <i>cytoscape-springy.js</i> layout extension and the following code for the layout:
````
var springyNetworkLayout_new= {
    name: 'springy', 
    animate: true, fit: true, avoidOverlap: true,
    minDist: 20
   };
````

I was earlier using the setting below but this also caused the same layout error:
````
var springyNetworkLayout= {
    name: 'springy', 
    animate: true, fit: true, padding: 10, maxSimulationTime: 4000, 
    ungrabifyWhileSimulating: false, 
    boundingBox: undefined, random: false, infinite: false, 
    ready: undefined, stop: undefined, 
    avoidOverlap: true, handleDisconnected: true,
    nodeSpacing: 10, // for extra spacing around nodes
    // springy forces
    stiffness: 400, repulsion: 400, damping: 0.5 
   };
````

**Comment by maxkfranz** [comment]
I've just confirmed all the extension layouts working just fine, including both `springy` and `cose-bilkent`.  Make sure you're following the instructions in the readme for each extension you use.  If you find a bug in a particular extension, please use the issue tracker for that extension with a reproducible test case demo and/or description.

Please note that Springy is an external library, and if you have problems with the algorithm itself then you should contact its author.  Also note that all of the other physics simulations layouts supported by Cytoscape.js are faster and also produce better results as compared to Springy.  You may be better off using a different layout.

**Comment by maxkfranz** [comment]
The `randomize` option might help if Springy gets stuck -- but it's no guarantee.  It's just not as reliable an algorithm as the other layouts.

**Comment by AjitPS** [comment]
Thanks Max.
I'll try that and if Spring still doesn't work, I'll use other layouts instead (which all work fine).

**Comment by maxkfranz** [comment]
OK; closing for now

**Comment by AjitPS** [comment]
FYI, I am not using <i>Springy</i> layout anymore as I can't get it to render as required. I'm also encountering errors with the <b><i>breadthfirst</i></b> layout when using cytoscapeJS-2.5.4.

The other layouts: CoSE, cose-bilkent, circle, concentric, dagre, grid, arbor, etc. work fine so I am using a few amongst them instead along with CoLa which is still causing problems for larger networks.

**Comment by AjitPS** [comment]
@maxkfranz: For <b>CoLa</b> layout (which I use as the default layout in my web application; users can otherwise choose circular, concentric, cose or cose-bilkent layout and re-layout the network graph), it works perfectly for smaller networks (with <30 nodes and <50 edges, both nodes and edges have varying sizes and colors) as shown below:
![cola_small](https://cloud.githubusercontent.com/assets/1078989/12263438/04511988-b927-11e5-8967-ffc6898ec144.png)

My CoLa layout settings are defined as:
````
   var cola_Layout= {
    name: 'cola', animate: true,
    handleDisconnected: true, avoidOverlap: true, 
    randomize: false, fit: true, maxSimulationTime: 4000/*1500*/, 
    padding: 10, refresh: 1, ungrabifyWhileSimulating: false,
//    boundingBox: undefined/*{ x1: 0, y1: 0, w: 1200, h: 900 }*/,
    nodeSpacing: 5 /*20*/, 
    edgeLengthVal: 45 /*10*/,
    edgeLength: 45
    //, infinite: false
   };

  // Set WebCola layout (default).
  function setColaLayout(eles) {

   // run the default (CoLa) layout, on the visible elements only.
   cy.$(':visible').layout(cola_Layout);
  }
````

However, for larger networks (>50 nodes, >80 edges), the layout is highly clustered horizontally despite there being a lot of free space in the viewport (the cytoscapeJS container <i>div</i>), as shown below:
![cola_large_issue](https://cloud.githubusercontent.com/assets/1078989/12263441/07480854-b927-11e5-842f-98c5db78b06c.png)

Firstly, in the CoLa parameter settings, I was previously using ````edgeLength```` to define the length of edges but I noticed in your cytoscapejs-cola <b><i>demo</i></b> on the cytoscapeJS website that you used the variable ````edgeLengthVal```` instead which is later used in the cytoscapejs-cola layout extension file. Which of these 2 should I be using ?
 
Secondly, in my web application, at first the network is generated with only a few nodes visible. Users can then gradually un-hide the hidden nodes to eventually see the full, large network. However, CoLa layout doesn't work as expected for larger networks. How can I ensure that the layout <b><i>spreads wider</i></b> to make full use of the space in the viewport ?

**Comment by AjitPS** [comment]
Note: also posted at https://github.com/cytoscape/cytoscape.js-cola/issues/6

**Comment by AjitPS** [comment]
I am using <b>CoLa</b>: http://marvl.infotech.monash.edu/webcola/cola.v3.min.js with http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-latest/cytoscape.min.js and https://cdn.rawgit.com/cytoscape/cytoscape.js-cola/1.1.1/cytoscape-cola.js (the cola layout extension for cytoscapeJS)

**Comment by AjitPS** [comment]
I tried ````randomize: true```` and also experimented with disabling ````fit: true```` for <b>CoLa</b>. However, I get the same issue (as seen in the 2nd screenshot above).
It seems to zoom out and stretch the layout vertically without using the ample horizontal space available. Also, the edge lengths become very long despite setting my specifying the ````edgeLength```` value.

Note: I am running the layout with ````maxSimulationTime: 4000```` (was ````1500```` initially). Could it be worth allowing the layout to run longer to maybe have it cluster in a better way ?

On the other hand, <b>CoSE</b> layout works perfectly for this with the following basic settings:
````
var coseNetworkLayout= {
    name: 'cose', animate: true,
    handleDisconnected: true, avoidOverlap: true,
    idealEdgeLength: 100, nodeOverlap: 20
   };
   // run the default (CoLa) layout, on the visible elements only.
   cy.$(':visible').layout(coseNetworkLayout);
````
