### ISSUE TITLE
cytoscape flash class not working

### ISSUE THREAD

**Issue by chriscr** [cytoscape/cytoscape.js#1216]
Max
I was using cytoscape 2.3.3 and implemented the node flash class to indicate when a new node is added to the graph.  It was working in 2.3.3., but recently upgraded to 2.5.0 and it no longer flashes.

Here is my code

//add flash class for animation
for(var j=0; j<oApp.animateNewNodeIDsList.length; j++){
	var cyNode = oApp.cygraph.getElementById(oApp.animateNewNodeIDsList[j]);
	cyNode.flashClass('flash-new-node', 1500);
}

I am implementing this flash style through

$.MyApp.GraphStyles = [{
	selector: '.flash-new-node',
	css: {
		'background-color': '#FA8258'
	}
}];

Again, this all worked in 2.3.3.  In 2.5.0 its not breaking anything and its hitting all the steps, the change in the nodes background for 1500ms is not working.

thank you

**Comment by maxkfranz** [comment]
I've confirmed `eles.flashClass()` working in 2.5.  Your code is likely relying on a style bug in 2.3 to work.  Make sure your class is after any selectors in your stylesheet that also set background colour and are also on the elements of interest.

**Comment by maxkfranz** [comment]
Closing for now
