### ISSUE TITLE
Changing node options post-initialization

### ISSUE THREAD

**Issue by Defavlt** [cytoscape/cytoscape.js#1220]
According to the documentation, there's a couple of `get`-functions, such as [`grabbable`](http://js.cytoscape.org/#node.grabbable), or [`selectable`](http://js.cytoscape.org/#ele.selectable), but there doesn't seem to be any way of actually setting any of these options post-initialization.

Have I missed something?

**Edit:** I *could* of course change _private, but isn't that internal, and prone to change?

**Comment by maxkfranz** [comment]
Use .grabify() and .selectify()
