### ISSUE TITLE
Meteor/Atmoshpere : Having both cytoscape:cytoscape and maxkfranz:cytoscape is confusing

### ISSUE THREAD

**Issue by clemsos** [cytoscape/cytoscape.js#1222]
If one of those is not used or maintained, it should be removed

**Comment by maxkfranz** [comment]
Unless this has changed recently, Meteor doesn't allow removal

**Comment by clemsos** [comment]
ok no problem then ...

**Comment by maxkfranz** [comment]
https://atmospherejs.com/i/faq

Apparently this will kind of hide it?

```
meteor admin set-unmigrated [packagename]
```

I'll see if that helps.

**Comment by maxkfranz** [comment]
Their command doesn't work.  It just spins forever...

**Comment by maxkfranz** [comment]
Ref : https://github.com/meteor/meteor/issues/5534
