### ISSUE TITLE
Setting edge weight doesn't seem to alter the appearance of the edges?

### ISSUE THREAD

**Issue by andrewlouis93** [cytoscape/cytoscape.js#1223]
I have a demo here: http://codepen.io/anon/pen/pgdLVd

I'm wondering why the edge weights do not seem to vary the appearance of the edges..., is there anything in the edge styles that is conflicting?

**Comment by maxkfranz** [comment]
Thanks for the feedback; I've put the issue in the extension's repo https://github.com/cytoscape/cytoscape.js-dagre/issues/9
