### ISSUE TITLE
cytoscape.js init failed. - meteor lib cytoscape:cytoscape 2.5.5

### ISSUE THREAD

**Issue by mraky** [cytoscape/cytoscape.js#1225]
**sumary:**
seems function 'ready'  in  "cytoscape:cytoscape"  is called before graph is ready

//btw. shall i put this  to stackoverflow rather then here ?

**details:**
with reference(same code) to :
http://stackoverflow.com/questions/34832148/cytoscape-js-meteor-simple-example-doesnt-work

when i use lib maxkfranz:cytoscape(i can see it is 2.4.9) , with code:
```Javascript
.
.
   sit = cytoscape({
        container: document.getElementById('cy'),
        ready: function() {
.
.
```

graph is initialised properly, and variable sit is avaiable  at moment of calling "ready: function()"

but when i try to use lib  "cytoscape:cytoscape" ( which was suggested ), i can see(in web browser debug)  variable sit is empty at moment of calling ready: function() {

**Comment by maxkfranz** [comment]
This doesn't look like a Cytoscape issue.  It looks like you're making some assumptions about the order of execution.  Refer to the docs:

- http://js.cytoscape.org/#getting-started/the-ready-callback
- http://js.cytoscape.org/#core/initialisation

`ready` could be executed before or after your `sit = ...` assignment.  It depends, so you really shouldn't be making assumptions about execution order.  You should refer to `event.cy` in the ready callback or you should call `cy.ready()` after calling `cytoscape()`.
