### ISSUE TITLE
Performance of square shapes in docs

### ISSUE THREAD

**Issue by dwjohnston** [cytoscape/cytoscape.js#1228]
In the official documentation (http://js.cytoscape.org/#performance) , please add 'set node shape to rectangle' as an optimization. 

(Are documentation issues on topic here? )

**Comment by maxkfranz** [comment]
Yes, there's even a tag for it.

Do you notice a significant difference with the shapes?  Node shape paths are cached and so they should be roughly the same cost to render.  Calculating intersections for rectangles might be a bit cheaper.

**Comment by maxkfranz** [comment]
@dwjohnston I'm not noticing any difference.  Do you have a particular config you're noticing this on?  Thanks

**Comment by dwjohnston** [comment]
@maxkfranz - Hi Max - the performance issue is specifically on dragging the nodes. 

Though to be honest, I've tried to reproduce it, and I'm not sure there's a consistant performance difference. 

Try: 
	<!DOCTYPE html>
	<html>
	<head>
	
		<script src = "jquery.js"		type ="text/javascript"></script>
		<script src = "cytoscape.js" 	type ="text/javascript"></script>
	
	</head>
	<body   ng-app= "myapp" ng-controller = "myctrl">
	
	
		<div id = "foo" style = "width: 1500px; height: 750px; background-color: light-grey"></div>
		
	
	
	</body>
	
	<script type = "text/javascript">
	var cy = cytoscape({
		container: document.getElementById('foo'),	
		style: [
		        	{
		        		selector: '.round', 
		        		css: 	{
		        			shape: 'ellipse', 
		        			width: 20, 
		        			height: 20
		        		}
		        		},
		        	
		        	{
		        		selector: '.square',
		        		css: {
		        			shape: 'rectangle', 
		        			width: 20, 
		        			height: 20
		        		}
		        		
		        	}
		        ],
	      elements: {
	      	nodes: [
	      	        { data: { id: 'a'}, position: { x: 215, y: 85 } },	        
	      	        { data: { id: 'c'}, position: { x: 300, y: 85 } },
	      	        { data: { id: 'd'}, position: { x: 215, y: 175 } },	        
	      	        { data: { id: 'f'}, position: { x: 300, y: 175 } }
	      	        ],
	      	        
	      	        edges: [
	      	                { data: { id: 'ac', source: 'a', target: 'c' } },
	      	                { data: { id: 'df', source: 'd', target: 'f' } }
	      	                ]
	      },
	
			layout: {
				name: 'preset'
			}
		});
		
		function getRandomInt(min, max) {
		    return Math.floor(Math.random() * (max - min + 1)) + min;
		}
		
		for (var i = 0; i<500; i++){
			cy.add({
				group: 'nodes', 
				position: {
					x: getRandomInt(0, 1500),
					y: getRandomInt(0, 750)
				},
			
				classes: (i%2==0) ? 'round' : 'square'
				//classes: 'square'
			}
			);
		}
	
	
	</script>
	
	</html>

**Comment by dwjohnston** [comment]
>Node shape paths are cached 

@maxkfranz do you have any more info about this? - I'm really looking for some ways to improve performance for interactive styling (highlighting node on mouseover etc).

**Comment by dwjohnston** [comment]
For example, the following mouseover seems a bit slow: 

	<!DOCTYPE html>
	<html>
	<head>
	
		<script src = "jquery.js"		type ="text/javascript"></script>
		<script src = "cytoscape.js" 	type ="text/javascript"></script>
	
	</head>
	<body   ng-app= "myapp" ng-controller = "myctrl">
	
	
		<div id = "foo" style = "width: 1500px; height: 750px; background-color: light-grey"></div>
		
	
	
	</body>
	
	<script type = "text/javascript">
	var cy = cytoscape({
		container: document.getElementById('foo'),	
		style: [
		        	{
		        		selector: '.round', 
		        		css: 	{
		        			shape: 'ellipse', 
		        			width: 20, 
		        			height: 20
		        		}
		        	},
		        	
		        	{
		        		selector: '.square',
		        		css: {
		        			shape: 'rectangle', 
		        			width: 20, 
		        			height: 20
		        		}
		        		
		        	},
		        	
		        	{
		        		selector: '.mouseover',
		        		css: {
		        			'background-color': 'red'
		        		}
		        		
		        	}
		        		
		        		
		        		
		        ],
	      elements: {
	      	nodes: [
	      	        { data: { id: 'a'}, position: { x: 215, y: 85 } },	        
	      	        { data: { id: 'c'}, position: { x: 300, y: 85 } },
	      	        { data: { id: 'd'}, position: { x: 215, y: 175 } },	        
	      	        { data: { id: 'f'}, position: { x: 300, y: 175 } }
	      	        ],
	      	        
	      	        edges: [
	      	                { data: { id: 'ac', source: 'a', target: 'c' } },
	      	                { data: { id: 'df', source: 'd', target: 'f' } }
	      	                ]
	      },
	
			layout: {
				name: 'preset'
			}
		});
	
		cy.on('mouseover', 'node', function(event){
			event.cyTarget.toggleClass('mouseover', true); 
		}); 
		
		cy.on('mouseout', 'node', function(event){
			event.cyTarget.toggleClass('mouseover', false); 
		}); 
		
		function getRandomInt(min, max) {
		    return Math.floor(Math.random() * (max - min + 1)) + min;
		}
		
		for (var i = 0; i<500; i++){
			cy.add({
				group: 'nodes', 
				position: {
					x: getRandomInt(0, 1500),
					y: getRandomInt(0, 750)
				},
			
				classes: (i%2==0) ? 'round' : 'square'
				//classes: 'square'
			}
			);
		}
	
	
	</script>
	
	</html>

**Comment by maxkfranz** [comment]
I just tested this out on a graph of 1000 nodes.  I got the same performance for rectangles as ellipses.  Is your Angular code interacting with this in any way?  Have you tried using the profiler in Firefox or Chrome to see where the difference might be coming from?  Thanks
