### ISSUE TITLE
Cose layout broken if running on a selection of elements. 

### ISSUE THREAD

**Issue by dwjohnston** [cytoscape/cytoscape.js#1229]
If we do something like this:

     cy.nodes(':selected').layout(aCoseLayout); 

We get this error: 

    Uncaught TypeError: Cannot set property 'x1' of undefined
    //line 589 in blob

**Comment by maxkfranz** [comment]
Thanks for letting us know.

The issue is not in CoSE, but CoSE is affected because it uses components.  The issue is here and has been fixed:

 eles.components() includes extra elements in some cases #1231
