### ISSUE TITLE
COSE-Bilkent and Spread do not work in IE

### ISSUE THREAD

**Issue by timconnell** [cytoscape/cytoscape.js#1230]
The cose-bilkent and spread layouts do not work in IE (tested with 10 and 11).  This happens with regular and minified code, both from local server and CDN. The issue can be replicated on the demo site.

Error Message:
Unhandled exception at line 23480, column 11 in cytoscape.js
0x800a139e - JavaScript runtime error: The function name could not be automatically determined.  Use thread.require( someFunction, "someFunction" )

If you check the call stack the exception is being thrown from here:
cytoscape.cose-bilkent.js
Line 4510: t1.require(DimensionD);

**Comment by maxkfranz** [comment]
I've just confirmed that both the layouts work fine on both IE and Edge.  Please make sure you're using the latest versions of the extensions.

The demo on the docs page for spread is using an old version and doesn't work on IE, but the demo in the spread repo does work.  https://github.com/cytoscape/cytoscape.js/issues/1233
