### ISSUE TITLE
edge-distances: intersection | node-position

### ISSUE THREAD

**Issue by danielpes** [cytoscape/cytoscape.js#1236]
Add support for the `edge-distances` style property:

**`edge-distances`** : With value `intersection` (default), the line from source to target for `control-point-weights` is from the outside of the source node's shape to the outside of the target node's shape.  With value `node-position`, the line is from the source position to the target position.  The `node-position` option makes calculating edge points easier &emdash; but it should be used carefully because you can create invalid points that `intersection` would have automatically corrected.

Original post:

--

Hi,

When I read the documentation on unbundled edges, I saw the following:

> control-point-distances: A series of values that specify for each control point the distance perpendicular to a line formed from source to target

So, I made some geometric calculations to find my control-points distances based on a line from ```edge.source().position()``` to ```edge.target().position()```. However, the edges were not being drawn exactly as I expected, so after a (big) while, I inspected the cytoscape.js code and found out that the distance calculation is based on a line from ```srcOutside``` to ```tgtOutside```, so I edited my copy of cytoscape to save this information in the scratchpad to be able to correctly calculate the distances.

Is this the expected behavior? If so, is there a way to easily find out the ```srcOutside```and ```tgtOutside``` for each edge? I need this to correctly calculate the control-points distances.

Thank you.

**Comment by maxkfranz** [comment]
This is expected behaviour, but it might be easier if the points are calculated from the node positions rather than the intersection points.  I'll try it out, and if it doesn't break anything then it can be in 2.7.0.

**Comment by maxkfranz** [comment]
@danielpes This adds it as an option.  I can't change the default, because the node-position case is more error prone.

**Comment by danielpes** [comment]
That's great, thank you!
