### ISSUE TITLE
element IDs incrementing

### ISSUE THREAD

**Issue by chriscr** [cytoscape/cytoscape.js#1237]
I am creating a custom layout that depends on a node list sorted by ID.  However, if I remove a node it seems as though cytoscape back fills the ID, which then disrupts my custom layout.  I was seeing if there is a way to have cytoscape keep incrementing the element IDs up and not back fill, or if there is a way for me to control the node IDs when they are being added, and I have to keep track of the incrementing.

thx
Chris

**Comment by maxkfranz** [comment]
The auto IDs are there for convenience / playing around in the console.  If you want control over the IDs, you should specify your own IDs in `elementJson.data.id` using whatever generation method you like.

**Comment by maxkfranz** [comment]
See the JSON format here : http://localhost:8888/cytoscape.js/documentation/#notation/elements-json

**Comment by chriscr** [comment]
I cant get to that url.

I want to control my own IDs before the node gets added to the core, which is I guess is at this point
var oNewNode = cygraph.add( nodeConfigurationData ).eq(0);
So I guess I need to set the ID in my nodeConfigurationData first.

Right now my ID is empty and the core creates an ID for me.

What does eq(0) do ?

Looking at
http://cytoscape.github.io/cytoscape.js/#ele.json
this means I can get the json of the object and update the ID if I want.

Is this the only API documentation
http://cytoscape.github.io/cytoscape.js

**Comment by maxkfranz** [comment]
You need to set `data.id` in the JSON for the element on creation/add : http://js.cytoscape.org/#notation/elements-json
