### ISSUE TITLE
Allow cose to start with set positions. 

### ISSUE THREAD

**Issue by dwjohnston** [cytoscape/cytoscape.js#1239]
One of the problems with the cose layout is that it resets (randomises) the positions of the nodes every time it runs. 

This is a little annoying because what you might want to do is start a cose layout running, then allow the user to stop the layout running when it's 'good enough'. However the user might want to resume running the layout later - and this could be achieved by allowing the cose layout to specify the positions of each node at the layout start.

**Comment by maxkfranz** [comment]
Because of how the CoSE algorithm works, it tends to really need randomised positions to give good results.  Even if it were allowed an option, CoSE tends to shake the nodes pretty violently at the start -- so you don't get much continuity.

If you need continuity and pausing etc, I'd suggest Cola.

**Comment by maxkfranz** [comment]
It uses existing positions if specified
