### ISSUE TITLE
What's the best way to contribute? 

### ISSUE THREAD

**Issue by dwjohnston** [cytoscape/cytoscape.js#1240]
I'm quite familiar with cytoscape having been using it the project I'm working on, and have made some custom modifications myself (allowing it to add extra labels per node). 

How would I go about contributing if that's something you need?

**Comment by maxkfranz** [comment]
It would be great if you'd like to contribute!

If you already have some things that you've added/modified, we could add them in 2.8.  I'm currently finishing up [a few things](https://github.com/cytoscape/cytoscape.js/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.7.0) for 2.7 in the unstable branch.

For now, it would be best to start by putting your changes on a public fork repo on Github.  At that point, we can do a review/pull request etc.

**Comment by maxkfranz** [comment]
@dwjohnston Would you be able to put your existing changes on a Github fork sometime this week?  I'm hoping that we can put your modifications in for 2.7.  Thanks

**Comment by dwjohnston** [comment]
@maxfranz Hi Max - Probably not to be honest: 

- I have to work out how the code is structured on Github. The modification I've made are on the single compiled 2.5.0 JS file. 
- I don't have access to tools like `gulp` `npm` or `node` here. (FML). 
- My current solution is a hard coded label to make the specific change I need to make. 

That said - I'll see what I can do.

**Comment by maxkfranz** [comment]
@dwjohnston OK.  If you manage to diff out the changes, let me know.  Thanks
