### ISSUE TITLE
manually set font-size for a node's label

### ISSUE THREAD

**Issue by Frankzxliu** [cytoscape/cytoscape.js#1242]
Is there a way to manually set label size above a node's label when using layout 'breadthfirst'?

Thank you in advance!

**Comment by maxkfranz** [comment]
You can set alignment with `text-valign` and `text`halign`.  The stylesheets are independent of the layout : http://js.cytoscape.org/#style/labels

**Comment by Frankzxliu** [comment]
How does the font-size for a node's label calculate? On my android tablet, I am using Webview, the font-size of a node's label never changed?

Thank you in advance!

**Comment by maxkfranz** [comment]
(1) Set your style appropriately http://js.cytoscape.org/#style/labels

(2) The webview in Android isn't good.  Apparently, the webview in Android 6 is a bit better than previous versions.  It's not reliable, considering that Android is so fragmented and the webview is dependent on the version of the OS.  You're better off building an embedding Chrome in your app.

**Comment by Frankzxliu** [comment]
@maxkfranz  Thank you for your prompt reply!

Is there a way to set boundary on a graph, so that the graph will not move out of canvas view?
In this case, when a user drags the graph to the edge of canvas view, the graph will stop moving.

Thank you in advance!

**Comment by maxkfranz** [comment]
You'll have to write code for that.  In future, if you have help questions please use Stackoverflow.  There are links on the website.  Stackoverflow works nicely with Google search, so other people can benefit from old questions/answers.

Github is for reporting bugs and requesting features.
