### ISSUE TITLE
Function selector is broken.

### ISSUE THREAD

**Issue by dwjohnston** [cytoscape/cytoscape.js#1246]
Here's a working plunker: https://plnkr.co/edit/QHKUEIHFpHVSwhdg055g?p=preview

Here's the relevent code: 

function changestyle(){
  cy.style(
    cytoscape.stylesheet().selector('node[ent = "biz"]').css({    //this one works
      'background-color' : 'blue',
      'content': 'data(ent)',
      	'font-size': 14, 
					'text-background-color': '#ffffff', //white
					'text-border-width': 1,
					'text-border-color': '#000000',
					'text-border-opacity': 1, 
					'text-background-opacity': 1
    }).
    selector(function(ele){                                       //This one doesn't
      return ele.hasClass('round') && getRandomInt (0, 1) ===0; 
    }).css({
      'background-color' : 'green'
    })
  ); 
}

This will throw an error: 

newQuery is not a function
https://run.plnkr.co/xRiTWYdXbkND7j7K/cyto.js
Line 20264

The issue is that the newQuery function isn't declared before it's called: 

else if( is.fn( selector ) ) {
    self[0] = newQuery();
    self[0].filter = selector;
    self.length = 1;

  } else if( is.string( selector ) ){

    // the current subject in the query
    var currentSubject = null;

    // storage for parsed queries
    var newQuery = function(){
      return {
        classes: [],
        colonSelectors: [],
        data: [],
        group: null,
        ids: [],
        meta: [],

        // fake selectors
        collection: null, // a collection to match against
        filter: null, // filter function

        // these are defined in the upward direction rather than down (e.g. child)
        // because we need to go up in Selector.filter()
        parent: null, // parent query obj
        ancestor: null, // ancestor query obj
        subject: null, // defines subject in compound query (subject query obj; points to self if subject)

        // use these only when subject has been defined
        child: null,
        descendant: null
      };

**Comment by dwjohnston** [comment]
Apologies for the lack of code indentation. I'm stuck working with Firefox 11 here.

**Comment by maxkfranz** [comment]
(1) You can use a filter function in the API functions, like `eles.nodes()`.  You can't do that in a stylesheet.

(2) You've used the wrong arguments : `eles.filter( function(i, ele) )` : http://js.cytoscape.org/#collection/building--filtering/eles.filter
