### ISSUE TITLE
Select box offset in Chrome.

### ISSUE THREAD

**Issue by dwjohnston** [cytoscape/cytoscape.js#1247]
Have tried this on FF11, IE11 and Chrome 46 and the issue appears to be specific to chrome. 

Using the select box `selectionBoxEnabled = true` and using a shift select, the select box is draw about 100px to the bottom right. 

I will test this on my home computer when I get home.

**Comment by dwjohnston** [comment]
Hmmm now that i've revisted this, I'm unable to reproduce it reliably. :-/

**Comment by dwjohnston** [comment]
Definitely still an issue.

**Comment by dwjohnston** [comment]
The issue isn't just the selection box, it's all mouse clicks.

**Comment by maxkfranz** [comment]
This is an issue of you modifying the style/positioning of the viewport.  It's a common issue with any library that has a canvas/viewport, like Google Maps or Leaflet.

Please refer to `cy.resize()` : http://js.cytoscape.org/#cy.resize

There's also mention of it in the init section.
