### ISSUE TITLE
Change 'width' to 'linewidth' for edges. 

### ISSUE THREAD

**Issue by dwjohnston** [cytoscape/cytoscape.js#1248]
Plunker: https://plnkr.co/edit/mmUPHn4N6c1mca1zed02?p=preview

style: [
                {
                    selector: '.round', 
                    css:    {
                        shape: 'ellipse', 
                        width: 20, 
                        height: 20
                    }
                    },

                {
                    selector: '.square',
                    css: {
                        shape: 'rectangle', 
                        width: 20, 
                        height: 20
                    }

                },
                
                {
                  selector: ':selected', 
                  css: {
                    'background-color': 'red', 
                    'line-color': 'red',
                    'width': 30
                  }
                  
                }
            ],

The problem with this, is that it will make both the node widths, and the edge widths 30 when selected. Probably what you want is just the node widths to change.

This can be avoided by doing a seperate selector `'node :selected'`.

**Comment by maxkfranz** [comment]
I don't think changing the property name is practical, since it breaks backwards compatibility.  As you mentioned, it's possible to just use more descriptive selectors.
