### ISSUE TITLE
`eles.sort()` example typo in docs

### ISSUE THREAD

**Issue by mabossert** [cytoscape/cytoscape.js#1251]
When I run a sort function on my data as written in the documentation here: [http://js.cytoscape.org/#eles.sort](http://js.cytoscape.org/#eles.sort), the nodes do not sort as expected.  By rewriting the sort function as below, it works just fine.  Is the documentation incorrect?  Or perhaps there is some other weirdness at play?

This works as expected:
`var sortedNodes = nodes.sort(function(a,b) {`
`     if(a.data(options.axisSort) > b.data(options.axisSort)) {`
`            return 1;`
`     }`
`     else {`
`         return -1;`
`     }`
`});`

This does not:

`var sortedNodes = nodes.sort(function(a,b) {`
`     return a.data(options.axisSort) > b.data(options.axisSort);`
`});`

**Comment by maxkfranz** [comment]
It's a typo; `>` should be `-`.

**Comment by maxkfranz** [comment]
```js
var nodes = cy.nodes().sort(function( a, b ){
  return a.data('weight') - b.data('weight');
});
```

**Comment by maxkfranz** [comment]
Docs updated http://localhost:8888/cytoscape.js/documentation/#eles.sort
