### ISSUE TITLE
Feature proposal: mapData with bipartite color gradients (e.g. for logFC)

### ISSUE THREAD

**Issue by marteber** [cytoscape/cytoscape.js#1255]
First of all, thanks for your continuous work and support on this project!

I am visualizing logarithmic fold changes from a gene expression profiling analysis in my network with mapData. The range of logFCs in my case is -3.5 to 8.5, but it will likely cross 0 also in the general case.

A two-color gradient with mapData works fine but makes it hard to discern which nodes have a logFC close to zero. The ability to specify a third anchoring value and color to mapData, e.g. 0 and white, would improve that a lot. The gradient would then have two linear segments, and the mapper would first need to decide into which segment to put each value. I do not know how much that would impact performance, but it would definitely improve perception a lot.

**Comment by maxkfranz** [comment]
@marteber Have you tried the function mappers? 

http://js.cytoscape.org/#style/mappers

You can specify arbitrary JS to generate the style value from the element's data.

If the data is not dynamic, you can easily use lodash `_.memoize()` to make sure performance isn't impacted.  If the data is dynamic, you could use a bit more sophisticated caching mechanism.

Using a custom function has other advantages, like being able to use non-linear mappings.

**Comment by marteber** [comment]
Thanks for the suggestion! I have seen similar examples but had trouble getting a function mapper to work - I am not overly fluent in Javascript and the Cytoscape.js documentation often makes me feel like I am lacking crucial background knowledge. That is why I thought it would be a nice pre-defined addition for an assumedly frequent use case. 

Anyway, I will try my luck with a function mapper for now. Thanks again!
