### ISSUE TITLE
cose layout does not trigger 'layoutstop'

### ISSUE THREAD

**Issue by dwjohnston** [cytoscape/cytoscape.js#1257]
Here's an example: https://plnkr.co/edit/EMZzyCebSB0KULQwVnKn

If you change the layout type to 'random', then the console.log statements will execute.

**Comment by maxkfranz** [comment]
I've just confirmed this working OK on the debug page:

![screen shot 2016-02-23 at 1 21 00 pm](https://cloud.githubusercontent.com/assets/989043/13261928/5d3ea28e-da30-11e5-9039-7d13ab3ca907.png)
