### ISSUE TITLE
Is it possible to batch animations in order to call a 'complete' function when they are all finished?

### ISSUE THREAD

**Issue by ckapop** [cytoscape/cytoscape.js#1272]
I was wondering if there is a way to batch animations so a 'complete' function can get called only when the last animation is complete, Something like this would be useful if you wanted to move a bunch of nodes and then animate the view port to fit all the nodes again.

For example:

```
for (var i = 0; i < nodeIdList.length; i++) {
        var x = getNewPosition().x;
        var y = getNewPosition().y;
        
        var node = cy.nodes('#' + nodeIdList[i]);
        var pos = {'x': x, 'y': y};

        var ani = node.animation({
          position: pos
        });
        aniCollection.push(ani);
}

cy.animate({
       animations: aniCollection,
       complete: myFunction // called after the last animation is finished,
});
```

**Comment by maxkfranz** [comment]
Use the complete callback for the animation that occurs last.  If several animations occur last, choose an arbitrary one.

**Comment by maxkfranz** [comment]
Or use promises if the timing is more complex:

```
Promise.all( animations.map(function( ani ){ return ani.promise('complete'); }) ).then( doSomethingWhenDone );
```

**Comment by ckapop** [comment]
I did try that originally. It seemed like ele animations in the loop washed out the cy animation at the end after the loop (it never animated). I will try it again. Thanks!
