### ISSUE TITLE
GraphML extension

### ISSUE THREAD

**Issue by thejmazz** [cytoscape/cytoscape.js#1273]
Is there any? Is it worthwhile? I can try to put together a JS GraphML parser which can output to the proper nodes, edges form of cytoscape.js.

**Comment by maxkfranz** [comment]
There's this one and probably others floating around for GraphML parsing in JS: https://github.com/weflex/graphml-parser

Using a library like that, it's just a simple matter of mapping its JSON output to the JSON output Cytoscape.js expects.  If you want, you could wrap that mapping in an extension: http://js.cytoscape.org/#extensions

**Comment by maxkfranz** [comment]
https://github.com/iVis-at-Bilkent/cytoscape.js-graphml
