### ISSUE TITLE
Add right-to-left language support

### ISSUE THREAD

**Issue by sndre** [cytoscape/cytoscape.js#1276]
I may miss this in the documentation, but there seems to be nothing specific with regard to supporting right-to-left languages. Is this something you have on the backlog or willing to consider?

**Comment by maxkfranz** [comment]
RTL languages aren't explicitly supported in canvas on a draw-by-draw basis: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/direction

It looks like the only way to support it is globally setting HTML attributes: http://stackoverflow.com/questions/8961636/html5-canvas-filltext-with-right-to-left-string

But in the case of using a `dir` attribute, couldn't the user set it on their own div or a parent div?  I'd assume the entire page would probably be in a RTL language in that case anyway.

**Comment by sndre** [comment]
@maxkfranz, setting dir on the canvas works for our use cases. Thank you!
