### ISSUE TITLE
How to rotate layout on 90 degree?

### ISSUE THREAD

**Issue by gig177** [cytoscape/cytoscape.js#1279]
How to rotate layout of network entirely? I expect something like that:
```javascript
var cy = cytoscape({
    ...
    layout: {
        name: 'breadthfirst',
        directed: true,
        flow: 'LR', // hypothetical option
    }
});
```
I need to change network flow from `top->bottom` to `left->right`.
![a](https://cloud.githubusercontent.com/assets/8968462/13459957/715277a6-e088-11e5-9d3d-c337a78f7efe.png)

**Comment by appunnicer13** [comment]
You can use CSS on the shadow elements , so rotate the whole cy by 90 deg and then rotate each element by -90deg . I think that will solve the problem , no need of options

**Comment by gig177** [comment]
Thanks for your reply! This snippet doesn't solve this problem:
```css
canvas {
    transform:rotate(-90deg);
}
```
It isn't work perfectly cause axis [is break now (demo)](http://pagerank-gig177.rhcloud.com/?cytoscape-issue=1279).

**Comment by maxkfranz** [comment]
Use [dagre](https://github.com/cytoscape/cytoscape.js-dagre) with the `rankDir` option

**Comment by gig177** [comment]
Dagre calculates edge's length in unexpected way. For dynamic CRUD system it's unsuitable.
Therefore `breadthfirst` layout is ideally for me.

**Comment by maxkfranz** [comment]
Then you could rotate the node positions after breadthfirst finishes.  It's just [a little bit of trig](https://en.wikipedia.org/wiki/Rotation_%28mathematics%29#Two_dimensions).  If you want, you could put that into breadthfirst directly as an option and push a PR.

**Comment by chirchiAbdelhamid** [comment]
You can make a rotate function like that
function rotate() {
			setTimeout(function (){
				cy.nodes().positions(function( i, node ){
					  return {
						    x: node.position('y')*6,
						    y: -1*node.position('x')*0.2
						  };
						});
				 
				cy.fit()
	
				},100); 
}
