### ISSUE TITLE
Arbor firing multiple layoutstop event

### ISSUE THREAD

**Issue by pmall** [cytoscape/cytoscape.js#1287]
I'm using customized arbor layout for displaying protein-protein interactions networks with nodeMass proportional to the node degree and edgeLength inversely proportional to the difference of degree between source and target. I know this layout is outdated but I have great results with it and I can't manage to reproduce such good results with cose or cola layout so I'm bit stuck using arbor.

The thing is arbor is firing many time the stoplayout event. The number can vary and the moment can vary. Is there a way to fix it ?

**Comment by pmall** [comment]
I also have to mention that sometimes cose layout don't fire any stoplayout event. Only cola works as expected everytime.

**Comment by maxkfranz** [comment]
If you notice a bug, please file an issue for it.

`cose` is used in production in lots of places where it has no issue with `layoutstop`, so I'd be interested in seeing the data/steps/example to reproduce your issue.  I tested `cose` today with several graphs, and `layoutstop` fired every time.

**Comment by maxkfranz** [comment]
Arbor is not a part of the library, it's a separate extension.  If you have an issue with the arbor extension, please file an issue in its repo as per [`contributing.md`](https://github.com/cytoscape/cytoscape.js/blob/master/CONTRIBUTING.md)

Thanks
