### ISSUE TITLE
Cose layoutstop event fired randomly

### ISSUE THREAD

**Issue by pmall** [cytoscape/cytoscape.js#1291]
Code reproducing the issue on ubuntu 15.10/firefox 44 : 

~~~
function initNetwork(options){

    var container = options.container;
    var data = options.data;

    var cy = cytoscape({
        container: container.find('.canvas').get(0),
        elements: data,
        layout: { name: 'null' },
    });

    cy.on('layoutstart', function () { console.log('layoutstart'); });
    cy.on('layoutstop', function () { console.log('layoutstop'); });

    cy.layout({name: 'cose'});

}
~~~

data is 285 nodes / 313 edges : http://pastebin.com/rRiVgshU

**Comment by maxkfranz** [comment]
Only was reproducible sometimes for me on FF.  Much more often on Linux/FF than Mac/FF

This small patch seems to sort it out

**Comment by maxkfranz** [comment]
Thanks for the test case

**Comment by maxkfranz** [comment]
@pmall Since this completes the 2.6.6 milestone, let me know if this patch works for you.  If so, I'll release 2.6.6.  If not, I'll re-open

Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-88ee7d566f-1457376875221.zip

**Comment by pmall** [comment]
It is working now thanks. Please can you check this for arbor too https://github.com/cytoscape/cytoscape.js-arbor/issues/2 ?
