### ISSUE TITLE
Option "boxSelectionEnabled" is not working anymore

### ISSUE THREAD

**Issue by jakinto** [cytoscape/cytoscape.js#1300]
Hi,

I've just updated to 2.6.6 and enabling "boxSelectionEnabled" option is not working.

Kind regards.

**Comment by maxkfranz** [comment]
I've confirmed it working [as documented](http://js.cytoscape.org/#cy.boxSelectionEnabled) in 2.6.6

Do you have an example of it not working?  Thanks

**Comment by jakinto** [comment]
You are right. I haven't read that you must use shift, control, meta, or alt down to initiate box selection. Apologize for the inconvenience.
