### ISSUE TITLE
Using a promise for 'elements' doesn't work if 'style' is undefined?

### ISSUE THREAD

**Issue by byllyfish** [cytoscape/cytoscape.js#1301]
I am using cytoscape.js 2.6.6, Jquery 2.2.0.

The following code causes an error both Chrome and Firefox (mac, recent versions):

- Chrome: "Uncaught TypeError: Cannot read property 'then' of undefined"
- Firefox: "TypeError: p is undefined" in promise.js "var isPromise = p.then != null;"

```javascript
$(function(){ // on dom ready

cy = cytoscape({
  container: document.getElementById('cy'),
  layout: {
    name: 'cose',
    padding: 10
  },
  style: undefined,
  elements: $.getJSON('/topology.json'),
});

}); // on dom ready
```

If I replace the `elements` promise with a hard-coded object, it works fine. 

If I set the `style` property to {}, the error goes away and everything works. If I set the `style` property to null, Firefox now complains that "TypeError: p is null" in promise.js "var isPromise = p.then != null;"

It appears that `style` is not checked to make sure it's a promise when it is undefined/null and elements is set to a promise? Or perhaps, I am doing something wrong?

**Comment by maxkfranz** [comment]
@byllyfish 

(1) The promise polyfill was incorrectly applied regardless of whether native promises are available: Promise polyfill should be applied only in promiseless environments #1303

(2) The `Promise.all()` implementation in the polyfill incorrectly handled the nil value case

Try this snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-f1d3443661-1458235563369.zip

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-b5f7581b78-1458240150429.zip

**Comment by byllyfish** [comment]
This works. Thanks for the quick turnaround!

This snapshot has one new behavior. If my `elements` graph is empty,
there's a type error. This is true even if I hard-wire it.

Firefox: "TypeError: v is undefined" at cytoscape.js:870
Chrome: "Uncaught TypeError: Cannot read property 'length' of undefined" at
"bfs-dfs.js:64" (line number is off)

The line is: "for( var i = 0; i < v.length; i++ ){"

Here's my code:

```javascript

$(function(){ // on dom ready

cy = cytoscape({
  container: document.getElementById('cy'),
  layout: {
    name: 'cose',
    padding: 10
  },
  elements: {"edges":[], "nodes":[]},
});

}); // on dom ready

```

**Comment by maxkfranz** [comment]
@byllyfish I've just confirmed it working with several unit tests to reproduce your case.  They all pass on Node.js, Firefox, and Chrome.

**Comment by maxkfranz** [comment]
@byllyfish Your issue has to do with the layout, which calls `eles.components()`: https://github.com/cytoscape/cytoscape.js/issues/1316

This promise issue is already resolved, so I'll close it
