### ISSUE TITLE
Loading cytoscape.js + layouts + plugins using RequireJS + AngularJS

### ISSUE THREAD

**Issue by danpaulsmith** [cytoscape/cytoscape.js#1302]
I've just updated to the latest versions for cytoscape, the layouts, panzoom, edgehandles, navigator and the context menu.

The requirejs config, shims, exports & dependencies - together with Angular's dependency management - is causing me a headache. I'm getting "cytoscape is undefined" for some of the plugins, which I've specified depend on cytoscape and jquery.

If anyone could help my jsfiddle that would be hugely appreciated. To start with, edgehandles can't find cytoscape:

http://jsfiddle.net/ZgJXv/63/

**Comment by maxkfranz** [comment]
I'm not an expert at RequireJS, but Angular's dependency management isn't all that great.  I'd recommend trying not to use it if you can.
