### ISSUE TITLE
cytoscape server issue

### ISSUE THREAD

**Issue by cytoscapejsissues** [cytoscape/cytoscape.js#1304]
From: rangaananth@rediffmail.com<br>
Subject: cytoscape server issue<br>
First Attachment: http://ift.tt/19fNRe4<br>
Date: March 18, 2016 at 02:04AM<br><br>
Dear Team, There are some issue in cytoscape jsbin example. json path not found.(server not found). Could you please look into this. cdn server error. http://ift.tt/1LuDwm0 Thanks, Rangaananth. Get your own FREE website, FREE domain &amp; FREE mobile app with Company email. &nbsp; Know More &gt;<br><br>
via Gmail

**Comment by maxkfranz** [comment]
https://github.com/rgrove/rawgit/issues/108
