### ISSUE TITLE
path not found

### ISSUE THREAD

**Issue by cytoscapejsissues** [cytoscape/cytoscape.js#1305]
From: rangaananth@rediffmail.com<br>
Subject: path not found<br>
First Attachment: http://ift.tt/19fNRe4<br>
Date: March 18, 2016 at 02:13AM<br><br>
Dear Team. The following address is not working. http://ift.tt/1RSYDuH http://ift.tt/1LuDBWC Regards Rangaananth Get your own FREE website, FREE domain &amp; FREE mobile app with Company email. &nbsp; Know More &gt;<br><br>
via Gmail

**Comment by maxkfranz** [comment]
https://github.com/rgrove/rawgit/issues/108
