### ISSUE TITLE
Implementing fruchterman reingold layout algorithm

### ISSUE THREAD

**Issue by Saadman** [cytoscape/cytoscape.js#1312]
Hello. I have been using the r-cytoscape.js package for a few weeks for one of my projects. At this point,I'm stuck with the layout properties because the htmlwidget only supports a certain number of layouts. For my project, I need to implement fruchterman reinold layout algorithm but I don't know how to do it. Could someone kindly help me with this?

**Comment by maxkfranz** [comment]
https://github.com/cytoscape/cytoscape.js-spread

**Comment by Saadman** [comment]
Thank you for the link .But how do I use it with rcytoscapejs ?
