### ISSUE TITLE
graph for tree structure using "dagre.js" layout

### ISSUE THREAD

**Issue by yugi003** [cytoscape/cytoscape.js#1319]
Hi There,

I am trying to implement the tree structure for my dataset using dagre.js layout in cytoscape.js. I have the following information:- 
unique_val_obj = {'param1': ['9211', '9212', '9213', '9214', '9215', '9216', '9217', '9218'], 'param2': ['1', '14'], 'param3': ['val1', 'val2']}
uniq_comb_arr = [{"param1":"9211","param2":"14","param3":"val1"},{"param1":"9211","param2":"14","param3":"val2"},  {"param1":"9211","param2":"1","param3":"val1"},{"param1":"9211","param2":"1","param3":"val2"}, {...}]

'uniq_comb_arr' contains unique combination of the array values of param1, param2 and param3 in the form of array of objects.

In uniq_comb_arr, each object contains the information from parent node to child node in order from left to right i.e  param1 -> param2 -> param3, which I have to convert in tree structure form.

Along with this, I want the styling of the edges in "unbundled-bezier" form. For eg. if there are 4 child node of a parent node, then 2 edges should be concave and 2 should be in convex form, which is shown in below image.
![req_tree_structure](https://cloud.githubusercontent.com/assets/18144037/14142148/79e6c8fc-f6a1-11e5-9903-59f8d6c57e95.png)

I was trying to make the array of objects [ say 'eles']  while looping over the "uniq_comb_arr", in which each object contains the data either related to a node or an edge, and that object was later stored into the cytoscape's object's 'key' which are "elements". But, while creating the data corresponding to the edges, i was not able to add the above styling layer-wise, using the cytoscape's function. 

So, in order to add that styling to the edges, I created the cytoscape object [ say cy1 ], so that nodes and edges can be made of the tree structure. Then, I used the same 'eles' object and added the styling to its edges by checking the relative position of the nodes using the function 'node.position()'. Then, i created a new cytoscape object [ say cy2] over the same id with the updated 'eles' object  ( added styling ), which gave me the plot with the required styling.
So, is there any good way to add above styling layer-wise.

Thanks in advance!

**Comment by maxkfranz** [comment]
(1) Run dagre

(2) For each node, add classes: `left`, `right`, or `center`.  You add these classes based on the node's position relative to its [incomer](http://js.cytoscape.org/#nodes.incomers).

(3) In your stylesheet, just set the control point distance for each class.  The sign of the value determines the handedness of the curve.

**Comment by yugi003** [comment]
I checked out the nodes.incomers() function, but i didn't get how can I find left, right or center using that function. I am not able to find a way to do the above mentioned procedure. In my case, all the children have a single parent.

**Comment by maxkfranz** [comment]
`.position()`

**Comment by maxkfranz** [comment]
In future, please file issues for extensions in their respective extension repo.  That helps to keep things organised.  Thanks
