### ISSUE TITLE
Adding elements duplicated id

### ISSUE THREAD

**Issue by juancroca** [cytoscape/cytoscape.js#1321]
If I create an element without an Id the idFactory will provide one for me in a sequential way, but if I save the state, the json, and then reload and add the json either using .add() or .json(). I get an error saying "Can not create second element with ID '[NODEID]' ". Am I approaching this incorrectly?

**Comment by maxkfranz** [comment]
You shouldn't really rely on the autogenerated IDs for uniqueness across sessions.  They're there for convenience in prototyping etc.

You should have your own ID mechanism if you want something non-clashing, like UUIDs: https://github.com/broofa/node-uuid

Maybe the default generated IDs should be better than an increasing int, but I don't want to make it complicated or long (thereby increasing lib kb) for something that the dev would be specifying anyway.

**Comment by maxkfranz** [comment]
This is short: https://gist.github.com/jed/982883

The issue is it makes the prototyping case harder for devs.  If you're just playing in the console, it's easier to type `ele3` than `D581C808-F75D-11E5-AC29-BC90ADB65F8F`...

**Comment by juancroca** [comment]
Ok I get we have to generate our own ids but would be a good idea to expose the idFactory to be overwritten if necessary. Think its cleaner that going where all the different, add elements actions are.

**Comment by maxkfranz** [comment]
At that point, I'd rather just use UUIDs by default rather than exposing another API -- especially since the API could be achieved with a wrapper on the app side, e.g.:

`function add( cy, ele ){ ... }`

Or as an extension if you want brevity:

`cytoscape('core', 'add', function add( ele ){ ... });`
