### ISSUE TITLE
Icons support for edges ?

### ISSUE THREAD

**Issue by AoDev** [cytoscape/cytoscape.js#1322]
Hello, 

Would it be possible to display icons on edges the same way we do for nodes?
For example in the middle of the line and ideally can be used at the same time than a label.

**Comment by maxkfranz** [comment]
Right now, you can use an icon from an icon font instead of the label.  If both were supported at the same time, it would essentially be another label at exactly the same position.  Considering overlap, I'm not sure that's very useful.

**Comment by AoDev** [comment]
This is what I'd like to be able to do.
* I have edited the screenshot to put the icon over the label of the edge

![icon-on-edge](https://cloud.githubusercontent.com/assets/1526150/14266212/eb98122a-fac6-11e5-9dcf-249d43e6e4a6.png)

**Comment by maxkfranz** [comment]
For the edges, you can use a newline: http://js.cytoscape.org/#style/labels

See `text-wrap`

**Comment by AoDev** [comment]
Hi, yes if you look at the screenshot you can see I'm doing it for the nodes.

But using an icon font is not possible if we want a text at the same time. (and we have decided to remove all icon fonts in favor of svg in our app for different reasons)

I am using utf8 "icon like characters" but it's not really a good result.

**Comment by maxkfranz** [comment]
You can certainly use icon fonts at the same time as text.  You just use a font face hierarchy.

Something like `font-awesome, helvetica neue`

Use the unicode chars that correspond to the icons.  Those match the `font-awesome`, for example.  Text would fall through to `helvetica neue`, because there would be no matches for those characters in the first font, `font-awesome`.

**Comment by AoDev** [comment]
Ok, we could do this. Still is it possible to have such feature? Regardless of how it's done, it would still be nice to be able to use an icon with an optional label on an edge, the same way we can do it for the nodes.

Above was just an example, the icon could be on the edge while the label floating above or below it, etc.
I even saw some issue which idea is somewhat related. Where node labels can be positioned through margin to be able to see the incoming arrows better. https://github.com/cytoscape/cytoscape.js/issues/965

I still think the idea would be useful regardless of the final exact spec for the feature.

**Comment by djangosdk** [comment]
http://jsfiddle.net/bababalcksheep/ajhnmcrb/ 
I prepared a sample using font-awesome.

Can anyone tell me why ```\n``` is not working in edge  ```label: '\uf173\n twitter vs FB',```
I want icon on top and below the text.

**Comment by maxkfranz** [comment]
@djangosdk Have you set `text-wrap: wrap`?  It's `text-wrap: none` by default for performance.

**Comment by djangosdk** [comment]
@maxkfranz 
Thank you. it works now as expected/ http://jsfiddle.net/bababalcksheep/ajhnmcrb/8

But from http://jsfiddle.net/bababalcksheep/ajhnmcrb/8 is it possible that icon of twitter is inside circle and rest of text is below circle

**Comment by maxkfranz** [comment]
I'm not sure what you mean and your demo doesn't run for me.

**Comment by djangosdk** [comment]
@maxkfranz 
Here is working fiddle:  http://jsfiddle.net/ajhnmcrb/11/ 
![position](https://cloud.githubusercontent.com/assets/4101480/18741543/3ccbb5ec-80c9-11e6-918e-b60e169192ca.png)

**Comment by maxkfranz** [comment]
If you want the node label disjointed, then you probably shouldn't use a label.  You definitely shouldn't use label sizing.

The icon should really be a background image for nodes if you want that effect.

**Comment by djangosdk** [comment]
@maxkfranz  Thank you for the clarification.
I know this is not the scope of this issue but is there any event where we can manipulate node and add custom labels perhaps ? or is it a wrong approach

**Comment by maxkfranz** [comment]
Use a mapper in your stylesheet and store the label text in the `data()`

**Comment by djangosdk** [comment]
@maxkfranz 
please have a look at https://jsfiddle.net/bababalcksheep/ajhnmcrb/16/
If I use 
```content:  '\uf173'  then font renders correctly.```
But If I want to update node label with new font, it does not work.

I am using inputbot to change node with id e to change its content.
```js
   $('#title').on('input', function() { 
         cy.$('#e').css({
          content:   $('#title').val()
        });
   });
```

**Comment by DenisTis** [comment]
Hi AoDev, 

how did you achieve that there is white background between edge text and edge line?
I try to achieve the same, but cannot find the setting to do it

> This is what I'd like to be able to do.
> 
> * I have edited the screenshot to put the icon over the label of the edge
> 
> ![icon-on-edge](https://cloud.githubusercontent.com/assets/1526150/14266275/56e51e4c-fac7-11e5-8a13-57887e7a8502.png)

**Comment by AoDev** [comment]
@DenisTis It was a long time ago and I haven't worked with Cytoscape since then. Unless the api has changed, I think these label properties are what you are looking for:

```
'text-background-color': '#fff',
'text-background-shape': 'rectangle',
'text-background-opacity': '1',
```

**Comment by binDongKim** [comment]
Does [this](https://github.com/cytoscape/cytoscape.js/issues/1322#issuecomment-205871956) approach work with fontawesome 5?

**Comment by fallenreaper** [comment]
It seems that with this unicode character set, when using Chrome if you zoom in and out for Cytoscape, it will fail to render some of the icons.   In the above example by 

> @maxkfranz Thank you. it works now as expected/ http://jsfiddle.net/bababalcksheep/ajhnmcrb/8
> 
> But from http://jsfiddle.net/bababalcksheep/ajhnmcrb/8 is it possible that icon of twitter is inside circle and rest of text is below circle

the top link shows that if you zoom in/out, it will turn into a block because it doesnt know how to render.   This is common for rendering text of specific sizes, and was thinking that if we had a way to apply a SVG to it, it would be more dynamic allowing it to scale with Cytoscape itself.

**Comment by fallenreaper** [comment]
i did not.  I stepped away from Cytoscape a few years ago.  There are 2 things I can think of, either a Viewplane issue, or more likely, it fails to render because the icon isnt a proper SVG.  If youre looking at specific things, look into creating your own subset of SVG components.   I do not have any demos at this time though.
