### ISSUE TITLE
selectionType: 'single' overridden by holding shift/control

### ISSUE THREAD

**Issue by dpekkle** [cytoscape/cytoscape.js#1326]
In my application I have set selectionType: 'single' within the initialisation of cytoscape, as I only really want one node/edge to be selectable (since the ui brings up a pane to edit it's data).

Everything behaves as expected when clicking on a node, it selects that node, and a click on another node will deselect the previously selected node.

However, holding shift/control will allow more than nodes to be selected, behaving as if selectionType was additive. There doesn't seem to be any way to disable or configure this behaviour.

**Comment by maxkfranz** [comment]
That field just indicates what the selection behaviour on tap is.  It is not a method to enforce some sort of global selection policy.

If you want to do that instead, you can bind to selection events and enforce whatever policy you want.  For what you describe, just unselect everything else when you get a new element selected.
