### ISSUE TITLE
Basic cytoscape not showing up in html page

### ISSUE THREAD

**Issue by d4ndruff** [cytoscape/cytoscape.js#1328]
I am just starting out with cytoscape and wanted to test it. But nothing is showing up. This is a pretty simple code:

1. included a local copy of cytoscape.js in index.html
2. html contains only one simple div id=cy
3. the html also contains a mainapp.js file that contains copy of an online demo (copied from the link here: http://js.cytoscape.org/demos/2ebdc40f1c2540de6cf0/)

yet nothing shows up in the html in browser :(
the div tag is just an empty box. i was hoping to see the cytoscape UI in there.

**Comment by maxkfranz** [comment]
You need to set dimensions on your div using CSS.  Divs have size zero by default.

See the getting started section: http://js.cytoscape.org/#getting-started/including-cytoscape.js

**Comment by d4ndruff** [comment]
yup - i did. which is why i see a box 300 x 300 in size. but nothing in it. could it be because the div is not big enough for the cytoscape.

**Comment by maxkfranz** [comment]
If you just copied the demo JS verbatim, then you've probably got errors in the console.  If you just want to download the demo, click the download icon (link : https://gist.github.com/2ebdc40f1c2540de6cf0/download)
