### ISSUE TITLE
click and tap trigger on box selection

### ISSUE THREAD

**Issue by rockshandy** [cytoscape/cytoscape.js#1330]
I have box selection and panning enabled (trying out cytoscape 2.6.7 from 2.4.1). When I use box selection to select multiple nodes I see my click handlers triggering when I complete the box. Peeking at the code it seems like if I didn't drag or pan a click is fired now, but I find it strange box selection wouldn't be included in that list.

Is this expected behavior? Is there a recommended way in my click eventing I should catch box selection cases myself?

**Comment by maxkfranz** [comment]
This is probably a bug.  Thanks for the heads up, and it will be addressed soon

**Comment by rockshandy** [comment]
Thanks for the quick response!

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-5c44b95d96-1460477953036.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by rockshandy** [comment]
That worked great! I'll hope to start using 2.6.8 when it's out then, thanks.
