### ISSUE TITLE
"free" event is triggered on "tap" / "grab" triggered too soon

### ISSUE THREAD

**Issue by AoDev** [cytoscape/cytoscape.js#1331]
Hello,

Using cytoscape 2.6.7.  When I simply "tap" on a node, the "free" event is also triggered.
I have both "drag" and "tap" handlers as well as "free" for when I stop dragging. So there is a conflict.

I think that's because the "grab" event is triggered immediately, like a "tap" event.
Might be related to this? https://github.com/cytoscape/cytoscape.js/issues/636 (I am using a touchpad from mac book pro)

To solve this currently I've done the following:

```
    this.cy.on('drag', 'node', () => {
      this.isDragging = true
    })

    this.cy.on('free', 'node', (event) => {
      if (this.isDragging) {
        // do something...
        this.isDragging = false
    })
```

**Comment by maxkfranz** [comment]
Thanks; I'll look into it

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-a0afcd0286-1460477182301.zip

I think that commit should fix it

**Comment by maxkfranz** [comment]
@AoDev Closing for now; let me know if it works for you or if you have issues with it

**Comment by AoDev** [comment]
@maxkfranz I am getting cytoscape from npm but it seems  the 2.6.8  has not been published yet.

**Comment by maxkfranz** [comment]
@AoDev  You'll have to use the snapshot to test until 2.6.8 is released.  The fix is working for me when I tested it
