### ISSUE TITLE
text-wrap doesn't work when labels are updated using node.data or batchData.

### ISSUE THREAD

**Issue by fahimulhaq** [cytoscape/cytoscape.js#1332]

**Comment by maxkfranz** [comment]
I could not reproduce this on the latest release.  Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  Any of the example demos on js.cytoscape.org can be forked on JSBin to easily provide a code sample.

**Comment by fahimulhaq** [comment]
http://jsfiddle.net/xuxptna0/2/. 
Look at this fiddle and try adding "foo\nbar" and then click add Node.

I'm using latest version of Chrome on Mac (Version 50.0.2661.75 (64-bit))

**Comment by maxkfranz** [comment]
I think you've got other problems.

See how this fiddle that adds the nodes and modifies the labels works just fine: http://jsfiddle.net/xuxptna0/3/

Generally, you can't expect browsers to allow you to type newlines in textboxes.  You need a multiline textarea for that

**Comment by fahimulhaq** [comment]
That's correct. I'm closing the issue. Thanks for your help.
