### ISSUE TITLE
node align by neighbour

### ISSUE THREAD

**Issue by 440459012** [cytoscape/cytoscape.js#1333]
i'm sorry, maybe i do not know about any function, but not found it yet, how can i align draggable node by his neighbour
want something like this:
![untitled-1](https://cloud.githubusercontent.com/assets/8831983/14486660/cb178dfe-0166-11e6-8e70-283ef3fef50f.jpg)

**Comment by maxkfranz** [comment]
It's not clear to me what you mean.  Please explain in more detail

**Comment by 440459012** [comment]
i talking about alignment line, what show position of draggable node to his neighbour, soryy for my bad english,
this project have this functionality, for example:

[http://freegroup.github.io/draw2d_js.app.shape_designer/](http://freegroup.github.io/draw2d_js.app.shape_designer/)

![sample1](https://cloud.githubusercontent.com/assets/8831983/14519904/47268d32-022a-11e6-8da5-e692786c33cf.jpg)

![sample2](https://cloud.githubusercontent.com/assets/8831983/14519921/5a57fa08-022a-11e6-9e2a-b66b94c94d8f.jpg)

**Comment by maxkfranz** [comment]
That's the sort of thing you'd do in your app-level or extension-level code

**Comment by 440459012** [comment]
ok, can you tell to me, how i can get closest neighbour of grabbing node, all node are not grouped

**Comment by maxkfranz** [comment]
You can use [`eles.neighborhood()`](http://js.cytoscape.org/#eles.neighborhood) to get the proper neighbourhood, or you can use `node.position()` if you want to compare positions.
