### ISSUE TITLE
Explicitly list supported gestures in docs

### ISSUE THREAD

**Issue by dpekkle** [cytoscape/cytoscape.js#1336]
When a node/edge is selected clicking the canvas element using a mouse deselects it.

However this behaviour is not present with a touch screen. Clicking the canvas does not deselect currently selected elements, meaning there's no inbuilt way for a user to clear their selection.

Tested in chrome and IE with latest cytoscape.min, behaviour is present in demos such as http://js.cytoscape.org/demos/b7c65115947d9e0e8ec8/

There's obviously workarounds such as

`
cy.on('tap', function(event)
{
	if (event.cyTarget === cy)
		cy.$(':selected').unselect();
}
`
But I thought it was worth mentioning.

**Comment by maxkfranz** [comment]
You `taphold` the background to remove selection from all elements.  

It's very easy on touch devices to tap accidentally on the background, causing the user to lose selection state.  If you want the behaviour also on `tap`, it's easy to use a listener as you mentioned.

**Comment by dpekkle** [comment]
Ah, thank you. Default behaviours are hard to figure out.

**Comment by maxkfranz** [comment]
Worth mentioning in the docs

**Comment by dpekkle** [comment]
Fair enough, perhaps a section with all the 'default' behaviours for touch and KBM would be helpful. 

Had a team member tell me that functionality for multiple selections (by holding control) was already added when I suggested we implement it, and I couldn't find any mention in there.
