### ISSUE TITLE
cy.fit() change minus value at cy.zoom()   in IE 11

### ISSUE THREAD

**Issue by duskan** [cytoscape/cytoscape.js#1341]
Hi, 
I`m a korean developer and I can`t speak/write english well..
please understand about this . :-)

I use cytoscape.js 2.2.1 version and cytoscaple-panzoom widget in my project.

in my project,
when i call $("cy").cytoscape( ...... ) , IE 11 didn`t display nodes  and edges
but other browsers ( safari, chrome) work!

I tracking my source code and 
I found that cy.zoom() returns minus value only IE. 
and if I call cy.reset(), IE can browser rendering nodes and edges! (zoom() == 1)

I tracking agian and finary I found cy.fit() function change zoom value
 using "cytoscape-panzoom" widget.

i call cy.reset()  (zoom == 1) and 
click cytoscape-panzoom reset button 

in  "cytoscape-panzoom widget'

```
  var cy = $container.cytoscape("get");
  if( cy.elements().size() === 0 ){
	cy.reset();
  } else {
	**cy.fit( options.fitPadding );**
  }

```
when system call bold line, zoom value changed to minus value only in IE.

in that code, options.fitPadding is 50, elements().size() == 370 
(IE and other browser have same value)
and after call cy.filt(options.fitPadding). other browser`s values are neer to 0.8  
but IE zoom value is -0.0913..... !

I think some properties gets wrong value  in IE11
( i don`t know that properties are caluculated in my cord or cytoscape code) 

How can I solve this problem???
plz tell me why it happen .... 

this project is our company project, so I can`t share our code. (T.T)

if you can`t find definitely reason, 
plz tell me what kinds of properties(or value) asfect to caculate cy.fit() fuction 

Thanks . got bless to you.

**Comment by maxkfranz** [comment]
Try the latest version of Cytoscape, 2.6

**Comment by duskan** [comment]
@maxkfranz : Thank you for your help. 
I can solve  that problem!!

but ... I have another  problem during upgrade my Cytoscapejs version. 

after change newest Cytoscape js file, 
 generated canvas area (using cytoscape js ) has wrong height value like this .


```
<div id="cy" class="chrome" style="overflow:auto;-webkit-tap-highlight-color: rgba(0,0,0,0);">
  <div style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); position: relative; z-index: 0; overflow: hidden; width: 685px; height: 2695px;">
      <canvas style="-webkit-user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline-style: none; position: absolute; z-index: 3; width: 685px; height: 2695px;" data-id="layer0-selectbox" width="685" height="2695"></canvas>
      <canvas style="-webkit-user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline-style: none; position: absolute; z-index: 2; width: 685px; height: 2695px;" data-id="layer1-drag" width="685" height="2695"></canvas>
      <canvas style="-webkit-user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline-style: none; position: absolute; z-index: 1; width: 685px; height: 2695px;" data-id="layer2-node" width="685" height="2695"></canvas>
  </div>
</div>
```

 in my css files, "#cy" has 700px width & height value , but generate result  has 9938 px  height value. 
 before upgrading , that area`s height was  600~ 700px.    
 i try to find solving this problem. can`t find documentation or issue about this....

 can you tell me an advice for this problems?   thanks.

**Comment by maxkfranz** [comment]
Make sure your stylesheet takes effect before the JS for the graph runs.

You can also use [`cy.resize()`](http://js.cytoscape.org/#cy.resize) after your code has resized the graph div to correct for changes.
