### ISSUE TITLE
Edge selection prevented by panning state

### ISSUE THREAD

**Issue by rs0h** [cytoscape/cytoscape.js#1342]
It seems that  it's almost impossible to select edge due to `r.hoverData.dragging` flag always set at  the line 802 in "load-listeners.js".
For temporary workaround I've just set r.hoverData.dragging to true before that line.

**Comment by maxkfranz** [comment]
Possibly related to https://github.com/cytoscape/cytoscape.js/issues/1335

**Comment by maxkfranz** [comment]
Also related to https://github.com/cytoscape/cytoscape.js/commit/e2bdfae4f7d762383888da65573fc6e70052f38d

**Comment by maxkfranz** [comment]
@rs0h 

Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-634d2ba902-1461605352048.zip

Let me know if it works for you or if you have any issues with it.  

Thanks
