### ISSUE TITLE
Spiral option for circle layout

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1343]
Have an option to make the circle layout use a spiral shape to make more effective use of area

**Comment by dandeancook** [comment]
Is the spiral layout available yet?

**Comment by maxkfranz** [comment]
This isn't assigned to a milestone and I don't see it in the documentation, so it looks like it's still up for grabs.  You're welcome to put up a PR for it if it's important to your use case.

Let me know if and when you're moving forward on this, and I'll reopen this issue.
