### ISSUE TITLE
Undirected graph?

### ISSUE THREAD

**Issue by PinaGamer** [cytoscape/cytoscape.js#1344]
Hi! I want to create an undirected graph. I've read all the documentation and [this StackOverflow question ](http://stackoverflow.com/questions/28137199/cytoscape-for-undirected-graphs) but I've not found anything about set a graph's parameter like `directed: true` or something like this, and when I use `node.indegree()`method, the result is not the same like `node().outdegree()` because my edges have to be generated randomly.

![Cytoscape Issue](http://i65.tinypic.com/rw28sl.png)

**Comment by maxkfranz** [comment]
@PinaGamer There's no reason to use `indegree()` or `outdegree()` if your graph is undirected.  Just use `degree()`.

APIs that can care about directionality (e.g. [`eles.bfs()`](http://js.cytoscape.org/#eles.breadthFirstSearch)) have options like `directed: true | false`

**Comment by PinaGamer** [comment]
And if I want to get the shortest paths? With [eles.dijkstra()](http://js.cytoscape.org/#eles.dijkstra) or [eles.bellmanFord()](http://js.cytoscape.org/#eles.bellmanFord) algorithms I can't get the shortest path in the above graph because the edges are directed.

**Comment by maxkfranz** [comment]
No, those are both undirected algorithms unless you specify otherwise.

**Comment by PinaGamer** [comment]
But then, how can I create an undirected graph? Because I don't know yet how to create it.
![GitHub Logo](http://i67.tinypic.com/sbsvag.png)

In the above image, you can see that the shortest path is 25 units, but the bellmanFord algorithm return the edge which its weight is 51 :(

**Comment by maxkfranz** [comment]
You don't create an undirected graph.  You create a graph, and you can choose to regard or disregard direction.

If you don't specify weights in algorithms, the algorithm assumes constant weight per edge.  Please refer to the docs for details

**Comment by PinaGamer** [comment]
Hello again! I'm stuck with my problem because I can't get the shortest path between two nodes. Algorithms like `eles.dijkstra()` or `eles.bellmanFord()` are keeping in mind directionality and I know that these algorithms, by default, `directed` option is `false`.

Sorry if I bother you, but I'm unable to do this easy task whether I have multiple edges between two nodes and I want the shortest edge.

Thanks one more time.

**Comment by PinaGamer** [comment]
Finally, I could solve it! The problem was in algorithm's option. I had not defined a function that returned me the value of every edge. So, if someone else has the same problem only have to add this: 
```javascript
//Define the options var with your preferences
    var options = {
      root : nodes[i],
      weight : function (edge){
        var minEdge = edge.data('weight');
        return minEdge;
      },
      directed : false //this is not necessary
    }
//And execute he algorithm with these options
elements.dijkstra(options);
```

If I finish my project, I will show you. Thanks @maxkfranz for everything!
