### ISSUE TITLE
Remove Meteor package

### ISSUE THREAD

**Issue by fvandillen** [cytoscape/cytoscape.js#1347]
I'm trying to add this to a Meteor project running meteor 1.3.1. Any ideas?
```
florianvandillen$ meteor add cytoscape:cytoscape
 => Errors while adding packages:

While checking for cytoscape:cytoscape@2.6.9:
error: No compatible binary build found for this package. Contact the package
author and ask them to publish it for your platform.
```

**Comment by maxkfranz** [comment]
TLDR : Use npm, meteor/atmosphere isn't a good package management system.

This is an issue on the Meteor side.  We don't have any dependencies at all, much less binary ones.

They have many issues with their package management system.  For Meteor 1.3+, they've conceded and have proper npm support.  Looking now, [they seem to recommend publishing only to npm](http://guide.meteor.com/v1.3/1.3-migration.html).

I'll repurpose this issue for removing the Meteor package.
