### ISSUE TITLE
Rendered style not recalculated on style-only events

### ISSUE THREAD

**Issue by ccaper** [cytoscape/cytoscape.js#1349]
Been using cytoscape for over a year, thank you for it.

Something breaks for me if I use a version after v2.6.7.  I haven't been able to sort out what is going wrong.

In summary, I'm using cy.filter to decide which nodes and edges to show based on an array of node ids.  After I've computed what nodes and edges to show, I'm calling show() and hide() on them.  This works up to v2.6.7.

I've debugged the results of my filter in 2.6.7 and 2.6.8, both appear to return the the correct lists.  I think something changed with the show()/hide().

Running my code in 2.6.8 gives no errors, but does not show/hide the nodes and edges that should be shown/hidden.  2.6.7 works fine.

The following code is embedded in an onChange of a bootstrap multi select form, where the inputs are the node ids.

Here is the code in the onChange:
```
onChange: function(option, checked) {
        var selectedOptions = $('#taggerNamesFilter').val();
        var nodesToShowFromWalkingEdges = [];

        var edgesToShow = cy.filter(function(i, element){
          if(element.isEdge()) {
            if (selectedOptions == null || selectedOptions.length == 0) {
              return true;
            }
            var sourceNode = element.source();
            var targetNode = element.target();
            if ((jQuery.inArray(sourceNode.id(), selectedOptions) >= 0) || (jQuery.inArray(targetNode.id(), selectedOptions) >= 0)) {
              if (jQuery.inArray(sourceNode.id(), nodesToShowFromWalkingEdges) < 0) {
                nodesToShowFromWalkingEdges.push(sourceNode.id());
              }
              if (jQuery.inArray(targetNode.id(), nodesToShowFromWalkingEdges) < 0) {
                nodesToShowFromWalkingEdges.push(targetNode.id());
              }
              return true;
            }
          }
          return false; 
        });
        
        var edgesToHide = cy.filter(function(i, element){
          if(element.isEdge()) {
            if (selectedOptions == null || selectedOptions.length == 0) {
              return false;
            }
            var sourceNode = element.source();
            var targetNode = element.target();
            if ((jQuery.inArray(sourceNode.id(), selectedOptions) < 0) && (jQuery.inArray(targetNode.id(), selectedOptions) < 0)) {
              return true;
            }
          }
          return false; 
        });
        
        var nodesToShow = cy.filter(function(i, element){
          if(element.isNode()) {
            if (selectedOptions == null || selectedOptions.length == 0) {
              return true;
            }
            if (jQuery.inArray(element.id(), nodesToShowFromWalkingEdges) >= 0) {
              return true;
            }
          }
          return false; 
        });
        
        var nodesToHide = cy.filter(function(i, element){
          if(element.isNode()) {
            if (selectedOptions == null || selectedOptions.length == 0) {
              return false;
            }
            if (jQuery.inArray(element.id(), nodesToShowFromWalkingEdges) < 0) {
              return true;
            }
          }
          return false; 
        });
        
        edgesToShow.show();
        edgesToHide.hide();
        nodesToShow.show();
        nodesToHide.hide();
      }
```

Any ideas what might have changed post 2.6.7 that is preventing this from working?

Thank you.

**Comment by cstancu** [comment]
I can confirm that 2.6.9 seems to be having some problems with show/hide. In my case I am trying to hide all children of a compound node using : `target.children().show();`, triggered by a button press.

In 2.6.9 this results in an unwanted effect. The compound node shrinks and moves slightly to the top-left, as if its children have been hidden. However the children as still there, outside the parent node, but neither the children or the parent can be moved. They can be selected, clicked, but not moved.

In 2.6.7 the same happens with the difference that the children are no visible, but the parent node still cannot be moved.

I came across this page http://bumbu.github.io/cytoscape.js/debug/ which in the second example has exactly what I need, hiding child nodes. Is this the 'official' debug page? What version cytoscape.js does it run on?

**Comment by cstancu** [comment]
I replicated my problem in this jsbin: http://jsbin.com/zamufajata/1/edit?html,js,output . I created it starting with the 'Compound nodes' demo on http://js.cytoscape.org. You should press the 'Hide a&c' button and then zoom out since the 'b' button moves to the top-left. It also looks like edges connected to the hidden nodes are not hidden as I expected. Pressing 'Show a&c' button restores everything.

**Comment by maxkfranz** [comment]
@ccaper @cstancu 

Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-63fa2ab179-1461856302209.zip

Let me know if it works for you or if you have any issues with it.  This issue was caused from porting [this fix](https://github.com/cytoscape/cytoscape.js/commit/1c06e5e99a3fba02ee81ccdf1720ce05c7183919) from the unstable / next version branch -- on which the calculation is unnecessary there.

Thanks

**Comment by ccaper** [comment]
That works like a champ.  Will this snapshot be merged into a release?

Thanks for looking into this so quick.

If you are curious as to what/how I am using cytoscape for, I'm tracking graffiti in Chicago, noting the names of taggers, and attempting to track which taggers tag together, and make up some of the sets.  Cytoscape has been amazing for this.

**Comment by maxkfranz** [comment]
@ccaper Thanks for letting me know it works for you.  I'll release 2.6.10 within the next hour.  Glad to hear Cytoscape is working well for you.

**Comment by maxkfranz** [comment]
> I also came across this page http://bumbu.github.io/cytoscape.js/debug/ which in the second example has exactly what I need, hiding child nodes. Is this the 'official' debug page? What version cytoscape.js does it run on?

@cstancu That's just someone else's fork.  The debug page is in the repo in `/debug`.  It's just a simple thing for testing rendering stuff

**Comment by ccaper** [comment]
Thanks Max for quick turnaround!

**Comment by cstancu** [comment]
Hi Max, thanks for the quick fix. It does indeed fixes some part of the problem, i.e., the hidden children are indeed hidden now. However, in my specific case, the compound node whose children I hide still cannot be dragged. Please look at this example: http://jsbin.com/wadetaxena/1/edit?html,css,js,output that uses the latest cytoscape.js which includes your fix.

**Comment by maxkfranz** [comment]
@cstancu If you set all children to a compound parent to `display: none`, the compound has no dimensions.  A compound doesn't have dimensions defined apart from those defined by its children.  If you want to remove nodes, you should use `eles.remove()`.

**Comment by cstancu** [comment]
My use case is to collapse a parent node, i.e., hide its children, while shrinking the parent but keeping it visible, then expand the parent node back again, i.e., make the children visible and restore the parent size. I don't think that removing the elements would work for me. I trigger this currently using a context menu, but I would like to do this on zoom level in the future, i.e., zoom-out collapse, zoom-in expand. I also tried using `visibility: hidden` and `visibility: visible`; in this case the compound node seems to maintain its dimension, at least visually, but still cannot be dragged.

**Comment by maxkfranz** [comment]
@cstancu Removing is exactly what you should be doing in that case.  You can put a reference to the removed elements in the parent's scratchpad for easing restoring: http://js.cytoscape.org/#ele.scratch

e.g.  `parent.scratch( 'descendants', parent.descendants().remove() )` `parent.scratch('descendants').restore()`

**Comment by cstancu** [comment]
@maxkfranz Thank for your suggestion, it works! Remove/restore is the behaviour that I was looking for.
