### ISSUE TITLE
Use offscreen canvases in workers in the renderer

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1350]
- https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

This could increase rendering performance, but only if shared memory is supported or there is live syncing of all the graph elements.

**Comment by pumpadump** [comment]
I would be very interested to try such a feature, we are currently displaying several graphs on one page, and if some of the graphs are huge the ui is blocked while they render.

**Comment by maxkfranz** [comment]
All browsers have dropped SharedArrayBuffer and Safari still does not support OffscreenCanvas, so this specific approach probably won't be possible to implement.

We could do something similar if we had access to a proper thread API within the browser.  OffscreenCanvas is nice to have, but it's not absolutely necessary.

**Comment by limingyang2012** [comment]
https://github.com/cytoscape/cytoscape.js/blob/9b7425c745429483d7c3601119de5e0a1686a642/src/extensions/renderer/canvas/index.js#L313

![image](https://user-images.githubusercontent.com/10152413/65027430-eb5dd000-d96c-11e9-886d-9fd5bd1d3549.png)

iOS UIWebView new OffscreenCanvas(256, 256).getContent('2d') return null，There may be compatibility issues.

**Comment by maxkfranz** [comment]
It's probably moot anyway.  Webworkers have bad support for shared memory.  Until JS engines have proper threading support with general shared memory, this feature is not worthwhile.
