### ISSUE TITLE
3.0.0 upgrade guide

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1352]
A blog post that 
- reiterates the motivations behind the the changes,
- covers the APIs most likely affecting your apps, and
- shows how to update your app to upgrade to 3.0.

**Comment by fhur** [comment]
Where can I find the blog post?

**Comment by josephst** [comment]
http://blog.js.cytoscape.org/2017/04/11/3.0.0-release/


________________________________
