### ISSUE TITLE
Mixed graphs

### ISSUE THREAD

**Issue by ctamas** [cytoscape/cytoscape.js#1362]
I am having trouble finding how to utilize the mixed graph functionality of this framework. The documentation states it is capable of handling directed graphs, undirected graphs and mixed.

So far I found I can select that by deleting or including:

```
.selector('edge')
.css({
'target-arrow-shape': 'triangle'
...
```
at startup or changing it programmatically. This however changes this setting for all edges.
How do I do this individually so I can get mixed graphs?

**Comment by maxkfranz** [comment]
Use selectors in your stylesheet: http://js.cytoscape.org/#selectors

e.g. `edge.directed { ... }` for a class

e.g. `edge[?directed]` for a boolean `directed` data attribute when true

etc.
