### ISSUE TITLE
getting error while running

### ISSUE THREAD

**Issue by d4ndruff** [cytoscape/cytoscape.js#1366]
I get this error in a simple page (copied from demo):
Object doesn't support property or method 'appendChild'.

It is at Line 17972:
`container.appendChild( r.data.canvasContainer );`

It took me a while to get this far but it would be nice to finally get a test working.

**Comment by maxkfranz** [comment]
@d4ndruff Are you specifying the `container` property when you init Cytoscape?  Would you please paste your file here?

**Comment by d4ndruff** [comment]
I have a basic blank html file with just a code below in the body:
`<div id="cy"></div>`

[mainapp.txt](https://github.com/cytoscape/cytoscape.js/files/260614/mainapp.txt)

**Comment by d4ndruff** [comment]
Actually this was fixed just now. I moved the script reference in to the bottom of the body tag and it works correctly now.

**Comment by maxkfranz** [comment]
OK, closing
