### ISSUE TITLE
Detect tap on each line of multi line node content

### ISSUE THREAD

**Issue by djangosdk** [cytoscape/cytoscape.js#1369]
I am new to cytoscape.js and just started using it.

Is there a possibility to detect tap/click on each line of multi-line text ?
I want to have nodes content as list inside it like  ```html <ul> <li>``` and each Link must be tapable separately. 

Any help will be much appreciated.

JSFIDDLE: https://jsfiddle.net/bababalcksheep/nyt8Lupv/7/

I tired using content as function to see if i could use xlink :
but it is treated as text.I was hoping if I have array of items , I could create links for each and return 
Cant we have custom component returned as function ?
```js
 'content': function (node) {
 return '<a xlink:href="#dd1">' + node.data('name') + '</a>';
},
```

**Comment by djangosdk** [comment]
https://jsfiddle.net/bababalcksheep/nyt8Lupv/8/
Another try to return svg_label from content function

**Comment by djangosdk** [comment]
i think its not valid as cytoscape does not support html or svg

**Comment by maxkfranz** [comment]
@djangosdk If you want independent elements as in the DOM, you should use the DOM itself.  You can place arbitrary DOM content in [qtips](https://github.com/cytoscape/cytoscape.js-qtip), for example.
