### ISSUE TITLE
parent label positioning problem

### ISSUE THREAD

**Issue by djangosdk** [cytoscape/cytoscape.js#1370]
I am trying to to render list type style inside parent node.But I cant seem to make parent label appear as expected.
https://jsfiddle.net/bababalcksheep/nyt8Lupv/9/

![labels-issue](https://cloud.githubusercontent.com/assets/4101480/15204888/28d91814-182c-11e6-8621-137f1d598812.jpg)

**Comment by maxkfranz** [comment]
The only label placement inside a node is `center center`.  Padding just pushes a label farther out -- padding should never put a label inside.

In 2.7, [you can specify label margins](https://github.com/cytoscape/cytoscape.js/issues/965) -- so you could use a negative margin along with `top center`.

You'll have to wait for 2.7 and use regular outside labels in the meanwhile.
