### ISSUE TITLE
Add the ability to re-run layout for compound node children.

### ISSUE THREAD

**Issue by aindlq** [cytoscape/cytoscape.js#1372]
I'm trying to do some ad-hock collapse/expand feature for compound nodes.

Collapse is done with changing position of all compound node children to one point:
``` elem.descendants().positions(elem.position()); ```

And then, on expand, I'm trying to re-run layout over all node children:
```  elem.descendants().layout({name: 'cose-bilkent'}); ```

Reading the http://js.cytoscape.org/#eles.layout it seems that it should be possible to layout only some collection of nodes. But it seems this doesn't work for compound node children.

See http://jsbin.com/didunafota/1/edit?html,output

**Comment by maxkfranz** [comment]
Not an issue with Cytoscape.  If you try with a different layout like `circle`, you'll notice your demo works fine.

See https://github.com/cytoscape/cytoscape.js-cose-bilkent/issues/14

**Comment by maxkfranz** [comment]
@aindlq In the meantime, I suspect you could just run the `random` layout before `cose-bilkent` and it would work OK as a workaround.  You can use the `boundingBox` to constrain the layout bounds.

**Comment by maxkfranz** [comment]
@aindlq Or rather than running a layout to expand, you could save the relative positions of each child before collapsing.  Then you can restore that relative position on the expand action.
