### ISSUE TITLE
Positioning the edges on sides

### ISSUE THREAD

**Issue by spurnaye** [cytoscape/cytoscape.js#1373]
Hi,
I have group of elements which are interconnected and the parents are also interconnected and I want to position the origins of the edges between parents on right or left side instead of originating from bottom.
Is there any way I can do this?

**Comment by maxkfranz** [comment]
Edges are positioned automatically based on the relative position of the source and target nodes.  You can position your nodes appropriately for the effect you want, or you can manually specify edge [control points](http://js.cytoscape.org/#style/unbundled-bezier-edges) or [segment points](http://js.cytoscape.org/#style/segments-edges).
