### ISSUE TITLE
Edge label positioning

### ISSUE THREAD

**Issue by ronnyek** [cytoscape/cytoscape.js#1374]
I'd like to add text labels to edges, and I dont have a problem gettign the text here or getting the auto rotate working etc. 
http://puu.sh/oTy6W/d2dc16fb65.png

I'd just really like to take the tex there and have it appear like 10px above the line or something. Doesnt seem like theres anyway to offset the text vertically. Also, is there anyway to insert html into the edge label?

**Comment by maxkfranz** [comment]
See https://github.com/cytoscape/cytoscape.js/issues/965 re. margins

You can not use HTML for labels.  That would require reimplementing much of the DOM, so in that case you may as well just use the DOM directly.  If you want to use HTML text, you should put your text in the DOM -- e.g. using a qtip, an overlay layer, etc.

**Comment by doaa-altarawy** [comment]
I have this issue too, the edge labels are very close to the edge. I used a workaround and set:
`'text-margin-y': -10`
But it doesn't look pretty with autorotation.
