### ISSUE TITLE
New layout algorythm from Viva Graph

### ISSUE THREAD

**Issue by Nickolasmv** [cytoscape/cytoscape.js#1379]
Hi I've integrated new layout algo based on Viva Graph project. I's much more faster that any of avaliable for cytoscape right now. It's in beta now https://github.com/Nickolasmv/cytoscape-ngraph.forcelayout

**Comment by maxkfranz** [comment]
That's really cool!

Is this the same as the Viva `forceDirected` layout?  [CoSE is faster than that layout](https://github.com/cytoscape/js-graph-lib-comparison), but it's always nice to have more options.

Thanks!

**Comment by Nickolasmv** [comment]
Hi yes it's integrated with https://github.com/anvaka/ngraph.forcelayout .

**Comment by cmdcolin** [comment]
Also glad to see new options like this

I added what I think is a bugfix to this package here https://github.com/Nickolasmv/cytoscape-ngraph.forcelayout/pull/1

**Comment by maxkfranz** [comment]
@Nickolasmv Is your layout ready to be used?  Can I list it on js.cytoscape.org?  Thanks

**Comment by maxkfranz** [comment]
(It's been in the list for a while now)
