### ISSUE TITLE
Question: Different Background sizing SVG nodes crossbrowser

### ISSUE THREAD

**Issue by Lenndev** [cytoscape/cytoscape.js#1380]
Hi all,

I have a question, and hope someone's got the answer.
I use svgs as background-image for my nodes. 
But I can't put my finger on the fact that not every browser is displaying them correct (or at all).

I know every browser handles svg differently, but there should be a middle way right?

Does anyone know how to create a svg that will be displayed correctly in cross browser?
and what should be the settings of the cytostyle of the node?

thnx in advance

**Comment by elecnix** [comment]
Actually, two recent versions of Chrome scale the background differently. On Chrome 48, the image is scaled to fit the node, while on 51 it appears scaled to the size of the whole window, but cropped into the node.

You may try it here: http://jsbin.com/hobuzijubu/1/edit?html,css,js,output (source also at https://gist.github.com/anonymous/70297f91b23f8e176de5dfa60b086be5)

Here's how it looks on Chrome 48:
![svg-background-chrome48](https://cloud.githubusercontent.com/assets/17873/15835778/96a67cba-2bff-11e6-91dc-69fe426d50b2.png)

And here's Chrome 51:

![svg-background-chrome51](https://cloud.githubusercontent.com/assets/17873/15835777/96a5dfd0-2bff-11e6-8bca-de410c779938.png)

**Comment by maxkfranz** [comment]
There's a `viewport` tag in SVG.  Chrome may be using that to report the SVG dimensions.  Maybe try exporting your file with Inkscape?  Inkscape usually generates SVGs that work pretty well in different browsers.

Unfortunately, browsers still have trouble with SVG.

Setting a manual `background-width` and `background-height` tends to help in browsers that have buggy SVG implementations -- like IE.

**Comment by maxkfranz** [comment]
Yes, look at the file: <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" ***width="100%" height="100%"*** viewBox="0 0 100 100">...

**Comment by maxkfranz** [comment]
If removing the `width=...` bit fixes it, a bug should be filed in the Chrome issue tracker.

**Comment by elecnix** [comment]
I tried removing the `width`, but that didn't fix it. Also, I played with `background-width` & `background-height` and various siblings without success.

The Chrome changelog shows changes related to SVG scaling, so it may be related. I don't know if it's a change in behavior to comply with a spec, or if it's a regression. What would help is having a test that does not use cytoscape, and I haven't wrapped my head around it yet.

**Comment by elecnix** [comment]
If you zoom out in the sample mentioned above ([link](http://jsbin.com/hobuzijubu/1/edit?html,css,js,output)) you will notice that at a certain point, the background is scaled properly. There is a threshold where the background image becomes too big.

When there are two nodes ([code here](http://jsbin.com/javojefuma/1/edit?html,css,js,output)), the default zoom shows two smaller nodes, and their background is too small to cover the node. Zooming in, it becomes scaled properly (covers the node), and if you zoom further, then it becomes too big.

**Comment by elecnix** [comment]
The scaling in Chrome 51 is done properly by changing the height and width from percentages to fixed pixel values.

**Comment by maxkfranz** [comment]
I think that's only because we allowed the stylesheet value to override the browser's reported image's dimensions when possible.  I think that's the only way SVG works at all in IE.
