### ISSUE TITLE
How to save visual representation of the graph js.cytoscape

### ISSUE THREAD

**Issue by xtreding** [cytoscape/cytoscape.js#1381]
Hello! Please somebody help me.
I need to save visual layout (after nodes of graph was manipulated) and load this visual representation next time.

I tried to save position of each node, and write this positions in input json {data:{id..}, position{x=.y=}.
But new graph was draw incorrect.

**Comment by maxkfranz** [comment]
Use the preset layout or `nodes.positions()`
