### ISSUE TITLE
Layout option for whether to include labels in calculating bounding boxes

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1382]
Including labels prevents labels overlapping other nodes

Excluding labels prevents the graph from being overly spaced out because of a few long labels

**Comment by jsalankey** [comment]
I like this idea. I'm battling with this problem right now in my app and I'm gonna have to settle on a solution where I just hide labels when the layout is calculated.

**Comment by maxkfranz** [comment]
Proposal:

Each layout has a `boundingBoxOptions` field in its options object.  `boundingBoxOptions` is passed whenever `ele.boundingBox()` is called in a layout for overlap detection.  This can be used to include/exclude labels, or further customise overlap detection.

---

I don't have time to do this now, but if someone wants to make a PR on unstable for this, it could definitely be included in the next feature release.

There's also the layout extensions to consider: http://js.cytoscape.org/#extensions/layout-extensions

**Comment by maxkfranz** [comment]
Duplicate of https://github.com/cytoscape/cytoscape.js/issues/1626

Planned for 3.1
