### ISSUE TITLE
change background-colcor node

### ISSUE THREAD

**Issue by vahidalvandi** [cytoscape/cytoscape.js#1383]
{"selector":"node[bkcolor=\"green\"]","style":{"background-color":"#41f203"}},

	"data":{"id":"605755","idInt":605755,"name":"PCNA","score":0.006769776522008331},"group":"nodes","bkcolor":"green"},

dont change back ground color

why?

**Comment by maxkfranz** [comment]
You misplaced your data.  See http://js.cytoscape.org/#notation/elements-json
