### ISSUE TITLE
Provide the ability to define custom selectors and match operators.

### ISSUE THREAD

**Issue by aindlq** [cytoscape/cytoscape.js#1385]
It would be convenient to have the ability to define custom selectors and match operators. 

The use case is when graph is designed to work with some domain specific model and the idea is to provide some kind of DSL embedded into cytoscape stylesheets. 

E.g I'm working with RDF data, and every element in graph can be either Iri, Literal, or bNode. So I want to be able to use selector like `node:isIri` or `node:isLiteral`.

**Comment by maxkfranz** [comment]
Wouldn't `node[?Iri]` work if you had `data: { Iri: true | false }`?

**Comment by maxkfranz** [comment]
Or `node[Iri]` if you had `data: { Iri: anyValue | undefined }`
