### ISSUE TITLE
tapdragover, touchmove, etc should be triggered even when tapstart event originated outside Cytoscape

### ISSUE THREAD

**Issue by tonymullen** [cytoscape/cytoscape.js#1389]
- `tapdragover` and `tapdrag` should be triggered regardless of whether the source `tapstart` event was triggered inside the cy div
- If node not grabbed by `tapdown`, then don't prevent pointer/finger-move-related events (see #1417 and #1358 which caused this)

OP follows:

--

I'm upgrading my app's cytoscape.js dependency from 2.6.7 to 2.6.12. With the new version, the edge handle creation using cytoscape-edgehandles fails to connect to the target node with touch interface. The new edge previews correctly, and I can drag it to the target node, but no edge is created to the node.

**Comment by maxkfranz** [comment]
This is the only error I see on 2.7.2: Dragging nodes via touch gives errors in some cases (extensions etc.) #1411

Does it work for you now on master (or the snapshot)?

**Comment by tonymullen** [comment]
I'm still having the same problem. The edghandles plugin master works as expected with Cytoscape 2.6.7, but with the latest Cytoscape snapshot I'm not able to connect the edge on mobile. Tested on iOS with Chrome and Safari and on Android with Chrome. There doesn't seem to be any event firing when I drag over the target node.

**Comment by tonymullen** [comment]
I tested the cytoscape-edgehandles demo on android and ios also. The target nodes do not change color and edges are not added, so it seems that the same problem is happening with the demo (which uses the latest cytoscape from github). 

Actually, I'm seeing the same issue in the Chrome dev tools device mode emulator.

**Comment by tonymullen** [comment]
Oh, wait a second... I've just noticed the 'drawon' and 'drawoff' properties... This may be the issue. Testing.

**Comment by tonymullen** [comment]
Ok. It seems that the issue I'd been noticing is a difference in the drawon/drawoff settings. I'm going to close this issue.

**Comment by tonymullen** [comment]
I'm still not able to recreate the behavior of the earlier version of Cytoscape. The issue now seems to be related to drawon/drawoff behavior. Let me know if I should open up a separate issue. 

The problem is that if the edghandles are set to 'drawoff' the handles behave correctly but the edge is not drawn, however, if the edghandles are set to 'drawon' the edge starts to be drawn immediately upon touching the node, making it impossible to drag the node, etc. I've tried calling 'drawon' in the start function and a few other things but I can't get edgehandles to work the way it previously did, where a tap would display the handle, and subsequent drag from the handle created the edge.

**Comment by maxkfranz** [comment]
That sounds like expected behaviour to me.  Maybe there was a bug in a previous release that caused the side effect of different behaviour in this case.

Draw mode has always supposed to be a one gesture mode -- press down on a node and move to the target.

**Comment by maxkfranz** [comment]
There is this feature: 

`cy.edgehandles('start', 'some-node-id')` : start the handle drag state on node with specified id (e.g. 'some-node-id')

**Comment by tonymullen** [comment]
Ok, thanks. I'll experiment with this. I'm not sure I'm fully understanding the utility of 'drawoff' mode, though, as it does still draw the preview/ghost edge, but just doesn't connect it to the target. Is this also as designed?

The previous behavior that I described was important because it was the only way that it was possible to move nodes (by dragging them) and also to create edges (by tapping first and then dragging from the handle). So I hope I can get that behavior back.

**Comment by maxkfranz** [comment]
('drawoff' should be the default state)

**Comment by tonymullen** [comment]
Still a showstopper for me. 

With 'drawoff' the edgehandles appear and the preview (or ghost) edge follows the drag, however the edge will not attach to any target node. So no edges can ever be created in 'drawoff' mode. 

I don't see when it would be desirable for edge handles to appear and edge previews to be drawn but not be able to create edges.

**Comment by maxkfranz** [comment]
[The demo](https://github.com/cytoscape/cytoscape.js-edgehandles/blob/master/demo.html) is working for me and creating edges on Mac on Chrome and Firefox.

Could you clone the repo and try it?  What browser/OS are you using?

**Comment by tonymullen** [comment]
The issue is with touch interfaces. I'm seeing it using Chrome (desktop) on Mac in Device Mode (Developer Tools) or on an Android or iOS device.

**Comment by maxkfranz** [comment]
Should work on edgehandles 2.4.2 and Cy.js 2.7.3 (or master)

Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-586e527dfc-1466453164142.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by tonymullen** [comment]
Great, thanks! It seems to be working now.
