### ISSUE TITLE
cytoscape.js 2.7.0 rendering problems

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1390]
Hi,
I know that version 2.7.0 is not officially released. However, I tried to entegrete its beta version to our application. I see that sometimes the borders of the nodes are not well rendered and node labels are rendered at wrong positions. However, when I perform mouse tap operation on such nodes the rendering problems disappear. See the figures below. 
![render-error](https://cloud.githubusercontent.com/assets/6534865/15652479/32899a98-268f-11e6-85d8-840c6cac4561.PNG)
![render-not-error](https://cloud.githubusercontent.com/assets/6534865/15652487/3b6f20a6-268f-11e6-891a-b35ab223277b.PNG)
The first image represent the case where the rendering mistakes that I mentined can be seen. You can see the left border and label of the top-most compartment are not rendered as expected. The second image represent the case when I have selected the problematic node and these problems disappeared. 
@maxkfranz is it a known problem in the beta release of version 2.7.0. Note that in our application we are overwriting some part of cytoscape.js code this may also cause some problems, but when we do the same thing in the other version such as 2.6.12 everthing was working fine.

**Comment by maxkfranz** [comment]
There are significant architectural changes in 2.7.  You'll probably have to make more significant changes to your fork to get things working.

This will get even harder for you to maintain in future versions.  It's probably easier for you to use extensions instead.
