### ISSUE TITLE
Failed to find file ./version in src/index.js

### ISSUE THREAD

**Issue by xzhu06** [cytoscape/cytoscape.js#1394]
At src/index.js  line 32:
cytoscape.version = require('./version');
File version didn't exist, the version file is version.json
Change to:
cytoscape.version = require('./version.json'); then works.

**Comment by maxkfranz** [comment]
`require('./version')` and `require('./version.json')` are the same.  The filename extension is optional: https://nodejs.org/api/modules.html#modules_all_together

It's working with Node.js 0.10 to 6.2: https://travis-ci.org/cytoscape/cytoscape.js

Can you describe your usecase more?  While changing the `require()` call is safe, I'd like to know what environment is problematic.

**Comment by xzhu06** [comment]
It is third party web platform app - "motion" which using npm install dependencies, when start our web app, it complains "version" not exist. After coping version.json to version will solve the problem.

**Comment by maxkfranz** [comment]
@xzhu06 While we easily can (and will) revise the `require()` call, you should also update your toolchain so it's `require()` spec compliant.  You could easily run into issues with other libs in future...

**Comment by xzhu06** [comment]
Thanks! We will.

**Comment by maxkfranz** [comment]
TODO merge this change onto `unstable`
