### ISSUE TITLE
Background style for source/target labels not taking effect

### ISSUE THREAD

**Issue by sindhukothe** [cytoscape/cytoscape.js#1395]
I have created the following style on an edge: 
{
      selector: 'edge',
      style: {
        'line-color': '#cab07f',
        width: 2,
        'text-events': 'yes',
        'curve-style': 'haystack',
        'haystack-radius': 0,
        'source-label': 'data(srcTp)',
        'target-label': 'data(destTp)',
        'source-text-offset': 30,
        'target-text-offset': 30,
        'min-zoomed-font-size': 10,
        'color': '#000000',
        'text-background-color': '#cab07f',
        'text-background-opacity': 1,
        'text-background-shape': 'roundrectangle'
      }
    },

But background properties are ignored for source & target labels and they always come with no background.

**Comment by sindhukothe** [comment]
I have made an attempt to fix this in my fork with the following changes:
https://github.com/sindhukothe/cytoscape.js/commit/5215432ead19cc6b25d4de0fcba991a1eb0f092d
This seems to be working. Please let me know if these changes are correct.

**Comment by maxkfranz** [comment]
@sindhukothe  While your change may work, I suspect the root of the problem may be elsewhere.  Calculations of labels dimensions should not depend on the prefix.

**Comment by sindhukothe** [comment]
@maxkfranz, Thanks for the comment. I assumed that they do. Because each prefix (source/target) label would have different content and the content would change the dimensions of the label.

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-bfa49775b2-1465242250397.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by maxkfranz** [comment]
@sindhukothe If the snapshot works for you for this and #1399, I'll release 2.7.2 tomorrow.

**Comment by sindhukothe** [comment]
It is working as expected. Thank you for your help;.
