### ISSUE TITLE
Change selectionType after initialization

### ISSUE THREAD

**Issue by peterboot** [cytoscape/cytoscape.js#1396]
Unlike other interaction options it's not possible to change the `selectionType` after initialization. It would be nice to change it like `cy.selectionType('single')` or `cy.selectionType('additive')`.

**Comment by jsalankey** [comment]
I've been doing it by setting the private variable on the Cy instance, but yes, it would be nice to have a setter. It's useful for the case of wanting a regular click to select normally and a ctrl+click to select additively.
