### ISSUE TITLE
3D renderer extension using Three.js

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1398]
This would be a low fidelity, high performance renderer for 3D.  It would be very simple and not support much style properties.

Three.js : http://threejs.org/

**Comment by danbars** [comment]
@maxkfranz Did you have any progress with it?

**Comment by neodigm** [comment]
I have some ideas how this could be done if there is interest.

**Comment by smallstepman** [comment]
I'd love to have it for purpose of visualizing [personal knowledge management system](https://github.com/org-roam/org-roam) I'm running. Currently, the visualization part is made with 2d graphviz: with https://github.com/org-roam/org-roam-server
