### ISSUE TITLE
text-events options seems to be broken in 2.7.1

### ISSUE THREAD

**Issue by sindhukothe** [cytoscape/cytoscape.js#1399]
text-events option is not taking effect in 2.7.1
When I provide 'text-events': 'yes' in my style, the events are not triggered even when I hover or click on the labels.

**Comment by sindhukothe** [comment]
This fix seems to have fixed this issue. Please let me know if this is correct:
https://github.com/sindhukothe/cytoscape.js/commit/70fb00f9c3aa4b653b3647c3f85c1fd9da1f7d6b

**Comment by maxkfranz** [comment]
@sindhukothe Yes, but it's safer to use a truthy check.   That captures 0, null, and undefined.

**Comment by maxkfranz** [comment]
@sindhukothe 

Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-bfa49775b2-1465242250397.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by sindhukothe** [comment]
I verified and it is working good. Thank you for your help.
