### ISSUE TITLE
Update stylesheet in Dagre demo (and others)

### ISSUE THREAD

**Issue by machow** [cytoscape/cytoscape.js#1402]
The stylesheet in the Dagre demo (and others with edge arrows) needs to be updated to look the same as the old thumbnail.  OP follows:

--

It looks like arrows are not appearing, or being drawn inside nodes. For example, viewing the dagre layout demo on the docs shows this for the preview image:

![image](https://cloud.githubusercontent.com/assets/2574498/15805707/378c8f76-2b00-11e6-9ba7-c16e1c06e009.png)

However, clicking to the example shows this:

![image](https://cloud.githubusercontent.com/assets/2574498/15805697/172f2e46-2b00-11e6-90f4-fe9be701c960.png)

I checked it on Google Chrome (Version 50.0.2661.102 (64-bit)), and Safari.

**Comment by maxkfranz** [comment]
The default stylesheet changed to use more performant, haystack edges by default.  Those edges don't support source or target arrows.  The stylesheet of the demo just needs to be updated (or the image).

**Comment by maxkfranz** [comment]
Demos updated.  Visible on Jsbin now, and will be visible on the site in the next docs push
