### ISSUE TITLE
After deleting node network zoom and pan seems to be disabled

### ISSUE THREAD

**Issue by JarrenceMelie** [cytoscape/cytoscape.js#1403]
Hi guys,
When I call remove() function for a node it removes but after that I can't zoom or pan network... It seems very strange for me.
Also, I noticed that after calling remove() function 'userZoomingEnabled' and 'userPanningEnabled' properties equal to false.

If I delete node through browser console with 'net.nodes('#n42').remove()' everything seems to be fine.

I am using version 2.7.0. Code snippet:

``` javascript
network.cxtmenu({
    selector: 'node',
    commands: [{
      content: '<span class="fa fa-trash-o fa-2x"></span>',
      select: function() {
        // remove from graph
        this.remove();

        Meteor.call('updateNodes', {_id: Session.get("docid"), data: network.json()});
      }]
  });
```

**Comment by maxkfranz** [comment]
I suspect you have an issue with either (1) your meteor model sync or (2) removing the element too early using the cxtmenu extension (maybe the extension needs access to the element after `select()`...).
