### ISSUE TITLE
Calling .move() second time on the same node

### ISSUE THREAD

**Issue by mrsfy** [cytoscape/cytoscape.js#1410]
Calling .move() second time on the same node does not work properly, instead it seperates from its edges when dragged.

It has no parent at first.
![bug_cy](https://cloud.githubusercontent.com/assets/13938178/16037604/ea12090c-3229-11e6-81e1-04dd01c51fdd.PNG)
(Id of nodes are their content)
![bug_cy_console](https://cloud.githubusercontent.com/assets/13938178/16037610/ed975c3a-3229-11e6-9dc6-bf80b42511f8.PNG)

Cytoscape version: 2.7.1

**Comment by maxkfranz** [comment]
Seems related to

- Updating compound bounds should happen from the current level up #1413
- When removing elements, all connected compounds should have style updated #1414
- The traversal cache should be cleared on restore() #1415

I think addressing those fixed your issue.

Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-0642437d9c-1466012804119.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by mrsfy** [comment]
It works, thank you.
