### ISSUE TITLE
Child node should move when parent dragged iff `child.grabbable() && !child.locked()`

### ISSUE THREAD

**Issue by gouldingken** [cytoscape/cytoscape.js#1412]
When you drag a parent node with invisible children, the invisible nodes are not dragged with the parent node, however these nodes are still factored into the bounding box calculation. This results in unexpected behavior when repositioning parent nodes.

For dynamic solutions where you show and hide child nodes, it would be preferable for the hidden nodes to also be dragged with the parent so that they maintain the same relativePosition within the parent when they get turned back on.

In this demo, click a node to set its value to 0 which then hides it via a conditional style. Then drag the parent node far enough that the original node falls outside the bounds.
http://jsbin.com/mededot/3/edit?html,output

The same issue occurs for nodes set to display:none and opacity:0

**Comment by maxkfranz** [comment]
Invisible elements are not interactive.

If you want them to be interactive, don't make them invisible.  Use `opacity: 0.00001` or similar.

The following may be useful in future: `display: none` should make node take up no space in parent #1416

However, if you don't want children to be in a parent visibly and w.r.t space, you should just `.remove()` it -- and `.restore()` it later if need be.

**Comment by gouldingken** [comment]
I tried using opacity 0.0001 but is not an acceptable solution because it's not the same as setting display to none. Edges will still be displayed for those nodes. If you set display "none" on either node, the connected edges will be hidden.

Also, your solution #1416 won't help in the example I outlined because the nodes won't be dragged and when they reappear they will no longer maintain the same relativePosition.

Removing and restoring may be a better way to go ultimately, but it's simpler to control the visibility based on a style and I don't see why it can't work this way.

**Comment by maxkfranz** [comment]
We've decided after some discussion to allow this, in the following plan for 3.0:

- `visibility: hidden` and `opacity: 0` will no longer affect interactivity
- `display: none` will disable interactivity and take up zero area
- child moves when parent dragged iff `child.grabbable()`

See https://github.com/cytoscape/cytoscape.js/issues/1092

I'm labelling this as a bug for now.  Otherwise, you'd have to wait until >=3.0.

**Comment by maxkfranz** [comment]
Related : Bounding box calculations should ignore positions for zero area components #1421

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-d2aa0c07b3-1466447977670.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by maxkfranz** [comment]
Since this is working when I tested it, I'm going to release 2.7.3.  If you have any issues with the fix, please include a description and feel free to re-open for 2.7.4.

**Comment by gouldingken** [comment]
This is working great now. Thanks for the quick fix!
