### ISSUE TITLE
How to load cytoscape generating data into cytoscape.js

### ISSUE THREAD

**Issue by hsiaoyi0504** [cytoscape/cytoscape.js#1418]
Hello all:
I already tried the method mentioned here to generate a template and use my own data
https://github.com/cytoscape/cyjs-sample/wiki/Visualize-Cytoscape-Network
But it seems that the method is outdated and is not compatible to newer version cytoscape.
Here is my data used.
Can anyone help me how to visualize these?

cyjs file:
https://drive.google.com/file/d/0BwpSn-wD4D7EeVNON1ExWll5dTg/view?usp=sharing
style.json:
https://drive.google.com/open?id=0BwpSn-wD4D7EVF9oN3ZhLTc1Vmc

Thank you for your help

**Comment by maxkfranz** [comment]
There are tutorials to help you get started: http://blog.js.cytoscape.org/tutorials/
