### ISSUE TITLE
Bug with style properties caching (function values)

### ISSUE THREAD

**Issue by aindlq** [cytoscape/cytoscape.js#1419]
When style value is function caching of style properties can lead to situation when wrong function is selected.

E.g let's say we have a function:

```javascript
  var templateFunction = function(f) {
          return function(data) {
            return f(data)
          }         
  }
```
and then use it in style:

```
style: [
            {
              selector: 'node[?isIri]',
              style: {
                'background-color': '#ad1a66',
                'content': templateFunction((elem) => 'A')
              }
            },
            {
              selector: 'node[?isLiteral]',
              style: {
                'background-color': '#ad1a66',
                'content': templateFunction((elem) => 'B')
              }
            }
]
```

As result, independent from selector, all labels will be "A", because first function is cached. I thik the issue is in https://github.com/cytoscape/cytoscape.js/blob/master/src/style/parse.js#L12, because in both cases function body is the same, second time it is just taken from the cache.

see live example http://jsbin.com/yacihiheha/1/edit?html,output

**Comment by maxkfranz** [comment]
@aindlq  Thanks for the demo.  I verified the change makes the demo work as intended.

Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-a553c9f8eb-1466089211684.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by maxkfranz** [comment]
Since this is working when I tested it, I'm going to release 2.7.3.  If you have any issues with the fix, please include a description and feel free to re-open for 2.7.4.

**Comment by aindlq** [comment]
Sorry for the delay with response. I can confirm that bug was fixed. Thank you!
