### ISSUE TITLE
Bezier edge bundling misaligned when add and remove on same tick

### ISSUE THREAD

**Issue by michalhabala** [cytoscape/cytoscape.js#1420]
Hi, I have updated to CY 2.7.2 (from 2.5.4) and noticed some strange behavior with bezier edges. In my app there are some cases where I need to bulk insert some edges to CY and immediately remove some other edges. After this 2 operations done immediately one after another some bezier edges gets misaligned.

You can reproduce this behavior in [Edges types demo](http://js.cytoscape.org/demos/18504640d9a03c178fff/) from console with these commands:
(1) `ed = cy.add([{ group: "edges", data: { id: "ed", source: "n01", target: "n02" }, classes: 'bezier'}]);`
(2) `ed.remove()`
(3) `cy.add(ed).remove()`

Before executing (1):
![1](https://cloud.githubusercontent.com/assets/9348874/16198217/6aa23dfa-3705-11e6-87fe-b226a5df0803.jpg)

After executing (1):
![2](https://cloud.githubusercontent.com/assets/9348874/16198216/6a7eddc4-3705-11e6-9865-fb6683e6d248.jpg)

After executing (1)+(2)+(3):
![3](https://cloud.githubusercontent.com/assets/9348874/16198215/6a78cd4e-3705-11e6-8b2f-23b1ae52214e.jpg)

**Comment by michalhabala** [comment]
Let me know if you need jsBin example or another form of issue reproduction.

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-586e527dfc-1466453164142.zip


Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by michalhabala** [comment]
Works like a charm. There are no issues with it. Thanks for very fast response!
