### ISSUE TITLE
Allow quoted field names in data selector.

### ISSUE THREAD

**Issue by aindlq** [cytoscape/cytoscape.js#1424]
In my use case I have URI's as data properties, so to use them in selectors I need to escape all special characters. In the end I end up with very ugly selectors like:

```node[http\\:\\/\\/www\\.w3\\.org\\/2000\\/01\\/rdf-schema\\#label *= 'Alice']```
Do you think it would make sense to allow quoted field names, so one can use any characters inside them, so previous example will become: 
```node['http://www.w3.org/2000/01/rdf-schema#label' *= 'Alice']```

I can create a PR. Just want to ask if you think it is feasible and OK to have this extension to selector syntax.

**Comment by maxkfranz** [comment]
If you want, you could make a PR for 3.1.  You'd have to `npm install` from the git repo pointing to the `unstable` branch or do manual builds yourself until 3.1 is released.

Note that you can already do what you want without having to manually escape:

- You could use a function to escape URIs (either inside a whole selector string or just the URI itself) and wrap your selectors with it.  You could even use the extra quote syntax you proposed, if you like, e.g. `cy.$( u("node['http://www.w3.org/2000/01/rdf-schema#label' *= 'Alice']") )` where `u()` escapes the URI
- You could use function values in your stylesheet, e.g. `.selector('node').style({ 'background-color': getColor })` where `getColor()` can just use `node.data( someUri ) === 'Alice'`
- You can use filter functions outside of the stylesheet, e.g. cy.nodes(function(){ return this.data( someUri ) === 'Alice' })

My suggestion would be to use one or more of the above.  It's probably much easier / less time to implement.

If you do decide to do a PR, please write some unit tests for the new syntax and make sure the old selector tests still work.  My intuition is that it will be difficult to implement, as the addition could create some ambiguous cases.  The selector functionality is very important and high risk (as it touches every usecase), so any major change like this would need a lot of unit tests to make sure it's still reliable.

Thanks for the feedback

**Comment by aindlq** [comment]
Thank you for suggestions, I've looked into the parser logic and indeed it is quite complex. So I decided to make some pre-processing of selectors and escape URIs before they get into cytoscape.
E.g `"selector": "node[iri('http://www.w3.org/2000/01/rdf-schema#label') *= literal('Alice')]"`, then I look for `iri` and `literal` patterns and replace them with escaped values.
