### ISSUE TITLE
Start edges from node center

### ISSUE THREAD

**Issue by cDor** [cytoscape/cytoscape.js#1426]
When drawing wide edges, the rendering generates the following result:

![screenshot from 2016-06-23 17 11 57](https://cloud.githubusercontent.com/assets/7893498/16308882/f9c57304-3966-11e6-8f43-98a0f55a2284.png)

Since I don't need an arrowhead for the source of the edge, I want to place the source position at the center of the node.

I have found a solution by changing the [these lines](https://github.com/cytoscape/cytoscape.js/blob/703935a6f2412fd4780b7b70b4c973182200fb5e/src/extensions/renderer/base/coord-ele-math.js#L2030-L2031)

`rs.startX = srcPos.x; //edgeStart[0];`
 `rs.startY = srcPos.y; //edgeStart[1];`

![screenshot from 2016-06-23 17 12 36](https://cloud.githubusercontent.com/assets/7893498/16309109/de4fbe08-3967-11e6-9e05-773cb2c34339.png)

It would be nice to have a css property for that. This should be open to discussion.

**Comment by maxkfranz** [comment]
Maybe properties like `edge-source-endpoint: node-body | center`, `edge-target-endpoint: node-body | center` that would act as simple toggles.

This wouldn't affect haystack edges, as they already point inside a node: http://js.cytoscape.org/#style/haystack-edges

**Comment by maxkfranz** [comment]
There's overlap with this issue, so the feature should probably be merged into one property: https://github.com/cytoscape/cytoscape.js/issues/1454

**Comment by maxkfranz** [comment]
Should be possible in 3.1 as a subset (e.g. `source-endpoint: inside-to-node`) of this feature:
`source-endpoint` & `target-endpoint` to specify the intersection/starting/ending points of an edge #1613
