### ISSUE TITLE
MutationObserver.observe does not implement interface Node

### ISSUE THREAD

**Issue by kikki** [cytoscape/cytoscape.js#1429]
Hello in my small project I use for the first time angularjs and cytoscapejs.
I not include cy in angular (dirty work). First I load cy after this load angular. It work. 
But sometimes (not often!) I have Error before it finished load cy.  I can not  error reproduced. Error is: TypeError: Argument 1 of MutationObserver.observe does not implement interface Node.
 cytoscape.js:14505:1 (It is cytoscape.js; V. 2.7.2). 
My questions are: 
(1) What can this error mean?
(2) what for a cause could this error message have?
(3) How can I fix it?
All ideas are welcome.
in advance thank all.

**Comment by maxkfranz** [comment]
Possibly you're not waiting for `DOMContentLoaded`.

**Comment by kikki** [comment]
Hi maxkfranz :-).  Thanks for Input
I thought this at first, too.
cy is init in $(document).ready(function(){cy});
I tested $(document).ready(function(){
					setTimeout(function() { cy}, 200);});
and $(window).load(function() {cy}); too. 
I don´t tested (function () {}) ();
Sometimes  r.container :  [object HTMLDivElement] it invites.
Sometimes is r.container : [object Object] and Error.
If I set r.container = this.cy.container(); Error exist  too.

What makes cytoscape.js: 14505? What will be set on this position in cy?

**Comment by maxkfranz** [comment]
I can't say what the issue might be without a demo that reproduces it.  I've never seen this behaviour.

If everything works without Angular, then I suspect you've done something in your Angular code that may be unstable.

**Comment by kikki** [comment]
For information:
I had initialized controller after DOM with
angular.bootstrap(...);
Now I initialize angularjs in HTML-Code.
Until now I had no error message ....
Thus, I  assume that the processes require asynchronous of mutual resource ...
