### ISSUE TITLE
An empty component with display: none children 

### ISSUE THREAD

**Issue by mrsfy** [cytoscape/cytoscape.js#1431]
It is undraggable. It might be unhandled case. I applied `display: none`

It is when it still has visible children
![bug_okey](https://cloud.githubusercontent.com/assets/13938178/16384485/b27679f2-3c91-11e6-8a8b-7be198575153.PNG)

But when `display: none` is applied to all children parent transforms far away from screen and becomes undraggable.
![bug_notok](https://cloud.githubusercontent.com/assets/13938178/16384484/b2750568-3c91-11e6-9cc6-48758d3fd81e.PNG)

Sorry for misclick submission at first.

Edit: http://jsbin.com/kakixo/6/edit?js,output here I applied 
`{ selector: "#a, #c", css: { "display": "none" } }`
a and c are children of b

**Comment by maxkfranz** [comment]
Having all children as `display: none` is a problematic state.  `display: none` means the element should take up zero area.

All children `display: none`
=> The parent is still a parent node, because it has children
=> The parent no longer has a bounding box defined, because it is defined by the children's dimensions

**Comment by mrsfy** [comment]
Makes sense now, thanks.

**Comment by finger563** [comment]
Why can the parent not be sized based on either set or default `width`, `height`, and `padding` properties?  It doesn't make sense to have to remove the child elements, keep track of them, and then restore them later when all we want to do is hide the children from being rendered (and have the parent size and total used area recalculate accordingly).

**Comment by maxkfranz** [comment]
@finger563 See https://github.com/cytoscape/cytoscape.js/commit/a3da6558d0014cba1256d28f750736f6dc9f9a9e for 3.2

**Comment by finger563** [comment]
@maxkfranz I think that might have been my issue then; I was using an older cytoscape install that was `v2.x`.  I'll try porting my code over to `v3.x` and see if that performs how I like :)  Thanks!
