### ISSUE TITLE
2.7.x does not show multiple edges

### ISSUE THREAD

**Issue by fracz** [cytoscape/cytoscape.js#1438]
The graph rendered in 2.6.x has multiple edges rendered ([2.6.x fiddle](http://jsfiddle.net/rbuj3o9c/37/)):

![image](https://cloud.githubusercontent.com/assets/3918865/16516585/11609e5e-3f79-11e6-993c-a044150fe12a.png)

The same graph in 2.7.x does not have them ([2.7.x fiddle](http://jsfiddle.net/rbuj3o9c/38/));

![image](https://cloud.githubusercontent.com/assets/3918865/16516597/1be73acc-3f79-11e6-8af8-830e5ae401ff.png)

Is there any new configuration option I am missing?

**Comment by maxkfranz** [comment]
See https://github.com/cytoscape/cytoscape.js/issues/1408
