### ISSUE TITLE
Trigger 'destroy' event when cytoscape instance is destroyed.

### ISSUE THREAD

**Issue by aindlq** [cytoscape/cytoscape.js#1440]
I can see that many extensions have destroy function defined, e.g. 
https://github.com/cytoscape/cytoscape.js-panzoom/blob/master/cytoscape-panzoom.js#L77
https://github.com/cytoscape/cytoscape.js-navigator/blob/master/cytoscape-navigator.js#L300

But right now one need to manually call all destroy methods.

Would be great if cytoscape destroy all extensions on instance destroy event automatically.

**Comment by maxkfranz** [comment]
Not possible.  Each extension has its own API and there are no restrictions on what those APIs include and what signatures they have.

You need to manually call `destroy()` or remove the container DOM element to clean up a Cytoscape instance anyway -- so you may as well handle each extensions at the same time.

Cytoscape itself can make no assumptions.  The only way to automate this would be on the extension side, for each extension.  They could listen for a `destroy` event and destroy themselves at that time, but no such event exists currently.

**Comment by aindlq** [comment]
ok, I see. I think the `destroy` event is the way to go. I've changed title of the issue accordingly.

**Comment by EyMaddis** [comment]
see PR #1527

**Comment by maxkfranz** [comment]
Added via @EyMaddis' PR

Thanks
