### ISSUE TITLE
Update compound demo stylesheet

### ISSUE THREAD

**Issue by cavei** [cytoscape/cytoscape.js#1442]
Hi all,
in the "compound nodes" thumbnail at the http://js.cytoscape.org/ homepage there is an arrow between "a" and "d".
When you open the example (http://js.cytoscape.org/demos/5b192c88616af2f75344/) in both firefox and chrome, the arrow between "a" and "d" disappears.

Is this a bug or something expected?

Thanks

**Comment by maxkfranz** [comment]
Revised
