### ISSUE TITLE
"text-align-*" property of stylesheet is not working while using cytoscape.js via npm

### ISSUE THREAD

**Issue by istemi-bahceci** [cytoscape/cytoscape.js#1449]
I have been having trouble using "text-align-*" property in my stylesheet. It has no effect on the graph, I've observed that this happens when using cytoscape.js by using `require()` in CommonJS/Node.JS  style. It works when I include cytoscape.js from HTML file using: `<script src="http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-latest/cytoscape.min.js"></script>` file. Could not figure it out what goes wrong.

**Comment by maxkfranz** [comment]
Works for me

[text-align.zip](https://github.com/cytoscape/cytoscape.js/files/357693/text-align.zip)
