### ISSUE TITLE
Field values in $= or ^= selectors can be wrongly compared for metachar-containing values

### ISSUE THREAD

**Issue by aindlq** [cytoscape/cytoscape.js#1450]
Documentation says that metacharacters need to be escaped in selectors, as I understand the reason for that is that some operators are using regex. But for example simple equality operator doesn't use any regex for matching (https://github.com/cytoscape/cytoscape.js/blob/master/src/selector.js#L595), and as a result it is behavior is quite inconsistent when compared to other operators.

Lets say I have quite strange data value:
```
"->count": "\"2\"^^<http://www.w3.org/2001/XMLSchema#integer>"
```

To match node with this value using simple equality I need to escape left operand but don't right operand:
```
'node[-\\>count = \'"2"^^<http://www.w3.org/2001/XMLSchema#integer>\']'
```

But to match the same node using containment operator `*=` I need to escape both operands:
```
'node[-\\>count *= \'"2"\\^\\^<http\\:\\/\\/www\\.w3\\.org\\/2001\\/XMLSchema\\#integer\\>\']'
```
Example can be found here http://jsbin.com/gowipomure/edit?html,output.

I see two solutions. Or it should be documented as intended behavior or value should be cleaned from metacharacters with cleanMetaChars function.

Any ideas?

**Comment by maxkfranz** [comment]
If I remember correctly, I don't think you should escape string values enclosed in quotes.  You escape tokens like field names.

I've added extra tests to confirm this is working: `mocha -g Selectors`

```
...

    ✓ [weird\.name = 1]
    ✓ [weird\.name2 = "weird.val"]
    ✓ [weird\.name2 *= "d.v"]
    ✓ [weird\.name2 ^= "weird."]
    ✓ [weird\.name2 $= ".val"]
```

**Comment by aindlq** [comment]
It seems that something is wrong with `^` character. See https://github.com/aindlq/cytoscape.js/commit/bb0e36854016336bdf0f85e14278e15e84e376ab

**Comment by maxkfranz** [comment]
The commit fixes has the tests behaving as expected.

Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-367077a893-1468335227910.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by aindlq** [comment]
Works fine for me. Thank you!
