### ISSUE TITLE
Loosen bezier validity checks

### ISSUE THREAD

**Issue by fedarko** [cytoscape/cytoscape.js#1451]
Hi,

While using the `unbundled-bezier` and `segments` edge settings, I've noticed that certain edges aren't visible after rendering the graph, and only become visible upon the user dragging their source or target nodes. (I noticed the problem was also present in some cyclic `bezier` edges.) I did a bit of digging, and it looks like some of these particular edges are flagged internally as `badBezier` edges (accessible for an arbitrary edge `e` via `e._private.rscratch.badBezier`), although some edges that exhibit this problem still have `badBezier === false`.

I understand that some edges may just be impossible to draw using `unbundled-bezier` or `segments` edges, but all of the edges I use in the examples here are fairly simple and seem like they shouldn't be impossible to draw.

I've identified two main types of these problems, each of which is indicated in the provided example (the code is accessible in JSBin [here](https://jsbin.com/rasejokigo/edit?html,js,output), and it's runnable also on JSBin [here](https://output.jsbin.com/rasejokigo)).

**Case 1.**
- `unbundled-bezier` edges that are not labelled as `badBezier` (from what I've seen, seems to be caused by a `control-point-weight` of exactly 0 or by some straight-line edges)

The edges in this case (an example of an edge exhibiting this problem is the edge from 1 to 2 in the provided code) are only occasionally visible when dragging its source or target node, and even then (on my system, at least) seem to "flicker" between being visible and invisible. (I'll discuss the straight-line problems below in case 2, as those can result in `badBezier` being true or false. Also, some straight-line invisible edges [e.g. edge 3 -> 4 in the provided code] seem to not have the "flickering" problem.)

*Workaround*: Changing the first `control-point-weight` from 0 to 0.01 seems to fix this problem; as a cursory guess, maybe the control point weights are used as divisors somewhere in the edge calculations?

Also, using `'edge-distances': 'node-position'` for this edge actually just makes the problem worse, resulting in no edge (not even a flickering one) being rendered at all. I understand that a `control-point-weight` of 0 indicates that an edge's control point is located "in line" with either the outside (if `edge-distances` is set to `intersection`) or center (if `edge-distances` is set to `node-position`) of the source node—is a control point weight of 0 invalid, or otherwise semantically meaningless? (If so, this would be a good thing to mention in the Cytoscape.js documentation on `unbundled-bezier` edges.)

**Case 2.**
- `unbundled-bezier` edges that are labelled as `badBezier` (I'm not sure what exactly causes these, aside from certain types of lines)

The edges in this case (`badBezier === true`) are somewhat harder to classify, I think. Both straight lines (e.g. 3->4 in the provided code) and curved lines (e.g. 5->6 in the provided code) can suffer from this problem. In this case, the edges don't have the "flickering" problem—they're just not immediately visible until their source/target node are dragged, which can be confusing to users.

*Workaround*: I currently use a simple workaround when processing an edge's control points where, if the magnitude of each control point's `control-point-distance` is less than some epsilon value (I'm using a relatively conservative value of 1.0 for now)  **or** the edge is self-directed, then the edge is just rendered as a normal `bezier` instead of an `unbundled-bezier` curve. (This accounts for straight-line edges and for self-directed edges.)

However, I think there may be other cases where this behavior manifests—the edge between nodes 5 and 6 in the provided code is an example of a `badBezier` that isn't fixable using only this workaround.

**Other issues with unbundled-bezier/segments edges**

This is fairly minor in comparison, but unless I'm mistaken the current way of defining relative edge control points makes representing self-directed unbundled-bezier edges (aka loops) impossible. Since there is no "line" from source to target when the source and target are the same node and therefore in the same position, you can't really represent the perpendicular distance or weight of a given control point.

This isn't that big of a deal (like I mentioned, I just convert all loops to basic `bezier` edges), but it might be worth mentioning in the documentation that loops aren't supported for `unbundled-bezier` and `segments` edges. (One possible way to circumvent this would be to implement coordinates relative to just the node's position, but I'm not sure of the best way to go about that and this is a pretty minor issue.)

**Other details**
For reference: this issue persists for me in both Chromium 49.0.2623.108 and Iceweasel 38.7.1. My computer runs Debian 8.4. I copied the latest version of [cytoscape.min.js](http://cytoscape.github.io/cytoscape.js/api/cytoscape.js-latest/cytoscape.min.js) into the JSBin in order to get it to run properly, so these issues seem to be present in at least Cytoscape 2.7.5 and Cytoscape 2.7.4 (which is what I've been working with for the past few days).

Thanks for all of your work on Cytoscape.js! It's been very useful for the project I'm currently working on.

**Comment by maxkfranz** [comment]
(1) Control point weights of 0 for the first specifies point or 1 for the last one never make sense.  There are implicit points already there.

(2) If any of several intersections can't be made, the bezier is bad and impossible to draw.

> This is fairly minor in comparison, but unless I'm mistaken the current way of defining relative edge control points makes representing self-directed unbundled-bezier edges (aka loops) impossible. Since there is no "line" from source to target when the source and target are the same node and therefore in the same position, you can't really represent the perpendicular distance or weight of a given control point.

Yes, loops may only be beziers or unbundled beziers.  You may customise the control point distance.  You may also control the direction in 3.1: https://github.com/cytoscape/cytoscape.js/pull/1391

**Comment by maxkfranz** [comment]
Your demo corrected : https://jsbin.com/nawigedeqo/edit?html,output

5->6 is maldesigned for smaller distances.  You need to design your points more robustly, or they will fail at certain orientations.  You probably shouldn't be putting curved edges going out the opposite way -- that's making it almost guaranteed you'll have problems.

The more you customise edges, the more likely you are to have problems and the more careful you'll have to be.  There isn't much if anything the lib can do to help you in an automated way in those cases.

**Comment by maxkfranz** [comment]
Your demo corrected : https://jsbin.com/nawigedeqo/edit?html,output

**Comment by fedarko** [comment]
Thanks for your response! I didn't know that there were implicit points used in unbundled bezier edges, but that makes sense. It might be something helpful to add to the documentation for unbundled bezier edges, since I don't see it mentioned anywhere.

> Yes, loops may only be beziers or unbundled beziers. You may customise the control point distance. You may also control the direction in 3.1: #1391

This is great, thank you for letting me know!

> The more you customise edges, the more likely you are to have problems and the more careful you'll have to be. There isn't much if anything the lib can do to help you in an automated way in those cases.

That's entirely fair. I'm using another graphing library to generate the layouts of large graphs and then render those layouts in Cytoscape.js, and that library uses static control points (i.e. stored as absolute coordinates) for B-spline edges in order to minimize edge crossings. The 5->6 edge is an example of one of these auto-generated edges; I can automatically convert the control points to the relative format used in Cytoscape.js, but it looks like I might have to do some more work to verify that the edge is a valid Bezier curve.

Out of curiosity, do you think it would be feasible to implement something in the Cytoscape.js side that, on detecting that an edge is impossible to draw, just draws it as an ordinary bezier/haystack edge? I think a feature like that might be useful—from a few minutes of playing with [coord-ele-math.js](https://github.com/cytoscape/cytoscape.js/blob/6608346ac9d94a6eb10e9d6b361e2f255cb45c2b/src/extensions/renderer/base/coord-ele-math.js), I found a simple (if flawed) way to show badBezier edges as visible, simple bezier edges on the graph's initialization by changing line 1327 to
`var curveStyle = badBezier ? 'bezier' : edge.pstyle( 'curve-style' ).value;`
`badBezier = false;`

However, there's more that would need to be done to get this consistently working. If you think it'd be worthwhile, I can try to implement such a feature in Cytoscape.js (and then make a pull request). Ideally, a feature like this would be configurable by the user, so that they can 1) only use it if they want to show beziers/haystacks in place of impossible unbundled-bezier/segments, and 2) choose the fallback edge type (e.g. bezier vs. haystack).

**Comment by maxkfranz** [comment]
I don't know that it would make the situation much better for invalid beziers.  Any bezier needs its points calculated correctly to be drawn.  For invalid beziers, you can't fall back on another bezier.  That would require another calculation -- so that's out.

You could fall back on haystacks of radius 0 for bad edges -- i.e. when the renderer bails out on bezier or segment edges.  I suppose it would be a bit better than showing nothing.

**Comment by fedarko** [comment]
Ah, got it. I usually just think of single beziers as straight lines, but I suppose for really small distances or for the case of multi-edges we can't rely on that case.

A pertinent question: in the original demo I provided ([here](https://output.jsbin.com/wacujek/1)'s the demo's output—I set up a JSBin account and cloned the demo, so the output should be persistent), edge 5->6 actually renders at a smaller distance than what it's originally set to. It also renders fine at most larger distances. Only when the gap between nodes 5 and 6 gets really small, smaller than the original gap size, does the renderer bail out, which brings up an interesting point: it looks like the initial rendering process (on rendering the graph) is **too cautious**, and rejects what would otherwise be considered valid edges. I've provided another JSBin clone of the demo (output [here](https://output.jsbin.com/gugobo), code [here](https://jsbin.com/gugobo/edit?html,js)) in which the initial detection of badBezier edges is commented out, and that fixes this problem: 5->6 shows on rendering the graph, and it only disappears when the gap between nodes 5 and 6 gets small—since, as you mentioned, the edge is "maldesigned for smaller distances." (The effects of this change can be observed by un-commenting-out the initial badBezier detection process, which can be found by ctrl-F'ing for "README" in the accompanying cytoscape.js file.)

Is this "cautiousness" of the initial renderer expected behavior, and do you think commenting out the initial bad edge detection is a sustainable solution (or might it have some harmful side-effects)? The commenting-out thing solves most of the "invisible" problems I was having with unbundled-bezier edges, and implementing haystacks with a radius 0 as a fallback would solve the rest of the problems.

Thank you for your help!

**Comment by maxkfranz** [comment]
I've loosened the bezier check a bit, but that won't solve your problem.  It may give you ~10% or so more of the time that an edge can be rendered, but your problem will still exist.  It's better to fix your edges so they work in the *general* case. 

Edges like 5=>6 shouldn't really loop around like that.  To loop around properly, you'd have to calculate the min distance the first point should be away relative to the node size.  It's better/easier use a bezier with a large control point distance, and you'll get always valid edges -- and better looking, symmetric edges.   See https://jsbin.com/tiqocuguju/1/edit?output which has all your cases corrected using the latest snapshot

If your edges don't work in the general case, then you could use static graphs -- where nodes are never moved, added, or removed.

After a review, fallbacks to haystacks are not possible.  The renderer can bail out too late in the pipeline for an edge for this to be possible.  It would also be inconsistent with other failure cases, so it would be too confusing.

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-63b320ae28-1468863233346.zip

**Comment by fedarko** [comment]
Thank you for the help and advice!
