### ISSUE TITLE
Node style get lost when playing with compounds nodes

### ISSUE THREAD

**Issue by gulian** [cytoscape/cytoscape.js#1452]
I'm updating to Cytoscape 2.7.3 and I'm having trouble with my graph style. Compounds node seems to have trouble to reload styles when moving in and out nodes.

I'm using move() to define hierarchy between nodes : node.move({ parent: parent.id });

I finally succeed to reproduce the issue with a few lines of code (Firefox, Safari & Chrome) : http://jsbin.com/quricilavu

In this case, i'm removing and adding node A to node B. We can see two problems: 
- Visually, the node doesn't seems to be removed from the parent one
- The child is loosing its style 
- (in my case, the parent often lose its style too, but I can't reproduce it) 

Here a screen capture, just in case : 
![kitten_groups](https://cloud.githubusercontent.com/assets/487387/16730688/a6e34cee-4774-11e6-96f0-e05cff0747c9.gif)

**Comment by maxkfranz** [comment]
See #1460
