### ISSUE TITLE
edge-pointing-direction to control edge endpoint position

### ISSUE THREAD

**Issue by gulian** [cytoscape/cytoscape.js#1454]
`edge-pointing-direction: inside | outside`

- `inside` : edge points towards the node center points
- `outside` : edge points towards the intersection point on the node shape, from the source-target position line

The `outside` value helps to avoid impossible bezier conditions, especially for compound nodes.

This can be extended to take on two numbers to specify a different internal point.

`edge-pointing-direction: inside` (default):

<img width="597" alt="screen shot 2016-09-29 at 4 53 24 pm" src="https://cloud.githubusercontent.com/assets/989043/18972046/90316686-8665-11e6-90e0-731d0a8d9953.png">

`edge-pointing-direction: outside`:

<img width="596" alt="screen shot 2016-09-29 at 4 52 53 pm" src="https://cloud.githubusercontent.com/assets/989043/18972060/9afc5f94-8665-11e6-83f7-c1b0b855ba5a.png">

OP:

---

Hi again, 

When they are more than one edge between two nodes, and they are begin to be too close, some edges are disappearing. 

Here an example: http://jsbin.com/hecumuroxu/

In this example, there is two edges between `B` and `E`, but only one is displayed. If you move around the `E` node, the second edge is appearing.

Here a screen capture : 

![kitten_groups2](https://cloud.githubusercontent.com/assets/487387/16763081/94e4a890-4827-11e6-9b4d-1604d7d12cbd.gif)

I've tried to play with edge style and type, but the problem remains.

Thanks again for your help !

**Comment by maxkfranz** [comment]
You have to alter your control point distances for the sizes of nodes you are using.  If you have an impossible edge (e.g. no points, no intersection, etc.), then it can't be drawn.

I have a branch that allows you to specify where the edges should bundle/point (centre position which is the same as today, or outside shape position).  This should help with compounds, but it's incomplete (arrows don't work).
