### ISSUE TITLE
Style error when calling ele.move on the same element multiple times during batch

### ISSUE THREAD

**Issue by fedarko** [cytoscape/cytoscape.js#1455]
Hi --

After calling `.move()` **on an edge** twice within the same batch operation, the edge turns into a thick directionless line. Clicking on the edge (but not necessarily selecting it) makes it change back to normal.

This seems to affect both asynchronous (`cy.startBatch(); ... cy.endBatch();`) and "normal" (`cy.batch(function() { ... });`) batching.

A workaround I developed when I first encountered this problem (having to move large amounts of edges, some of them twice) was to define a mapping where each edge maps to another mapping, which could be either `{'source': [new source]}`, `{'target': [new target]}`, or `{'source': [new source], 'target': [new target]}`. By updating this mapping and then iterating through it, we can apply the move operation to all the edges without this style problem while using a single batch operation.

Similarly, after calling `.move()` **on a node** twice within the same batch operation, the node loses its label and becomes smaller. (This seems like the node is just reverting back to the default node style.) As with the "thick line" problem with edges, clicking on the affected node changes it back to normal.

I haven't thought of a workaround for this problem yet (I was curious to see if `nodes.move()` faced a similar problem as `edges.move()`, which is how I discovered this), but I'd guess you could probably use a similar approach to the workaround I described above for moving edges. However, since a node can only have one parent at a time, you would probably just want to keep track of a single "parent" value for each node—making this a simpler 1-dimensional mapping.

A demonstration of these errors is viewable on JSBin [here](https://output.jsbin.com/lapaxok), and the  code for the demonstration is also viewable on JSBin [here](https://jsbin.com/lapaxok/edit?html). (The code draws 12 nodes in random positions, encapsulates nodes 1, 2, and 3 in a parent node, and draws an edge between nodes 6 and 5. From there, you can move (in batch or in non-batch):

- the edge in the graph to have a different source and/or target
- any node in the graph (...except for the "Parent" node, I suppose, since making a node its own parent doesn't really make sense) to be a child of "Parent" and then not a child of "Parent"

These actions (contained in the simple functions `moveEles()` and `moveNode()`) highlight both of the issues described in this report.

This issue persists for me in Chromium 49.0.2623.108 and in Iceweasel 38.7.1 on a computer running Debian 8.4. The provided demonstration uses Cytoscape 2.7.5, although these problems (or at least the case regarding moving edges) exist in Cytoscape 2.7.3 as well.

**Comment by gulian** [comment]
Hi, 

May be related to https://github.com/cytoscape/cytoscape.js/issues/1452

Gulian

**Comment by maxkfranz** [comment]
See #1460
