### ISSUE TITLE
removeClass() has no effect on ele.json()

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1458]
Hi,
I am not sure if this problem is special to ele.json() I think that it may be more general. I executed the code line below,

"edge.removeClass('edgebendediting-hasbendpoints');"

However I realized that "edge.json().classes" still includes 'edgebendediting-hasbendpoints'.
Then I realized that 'edgebendediting-hasbendpoints' is still included in 'edge._private.classes'. I am able to solve my problem with  a temprorary workaround by executing 
"delete edge._private.classes['edgebendediting-hasbendpoints'];" right after "edge.removeClass('edgebendediting-hasbendpoints');"

But I think that there is a kind of bug here.

**Comment by maxkfranz** [comment]
Issue from : https://github.com/cytoscape/cytoscape.js/commit/e5579e2ec1fd4445f0ef04b2dad31c39a5826b34#diff-0a12ab28e95ef60c35904eebf53d64e7L226

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-06af91ea3f-1468853599115.zip


Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by metincansiper** [comment]
Upgrading the Cytoscape.js version is not so easy for me. Therfore I could not directly try the snapsot. However, I see that I already have the changes in 'e5579e2#diff-0a12ab28e95ef60c35904eebf53d64e7L226'. Then I have adopted the 'elesfn.json' method in 'http://js.cytoscape.org/download/cytoscape.js-snapshot-06af91ea3f-1468853599115.zip'. It seems that this problem is solved for me. Thanks.
