### ISSUE TITLE
Batching doesn't update style for ID collisions

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1460]
The list of elements queued to update style when batching ends can have collisions of ID.  The ID collides when one element is removed and another element is added with the same ID.  This happens when calling `.move()`, for example.

See
- Style error when calling ele.move on the same element multiple times during batch #1455
- Node style get lost when playing with compounds nodes #1452

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-6bb0704146-1468857474391.zip


Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by fedarko** [comment]
The snapshot works for me. Thank you!

**Comment by gulian** [comment]
The snapshot works for me too ! And the performances doesn't seems to be affected. 

When do you plan to release v2.7.6 ?

Thanks a lot!
