### ISSUE TITLE
Strange issue with renderer binding registration

### ISSUE THREAD

**Issue by jsalankey** [cytoscape/cytoscape.js#1461]
I recently upgraded my app from 2.6.3 -> 2.7.5 and started encountering a very strange problem with mousemove bindings not being registered properly (among others). The problem was traced to [load-listeners.js:28](https://github.com/cytoscape/cytoscape.js/blob/42808747eb30ec2f3fc5f480ae0f6ab4dfb91ca8/src/extensions/renderer/base/load-listeners.js#L28). The adding of the listener prefers `tgt.on` as its adder function. This is problematic with some minifiers (like the Closure Compiler we use) because the `window.on` symbol can be set to something arbitrarily chosen by the compiler (in my case it was set to the `Math.cosh` native function and was failing to add the listener silently because it didn't throw an exception).

This is unlikely to happen to other people, but to ensure that it doesn't, the `addEventListener` method could be preferred here. I was able to work around it by forcing the compiler to never use the `window.on` symbol, but it took me quite a while to find the problem in the first place.

**Comment by maxkfranz** [comment]
Since there's an `addEventListener` alias for elements now it's really the only one needed.  Would you please make a PR on master for the change if you can confirm it working for your case?

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-b9e0c50595-1469113017454.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by jsalankey** [comment]
This fixes the problem, thanks.
