### ISSUE TITLE
width: label not in effect when all children removed from compound node.

### ISSUE THREAD

**Issue by aindlq** [cytoscape/cytoscape.js#1463]
When all children are removed from compound node sometimes it still behaves as compound node. 

E.g `"width": "label"` and `"height": "label"` styles are not applied to the node. See http://jsbin.com/fujocekaso/1/edit?html,output.

Also see  https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/issues/7

**Comment by maxkfranz** [comment]
Not a bug.  If you remove the children from node A, then A is no longer a parent and you can't expect a `:parent` selector to match it.

Use a different selector, like a class.

**Comment by maxkfranz** [comment]
I missed the "sometimes" part.  I've refreshed the demo dozens of times, and it worked as expected every time.

**Comment by aindlq** [comment]
Look into selectors. There is `node` selector with `"width": "label"` and `"height": "label"`. My expectation was that this selector will be applied to the node when it is no longer compound node. But it is not applied.

**Comment by aindlq** [comment]
Ok, selector is actually applied. See http://jsbin.com/qeyibukeqi/1/edit?html,output
Node changes the color from green to yellow, but it doesn't change the size.

**Comment by maxkfranz** [comment]
Oh, you're talking about `width: label`.  I was confused by the link to expand-collapse...

**Comment by aindlq** [comment]
Sorry for the confusion, I've just added it to show how actually I've ended up in this situation. Initially I was thinking that this is expand-collapse related issue.

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-6bbf986aff-1469201769761.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by aindlq** [comment]
That was blazingly fast! I can confirm that issue was fixed. Thank you!
