### ISSUE TITLE
Updating data mapping for a node's shape-polygon-points doesn't redraw the node

### ISSUE THREAD

**Issue by fedarko** [cytoscape/cytoscape.js#1465]
[Here](https://jsbin.com/vusoqat/edit?html,js)'s a link to the code for this issue on JSBin, and [here](https://output.jsbin.com/vusoqat)'s a link to a demo of the issue. (The initial values of the two text fields correspond to the initial values of node "1".)

As you can see, modifying the node's `shape` value (through the node's `data(thisshape)` mapping) yields an immediate update to reflect the node's new shape. However, modifying the node's `shape-polygon-points` value (through the node's `data(polypts)` mapping) produces no changes.

Here's a way to recreate the error:

1. Modify the node's polygon points (e.g. by removing the last (x, y) point from its definition, to change the trapezoid to a scalene triangle) and click the "Modify Node shape-polygon-points" button. No observable change happens to the node.
2. Modify the node's shape from `polygon` to, say, `ellipse` (any non-polygon shape will work) and click the "Modify node shape" button. The node will change to the new shape given, overriding the `shape-polygon-points` value (which is expected behavior, since that attribute only applies to `polygon` shapes).
3. Change the node's shape back to `polygon` and click the "Modify node shape" button again. **Now** the new `shape-polygon-points` attribute of the node will be visible.

This issue persists for me in Cytoscape 2.7.6, in both Chromium 51.0.2704.79 and Iceweasel 38.7.1, on a computer running Debian 8.4.

**Comment by maxkfranz** [comment]
Bug in canvas path caching: key doesn't take into account polygon points

Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-c93950f64e-1469452218986.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by fedarko** [comment]
The snapshot works perfectly—thank you for your help!
