### ISSUE TITLE
Text borders not rendering when zoomed out

### ISSUE THREAD

**Issue by YacoobHolden** [cytoscape/cytoscape.js#1467]
Using cytoscape version 2.7.6 on Chrome 51.0.2704.103

I have added a border around labels on my nodes, as I found the default labels did not leave enough space around the label at larger font-sizes. This looks great when zoomed in, but upon zooming out (even marginally), the borders are not rendered.

<img width="439" alt="nomargins" src="https://cloud.githubusercontent.com/assets/8241933/17122898/a54028b0-5333-11e6-9cf6-ed6e506ebda9.png">

**Comment by maxkfranz** [comment]
(1) A border on the label does not shift the label, e.g. the red border overlays the node and the background

![screen shot 2016-07-26 at 11 03 56 am](https://cloud.githubusercontent.com/assets/989043/17143230/b477d66a-5320-11e6-8493-e7dbd3c2f233.png)

A margin shifts the label

(2) Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-2c463ef773-1469546291655.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by maxkfranz** [comment]
@YacoobHolden I'm planning to release 2.7.7 Tuesday.  Does the snapshot work for you?

**Comment by maxkfranz** [comment]
I've testing this working, so I'm closing the issue

**Comment by YacoobHolden** [comment]
@maxkfranz apologies about the delay - snapshot resolves my issues! Thanks!
