### ISSUE TITLE
Bounding boxes for edges not calculated correctly in certain cases when the curve style is changed

### ISSUE THREAD

**Issue by fedarko** [cytoscape/cytoscape.js#1474]
[Here's](https://output.jsbin.com/natoyu) a JSBin demo of the error (steps to replicate the error are below), and [here's](https://jsbin.com/natoyu/edit?html,js) the code for the demo.

## How to replicate the error in the provided demo

1. Click the first button from the left ("add class 2 and remove class 1"). The edge should turn into a red unbundled-bezier curve (expected behavior).
2. Click the second button from the left ("add class 1 and remove class 2"). The edge will turn back into a dotted bezier curve (expected behavior).
3. Move all of the nodes and the single edge (using block selection is probably the easiest way) to some distance away from where the edge was. Press the "fit graph" button.
4. `cy.fit()` will include the previous location of the edge in its fitting calculations, resulting in the graph being off-center.

I don't know what exactly is causing this error (or the full scope of its effects), but my guess is that it occurs as a consequence of `eles.removeClasses()` not removing all the lingering style information from the removed class, and from `unbundled-bezier` control point information somehow being left over.

I haven't checked to see if a similar error occurs when adding/removing node classes, but having the "removed" class be an `unbundled-bezier` curve and the "new" class not be an `unbundled-bezier` curve seems to be at least one cause for the problem from what I've observed (so I don't necessarily think this issue would affect nodes).

## Temporary workaround

Calling `eles.move()` for the impacted edge seems to fix this problem—since the move function actually creates a new copy of the edge, it makes sense that maybe some information that `removeClasses()` doesn't remove is what causes the error. This can be seen in the demo, where pressing the "Move edge nowhere" button after observing the error will fix the error (fitting the graph will then work properly). The "Move edge nowhere" button just calls `.move()` on the edge with its current source node, which removes the edge and creates a clone of it.

## Miscellany

This issue persists for me in Chromium 51.0.2704.79 and in Iceweasel 38.7.1 on a computer running Debian 8.4. I'm using a post-2.7.6 snapshot of Cytoscape.js provided [here](https://github.com/cytoscape/cytoscape.js/issues/1466#issuecomment-235320483) (thanks!).

Thanks for your help!

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-e1bf31360c-1469738341740.zip

Let me know if it works for you or if you have any issues with it.  I'm planning to release on Tuesday, so if you could let me know by then I'd appreciate it.

Thanks

**Comment by fedarko** [comment]
The snapshot works perfectly for me. Thank you so much for your help!

**Comment by maxkfranz** [comment]
Great; thanks
