### ISSUE TITLE
Edges have reversed point properties when `srcId > tgtId`

### ISSUE THREAD

**Issue by soomin-maeng** [cytoscape/cytoscape.js#1477]
- This can create inconsistencies for customised edges
- Simplify/refactor to remove swapped direction check on unbundled edges

OP:

---

The property "segment-weights" for the "segments" edge style does not work consistently.
The edges with the equal length, same values for the property "segment-weights" and different ids have their zigzag sections at different points of the lines.
![capture1](https://cloud.githubusercontent.com/assets/20598703/17263466/3e0abd76-55af-11e6-86ed-a39e5964892a.PNG)
![capture2](https://cloud.githubusercontent.com/assets/20598703/17263467/3e0e2d94-55af-11e6-9089-1eae0c43769d.PNG)

The code for those two pictures:

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>cytoscape.js edge bug</title>
        <script src="cytoscape-2.7.6.min.js"></script>
    </head>
    <body>
        <div id="cy" style="height: 600px; width: 100%"></div>

        <script>

var cystyle = cytoscape.stylesheet()
		.selector('node')
		    .css({ 
                'label': 'data(id)',
			    'width': '45px',
			    'height': '45px'
		    })
        .selector('node.special')
            .css({
                'width': '65px',
			    'height': '65px'
            })
        .selector('edge')
		    .css({
                'curve-style': 'segments',
                'segment-distances': '0 10 -10 0',
                'segment-weights': '0.40 0.45 0.55 0.60'
		    })

var cy = cytoscape({
    container: document.getElementById("cy"),
    style: cystyle
});

cy.add({nodes: [{"data":{"id":"large"},"classes":"special"},
                {"data":{"id":"small1"}},
                {"data":{"id":"small2"}},
                {"data":{"id":"SMALL3"}}]});
cy.add({edges: [{"data":{"id":"ab","source":"small1","target":"large"}},
                {"data":{"id":"ac","source":"small2","target":"large"}},
                {"data":{"id":"ad","source":"SMALL3","target":"large"}}]});

cy.makeLayout({name: 'circle', radius: 3}).run();

        </script>
    </body>
</html>

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-4c03b160b4-1470170070783.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by soomin-maeng** [comment]
It works perfectly.
Thank you for the quick response!

**Comment by maxkfranz** [comment]
Great, thanks
