### ISSUE TITLE
Segment edges with a same source and target node does not get visualize.

### ISSUE THREAD

**Issue by soomin-maeng** [cytoscape/cytoscape.js#1485]
Is it possible to extend the segment edges around the nodes to visualize them similar to how it was done for the bezier edges?

**Comment by maxkfranz** [comment]
The positioning of segments is defined relatively, from the line from source to target.  That line would have zero length, making the points not make any sense.

This would require other features to be implemented first, including different way of specifying the points.  There are also possible conflicts to take into consideration (e.g. mixing specification types, specification type hierarchy, etc.).  Absolute positioning is a possibility, but that defeats the purpose of having the edges update as nodes are moved.  Radial positioning could work, but again, it would require consideration of conflicts.

**Comment by soomin-maeng** [comment]
Thanks for the reply!
I see why it is difficult to implement this.
thank you!
