### ISSUE TITLE
Is it possible to know what changed with a data event?

### ISSUE THREAD

**Issue by arddor** [cytoscape/cytoscape.js#1486]
I have a usecase where I need to recompute values if the data changes. I thought that the `data event` `cy.on('data', ...)` would be perfect. However the computations should not be triggered if for example the `name` is changed. Is there a way to tell in the event which data attribute changed? I thought something like a selector on the event would be nice, e.g. `cy.on('data[value]', ...)`, which would only trigger if the value attribute changed.

**Comment by maxkfranz** [comment]
You can implement a diff check in a listener (maybe using something like Immutable.js or a JSON diffing lib).  You can fire a custom event to give exactly the behaviour you're looking for:

```js
cy.on('data', '*', function(){
  if( fooDiffPositive ){
    this.trigger('foodiff');
  }
});
```

General diffing (without making assumptions about what your model is like) can be expensive, so it should probably be left to the developer to control and implement.

**Comment by maxkfranz** [comment]
Another option is wrapping your data modifications in an extension, e.g.:

```js
cytoscape('collection', 'fooData', function( newFoo ){
  return this.data('foo', newFoo).trigger('foodiff');
});

cy.nodes().fooData('bar');
```
