### ISSUE TITLE
ele.move() is not preserving ele.scratch()

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1487]
I think that in ele.move() method get the json data of elements with eles.jsons() and create new elements using this jsons. However, as far as I know eles.jsons() does not contain scratch of the eles. Therefore, in ele.move() the scratch of ele is lost. I think that this may be problematic in some cases (Currently I have trouble with this). How about preserving ele.scratch() in ele.move() method while the new ele is just being created.

**Comment by maxkfranz** [comment]
Yes, most people probably expect scratch to be maintained.

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-f6e60c0fa4-1470842221938.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by metincansiper** [comment]
I tried this snapshot, it seems that scratch is maintained during in move operation.

**Comment by maxkfranz** [comment]
Great; thanks
