### ISSUE TITLE
Animation & z-index

### ISSUE THREAD

**Issue by pconihout** [cytoscape/cytoscape.js#1491]
Hi,

I'm trying to make an animation where when i click it goes in the center of the screen and mark it as selected.

The thing is it's always in the background of the others nodes whereas I click on it it  goes to the the front.

After animation :
![capture d ecran 2016-08-11 a 10 38 18](https://cloud.githubusercontent.com/assets/16023563/17594525/3ec13e2a-5faf-11e6-87c4-45edabb1d85d.png)

After a click on it:
![capture d ecran 2016-08-11 a 10 38 26](https://cloud.githubusercontent.com/assets/16023563/17594531/4659adde-5faf-11e6-934c-4b70aebb5347.png)

Any ideas on how I could add something where it mark it as clicked in my animation ?

**Comment by maxkfranz** [comment]
Are you animating the z-index property?  Do you have a live example of your animation I could look at?  Thanks

**Comment by maxkfranz** [comment]
@pconihout Do you have a live example I could look at?  I'm not entirely sure what the issue is or how to reproduce it.

**Comment by maxkfranz** [comment]
No response; closing
