### ISSUE TITLE
Display graph only when loaded

### ISSUE THREAD

**Issue by pconihout** [cytoscape/cytoscape.js#1492]
Hello,

I'm using Cytoscape for a graph of nearly 1000 nodes. And as i import them from outside DB, i'm using a look with cy.add().

I'm just wondering is there a way of knowing when the graph is totally ready & every nodes loaded ?
Cheers.

**Comment by maxkfranz** [comment]
That you can do just with regular CSS on your div.  All ops in the graph are synchronous, so you can show after `.add()`

**Comment by pconihout** [comment]
I don't really agree with you, there is always a delay with me between adding elements and applying layout i guess...

**Comment by maxkfranz** [comment]
Then you can show your div after the layout is done on the `layoutstop` event

Adding and layout are different actions
