### ISSUE TITLE
Defining relative edge source/target label offset

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1497]
I think that if we directly define a value for source/target label offset of an edge in stylesheet it is a fixed value not something relative. Therefore, I tried to define a function returning a relative offset for this in the following way:

```
 'source-text-offset': function(ele) {
    return getCardinalityDistance(ele);
  }
```

However, when I do this I realized that position of label is not updated on drag when I stopped dragging a connected node. It is updated when I tap any element in the graph.

I solved this problem by updating the stylesheet on node drag in the following way:

```
   cy.on('drag', 'node', function (event) {
      cy.style().update();
    });
```

I was wondering if there is a better solution for this problem?

**Comment by maxkfranz** [comment]
(1) Stylesheet calculations are way too expensive to be recalculated on gestures.  Stylesheets get recalculated only on data changes or possible selector match changes.  

(2) The offset is a crude approximation.  It's very accurate for most edges, but only for relatively small values.  The usecase is pushing a small label, like a digit, a bit so it doesn't overlap the node.  It's not meant for shifting large amounts, which is when you'd want a percent value.
