### ISSUE TITLE
Issue with cose layout when there are edges between children and its parent in compound nodes.

### ISSUE THREAD

**Issue by aindlq** [cytoscape/cytoscape.js#1498]
Cose layout adds huge paddings if one have edges beetwen children and it's parent in compoun node, e.g http://jsbin.com/jozufaquba/1/edit?html,output

**Comment by aindlq** [comment]
see https://github.com/cytoscape/cytoscape.js-cose-bilkent/issues/25, is it correct that cose have the same issue and this won't-fix?

**Comment by maxkfranz** [comment]
@ugurdogrusoz I'm not sure what the best solution is here.  Devs can specify themselves to exclude problematic edges (`eles.layout()`).  But could we safely filter these out all the time to make it more convenient in `cose` and `cose-bilkent`?  Are there any cases where you would want these edges included?

@aindlq Does this only affect parent-children edges or does it also affect general parent-descendant edges?
