### ISSUE TITLE
Approach for implementing zoom-dependent layout

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js#1501]
This isn't a bug, so if this is preferred to keep somewhere else - please let me know and I'll move it. 

I'm sketching on how to implement a zoom-dependent layout, basically the following: 

A graph with a set of nodes of type X, all of which has N nodes of type Z associated via directed edges. At zoom level A, display only type X using a given positional logic. At zoom level B, display nodes Z at distance D from each X. For each delta-zoom between A and B - interpolate distance D as a function of delta-zoom. Node types are determined by a given attribute within the data of each node.

Is implementing this as a custom layout the best option or is there a better way to do this?

**Comment by maxkfranz** [comment]
You can think of a layout as just a map function of `node => ({ x, y })`.  Your idea sounds like it has behaviour/UI associated with it, so it would be better as a general extension.

The extension could call one or many layouts to position the nodes.  You could even parameterise it so you could use any layout.

Your idea has some overlap with the general semantic zoom idea : https://github.com/cytoscape/cytoscape.js/issues/1157

**Comment by buffpojken** [comment]
Hmm, not really sure I understand your thought on extension vs layout. The logic of determining which node is visible at a given zoom level should then be in an extension since it doesn't map a node to a position - but the actual calculation for x,y should be kept in a custom layout? Since that's dependent on current zoom level? 

Or am I misunderstanding and the extension should basically calculate this on any relevant change, set x,y for any nodes dependent on zoom for position and just pass it on to a (perhaps parameterized) layout for actual rendering/positioning?

**Comment by buffpojken** [comment]
Also - thanks for taking the time to reflect on this, want to make sure I implement it cleanly according to how it should be done.

**Comment by maxkfranz** [comment]
If you have a really different idea of how to position the nodes, then you may want a custom layout extension that your main extension would use.  It sounds like you could get by just using one of the existing layouts to simplify things.   The layouts are fairly customisable.  

You can just call one or more layouts as needed on zoom changes.  (You have some flexibility in that layouts can be applied to subsets of the graph.)

If you have linear levels, you could just use the grid layout and specify the bounding box to effectively scale the distance between the levels.

**Comment by buffpojken** [comment]
So, your recommendation on working with layouts applied to subsets of graph lead me straight to the right place. 

A dynamically calculated bounding box together with calculating the radius-option on a circle layout on zoom changes and then just re-running the pre-created layout works like a charm. 

This leads me to a another "best practice"-question. How "expensive" is ele#makeLayout? Is it better to create a lot of layout-objects with different sets of nodes in them or is it better to create them dynamically on changes in zoom?

**Comment by maxkfranz** [comment]
It's pretty much the same expense either way.  Creating new layouts isn't expensive w.r.t. execution cost.  For more complex layouts that create extra objects per element and call out to external libs (like Cola, Dagre), there is memory/gc cost to consider per run -- though probably a relatively small one.

The main thing to consider is that layouts, like collections, are immutable w.r.t. to the element set.  You can't add or remove elements to a layout; you must create a new layout.

**Comment by buffpojken** [comment]
Okey, check - then I'll probably pre-create all layouts - their immutability isn't a problem, the exact set of nodes they need to be applied to is known at all times, so I can just recreate layout whenever required. 

Many thanks for your patient replies!
