### ISSUE TITLE
Feature Suggestion: Yen's K Shortest Paths

### ISSUE THREAD

**Issue by hjtran** [cytoscape/cytoscape.js#1507]
Hey all, sorry if this isn't the right way to go about doing this (first time trying to contribute to open-source), but I was wondering if you'd all be interested in me adding Yen's to the cytoscape.js algorithms. I've already implemented it for a project of mine so was excited about the prospect of contributing it.

Thanks!
Joey

**Comment by maxkfranz** [comment]
@hjtran Yes, it would be great to add this!  The best way to do it for now is as [an extension](http://js.cytoscape.org/#extensions).  Normally, an algorithm like this would be merged into the `unstable` branch for the next feature release -- but that's going to be 3.1 as 2.x is in maintenance mode in preparation for 3.0.

So, doing an extension would better/faster for now.  We can easily include extensions in the main build, so we can easily merge Yen's algorithm from the extension into 3.1 in future.  (In fact, we have several other algorithms implemented as extensions for now, waiting for 3.1 -- [k-means](https://github.com/cytoscape/cytoscape.js-k-means) for example.)

There's an [autoscaffolder](https://github.com/cytoscape/slush-cytoscape-extension) to make generating extensions easy.  If you have any trouble using it, just let me know.

Does this sound good to you, Joey?

Thanks

**Comment by maxkfranz** [comment]
@hjtran Any updates, Joey?  Thanks

**Comment by maxkfranz** [comment]
This issue can be re-opened if there is a response from @hjtran.
