### ISSUE TITLE
Label background misaligned on y axis

### ISSUE THREAD

**Issue by monprin** [cytoscape/cytoscape.js#1513]
![label demo](https://cloud.githubusercontent.com/assets/7094030/18138696/986d36d0-6f73-11e6-9faa-7fe950997f0c.png)

As you can see I am still having major label alignment issues since the new renderer. I am currently using v.2.7.8. It happens in both chrome and firefox on Ubuntu 14.04 and Ubuntu 16.04. 

The code that is relevant to the graph can be seen here:
https://github.com/monprin/cob/blob/master/static/js/graph.js

Any help would be greatly appreciated!

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-51e9bb8de8-1472742026086.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by monprin** [comment]
Yes that appears to fix it! Thank you!

**Comment by maxkfranz** [comment]
Great; thanks
