### ISSUE TITLE
how to delete a group elements  who have the same feature in the id

### ISSUE THREAD

**Issue by yujunjie0603** [cytoscape/cytoscape.js#1515]
hello
I would delete a group elements who have the same feature in the "id".
for example : id = "a_1", id="a_2", ...

could we delete all of the elements who have id "a_" plz ?

**Comment by maxkfranz** [comment]
Use a data selector: http://js.cytoscape.org/#selectors/data

[name ^= value]
Matches elements if their data attribute starts with the specified value (e.g. [foo ^= 'bar']).

**Comment by yujunjie0603** [comment]
thanks a lot !
