### ISSUE TITLE
Manipulate content property in node style

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js#1516]
Is it possible to manipulate the `content` attribute in node style, i.e. instead of

    style: {
      'content': 'data(id)',
    }

I want to write

    style: {
      'content': 'ID: data(id)',
    }

but this approach doesn't work.

**Comment by maxkfranz** [comment]
Use a function: http://js.cytoscape.org/#style/mappers

E.g. `content: function( ele ){ return 'foo' + ele.data('bar'); }`
