### ISSUE TITLE
Arrow positioned wrong when using label width and height

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js#1530]
There seems to be a problem with arrow positioning when I use `width: 'label'` and `heigh: 'label'` as node style.

The arrow points to the center of the node instead of to the arrow. When I select a node, the arrows are redrawn and then positioned correctly.

What can I do to make sure they are initially drawn correctly.

**Comment by maxkfranz** [comment]
Can you provide a demo?  It's working as expected for me on the debug page:

![screen shot 2016-09-21 at 12 34 24 pm](https://cloud.githubusercontent.com/assets/989043/18720006/cf094334-7ff7-11e6-8f8f-4164ed57d6a1.png)

**Comment by mazing** [comment]
I guess it is the same problem as with http://jsbin.com/tiqinayico/1/edit?html,output.

The arrows are not visible until you select a node.

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-871d0d41e2-1474576375330.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by mazing** [comment]
It works :-)

**Comment by maxkfranz** [comment]
Great; closing
