### ISSUE TITLE
Drag/grab if ctrlKey pressed, draw otherwise

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js#1532]
It seems it is only possible to decide whether the user can drag nodes or draw new nodes/edges (with edgehandles) using `cy.autoungrabify(bool)`.

But I want to let users drag if they hold `ctrlKey` while dragging a node and draw if they are not holding `ctrlKey`. 

I have tried accomplishing this with

    // draw mode as default
    cy.autoungrabify(true);

    cy.on('mousedown touchstart', 'node', function (event) {
      cy.autoungrabify(!event.originalEvent.ctrlKey); // draw mode if ctrlKey not pressed
    });

    cy.on('mouseup touchend touchcancel blur', 'node', function (event) {
      cy.autoungrabify(true); // back to draw mode
    });

but it doesn't work.

**Comment by maxkfranz** [comment]
There are no guarantees provided for exactly when state checks are done during gestures.  That's undocumented/undefined behaviour, so you can't make any assumptions like your above code does.

Try changing the grabbable state *before* any gesture.  You can probably assume users will press `control` before clicking -- so change state on `keydown` and revert on `keyup`.
