### ISSUE TITLE
Enumerate nodes in label

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js#1549]
Is it possible to enumerate the nodes in a label, so each node has the content `'node' + i` where `i` is the index of the node?

I have tried `'content': function (el, i) { return 'node' + (i + 1); }`, but it doesn't work.

**Comment by maxkfranz** [comment]
That won't work, as the function is unary and needs to be able to run independently of other elements.

You need to keep track of your indices in your app's model.  You can store the index in `.data()` s.t. you'd just use `content: 'data(index)`
