### ISSUE TITLE
cy.nodes().reduce() just like cy.nodes().map()

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js#1550]
Are there any plans on implementing the `Array.reduce` function in `cy.nodes()` just like `Array.map`, `Array.filter`, etc. has already been implemented.

**Comment by maxkfranz** [comment]
Yes : https://github.com/cytoscape/cytoscape.js/issues/1401

**Comment by mazing** [comment]
Great! Can't wait :-D

**Comment by 132041** [comment]
I can see that it is implemented with this commit https://github.com/cytoscape/cytoscape.js/commit/1bf356f89082678f276ac3bfe7974d3e3e6b1259

But even when running unstable, I get the error `cy.edges().filterFn(...).reduce is not a function`. Is it not implemented like normal array reduce?

**Comment by mazing** [comment]
It is implemented in https://github.com/cytoscape/cytoscape.js/commit/1bf356f89082678f276ac3bfe7974d3e3e6b1259, but when running unstable, I still get the error `Uncaught TypeError: edges.filterFn(...).reduce is not a function`.

**Comment by maxkfranz** [comment]
You'd have to build your app using Browserify or Webpack and have the Cy.js source built-in in order to use the code in unstable.  You can't use dist unless it's off a tag
