### ISSUE TITLE
the length of edge

### ISSUE THREAD

**Issue by yujunjie0603** [cytoscape/cytoscape.js#1560]
hi :
Could we get the length of edge plz ?

Thanks a lot !

**Comment by yujunjie0603** [comment]
srcX = val._private.rstyle.srcX
srcY = val._private.rstyle.srcY
tgtX = val._private.rstyle.tgtX
tgtY = val._private.rstyle.tgtY
distance = Math.sqrt(Math.pow((srcX-tgtX), 2) + Math.pow((srcY-tgtY), 2));

**Comment by maxkfranz** [comment]
Don't read private data if you care about your app's stability.

Use the diagonal of the `.boundingBox()` instead.

**Comment by yujunjie0603** [comment]
thank you for your remind !
but i saw that the value srcX is differente of boundingBox.x1 !
what is differente of them plz ?

**Comment by maxkfranz** [comment]
There are four points in a bounding box.  You have to figure out which of the four corners is closest to the nodes.

**Comment by maxkfranz** [comment]
But you can usually just use the top-left to bottom-right diagonal.  It's close enough for most edge types.

**Comment by yujunjie0603** [comment]
I used the style unbundled-bezier at the edge .

1 :
            position_ini = val.boundingBox();
            srcX = position_ini.x1
            srcY = position_ini.y1
            tgtX = position_ini.x2
            tgtY = position_ini.y2
            distance = Math.sqrt(Math.pow((srcX-tgtX), 2) + Math.pow((srcY-tgtY), 2));

2 :
            srcX = val._private.rstyle.srcX
            srcY = val._private.rstyle.srcY
            tgtX = val._private.rstyle.tgtX
            tgtY = val._private.rstyle.tgtY
            distance = Math.sqrt(Math.pow((srcX-tgtX), 2) + Math.pow((srcY-tgtY), 2));

The result are diffrente between these two means !

**Comment by maxkfranz** [comment]
The private values don't mean what you think they mean.  Just use the bounding box.

**Comment by yujunjie0603** [comment]
ok, thanks a lot !
