### ISSUE TITLE
Animations permanently prevent style changes via class manipulation for the animated attribute(s)

### ISSUE THREAD

**Issue by marteber** [cytoscape/cytoscape.js#1561]
I have a setup in Cytoscape.js 2.7.10 where I set a node width of 30 at initialization which can be changed to 50 via a class defined at initialization, i.e.
```javascript
cytoscape({
	/* ... */
	style: cytoscape.stylesheet()
		.selector("node")
			.css({
				width: 30
			})
		.selector(".bigger")
			.css({
				width: 50
			})
	/* ... */
})
/* ... */
function grow(coll) {
	coll.addClass("bigger");
}

function shrink(coll) {
	coll.removeClass("bigger");
}
```
Now, I also have an animation that temporarily changes node size. It is used to focus the user's attention on a node that was selected from an accessory `select` element:
```javascript
function emphasize(node) {
	var a = node.animation({
		css: {
			width: 100
		},
		duration: 400,
		queue: true
	});
	// increase node size
	a.play().promise("complete").then(function() {
		// revert size increase
		a.reverse().play();
	});
}
```
(Please note that the code and use case are heavily simplified.)

Once the animation has run on a node, the node's width is locked for the remainder of the session to whatever it was when the animation started (depending on whether the node was `bigger` pre-animation). Calling `grow(node)` or `shrink(node)` will not change the width anymore.

Unfortunately, that steps on my toes because my scenario relies on changes in node width for conveying information to the user. From a more general perspective, I think the engine should in principle not lock style attributes to the result of an animation. I have tried equivalent approaches with `animate` or `animation` (like chaining a second animation which sets the cached initial width) and even switched to `flashClass` to see if I could mimic the expected behavior but no dice.

Are there alternative ways that I have not found? And should this be labeled bug or feature request?

**Comment by maxkfranz** [comment]
In short, this is expected behaviour whenever you use bypasses (which animations naturally use).  You have to remove the bypass on the style properties in order for the bypasses not to bypass the stylesheet.

Animations are bypasses, just like calling `ele.style('foo', 'bar')`.  That's analogous to setting `<someTag style="foo: bar">` in HTML/CSS.  You'll find the same behaviour in any CSS/animation lib like jQuery or Velocity.

**Comment by maxkfranz** [comment]
Set `ele.style('foo', '')` or `ele.style('foo', null)` to clear a bypass

**Comment by marteber** [comment]
I see. I had the idea in my head that an animation should behave differently from a transition, in that it should revert to the original state on its own (despite my own code's `reverse()` proving already that that idea is incorrect).

Thanks for the explanation and workaround!

**Comment by maxkfranz** [comment]
Yes, the difference with a transition is that it has a definite stylesheet block state that is starts and ends in.  This isn't the case with general, imperative animations -- so the bypass needs to remain.
