### ISSUE TITLE
can't run cose as initial layout

### ISSUE THREAD

**Issue by mmaclach** [cytoscape/cytoscape.js#1562]
I'm having an issue with setting the initial layout to 'cose' in 2.7.9 / 2.7.10

I've just set the initial layout using the options.layout property with some basic settings (gravity, numIter, padding, etc).

What i've found: 
- the layout is not run initially
- running the 'cose' layout additional times doesn't produce any results unless 
    1) another layout is run first 
    2) I manually drag a node first

- other initial layouts work (i've tried random, grid, breadthfirst .. )

For now i've rolled back to 2.7.8 which seems to work fine

**Comment by maxkfranz** [comment]
You forgot to set initial positions or set `randomize: true`.

Force-directed/physics layout tend not to work well with zero distances (e.g. all nodes at (0, 0) at init).

**Comment by mmaclach** [comment]
Solved, thanks.
