### ISSUE TITLE
No taphold on new edges

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js#1565]
If I load my graph with nodes and edges, I am able to taphold an edge using `cy.on('taphold' ...)`

But if I create a new edge using `cy.add({ group: 'edges', data: { source: ..., target: ... }})`, I am not able to taphold it until I have refreshed the page.

What is different from the edges loaded on init and those created afterwards? I have inspected them with

    cy.edges().forEach(edge => {
      console.log(edge.data());
    });

but they look just the same.

**Comment by maxkfranz** [comment]
Did you actually bind via (1) `cy.on('taphold', 'edge', function(){ ... })`, or did you (2) `cy.edges().on('taphold', function(){ ... })`?

(1) uses a delegate selector and so will match elements that don't exist yet.  (2) is calling on a specific set of elements, and naturally will not match elements outside this set.

**Comment by maxkfranz** [comment]
I've confirmed (1) working as expected for any edge.

**Comment by maxkfranz** [comment]
Closing for now
