### ISSUE TITLE
Change node id after populating database

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js#1566]
I am creating nodes on the client and saving the data about the new node on the server.

When I am populating the database with the nodes, MongoDB assigns an ids to them.

But why is it not possible to change the id of the nodes in cytoscape after I have received the new id from MongoDB? I have tried `node.data('id', the new id)`, but it seems IDs are immutable.

**Comment by maxkfranz** [comment]
There are lots of reasons for not allowing mutable IDs.  Mongo doesn't let you mutate `_id`, either.

Remove the element, and add a new one with the new ID.  Or just don't use the `id` field: It doesn't have to match your DB ID.  You could use an `_id` field, which would be mutable and match your Mongo `_id` better anyway.
