### ISSUE TITLE
Just change the axis Y

### ISSUE THREAD

**Issue by yujunjie0603** [cytoscape/cytoscape.js#1567]
Hi:
How to change just the positon Axis Y when we do drag !

        page_rubrique.$(".numero").on('mousedown', function(event) {
            var position_ini = (this.position());
            old_x = position_ini.x;
            old_y = position_ini.y;
            this.on('mouseup', function(){
                
                new_x = position_ini.x;
                new_y = position_ini.y;
                console.log(old_x); // return 100
                console.log(new_x); // return 200
                if (old_x != new_x) {
                    this.animation({
                        position:{
                            x:old_x,
                            y:new_y
                        },
                        duration: 1000
                    });
                    console.log(this.position('x')); // return 100
                }
            });
        });

my code don't work ! :(

in fact, I would like to perform an action such as jQuery Draggable and sortable

Do you have some ideas plz ?

**Comment by maxkfranz** [comment]
You can use the automove extension to set restrictions on position: https://github.com/cytoscape/cytoscape.js-automove

There's an example in the demo that limits one axis based on the position of another node.  It's the same principle in your case except simpler -- just make the x value constant as your restriction.

**Comment by yujunjie0603** [comment]
Thank you !
 
How to change the position of node plz ?

I try
 cy.("#id").position({x:100, y:200});

but it don't work !
