### ISSUE TITLE
For loop for Reading Into Elements

### ISSUE THREAD

**Issue by jiwpark00** [cytoscape/cytoscape.js#1568]
Hi,

I'm newbie to Cytoscape and I was wondering, is there a way to read file and save that as edges/nodes for elements?

I went through tutorial and checked out two examples but it seems that the contents of elements were explicitly typed in...I'm sure this is possible, I just don't know enough JS for how to do this just yet.

Thank you.

**Comment by maxkfranz** [comment]
The graph data is serialisable via JSON.  Use `cy.elements().jsons()` or `cy.json()`.

**Comment by jiwpark00** [comment]
Awesome, thank you.
