### ISSUE TITLE
cy.elements(':selected').size() returns 0 inside `cy.on('tap', ...)` every time

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js#1569]
If an element is selected, I want to unselect all elements when I tap the canvas (i.e. `event.cyTarget === cy`) just like it behaves when I press `ctrl` while tapping the canvas; however, my project creates a new node instead of unselecting.

Therefore, I tried

    cy.on('tap', function (event) {
      if (event.cyTarget === cy) {
        const selectedElements = cy.elements(':selected');

        if (selectedElements.size() > 0) { // returns 0 every time
          selectedElements.unselect();
        } else {
          createNode();
        }
    }

but `cy.elements(':selected').size()` returns `0` every time inside this event listener.

I guess this is either a bug or it is because it is unselecting the elements before firing this event, so how can I make sure it isn't fired if an element is selected, just like the "ctrl key pressed behaviour" (and where is this defined btw)?

**Comment by maxkfranz** [comment]
The order of events is unspecified, so you can't make assumptions re. the relative ordering of tap and select.  Bind to select events if you're interested in selection.

As an aside: The default selection behaviour is already to unselect everything on tap/taphold of the background.
