### ISSUE TITLE
Problem with IE11

### ISSUE THREAD

**Issue by dannysh1** [cytoscape/cytoscape.js#1570]
Hi,
I'm trying to run cytoscape.js with a simple change to the example that on the site.
I can view the chart on Chrome, but see nothing on IE11 (get some kind of "SecurityError" in the console.

Here is the code: https://jsfiddle.net/e78w83uy

Is there a general problem with viewing this chartes on IE?

Thanks

**Comment by maxkfranz** [comment]
Apart from bugs in IE itself, there's no reason Cytoscape wouldn't work in IE.  It should work in versions with ES5 support and the canvas API, so IE9+.

It works fine in IE11 in a Windows VM on my machine.
