### ISSUE TITLE
Get positions after changing layout

### ISSUE THREAD

**Issue by mazing** [cytoscape/cytoscape.js#1574]
How is it possible to get the positions after setting the layout?

I have tried

```
const nodes = cy.nodes();
nodes.layout(layout);
console.log(nodes.map(node => node.position()));
```

but it prints the old positions. Shouldn't it print the positions to which the nodes are moved?

**Comment by maxkfranz** [comment]
If you're running unstable/3.0, you need `.layout().run()`
