### ISSUE TITLE
Label border padding

### ISSUE THREAD

**Issue by dpekkle** [cytoscape/cytoscape.js#1575]
Is there any way to add padding to the border of a label? After updating to the latest version borders are wrapped at a minimum distance around labels for nodes and edges, which can create for some very cramped looking labels.

e.g. The labels for edges and the compound node:
![label-padding](https://cloud.githubusercontent.com/assets/1937814/19230594/1cdc762a-8f21-11e6-8daa-633bbfc69ad3.PNG)

Current padding attributes only apply to labels in the center of nodes, without borders being affected. Margins only position the label, and the text-border options don't support any sort of padding.

Is there something I'm missing? Ideally there would be a text-border-padding style attribute.

**Comment by maxkfranz** [comment]
@dpekkle Yes, this would be nice to have in the library.  I don't have time to try that now, but if you're interested it should be relatively straight forward to make a pull request on the unstable branch for it.  Let me know if you need help finding the relevant places in the renderer (hit tests, drawing) and the stylesheet.

**Comment by dpekkle** [comment]
Seems like \src\extensions\renderer\canvas\drawing-label-text.js and \src\style\properties.js are where I'd work on it? 

Not sure what part you're referring to with tests.

**Comment by maxkfranz** [comment]
The [hit testing](https://en.wikipedia.org/wiki/Hit-testing) is here: https://github.com/cytoscape/cytoscape.js/blob/78f1f8b78626f3e4d07fb50827d1028a3ed132d9/src/extensions/renderer/base/coord-ele-math.js#L208

**Comment by dpekkle** [comment]
Ok, here's what I managed to get working:
http://run.plnkr.co/CK87ChsYlhGvCDUf/

I've made it so there's a single attribute 'text-border-padding', if you'd rather separated into top/bottom/left/right I can do that instead.

Had to modify [dimensions.js#L325](https://github.com/cytoscape/cytoscape.js/blob/78f1f8b78626f3e4d07fb50827d1028a3ed132d9/src/collection/dimensions.js#L325) as well so that the larger labels were included in the bounding box, and thus fully displayed.

**Comment by maxkfranz** [comment]
Might also need the hit tests updated for tap support on labels

**Comment by dpekkle** [comment]
Here's where I'm at: http://plnkr.co/edit/pCHSRccMDNkiOIOD40Sd?p=preview

Node and edge labels work with the text-events attribute, but I'm hitting a bit of a wall with auto-rotating edge labels.

I've modified [checkLabel](https://github.com/cytoscape/cytoscape.js/blob/78f1f8b78626f3e4d07fb50827d1028a3ed132d9/src/extensions/renderer/base/coord-ele-math.js#L390) such that.
```
      var lw = preprop( rstyle, 'labelWidth', prefix ) + bw/2 + 2*th + 2* borderPadding;
      var lh = preprop( rstyle, 'labelHeight', prefix ) + bw/2 + 2*th + 2* borderPadding;
```

It will then correctly tell if the mouse intersected with the rotated label (outputting inside/outside to console). However this result appears to be ignored in that the actual the bounds of the label (which is a bounding box aligned with X/Y axes) are what will determine the click. 

![autorotateboundissue](https://cloud.githubusercontent.com/assets/1937814/19832699/e0723fa2-9e76-11e6-9561-ca16ff010e2e.png)

A click anywhere in the red region will select the edge. This happens whether or not I assign the label padding, but doesn't occur using /dist/cytoscape.min.js. I've been stuck on how that can be the case as the only thing I have modified in [dimensions.js#L363](https://github.com/cytoscape/cytoscape.js/blob/78f1f8b78626f3e4d07fb50827d1028a3ed132d9/src/collection/dimensions.js#L363) in regards to edges is:

```
 if( isEdge ){
      lx1 = labelX - lw_2 - borderPadding;
      lx2 = labelX + lw_2 + borderPadding;
      ly1 = labelY - lh_2 - borderPadding;
      ly2 = labelY + lh_2 + borderPadding;
    }
```

**Comment by maxkfranz** [comment]
On your side, I think all that should be necessary is making sure the width and height considered for the label in the hittests have the paddings taken into consideration.  The issue with the rotation calculation looks like a separate, unrelated issue.  I am able to reproduce on unstable as well.  I haven't looked at master yet, so maybe it's an issue introduced after 2.7.

I'll look into this more and see.

In the meanwhile, would you please organise your changes into a pull request?

**Comment by dpekkle** [comment]
Pull request is up. Squashing the commits didn't work as I expected but it should be fine.

**Comment by maxkfranz** [comment]
OK, thanks.  I should be able to squash them on my side anyway.  I'll review on Monday.

**Comment by maxkfranz** [comment]
This should address the hit test issue:

Label hit tests do not differentiate source/target/mid labels when not rotated #1619
