### ISSUE TITLE
Working on more node details

### ISSUE THREAD

**Issue by tongbin** [cytoscape/cytoscape.js#1576]
Hi @maxkfranz , I'll need some more details to show in the node.

including
1. support FontAwesome icon as node background image
2. support FontAwesome icon as node right icon
3. support text scale to show smaller label for node

So I'll add these stylesheet properties
1. **background-font-icon** : text, the text to show in the middle of the node
2. **background-font-icon-fill** : zeroOneNumber, the area where icon fills in the node
3. **background-font-icon-family** : fontFamily, the font family is used as the icon in the node, default is fontAwesome
4. **background-font-icon-color** : color, the icon color is used in the icon in the node, default is black
5. **top-right-icon** : text, the text to show in the top right corner
6. **top-right-icon-family** : fontFamily, the font family to use in the top right corner, default fontAwesome
7. **top-right-icon-color** : color, the color to use in the top right corner, default is black
8. **top-right-icon-scale** : zeroOneNumber, the text scare to use int the top right corner, default is 1, the default font size is 12px for top right corner, since for my case there won't be big icon on the top right for me.
9. text-scale : zeroOneNumber, for text scale to show smaller text, since most browser has an minimum font size as 12, if we want to show smaller text, we will need a scale

Please review if these are reasonable, I could create a pull request if we are planing to add these features to cytoscape.

**Comment by maxkfranz** [comment]
Because SVG background images are supported, you can put anything you want in the SVG.  There are libraries that make SVG editing easy, and you can even put content outside of the node body if you disable background clipping in your stylesheet.

**Comment by tongbin** [comment]
Sounds workable, I'll try it. Thanks.

**Comment by tongbin** [comment]
Actually I want to implement something like this:
![image](https://cloud.githubusercontent.com/assets/8870302/19507348/df1ab1ea-9604-11e6-96c0-f488e887bef6.png)

The image on the right top corner indicates that the node is locked.
And the text is left aligned at the bottom.

If you have any suggestions, it will be great. Thanks. @maxkfranz

**Comment by maxkfranz** [comment]
I'm not sure if the text can be aligned like that.  Otherwise, it looks possible.

**Comment by tongbin** [comment]
So I'm considering to add some styles like
1. `top-right-image` to add a top right image
2. `text-scale` as an one-zero number to make spaces in the label
3. `text-fit-node` to make the label starts from left border of the node which only could be applied to `valign == bottom` and `halign center`

**Comment by ron23** [comment]
On the same manner, do we have a way of adding icons/glyphs AROUND nodes? 
For example a small icon that represents the country of the node, or some score about the node.
Iv'e found [THIS](http://stackoverflow.com/questions/27799220/adding-extra-information-above-the-node-in-cytoscape-js):  But I feel this is really hacky.
I'm basically looking to do something similar to [THIS](http://d13uzbxp4vxmou.cloudfront.net/wp-content/uploads/2014/05/glyph-gif-2.gif)

**Comment by maxkfranz** [comment]
You can control node drawing completely is you specify a SVG background image.  You can put whatever you want in the SVG.
