### ISSUE TITLE
Some more edge features as demanded for me

### ISSUE THREAD

**Issue by tongbin** [cytoscape/cytoscape.js#1579]
There are some requirements for some more edge features for me, including.
1. **Draw edge arrow at the 3/4 point on an edge.** This one looks relatively simple, I could add a style like `qrt-target-arrow-shape` and draw an arrow there. 
2. **Show some animation (maybe a disc moving along the edge) indicates the movement.** I've noticed that we've an issue #1573 which mentioned to show an animated dash line, not sure if it's the same thing. This one sounds much more complicated. I am going to create an extension to archive it.

**Comment by maxkfranz** [comment]
I don't think (1) is pragmatic.  The only reason mid arrows are supported is because the midpoint already needs to be calculated for basic drawing (e.g. control point for beziers).  Calculating extra points per edge can be very expensive.
