### ISSUE TITLE
Qtip on mouseover

### ISSUE THREAD

**Issue by botev** [cytoscape/cytoscape.js#1580]
So I'm trying to use the `qtip` extension, however I want those to come up on mouse over. I directly used the example provided and tried [modifying it](https://gist.github.com/botev/efef3bb21553dd3598708bcdda9a709b). 
If I try this the event gets logged, but not tip is shown:

```
cy.on('mouseover', 'node', function(e) {
console.log(e);
$(this).qtip({
    overwrite: false, // Make sure the tooltip won't be overridden once created
  content: 'Hello!',
    position: {
    my: 'top center',
    at: 'bottom center'
  },
  style: {
    classes: 'qtip-bootstrap',
    tip: {
        width: 16,
      height: 8
        }
    }
}, event); // Pass through our live event to qTip
});
```

If I however add to the `qTip`:

```
show: {
   ready: true // Show the tooltip immediately upon creation
},
```

I get the error:

```
jquery-2.0.3.min.js:5 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```

Note that I got this example of making a `qTip` from the official [docs](http://qtip2.com/guides). Would anyone have any idea how to construct this correctly?

**Comment by maxkfranz** [comment]
Initialise your qtip with the proper `show` `events` (i.e. `mouseover`)

Use the extension repo to discuss the qtip extension in future, please.

**Comment by kavinnagul** [comment]
Hi Max,

Qtip not working on mouse over. Below code working for Click event. 

Can you please suggest what  changes i have to do for mouseover event.

cy.$("#"+this.id()).qtip({
			  show: { event: 'directtap' },
			  //hide: { event: 'mouseout' },
			  content: function(){ return 'Example qTip on ele ' + this.id() },
			  position: {
				my: 'top center',
				at: 'bottom center'
			  },
			  style: {
				classes: 'qtip-bootstrap',
				tip: {
				  width: 16,
				  height: 8
				}
			  }
			}).on('tap', function( e ){
			  var eventIsDirect = e.target.same( this ); // don't use 2.x cyTarget

			  if( eventIsDirect ){
				this.emit('directtap');				
			  }
			}).on('directtap', function( e ){
			  e.stopPropagation();
			});
