### ISSUE TITLE
Mapped style values like `control-point-distances` can fail on initial application of style diff

### ISSUE THREAD

**Issue by ibas87** [cytoscape/cytoscape.js#1581]
Specifying 'control-point-distances' using node data Object throws an error: 
'Error: null is not an object (evaluating 'eleProp.bypass')'

The following configuration will fail:
`{data: { id: 'node1', curveStyle: 'unbundled-bezier', cpd: -15, shape: 'rectangle', row:1, col: 1, width: 120, height: 60, background:'#fff' }, classes: 'node'}`

`style: cytoscape.stylesheet()
    .selector('node')
      .css({
        'background-color': 'data(background)',
        'shape': 'data(shape)',
        'border-width': 1,
        'curve-style': 'data(curveStyle)',
        'control-point-distances': 'data(cpd)'
      })`

Changing the css definition to include 'control-point-distances' inline works:

`style: cytoscape.stylesheet()
    .selector('node')
      .css({
        'background-color': 'data(background)',
        'shape': 'data(shape)',
        'border-width': 1,
        'curve-style': 'data(curveStyle)',
        'control-point-distances': -15
      })`

**Comment by maxkfranz** [comment]
@ibas87 

Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-d5a404185a-1478725109265.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by maxkfranz** [comment]
Closing for 2.7.11 release, since it looks to be fixed from my testing.
