### ISSUE TITLE
Node Background Image: Data URI images won't load on Safari

### ISSUE THREAD

**Issue by ibas87** [cytoscape/cytoscape.js#1582]
Node Background Image - Data URI images won't load on Safari because Image Cross Origin is set to 'Anonymous'.

This will make Safari to block the resource throwing the following error:
'Cross-origin image load denied by Cross-Origin Resource Sharing policy.'

I found a workaround solution: on 'cytoscape.js/src/extensions/renderer/base/images.js' setting Image Cross Origin to null will solve the problem.

**Comment by maxkfranz** [comment]
This is a bug in Webkit itself: https://bugs.webkit.org/show_bug.cgi?id=123978

Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-55b670e25a-1477748336657.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by ibas87** [comment]
@maxkfranz, just tested the snapshot version, it is working perfectly! 

Cheers!

**Comment by maxkfranz** [comment]
@ibas87 Great; thanks for the update

**Comment by Nicolas-PredictaLab** [comment]
This bug is still present, right ? How can we pass 'null' to this properties ? I'm having the very same problem with images not rendered in Cytoscape but rendered in other part of my application.
