### ISSUE TITLE
Cose layout not working properly

### ISSUE THREAD

**Issue by arthurchipdean** [cytoscape/cytoscape.js#1584]
I recently upgraded from 2.5.1 to 2.7.10 and I'm now running into two issues that previously weren't there with the cose layout.
- Specifying the cose layout in the initialization options seems to break the layout completely.
  - See this fiddle: http://jsbin.com/qeyozivipo/edit?js,output
- Adding nodes to the graph and calling `cy.layout({name:'cose'});` also does not apply the layout properly, I am getting overlapping nodes. 
  - Here is a fiddle for this one: http://jsbin.com/sevefoyatu/1/edit?js,output

**Comment by aindlq** [comment]
I can confirm exactly the same behavior with 2.7.9, it works without any issues with 2.7.7.

**Comment by maxkfranz** [comment]
Force-directed / physics simulation layouts generally need unique initial positions to work properly, or you get invalid forces (0 distance) and all the nodes don't move.  You need to either specify nodes with initial positions or tell the layout to set some for you with `randomize: true`: http://jsbin.com/pekotesuno/2/edit?js,output

Same for your second case: http://jsbin.com/gukeqiyuqe/1/edit?js,output

**Comment by maxkfranz** [comment]
@aindlq 2.7.7 incorrectly had `randomize: true` as the default option.

**Comment by arthurchipdean** [comment]
@maxkfranz Why does the second example work without passing randomize if you call `cy.layout({name:'cose'});` inside `cy.ready()`? I'm also not passing the randomize parameter but that one works for some reason.

**Comment by maxkfranz** [comment]
You've provided Cose initial positions from the prior layout

**Comment by arthurchipdean** [comment]
Ahhh that makes sense. Thanks for your help! :+1:

**Comment by maxkfranz** [comment]
See also https://github.com/cytoscape/cytoscape.js/issues/1520 which should automatically mitigate this issue for CoSE
