### ISSUE TITLE
No clear way to style node on click

### ISSUE THREAD

**Issue by uzhcwells** [cytoscape/cytoscape.js#1586]
I'm looking to style a node when it is clicked. I created a 'selector' with a CSS section with the style, but when clicking the node, adding that as a class does not work. I need to know how to do this when a node is clicked. Please help.

Thanks

**Comment by tongbin** [comment]
Are you looking for something like 
```javascript
{
    selector: 'node:selected',
    css: {
      'border-color': 'red',
    }
}
```

**Comment by dpekkle** [comment]
Define it as such
```
var cy = cytoscape({
        ...
	style: [
		{
			selector: '.disconnected',
			style:{
				'border-color': 'red',
			}
		},
        ]
        ...
```
And bind it
```
cy.on('tap', function(event)
{
		event.cyTarget.addClass('disconnected');
});

```
