### ISSUE TITLE
compound node css shape support

### ISSUE THREAD

**Issue by djangosdk** [cytoscape/cytoscape.js#1589]
I am having issues in styling compound nodes.
is `shape` supported as css attribute ?

**JSFIDDLE:** https://jsfiddle.net/bababalcksheep/hzu9t4zw/3/

```
{
      selector: '$node > node',
      css: {
        'background-color': 'black',
        'shape': 'ellipse',
        'background-opacity': 0,
        'border-width': 1,
        'border-color': 'black'
      }
 }
```

**Comment by dpekkle** [comment]
Shape seems to have limited support, 'roundedrectangle' does work but ellipse and star don't appear to be.

**Comment by djangosdk** [comment]
for me  'roundedrectangle'  also does not work.
It would be nice to have ```roundedrectangle```  and ```circle``` support atleast

**Comment by dpekkle** [comment]
Not sure what to say, this works for me:
```
		{
			selector: ':parent',
			style:{
				'shape': 'roundrectangle',
			},
		},
```

If you could update your codepen so that it works (doesn't include jquery for one?) that would help.

**Comment by djangosdk** [comment]
@dpekkle  yes 'roundrectangle' is supported .

**Comment by dpekkle** [comment]
Ah my mistake.
