### ISSUE TITLE
tap event, differentiate between node,edge and background

### ISSUE THREAD

**Issue by djangosdk** [cytoscape/cytoscape.js#1590]
as per http://js.cytoscape.org/#cy.on
Is this correct way to differentiate between node, edge and background tap.
I know there exists `cy.on('tap','node', function(event){ });` but I want to use one global `cy.on('tap', function(event){ });` and differentiate  between clicked target.

``` js
      cy.on('tap', function(event) {
        var evtTarget = event.cyTarget;
        if (evtTarget === cy) {
          console.log('tap on background');
        } else if (event.cyTarget.data().hasOwnProperty('source') && event.cyTarget.data().hasOwnProperty('target')) {
          console.log('tap on Edge');
        } else {
          console.log('tap on Node');
        }
      });
```

Is this correct way ? 
It would be very helpful if `event` has additional data like `event.cyTargetType`  with possible values `background, node, edge` so one can easily differentiate

**Comment by min-metal** [comment]
I guess you can use evtTarget.isNode() and evtTarget.isEdge() if you wanted to.

**Comment by djangosdk** [comment]
@min-metal  Thankx. I missed that.
