### ISSUE TITLE
Search efficiency criteria

### ISSUE THREAD

**Issue by SumNeuron** [cytoscape/cytoscape.js#1594]
Currently functions like `bfs` and `dfs` have a `visit` function which is useful for picking out one `node` in the `collection`; however it is not curtailed for selecting elements given criteria. 

For example, one may wish to get the _extended_-neighborhood of a node where every node in that neighborhood is  at most _k_ "degrees" away from the root. In a search this may be called _max-depth_. e.g, in pseudo code: `if (curDepth > maxDepth) {continue} else {collection.push(curNode)};`

Currently if the visit function returns a value it ends the search. Adding a `continue` as described above also appears to generate an error whereby the graph is no longer rendered. Thus it would be nice to have an optional efficiency tuning criteria.

For example.` if ( this.attribute = someValue ) continue` would greatly improve the efficiency of the search for large graphs and only return nodes / edges of interest. This could be a included in some form of delimited list, e.g.

```
dfs({
roots: someNodes
visit: function(i, depth, v, e, u) {someFunction}
directed: someBoole
tuning: "depth > 500; e.attribute ==  someValue; v.attribute == someOtherValue"
})
```

**Comment by maxkfranz** [comment]
Strictly speaking, no additional APIs are necessary for this usecase.

You would just do something like this:

```js
let noop = () => {};
let kAwayNodes = cy.collection();
let tuningCriteria = el => el.isEdge() || el.data('foo') === someValue && el.data('bar') == someOtherValue;
let add = el => kAwayNodes = kAwayNodes.union( el );
let a = ( i, depth, v, e, u ) => depth > k ? add( u ) : noop;

cy.elements().stdFilter( tuningCriteria ).bfs({ visit: visit /* ... */ });
```

**Comment by SumNeuron** [comment]
Can you walk me through what you did there?

**Comment by maxkfranz** [comment]
It just keeps a set of nodes that's joined on each visit.  The tuning criteria happens beforehand so you run bfs only on the elements of interest (class/data/etc), rather than on the entire graph.

**Comment by SumNeuron** [comment]
Could you please be a tad more specific. I get the tertiary operator, I am confused about the 1st, 4th, and 5th line
