### ISSUE TITLE
Visibility : z-index for curves

### ISSUE THREAD

**Issue by djangosdk** [cytoscape/cytoscape.js#1595]
as per doc, http://js.cytoscape.org/#style/visibility
dges are under nodes despite z-index.

In my case I need to give options for user where he can select a curve or node and bring it at top or bottom just like ms word objects.

Is it possible to override this default behavior which is forced for curves ?

**Comment by maxkfranz** [comment]
See this 3.1 ticket

`z-compound-depth` and `z-index-compare` to control (normally) implicit z-ordering rules #1600
