### ISSUE TITLE
findPaths(s, t, k, n) and print message of paths for debug

### ISSUE THREAD

**Issue by SumNeuron** [cytoscape/cytoscape.js#1597]
The current graph theory algorithms return only the shortest path from the root to the elements in the collection. The only exception being bfs which allows for multiple roots. I would like to request the following two features:

First:

cy.elements().findPaths(s, t, k, n, alg)

where s is the root, t is the desired end node, k is the max length of the paths to find and n is the number of paths to find and alg is an optional argument allowing for algorithm specification.

second:

a textual representation of the paths found for debugging purposes. e.g.

var bfs = cy.elements().bfs({...});
var path = bfs.path;
alert(path.print)

"a -> b -> c, 
b-> c,
e-> f-> b -> c->"

**Comment by maxkfranz** [comment]
If you want to find all paths, you're basically just doing a BFS and that algorithm is already built-in.

If you want to get a string like that just do `eles.map( ele => ele.id() ).join('->')`

**Comment by SumNeuron** [comment]
Yes and no. bfs.path gives an object for the path. Your code yields just a long list without separation of paths. If on squints one can try and find where the node and the next edge are inconsistent, but not ideal.

It is clear even by your naming convention that bfs.path is meant to return one path, not many thereof.  Thus this should not be closed as the features requested are not existent.

**Comment by maxkfranz** [comment]
BFS returns one path by definition.  But it traverses over each reachable node at least once.  You can use this information as you traverse and built up your own lists.  You would use my snippet on each path that you build up.

Or you just have to run Dijkstra N times.
