### ISSUE TITLE
Multiline label support with horizontal line (<hr> tag usage) between lines

### ISSUE THREAD

**Issue by bishtravindra11** [cytoscape/cytoscape.js#1615]
Multiline label support with horizontal line (\<hr\> tag usage) between lines.
**Example:**
![image](https://cloud.githubusercontent.com/assets/13809295/20514458/01dffd26-b0b2-11e6-9f0b-decc0f8d1f1f.png)

**Comment by maxkfranz** [comment]
Have you tried a repeated background image with the lines?
