### ISSUE TITLE
Allow a child element to appear 'selected' when parent is clicked

### ISSUE THREAD

**Issue by lszanto** [cytoscape/cytoscape.js#1625]
I have a basic setup with an parent element and a child element. The child element has events set to no so that the parent is responsible for grabbing and moving the element. However it means when the element is selected there is a big whole in the middle of the overlay where the child sits. 

I've tried on grab to select the element but this doesn't work as it has no events registered. I also tried to increase the overlay padding but it seems to be a layering issue.

Is there any way to make it appear selected or possibly have the overlay as the highest z-index?

This is what it looks like:

![selected](https://cloud.githubusercontent.com/assets/139145/20656384/2c776d1c-b580-11e6-87b1-301dd18d9f72.png)

**Comment by maxkfranz** [comment]
No, overlays are a part of an element.

You have control over appearance with the stylesheet.  Do something like

```
node:active node {
  // my style here; maybe darken the children
}
```

**Comment by lszanto** [comment]
I pulled out the colour with a colour picker so I could simply change the backround in node:active node however it doesn't seem to be working when the parent is selected. Elements that I target with
`node node`
seem fine however
`node:active node`
Doesn't seem to be picking anything up, is this correct?
```
{
    selector: 'node:active node',
    style: {
        'background-color': '#9a9a9a'
    }
}
```

**Comment by lszanto** [comment]
Fixed this another way @maxkfranz ended up setting background opacity of the child to 0 so that all background color/overlay changes simply come through.

**Comment by maxkfranz** [comment]
Looks like you found a bug https://github.com/cytoscape/cytoscape.js/issues/1628

**Comment by lszanto** [comment]
@maxkfranz can confirm this now works for me. Tested with :selected and :active descendants.

**Comment by maxkfranz** [comment]
Great; thanks!
