### ISSUE TITLE
Option to specify whether labels are included in overlap detection for layouts

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1626]
Including labels can make the graph more spaced out than desired in some cases.  Having an option would give more control over the output.

`options.nodeDimensionsIncludeLabels` : If `true`, the width of a node is considered to be `node.boundingBox().w`.  If `false`, the width of a node is considered to be `node.outerWidth()`.  The analogous cases for height also hold.

Uses `node.layoutDimensions()`

Ref https://github.com/cytoscape/cytoscape.js/pull/1784

- [x] Update bundled layouts
- [x] Update first-party extensions
  - [x] Dylan
    - [x] arbor
    - [x] cose-bilkent
    - [x] spread
    - [x] springy
    - [x] cola
  - [x] Max
    - [x] klay
    - [x] euler
    - [x] dagre
- [x] Add the option in the slush-cytoscape-extension generator layout template files

**Comment by d2fong** [comment]
cose-bilkent in progress - https://github.com/cytoscape/cytoscape.js-cose-bilkent/pull/53
