### ISSUE TITLE
eles.classes() vs eles.classes('') for clearing classes

### ISSUE THREAD

**Issue by righettime** [cytoscape/cytoscape.js#1631]
Per the [documentation](http://js.cytoscape.org/#eles.classes), the function eles.classes() should accept no parameters if you wish to remove the classes, but this throws a error "Uncaught TypeError: Cannot read property 'match' of undefined(…) - cytoscape.min.js:26".  Not sure if this is a documentation error or minor bug.

**Comment by maxkfranz** [comment]
I think it's supposed to work with either `.classes()` or `.classes('')`.  Must be a bug

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-53545212c4-1481058547047.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by righettime** [comment]
That did the trick!  Thanks @maxkfranz

**Comment by maxkfranz** [comment]
Great; thanks
