### ISSUE TITLE
cy.center(el) seems to be positioning perfectly on Y-axis but not on X-axis

### ISSUE THREAD

**Issue by lszanto** [cytoscape/cytoscape.js#1640]
I have a list of nodes/edges i'm loading in via cy.json(). Everything loads correctly.

After loading the json I want to position the view to be looking at the first node. To get the first node i'm loading/centering it with:
```
var firstEl = cy.$('node')[0];
cy.center(firstEl);
```
I've checked and this it fetching me the right node however it does not seem to be aligning correctly across the X-axis, only the Y-axis seems to be centered on the node. 

Node[0] contents:
```
      {  
         "data":{  
            "id":"node01",
            "title":"1"
         },
         "position":{  
            "x":673.7692285732613,
            "y":-24.551160667420913
         },
         "group":"nodes",
         "removed":false,
         "selected":false,
         "selectable":true,
         "locked":false,
         "grabbable":true,
         "classes":""
      }
```

Screenshot:
<img width="1280" alt="screen shot 2016-12-07 at 11 13 56 am" src="https://cloud.githubusercontent.com/assets/139145/20949728/27225872-bc6f-11e6-8745-999323151608.png">

**Comment by maxkfranz** [comment]
I just tested this, and it's working for me.

Make sure you've sized your container properly in your CSS.  It's probably overflowing to the right.

**Comment by lszanto** [comment]
I just have the container set to: 
```
#cy {
    position: absolute;
    left: 50px;
    top: 0;
    bottom: 0;
    right: 0;
}
```

Could the 50px allocated for the toolbar be the issue?

I also tried instead of setting it that way to include a width and height and it seemed to center the node more but still not in the middle.

1500px wide container:
![1500px](https://cloud.githubusercontent.com/assets/139145/20987073/4ef38140-bd1f-11e6-933b-b34a4c1d32f7.png)

1800px wide container:
![1800px](https://cloud.githubusercontent.com/assets/139145/20987081/567b64f0-bd1f-11e6-8dad-ed2bbe5c9807.png)

**Comment by maxkfranz** [comment]
There's no way to tell without inspecting it live.  Please make a small jsbin that reproduces your issue

**Comment by lszanto** [comment]
This is roughly what i'm working with and shows the error: https://jsbin.com/poquvalazi/

**Comment by lszanto** [comment]
Yet this snippet works fine if you're outputting on the same page but if you view on it's own page it doesn't work: https://jsbin.com/solevoluju/1/edit?js,output

**Comment by maxkfranz** [comment]
You've explicitly specified an animated layout with fitting.  Obviously the fitting would change the viewport state.

The subtle bit is that you've effectively created a race condition with the layout and any other viewport ops around the same time.

If there aren't any elements specified at init, there's no reason to specify an init layout at all -- especially an animated one.

**Comment by lszanto** [comment]
Thanks heaps mate, thought I was going nuts. This makes a lot of sense.
