### ISSUE TITLE
`ResizeObserver` for more automatic `cy.resize()`s

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1652]
We already catch direct attribute changes on the container (e.g. `el.classList.add()`) for resizes, but using the proposed [`ResizeObserver`](https://developers.google.com/web/updates/2016/10/resizeobserver) would catch more cases and would avoid some false positives.

Once the spec is finalised, we can use it with a check for the API's existence.  We can fall back on the existing behaviour if `ResizeObserver` is unavailable.

**Comment by TrySound** [comment]
https://github.com/que-etc/resize-observer-polyfill

**Comment by maxkfranz** [comment]
Thanks.  That would allow for an easier transition when it's supported natively in the browsers. However, it seems like the `ResizeObserver` API is just a [draft](https://wicg.github.io/ResizeObserver/) at this point and could change in future.  We're already doing what the `resize-observer-polyfill` does under the hood with `MutationObservers` etc.  So it probably doesn't make sense to take action on this now, but the polyfill could be useful when the `ResizeObserver` API is finalised.

**Comment by maxkfranz** [comment]
More browsers support this now or will support it soon: https://caniuse.com/#search=resizeobserver

Let's put this in the 3.9.0 milestone.

**Comment by maxkfranz** [comment]
I'm not getting errors with eslint when I run it locally:

```
$ node --version
v10.16.0
$ npm --version
6.9.0
$ npm run lint

> cytoscape@3.9.0-unstable lint /Users/max/Documents/workspace/cytoscape.js
> eslint src benchmark

$
```

**Comment by maxkfranz** [comment]
Though I can't reproduce the linting error, I have added comments to disable the eslint warnings in c18937bb12e47d21658e53566d0326e49b8d6ae6.
