### ISSUE TITLE
Implementing triangle-tee arrow shape variants

### ISSUE THREAD

**Issue by d2fong** [cytoscape/cytoscape.js#1656]
@maxkfranz @ugurdogrusoz  @gbader @jvwong @metincansiper @IgorRodchenkov 

### Note
**This is a translation of my notes from talking with Max about how to implement custom arrow 
shapes.  They represent a skeleton implementation and they are not fully fleshed out.**  

# Requirements
Custom arrow shapes are needed for cytoscape.js.

Here is an example arrow shape that is required:
![screen shot 2016-12-19 at 11 34 39 am](https://cloud.githubusercontent.com/assets/2328291/21365977/c74dff62-c6c5-11e6-8109-6ceaeb25d810.png)

# Implementation Notes

### Draw the arrow-tee in phases
Split up the drawing execution into phases. 

For example:
* phase 0 draws the arrow head
* phase 1 draws the arrow edge connector
* phase 2 draws extra lines that represent the variations in the arrow-tee
Each portion of the shape can be rendered differently via config values associated with each phase.

### Phase config values
* ```multiphased```: boolean representing whether this shape should be drawn in multiple phases or not
* ```matchEdgeWidth```: list of n booleans corresponding to the n drawing phases for the arrow shape.  If matchEdgeWidth[n-1] is true, then phase n-1 will be drawn with the same line width as the edge it is attached to.
* ```forceStroke```: boolean to override a shape style and render it using strokes instead of fill. (Used for special cases such as a line between two points.  In this case, you need to draw it using a stroke)

### Other remarks

 The collision function for `necessary stimulation` could be improved. 

```js
    collide: function( x, y, size, angle, translation, padding ){
      var triPts = pointsToArr( transformPoints( this.points, size + 2 * padding, angle, translation ) );
      var teePts = pointsToArr( transformPoints( this.pointsTee, size + 2 * padding, angle, translation ) );

      var inside = math.pointInsidePolygonPoints( x, y, triPts ) || math.pointInsidePolygonPoints( x, y, teePts );

      return inside;
    },
```

```math.inlineVicinity``` and ```math.squareDistanceToFiniteLine``` could be better suited for detecting collisions.

```pointsTee``` should be renamed to ```pointsLine``` or something more descriptive -- the points currently do not represent a tee.

A generic name for this type of arrow should be considered over the biology specific ```necessary stimulation``` term.  ```arrow-tee-stripe```, ```arrow-tee-cross``` are potential names.

**Comment by metincansiper** [comment]
@d2fong Thanks, it seems nice. However, there are some points not clear to me. 
- I am not sure if I understand what you mean by config in correct way. What I understand by config is something similar to 'shape-polygon-points' defined for 'polygon' shapes.  Am I correct?
- If what I understand by config is correct then I think that a config may be defined for the 'pointsTee' (or 'pointsLine' with the new name that you suggested) and users may be able to set it as well (In this way current 'triangle-tee' in cytoscape can be rendered using this arrow type as well and one more arrow type will not be needed). 
- What portion is rendered by phase 0 is clear to me. However, I am not sure if I understand what portions are rendered by phase 1 and phase 2. Please would you number them in the shape that you attached? (Sorry, most probably they are already clear but I could not figure out that portions clearly)

**Comment by d2fong** [comment]
@metincansiper 

### Note
First note that I should have made clear in the original post:
**This is a translation of my notes from talking with Max about how to implement custom arrow 
shapes.  They represent a skeleton implementation and they are not fully fleshed out.**  

### Config Values
The config values refer to how the arrow part is drawn in each phase.  
Config values will be defined in the triangle-tee implementation.

### Phase Map
I am not exactly sure which phase will draw which part of the arrow yet.  I really only have the concept of associating a part of the arrow with a specific phase.  

My guess is that the normal arrow shape will be drawn in one phase, and then the line parallel to the base of the arrow head would be drawn in a separate phase.


### Prototype Code
Here are some of the ideas that me and Max talked about:

Config value definition idea:
src/extensions/renderer/base/arrow-shapes.js
```js
  defineArrowShape( 'triangle-tee', {
    points: [
      -0.15, -0.3,
      0, 0,
      0.15, -0.3,
      -0.15, -0.3
    ],

    pointsTee: [
     ....        // user specifies the points here 
    ],

    multiphased: true,

    matchEdgeWidth: [true, false],

    forceStroke: true,
    
     ...
     ...
  } );
```

Example: src/extensions/renderer/canvas/drawing-edges.js

1. add a phase parameter, and then conditionally render portions of the arrow based on the phase

```js
CRp.drawArrowShape = function( edge, arrowType, context, fill, edgeWidth, shape, x, y, angle, phase, forceStroke ){
  // truncated implementation
  if( phase === 0 ){
        // render first part of arrow
  }

  if ( phase === 1 ){ 
      // render second part of the arrow
   }
};
```

2.  using the values in the config, render the part to be drawn in the specific phase differently:

```js
CRp.drawArrowShape = function( edge, arrowType, context, fill, edgeWidth, shape, x, y, angle, phase, forceStroke ){

  // truncated implementation
  if( fill === 'hollow' || fill === 'both' ){            // render edge width based on config value
    context.lineWidth = ( shapeImpl.matchEdgeWidth || shapeImpl.matchEdgeWidth[phase] ? edgeWidth : 1 );     
    context.lineJoin = 'miter';

    if( usePaths || forceStroke ){                    // forceStroke config value example (not necessarily where it is exactly used)
      context.stroke( path );
    } else {
      context.stroke();
    }

  }
```

**Comment by d2fong** [comment]
We want to split up drawing the arrow parts so that each part can have more control over how each part is rendered.

**Comment by maxkfranz** [comment]
@d2fong Would you please add the feature to the docs (`.md` files)  in `/documentation`?

**Comment by d2fong** [comment]
Okay I can do that.  Do I use the same workflow (work on my fork then pull request) ?

**Comment by maxkfranz** [comment]
Normally, it's best if the docs go in the same PR as the code.  It's fine to just commit the docs update directly to unstable this time.  (You just need to update the md; you don't need to build the docs or anything.)

**Comment by d2fong** [comment]
Okay, I have updated the docs, should I close this issue?

**Comment by maxkfranz** [comment]
Yes, I think that's all
