### ISSUE TITLE
On Tap :selected() different in desktop vs mobile

### ISSUE THREAD

**Issue by imukai** [cytoscape/cytoscape.js#1659]
Given the following:

```
cy.on('tap', 'node', function (e) {
  var select = e.cyTarget.selected();
});
```
Click an unselected node in the graph, thus selecting it.  On desktop, for the above tap event, select == false.  On mobile, select == true.

Is there a foolproof way to determine if the user just selected or deselected a node by their tap action, without resorting to caching previously-selected nodes or messing with a setTimeout?  I could not find this documented anywhere.

**Comment by maxkfranz** [comment]
There is no documentation on the order of events.  Similarly, the order of events is not guaranteed, except for obvious cases like `mousedown`, `mouseup` => `click`.

If you want to get the change of state of selection, you should listen to `select` events.
