### ISSUE TITLE
node background-image: fails using local http server

### ISSUE THREAD

**Issue by paul-shannon** [cytoscape/cytoscape.js#1660]
In RCyjs I execute this statement in a loop, one for each image url passed in from R:

    cy.nodes(filterString).style({"background-image": urls[i], "background-fit": "cover"});

When the url is 

    http://farm9.staticflickr.com/8316/8003798443_32d01257c8_b.jpg

things work fine.   But it fails when the same image file is served up locally, at 

    http://localhost:5000/8003798443_32d01257c8_b.jpg

I have verified that the localhost:5000 image indeed loads fine into another (non-cyjs) tab in my browser, from the simple python http.server running on port 5000.   

`background-image-cross-origin` has its default  value in all cases.

Do you know how I might be able to get local images to display on nodes?

Thanks!

**Comment by maxkfranz** [comment]
You need the [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) header set on the server.  If you use the [http-server](https://www.npmjs.com/package/http-server) package for local development, you can just use the `--cors` option.

**Comment by pshannon** [comment]
Thanks, Max.  I am must seeing your reply today.  I will give this a try.

 - Paul
