### ISSUE TITLE
Zoom and freeze

### ISSUE THREAD

**Issue by uzhcwells** [cytoscape/cytoscape.js#1662]
When viewing different graphs in cytoscape.js, I have noticed a "zoom and freeze" issue, where the graph zooms in on nodes and then is not responsive to panning, zooming, etc. This happens as I transition between graphs, redrawing new nodes for different graph representations. Is this the use of caching or a pre-rendered image in the viewport? Can the caching behavior be turned off by default?

**Comment by maxkfranz** [comment]
Would you please provide an example graph that reproduces this behaviour?

It's probably enough to just paste in your data and layout into one of the demos on JSBin: http://js.cytoscape.org/#demos
