### ISSUE TITLE
"target-label" and "source-label" use text from "label" / "content"

### ISSUE THREAD

**Issue by Fannon** [cytoscape/cytoscape.js#1663]
Hello,

thanks for creating this awesome graph library! It works very nicely for me.

I'm having one issue, though:
I'd like to use a cardinality on an edge (at the target side). If I supply the parameter, cytoscape will draw a target-label but it will use the text from "label" instead of the "target-label". Same happens with "source-label". Did I miss something here, or is this a bug? If I switch to 'curve-style': 'segments', the behavior is still the same.

```text
{
    selector: 'edge',
    style: {
        'label': 'data(label)',
        'target-label': 'data(cardinality)', // TODO: Doesn't work -> Bug :(
        'source-label': 'SOURCE', // TODO: Doesn't work -> Bug :(
        'text-wrap': 'wrap',
        'color': '#000',
        'line-color':'#DDD',
        'target-arrow-color': '#DDD',
        'target-arrow-shape': 'triangle',
        'font-size': '7px',
        'width': '3px',
        'curve-style': 'bezier'
    }
},
 ```

Resulting in:
[NODE-1]--data(label)----data(label)-----data(label)-->[NODE-2]

instead of:
[NODE-1]--SOURCE----data(label)-----data(cardinality)-->[NODE-2]

Best,
Simon

**Comment by Fannon** [comment]
I think I could narrow the problem down:

If `'text-wrap': 'wrap',` is removed, everything works as expected

**Comment by maxkfranz** [comment]
Yes, it happens only when `text-wrap: wrap` for source and target labels.  I've pushed a fix.  It's a slight change to one line.

Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-7b5148865c-1483550792165.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by insiderinside** [comment]
still bug ? im use like this:
'target-label': 'data(label-data)', // TODO: Doesn't work -> not showing label-data just a text "data(label-data)".
using version 3.18.1
