### ISSUE TITLE
a function like jquery UI sortable

### ISSUE THREAD

**Issue by yujunjie0603** [cytoscape/cytoscape.js#1664]
Hi :
I would like to perform a function like JqueryUI sortable, do you have some idea plz ?

**Comment by maxkfranz** [comment]
Can you describe this in detail?

**Comment by yujunjie0603** [comment]
for example, Exchange places between two nodes !

http://jqueryui.com/sortable/#default

**Comment by maxkfranz** [comment]
You can animate the nodes going to the opposite positions: http://js.cytoscape.org/#cy.animation
