### ISSUE TITLE
Reworked `resize` event

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1665]
The `resize` event should be triggered not only when `cy.resize()` is explicitly called but also when the renderer detects a div/window resize and updates internally.  (The `resize` event is undocumented in 2.x.)

**Comment by metincansiper** [comment]
@maxkfranz please try the following fiddle (http://jsbin.com/daheveyati/1/edit?js,console,output). In this fiddle, if you resize the window you see that 'window resized' is printed out but 'cy resized' is not. However, in documentation(http://js.cytoscape.org/#cy.resize) it is written that 'cy.resize() is automatically called for you on the window‘s resize event'. Though the resize event is not documented yet I think that it is supposed to be called on 'cy.resize()' and 'cy.resize()' is supposed to be called on window resize. I think that there may be a problem here.

**Comment by maxkfranz** [comment]
JSBin is within a different iframe, and so it's in a different window.

**Comment by metincansiper** [comment]
@maxkfranz I tried to do the same thing without using jsbin. Please run 'index.html' in the attached zip file. if you resize the window you will see that 'window resized' is printed out but 'cy resized' is not.
[demo.zip](https://github.com/cytoscape/cytoscape.js/files/688107/demo.zip)

**Comment by maxkfranz** [comment]
The event doesn't look like it's meant to be used like that.  It's fired only when someone calls `cy.resize()`.

**Comment by metincansiper** [comment]
Okey, thanks.
