### ISSUE TITLE
cy.json() and ele.json() generate circular structures when compound nodes are present

### ISSUE THREAD

**Issue by fedarko** [cytoscape/cytoscape.js#1667]
I'm looking into exporting the JSON for a graph using Cytoscape.js to the desktop Cytoscape application. It seems that both `cy.json()` (when at least one compound node is present within the graph) and `ele.json()` (where `ele` refers to a compound node) generate JSON objects that cannot be passed into `JSON.stringify()`, and therefore can't (as far as I can tell) be exported to the desktop Cytoscape application.

When compound nodes are not in the graph, the JSON generated is not circular (calling stringify on it works). I've tested this phenomenon by opening graphs with compound nodes, calling `JSON.stringify(cy.json());` from my browser's console, and observing an `Uncaught TypeError: Converting circular structure to JSON` error. Calling `cy.remove()` on all of the compound nodes in the graph results in the stringify call working without error.

For reference, I'm running Chromium 55.0.2883.75 as my browser, on Debian 8.6.

**Comment by maxkfranz** [comment]
I just confirmed that `cy.json()` and `ele.json()` are serialisable.  There are no circular references.

You've probably got circular references in what you're putting in `.data()`.  You're only allowed to put plain JSON data in `.data()`, as the docs say.  Complex objects and other temp data goes in `.scratch()`.  Please confirm your data is correct, and provide an example that illustrates the bug if you can reproduce with proper data.

**Comment by fedarko** [comment]
My apologies—this was my fault. I was storing collections of certain elements within the `.data()` fields for compound nodes.

I did not notice anywhere in the documentation that certain types of data could not be stored in `.data()`, although I see now that the documentation does mention that non-JSON data can be stored in `.scratch()`. I'm sorry for the confusion.

**Comment by maxkfranz** [comment]
The docs are pretty long.  It should be mentioned in more sections in the docs if it's not clear: https://github.com/cytoscape/cytoscape.js/issues/1670
