### ISSUE TITLE
Issue with node selector and boolean value

### ISSUE THREAD

**Issue by pwichmann** [cytoscape/cytoscape.js#1671]
I seem to have stumbled across a problem with a node selector based on a boolean value.

In the style I defined my nodes as (excerpt):

```
elements: {
	nodes: [
		{ data: { id: 'n1', visible: true, selected: false } },
```

And now I would like to select nodes that are visible _AND_ selected. 
NB: These are properties I made up.

If I try to select them like this:

```
cy.nodes("[visible = true][selected = true]");
```

Then I get an error:
```
cytoscape.min.js:62 The selector `[visible = true][selected = true]`is invalid
```

Why is that? Do I need to escape the boolean values somehow? Are boolean values not accepted for a selector? Or do my properties conflict with some internal properties?

**Comment by josephst** [comment]
If you want to structure your selectors like that, try `cy.nodes("[foo = 'true'][bar = 'true']")` (i.e. wrap the boolean values in quotes). However, I would recommend using the [boolean-specific selectors](http://js.cytoscape.org/#selectors/data). It's more concise to write your code as `cy.nodes('[?foo][?bar]')`.

**Comment by pwichmann** [comment]
You're a star, mate.
I was sure I had tried ```[visible = 'true']``` but - in any case - she shorthand boolean notation works like a charm. Many many thanks!

Solved.

**Comment by maxkfranz** [comment]
> [visible = 'true']

That would be using coercion under the hood, as only strings and numbers are supported for values in comparisons.  Better to use the truthy selectors.
