### ISSUE TITLE
PhantomJS won't load cytoscape

### ISSUE THREAD

**Issue by ibas87** [cytoscape/cytoscape.js#1675]
I have got an Angular App and I am writing unit tests for a component that uses Cytoscape.

When running the unit tests seems that PhantomJS doesn't import Cytoscape correctly, the import is returning 'undefined'. 

Is there any limitation on what I am trying to achieve? Everything works well during runtime on a browser.

**Comment by ibas87** [comment]
While importing cytoscape, it starts at cytoscape/src/index.js and it loads everything until "require('./is')" but not "require('./core')". Seems that some dependency is failing to load.

**Comment by ibas87** [comment]
Also I forgot to mention that I am using Traceur.

After some deep ivestigation I found why some files fail to import.

For example:
cytoscape/src/collection/animation.js

(...)
`var elesfn = ({
	animate: define.animate(),
	animation: define.animation(),
	animated: define.animated(),
	clearQueue: define.clearQueue(),
	delay: define.delay(),
	delayAnimation: define.delayAnimation(),
	stop: define.stop()
});`
(...)

this code fails while importing, wrapping it with a try catch:

(...)
`try {
	var elesfn = ({
    	animate: define.animate(),
    	animation: define.animation(),
    	animated: define.animated(),
    	clearQueue: define.clearQueue(),
    	delay: define.delay(),
    	delayAnimation: define.delayAnimation(),
    	stop: define.stop()
  	});
} catch(e) {
  	console.log('error', e);
}`
(...)

I got the following error: 
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: Requested keys of a value that is not an object.
  at /my-project/tests/spec.bundle.js:2382 <- webpack:///~/traceur/bin/traceur-runtime.js:2316:0


Removing the parentheses seems to work:

(...)
`var elesfn = ({
	animate: define.animate,
	animation: define.animation,
	animated: define.animated,
	clearQueue: define.clearQueue,
	delay: define.delay,
	delayAnimation: define.delayAnimation,
	stop: define.stop
});`
(...)

This problem is happens across multiple files, have you experienced anything similar?

**Comment by maxkfranz** [comment]
You shouldn't be running Traceur or Babel on anything in your  `dependencies` for `package.json`.  You should exclude the `node_modules` folder.

See http://stackoverflow.com/questions/31822593/import-a-module-from-node-modules-with-babel-but-failed

See https://github.com/cytoscape/cytosnap for an example package that runs Cytoscape in Phantom for an example.
