### ISSUE TITLE
Style transition animations

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js#1677]
Are there any style properties not supported by transition animations? I'm seeing some weird behaviour surrounding the label-styles? 

I'll try to boil it down to a proper test case if the style properties should be supported?

**Comment by maxkfranz** [comment]
A transition doesn't make sense at all unless it's on a numeric property.  Colours are also numeric properties (i.e. [r, b, g]).

**Comment by maxkfranz** [comment]
It's the same in CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties

**Comment by buffpojken** [comment]
Oh, sure thing - the weird behavior I was seeing was regarding font-size and opacity - which ought to be numeric? 

But I'll try to isolate a test case - will update here!

**Comment by buffpojken** [comment]
Hmm, never mind - I can't seem to isolate a test case anymore. I'll re-open this if I manage to isolate one in the future.

**Comment by maxkfranz** [comment]
@buffpojken OK, please do re-open if you can find a test case
