### ISSUE TITLE
Wrong font-family rendered on zoom when font-weight set to bold.

### ISSUE THREAD

**Issue by Andreew4x4** [cytoscape/cytoscape.js#1692]
Font family is swap on specified zoom - which cause cropped label.
Node styles:
```javascript
{
              selector: 'node',
              style: {
                'height': 40,
                'width': 40,
                'background-color': '#ccc',
                'label': 'data(label)',
                'font-family' : 'Open Sans',
                'font-size': '16px',
                 'font-weight': 'bold'
              }
},
```
Zoom out:
![zoomout](https://cloud.githubusercontent.com/assets/7188840/22287647/e92051cc-e2f3-11e6-9ae4-e4be34087448.png)

Zoom in:
![zoomin](https://cloud.githubusercontent.com/assets/7188840/22287653/ec72078a-e2f3-11e6-9eb2-2ab3dacad2c6.png)

When font-weight bold is removed. Bug doesn't occur.

**Comment by maxkfranz** [comment]
I can't reproduce this on the debug page or the label demo.  I think you may have something else going wrong in your app, like not guaranteeing that your fonts are loaded before you init Cytoscape.
