### ISSUE TITLE
A question on overriding stylesheet

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1696]
Please see the following fiddle ( http://jsbin.com/gowagojeci/1/edit?js,console,output ). In this fiddle there is a previously defined function for 'background-color' of ':parent' selector. Then I override it so that it will return 'red' if an external parameter is truthy and return 'black' otherwise. What if I want it to get the return value of overriden function, as if I did not override it, instead of black when the external variable is not truthy. Is there a way of doing it.

Thanks,
Metin

**Comment by maxkfranz** [comment]
You are only to use pure(ish) functions.  There's no way for Cytoscape to know when you change an outside variable.  Change the stylesheet or use a class etc.
