### ISSUE TITLE
Make `touch*` event handlers explicitly `passive: false` in renderer

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1702]
Chrome has broken compatibility with touch events.  This means that several gestures/events supported by Cytoscape won't work properly on touch devices that use Chrome.

The current living-standard [W3C spec](https://dom.spec.whatwg.org/#dom-eventtarget-addeventlistener) says [`passive` should be `false` by default](https://dom.spec.whatwg.org/#event-flatten-more).  Chrome doesn't follow this.

Confirmed broken:

- `drag` gesture on node
- `pan` gesture
- pinch-to-zoom (`zoom` and `pan`)
- box selection (`boxstart`, `boxend`, `box`, `boxselect`)
- `cxtdrag`
- `cxtdragover`
- `cxtdragout`

We'll add a workaround for this breaking change that Chrome has made.

This also may affect Chrome on touch desktops, like the Surface --- the touchscreen won't work.  That's not as problematic, because you can use the touchpad/mouse instead.

See 

- https://bugs.chromium.org/p/chromium/issues/detail?id=639227
- https://www.chromestatus.com/features/5093566007214080
- https://github.com/w3c/touch-events/issues/74
- https://github.com/WICG/interventions/issues/18
- https://dom.spec.whatwg.org/#dom-eventtarget-addeventlistener

**Comment by dtapuska** [comment]
It appears you are binding pointer events and touch events. ie; https://github.com/cytoscape/cytoscape.js/blob/2816df20bb7410a6b9450ab689c7a03674046768/src/extensions/renderer/base/load-listeners.js#L1954 

and you are preventDefaulting the pointer events so you won't get touch events. Could this be that your pointer event code isn't setting touch-action correctly and that this is in fact broken in Microsoft Windows Phone as well?

**Comment by dtapuska** [comment]
Also you appear to be using fastclick in the documentation directory. Avoiding fastclick has been suggested for some time now. See #fastclick/498

**Comment by maxkfranz** [comment]
Thanks for your response!

> It appears you are binding pointer events and touch events. ie; https://github.com/cytoscape/cytoscape.js/blob/2816df20bb7410a6b9450ab689c7a03674046768/src/extensions/renderer/base/load-listeners.js#L1954
>
> and you are preventDefaulting the pointer events so you won't get touch events. Could this be that your pointer event code isn't setting touch-action correctly and that this is in fact broken in Microsoft Windows Phone as well?

That's a good guess, but pointer events don't get registered, [unless the browser has no touch event support](https://github.com/cytoscape/cytoscape.js/blob/2816df20bb7410a6b9450ab689c7a03674046768/src/extensions/renderer/base/load-listeners.js#L1897), like the Surface or Windows phone.  So, pointer events do not affect this lib on Chrome.  We've definitely confirmed that the Surface works on Cytoscape 2.7.

> Also you appear to be using fastclick in the documentation directory. Avoiding fastclick has been suggested for some time now. See ftlabs/fastclick#498

That's a good call.  Originally, the docs had some more sophisticated widgets on them and it was really nice to have them working quickly on older Android tablets or older iPads, for which Fastclick is still necessary.  It could be removed from the docs pages now, though, considering mostly devs read it and the lag would only affect the run links now. https://github.com/cytoscape/cytoscape.js/issues/1703

However, Fastclick is a bit of a red herring for the topic at hand.  It's not a dependency, and it doesn't affect Cytoscape.  Cytoscape gets negatively affected by making `passive: true` default, Fastclick or no.

The main concern regarding Cytoscape is that the lib is used in many places, in both academia and commercial organisations, not all of which can easily update their code.  Having support for passive events in Chrome is great but unfortunately, changing the default behaviour breaks our lib and many apps that depend on it.
