### ISSUE TITLE
Fire `background` event on a node when its background image loads

### ISSUE THREAD

**Issue by Kurtas** [cytoscape/cytoscape.js#1711]
`node.trigger('backgrounded')` when a background image is applied to a node.  The image may be cached, so it's important to emit the event when the image is newly applied per node --- not newly loaded.

OP follows:

---

Hello,

we use icons (```background-image```) for nodes and we have script which takes data and generates pictures of charts. I found that ```layoutstop``` event is triggered before image is loaded into layout.

See this JsFiddle http://jsfiddle.net/2q2uy3q2/3/

As you can see, first loading of page shows PNG without icons and in the cytoscape chart it's loaded after few ms. When you hit RUN button again then the icons are also exported into PNG, but when you try to change image icon URL for one node then this new icon isn't exported (other yes), it will exported in next run. There must be some kind of cache.

**Comment by maxkfranz** [comment]
I think you've misunderstood the meaning of a layout.  A layout is just a mapping of node to position.  It may be continuous, applying positions over time.  It may alternatively be discrete, applying just a final position.  A layout fires `layoutstop` after setting the final positions.  

A layout has nothing to do with background images, and `layoutstop` is not analogous to the `load` event for `window`.

If you want to know whether a node is still loading, you should use the `:backgrounding` [state selector](http://js.cytoscape.org/#selectors/state) in your stylesheet or with [`ele.is()`](http://js.cytoscape.org/#eles.is) etc.

**Comment by Kurtas** [comment]
Thanks, but I think that there should be also be an event when chart is ready for export.

**Comment by maxkfranz** [comment]
It's possible to have an event per-element, such as `backgrounded`, corresponding to the change in state from `:backgrounding` to `:nonbackgrounding` for a non-null image end state. 

However, it's not really useful at init:

(1) You can't listen to events during the init call --- only after.  If the all images are cached, for example, you would be too late to listen.

(2) Events bubble from the elements to the core, so you couldn't expect the event firing on `cy` to mean that all images are loaded.  Further, an event with a different name for all element images loaded doesn't make sense:  The set of elements in the graph is dynamic.  Add or remove a node and suddenly the event means something else or it loses meaning altogether.

If an event is added, your workflow would be the same --- except you wouldn't have to use polling to find when the background state changes, e.g.

```js
cy.add( elesJson );

let bged = cy.nodes().map( n => n.is(':nonbackgrounding') ? Promise.resolve() : n.pon('backgrounded') );

let layouted = cy.pon('layoutstop');

cy.makeLayout( layoutOpts ).run();

let exportReady = Promise.all([ layouted, ...bged ]);
```
