### ISSUE TITLE
`:childless` selector & `ele.isChildless()`

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1714]
Add a `:childless` selector that matches an element for which `ele.isChildless()`, i.e. `ele.isNode() && !ele.isParent()`.

OP follows:

---

Hi,
I was wondering if any selector for simple nodes (nodes with no children) in cytoscape.js. Or is there any selector similar to css ':not' selector (If such a selector exists ':not(:parent)' may work to cover simple nodes).

**Comment by maxkfranz** [comment]
There's no special state selector (like `:nonparent`).  There could be. 

For now, you can just specify with the order in your stylesheet.

```
node {
  /* non-parents & parents */
}

node:parent {
  /* overrides for parents */
}
```
