### ISSUE TITLE
node style rendering just changed? rectangle for octagon when zoomed out

### ISSUE THREAD

**Issue by paul-shannon** [cytoscape/cytoscape.js#1719]
I imagine this is a feature :} - but it takes me surprise.  Is there a style option which does full rendering and styling regardless of the zoom?

<img width="253" alt="screen shot 2017-02-21 at 6 50 09 pm" src="https://cloud.githubusercontent.com/assets/2480712/23195039/a1b2a5be-f866-11e6-8eed-327fde22487f.png">

becomes

<img width="236" alt="screen shot 2017-02-21 at 6 50 18 pm" src="https://cloud.githubusercontent.com/assets/2480712/23195046/a989e1b2-f866-11e6-8fc2-93ee8bc234cf.png">

**Comment by maxkfranz** [comment]
Would you please post an example graph JSON (esp. `elements` & `style`)?

**Comment by maxkfranz** [comment]
@paul-shannon Any updates on the json?

**Comment by maxkfranz** [comment]
I think this should be addressed by the issues fixed in 3.2.7: https://github.com/cytoscape/cytoscape.js/milestone/107?closed=1
