### ISSUE TITLE
Accessing documentation of older versions of Cytoscape.js

### ISSUE THREAD

**Issue by vigneshdv** [cytoscape/cytoscape.js#1721]
Is there a way to access the older versions of the website/documentation for cytoscape.js? 
I am still using 2.6.X version for my project and wanted to look at that versions documention, but couldnt find a way to jump to that version. 
I'm forced to run a local copy of the website from the specific commit id to read the docs.

**Comment by maxkfranz** [comment]
You can checkout a tag for that version and view the docs, or you can upgrade to 2.7.

**Comment by vigneshdv** [comment]
Updating to 2.7 is not an option all development environments.
Wouldn't it make sense to allow people to choose the version of the docs
they want to look at on the website? The latest version can be the default.

And yes currently I've pulled the older docs by using the tags.

**Comment by maxkfranz** [comment]
Projects generally only do that for versions that are still supported (i.e. it receives patches).  Only the latest 2.x is supported, and we don't want to give the wrong impression by publishing out-of-date documentation.

The project follows semver, so you can safely upgrade to 2.7 if you want.  You can alteranatively use an old version if you want, but you won't be able to report bugs and you'll have to checkout the docs yourself.
