### ISSUE TITLE
After changing browser zoom on Firefox, resetting zoom to 100% does not update canvas dimensions

### ISSUE THREAD

**Issue by jspautsch** [cytoscape/cytoscape.js#1725]
Steps to reproduce (seen in Firefox 44 and Chrome 56):

1. Use the browser zoom controls to zoom in a few levels.
2. Now zoom the browser out one level: Note the canvas resizes correctly to fill the available space. You can verify by dragging the canvas around.
3. Zoom back out to 100%*: Note that once 100% is reached, the canvas fails to resize.

*Chrome's behavior was slightly different: Zooming out incrementally would work, but resetting back to 100% would cause the issue.

The problem seems to be in `CRp.matchCanvasSize()` (called from `onResize()`) in these two for loops:

```
  for( var i = 0; i < r.CANVAS_LAYERS; i++ ){

    canvas = data.canvases[ i ];

    if( canvas.width !== canvasWidth || canvas.height !== canvasHeight ){

      canvas.width = canvasWidth;
      canvas.height = canvasHeight;

      canvas.style.width = width + 'px';
      canvas.style.height = height + 'px';
    }
  }

  for( var i = 0; i < r.BUFFER_COUNT; i++ ){

    canvas = data.bufferCanvases[ i ];

    if( canvas.width !== canvasWidth || canvas.height !== canvasHeight ){

      canvas.width = canvasWidth;
      canvas.height = canvasHeight;

      canvas.style.width = width + 'px';
      canvas.style.height = height + 'px';
    }
  }
```

Specifically, these lines:

```
if( canvas.width !== canvasWidth || canvas.height !== canvasHeight ){
```

The problem is that `canvas.width`, for example, does equal `canvasWidth`, but `canvas.style.width` does not match `canvasWidth`, and so needs to be updated (but is skipped).

I'm not terribly familiar with cytoscape's code yet, but perhaps the IF statement needs to check both `canvas.width` and `canvas.style.width`?

**Comment by maxkfranz** [comment]
Can't reproduce on Chrome 56 or Firefox 51

**Comment by jspautsch** [comment]
I tried again and cannot reproduce on Chrome, but was able to reproduce on Firefox 51 with Cytoscape 2.7.15 (Win 7), using this demo page: http://js.cytoscape.org/demos/444dc95703caa319c147/

1. Hit (Ctrl+) to zoom in the browser
2. Hit (Ctrl-) to zoom back out to 100%
3. Try dragging the cytoscape canvas. You'll see the :active marker is not correctly aligned with your mouse position, and dragging the graph to the bottom-right corner shows it gets cut-off early (the graph failed to resize when zooming back to 100%).

![image](https://cloud.githubusercontent.com/assets/1054163/23407788/94089c0c-fd93-11e6-8ac7-65dcc3554b8d.png)

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-30ea9fc3f4-1488572129569.zip

Or if you're using npm+browserify or npm+webpack, temporarily replace `"cytoscape": "x.y.z"` in `package.json` with `"cytoscape": "https://github.com/cytoscape/cytoscape.js.git"` to use the latest code from `master`.

Let me know if it works for you or if you have any issues with it.  

Thanks
