### ISSUE TITLE
Add layout option to include labels in bounding box calculations

### ISSUE THREAD

**Issue by jspautsch** [cytoscape/cytoscape.js#1726]
We've found it very useful to patch cytoscape to disable includeLabels for certain layouts, so they ignore labels when calculating node positions. It would be nice if this could be passed in as a config option for the layout for added flexibility.

I can probably do a PR for this, but wanted to log an issue first.

**Comment by maxkfranz** [comment]
Duplicate of 3.1 issue https://github.com/cytoscape/cytoscape.js/issues/1626

**Comment by jspautsch** [comment]
My bad, I thought I searched for this one. I'll keep an eye on the original ticket.
