### ISSUE TITLE
Allow zooming with mousewheel even when box selection is active

### ISSUE THREAD

**Issue by jspautsch** [cytoscape/cytoscape.js#1727]
Currently, the user cannot use the mousewheel to zoom when not in pan mode. This is generally very frustrating to our users because they prefer to be in box-selection mode, but still need the mousewheel to zoom easily.

We ended up commenting out the check that requires panningEnabled and userPanningEnabled to both be true to enable mousewheel zooming.

An additional initialization option to allow mousewheel zooming even when userPanningEnabled is false would be appreciated.

**Comment by maxkfranz** [comment]
It's inherently not possible to zoom about a point without changing the pan.  If you disable panning, you can't zoom with the wheel.  The semantics of `userPanningEnabled()` can't be changed then.

You'd need some other panning class, e.g. `fooUserPanningEnabled()`, for panning-only user gestures.  The naming and semantics need to be very clear for both dev understandability and avoiding possible conflicts.

**Comment by maxkfranz** [comment]
Generally, you either make the app modal w.r.t. box selection, or you just leave it as it is by default.  Most apps only allow box selection when shift or control is down.
