### ISSUE TITLE
Note font loading in init docs

### ISSUE THREAD

**Issue by HugoSalt** [cytoscape/cytoscape.js#1734]
In the init section of the docs, mention that fonts must be loaded prior to cy load to guarantee custom font usage.

OP follows:

---

I am using CytoscapeJs 2.7.15, I have loaded in the CSS of my html page a custom font as such :

```
  @font-face {
            font-family: 'Source Code Pro';
            font-weight: 400;
            font-style: normal;
            font-stretch: normal;
            src: url('fonts/SourceCodePro-Regular.otf.woff2') format('woff2');
        }
```
I then initialize the graph with this font for my nodes label :

  ```
style: { 
                        ...
                        'label': 'data(id)',            
                        'font-family': 'Source Code Pro',
                        'font-weight': '400',
                        'font-size': '0.5em',
                        ...
                    }
```

And the label gets cropped at a certain zoom level, past this zoom level the label is well displayed.
Here's a [video](http://filebin.ca/3DqvD3vKBHfL/CytoscapeCrop.webm) of the problem, and here are screenshots :

Not cropped when close enough :
![notcropped](https://cloud.githubusercontent.com/assets/25799656/23369441/ad28a72c-fd11-11e6-9324-070ab6c8f84e.png)
Cropped past a certain zoom level :
![cropped](https://cloud.githubusercontent.com/assets/25799656/23369460/b6ce3170-fd11-11e6-8c17-66e0314ceebb.png)

I have tried using .ttf instead of .woff2 format but it doesn't solve the issue.

The issue doesn't appear when I don't specify a custom font

**Comment by HugoSalt** [comment]
Actually this seems to be the same issue as #1692 , but for me it's not linked to whereas the font is set to Bold or not, it's the fact of using this custom font that triggers this issue

**Comment by maxkfranz** [comment]
Just as in the other issue, you need to insure your fonts are loaded before Cytoscape is initialised.

**Comment by HugoSalt** [comment]
Indeed this was the issue thanks a lot ! If there's no plan to implement in Cytoscape the checking that fonts are loaded I guess both issues can be closed. But maybe it would be worth it adding to the doc (for eg in the initialization chapter) a mention that we must wait for fonts to be loaded before initializing ?

For those having the same issue , on Chromium, having an external styleseet as recommended [here](http://stackoverflow.com/questions/4712242/wait-for-fonts-to-load-before-rendering-web-page) does not solve the issue, neither does `document.fonts.ready` or `document.fonts.onloadingdone` the only thing that worked for me is the hack function `waitForWebfonts` described [here](http://stackoverflow.com/questions/5680013/how-to-be-notified-once-a-web-font-has-loaded). It's kinda dirty but it's the only thing that works for me

**Comment by maxkfranz** [comment]
You should probably be using something like this to detect if fonts are loaded (if you're doing things dynamically): 

- https://github.com/typekit/webfontloader
- https://github.com/bramstein/fontfaceobserver
- https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onload

It's not really in the scope of Cytoscape to be checking for fonts.  It's up to the dev to init the lib at the proper time for his app.

As you suggested, a note could be added to the docs to make this case clearer.

**Comment by develar** [comment]
> neither does document.fonts.ready

Indeed. And it doesn't work because it maybe called _before_ CSS file loading will be finished.

Use [document.fonts.load("12px MyFont", "ß").then(…);](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/load) instead.
