### ISSUE TITLE
Selector unable to evaluate against empty string ("")

### ISSUE THREAD

**Issue by dukexor** [cytoscape/cytoscape.js#1735]
var foo = cy.nodes('[bar == ""]') and
var foo = cy.nodes('[bar != ""]') will result in an invalid format error when attempting to select by node.data().bar values.

I am manipulating and formatting our data in a couple languages and use "" as a catchall for database errors, data that is non-existant and the like.

**Comment by maxkfranz** [comment]
If the empty string is the only falsey value it can take on, you can use `[!bar]` for now.

**Comment by dukexor** [comment]
Thanks for the prompt response, Max. I made a kludge, but will update that
tomorrow. Thanks for your continued work on this great software!

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-5e66f326ac-1488569187525.zip

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by dukexor** [comment]
That did the trick, thanks!
