### ISSUE TITLE
Error when using Dagre layout

### ISSUE THREAD

**Issue by bernatfortet** [cytoscape/cytoscape.js#1738]
I get this error when I'm trying to use the dagre layout

`Can not apply layout: No such layout `dagre` found; did you include its JS file? `

```js
import cytoscape from 'cytoscape'
import cydagre from 'cytoscape-dagre'
cydagre( cytoscape )

...
    var cy = cytoscape({
      container: document.getElementById('cy'),
      elements:{ nodes:graph.nodes, edges: graph.edges},
      layout: {
        name: 'dagre',
      },
    })
```

If I use the default layouts works fine.

**Comment by maxkfranz** [comment]
If you have an issue with an extension, please file a bug in that extension's repo.

**Comment by maxkfranz** [comment]
https://github.com/cytoscape/cytoscape.js-dagre/issues/22
