### ISSUE TITLE
The vertices drag the shadows

### ISSUE THREAD

**Issue by Samli514006030** [cytoscape/cytoscape.js#1740]
Hi, I am now using visallo, using the framework is cytoscape.js. Then I found that when the vertex was over 100, the vertices dragged the shadow, and the size of the shadow was the same as the size of the vertex. Color and vertex background color consistent, I do not know where a problem, please advise.

**Comment by maxkfranz** [comment]
Are you a dev or a user for Visallo?  If you're a user, it sounds like you should be filing a bug report in that tool.
