### ISSUE TITLE
Graph not showing until resize event occurs

### ISSUE THREAD

**Issue by dviljoen** [cytoscape/cytoscape.js#1748]
I have my graph inside of a bootstrap tab div,  It is not the default tab.  When I click the tab the graph is blank until I resize the browser window.  How can I make it show automatically?

**Comment by maxkfranz** [comment]
See

http://stackoverflow.com/questions/40307570/a-hidden-cytoscape-graph-cannot-be-displayed-later/40516242#40516242

http://js.cytoscape.org/#cy.resize
