### ISSUE TITLE
Note function style property value best practices

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1749]
- **Do** specify a valid value for the corresponding style property for all elements that its corresponding selector block applies.
- **Do not** create cyclic dependencies (i.e. one style property reads the value of another style property).
- **Do** use pure functions that depend on only
  - `ele.data()`,
  - `ele.scratch()`, or
  - basic state that could alternatively be represented with selectors (e.g. `ele.selected()` is OK because there's a `:selected` selector).
- **Do** use caching, e.g.  with [`_.memoize()`](https://lodash.com/docs#memoize), for expensive property functions.  If the functions are pure, then `_.memoize()` works perfectly.
- **Do not** use functions if you can use built-in mappers and selectors to express the same thing.  If you use a function, you lose built-in style performance enhancements and you'll have to optimise and cache the function yourself.

**Comment by mj3cheun** [comment]
@maxkfranz Do you want this to go under `cy.style()` in the documentation or under `Style` where all the style properties are.
