### ISSUE TITLE
Elements style get reset after being moved to another parent

### ISSUE THREAD

**Issue by royludo** [cytoscape/cytoscape.js#1750]
https://jsfiddle.net/okegvn2d/2/
This fiddle shows the situation very well, with minimal code. Version 2.7.16 of cytoscape.js was used.
This issue is related to #1452 I think.

If you comment line 75 to avoid the move call, you can see that some style was present for node "d" and its edge. When the node is moved to "b", its style gets reset, and the connecting edge too.

The problem must be located here:
https://github.com/cytoscape/cytoscape.js/blob/master/src/collection/index.js#L686
The style probably doesn't get included in the json.

**Comment by maxkfranz** [comment]
If you want style to be persistent, then use the stylesheet.  The docs say that `.move()` makes a new element: http://js.cytoscape.org/#eles.move

You should use `ele.style()` only for very specific edge cases, just as it's bad practice to put everything in the `style` attribute in HTML.

**Comment by royludo** [comment]
@maxkfranz What would you recommand for setting any style property to any value dynamically for any element? Using cy.style().selector('#id').style() ?

**Comment by maxkfranz** [comment]
If your selectors can be broad and the cases are relatively few, then it's best to use the stylesheet and hard-code the styles for each case there.

If the values vary for most (or every) element, it's usually best to use a mapper: http://js.cytoscape.org/#style/mappers
