### ISSUE TITLE
cytoscape not initializing in JavaFX WebView from version 2.7.12 and up

### ISSUE THREAD

**Issue by CarlosZaldivar** [cytoscape/cytoscape.js#1752]
I'm using cytoscape.js in a JavaFX application, inside WebView node. After upgrading cytoscape.js to newer versions I can't get it to work. I'm trying to write:
`var cy = cytoscape({
  container: document.getElementById('cy')
});`
And I get:
`TypeError: undefined is not a function (evaluating 's(e)')`

**Comment by maxkfranz** [comment]
The javafx webview is not an officially supported environment.  Many basic APIs are not supported even in the same version of Webkit.  It's also years behind the latest release of Webkit.  There isn't even a proper built-in debugger.

You could try to work around the limitations of javafx and make a pull request for it if you like.  I don't have time to play around with it.

If you must use Java, you may want to look into [CEF](https://bitbucket.org/chromiumembedded/java-cef) or [JxBrowser](https://www.teamdev.com/jxbrowser) instead.  

If you can, it would be better to build a webapp.  You could expose your Java code as a webservice.  If you really want a native app container it would be better to use [Electron](https://electron.atom.io/), and then you don't need to use Java at all.

**Comment by CarlosZaldivar** [comment]
Ok, I get it. Thanks for pointing me in some other directions. (JxBrowser seems very interesting but it's also tremendously expensive.)
