### ISSUE TITLE
png/jpeg function do not render shadows correctly

### ISSUE THREAD

**Issue by stan-golembivsky** [cytoscape/cytoscape.js#1755]
cytoscapejs 2.7.13
If nodes has shadows (i used built in styles 'shadow-color', 'shadow-offset-x', 'shadow-offset-y', 'shadow-opacity') and on the generated png/jpeg image seems that light source is moved and the shadows are offsetted. Here are the screenshots(especially it can be detected when the graph is zoomed):
![graph1](https://cloud.githubusercontent.com/assets/16240384/24258628/cc470712-1007-11e7-8f8c-c63962d68c78.png)
![graph2](https://cloud.githubusercontent.com/assets/16240384/24258627/cc45fbd8-1007-11e7-828f-6e35624dd3bb.png)

**Comment by maxkfranz** [comment]
Do you have a minimal code example that reproduces the issue?

It works fine when I try it:

Stylesheet:

```js
{
  selector: 'node',
  style: {
    'shadow-blur': 20,
    'shadow-color': 'red',
    'shadow-offset-x': 10,
    'shadow-offset-y': 10,
    'shadow-opacity': 1
  }
}
```

Get image in console:

```js
window.open( cy.png() );
```

**Comment by stan-golembivsky** [comment]
Here is a small code sample

https://codepen.io/stan_golembivsky/pen/LWJVvG

i've found out that if i use some value to scale the image than the bug reproduces:

`var base64 = core.png({
      full: true,
      scale: 0.5
    });`

 and if there is current zoom value instead than everything works fine:

`var base64 = core.png({
      full: true,
      scale: core.zoom()
    });`

i'm using [cytoscape-navigator](https://github.com/cytoscape/cytoscape.js-navigator) extension and can't change this value... so the best solution for me is to write the extension by myself((

**Comment by maxkfranz** [comment]
The canvas doesn't support blurring properly.  It's not possible to use workaround to fix everything.  The original feature was added in a pull request, and I should have been more careful about accepting it.

If having consistent output is important to you, you shouldn't use shadows.

Shadows won't be supported in 3.0.  You can follow the `ghost` style property feature, which is similar, in the following ticket https://github.com/cytoscape/cytoscape.js/issues/1197
