### ISSUE TITLE
Remove `data` parameters in `.on()` etc

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1764]
Listener functions like `.on()` have a `data` parameter in 2.x, e.g. `node.on('tap', { foo: 'bar' }, function(){ /* ... */ })`.  In order to keep events lean and as performant as possible, this feature will not exist in 3.x.

**Comment by maxkfranz** [comment]
Ref 7565b51

**Comment by KonradHoeffner** [comment]
The link that should send the user here from the blog post `http://blog.js.cytoscape.org/2017/04/11/3.0.0-release/#summary-of-changes` sends the user to the non existing URL `http://blog.js.cytoscape.org/2017/04/11/3.0.0-release/(https://github.com/cytoscape/cytoscape.js/issues/1764)` instead (hope this is the right place to report that).

**Comment by maxkfranz** [comment]
@josephst Would you please look into the link issue on your release post?

**Comment by josephst** [comment]
@maxkfranz @KonradHoeffner [fixed now](https://github.com/cytoscape/cytoscape.js-blog/commit/1607768b85fe9ed20800a0802c20d49c741eeb20)
