### ISSUE TITLE
Nodes with background image on top of pie chart?

### ISSUE THREAD

**Issue by dwitvliet** [cytoscape/cytoscape.js#1768]
I'd like to put an image within some nodes on top of their pie charts. Is this possible? 
I do not want to reduce the opacity of the pie charts, since that will change their colors, but I want to lay the image on top. The image is mostly transparent, so I would still be able to see the pie chart behind the image.

**Comment by maxkfranz** [comment]
No, it's not possible.  If you want that kind of customisation, you'll have to generate the pie charts yourself as one of the background images: https://github.com/cytoscape/cytoscape.js/issues/1747
