### ISSUE TITLE
Modifying Container Height After Initialization With Resize()

### ISSUE THREAD

**Issue by pihish** [cytoscape/cytoscape.js#1769]
I have a HTML DOM that looks like:

`<div id="my-element"></div>`

with the corresponding code to initialize Cytoscape:

```
var cy = cytoscape({
    container: $('#my-element'),
    height: 500px
});
```

I would like to change the height of the container element to something other than the original `500px` value when an user commits an action.

After going through the docs, it seems like I should be able to do this with `cy.resize()`.

I have the following bound to a button click action in my code:

```
$('#my-element').css('height', 'calc(100% - 410px)');
cy.resize();
```

But the above doesn't redraw my Cytoscape container with the new height.

What am I missing here?

**Comment by maxkfranz** [comment]
(1) Your redefined style is probably invalid.

(2) You can't define height here; use your stylesheet.

```js
var cy = cytoscape({
    container: $('#my-element'),
    height: 500px // wrong
});
```

**Comment by pihish** [comment]
I am pretty sure the style is valid.  When I look at the canvas elements and also the container element after I call `$('#my-element').css('height', 'calc(100% - 410px)');`, the height is the calculated height I have defined with the code.  

It seems that while the canvas elements are redefined with the appropriate height, the nodes and edges are not resized to fit with this new height.

**Comment by maxkfranz** [comment]
A simple `calc()` works for me: 

```js
document.getElementById('cytoscape').style.height = 'calc(400px + 100px)'
```

I suspect your style is invalid (e.g. percent units don't mean anything unless the parent has properly defined style) or you have problems elsewhere.

**Comment by pihish** [comment]
It had nothing to do with styling.  `cy.resize()` needs to be followed by a call to `cy.fit()`

```
$('#my-element').css('height', 'calc(100% - 410px)');
cy.resize();
cy.fit();
```

**Comment by maxkfranz** [comment]
Cytoscape.js has a viewport.  The viewport has a zoom level and a pan, which correspond to [scale and translation transforms](https://en.wikipedia.org/wiki/Transformation_matrix#Examples_in_2D_computer_graphics).  

Changing the container dimensions just changes the viewport extent; it has no effect on the pan and zoom.  For example, resizing the window for a full-screen graph just extends the viewport (just as it would for a map, like Google Maps).

Your question seemed to concern only the viewport extent.

Does that clarify things?

**Comment by ianhi** [comment]
I also found this slightly confusing. In particular I took this line from the documentation for `resize`([ref](https://js.cytoscape.org/#cy.resize))
> to have the graph resize and redraw itself

to mean that I should expect the pan and zoom to be modified to fit the graph inside the new dimensions when I called this function. This probably stems from my being newish to javascript and not fully understanding the distinction of viewport and pan and zoom you helpfully described. 

@maxkfranz would you be open to adding something like the following to the documentation:
This function will only change the viewport extent, it will not modify the pan and zoom to fit the graph inside the new dimensions. To accomplish that you will need to call `cy.fit()` after this function.

**Comment by maxkfranz** [comment]
If you found this function confusing, then there are probably other people who would also benefit from your proposed change.  I’m not sure exactly what’s misleading about the current wording (e.g. maybe the term “redraw” is problematic), so feel free to make a PR in the MD files to help to clarify this function as you see fit.  Since you’ve experienced the issue, you’d know best.  Thanks for the feedback

Aside: Given the support for `ResizeObserver` (#1652 <https://github.com/cytoscape/cytoscape.js/issues/1652>), I’m not sure there are many use cases for calling this function anymore — at least in modern browsers <https://caniuse.com/#search=ResizeObserver>.  So perhaps there should be a warning that most people generally shouldn’t use this function.  Alternatively, the last paragraph could be removed.

**Comment by ianhi** [comment]
I think you're correct that redraw is what confused me. 

> so feel free to make a PR in the MD

:+1: 

I ran into this in context of the cytoscapejs jupyter widget. See: https://github.com/QuantStack/ipycytoscape/pull/91 for gifs and code changes. Though perhaps I only needed to call `fit` and didn't need `resize` given what you are saying about `ResizeObserver` I will look into that

**Comment by ianhi** [comment]
For the widget I do seem to still need to call `resize`. I'm not exactly sure how resizing widgets works in jupyterlab so I'm not sure if this is something that `ResizeObserver` should have picked up. I'm using Firefox 75 on linux

**Comment by maxkfranz** [comment]
It looks like there may be more edge cases that the browsers don’t yet support automatically.  The resize function shouldn’t be undocumented just yet, so it would be good to improve its clarity in the meanwhile.

Thanks
