### ISSUE TITLE
put source nodes in left column and target in right column layout 

### ISSUE THREAD

**Issue by behrouzsh** [cytoscape/cytoscape.js#1770]
Hi there,
I have seen a layout that arrange nodes in two columns, for example source in left (with text on the left hand side) and target nodes on the right (with text on RHS). I am pretty sure that this is not one of the pre-implemented layouts in cytoscape.js. So any guidance that points me in the right direction (how to find this layout or how to implement this) is appreciated.

**Comment by maxkfranz** [comment]
That sounds like just a particular case of the grid layout: two columns with custom node placement
