### ISSUE TITLE
[Feature Request] separate the graph visualization tool from the graph algorithms library

### ISSUE THREAD

**Issue by avrahamcool** [cytoscape/cytoscape.js#1772]
Is there any way to use the graph algorithms independently from the graph visualization library?
It can be very helpful for applications that don't need the visualization but only need the powerful graph algorithms.

**Comment by maxkfranz** [comment]
That's not really necessary, since you can run a Cytoscape instance headlessly.  

Rendering is optional and it's implemented by a prepackaged extension.  It's just included in the  build for convenience.
