### ISSUE TITLE
Fire a `dragover` event when a node is dragged over another node

### ISSUE THREAD

**Issue by disovi** [cytoscape/cytoscape.js#1773]
**Description of new feature**

Fire a `dragover` event when a node is dragged over another node.  Fire `dragout` when dragging a node off of the other node.

**Motivation for new feature**

A graph editor app may want to use events like this for grouping nodes (e.g. creating compound nodes).  Another usecase is the hover effect, described in the OP.

OP follows:

---

Hello, I want to be able to add hover effect when dragging one element over another.
I've tried two ways, but none has worked for me. I've studied the source code and want to fix it.
I've tried the following approaches:
1. Subscribe to 'mouseover' or 'tapdragover' event. But this events are not being triggered because of the line   [load-listeners.js#L572](https://github.com/cytoscape/cytoscape.js/blob/84b450533e40d2eae9de32608bc22db084da7cc8/src/extensions/renderer/base/load-listeners.js#L572)
2. Subscribe to drag event and use cy.renderer().findNearestElements() to find needed elements. But the problem is in [coord-ele-math.js#L244](https://github.com/cytoscape/cytoscape.js/blob/05d0c1664df640e4171ea2719bb82141cf3c3486/src/extensions/renderer/base/coord-ele-math.js#L244) it returns only one node, so when I drag node - it returns its own element.

Available solutions:

1.  add a parameter to findNearestElements indicating that we need all elements or always return all elements (I can't see the reason why it should return only one node or edge).
2. make dragover event trigger even when node is grabbed (the subscriber can manualy filter such events)
3. add new event (?)
Personally I like 1 and 2 solutions to work together.
If you give me some feedback - I'll create a pull request fixing this issue.

**Comment by maxkfranz** [comment]
Take a look at `BRp.findNearestElements()` in the `unstable` branch.  Anything new should be based on `unstable.`

It doesn't make sense for additional events to happen on drag, as you're already over an element.

Basically, some core function that calls `findNearestElements( x, y, false, 0 )`.  You'd have to add the ability for `isTouch` to be `isTouchOrThreshold` -- accepting a number that overrides the default threshold.  I'm against supporting any other args than `x` and `y` in the core function.

**Comment by volk-s** [comment]
also need the option to drag a node and trigger an event ( to drag it above another node and create a compound). Can't think of another solution - input welcome!
@disovi did you find a solution to trigger such an event?

**Comment by disovi** [comment]
@volk-s i've finished with such workaround. Don't have time for contributing now:(
```javascript
_distanceTo(pos1, pos2) {
  return Math.sqrt(((pos1.x - pos2.x) ** 2) + ((pos1.y - pos2.y) ** 2));
}

_getGraphIntersectionFix(e) {
  let nodes = [];
  if (this.cy) {
    const pos = e.cyTarget.position();
    nodes = this.cy.nodes();
    nodes = nodes.filter((i, el) => el !== e.cyTarget &&
        !el.edgesWith(e.cyTarget).length &&
        this._distanceTo(pos, el.position()) <= 20);
  }
  return nodes;
}
```
```javascript
this.cy.on('drag', 'node', _.throttle((e) => {
  const els = this._getGraphIntersectionFix(e);
  ...
}), 100);```
