### ISSUE TITLE
element.isEdge() return not a function

### ISSUE THREAD

**Issue by marieBvr** [cytoscape/cytoscape.js#1774]
Hello,
I'm using the last version of Cytoscape.js (Apr 11, 2017).
My code was working very well since this last commit (two days ago).
```
cy.filter(function(i, element){
        if( element.isEdge() && element.data("type") === 'ACTIVATION' ){             
            element.addClass('class-activation');
        }
 });
```
With the last commit, my code return an error : TypeError: element.isEdge is not a function.
Is there modification of the use of the isEdge() function ?

Thanks,
Marie

**Comment by maxkfranz** [comment]
If you want to use old 2.7 APIs, you'll have to stick with 2.7

See 

- http://blog.js.cytoscape.org/2017/04/11/3.0.0-release/
- https://github.com/cytoscape/cytoscape.js/issues/1092
