### ISSUE TITLE
Issues related to compound paddings

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1783]
Hi,
For setting compound paddings I use the following code segment in my stylesheet

```
          .selector("node:parent")
          .css({
            'padding': function() {
              return getCompoundPaddings(); // Returns the padding value for the compounds
            }
          })
```

Here ```getCompoundPaddings()``` returns the padding value for compounds. And its return value changes sometimes. However, when its return value changes the change is not percieved by the user (It is reflected to screen properly when the compound nodes are dragged). I suppose that it works in this way because of the performance related issues in Cytoscape.js. 

However, in the past I am used to call ```cy.style().update()``` when I really need to reflect such changes to the screen (e.g. when the user sets a new value for paddings through the interface that is provided by the application in this case) without any user interaction to the cy elements (such as node drag). It may not be an ideal usage but I need it in such cases.

With cytoscape.js latest version it works fine if I call ```cy.style().update()``` when padding value is changed by the user explicitly. However, it does not work with latest Cytoscape.js code in unstable branch. 

What shall I do to percieve the updated paddings when the user set them explicitly through my application interface?

Also, in earlier versions of cytoscape I was able to set padding for 4 sides of the nodes seperately e.g. ```padding-left``` (I am not sure if it was an exposed functionality but it was working fine for me). I think that it is not working in cytoscape.js v3 and as far as I see just ```padding``` is exposed in the documentation. Is there a way to set different values to set different amount of padding for different sides of the nodes in v3?

Thanks,
Metin

**Comment by maxkfranz** [comment]
It's not possible to have independent paddings.

Your functions should be pure functions, based only on the node state.  Functions like that will always update when the node state updates.

**Comment by ugurdogrusoz** [comment]
@maxkfranz Looks like in our case, the style of nodes are sometimes defined via functions, and what the function returns actually changes programmatically; thus the state of the node changes indirectly but Cytsocape.js has no way of knowing this. 
So isn't there a way to force re-rendering of nodes even though their state didn't explicitly change?

**Comment by maxkfranz** [comment]
Your programmatic changes should alter the node state in order to affect rendering.  If your functions aren't pure, you need to remove all references to global state from them.  If you want to change values often, you should be using a direct mapper `foo: data(bar)` and calling `node.data('bar', newVal)`.  Functions are for things like creating logarithmic mappings --- not for referencing global state.

**Comment by metincansiper** [comment]
@maxkfranz I am not sure if the problem is just related to altering the node state. I think so because if I change the selector as the following I see that the paddings of simple nodes are updated on the screen but the paddings of compounds are not updated (as in the previous case they are updated when we drag them). 
```
        .selector("node")
          .css({
            'padding': function() {
              return getCompoundPaddings(); // Returns the padding value for the compounds
            }
          })
```

Also, I tried to alter the node state as you described. I added the following to my stylesheet

```
{
      selector: 'node',
      css: {
		'padding': function(ele) {
			return ele.data('padding') || 5;
		}
      }
}
```
When I call ```cy.nodes().data('padding', newPadding)``` I see that the paddings of simple nodes are updated on the screen but the paddings of the compounds are not updated again.

Therefore, I think that there may be a problem related to the compounds.

**Comment by metincansiper** [comment]
I created another issue which seems similar to this one (https://github.com/cytoscape/cytoscape.js/issues/1836)

**Comment by jsphstls** [comment]
> It's not possible to have independent paddings.

I stumbled upon a workaround by using `bounds-expansion` on the child nodes within a compound node. Setting the expansion in one direction will cause the boundary of the parent to also expand in that direction.
