### ISSUE TITLE
Link to CDNJS in the docs

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1795]
Link out to CDNJS in the docs for people who are interested in using a CDN.  People should not be using JS files referenced from Github pages (i.e. copied from the demos).

- [x] Mention CDNJS in the "Compatible with" line
  - [x] On the docs
  - [x] On the Github repo page
- [x] Link to CDNJS in the docs in the same area as npm install instructions in "Getting started"
- [x] Also mention not to use the Github URLs from the demos

**Comment by kumarmj** [comment]
Hi, I am interested, please assign me this issue. I might not be able to change
 > On the Github repo page
