### ISSUE TITLE
`width: label; height: label;` nodes added after initialization are not interactive

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js#1796]
When I initialize without any elements:
```
var cy = cytoscape({
  container: ...,
  elements: [],
  style: ...
})
```

and add elements afterwards:
```
cy.add(...)
```

The added nodes are *not* draggable. The entire canvas moves.
This seems to be a bug.

A related issue occurs when *some* nodes are set while initialization and some are added afterwards. The nodes added afterwards are *not* dragable, but the initially set nodes are. And: as soon as an initially set node is dragged the nodes added afterwards are draggable as well then!

Observed in Cytoscape 3.0

**Comment by kumarmj** [comment]
I don't get that bug checkout here https://jsfiddle.net/owsmmj/ra9jcch9/

**Comment by jri** [comment]
Yes, you're right! Your fiddle works.
Sorry for not isolating the problem properly.

The problem occurs if in the node style `width` or `height` (or both) are set to `label`. With a number, e.g. `50` it works, with `label` it doesn't work.
You can check it in my updated fiddle: https://jsfiddle.net/ra9jcch9/4/

Thank you for testing and replying!

**Comment by maxkfranz** [comment]
Try the snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-c0ac08b4f5-1493053549208.zip

Or if you're using npm, temporarily replace `"cytoscape": "x.y.z"` in `package.json` with `"cytoscape": "https://github.com/cytoscape/cytoscape.js.git"` to use the latest code from `master`.

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by jri** [comment]
Now it works!
Great :-)
Thank you very much for the quick fix!
