### ISSUE TITLE
Non-uniform compound paddings 

### ISSUE THREAD

**Issue by ugurdogrusoz** [cytoscape/cytoscape.js#1809]
Certain applications need to make use of compound paddings for labels or other types of annotation, allocating "extra" paddings. Hence without the ability to set the paddings for 4 sides independently, they have to "waste" space on certain (left and right) sides as in this case:

![image](https://cloud.githubusercontent.com/assets/3874988/25693943/ae7c4ac6-30b4-11e7-9c46-489780371d6f.png)

**Comment by maxkfranz** [comment]
Unfortunately, that's not something that's possible to support.  It breaks several other major features.
