### ISSUE TITLE
cubicBezier easing needs to solve back for time

### ISSUE THREAD

**Issue by josephst** [cytoscape/cytoscape.js#1811]
The various default easings in `animation.js`, such as ease, ease-in, ease-out, etc. all call `cubicBezier` with four arguments describing the (x,y) coordinates of two points, but the cubicBezier function only uses the first point and discards the second point, since it only accepts 2 parameters (rather than four).

The code in question (line 384):
```
    function cubicBezier( p1, p2 ){
      return function( start, end, percent ){
        return start + (end - start) * evalCubicBezier( p1, p2, percent );
      };
    }
```

This ignores some of the parameters passed to cubicBezier, which are similar to `'ease': cubicBezier( 0.25, 0.1, 0.25, 1 )`

**Comment by maxkfranz** [comment]
It should be solving back for time in order to take all of (t1, p1, t2, p2) into account.  It looks like only (p1, p2) were intended but that ignores (t1, t2) which can significantly alter the effect of the easing.

It should be working now.  Let me know if it's OK for you now.  Thanks

**Comment by josephst** [comment]
Yes, new changes have gotten everything working now. Just compared with the previous build and (1,0,0,0) now looks distinctly different than (1,0,1,1) whereas these options previously were producing identical animations.
