### ISSUE TITLE
Any Vue.js based example?

### ISSUE THREAD

**Issue by vision8tech** [cytoscape/cytoscape.js#1821]
Hello,

Does anybody has an example of how to use `Cytoscape.js` in a `Vue.js` based application?
Any starter, boilerplate or sample would help.

Thank you!

**Comment by maxkfranz** [comment]
Take a look at https://github.com/cytoscape/cytoscape.js/issues/1468

The approach would be similar.

**Comment by vision8tech** [comment]
Thanks, Max! 👍 
I'll take a look into it.

**Comment by wydewy** [comment]
import cytoscape from  'cytoscape' in a component

**Comment by andres-k** [comment]
@vision8tech  Did you work something out? If so, could you share an example, please

**Comment by hannesN** [comment]
@vision8tech I'd like to see that too.
