### ISSUE TITLE
.addClass() does not working for compounds

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1835]
If you add the following to your stylesheet
```
{
      selector: 'node.red',
      css: {
		'background-color': 'red'
      }
}
```
and call ```cy.nodes().addClass('red')``` then just the simple nodes become red. 

Also I realized that the result of ```cy.nodes(':parent')[0]._private.classes```does not contain 'red' key after this operation is performed.

**Comment by maxkfranz** [comment]
I just tried this on the debug page, and it works as expected for noncompound nodes and compound nodes.

```
.foo { background-color: red; }
```

```js
cy.nodes().addClass('foo');
```

**Comment by maxkfranz** [comment]
There must be another factor, one not in your pasted code, causing your issue.

**Comment by metincansiper** [comment]
Yes, actually I was not getting this error from our application but getting it from a demo where I tried something and I thought that it is a bug appearing in the latest version of Cytoscape.js. However, then I realized that in that demo file the style is overridden for the parent nodes. Sorry, I am closing the issue.
