### ISSUE TITLE
Bezier Curve Control Points.

### ISSUE THREAD

**Issue by askari12** [cytoscape/cytoscape.js#1841]
I am trying to find the Control points for nodes but it becomes very hard when two nodes are at an angle to each other and not in a straight line.

I was trying to find the Control point if the nodes were vertical and then rotate them to the desired angle but that takes a lot of computational time.

Is there a faster way by getting the Control Points directly ?

**Comment by maxkfranz** [comment]
No, there isn't a way of getting model points from a relative control point spec.  There is a planned API for 3.2 : https://github.com/cytoscape/cytoscape.js/issues/1552

**Comment by askari12** [comment]
I have worked on an algorithm to find the control points for unbundled Bezier edges. With a little change , I think it can be used for other curves as well. It uses coordinate geometry and reflection.

**Comment by maxkfranz** [comment]
The absolute points already exist in the internal model.  #1552 is just about making a public API around that existing data.

**Comment by askari12** [comment]
As in a get a method ?

**Comment by askari12** [comment]
Or do they exist somewhere that I can somehow access and use ?

**Comment by maxkfranz** [comment]
Yes, it would need a getter per type.  You can't get that information without #1552.  Take a look at the updated #1552 text and see if any other functions would be needed by your svg exporter project.

**Comment by askari12** [comment]
I would also like to have the points of the start and the end of an edge at the edge of a node. Also the control points for an edge of a node to the same node. I guess that is also covered in the bezier curve edges. Other edges are also covered in #1552 as far as I can see, right ? Thanks!

**Comment by maxkfranz** [comment]
It sounds like everything is already covered in #1552 then.

**Comment by maxkfranz** [comment]
Closing; follow #1552
