### ISSUE TITLE
Pan by Model Coordinates

### ISSUE THREAD

**Issue by Insulince** [cytoscape/cytoscape.js#1850]
Hello, I have been working on a cytoscape project which requires some sort of panning limit on both x and y. I have tried searching for solutions to this and only found this issue: https://github.com/cytoscape/cytoscape.js/issues/1329, which explains why panning limits are largely not possible due to pan using rendered coordinates, however, there is cy.extent() for getting model coordinates as well, just no way to set them.

Upon reading http://js.cytoscape.org/#layouts/random, I found that the options for this layout (and a few others) include the boundingBox section, which accepts an object that looks like {x1, y1, x2, y2}, or {x1, y1, w, h}. This style of setting up model coordinates is exactly what I would need to implement my panning limits. Something along this lines of:
```javascript
cy.extent({
    x1: 0, //Set x1
    y1: 0, //Set y1
    w: cy.extent().w, //Keep the current w
    h: cy.extent().h //Keep the current h
});
```

Currently I manage pan limits using the solution outlined in the aforementioned issue, however, it is kind of a mess in my project and this would make things much easier.

Is this something that's beyond reason? It would be immensely helpful, and I don't think only for my use case.

**Comment by maxkfranz** [comment]
I don't think we can have `cy.extent()` as a setter.  The dev can set many combinations of invalid values, for example.

But the bigger problem is that setting pan limits is not so straightforward as setting a zoom limit, as explained in #1329.  There are too many possible variations and no good, universal default.  

Some examples: Do you allow a user gesture and then animate back to an allowed viewport state?  Do you block gestures midway if they would break the constraint?  How does the UI give feedback for midway-blocked gestures (e.g. it's confusing if you can't zoom in on a node when it's at the boundary of the constraint)?  How do you visualise the constraint?  How do you access animation objects if they were used for the constraint?

I think these are questions better addressed by apps themselves.   If you implement a particular variation of viewport constraint enforcement and want to make a reusable module, feel free to put it in an extension: http://js.cytoscape.org/#extensions

**Comment by Insulince** [comment]
Thank you @maxkfranz, and I do hear you, however, a lot of those don't have to be deal-breaking issues. If a dev enters invalid combinations, simply reject them and/or throw an exception. One way of ensuring valid values would be to only allow setting of x1 and y1, and assume the same w and h (extent zoom cannot be set) then calculate x2 and y2. As for the constraint issues, these are things that I would agree should be left up to the developer to implement. A method of hard pan-limiting is not something I am suggesting here, just a way to set the current view using model coordinates instead of rendered ones. With a tool like that, developers could create their own pan limits by checking the extent, and when it is beyond a predetermined bound, re-setting the extent to the bound limit. The consequences on the rest of the graph are something for the developer to work on themselves.

**Comment by maxkfranz** [comment]
If you're looking for a just a setter for the current state, then that makes more sense.  I'm not entirely sold on the utility of setting via the `.extent()` function in particular though.  That function would accept a bounding box to be consistent, and a dev probably won't bother forming one unless it's from `eles.boundingBox()` --- in which case, you could just `eles.fit()`.

I think the following makes sense:

- `cy.panTo( modelPosition )` -- this is all your example would be doing anyway (i.e. zoom is unchanged)
- `cy.viewport({ panTo: {x,y}, zoom: z })` -- like existing function but uses model `panTo`
- `cy.extent( bb )` -- just converts the bb to a `.viewport()` call

There are issues to work out with `cy.extent()`.  For instance, what if you set conflicting `{ x1, x2, w }`?  Do you respect `{ x1, x2 }`, `{ x1, w }`, or `{ x2, w }`?  

Only respecting `{ x1 }` doesn't give any utility over `cy.viewport()` or `cy.pan()`.  That may be OK for your usecase, but it's probably not general enough for the lib.

`cy.extent()` should probably only support exactly two values specified per dimension (unless the third value is redundant/non-conflicting, e.g. `eles.boundingBox()`).  Otherwise, it should do nothing at all and bail out with an error message.

**Comment by Insulince** [comment]
I agree with you on most everything.

I think it would be wise to throw the whole operation away if the user passes any invalid values, or perhaps allow for a callback when that occurs as a way to recover.

A cy.panTo that accepts x1 and y1 would be absolutely terrific, and in my opinion, a dire need for the library. As a user, I have found myself falling off the edge of the graph with trouble finding my way back (for example, zooming very far out is basically a death sentence). I suppose using animations or cy.center/fit in combination with a zoom limit would be a solution, but I think a predefined way to set the pan via model coordinates could be used to make the user stay within a certain region with a more intuitive feel as well as make the dev's development process easier.

**Comment by maxkfranz** [comment]
OK, that makes sense.  Do you want to make a PR for the three viewport setters we discussed?  That way you can see if the setters are enough to build your dynamic viewport restrictions feature.  If they aren't enough, then we can re-evaluate what changes would be needed in the API.

**Comment by Insulince** [comment]
I am not quite sure what you mean, please forgive me, I am very new to the world of strictly regulated git (I'm used to working by myself exclusively on master), and it is my understanding that I would have to branch off of master, add some functionality for this, and submit a pull request to have it merged with the unstable branch. I intended this issue more as a feature request. Am I backward in my thinking here? If so, please tell me what you would need me to do.

**Comment by maxkfranz** [comment]
If you fork the repo, you can make any number of changes directly on the unstable branch to make a pull request.  It's not strictly necessary to make a new feature branch.

There's more information in an upcoming blog post: https://github.com/cytoscape/cytoscape.js-blog/blob/5a5769994e250953247926207f5a5309cc60bc74/_posts/2016-05-24-getting-started.md

**Comment by carlgieringer** [comment]
Was this every completed? I can't find panTo method or a panTo field in cy.viewport.

**Comment by carlgieringer** [comment]
This is what I'm using to pan to model coordinates. It's not ideal because it doesn't originate from the starting position, but it works:

```
      const extent = cy.extent();
      const x = modelPosition.x - extent.w / 2;
      const y = modelPosition.y - extent.h / 2;
      const zoom = cy.zoom();
      cy.pan({ x: 0, y: 0 });
      cy.animate({ panBy: { x: -x * zoom, y: -y * zoom } });
```

Shouldn't there be an easier way?

**Comment by maxkfranz** [comment]
Most usecases use `fit()` or `centre()`.

The usecase of limiting pan (i.e. restrict panning so that the graph doesn't go completely off screen) is straightforward to do with the graph's rendered bounding box and the existing pan functions.
