### ISSUE TITLE
Object doesn't support property or method 'bind'

### ISSUE THREAD

**Issue by mohan1304** [cytoscape/cytoscape.js#1854]
Application is throwing below error while index.html is loading cytoscape.min.js in IE11 and the page going blank. 

Cytoscape version : 2.7.10

SCRIPT438: Object doesn't support property or method 'bind'
File: cytoscape.min.js, Line: 63, Column: 12116

![image](https://user-images.githubusercontent.com/24724492/26844545-c47a7038-4ac1-11e7-8976-254911851719.png)

**Comment by maxkfranz** [comment]
We can't look into bugs if you're not using the latest version.  Only some bug fixes get backported from 3.x to 2.x, and 2.7.19 is the newest version of 2.x --- not 2.7.10.

Secondly, the lib is generally working in IE11.  You can open the demos on [the docs](http://js.cytoscape.org) to validate that.  So either you're reproducing a bug through specific use of the Cytoscape API or you're causing the bug only through your own code.  In either case, you need to provide a reproducible, minimal test case (e.g. a jsbin).

**Comment by maxkfranz** [comment]
This issue will be re-opened if a reproducible test case is posted.
