### ISSUE TITLE
Document svg image considerations

### ISSUE THREAD

**Issue by d2fong** [cytoscape/cytoscape.js#1856]
- viewbox in firefox doesn't work 
- required non-percent width and height attributes for svg 
- svg doesn't work consistently in ie 
- browser quirks, bugs in browsers since creation, new bugs discovered all the time
- include ```<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg>``` in each svg image
- use `encodeURIComponent` and utf8 for filecontents  
e.g 
```js
let data = 'data:image/svg+xml;utf8,' + encodeURIComponent(svgFile);
```

**Comment by maxkfranz** [comment]
@josephst These are some items that may be good to include in your future SVG tutorial.
