### ISSUE TITLE
After removing style with 'display: none', node is not clickable in 3.1

### ISSUE THREAD

**Issue by jamelt** [cytoscape/cytoscape.js#1859]
I just discovered this bug in Cytoscape.js 3.1. It appears that if you have a simple graph and you decide to apply a class to a node to hide it and remove the class to unhide it, the node becomes unclickable.

Here are the fiddles to demonstrate the behavior. As you can see, the code works fine in Cytoscape 2.7. You can see the tap events being output in the console if you open your developer tools.

Cytoscape 3.1 JS Fiddle
https://jsfiddle.net/udpngu7y/3/

Cytoscape 2.7 JS Fiddle
https://jsfiddle.net/g30n5nom/2/

**Comment by maxkfranz** [comment]
@jamelt Does the code on master work for you when you build it?

Let me know if it works for you or if you have any issues with it.  

Thanks

**Comment by jamelt** [comment]
@maxkfranz I just checked it out and everything is working fine. Thanks for the fix, I wouldn't have known where to begin to fix that issue.

**Comment by maxkfranz** [comment]
Great; thanks for letting me know
