### ISSUE TITLE
```min-height-bias-top``` and ```min-height-bias-bottom``` are working reversely

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#1861]
```min-height-bias-top``` is working as```min-height-bias-bottom``` is supposed to work, while ```min-height-bias-bottom``` is working as ```min-height-bias-top``` is supposed to work.

**Comment by maxkfranz** [comment]
@d2fong Could you take a look at your w/h bias feature here.  I'm pretty sure it was working when we released it, so maybe it's just a docs clarity issue?

**Comment by d2fong** [comment]
Okay I will look into it

**Comment by d2fong** [comment]
@metincansiper it should be fixed now can you confirm it and see that it works?

**Comment by metincansiper** [comment]
@d2fong I think that you made that fix in unstable. Testing it in unstable is not straightforward for me now. Therefore, I applied this change (https://github.com/cytoscape/cytoscape.js/pull/1863/commits/82ee37578cf328bd3a1364c85f4411a50d6e690c) on master branch and it seems to be working as expected with this change.

**Comment by d2fong** [comment]
Okay I can cherry-pick it
