### ISSUE TITLE
Can not apply layout: No such layout `dagre` found; did you include its JS file?

### ISSUE THREAD

**Issue by mdsadique2** [cytoscape/cytoscape.js#1864]
I am using cytoscape for my Angular app.
all the js files are getting loaded properly. I am using version 1.5 of cytoscape-dagre. Still getting the error as **"Can not apply layout: No such layout `dagre` found; did you include its JS file?"**

The code is as below:

`var cytoscapeFilePath = v('app/modulus/assets/js/plugins/cytoscape-3.1.1.min.js');
var dagreFilePath = v('app/modulus/assets/js/plugins/dagre-layout.min.js');
var cytoDagreFilePath = v('app/modulus/assets/js/plugins/cytoscape-dagre.js');
define(['app', cytoscapeFilePath, dagreFilePath, cytoDagreFilePath ], function (app, cytoscape, dagre) {
	app.register.service('cytoScapeService',function(){
		var ctScape={};

		require(cytoDagreFilePath);
		console.log(cytoscape);
		console.log(dagre);
		setTimeout(function(){
		 var cy = cytoscape({
			  container: document.getElementById('cy'),
			  elements: {
			    nodes: [{
			      data: {
			        id: 'DS001',
			        title: 'root',
			        desc:"hello"
			      },
			    }, {
			      data: {
			        id: 'DS002',
			        title: 'l1 - 1'
			      }
			    }, {
			      data: {
			        id: 'DS003',
			        title: 'l1 - 2'
			      }
			    }, {
			      data: {
			        id: 'DS004',
			        title: 'l1 - 3'
			      }
			    }, {
			      data: {
			        id: 'DS007',
			        title: '[CAL005]國家列表'
			      }
			    }, {
			      data: {
			        id: 'DS008',
			        title: '[CAL001] '
			      }
			    }, {
			      data: {
			        id: 'DS009',
			        title: '[CAL001] '
			      }
			    }],
			    edges: [{
			      data: {
			        id: '1',
			        source: 'DS001',
			        target: 'DS002'
			      }
			    }, {
			      data: {
			        id: '2',
			        source: 'DS001',
			        target: 'DS003'
			      }
			    }, {
			      data: {
			        id: '3',
			        source: 'DS001',
			        target: 'DS004'
			      }
			    }, {
			      data: {
			        id: '4',
			        source: 'DS002',
			        target: 'DS005'
			      }
			    }
			    }]
			  },
			  layout: {
			    name: 'dagre'
			  },
			  style: [{
			    selector: 'node',
			    style: {
			      'label': 'data(title)',
			      'width': '100%',
			      'font-size': '7px',
			      'text-valign': 'center',
			      'shape': 'rectangle',
			      'background-color': 'rgba(113,158,252,1)'
			    }
			  }, {
			    selector: 'edge',
			    style: {
			      'width': 2,
			      'line-color': '#ccc',
			      'target-arrow-color': '#ccc',
			      'target-arrow-shape': 'triangle'
			    }
			  }]
			});

			cy.on('click', 'node', function(evt){
			  var node = evt.target;
			  console.log(node.id());
			  var j = cy.$('#'+node.id());
			  console.log(j.data());
			});
		},2000);

		return ctScape;
	});
});
`

**Comment by jasonhornsby** [comment]
You still have to register the add on with cytoscape if you use require().
`cydagre( cytoscape );`
