### ISSUE TITLE
Webfonts do not work in SVG background images

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js#1867]
I want render a font-awesome character in a SVG text element:
```
<text x="0" y="20" style="font-family: FontAwesome" fill="blue">&#xf007;FA</text>
```
A "user" icon is supposed to appear, followed by "FA". The user icon does not appear:

![screen shot 2017-06-22 at 4 24 27](https://user-images.githubusercontent.com/120337/27414646-f03f199c-5702-11e7-9275-e5c34ff8ba16.png)

The SVG is rendered dynamically by the means of a `background-image` function.

See the fiddle:
https://jsfiddle.net/jri_/b23Lg89f/

**Comment by jri** [comment]
A modified fiddle shows that Webfonts in HTML embedded SVG do work. But not in Cytoscape.
https://jsfiddle.net/jri_/b23Lg89f/1/

**Comment by maxkfranz** [comment]
See
https://stackoverflow.com/questions/5495952/draw-svg-on-html5-canvas-with-support-for-font-element#5505861

**Comment by jri** [comment]
> See
https://stackoverflow.com/questions/5495952/draw-svg-on-html5-canvas-with-support-for-font-element#5505861

Sorry, I don't understand what part of it relates to my question.
Can you explain?

Are you saying that fonts are not supported in Cytoscape's Canvas SVG rendering?
I would not acknowledge that.
In a Cytoscape `background-image` function I can do e.g. `<text style="font-family: Arial">` or `Verdana` or `Monaco` or `Trebuchet MS`. These fonts render properly. But `FontAwesome` does not, despite it is loaded.

**Comment by jri** [comment]
> See
https://stackoverflow.com/questions/5495952/draw-svg-on-html5-canvas-with-support-for-font-element#5505861

This posting mentions canvg (https://github.com/canvg/canvg).

Does Cytoscape utilizes canvg for SVG-to-Canvas rendering?

canvg *does* support `<text font-family="FontAwesome">`.
FontAwesome icons are properly rendered:
https://jsfiddle.net/jri_/6r2jug6o/448/

(Probably you need to clear the browser cache)

**Comment by maxkfranz** [comment]
The issue in the s/o question is that the image causes tainting.  Cytoscape doesn't directly draw like a generic canvas lib would, and so tainting can cause issues with external resources.  I suspect this is the issue, but it's hard to say.

**Comment by jri** [comment]
I'm not so much interested in the Cytoscape internals. I just have a simple need: render a FontAwesome icon on a node, and set its color programmatically. Is this possible with Cytoscape?

canvg shows us that a SVG `<text font-family="FontAwesome">` CAN be rendered on a canvas. So, in principle it should be possible with Cytoscape as well.

**Comment by jri** [comment]
In the Cytoscape docs on Core Initialization I stumbled upon this one:

> Note that in order to guarantee custom font usage, the fonts in question must be loaded before Cytoscape is initialised.

I thought this might the problem and did further tests. But no success.

This fiddle definitely loads the FontAwesome font *before* it initializes Cytoscape. Cytoscape initialization is not done before you press the "Init" button. At this time some divs and a `<svg>` using the font are rendered already. Also in the browsers Network panel you can see that the woff(2) file is loaded already.
https://jsfiddle.net/jri_/b23Lg89f/5/

![screen shot 2017-06-23 at 18 29 48](https://user-images.githubusercontent.com/120337/27491276-018da282-5842-11e7-96a2-90c5fe70461c.png)

In order to exclude one other possible problem -- cross-origin requests -- I run the same demo on my local machine, serving all assets (html, css, woff) from the same server. Still no success.

At the moment I have no idea why Cytoscape can't render the FontAwesome font.

Dear Max,
can you acknowledge that problem?
Do my fiddles demonstrate the problem to you?
Did it possibly already work in an older Cytoscape version? Some issues suggests that:
https://github.com/cytoscape/cytoscape.js/issues/964
https://github.com/cytoscape/cytoscape.js/issues/1322

Do you see any solution?

Greetings,
Jörg

**Comment by jri** [comment]
One more hint to isolate the problem: in node labels FontAwesome works.
```
style: {
  'font-family': 'FontAwesome',
  'label': '\uF007 User'
}
```
https://jsfiddle.net/jri_/fh11wo5k/

![screen shot 2017-06-23 at 19 29 16](https://user-images.githubusercontent.com/120337/27493483-4df095dc-584a-11e7-83d8-cf36f96a5e8a.png)

But in SVG background images FontAwesome does not work.

So, the problem seems to be in the SVG-to-Canvas render code.

**Comment by maxkfranz** [comment]
Though it would be nice to support this, I don't see how we can at the moment.  Though your demo consistently shows the problem, the cause of the issue is still not clear.

You might want to consider using plain svgs, rather than fonts, to programmatically make your overall svg.  Most good icon fonts have the source svg available for download.

**Comment by jri** [comment]
> You might want to consider using plain svgs, rather than fonts, to programmatically make your overall svg. Most good icon fonts have the source svg available for download.

That's a good idea. I'll try that. FontAwesome comes with SVG glyphs as well.
Thank you!

**Comment by ocanty** [comment]
This is a browser security feature at play

See: https://stackoverflow.com/a/42405731

**Comment by jri** [comment]
@ocanty Thank you very much for the link! That is very relevant information.
