### ISSUE TITLE
Edges not clipped to the corner of barrel shape

### ISSUE THREAD

**Issue by kinimesi** [cytoscape/cytoscape.js#1874]
Edges are not clipped to the corner of new barrel shapes from unstable branch. There is a small gap between the end of edge and the corner. See the image below:
![image](https://user-images.githubusercontent.com/7281872/27828984-c8d7261e-60c7-11e7-90d6-a49406e77396.png)

**Comment by maxkfranz** [comment]
@d2fong Would you please take a look at your barrel shape w.r.t. the intersection calculations?

**Comment by maxkfranz** [comment]
@d2fong I notice this on the master branch debug page.

When I set `shape: barrel` in the stylesheet in `debug/init.js`, I get this:

<img width="594" alt="screen shot 2018-03-05 at 12 13 56 pm" src="https://user-images.githubusercontent.com/989043/36989196-023ed85e-206f-11e8-844c-163bd0e7070b.png">

Would you please take a look at this when you get a chance?  I suspect you may be using an old intersection calculation for edges, for an older iteration of the barrel corners.

This should affect all of the SBGN PC apps.

**Comment by d2fong** [comment]
I think the behaviour has always been like this for every iteration of the barrel shape.  I can try to fix it but am currently unsure of how.
