### ISSUE TITLE
`ele.component()`

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1878]
`eles.components()` gives all components of the elements in the calling collection.  It would be nice to have `ele.component()` that gives the component of a node or an edge.

`ele.component()` would have to take into account all the elements in the graph --- i.e. you can't specify a subset of elements to consider.  For those cases, it's better to use `eles.components()`.

**Comment by shabble** [comment]
is this as simple as something like:

```
function (ele) {
    let compEles = new Set(); 
    cy.elements().breadthFirstSearch({ root: ele, visit: (v) => { compEles.add(v) }} );
   return compEles;
}
```

or is there some better algorithm to use?

If it's as simple as above I can try to look at making a PR for it.

**Comment by maxkfranz** [comment]
More or less.  You'd use a new `cy.collection()` and `merge()` for internal functions for performance.  It's basically the existing `ele.components()` function implementation but only using one node as input rather than all nodes.
