### ISSUE TITLE
Paddings not respected by barrel shape

### ISSUE THREAD

**Issue by ugurdogrusoz** [cytoscape/cytoscape.js#1884]
Since the barrel shape's corners are curved and these amounts are a percentage of the node dimensions, we get undesired effects such as child nodes overflowing barrel shaped compounds. For instance:
![compartment-overflow](https://user-images.githubusercontent.com/3874988/27862934-6c3d5f9e-6190-11e7-992a-a5d550f990fd.png)
One solution for this would be to specify these offsets as constants rather than percentages of dimensions (just like rounded rect and cut rectangle shapes).

**Comment by maxkfranz** [comment]
@ugurdogrusoz I think you may have to use a percent padding with this shape if it's a parent.  If I remember correctly from @d2fong, the shape doesn't look like a barrel if you use a fixed / non-relative curve.

**Comment by d2fong** [comment]
I tried fixed constants but I couldn't get it to work.  If you have a working fix please submit a pull request I can review it.

Thanks,
Dylan

**Comment by ugurdogrusoz** [comment]
This is how we fixed them in our tool with @kinimesi: https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/2cd459ee87f26e31743c689c187f80532742ae2b

**Comment by d2fong** [comment]
Okay thanks I'll port it over.

**Comment by maxkfranz** [comment]
@ugurdogrusoz Does https://github.com/cytoscape/cytoscape.js/pull/1896 resolve it?

**Comment by ugurdogrusoz** [comment]
I think so

**Comment by maxkfranz** [comment]
OK, closing

**Comment by maxkfranz** [comment]
That looks correct to me.  I think it's expected that you use some padding if you use a barrel shape.  How else is overlap with the child nodes in the corners supposed to be avoided while respecting the bounding box definition?
