### ISSUE TITLE
pixelRatio without blur?

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js#1885]
Is it possible to reduce the amount of rendered pixels by an integer factor without blurring the result?

**Comment by maxkfranz** [comment]
No, the browser will automatically do filtering if the pixel ratio isn't set to the screen pixel ratio.  The browser decides whether to do this or not; it's out of our control.

If you want crisp output, you need to leave the pixel ratio at the default value.

**Comment by maxkfranz** [comment]
An alternative is to implement an upscaling interpolation algorithm, like hq2x, directly in the lib.
