### ISSUE TITLE
Node Background-Image remains blank until user clicks on canvas

### ISSUE THREAD

**Issue by tumri** [cytoscape/cytoscape.js#1886]
http://i.imgur.com/QOcOtdD.png

When loading a large graph the background images on nodes appear blank, seemingly at random, and later load when the user clicks on the blank "white" part of the canvas but not one of the nodes. Zooming in and out or simulating a click event does not fix the issue. Firefox does not seem to have this issue(or at least does not require a click before as it seems to re-try and renders the blank images on it's own).

This issue seems to be widespread on Chrome. The background image is set to a CDN url, the nodes are all different sizes, and the layout used is cytoscape-ngraph.

Seems similar to...

https://stackoverflow.com/questions/16560397/image-not-drawn-on-canvas-until-user-clicks
https://stackoverflow.com/questions/15652309/canvas-images-do-not-load-until-click-event-i-want-to-load-when-page-loads-h

The common fix suggested seems to be to try a redraw onLoad but I know that cytoscape already has onLoad callbacks to render the image with...

```
      image[i] = this.getCachedImage( url, bgImgCrossOrigin, function(){
        node.rtrigger('background');
      } );
```

I'm a bit lost as to what might be causing this issue.

**Comment by maxkfranz** [comment]
@tumri Do you have a demo that reproduces the issue?

The renderer automatically listens for image `load` and invalidates/redraws the node.  I suspect it's a problem in Chrome itself then, but it would be good to see a demo to confirm.

**Comment by tumri** [comment]
https://www.ventureapp.com/map/boston-tech/ - This consistently produces blank background image nodes as described.

I seem to have found a fix for it though I don't know if it fixes the root of the issue or just covers it up.

Changing that line above to node.rtrigger('style'); from node.rtrigger('background') seems to cause the node to properly redraw.

**Comment by maxkfranz** [comment]
It works for me, so maybe it would be worthwhile to put together a minimal demo that reproduces your issue.  There are too many things going on in the app to determine what the issue could be.

**Comment by tumri** [comment]
Did you have Chrome inspector open or have cache turned off? I notice that also somehow hides the issue.

Most of the images load fine but when you zoom in you should be able to see a few that are blank until click like this.

http://i.imgur.com/JDXaFu1.png

**Comment by maxkfranz** [comment]
No, they all load for me.  It's just slow.
