### ISSUE TITLE
It does not work at all to set the shape of parent nodes .

### ISSUE THREAD

**Issue by qtttttttttting** [cytoscape/cytoscape.js#1891]
## **I'm submitting a:**
- [x] Bug report

It does not work at all to set the shape of parent nodes .
--------------------

### Environment info
- [x] Browser and version: chrome 59.0.3071.115
- [x] Node version (if running headless): v6.10.2
- [x] Cytoscape.js version: v3.1.2

### Current behavior

The code goes in the way:
  {
              selector: ':parent',
              style: {
                'shape':'ellipse',
                'background-image': TMP,
                'background-color':'#f6f6f5',
                'border-width': 0,
                'content': ''
              }
 }
I want to change the shape of all the parent nodes, but whatever I set the shape property ,it remains rectangle .

### Desired behavior

I want the shape of all the parent nodes to be ellipse.
### Minimum steps to reproduce

--------------------

Eager for answers! Thank you ~

**Comment by maxkfranz** [comment]
You can only use rectangle shapes, because a parent's dimensions are defined by the bounding box of the children.  `rectangle`, `roundrectangle`, and `cutrectangle` work.

**Comment by qtttttttttting** [comment]
Do you have any suggestions if I have to satisfy this need?

**Comment by maxkfranz** [comment]
Cytoscape.js supports only rect-like shapes for compounds.  Either use regular nodes if you want a true ellipse, or use a roundrectangle on a parent.
