### ISSUE TITLE
Explicitly list supported compound shapes in the style section of the docs

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1892]
Only rect-like shapes are supported, because a compound's dimensions are defined by the bounding box of the children.  So `rectangle`, `roundrectangle`, and `cutrectangle` work.

It could be confusing if the user tries to use a non-rect shape.

Ref : https://github.com/cytoscape/cytoscape.js/issues/1891

**Comment by jsphstls** [comment]
Why would `round-rectangle` not be supported while `roundrectangle` is supported?
https://github.com/cytoscape/cytoscape.js/issues/2383
https://github.com/cytoscape/cytoscape.js/issues/1167#issuecomment-579869466

**Comment by maxkfranz** [comment]
It looks fine to me

<img width="241" alt="Screen Shot 2020-05-12 at 3 27 40 PM" src="https://user-images.githubusercontent.com/989043/81736818-29ac8000-9465-11ea-8076-0a84929f60b8.png">

**Comment by jsphstls** [comment]
Here is a repro:
https://codesandbox.io/s/cytoscape-ewwog

**Comment by maxkfranz** [comment]
Thanks for providing a reproducible test case, @jsphstls.  #2383 omitted the detail that the affected node is a parent.  If the issue template were followed properly, this could have been resolved sooner.

Anyway, thanks again for your repro.  The fix will be in the next patch release.
