### ISSUE TITLE
Does Cytoscape have a “S” edge line？

### ISSUE THREAD

**Issue by mokeyish** [cytoscape/cytoscape.js#1894]
I saw a “S” egde line in Demos Snapshot.
![baidushurufa_2017-7-12_17-36-58](https://user-images.githubusercontent.com/16131917/28111770-309bccf2-6729-11e7-82f1-e96512f0b0b6.png)

But I open the demo，there is no “S” egde line.
![baidushurufa_2017-7-12_17-39-30](https://user-images.githubusercontent.com/16131917/28111747-1bb044d0-6729-11e7-93f3-ae9a27f24f93.png)

**Comment by maxkfranz** [comment]
Someone made a mistake in the demo.  It's amended.  You may have to clear your cache.
