### ISSUE TITLE
Feature Request: Specify a node is locked for layout but subject to dragging

### ISSUE THREAD

**Issue by JLHwung** [cytoscape/cytoscape.js#1898]
**Issue type**

Feature request 

**Description of new feature**
Specify a locked node is draggable.

**Motivation for new feature**

We would like to use `cola` to draw a user-interactive force graph. While `infinite: true, fit: false` does keep interactivity, the user may be confused each time he/she drags out a pivot node and it turns out just sprinting back to the cluster since the node is never locked. However, if we set `node.lock()`, the user have to unlock each time before he/she drag again to minor refine the layout.

Here is a visual example: https://codepen.io/JLHwung/pen/VWBWYv/right/ implemented via d3-force. Each time you drag a node, the node is locked for forceSimulation but you can drag again any time if you aren't satisfied with the layout result.

This behavior can be partially imitated by 
```
on("layoutstart", () => node.lock())
on("layoutstop", () => node.unlock())
```
but it will cause racing when multiple layout run is active.

When `BRp.nodeIsDraggable` in `load-listeners.js` is set to exclude `lock()` status, the behavior is our desired behavior of this feature request.

**Comment by maxkfranz** [comment]
That approach would require refactoring every layout, and only the Cola layout would benefit.  In general, it would only be useful for infinite force-directed layouts that are stable between runs.  That's a very narrow class of layouts, and the feature would complicate the API for all layouts.  I don't think it makes sense in that case.

If you want to include a node in Cola but not have Cola change the position, it would make sense to instead add a feature to the Cola layout via a PR.

E.g. `canPositionNode: node => true || false`
