### ISSUE TITLE
Set a z-index for a node and node label separately

### ISSUE THREAD

**Issue by jlaw9** [cytoscape/cytoscape.js#1900]
**Issue type**
Feature request 

**Description of new feature**

I would like to be able to specify a z-index for a node and node label separately to  place the label of compound nodes above edges while keeping the compound node itself below edges. 

**Motivation for new feature**

In the two screenshots below, I have a compound node named "TARGETS" with many edges. In the first screenshot, the text is covered by the edges. In the second screenshot, I set the 'z-compound-depth' to 'top' which moves the text above the edges, but it also places the compound node above the edges.  
![image](https://user-images.githubusercontent.com/7592559/28386139-9fe22e34-6c98-11e7-801f-74b5440cc016.png)
![image](https://user-images.githubusercontent.com/7592559/28386166-b548da16-6c98-11e7-8fd2-33723cf60e4c.png)

**Comment by maxkfranz** [comment]
We experimented with having labels drawn in separate order from elements in the past.  It's not possible to support that without conflicting with several important features.

For your usecase, it may suffice to use `z-compound-depth: orphan` on the parent node.

**Comment by jlaw9** [comment]
Ok makes sense. Thank you for your response.

I tried using `z-compound-depth: orphan`, but the edges are still drawn on top of the parent node. I think I can get a pretty good solution for my usecase using the `z-index` option by setting the parent node above the edges (and the children above the parent node) and then setting the opacity of the parent node to be pretty low so the edges are still fairly visible.
