### ISSUE TITLE
 The 'preset' layout CANNOT achieve expected result.

### ISSUE THREAD

**Issue by qtttttttttting** [cytoscape/cytoscape.js#1902]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : v3.1.2
- Browser/Node.js & version :  chrome 59.0.3071.115 

**Current (buggy) behaviour**

When I set the layout to be 'null',the nodes are appear in the upper-left corner of the window. This is obvious ,because the null layout puts all nodes at (0, 0).But when I set the 'preset' layout  and set the property of node as follows:
 {
    "data": {
      "id": "1",
    },
    "position": {
      "x": 0,
      "y": 0
    },
    "group": "nodes",
}	
It does not  appear in the upper-left corner,but in the center.
I am so confused of the two layouts and the origin of coordinates.

**Desired behaviour**

 The preset layout can put nodes in the positions I specify manually.

**Minimum steps to reproduce**

as described above

**Comment by pumpadump** [comment]
Please paste your full layout configuration, do you configure `pan` or `fit` somewhere in your code?

**Comment by qtttttttttting** [comment]
var cy = window.cy = cytoscape({
          container: document.getElementById('cy'),
          layout: {
            name: 'preset',
            animate: false
          },
          elements: [
        {
        "data": {
          "id": "1",
        },
        "position": {
          "x": 0,
          "y": 0
        },
        "group": "nodes",
      }]
        });

**Comment by pumpadump** [comment]
if you look at the default config of the preset layout the fit option is set to true. I believe "fit" adjusts panning and zoom so that the nodes appear inside of the view port after they got relayouted. Try setting fit to false in your layout config and see if this leads to your expected results.
https://github.com/cytoscape/cytoscape.js/blob/92000782b9e77fc85ec59ed3c063243f14481119/src/extensions/layout/preset.js

**Comment by maxkfranz** [comment]
@qtttttttttting Have you read these sections of the docs?

- Position notation : http://js.cytoscape.org/#notation/position
- Default options for the preset layout : http://js.cytoscape.org/#layouts/preset

If you leave `fit: true`, it is expected that the viewport pan and zoom would be altered --- as @pumpadump suggested.

**Comment by qtttttttttting** [comment]
Sorry to bother you again.
Following your advice,I have tried to set the properties as follows.But the node remains in the center. 

var cy = window.cy = cytoscape({
container: document.getElementById('cy'),
layout: {
name: 'preset',
animate: false
},
          fit:false,
          zoom:1,
          pan: { x: 0, y: 0 },
elements: [
{
"data": {
"id": "1",
},
"position": {
"x": 0,
"y": 0
},
"group": "nodes",
}]
});

**Comment by pumpadump** [comment]
You have to set it as part of your layout options currently you only set the layout to preset and configure animate: false
```layout: {
name: 'preset',
animate: false
}```
above should be:
```layout: {
name: 'preset',
animate: false,
fit: false
}```

**Comment by qtttttttttting** [comment]
ooooooh,I come to understand suddenly. Thank you so much !
