### ISSUE TITLE
Allow for setting whether dragging from an element causes panning

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#1905]
**Issue type**

Feature request 

**Description of new feature**

Allow for no panning to occur when dragging on an edge.

Proposed API:

- `ele.pannable()` : Get whether panning happens when dragging on the element
- `eles.panify()` : Make the elements pannable.
- `eles.unpanify()` : Make the elements unpannable.

This allows for per-element granularity, and it's consistent with existing functions like `node.grabbable()`.

**Motivation for new feature**

When a `tapdown`-`tapdrag` gesture happens on an edge, it causes panning.  This is useful for dense graphs, where panning on an empty area may be difficult.

However, it may be desirable for some apps to have their own behaviour for dragging on an edge.  For example, you may want to drag the connected nodes of an edge when the edge is dragged.

This would be useful in apps like [Factoid](https://github.com/PathwayCommons/factoid).

**Comment by finger563** [comment]
Related to this, the behavior you describe differs if the edge is within another node, where no panning / dragging happen even if they're enabled.  I agree we should allow the developer to programmatically specify how / where / when dragging or panning is enabled even on a per-node / per-edge basiss.  For instance, I'd like to be able to disable dragging objects (which I can) but enable panning by clicking anywhere, not just on the background of the graph (which I can't: clicking / dragging inside compound nodes does nothing in that case).

**Comment by maxkfranz** [comment]
Yes, it may make sense to allow for nodes as well.  But I suppose that means we'd have to decide on a relative priority for dragging and panning.  If both may be enabled on a node, one should take precedence.  Probably dragging should be higher priority, but there may be some usecases I'm not considering.

**Comment by finger563** [comment]
I think it's at that point that the programmer / user should be able to select what actions are enabled by `ctrl`, `alt`, `meta/super`; e.g. drag is default, pan is ctrl, box select is alt, and the programmer can have another option for meta/super (e.g. copy / re-parent)

**Comment by SkBlaz** [comment]
Hello all! Has there been any improvement on the subject yet?

Thank you!

**Comment by rdecapomaranca** [comment]
I would also like to know if there has been any progress on this issue. It is an essential feature when dealing with dense graphs where nodes take the majority of the space.

**Comment by maxkfranz** [comment]
Any updates would be referenced in this ticket.  As you can see, this issue is not in the 3.3.0 milestone.  It may be considered for a later release, like 3.4.0.  PRs are welcome, and a PR could help put this feature into 3.3.0.

**Comment by finger563** [comment]
@rdecapomaranca have you seen https://github.com/cytoscape/cytoscape.js-panzoom ? I'm currently using that in my project until this feature gets implemented.

**Comment by lambdalisue** [comment]
I'm using the following code for workaround. fyi.

```typescript
function globalPanning(cy: cytoscape.Core, enabled: () => boolean) {
  let startPosition: null | {
    readonly x: number;
    readonly y: number;
  };
  cy.on('mousedown', (evt: cytoscape.EventObject) => {
    const e = (evt.originalEvent as any) as MouseEvent;
    if (enabled() && e.button === 0) {
      startPosition = evt.position;
    }
  });
  cy.on('mouseup', (evt: cytoscape.EventObject) => {
    const e = (evt.originalEvent as any) as MouseEvent;
    if (e.button === 0) {
      startPosition = null;
    }
  });
  cy.on('mousemove', (evt: cytoscape.EventObject) => {
    const e = (evt.originalEvent as any) as MouseEvent;
    if (startPosition) {
      const zoom = cy.zoom();
      const relativePosition = {
        x: (evt.position.x - startPosition.x) * zoom,
        y: (evt.position.y - startPosition.y) * zoom,
      };
      cy.panBy(relativePosition);
    }
  });
}

const cy = cytoscape({...});
globalPanning(cy, () => true);
```

**Comment by rdecapomaranca** [comment]
Thank you all for sharing different approaches. We have (temporarily) solved the problem by fixing the layout to be less dense.

**Comment by lambdalisue** [comment]
I made a plugin. fyi https://www.npmjs.com/package/cytoscape-anywhere-panning

**Comment by lhannest** [comment]
@lambdalisue
> I made a plugin. fyi https://www.npmjs.com/package/cytoscape-anywhere-panning

Thank you for that plugin. I found the nodes didn't move smoothly, but I was able to fix this by locking the elements in place:

```javascript
this.cy.anywherePanning();
this.cy.autolock(true);
```

**Comment by maxkfranz** [comment]
@lambdalisue's extension is great, but native support would be useful for things like changing the `ele.grabbable()` value automatically based on `ele.pannable()`.  Even with the native feature, the extension could have convenience functions for things like toggling the pan anywhere mode.  Another useful extension feature would be to easily customise keyboard shortcuts for toggling pan anywhere mode (e.g. enable pan anywhere mode when shift is held).

**Comment by luisflpereira** [comment]
Looks like "pannable: true" doesn't work for parent nodes.

**Comment by jtrammell-dla** [comment]
Agreed. I'm new to cytoscape, and I'm using it via plotly/dash, but I cannot for the life of me figure out how to get pannable to work on a compound node.

**Comment by maxkfranz** [comment]
@jtrammell-dla, what have you tried and what is the result?

**Comment by jtrammell-dla** [comment]
Let us start with: I am not entirely certain what version of cytoscape.js I am using, so it's possible I am not using a version that is intended to support this functionality? I can say that I am using dash_cytoscape 0.2.0. It seems that package refers to a package called react-cytoscape version 1.2.1. From there I can find no way of determining the remaining dependency chain back to a version of cytoscape.js. I don't even see my browser loading it which is a complete mystery to me...

That being said... I render a compound node:

`{"data": {"id": "background", "url": [png image data uri]}, "position": {"x": 0, "y": 0}, "pannable": True, "classes": ["background"]}`

I render four invisible nodes inside the compound node to force it to be large enough to display the full image:

`
{"data": {"id": "ul", "parent": "background"}, "position": {"x": -10, "y": -10}, "classes": ["cormer"]},
{"data": {"id": "ur", "parent": "background"}, "position": {"x": 10, "y": -10}, "classes": ["cormer"]},
{"data": {"id": "lr", "parent": "background"}, "position": {"x": 10, "y": 10}, "classes": ["cormer"]},
{"data": {"id": "ll", "parent": "background"}, "position": {"x": -10, "y": 10}, "classes": ["cormer"]}
`

And I render a simple graph inside the compound node:

`
{"data": {"id": "1", "parent": "background"}, "position": {"x": X, "y": Y}, "classes": ["datanode"]},
.
.
.
{"data": {"id": "N", "parent": "background"}, "position": {"x": X, "y": Y}, "classes": ["datanode"]},
`
And the result I get is that when I attempt to pan the plot by clicking and dragging on the compound "background" node, either with the left mouse button, or the middle mouse button, or the right mouse button, with or without any combination of control keys pressed, the node just "flashes" and nothing moves.

**Comment by maxkfranz** [comment]
You can get the Cytoscape version via `cytoscape.version`.

You can use the reported version number to determine whether features like pannable are supported in that version.  If you're using version that is too old, you could ask the folks at Plotly to upgrade their Dash component.
