### ISSUE TITLE
Strike-through style for labels

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js#1909]
Is it possible to render labels with a strike-through style?

**Comment by maxkfranz** [comment]
Canvas doesn't support text decorations, and the alignment of text differs between browsers: https://github.com/cytoscape/cytoscape.js/issues/1489

Because of those (sometimes fairly large) misalignments, I don't think the manually drawn strikethrough lines would be properly positioned.

**Comment by jalagar** [comment]
How about underlines? text-decoration: underline?

**Comment by maxkfranz** [comment]
That's exactly the same problem.
