### ISSUE TITLE
Edges do not follow nodes after several type changes

### ISSUE THREAD

**Issue by monprin** [cytoscape/cytoscape.js#1910]
**Issue type**
Bug report

**Environment info**
- Cytoscape.js version : 3.1.4
- Browser/Node.js & version : Node.js 8.2.1

**Current (buggy) behaviour**
Edges do not follow nodes if you cycle through bezier and haystack edges a couple times (see example in jsbin below).

**Desired behaviour**
I expect the edges to follow the nodes no matter what transformations I do to them.

**Minimum steps to reproduce**
When moving back and forth between haystack edges and bezier edges (such as in the context of using the undo-redo extension, it can hit a point where the edges just are not updated. This is shown fairly succictly in the following jsbin:
 
http://jsbin.com/belalonudi/edit?js,output

All I changed was the default edge type, added two classes to enable the switching, then the three transformation seen on the bottom.

**Comment by monprin** [comment]
It also appears that doing layout.run() twice on the last transformation fixes it, if that helps pinpoint the cause.

**Comment by maxkfranz** [comment]
@monprin Would you please confirm whether 81a7ccd solves this for your app using undo-redo?  I have tried the change on a downloaded copy of your Jsbin demo, and looks like it fixes it.

If it works for you, then I can apply it to unstable/3.2 and 2.x.

Sorry for the delay.  I was away and I've been catching up this week.

**Comment by monprin** [comment]
Yes that one does appear to fix it as far as I can tell! 

And no problem with the delay, thank you for all you work on this project.

**Comment by maxkfranz** [comment]
Great.  Fixed for 3.1.5 and applied to unstable/3.2 and 2.x.
