### ISSUE TITLE
Detached edge arrows after edge width change

### ISSUE THREAD

**Issue by michalhabala** [cytoscape/cytoscape.js#1912]
**Issue type**
Bug report

**Environment info**
- Cytoscape.js version : 3.1.4
- Browser/Node.js & version : Chrome 59.0.3071.115, no Node.js

**Current (buggy) behaviour**

When you change the edge width and the edge arrows are rendered then the edge line becomes detached or overreaching the arrow.
It looks like the distance from node is calculated and adjusted to allign with the edge arrow. But when you change the edge width (and the edge arrow size changes automatically according to the new edge width) then this distance is not recalculated.

**Desired behaviour**

Desired is to have the edge line alligned with the edge arrow (I suppose)...

**Minimum steps to reproduce**
- Open demo with rendered edge arrows, for instance http://js.cytoscape.org/demos/visual-style/
- Open JS console and run: 
```js
cy.style().selector('edge').style('width', '1px').update();
```
Now you should see that the arrows are detached from the ege line.
![detached_arrows](https://user-images.githubusercontent.com/9348874/28883874-34596948-77b0-11e7-8970-dc30e89481ce.png)

**Comment by maxkfranz** [comment]
@michalhabala Would you please try the latest on master and see if it's working for you?

**Comment by michalhabala** [comment]
@maxkfranz I've tested it and it looks that there is still a small bug. When I change the width of edges (bezier) then the arrows got detached (bug) but when I move some node then the edges of this node are redrawed and the arrows are attached correctly (but only on the redrawed edges)

**Comment by maxkfranz** [comment]
That was already fixed.  Make sure you're trying the latest source on master.

**Comment by michalhabala** [comment]
I'm using the /dist/cytoscape.min.js file because the /src/ folder contains unpacked files, which is a bit problem for me. Is there a way how to get the .min.js file from the latest source on master?

**Comment by maxkfranz** [comment]
`npm run build`

There are notes on build targets in the readme.

**Comment by maxkfranz** [comment]
Closing for release.  Comment here if you run into the issue again.

**Comment by michalhabala** [comment]
I've tested it and everything runs ok, the issue is solved for my case. Thanks
