### ISSUE TITLE
`dragfree`, `dragfreeon`, `freeon` events

### ISSUE THREAD

**Issue by anault** [cytoscape/cytoscape.js#1918]
Add a new event, `dragfree`, that is emitted when a set of nodes is has the following event sequence: `grab` => `drag` => `free`.

Use the `on` suffix to indicate the event concerns the node that the user's pointer is on, just like `grabon`.

Not supporting `freeon` with the previous addition of `grabon` was an oversight that this issue also addresses.  `free` was previously being emitted with the semantics of `freeon`.  Now, `free` happens on all the nodes that would be moved and `freeon` is just for the one under the pointer.

Implement for

- [x] Mouse 
- [x] Touch 

OP follows:

---

**Environment info**

- Cytoscape.js version : 3.1.1
- Browser version : Chrome 60.0.3112.90 (64-bit) 

**Current (buggy) behaviour**

Whenever I click a node, the `free` event is trigerred. Is this intended by the spec?
According to the doc:
> free: when an element is freed (i.e. let go from being grabbed)

**Desired behaviour**

Clicking a node would not trigger the `free` event.

**Minimum steps to reproduce**

```js
cy.on("free", "node", (evt) => {
    console.log("triggered")
});
```

**Comment by maxkfranz** [comment]
It's intended, because the `grab` event must happen on `tapstart`.  Otherwise, you'd have `grab` events without corresponding `free` events.

If you want to know when a node was freed from a drag, you need to listen for a `grab`-`drag`-`free` sequence.

**Comment by anault** [comment]
A `dragfree` event is exactly what I'm looking for!

**Comment by maxkfranz** [comment]
@alexcli Do you have time to implement this?

**Comment by alexcli** [comment]
@maxfranz Probably not. I'm gonna be busy today and tomorrow cleaning up and finalizing my data science stuff for Gary since I'm flying home on Friday.

**Comment by maxkfranz** [comment]
Ref : https://github.com/cytoscape/cytoscape.js/commit/9de44f52cd59aa00e13ec97053f2a5daab384175

**Comment by maxkfranz** [comment]
@anault This is working from my initial testing, but it would be good to try it in an app.

**Comment by anault** [comment]
I'll test it as soon as I can!

**Comment by maxkfranz** [comment]
Great; closing
