### ISSUE TITLE
The context-menus may be out of the screen

### ISSUE THREAD

**Issue by qtttttttttting** [cytoscape/cytoscape.js#1920]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version :  v3.1.2
- Browser/Node.js & version : chrome 59.0.3071.115

**Current (buggy) behaviour**

I use the context-menus of UI extension  , but when the node is on the right or bottom of the screen ,the context-menus will beyond the screen .And I see the source code ,it does not consider this situation.

207          var containerPos = $(cy.container()).offset();
208          var renderedPos = event.renderedPosition || event.cyRenderedPosition;
209
210          var left = containerPos.left + renderedPos.x;
211          var top = containerPos.top + renderedPos.y;
212
213          $cxtMenu.css('left', left);
214          $cxtMenu.css('top', top);

**Desired behaviour**

**Minimum steps to reproduce**

**Comment by maxkfranz** [comment]
Please post issues to the extension: https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/issues/17
