### ISSUE TITLE
Dynamic change of text-rotation for edge is not reflected when curve-style is set to bezier

### ISSUE THREAD

**Issue by fracz** [cytoscape/cytoscape.js#1936]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version: 2.7.23 & 3.2.1
- Browser/Node.js & version : All

**Current (buggy) behaviour**

If the `curve-style` of edge is set to `bezier`, changing the `text-rotation` of edge label is not reflected on graph until one of the connected nodes is dragged.

See fiddle: http://jsfiddle.net/fracz/jnznx0ze/46/

Click the button - the label is not autorotated. Then drag one of the nodes - the autorotation is applied.

Removing the `curve-style` attribute causes the `text-rotation` change be applied immediately.

**Desired behaviour**
The `text-rotation` style attribute shuould be applied immediately regardles of `curve-style`.

**Minimum steps to reproduce**
http://jsfiddle.net/fracz/jnznx0ze/46/

**Comment by maxkfranz** [comment]
@fracz Please try the latest source on master and let me know whether it works for you.

**Comment by izabellaszlosarczyk** [comment]
Hello. Sorry for the delayed response.
 It works perfeclty., thank you!
