### ISSUE TITLE
Bad performance on Chrome Mobile (Zenfone 2, Android)

### ISSUE THREAD

**Issue by anault** [cytoscape/cytoscape.js#1940]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.1
- Browser/Node.js & version : 
  - Good perf - Apple iPhone 5s 2013 iOS 10.3.3 Mobile Safari 10.0
  - Bad perf - Asus Zenfone 2 2015 Android 6.0.1 Chrome 59.0.3071.125

**Current (buggy) behaviour**

Performances are mediocre (~10 fps) on a recent Asus Zenfone 2 for a [single node graph](http://js.cytoscape.org/demos/qtip-extension/).

*left Safari, right Chrome*
![cydemo](https://user-images.githubusercontent.com/6646230/29538003-de2e74be-8691-11e7-86c7-b7ba29b30ddb.gif)

I noticed that the `Composite Layers` operations are taking ~100ms every frame during a pan on Chrome Mobile.

![cyperf](https://user-images.githubusercontent.com/6646230/29537545-2078fff8-8690-11e7-92b4-67aec4efa13b.png)

The problem only grows worse when the graph is bigger.

**Desired behaviour**

Improved performance for mid-range 2015 devices running Chrome Mobile 😄 

**Minimum steps to reproduce**

Open the [qTip demo](http://js.cytoscape.org/demos/qtip-extension/) on a Android device/emulator

**Comment by maxkfranz** [comment]
I tested on an iPhone SE today and a Moto G3.  The SE is 18 months old and the G is 25 months old.  They're both mid-range phones that are one generation behind current phones.  Both run the demos, like the qtip one, smoothly.  

We can't test on all hardware, especially in the fragmented Android market with hardware and software of highly ranging quality.  For devices that have manufacturer or service provider software modifications (i.e. non-stock Google Android), there are too many problems that they introduce for us to work around.

Cytoscape works well with modern hardware from mainstream brands, like Apple, Google (Nexus/Pixel), Motorola, Samsung, and LG.  Cytoscape is an open-source project that is funded by research grants.  We can not justify the cost in time and dollars in buying and testing many types of phones.

We'd welcome pull requests with workarounds for particular hardware, especially for niche or low-marketshare hardware that we are unable to test.

**Comment by maxkfranz** [comment]
Chrome has very conservative settings for the GPU.  Basically, it disables any 2D or 3D acceleration if the hardware isn't in Chrome's whitelist.

For example, Chrome won't enable acceleration for Intel HD 3000 (Sandy Bridge) even though it works just fine on Firefox and Safari.  Software rendering is very slow if that's all Chrome allows.    Or maybe the OS disables it too, since it's all Google software.  

If that's your issue, you might have better performance in Firefox for Android.  On desktop, `chrome://gpu` shows that all rendering is slow.  Maybe that also would show info on mobile.

**Comment by anault** [comment]
Here's the Chrome GPU infos for the Asus Zenfone 2:

![zenfone_2_gpu](https://user-images.githubusercontent.com/6646230/31150213-c661c926-a860-11e7-96f1-e944f75a3306.png)

Also, I tested the [qTip demo](http://js.cytoscape.org/demos/qtip-extension/) in Firefox Android on the same device, it's actually worst.

**Comment by maxkfranz** [comment]
> Disabled Features : accelerated_2d_canvas

That looks like the problem.
