### ISSUE TITLE
Compound nodes cause incorrect mid-target-arrow direction

### ISSUE THREAD

**Issue by josephrocca** [cytoscape/cytoscape.js#1942]
# Bug report

**Environment info**

- Cytoscape.js version : 3.2.1
- Browser version : Chrome Version 61.0.3135.4 (Official Build) dev (64-bit)

**Current (buggy) behaviour:** Mid arrow directions seem to render incorrectly (and inconsistently - not just opposite) when one of the source/target is a compound (parent) node.

**Desired behaviour:** Render them consistently and correctly

**Minimum steps to reproduce**
Here's a minimal example: http://jsbin.com/qaciwemefi/9/edit?html,output Notice that two edges are pointing toward node 15, and one is pointing away from it. They should all be pointing away from it - unless I'm terribly mistaken.

And here's the code since it's relatively small:

```javascript
    let elements1 = [
      {data:{id:1}},
      {data:{id:8}},
      {data:{id:11}},
      {data:{id:15}},
      {data:{id:"child", parent:15}}, // comment out this line and then the 15->1 and 15->11 arrow directions will be fixed
      {data:{id:"15-1", source:15, target:1}},
      {data:{id:"15-8", source:15, target:8}},
      {data:{id:"15-11", source:15, target:11}}
    ];
  
    
    let cy1 = cytoscape({
      container: div1,
      elements: elements1,
      style: [
          {
            selector: 'node',
            style: {
              'content': 'data(id)',
            }
          },
          {
            selector: 'edge',
            style: {
              'width': 3,
              'mid-target-arrow-shape': 'triangle',
              'arrow-scale':2,
            }
          }
        ]
    });
```
Thanks for your work on this incredible library! I'm having so much fun with it.

**Comment by maxkfranz** [comment]
Use `curve-style: unbundled-bezier; 'control-point-distance': 0;` (or [`curve-style: straight`](https://github.com/cytoscape/cytoscape.js/issues/1668) in 3.3).

Compounds can not use the default haystack edge type, so they fall back on bezier edges.  However, bezier edges are bundled.  That means they have to share the same direction, and that direction is automatically determined in order to maintain consistency as the graph changes.  So basically, you have to use an unbundled bezier for now so that the natural source-target direction is used.

**Comment by maxkfranz** [comment]
TODO note bundled bezier direction semantics in the docs

**Comment by josephrocca** [comment]
Thanks!

**Comment by maxkfranz** [comment]
I looked into this a bit more, and there is a problem in the code.  I was thinking about the spec of a previous version.  I've put some changes into master.  Let me know if that works for your with your original (non-workaround) code.

**Comment by josephrocca** [comment]
I just updated the cytoscape.js script src in that jsbin and it seems to work fine now, except that it doesn't look like arrow-scale is being respected: http://jsbin.com/roherazoji/1/edit?html,output

**Comment by maxkfranz** [comment]
The dist only gets updated for a release.

You need to build yourself from source.  I just tested it, and it's working OK.
