### ISSUE TITLE
Array.from() breaks cy.json() in Internet Explorer

### ISSUE THREAD

**Issue by brassard** [cytoscape/cytoscape.js#1961]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : v3.2.1
- Browser/Node.js & version : Internet Explorer 11 (11.540.15063.0)

**Current (buggy) behaviour**

Calling `cy.json()` errors out due to recently added incompatible code found at [`src/collection/index.js:232`](https://github.com/cytoscape/cytoscape.js/blob/6be2818ddefe2812dbbb828066da5368a0de921d/src/collection/index.js#L232):
```
    json.classes = Array.from(p.classes).join(' ');
```

`Array.from()` is [not supported by Internet Explorer](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Browser_compatibility).

**Desired behaviour**

`Array.from()` should be polyfilled so that the code will work in Internet Explorer 11. [The polyfill is available on MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill).

**Minimum steps to reproduce**

Here is a quick repro where JSON remains "unset" in IE because the code errors out: https://jsbin.com/desaxeyivu

Try to call `cy.json()`, which would normally return a JSON document like: 
```
{
    "elements": {
        "nodes": [],
        "edges": []
    },
    "style": [],
    "zoomingEnabled": true,
    "userZoomingEnabled": true,
    "zoom": 0.9108823716232318,
    "minZoom": 0.1,
    "maxZoom": 3.5,
    "panningEnabled": true,
    "userPanningEnabled": true,
    "pan": {
        "x": 591.5644850185573,
        "y": 397.78705897298585
    },
    "boxSelectionEnabled": true,
    "renderer": {
        "name": "canvas"
    }
}
```

That works fine in Chrome, but in IE11 emits the following error in the console:
```
SCRIPT438: Object doesn't support property or method 'from'
cytoscape.js (2225,5)
```

**Comment by maxkfranz** [comment]
In general, you should use [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill/) or [`core-js`](https://github.com/zloirock/core-js) if you are developing an app for outdated browsers.

I've addressed this particular instance.  But in future, Cytoscape will need to use more of the JS stdlib than is practical to internally work around or internally polyfill.

**Comment by brassard** [comment]
Thanks @maxkfranz. As I understand it, IE is currently listed as a supported browser for the library, but I completely agree with your points and would understand if Cytoscape dropped support for IE in the future. 

Unless support was already dropped with 3.x! In that case, I apologize for opening an issue!

**Comment by maxkfranz** [comment]
@brassard There are different levels of IE support:

(1) Write everything in ES5.  Use only underlying tech in the env that is directly supported (DOM APIs, drawing APIs, etc.).

(2) Write everything in ES6+ (incl. stdlib).  Use only underlying tech in the env that is directly supported (DOM APIs, drawing APIs, etc.).  A polyfill is needed for the stdlib and the lib itself is transpiled to ES5.

(3) Write everything in ES6+ (incl. stdlib).  Use the latest underlying tech in the browser env.  A polyfill is needed for the stdlib and the lib itself is transpiled to ES5.  It would also need several other high-quality polyfills that may or may not already exist.

All of these support IE.  (3) isn't really practical.  Nor is it practical in the longterm to do (1).  We can't have each contributor walking on eggshells, worrying if some basic feature in the stdlib is supported by a decade-old browser.  Some future feature or major release will probably go from (1) to (2).  It's too expensive to maintain (1).

In the longterm, we'll have to go with (2).  It's a reasonable compromise that would still have the same level of compatibility as (1).  Most modern apps use `babel` and `babel-polyfill` anyway.

**Comment by brassard** [comment]
Thanks for the thorough response, @maxkfranz.

I'm totally on board with your perspective and believe that contributors should ultimately be able to use the latest tech and not be concerned with breaking awful, obsolete browsers.

Usage of `babel` and `babel-polyfill` definitely seems like an essential piece for IE support here and any other modern JS libs. Do you think that we should update the documentation to mention it? If nothing else, we can add notes to the issue template and also quickly close tickets like these in the future. 😄

**Comment by maxkfranz** [comment]
Yes, it should probably be documented sooner rather than later.  We are already somewhere between (1) and (2), using a subset of ES6 with Babel.
