### ISSUE TITLE
Uncaught error when animating a 'fit' operation with bounding box

### ISSUE THREAD

**Issue by lorenzorande** [cytoscape/cytoscape.js#1965]
**Bug when giving a bounding box to cy.animate({fit: {...}})**

Bug report

*The sample JSBin provided in the issue template fails with this issue :* http://jsbin.com/teworah

This bug looks related to commit [270f5011b5c56169fc42cee9752c0b9432df98bd](https://github.com/cytoscape/cytoscape.js/commit/270f5011b5c56169fc42cee9752c0b9432df98bd#diff-34c8b5f694e27beb0e821e689286ae73L234), which adds a check on `object.empty()` where `object` is sometimes a collection of elements and sometimes bounding box `{x,y,w,h}`.
Adding a field `empty: () => true` to the bounding box bypasses the issue.

**Environment info**

- Cytoscape.js version : 3.2.2
- Browser/Node.js & version : IE11, Chrome

**Current (buggy) behaviour**

Throws a TypeError and fails to perform the fitting.

**Desired behaviour**
Perform the fitting without error.

**Minimum steps to reproduce**
```js
    cy.animation({
          fit: {
            boundingBox: cy.elements().boundingBox(),
          }
    });
```

The jsbin below highlights the TypeError.
https://jsbin.com/kisiqukimi/1/edit?html,output

**Comment by maxkfranz** [comment]
Thanks @lorenzorande 

Your patch has been merged into master and cherry-picked into unstable.

**Comment by maxkfranz** [comment]
Note that fitting to a bounding box is undocumented API.  It's used internally.

I've added a regression test.
