### ISSUE TITLE
Ctrl + scrool for zoom

### ISSUE THREAD

**Issue by ronkpunk** [cytoscape/cytoscape.js#1973]
Is it possible to change zoom control using ctrl + zoom instead of only scrool?

It would be confortable for high cytoscape areas

Thank you in advance
ronkpunk

**Comment by maxkfranz** [comment]
`C-+` is generally reserved by the browser for page zoom.  You can bind to `keypress` for just '+'/'=' and call `cy.zoom()` to zoom in.  You may want to zoom about the rendered centre point.
