### ISSUE TITLE
mapData() documentation

### ISSUE THREAD

**Issue by lisable** [cytoscape/cytoscape.js#1974]
**Explaination for function mapData()**

Hello!

I want to use mapData() for creating individual edges. But the documentation doesn't explain anything how the algorithm works behind this function. There is only a short example for mapData(strength, 1, 3, blue, red). But I couldn't figure out what blue and red means. And I need mapData() with numeric values and not with color names. Please, can someone explain how i.e. mapData(strength, 1, 3, 5, 20). I could figure out what strength and the range of 1, 3 means but for what is 5, 20. A range again? If yes, then for what? And how will be calculated the result of mapData()?

Thanks!

**Comment by maxkfranz** [comment]
Please refer to the docs: http://js.cytoscape.org/#style/mappers

**Comment by maxkfranz** [comment]
From the docs: mapData() specifies a linear mapping to an element’s data field. For example, mapData(weight, 0, 100, blue, red) maps an element’s weight to gradients between blue and red for weights between 0 and 100. An element with ele.data("weight") === 0 would be mapped to blue, for instance. Elements whose values fall outside of the specified range are mapped to the extremity values. In the previous example, an element with ele.data("weight") === -1 would be mapped to blue.
