### ISSUE TITLE
eles.move() deletes labels (and maybe all style)

### ISSUE THREAD

**Issue by nbgraham** [cytoscape/cytoscape.js#1975]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version: 2.7.15 (*The JS Bin uses the latest cytoscape, 3.2.3 at the time of writing this*)
- Browser/Node.js & version: 3.5.2

**Current (buggy) behaviour**

When I use `move` to move a node into or out of another node, I lose the labels on that node and the labels on the edges connected to that node.

**Desired behaviour**

These labels would be retained.

**Minimum steps to reproduce**
1. Add 4 nodes (1, 2, 3, and 4)
2. Makes edges (1,2) and (2,3)
3. Add labels to node 2 and edges (1,2) and (2,3)
4. Move node 2 into node 4

http://jsbin.com/nibigez/3/edit?js,output
Wait for the timeouts
```JS
setTimeout(function() {
    cy.$("#2").move({parent: "4"});
  }, 3000);
  
setTimeout(function() {
    cy.$("#2").style("label", "node 2");
    cy.$("#5").style("label", "edge (1,2)");
    cy.$("#6").style("label", "edge (2,3)");
  }, 6000);
  
setTimeout(function() {
    cy.$("#2").move({parent: null});
  }, 9000);
```
**My current fix for this:**
```JS
function moveSavingLabels(node, target) {
  let nodeID = node.id();
  let labelDict = {};

  let edgesConnectedToNode = cy.elements('edge[source = "' + nodeID + '"], edge[target = "' + nodeID + '"]');
  for (let index = 0; index < edgesConnectedToNode.length; index++) {
    let edge = edgesConnectedToNode[index];
    labelDict[edge.id()] = edge.style().label;
  }
  labelDict[nodeID] = node.style().label;

  node.move(target);

  for (id in labelDict) {
    cy.$("#" + id).style("label", labelDict[id]);
  }

  return cy.$("#" + nodeID);
}
```

**Comment by maxkfranz** [comment]
Duplcate https://github.com/cytoscape/cytoscape.js/issues/1750
