### ISSUE TITLE
Support for Background Video

### ISSUE THREAD

**Issue by ZachMoreno** [cytoscape/cytoscape.js#1976]
**Issue type**

Feature request

**Description of new feature**

Provide support for `<video>` elements as the backgrounds for nodes, similar to [Background Images](http://js.cytoscape.org/#style/background-image).

![cyctoscpe.js video mockup](https://i.imgur.com/C49gOTL.jpg)

**Motivation for new feature**

My team & I are building a podcast collaboration platform, [SquadCast.fm](https://squadcast.fm), & would very much like to redesign our recording experience from a layered to a graph UI for a number of reasons. Each participant's video would be displayed within a node, much like your [background image demo](http://js.cytoscape.org/demos/images-breadthfirst-layout/).

Our designers took inspiration from the [Tesla Powerwall app's UI](http://gph.is/2x3XbGO) & we'd like to illustrate the flow of A/V between participants & cloud storage. Cytoscape's reconfigurable & zoomable layout would also improve the UX for each participant.

Thanks for this awesome library & I'm happy to contribute to this enhancement.

**Comment by maxkfranz** [comment]
In general Cytoscape probably won't have core support for rendering anything other than the elements  The work-in-progress Popper extension is supposed to handle usecases like that, allowing arbitrary HTML/DOM over Cytoscape elements.

Refs:

- https://popper.js.org/
- https://github.com/cytoscape/cytoscape.js-popper
- https://github.com/cytoscape/cytoscape.js-qtip/issues/28#issuecomment-300247314

**Comment by maxkfranz** [comment]
You can position divs relative to Cytoscape elements using the `cytoscape-popper` extension: https://github.com/cytoscape/cytoscape.js-popper

Closing
