### ISSUE TITLE
`tapselect` and `tapunselect` events

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js#1977]
**Issue type**

Feature request

**Spec**

 * `tapselect` : when an element is selected by a tap gesture
 * `tapunselect` : when an element is unselected by a tap elsewhere

**Motivation**

See below OP:

-- 

Is there a way to set an element's selection state (like `ele.select()` does) but without firing a `select` event?

This is useful when the selection state must be restored programmatically e.g. on application launch or history pop (in a scenario when each interactive selection causes a history push).

In these cases the application must restore the (visual) state *programmatically* but without triggering the actions usually caused by *interactive* selection.

**Comment by maxkfranz** [comment]
No, mutating the selected state emits a `select` or `unselect` event.  It doesn't matter whether it originated from UI or whether it originated from just API calls.

You need additional (gesture) events.  It sounds like most of your app code shouldn't be listening to `select` directly.  There are already box events, so it would probably suffice to add `tapselect` and `tapunselect` events.  If you'd like to see these events in 3.3, please consider making a PR.  We already have a full queue of features we're working on for that milestone.

**Comment by jri** [comment]
The hint about not listening to the `select`/`unselect` event was fruitful. Now I kind of simulate `tapselect` and `tapunselect` by interpreting plain tap-node/edge and tap-background events. This solved my problem.

Thank you for helpful response!

**Comment by maxkfranz** [comment]
I'm glad it's working for you, but there is probably value in having direct support in the lib as well.  It would be clearer, and would support more cases.  The selection mode can be set differently from default.  Using `selectionType: 'additive'` would be different for `tap`, for example.

**Comment by jri** [comment]
I fully agree. Having `tapselect`/`tapunselect` events in the library would be good. Unfortunately at the moment I can't make a PR. Sorry.
