### ISSUE TITLE
a bug of edge

### ISSUE THREAD

**Issue by yujunjie0603** [cytoscape/cytoscape.js#1981]
Hello :

I replaced the library cy 2.78 by 3.23 !
I encountered a problem on edge !
If the "curve-style" is unbundled-bezier or segments 
at some distance and some degree, the edge disappeared ! (with 2.78, there isn't this problem)
I hadn't found problem !
There are someone who had encounted the same problem plz ?

thanks a lot

https://jsbin.com/puxixel/2/edit?html,js,output

**Comment by maxkfranz** [comment]
You've specified dimensions for your nodes and bezier points for your edges such that it's impossible to calculate the intersection points necessary to place the edge.

Change the edge style or the node dimensions to fix your issue.

See curve-style, control-point-distance, edge-distances, source-endpoint, etc.
