### ISSUE TITLE
Optional animated fit for preset layout

### ISSUE THREAD

**Issue by somedmguy** [cytoscape/cytoscape.js#1982]
**Issue type**

Feature request

**Description of new feature**  
Add a simple option to the preset layout (and any others for which this makes sense) that performs a pan & zoom animation to the correct final fit rather than repeatedly calling `fit()` as the layout progresses.

**Motivation for new feature**  
The current fit option can be rather jarring, causing the user to lose all context as the viewport instantly shifts at the start of the layout.  This change would allow the user to more easily track elements as they move from initial to final positions.

**Comment by maxkfranz** [comment]
It already does this http://js.cytoscape.org/#layouts/preset

See `/animate.*/` options

**Comment by somedmguy** [comment]
And that's what I get for not comparing the latest code with what I'm using before writing an issue.  Thanks!
