### ISSUE TITLE
SVG background-image causes an error in Internet Explorer 11.

### ISSUE THREAD

**Issue by soomin-maeng** [cytoscape/cytoscape.js#1990]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.4
- Browser/Node.js & version : Only Internet Explorer 11 - did not check other versions of Internet Explorer.

**Current (buggy) behaviour**

Adding a svg background-image property to elements causes an error in Internet Explorer 11, and no element is drawn on the canvas.

**Desired behaviour**

It should draw the svg image on the nodes or ignore the property if it causes an error.

**Minimum steps to reproduce**

Set the background-image property with a svg image and open the file on Internet Explorer 11.

context.drawImage(img, ix, iy, iw, ih, x, y, w, h) - is where the error 'Unexpected call to method or property access.' happens.

When I directly changed the code : 

html file
<img id="pix" src="image.svg" />

cytoscape file
var tempimage = document.getElementById("pix");
context.drawImage(tempimage, ix, iy, iw, ih, x, y, w, h);

It drew the svg image on the node (although it was not properly trimmed/adjusted for the node).

**Comment by maxkfranz** [comment]
Unfortunately, IE has several missing and broken SVG features.  If you want to use SVG in IE, you may have to test and potentially audit each SVG file that you include in your app.

**Comment by soomin-maeng** [comment]
I see. Thank you for the reply!
