### ISSUE TITLE
No box selection in compound nodes if parent is ungrabified

### ISSUE THREAD

**Issue by shean42** [cytoscape/cytoscape.js#1995]
In v3.2.4 (on FF55) this can be easily reproduced e.g. by:

var parent = cy.add({ group: "nodes", position: { x: 0, y: 0 } });
parent.ungrabify();  // comment this out for "expected" box selection behaviour in the compound node
cy.add({ group: "nodes", data: { parent: parent.data('id') }, position: { x: 50, y: 0 } });
cy.add({ group: "nodes", data: { parent: parent.data('id') }, position: { x: 100, y: 0 } });

Is this by design?

**Comment by shean42** [comment]
#1583

**Comment by maxkfranz** [comment]
OK, 8533ad2 should do it for the master branch.  Let me know if it works for you.
