### ISSUE TITLE
How could I export data and styles from cytoscapejs and import into cytoscape desktop?

### ISSUE THREAD

**Issue by renyaoxiang** [cytoscape/cytoscape.js#1997]
**Issue type**

This is a feature request

**details**

We would like to edit the network by the DesktopApp (cytoscape) and the Browser (cytoscapejs).
And how could we edit the same data through both app?  how could I get the doc.

And I found that the style exported by desktop app is not as same as the cytoscapejs.
for example, the key word 'css' in desktop means the key word 'style' in cytoscapejs.
and it can not import style from *.cyjs into desktop cytoscape, isn't it?

desktop app styles:
`

 	{
		"selector" : "node",
		"css" : {
			"border-opacity" : 1.0,
			"shape" : "rectangle",
			"border-width" : 2.0,
			"font-family" : "SansSerif.bold",
			 "font-weight" : "bold",
			 "background-color" : "rgb(0,255,51)"
		}
	},

`

cytoscapejs styles
`

	{
		"selector": "node, edge",
		"style": {
			"label": "fn"
		}
	},
`

**Comment by maxkfranz** [comment]
They both should support the same JSON.  It shouldn't matter if the desktop software uses a deprecated key.

**Comment by renyaoxiang** [comment]
I got it, Thank you!
