### ISSUE TITLE
Weird rendering bug in Safari (stretched or squished nodes)

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js#1998]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.1.4
- Browser/Node.js & version : Safari 10.1.2

**Current (buggy) behaviour**

Sometimes, rendering looks super-weird, see attached screenshot. I've only encountered it in Safari, but nowhere else. On certain thresholds of zoom we add/remove classes using cy.batch that change edge width, text size and similar, and once in a while (no discernible pattern) the attached screenshot is the result. When continuing to zoom (that is - triggering another threshold, no change until the new threshold is reached) it jumps back to expected look.

**Desired behaviour**

Not render weirdly.

**Minimum steps to reproduce**

![screen shot 2017-10-20 at 16 23 02](https://user-images.githubusercontent.com/47125/31826338-116e3588-b5b5-11e7-9378-f79514f154b1.png)

**Comment by buffpojken** [comment]
Exepcted look: 

![screen shot 2017-10-20 at 16 38 40](https://user-images.githubusercontent.com/47125/31826369-264692ca-b5b5-11e7-9bde-f334d23bb7ad.png)

**Comment by maxkfranz** [comment]
Do you have some sample code that reproduces it?  What version of OSX is this?  I'm on 10.12 (1 major release behind), and I'm on Safari 11.

**Comment by buffpojken** [comment]
This is the latest version of OS X and a freshly updated Safari. I'll see if I can isolate a test case.

**Comment by buffpojken** [comment]
Just for context - this is now the zoom-changes are implemented: 

```
	useZoomDependentStyles(){
		 this.zoomHandler = Utils.debounce((e) => {
		 	this.updateZoomDependentStyles()
		 }, 25);

		 this.graph.cy.on('zoom', this.zoomHandler);
	}

	updateZoomDependentStyles(){
		let zoom = this.graph.cy.zoom();
		let _add 		= '';
		let _remove = ''
		switch(true){
			case (zoom > 1.3): 
				_remove = 'zoom_2 zoom_3 zoom_4'; 
				break;
			case (zoom > 0.96 && zoom < 1.3):
				_add = 'zoom_2'
				_remove = 'zoom_3 zoom_4';
				break;
			case (zoom > 0.4 && zoom < 0.96):
				_add = 'zoom_3'
				_remove = 'zoom_2 zoom_4';
				break;
			case (zoom < 0.4):
				_add = 'zoom_4'
				_remove = 'zoom_2 zoom_3'
				break;
		}
		let that = this;
		this.graph.cy.batch(function(){
			that.graph.cy.$('node').addClass(_add).removeClass(_remove);
			that.graph.cy.$('edge').addClass(_add).removeClass(_remove);
		});
	}
````

Are we doing something obviously wrong that could result in this? 

I've tested not using ```cy.batch``` but apart from lower performance, the rendering issue still occurs.

**Comment by buffpojken** [comment]
Along with these style-definitions for classes: 

````
		  {
		  	selector: 'edge.zoom_2', 
		  	style: {
		  		width: 4
		  	}
		  },
		  {
		  	selector: '.zoom_3[?group]', 
		  	style: {
		  		"content": "", 
		  		"border-width": "3px"
		  	}
		  },
		  {
		  	selector: '.zoom_3[!group]', 
		  	style: {
		  		"font-size":36
		  	}
		  },
		  {
		  	selector: 'edge.zoom_3', 
		  	style: {
		  		"width": 6
		  	}
		  },
		  {
		  	selector: '.zoom_4[?group]',
		  	style:{
		  		"display": "none"
		  	}
		  },
		  {
		  	selector: '.zoom_4[!group]', 
		  	style: {
		  		'font-size': 45
		  	}
		  }, 
		  {
		  	selector: 'edge.zoom_4', 
		  	style: {
		  		'width': 8
		  	}
		  }
````

**Comment by buffpojken** [comment]
So, I've managed to isolate a very, very simple test-case which exhibits the bug (sometimes). The attached zip contains a super-simple graph, two nodes and an edge with some styling and scrolling back/forth in Safari will sometimes (not everytime but often enough) result in the render bug - see the attached screenshot. 

[cytoscape-test-package.zip](https://github.com/cytoscape/cytoscape.js/files/1449465/cytoscape-test-package.zip)
![screen shot 2017-11-07 at 10 56 37](https://user-images.githubusercontent.com/47125/32487687-a7f6f9a6-c3aa-11e7-9daa-a19ed4e0772f.png)

**Comment by buffpojken** [comment]
Unfortunately, I'm able to reproduce on latest Safari as well, Version 11.0.1 (12604.3.5.1.1) with the attached screenshot: 

![screen shot 2017-11-07 at 11 11 04](https://user-images.githubusercontent.com/47125/32488366-a51cc42a-c3ac-11e7-8085-abe12407d806.png)

**Comment by maxkfranz** [comment]
This affects 3.2.6 and 2.7.26.  I can reproduce this sometimes on Safari, rarely on Firefox, and I haven't been able to reproduce it on Chrome.

@buffpojken The 0afbc4b commit seems to resolve things for me on the test page you provided.  It's been ported to unstable and 2.x as well.  Let me know whether this fixes things for you in your app.

Sorry for the delayed response.  I've been very busy, and it wasn't easy to reproduce the issue and come up with a solution.

**Comment by buffpojken** [comment]
Your reproduction matrix matches ours - it happens sometimes (but still often) on Safari, once or twice on Firefox and we've never managed to reproduce it on Chrome. 

I'll see if I can run unstable against the case and reproduce. 

No worries at all, grateful for all the time you're spending on cytoscape and making it available to all of us!

**Comment by buffpojken** [comment]
Hmm, just to check - unstable has apparently reverted the cyTarget => target change from a while back - is this intentional?

**Comment by buffpojken** [comment]
I've got bad news. Unfortunately both me and QA could reproduce it on latest Safari, both in the test case and in the actual application using unstable, reporting version as "snapshot-564e9ad5ee-1466537151217".

See attached screenshot from an instance running this cytoscape-version.

![screen shot 2017-11-22 at 14 43 14](https://user-images.githubusercontent.com/47125/33130741-9c3834fe-cf94-11e7-8dbc-3fd5fa647358.png)

**Comment by maxkfranz** [comment]
@buffpojken When you build a snapshot, the first number is the commit hash of the build and the second is the timestamp.  I don't see that commit in the repo.  If you're running the latest code, there isn't even the ability to build zips anymore.

Maybe your local copy of the repo is bad.  I've attached a snapshot build off of master (0afbc4b).

[build.zip](https://github.com/cytoscape/cytoscape.js/files/1496713/build.zip)

**Comment by buffpojken** [comment]
Hmm, weird - but thanks! I'll test it asap tomorrow morning!

**Comment by buffpojken** [comment]
Well, I have good news and bad news. 

The good news is that it's -almost- fixed. The bad news is that while it now occurs a lot more seldom, it still occurs. Our QA-people used to able to trigger it quite regularly - today (with the new build) it occurred very rarely in their testing, but still occurred?

**Comment by maxkfranz** [comment]
You're able to reproduce it still with your cytoscape-test-package.zip?

**Comment by buffpojken** [comment]
Yes, though - as stated above, much more rarely.

**Comment by maxkfranz** [comment]
@buffpojken I tried 7e1d388 on Safari 10 (OSX 10.11) and 11 (OSX 10.12) on two different machines and I couldn't reproduce it.  I was able to reproduce it about 3 times pre-7e1d388 on the test page, though it was difficult to notice.

I've attached a build.  You probably want the cjs.js file.  Let me know if it works for you.

[build-snapshot-7e1d3884e6-1511889525723.zip](https://github.com/cytoscape/cytoscape.js/files/1510946/build-snapshot-7e1d3884e6-1511889525723.zip)

**Comment by buffpojken** [comment]
@maxkfranz - I've put this on the QA pipeline, will hopefully have results from them tomorrow!

**Comment by maxkfranz** [comment]
@buffpojken Great, thanks

**Comment by buffpojken** [comment]
I can confirm from QA that they can no longer reproduce at all with latest snapshot. Awesome work!
