### ISSUE TITLE
Unable to use edge points functions in headless mode.

### ISSUE THREAD

**Issue by juliepagano** [cytoscape/cytoscape.js#2000]
I get an error when trying to use the [edge point functions](http://js.cytoscape.org/#collection/edge-points) in headless mode. I am not entirely sure if this is a bug or a feature request. The documentation does not specify that this feature does not work in headless mode.

**Environment info**

- Cytoscape.js version : 3.2.4
- Browser/Node.js & version : running client-side in Chrome 60.0.3112.113 on OSX

**Current (buggy) behaviour**

When trying to do something simple with an edge point (e.g. console.log the source endpoint) in headless mode:
```
console.log(edge.sourceEndpoint())
```

I get the following error:
```
renderer.getSourceEndpoint is not a function
```
Looks like the error originates here: https://github.com/cytoscape/cytoscape.js/blob/master/src/collection/dimensions/edge-points.js

**Desired behaviour**

The edge point information is returned and no errors are thrown.

**Minimum steps to reproduce**

* Use cytoscape in headless mode.
* Add some nodes and edges.
* Try to use any of the [edge point functions](http://js.cytoscape.org/#collection/edge-points) on one of the edges.

**Comment by maxkfranz** [comment]
There's no way that could work.  You can't query for rendered values without having a proper renderer.  If you run headless, you just have a renderer that does nop for everything.

If you want to do rendering things on a server, use PhantomJS or the new headless Chrome.

**Comment by juliepagano** [comment]
Thanks for the feedback! We were trying to find a quick way to get enough information (positions, etc.) to do our own rendering, and headless mode worked well for nodes, and we were hoping we'd get enough for edges too. I'll give rendering without visibility a try, and if that doesn't suit our needs, we can look into making a custom renderer.

**Comment by maxkfranz** [comment]
(1) You can draw anything on or in place of nodes using SVG background images.  Cytoscape will handle this more performantly than an SVG document.

(2) You can use the canvas extension if you want to draw on top of the graph: https://github.com/classcraft/cytoscape.js-canvas
