### ISSUE TITLE
Unbundled bezier edges sometimes don't render

### ISSUE THREAD

**Issue by epatters** [cytoscape/cytoscape.js#2005]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.1 - 3.2.4
- Browser/Node.js & version : Google Chrome 61.0.3163.100, Node.js 8.7.0

**Current (buggy) behaviour**

Since version 3.2.1, my unbundled Bezier edges are rendering unreliably. Sometimes they appear, sometimes they don't. In version 3.1.5, I don't have this problem.

The issue is possibly related to https://github.com/cytoscape/cytoscape.js/issues/1451

**Minimum steps to reproduce**

This example (not minimal--sorry!) illustrates the problem:

http://jsbin.com/hurisituta

If you drag the nodes around you can see the Bezier edges appear and disappear.

**Comment by jack5678** [comment]
Sad

**Comment by epatters** [comment]
Thank you both for the quick fix! I will give this a whirl when you cut the next release.

**Comment by maxkfranz** [comment]
I was planning on releasing 3.2.5 today anyway, so I'll just close this for now and publish.
