### ISSUE TITLE
staggering the position of edge endpoints

### ISSUE THREAD

**Issue by jonorthwash** [cytoscape/cytoscape.js#2013]
**Issue type**

Feature request

**Description of new feature**

I'd like a way to manually adjust the x and/or y position of edge endpoints.  In other words, I'd like the endpoint of an edge to be able to be moved to one side or another of where it would normally intersect with a node.

**Motivation for new feature**

Currently it's possible to adjust the endpoints to some extent with `source-endpoint` and `target-endpoint`, but this affects the angles of parts of the edges.  Otherwise, endpoints default to the same position, as seen in this screenshot with three overlapping endpoints:
![2017-11-04-23 17 29_001](https://user-images.githubusercontent.com/963849/32411669-f742bbe8-c1b7-11e7-849f-0d79197593e1.png)

With some ability to adjust the position of the endpoints, one could do something like this [poor-quality (sorry)] mock-up:
![2017-11-04-23 17 29_001_1](https://user-images.githubusercontent.com/963849/32411671-fb7b8f00-c1b7-11e7-8dcc-0bfb743008f2.png)

Currently we have to use redundant arrows (at least one of the two hollow arrows in the above) so that we know which edges have a source in a given node and which edges have a given target.

@ftyers and @maryszmary are likely to be interested in this feature request too.

**Comment by maxkfranz** [comment]
You can already have full manual control over the edge endpoints: http://js.cytoscape.org/#style/edge-endpoints

> but this affects the angles of parts of the edges

Then you haven't set your control points appropriately.  If you have trouble understanding (or calculating) how bezier curves work, try the segments style instead: It's easier to position straight lines.
