### ISSUE TITLE
cytoscapeJS- 'get' graph object instance for downstream operations

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js#2015]
Hi, I used to use the following code with older versions of cytoscapeJS (2.4 and earlier) to get a reference to the graph container and set a _layout_ on it. This helped my network have users change/run layouts when they liked, from cola to cose, spread, etc., as shown below:
`var cy= $('#cy').cytoscape('get');`
`var coseLayout= { name: 'cose', animate: true,
    handleDisconnected: true, avoidOverlap: true,
    idealEdgeLength: 100 };`
`cy.$(':visible').layout(coseLayout);`

I am presently trying to upgrade to the _**latest**_ version of cytoscapeJS (v**3.2.5**)to try out the new algorithms and layouts (_euler_, _klay_) but my old graph rendering, layout code throws up errors. I modified the _initialisation_ from: `$('#cy').cytoscape({ ... });`
to the new way: `var cy= cytoscape({ ... });` and that works fine.

However, when changing layout, the `var cy= $('#cy').cytoscape('get');` line (to _get_ reference to the network/ container, it throws a `$(...).cytoscape is not a function` error. I'm going through the documentation but cannot find references to this change.

Any guidance would be very useful.

**Comment by AjitPS** [comment]
In cytoscapeJS **3.2.5**, what's the recommended approach to get an instance of the graph object, i.e., to replace the old approach below:
`var cy= $('#cy').cytoscape('get');`

**Comment by AjitPS** [comment]
Any suggestions regarding this @maxkfranz ? Thanks.

**Comment by AjitPS** [comment]
Also asked at https://stackoverflow.com/questions/47262638/cytoscapejs-3-2-5-get-graph-object-instance-cytoscapeget but got no response yet

**Comment by AjitPS** [comment]
any suggestions?

**Comment by eugeniashurko** [comment]
Hello! I am having a similar trouble here. I am creating a graph using Dash Cytoscape and my task is to retrieve the node positions generated by the layout (for example, 'cose'). According to https://stackoverflow.com/questions/55444768/how-can-i-find-the-positions-of-nodes-in-dash-cytoscape-after-the-user-moved-the it seems to be impossible using pure Dash. 

Therefore, I am trying to make a js-script which would 'retrieve' a cytoscape object from the graph already created and rendered by Dash Cytoscape (then, I would for example do `cy.elements().json()`). 

Would be greatful if you could suggest some workaround!

**Comment by maxkfranz** [comment]
Have you asked the Dash guys at Plotly?

**Comment by eugeniashurko** [comment]
Not yet, was wondering if there is some solution from the cytoscape.js side that I couldn't find. Thanks a lot, I will reach out to them

**Comment by rneeft** [comment]
Any news regarding this topic. I'm integrating Cytoscape with Blazor WASM, and I also need a reference to the Cytoscape instance in JS.
