### ISSUE TITLE
Background images do not invalidate the element texture cache if only dirtying position events come in 

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#2026]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.6
- Browser/Node.js & version : All

**Current (buggy) behaviour**

When an image loads, normally the texture cache should be invalidated.  It is not when only dirtying position events come in on the same tick.

(1) There is a check for performance: If only dirtying position events come in, the element texture is still valid.

(2) There is an omission for performance: Background events are not added to the dirty event list -- per element.

Because of (2), (1) can be an invalid assumption if a node's background image loads while the node is moving (and no other dirtying event type comes in).

**Desired behaviour**

Dirty the cache so that the element is drawn.  Removing (2) should suffice.

**Minimum steps to reproduce**

Refer to https://github.com/cytoscape/cytoscape.js/issues/1511#issuecomment-347941010

**Comment by maxkfranz** [comment]
@brassard @buffpojken faea4ce902c52910f8b71941c4323d0c448f8c2b should do it.  Let me know if it works for you.

[snapshot-faea4ce902-1511986837206.zip](https://github.com/cytoscape/cytoscape.js/files/1515396/snapshot-faea4ce902-1511986837206.zip)

**Comment by brassard** [comment]
Looks like that fixed it!

When do you expect 3.2.7 to land?

**Comment by brassard** [comment]
@buffpojken -- will your QA team be looking at this one too? Anything yet?

**Comment by buffpojken** [comment]
Sure thing! I’ll check with them later today when people are back from the weekend.

**Comment by maxkfranz** [comment]
@buffpojken @brassard Great, it looks like we're good for release then.  I'll publish within the next couple of hours.
