### ISSUE TITLE
How to write content on node's background image?

### ISSUE THREAD

**Issue by arpitmrana** [cytoscape/cytoscape.js#2032]
I want to show some features of the node (which is an item) in my case on mouseover a node. 

Node has already a background image which is set by passing an online link. Instead of showing the features in a tip (using cytoscape-qtip / qtip), I just want to show these features on the node background image itself. 

This is a simple functionality which I need image fades out and a piece of text is shown on it on mouseover. How can it be done in cytoscape? Any help...?

**Comment by maxkfranz** [comment]
The issue tracker is for feature requests and bug reports.  This is not a support forum.
