### ISSUE TITLE
eles.style() function synchronously

### ISSUE THREAD

**Issue by ituJava** [cytoscape/cytoscape.js#2033]
Hello, 

I am using Cytoscape.js 2.7.15 for my graduation project and i need to make some simple visualizations like changing the labels of  nodes. `subjectNode.style('label',myDesiredLabelToshow);`  works for me but i  am using it in a for loop and when i want to make it slowly or in debug mode to see how my algorithms works to label them, the labels of nodes do not change immediately, they change eventaully together after my function ends (i mean hit to end scope of function). I tried to use `cy.batch();`  `cy.startBatch()`  even tried to set Timeout but nothing worked. 

After tracking cytoscape.js file in debug mode i saw a function `o.requestAnimationFrame = function..` after debugger hits that changes are applied on my graph, how can i manually trigger it in my custom functions.

**Comment by maxkfranz** [comment]
https://stackoverflow.com/questions/47925344/cytoscape-js-eles-style-changes-update-immediately
