### ISSUE TITLE
Source code for demos?

### ISSUE THREAD

**Issue by BMahabir** [cytoscape/cytoscape.js#2034]
This may be a silly question but -- is there any way to see the source code for the wonderful demos you have created on the main website under the "Demos" section?  This would really help me a lot as I learn best by example.

Thanks!

**Comment by BMahabir** [comment]
I finally figured this out, it was by clicking on the tiny cat-icon next to each demo.  This is not obvious at all, I would include it as an instruction on the main page.

**Comment by maxkfranz** [comment]
The Github logo links to the source code on Github.  If you have an idea for a clearer icon, feel free to make a pull request that implements your idea.
