### ISSUE TITLE
Can't get `nodes.parents()` to work

### ISSUE THREAD

**Issue by subhc** [cytoscape/cytoscape.js#2035]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.7
- Browser/Node.js & version : Chrome Version 63.0.3239.108 (Official Build) (64-bit)

**Current (buggy) behaviour**

Ancestor list is always empty for `nodes.parents()`. I am not sure if I am using the method correctly.

**Desired behaviour**

It should return the ancestors of a node.

**Minimum steps to reproduce**
1. Open http://js.cytoscape.org/demos/dagre-layout/
2. In inspect window (`F12`),  type `cy.nodes('#n15').parents()` in its console

It should return 3 nodes but returns a zero length object.

![](https://i.imgur.com/OUt3jQr.jpg)

**Comment by maxkfranz** [comment]
Not a bug.

Read the docs, please:

- http://js.cytoscape.org/#nodes.parent
- http://js.cytoscape.org/#notation/compound-nodes
