### ISSUE TITLE
Position of nodes are reset after excute layout.run()

### ISSUE THREAD

**Issue by vietson** [cytoscape/cytoscape.js#2036]
Hello Sirs,
I'm using cytoscape, cose layout
I want set position of some node. This is my code
          `if(node.id()!='n10'){node.position({
			x: xxx + (i * 100),
			y: yyy
					});
				}`
But after excute layout.run(). position of my nodes are reset
How can preserve position of nodes  after layout.run()?
Thanks !

**Comment by NeemaPaul** [comment]
How did you fix this issue?
