### ISSUE TITLE
QTip on mouseover 

### ISSUE THREAD

**Issue by kavinnagul** [cytoscape/cytoscape.js#2038]
@maxkfranz 

Qtip not working on mouse over. Below code working for Click event.

Can you please suggest what changes i have to do for mouseover event.

cy.$("#"+this.id()).qtip({
show: { event: 'directtap' },
//hide: { event: 'mouseout' },
content: function(){ return 'Example qTip on ele ' + this.id() },
position: {
my: 'top center',
at: 'bottom center'
},
style: {
classes: 'qtip-bootstrap',
tip: {
width: 16,
height: 8
}
}
}).on('tap', function( e ){
var eventIsDirect = e.target.same( this ); // don't use 2.x cyTarget

		  if( eventIsDirect ){
			this.emit('directtap');				
		  }
		}).on('directtap', function( e ){
		  e.stopPropagation();
		});

**Comment by maxkfranz** [comment]
The issue tracker is for feature requests and bug reports.  This is not a support forum.

Try using cytoscape-popper instead.
