### ISSUE TITLE
Render html on edge labels

### ISSUE THREAD

**Issue by BernhardKonrad** [cytoscape/cytoscape.js#2043]
Feature request
**Description of new feature**

Render html on edge labels, in particular, allow different colors in the same label.

**Motivation for new feature**

I want to build a diff graph and it would be nice to have both the added (green) and removed (red) labels on the same edge.

**Comment by maxkfranz** [comment]
This is something that will not be supported in the core library.  You can use SVG background images to render whatever you want on top of nodes.  Cytoscape will scale and cache them appropriately to keep things fast.

If you require HTML labels specifically, you will need to write an HTML-labels extension or wait for the first-party [Popper extension](https://github.com/cytoscape/cytoscape.js-popper), which allows you to position HTML relative to graph elements, to be published.
