### ISSUE TITLE
Add method for switching box selection mode on/off programmatically without pressing shift/alt/ctrl key

### ISSUE THREAD

**Issue by aprudnikoff** [cytoscape/cytoscape.js#2045]
**Description of new feature**

I'd like to have some method to switch on box selection mode without pressing shift/alt/ctrl key additionally. I'd like to have an ability to switch it on/off programmatically.

**Motivation for new feature**

I need to add user simple ability to select some nodes and group them together as children of a new compound node.
It's not a good idea to write some instruction to press some shift/ctrl/alt key to make box selection. I'd like to add some toolbar button called kinda "Box selection mode: on/off".

**Comment by maxkfranz** [comment]
> I'd like to have an ability to switch it on/off programmatically.

This already exists.  Just toggle whether user panning and box selection are enabled.  If only one is on, it will be the only drag gesture available and will start without modifier keys.

**Comment by aprudnikoff** [comment]
@maxkfranz thank you. It works.
Can you add some words about it to docs? It's not clear enough now.
