### ISSUE TITLE
position event is triggered for all nodes when node is tapped without moving

### ISSUE THREAD

**Issue by aprudnikoff** [cytoscape/cytoscape.js#2046]
Bug report

**Environment info**

- Cytoscape.js version : 3.2.7
- Browser/Node.js & version : Chrome latest

**Current (buggy) behaviour**
`position` event is triggered for all nodes even if a node just tapped without moving.

**Desired behaviour**
`position` event should not be triggered if position isn't changed indeed.

**Comment by maxkfranz** [comment]
Not reproducible on master/3.2.8

```js
cy.nodes().on('position', () => console.log('position'))

// click node

// no log
```

**Comment by aprudnikoff** [comment]
Checked it one more time. Very sorry, it's my bad.
