### ISSUE TITLE
Stable event order?

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js#2047]
**Issue type**

Feature request

**Description of new feature**
This is more of a verification question than an outright feature request. Is the order of triggered events always stable for pan vs. zoom? Consider the following: 

```
		this.graph.cy.on('pan', this.panHandler = (e) => {
			console.log('pan')			
		});

		this.graph.cy.on('zoom', function(){
			console.log('zoom')
		})
```
We're observing that on a zoom-action, the zoom event will -always- trigger before the pan-event resulting from the zoom-action. Is this stable and thus can we rely on their internal order or is this just a side effect?

**Comment by maxkfranz** [comment]
It might be consistent as a result of writing it consistently in the code, but there was no design decision made on order of events.  You have no guarantees.

There's a `viewport` event that "joins" `pan` and `zoom` events together.  A `viewport` is either a `pan`, a `zoom`, or a joined `pan zoom` pair (e.g. wheel zoom).  This was added in 2.4 or 2.5, but it seems to be missing from the docs...

**Comment by buffpojken** [comment]
Hmm, I see.

The thing is that we need to differentiate between an explicit pan and a zoom-caused pan due to implementing a parallax-effect in the background. Based on current event ordering we’re setting a flag on zoom, and breaking on it in pan if set - which works just fine.

Not sure the viewport-event would help us out with that - unless that event has a fixed order in regards to pan?

**Comment by maxkfranz** [comment]
You should probably be checking the time delta between events.  Wheel zoom would generate `pan zoom` on the same tick

**Comment by buffpojken** [comment]
Oh, I see - I did not know that, that makes a lot of sense! Many thanks for the pointer!

**Comment by buffpojken** [comment]
Unfortunately, that's not the case. It's almooooost the case. In the attached screenshot, I've just hooked up a console-print as follows: 
````
		this.graph.cy.on('pan', this.panHandler = (e) => {
			console.log("pan:" + e.timeStamp)			
		});

		this.graph.cy.on('zoom', function(e){
			console.log("zoom:" + e.timeStamp)
		})
````

and roughly 2/3 of the times, they reflect the same tick, however, 1/3 of the times - on of them is off by 1. 

![screen shot 2018-01-25 at 09 54 15](https://user-images.githubusercontent.com/47125/35379269-d0aea4a4-01b5-11e8-8f72-86a48b7b778d.png)

For my case, that doesn't really matter since I can check if it's within X for acceptable results, but in case something else depends on them having the same timestamp I'm reopening the issue?

**Comment by maxkfranz** [comment]
On most hardware, each `requestAnimationFrame()` tick is ~16ms apart.  Consider also that for two lines you could be close to the end of a discrete ms on the clock for the first line and on the next ms the next line.

**Comment by maxkfranz** [comment]
For user gestures, you can use the fact that humans are pretty slow in changing input actions, so thresholds of ~100ms or ~200ms are probably fine.

**Comment by maxkfranz** [comment]
Closing.

For people who refer to this in future: The takeaway message is that you can not assume event order for `pan` and `zoom` when doing a wheel zoom or a pinch zoom.
