### ISSUE TITLE
How to enable zooming and panning with a fixed viewport?

### ISSUE THREAD

**Issue by BMahabir** [cytoscape/cytoscape.js#2052]
Core library issue

Bug report

**Environment info**

- Cytoscape.js version : 3.28
- Browser/Node.js & version :

**Current (buggy) behaviour**

When I set the option "userPanningEnabled: false", it stops my ability to zoom in and out of a particular point.  This is explained succinctly in this stackoverflow : https://stackoverflow.com/questions/38226272/panningenabled-false-disable-zooming.  This is fine, I can live with it.  Nevertheless, I do not want the user to be able to pan the graph with no restrictions, and the ability to zoom in and out is a requirement of my project.

**Desired behaviour**

I want to restrict the user panning the graph so that the furthest edges/nodes from the center of the graph are always inside the screen.  I also want the user to be able to zoom in and out of the graph, but be restricted from zooming in if, similarly, it would cause the graph to expand beyond the edges of the screen.  How can I accomplish this?

**Comment by maxkfranz** [comment]
That is not a bug report.  The issue tracker is for feature requests and bug reports.  This is not a support forum.

**Comment by srinivasrk** [comment]
@BMahabir were you able to figure out how to do this?
