### ISSUE TITLE
cy.emit and cy.removeListener error

### ISSUE THREAD

**Issue by huzhaoheng** [cytoscape/cytoscape.js#2055]
I am implementing following code

functino A(){
//some other code
cy.on('tap', 'node', function handler(evt) {
		var resource = this.data('label');
		showQueryObject(resource);
	});
}

function showQueryObject(resource) 
{
	var cy = document.getElementById('cy');
	cy.removeListener('tap');
}

I got an error which told me 

Uncaught TypeError: cy.removeListener is not a function
    at showQueryObject (CreateDataset.js:41)
    at e.Element.handler (CreateDataset.js:32)
    at e.Core.trigger (cytoscape.min.js:18)
    at e.Element.trigger (cytoscape.min.js:18)
    at cytoscape.min.js:26

Can anyone help me?

**Comment by maxkfranz** [comment]
The issue tracker is for feature requests and bug reports.  This is not a support forum.
