### ISSUE TITLE
Compound node: Left align the content/label in the child node

### ISSUE THREAD

**Issue by vijayperlakota** [cytoscape/cytoscape.js#2056]
Hi,

Recently I am trying with cytoscape js for my graph related assignment. Its one of the best lib I found.
**Problem I am facing:**
In compound node, I am trying to left align the label of the child node using text styles that lib provides. text-halign (left) and text-valign (bottom) properties.

Below is what I am seeing.

![screen shot 2018-01-29 at 2 30 17 pm](https://user-images.githubusercontent.com/5469709/35501801-fb55b1ae-0500-11e8-8f3b-379df1629f72.png)

I wanted the labels to be left aligned within the node. 

Appreciate your help, Thanks.
VJ

**Comment by maxkfranz** [comment]
The issue tracker is for feature requests and bug reports.  This is not a support forum.
