### ISSUE TITLE
Chrome v64 sometimes mangles the graphics output

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#2059]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 2.7.x (probably, but yet untested), 3.2.x (confirmed)
- Browser/Node.js & version : Chrome v64 (Mac, Linux)

Reproduced on:

- Mac 10.11
- Mac 10.12
- Mac 10.13
- openSUSE Tumbleweed (both Chromium and Google Chrome)
- Fedora 27 (Chromium)

**Current (buggy) behaviour**

The graphics can be mangled in Chrome v64.  The output can be missing (e.g. one or more nodes not shown).  The output can be garbled or shifted.

Neither Safari nor Firefox have this issue, and Chrome does not exhibit this behaviour in v63.  It seems there are changes to how Chromium handles canvas and the GPU in v64: https://chromium.googlesource.com/chromium/src/+log/63.0.3239.132..64.0.3282.119?pretty=fuller&n=10000

**Desired behaviour**

Render the graph properly, like Safari, Firefox, and Chrome v63 do.

**Minimum steps to reproduce**

The only easily reproducible example I've found so far is the klay layout demo: https://cytoscape.github.io/cytoscape.js-klay/

If you make the window as big as possible (at least 1200x1000 for the viewport) and zoom out (past zoom:0.25), the nodes will disappear.

I'm not sure how to reproduce this as a minimal example yet to report this on the Chromium issue tracker: https://bugs.chromium.org/p/chromium/issues/list

Notes:

- From playing around with the renderer code, I've found that setting the canvas transform values (to the exact same values) [here](https://github.com/cytoscape/cytoscape.js/blob/v3.2.8/src/extensions/renderer/canvas/layered-texture-cache.js#L323) helps with some cases but not others -- though what is essentially a nop shouldn't have any effect at all.
- It seems there also may be an issue when [`cxt.drawImage()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) is used with the form `ctx.drawImage(image, sx, sy, sWidth, sHeight, dx, dy, dWidth, dHeight)` -- though again, this happens sometimes and sometimes not.
- It seems to fail when you have the chain `off-screen canvas => off-screen canvas => on-screen canvas`.  But our uses of `off-screen canvas > canvas` seem OK.  Both use the above signature of `cxt.drawImage()`.  N.b. this isn't `OffscreenCanvas` but just a `Canvas` not in the DOM tree.
- I've stepped through the code and identified [the main `drawImage()` that seems to fail](https://github.com/cytoscape/cytoscape.js/blob/v3.2.8/src/extensions/renderer/canvas/layered-texture-cache.js#L324).  I've verified that the source image (`cache.texture.canvas`) that is drawn on `context` is as expected, so it seems Chromium just doesn't draw the image properly.
- Disabling GPU acceleration on canvas in `chrome://flags` makes the issue in the Klay demo not visible anymore: `chrome://flags/#disable-accelerated-2d-canvas`
- On a 2011 Macbook Pro (A1286, Mac 10.12, 2.2 GHz Intel Core i7, 16 GB 1333 MHz DDR3, Intel HD Graphics 3000 512 MB), the issue does not occur on the Klay demo when the discrete (ATI 6750M) graphics card is disabled with [gfxCardStatus](https://github.com/steveschow/gfxCardStatus) while `chrome://flags/#ignore-gpu-blacklist` is enabled.  Maybe for this case, Chrome isn't actually using acceleration on the integrated graphics.  Or maybe the Intel HD Graphics 3000 is handled differently by Chrome in some other way.
- Last resort: I can disable all `drawImage()` calls that seem to be problematic in Chromium 64, but this will mean greatly reduced performance for Chromium/Chrome users.  It could be dev-controllable with a flag.  A Chromium-64-only workaround would be preferable.

**Comment by maxkfranz** [comment]
It looks like the Chromium guys may have sorted out the issue.  The [cytoscape-klay demo](https://cytoscape.github.io/cytoscape.js-klay/) does have its node disappear at low zoom levels in Chrome Canary 66 (`Version 66.0.3342.0 (Official Build) canary (64-bit)`).

**Comment by maxkfranz** [comment]
Newer releases of v64 look like they also fix the issue, e.g. `Version 64.0.3282.140 (Official Build) (64-bit)` on Mac.

**Comment by maxkfranz** [comment]
From the [changes](https://chromium.googlesource.com/chromium/src/+log/64.0.3282.119..64.0.3282.140?pretty=fuller&n=10000), it looks like the issue was resolved by one of these:

- [24f4c0b20d9ebbcd12a527cda8c9b4bd11d2ba9d](https://chromium.googlesource.com/chromium/src/+/24f4c0b20d9ebbcd12a527cda8c9b4bd11d2ba9d) Revert "Fix perf regression on replacing AcceleratedImageBufferSurface with CanvasResourceProvider"
- [0186bfee26ca0bc9d6eff1e80203f84319aec437](https://chromium.googlesource.com/chromium/src/+/0186bfee26ca0bc9d6eff1e80203f84319aec437) Fix performance regression in putImageData

**Comment by maxkfranz** [comment]
The CoSE demo is another example: http://js.cytoscape.org/demos/cose-layout/

**Comment by maxkfranz** [comment]
Chrome 64.0.3282.167 on Mac does not exhibit the bad rendering on the Klay demo.

**Comment by tswcode** [comment]
There is another strange behaviour with Chrome Version 64.0.3282.167 (64-bit).
No matter which cytoscape canvas, e.g. http://js.cytoscape.org/demos/cose-layout/ ,
when I switch browser tabs or window for some seconds and switch back to this tab with the canvas,
then the canvas is empty. 

When I try to redraw it using 
`$(window).focus(function() { cy.fit( 50 ); }` 
only the edges are shown.

**Comment by maxkfranz** [comment]
@tswcode I can't reproduce this on my Mac (Intel graphics).  But I do see something similar on my Linux machine (Nvidia 1070) -- the whole graph disappears when I switch back to the tab.

What OS and graphics card are you using?

**Comment by tswcode** [comment]
I am using Linux as well: Nvidia gtx960, Gentoo x64, Xorg.

**Comment by maxkfranz** [comment]
Are you using the Nvidia proprietary driver or Nouveu?  I'm using the proprietary driver.

**Comment by tswcode** [comment]
I also am using proprietary driver.

**Comment by finger563** [comment]
I'm also seeing this on Linux with Nvidia GTX 1080 and proprietary drivers - clicking within the canvas shows some nodes / edges from the canvas randomly

**Comment by finger563** [comment]
specifically when I switch tabs - every time i go to another tab and then back to the tab with cytoscape my nodes have disappeared or are incompletely shown

**Comment by maxkfranz** [comment]
That's unfortunate.  I hoped that the Chrome team would have resolved this with recent updates.

Would someone affected by this issue be able to file a bug report with the Chrome team and link to the report here?

**Comment by ugurdogrusoz** [comment]
Interestingly, according to our experience, the graph in the navigator extension (overview window) is always rendered properly (both nodes and edges).
