### ISSUE TITLE
Opacity of child node is not updated for certain zoom levels after parent opacity is overridden 

### ISSUE THREAD

**Issue by joeybrk372** [cytoscape/cytoscape.js#2078]
**Issue type**
Bug report

**Environment info**
- Cytoscape.js version : 3.2.10, 2.7.28
- Browser

**Current (buggy) behaviour**
Opacity of child nodes are not updated at certain zoom levels after parent opacity is overriden via `ele.style('opacity', ...`

**Desired behaviour**
If parent opacity is changed all childrens' opacities should be updated for all zoom levels

**Minimum steps to reproduce**
[jsbin](https://jsbin.com/kogucex/7/edit?js,output), click the button then zoom

**Comment by maxkfranz** [comment]
Notes:

- I've confirmed that the patch corrects the errant behaviour described by @joeybrk372, using the jsbin as a test case.
- This patch is not necessary to the unstable branch (for v3.3.0) as the caches will not take into consideration the overall `opacity` property.
- This patch may reduce performance of compound graphs.  I've tried to keep the effect minimal, but I don't have time to thoroughly test this.
- This should serve as an example for why we should not add more parent-inherited properties in future releases.

**Comment by maxkfranz** [comment]
@joeybrk372, would you please build the master branch and try it in your app to confirm?

My local build of 84f2965: [build.zip](https://github.com/cytoscape/cytoscape.js/files/1826259/build.zip)

**Comment by joeybrk372** [comment]
Yep, tried it out with your changes and opacity is updating correctly now.

**Comment by maxkfranz** [comment]
Great.  3.2.11 will be released on Thursday.
