### ISSUE TITLE
When using Polymer, buttonless mouse events do not fire.

### ISSUE THREAD

**Issue by csmatt** [cytoscape/cytoscape.js#2081]
**Issue type**

Bug report

**Environment info**
Chrome and Firefox

- Cytoscape.js version : latest
- Browser/Node.js & version : all

**Current (buggy) behaviour**

'mouseover' and 'mouseout' events are not fired when moving the cursor over and away from nodes.

**Desired behaviour**

'mouseover' and 'mouseout' events should be fired.

**Minimum steps to reproduce**

The following demonstrates the issue http://plnkr.co/edit/MQgypP9A16Lshg3UkzOK?p=preview
'click' and 'mousedown' events seem to work fine, but mouse events that are not button presses do not seem to trigger the event.

**Comment by maxkfranz** [comment]
I'm not convinced that this is an issue with Cytoscape.js.  It looks like you may need to set up Polymer to properly support events, [as it seems Polymer doesn't support this out of the box](https://www.polymer-project.org/2.0/docs/devguide/events#listener-on-outside-elements).

[Cytoscape.js listens to events on `window`](https://github.com/cytoscape/cytoscape.js/blob/84f2965621942195fa6298e3ac442a2b0e5e80eb/src/extensions/renderer/base/load-listeners.js) to give the sort of experience that users expect.  This approach was decided on based on testing and feedback over many releases of Cytoscape.js.  That is not something that can be changed without serious consideration.

**Comment by csmatt** [comment]
Thanks for your quick reply. I was able to get it working by setting cy.renderer().hoverData.capture to true.

I tried for a long time to get eventInContainer() to return true, but when the event comes in (through the mousemove handler), it's target is the webcomponent rather than the canvas. I'm guessing that's Polymer's fault and not cytoscape's.

**Comment by maxkfranz** [comment]
Is there a hierarchical relationship between the `container` and the `target` (i.e. the polymer component)?

**Comment by csmatt** [comment]
There is a hierarchical relationship, but when I set the breakpoint inside cytoscape's 'mousemove' handler, it shows the target as 'custom-element' rather than 'canvas' even thought 'canvas' exists in path. It's almost like it can't see anything in the shadow dom.
