### ISSUE TITLE
removeListener with handler

### ISSUE THREAD

**Issue by sjneph** [cytoscape/cytoscape.js#2089]
Bug report

Fedora 27
cytoscape 3.2.11 via npm
Firefox

The following code should remove the mouseover listener when the context menu + star selection is chosen an even number of times.  This does use the cytoscape-cxtmenu extension, but I believe it is a core issue.

When the 'mouse_handler' parameter is removed on on line 56 in the attached, things behave as expected (removing all mouseover handlers).

[bugreport.txt](https://github.com/cytoscape/cytoscape.js/files/1893091/bugreport.txt)

**Comment by maxkfranz** [comment]
Could it be you've misplaced the scope of `mouseover_handler`?  It seems to me that `mouseover_handler` would be reference to a new function each time your `select()` is called.  In that case, you're not removing any handler at all based on your `if`.

**Comment by maxkfranz** [comment]
If not, it would be good to identify a minimal test case (without extensions) that could be added to the test suite.

**Comment by sjneph** [comment]
That appears to be exactly the case - sorry for the trouble and thanks for the help!
