### ISSUE TITLE
Transitions can spam z-index sorting in 2.7.x

### ISSUE THREAD

**Issue by pcurrivan** [cytoscape/cytoscape.js#2095]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 2.7.18 through 2.7.29, 3.0.1
- Browser/Node.js & version : any

**Current (buggy) behaviour**

Browser hangs during node size transitions in large graphs. z-index sorting is getting spammed due to style events. 

**Desired behaviour**

Should be fast

**Minimum steps to reproduce**
I believe it happens if height/width transitions are enabled and you change sizes in a way where nodes will overlap during the transition.
Fiddle: https://jsfiddle.net/95ahvn6v/2/
If you change the cytoscape version to  2.7.17 or lower the issue goes away (perhaps related to #1793 ?)
Version 3.0.1 is slow as well.  The latest version of Cytoscape 3 is faster. (maybe backporting #1340 would help?)

**Comment by maxkfranz** [comment]
2.x is updated only for very small bug fix changes.  Unfortunately, we can not afford the resources to maintain two different APIs for Cytoscape.js with the latest and greatest changes in both.  Eventually, 2.x will be retired altogether -- 2.x has so far received fixes for about a year after the release of 3.0.

You may want to consider updating to the latest version of Cytoscape.js, which has both the fast behaviour that you're looking for and the correct behaviour w.r.t. z-ordering.  There are instructions on upgrading in the blog, '[Announcing Cytoscape.js 3.0.0](http://blog.js.cytoscape.org/2017/04/11/3.0.0-release/)'.

See also '[The future of Cytoscape.js 2.x](http://blog.js.cytoscape.org/2017/04/11/2.x-maintenance/)'.

**Comment by maxkfranz** [comment]
Closing, as v2.x is no longer maintained
