### ISSUE TITLE
Animation of percent property values (e.g. pie charts) not working

### ISSUE THREAD

**Issue by ortega2247** [cytoscape/cytoscape.js#2099]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.11
- Browser/Node.js & version : 59.0.2

**Current (buggy) behaviour**

When there is a queue of animations to change the pie-1-background-size of a node, this pie-1-background-size doesn't change accordingly with the values set in the animation

**Desired behaviour**

pie-1-background-size should change accordingly with values set in the animation

**Minimum steps to reproduce**
https://jsbin.com/pojicus/edit?html,css,js,output

**Comment by maxkfranz** [comment]
@ortega2247 b253f95 should resolve the bug itself.  However, be aware that it is invalid to specify percent totals greater than 100%.  I tested on a modified version of your demo that used `[20%, 10% -> 50%]` instead.

**Comment by maxkfranz** [comment]
3.2.12 will be released on Thursday 3 May.
