### ISSUE TITLE
Option to disable multi selection entirely

### ISSUE THREAD

**Issue by davidhockey22** [cytoscape/cytoscape.js#2101]
**Issue type**

Feature request

**Description of new feature**

Add an option to disable multi selection of nodes/edges. Perhaps 'multiselectionEnabled' with a default to true. 

**Motivation for new feature**
When integrating with other tools allowing a user to change the settings of specific nodes/edges, it's beneficial to only have one selection at a time so the UI only needs to show one property panel.

**Comment by maxkfranz** [comment]
In 3.2, wouldn't doing something like `cy.on('select', 'node, edge', e => cy.elements().not(e.target).unselect())` suffice?

**Comment by davidhockey22** [comment]
From what I can tell, programmatically setting a node to selected does not trigger this select event though. For instance, if I create a new node and mark it selected as part of the node creation it does not call the event, which adds more edge cases. 

I am doing what you describe as well though for my other cases. 

The change for removing multi selection seems minor since there's already a check for both additive and multSelKeyDown. Adding a property that makes this function isMultSelKeyDown return false in load-listeners.js seems like it would handle this.

**Comment by maxkfranz** [comment]
It's not clear to me what you're asking for.

The first case you mention has to do with API and model-level restrictions.  There are no restrictions on selection in the model other than `selectable()`, which the dev can toggle as needed.  This keeps the model simple and flexible.

The second case you mention has to do with user (i.e. gesture) restrictions on the renderer-level.  All of the "click the background to deselect", "click another node to deselect the old one", etc. rules are defined in the renderer.  Those rules don't apply to anything created or mutated with the API.

It sounds like you should also be listening to the `add` event then.  Adding an element never mutates selection state -- it doesn't exist in the graph yet.

Also note that there are plans to remove `selectionMode: 'additive'` for v4.  I think things like that should be extensions.  Unfortunately, it's not for now for historical and compatibility reasons.
