### ISSUE TITLE
Add line-height to font styling

### ISSUE THREAD

**Issue by Akos9205** [cytoscape/cytoscape.js#2115]
**Issue type**

Feature request

**Description of new feature**

Add line-height to basic font styling possibilities:

**`line-height`** : The line height of multiline text, as a relative, unitless value.  It specifies the vertical spacing between each line.  With value `1` (default), the lines are stacked directly on top of one another with no additional whitespace between them.  With value `2`, for example, there is whitespace between each line equal to the visible height of a line of text.

 

**Motivation for new feature**

If a node label consist of multiple lines and the first line contains an underscore "_" character, then it is mixed/covered with the second line, the "_" character touches the text in the line below. 

![cyto](https://user-images.githubusercontent.com/7621826/40069614-24e4ad36-586c-11e8-99a0-b9f562e0ef17.png)

Example of actual usage:
The label is added the following way: node.data('label', line_1 + '\n' + line_2);
And the 'text-wrap' is set to 'wrap'.

**Comment by maxkfranz** [comment]
Here is an example of the feature.  Note that `line-height` has no effect on single line labels, i.e. values other than `text-wrap: wrap`.  The bounds of the text are highlighted in cyan with the `text-background-color`.  Varying `line-height` values are shown with example text that includes both ascenders and descenders.

`text-wrap: none`:

![Screen Shot 2019-04-24 at 3 46 20 PM](https://user-images.githubusercontent.com/989043/56689330-d83e2100-66a8-11e9-8a36-6f4c0d82b0d0.png)

`line-height: 1`:

![Screen Shot 2019-04-24 at 3 43 54 PM](https://user-images.githubusercontent.com/989043/56689357-e5f3a680-66a8-11e9-8f31-c06b2b4eec67.png)

`line-height: 1.5`:

![Screen Shot 2019-04-24 at 3 43 40 PM](https://user-images.githubusercontent.com/989043/56689376-ef7d0e80-66a8-11e9-9505-5b5c68c0e8d1.png)

`line-height: 2`: 

![Screen Shot 2019-04-24 at 3 44 09 PM](https://user-images.githubusercontent.com/989043/56689390-f60b8600-66a8-11e9-8ce2-4898c94abfc9.png)
