### ISSUE TITLE
Custom tie breaking algorithm for dijkstra

### ISSUE THREAD

**Issue by raae** [cytoscape/cytoscape.js#2117]
Feature request

**Custom tie breaking algorithm for dijkstra**
It is possible to submit a custom weight function. It could be helpful to be able to submit a custom tie breaking algorithm as well. Now it seems the implementation picks the first shortest distance edge it encounters, but this could then be customized.

**Motivation for new feature**
I am creating a product where this is needed. We need dijkstra to simulate the choices the routers in a network are doing. The routers pick the shortest distance edge with the lowest interface id.

I could contribute with a solution if it would be something you would be interested in.

**Comment by maxkfranz** [comment]
I understand your usecase, but couldn't the same be achieved numerically?

```
weight: edge => edge.data('weight') + epsilon * interfaceIdAsInt(edge)
```
