### ISSUE TITLE
`text-overflow-wrap: whitespace | anywhere`

### ISSUE THREAD

**Issue by weirdalsuperfan** [cytoscape/cytoscape.js#2119]
**Issue type**

Feature request

**Specification**

**`text-overflow-wrap`** : The characters that may be used for possible wrapping locations when a line overflows `text-max-width`; may be `whitespace` (default) or `anywhere`.  Note that `anywhere` is suited to [CJK](https://en.wikipedia.org/wiki/CJK_characters), where the characters are in a grid and no whitespace exists.  Using `anywhere` with text in the Latin alphabet, for example, will split words at arbitrary locations.

**Motivation**

See OP below:

-- 

**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.1.4
- Browser/Node.js & version : Chrome Browser Version 66.0.3359.117 (Official Build) (64-bit)

**Current (buggy) behaviour**

Japanese, or other text without spaces, won't wrap even with 'text-wrap' or 'overflow-wrap' or 'word-break' set

**Desired behaviour**

Wrap after text-max-width even without spaces, or at least follow word-break CSS.

**Minimum steps to reproduce**
http://jsbin.com/yikurinezu/edit?html,css,js,output

**Comment by maxkfranz** [comment]
Proposal : 

`text-wrap: anywhere` : Wrap on manual newline characters, or wrap on any character beyond `text-max-width`.

This should work for languages that don't use much if any whitespace.

**Comment by maxkfranz** [comment]
Similar to #2329, you should probably be using [zero-width spaces](https://en.wikipedia.org/wiki/Zero-width_space) between characters where you'd like to enable wrapping.

I suppose an implementation of `text-wrap: anywhere` would just put '\u200b' between every character in your input string, but you should be able to do that in your code in the same way using a style mapper function.

**Comment by maxkfranz** [comment]
Note that breaking on zero-width spaces is currently not supported, since it's not included in `\s`.

**Comment by maxkfranz** [comment]
<img width="129" alt="Screen Shot 2019-04-05 at 5 48 00 PM" src="https://user-images.githubusercontent.com/989043/55658257-ffe94a00-57ca-11e9-94a5-bc07269efdb1.png">

This is pretty much the best it can be with an `anywhere` value.  Note, however, that punctuation or other symbols can not be taken into account.  There are too many languages to consider.  In the example above, the end parenthesis isn't well placed on the fifth line.

To have more control over where breaking happens, you'll have to use zero-width spaces as hints in your text at appropriate locations -- e.g. not before ")".
