### ISSUE TITLE
cy.style().json() background-width/height misses "%" in value

### ISSUE THREAD

**Issue by emelendez** [cytoscape/cytoscape.js#2121]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.12

**Current (buggy) behaviour**
When I tried to get the JSON format of the actual style: cy.style().json()
I discovered that initial "background-width": "70%" was transformed into "background-width": "70".
So, in this case, I needed to add new "JSON" style to the actual style and I tried to concat new JSON to the actual JSON, but I saw that actual JSON was modified from initiation.

**Comment by maxkfranz** [comment]
If you pass `70` to a property that is implicitly specified in percent units, then it is interpreted the same as `70%`.   It should make no difference.

**Comment by emelendez** [comment]
sorry, but applying "70" again is reinterpreted as "70px" by default, not "70%" as in the original JSON style.

**Comment by maxkfranz** [comment]
You're right.  When I looked back at this issue, I scanned it too quickly and thought it was for the pie properties.  The commit should address this for 3.2.13

**Comment by emelendez** [comment]
your work is awesome!!!
