### ISSUE TITLE
Deprecate `cy.collection( val )`

### ISSUE THREAD

**Issue by mikpom** [cytoscape/cytoscape.js#2126]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.12
- Browser/Node.js & version : Firefox 60.0.1 (64-bit)/ Chromium 66.0.3359.181

**Current (buggy) behaviour**

Edges returned by `cy.add` are different from those return by `cy.getElementByID` and, for example, can't be converted to collection object.

**Desired behaviour**

Should be consistent.

**Minimum steps to reproduce**

Here is the fiddle https://jsfiddle.net/x23gyf1s/

**Comment by maxkfranz** [comment]
From the docs:

> cy.collection( elesArray )
> Get a collection from an array of *elements*.

You've passed an array of *collections*.  The distinction is subtle, so it's easy to make that mistake.  Your code would mean "create a collection that itself is composed of one or more collections".  Collections and elements are nearly (at least externally) identical w.r.t. API.  It looks like `cy.collection( elesArray )` makes things confusing.

It is not necessary for your code to call `cy.collection()`.

I'm deprecating `cy.collection( val )` in 3.2.13.  It will no longer be in the docs to make things simpler.

**Comment by maxkfranz** [comment]
The only really useful case of `cy.collection()` is with no args to create an empty collection.  This will remain.

**Comment by mikpom** [comment]
I understand the behavior now.

More general question then would be: if I iteratively create collections with `cy.add` and then want to join them, what is the efficient way to do that? I imagine I could create an array of collections and then do `array.reduce` with `eles.union`. But won't it create unnecessary intermediate unions in memory?

**Comment by maxkfranz** [comment]
For most cases, it's fine to just `eles = eles.union( newEles )`.

If you profile your app and you find that `.union()` is too slow, you could start with an empty `cy.collection()` and `.merge()` into it.  You have to be careful with `.merge()`, as normally collections are considered to be immutable.

**Comment by mikpom** [comment]
Many thanks for sensible reply!

I was looking for something named like `push` and missed the `merge` function.
