### ISSUE TITLE
Cors filter on Background image

### ISSUE THREAD

**Issue by marcoromano91** [cytoscape/cytoscape.js#2127]
Hi,

I have the following error when I tried to load the following thumbnail recovered from dbpedia in the background-image of the node.

attribute:
`'background-image': 'http://commons.wikimedia.org/wiki/Special:FilePath/Luigi_Di_Maio_daticamera.jpg?width=300',`

Error:
`Redirect from 'https://commons.wikimedia.org/wiki/Special:FilePath/Luigi_Di_Maio_daticamera.jpg?width=300' to 'https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Luigi_Di_Maio_daticamera.jpg&width=300' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

From the cytoscape manual I have already seen that is possible to set the following property:
`background-image-crossorigin: All images are loaded with a crossorigin attribute which may be anonymous or use-credentials. The default is set to anonymous.`
I have tested it with both arguments but it not working.

Any suggestion to help me? I already know that the link passed is not the real but I recovery it from a sparql query.

Thanks in advance.
Marco

**Comment by franklarryx** [comment]
Any news about this issue?
I have the same problem!

Thanks,
Frank

**Comment by maxkfranz** [comment]
Possibilities:

(1) You're not running an HTTP server.

(2) You're hotlinking images, and Wikimedia might be blocking that.
