### ISSUE TITLE
Filter for Zoom

### ISSUE THREAD

**Issue by janithmehta** [cytoscape/cytoscape.js#2131]
**Issue type**
Feature request

**Description of new feature**
Before 'zoom' is started, cytoscape checks whether the user provided variable is true or false. Similar to what d3.zoom.filter does. If the user provided variable is set to false, cytoscape automatically prevents zoom.
Or the ability to set an event on 'mousewheel up/down'

**Motivation for new feature**

https://github.com/d3/d3-zoom#zoom_filter

**Comment by maxkfranz** [comment]
For this usecase, doesn't this suffice?

http://js.cytoscape.org/#cy.zoomingEnabled

**Comment by janithmehta** [comment]
The d3.zoom.filter has a constant listener for value changes. So if I dynamically set the value to false, zooming is disabled. I used the javascript 'wheel' event, but since zooming is enabled at that time, it zooms 1 level before disabling zoom (using cy.zoomingEnabled). So before the zooming starts, I need to be able to check for the flag value

**Comment by maxkfranz** [comment]
That sounds a lot like using a `Proxy` on your model object and then setting the zoom-enabled state in `handler.set()`.  That's a built-in feature of the language.

If you would like to make a PR for the boolean toggle functions to accept functions, that would be great.

**Comment by janithmehta** [comment]
@maxkfranz I would've loved to do it, but don't have time at the moment
