### ISSUE TITLE
Use relative path for node background-image

### ISSUE THREAD

**Issue by IvyBerry** [cytoscape/cytoscape.js#2132]
The "Images & breadthfirst layout" - Example introduces background-images for nodes.
As it is common practice to deliver web apps with assets, I'd like to reference these in a manner like this:

```
    cy.style().selector('#nodeId')
        .css({
            'background-image': 'assets/background1.png'
        });
    cy.style().update();
```

Unfortunately it does not work. After several hours of google & try- anyone did this before and could offer some advice? Grateful for any advice. Kind regards

**Comment by maxkfranz** [comment]
You need to run an HTTP server.  You can't use `file://`
