### ISSUE TITLE
Adding elements to graph inside 'render' event callback

### ISSUE THREAD

**Issue by MatthijsBon** [cytoscape/cytoscape.js#2133]
**forceRender not working**
Bug report

**Environment info**

- Cytoscape.js version : 3.2.13
- Browser/Node.js & version : Chrome

**Current (buggy) behaviour**
When using ``cy.one('render', callback)``, callback is called directly upon rendering, but if elements are added inside this callback, these are only rendered to the graph when clicking on the map, even if ``forceRender()`` is called inside the callback.

**Desired behaviour**
I think ``forceRender()`` should at least actually rerender the page. When logging ``cy.renderer()`` and then calling ``renderer.redraw()`` from the console, canvas is rerendered and elements are shown as well. Then, why is ``forceRender()`` not working?

**Note:**
I was using a listener on render callback, because originally I wanted to add a node for every midpoint of an edge. But since the midpoint position is ``{x: undefined, y: undefined}`` before graph is fully rendered, this did not work. If there is a better (or work around) solution for this behavior, that would be fine as well.

**Minimum steps to reproduce**
https://jsfiddle.net/wx0a2y5d/166/

**Comment by MatthijsBon** [comment]
I've tested with several timeout functions and found that apparently, forceRender() is not working inside the 'render' event callback, probably to not cause any loops.

**Comment by maxkfranz** [comment]
There are very few usecases where it is necessary to use the render event.  An example usecase is having an overlay that you want synched to frames of the graph.

There are even fewer usecases where it is necessary to use the `forceRender()` function.  I think it was added for an extension, given prior limitations of the renderer.  I don't think those limitations exist anymore, so `forceRender()` should be deprecated and removed from the docs.

You should be using `add` and `position` events instead.
