### ISSUE TITLE
`ani.play()` doesn't loop/auto-rewind

### ISSUE THREAD

**Issue by janithmehta** [cytoscape/cytoscape.js#2135]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version : 3.2.12
- Browser/Node.js & version : 9.6.2

**Current (buggy) behaviour**
`ani.play()` isn't looping/auto-rewinding on completion of the animation

**Desired behaviour**
As mentioned in the documentation - http://js.cytoscape.org/#ani.play . The animation should start from the begging once its over.
Even the source code mentions _auto-rewind_ as a comment in the `play()` function - https://github.com/cytoscape/cytoscape.js/blob/master/src/animation.js 

**Minimum steps to reproduce**
[Demo](https://jsbin.com/pinobigelo/edit?html,output)

As you can see that on clicking 'Add Animation' the animation is not looping

**Comment by maxkfranz** [comment]
The animation does rewind.  But just like a VCR, rewinding doesn't mean that starts playing again.

You need to call `play()` again, after it finishes -- a recursive call made by the promise being fulfilled.
