### ISSUE TITLE
Cannot perform `removeClass('')` for edge

### ISSUE THREAD

**Issue by bdparrish** [cytoscape/cytoscape.js#2137]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.12
- Browser/Node.js & version :  Chrome 67.0.3396.79

**Current (buggy) behaviour**

Iterating over edges to change the class on the edge will work as expected when executing `addClass('')`, but it does not work when executing `removeClass('')`.  I would expect the class to remove styling from that class, but the styling remains.  `toggleClass('')` works for the same manner, I would assume I could use these synonymously.

**Desired behaviour**

I would expect that the edge sets styling for the correct styling with the class removed.

**Minimum steps to reproduce**

Cytoscape styles
```javascript
            {
                selector: '.highlighted-edge',
                css: {
                    'width': 3,
                    'line-color': '#66FF33',
                    'target-arrow-color': '#66FF33',
                    'target-arrow-shape': 'triangle'
                }
            }
```

Toggle code
```javascript
        this.cytoscape.edges().forEach((ele) => {
            (ele as any).addClass('highlighted-edge');
        });

// ----- OR

        this.cytoscape.edges().forEach((ele) => {
            (ele as any).removeClass('highlighted-edge');
        });
```

**Comment by maxkfranz** [comment]
I did this in the Chrome debug console on the debug page for master, and I got the expected results:

```
add = ele => ele.addClass('highlighted-edge')
cy.edges().forEach(add)
rm = ele => ele.removeClass('highlighted-edge')
cy.edges().forEach(rm)
```

**Comment by bdparrish** [comment]
Ok.  Closing the issue.
