### ISSUE TITLE
Change Cursor to Pointer For Some Nodes

### ISSUE THREAD

**Issue by ankita199** [cytoscape/cytoscape.js#2143]
Hi,
I want to change Cursor to Pointer when user hover on particular node (where click event is binded). But it is not working for me. I tried this code
` this.cy.on('mouseover', 'node', () => this.cy.$(`#${nodeId}`).addClass('mouseover'));`

but it is not working for me.

**Comment by maxkfranz** [comment]
There is no cursor style property.

**Comment by smith** [comment]
If you want to do this you can change the property on the container:

```js
cy.on('mouseover', (event) => {
  if(event.cy.container()) {
    event.cy.container().style.cursor = 'pointer';
  }
}

cy.on('mouseout', (event) => {
  if(event.cy.container()) {
    event.cy.container().style.cursor = 'default';
  }
}
```
