### ISSUE TITLE
Tweaks to improve style application performance

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#2145]
**Issue type**

Feature request

**Description of new feature**

Make tweaks to the styler in order to improve style application performance, especially at element creation during initialisation.

- [x] `Stylesheet.prototype.style()` iterates over `Object.keys(passedStyleJson)` rather than `Style.properties`.
- [x] Check for mapper updates only to the list of currently-active properties.
- [x] Iterate over existing style properties in the element for element cleaning on applying a new stylesheet, instead of iterating over all possible props.
- [x] Improve performance of style property parsing by using cheap heuristics to avoid regex mapper checks
- [x] Cache default properties without `memoize()`
- [x] Slightly cheaper checks in `ele.isSimple()` and `ele.isLoop()`
- [x] Document how to start from an empty stylesheet
- [x] Refactoring of `Selector`, esp. w.r.t. matching

**Motivation for new feature**

Faster init time and faster style changes

**Comment by JohnHadish** [comment]
I'm excited for this one. I make way too many styles and then it takes 8 minutes to load my network next time I open it. Thank you for working on improving this!
