### ISSUE TITLE
Transition Animations not being applied to different properties on the same node

### ISSUE THREAD

**Issue by janithmehta** [cytoscape/cytoscape.js#2148]
**Issue type**
Bug report

**Environment info**
- Cytoscape.js version : 3.2.13
- Browser/Node.js & version : Chrome

**Current (buggy) behaviour**
If transition animations are applied to different properties to the same node (in different classes), the transition animation doesn't occur 

**Desired behaviour**
The transition animations should be applied to all the properties

**Minimum steps to reproduce**
Here is the  [demo](https://jsbin.com/zomeved/edit?output)
The buttons change the background-color and size (width & height) properties. 

1. Click on 'Change Properties 1' and then 'Apply Properties' - Works fine on initial run. 
2. Click on 'Change Properties 2' and then 'Apply Properties' - Only the 'color' transition works, not the 'size' 
3. Click on 'Change Properties 3' and then 'Apply Properties' - The size changes, no transitions.

PS - 'Change Properties 3' only changes the size, not the color. The other 2 change both the size and color.

**Comment by maxkfranz** [comment]
There are several errors in your demo.  You can see that the (forward) transition animation works for multiple properties in this demo: https://jsbin.com/wijeqejasa

**Comment by maxkfranz** [comment]
@janithmehta Though the transition animations use the same underlying animation routines, I've added some explicit tests to confirm that the feature works as intended.  (The unstable branch is currently failing unrelated tests due to ongoing work.)  If you have a case where the feature fails, please feel free to re-open the ticket.
