### ISSUE TITLE
Wzrd not able to bundle the latest version(3.2.14)

### ISSUE THREAD

**Issue by Megh-Thakkar** [cytoscape/cytoscape.js#2154]
**Bundle error**

Bug report

The latest version ([3.2.14](https://wzrd.in/bundle/cytoscape@3.2.14)) is not getting bundled by wzrd whereas version [3.2.12](https://wzrd.in/bundle/cytoscape@3.2.12) is. I am working on the biojs registry and would be requiring the bundle to display the snippets. Please have a look.

**Comment by maxkfranz** [comment]
What do you get for `npm ls browserify`?

**Comment by maxkfranz** [comment]
Alternatively, you can use CDNJS if you want a browser-ready bundle for a particular version: https://cdnjs.com/libraries/cytoscape

Or if you always want the latest version (or a semver pattern), you can use Unpkg: https://unpkg.com/cytoscape/dist/cytoscape.min.js

**Comment by maxkfranz** [comment]
Lodash doesn't load on that wzrd cdn either: https://wzrd.in/bundle/lodash@4.17.10

Perhaps the site itself is broken.
