### ISSUE TITLE
Loop Element?? 

### ISSUE THREAD

**Issue by richiewang4528** [cytoscape/cytoscape.js#2161]
![15320696](https://user-images.githubusercontent.com/4962698/42987971-908312e0-8c2d-11e8-8ee4-e14c912389f4.png)

I have a little worry for this.  May be need a clone when  assign value
eg.  object.Element = Object.assign({}, Element)

**Comment by maxkfranz** [comment]
You shouldn't be using `Object.assign()` with objects that are instantiated from a prototype.
