### ISSUE TITLE
Removing text from edge's label keeps background visible

### ISSUE THREAD

**Issue by PeBraz** [cytoscape/cytoscape.js#2164]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.15
- Browser & version:
  - Chrome 68.0.3440.84
  - Firefox 61.0.1 

**Current (buggy) behaviour**

Removing an edge's label, by edge.data(), does not remove that label's background, if that edge has text-wrap with value *wrap*.

**Desired behaviour**

The label's background should have the same behavior as if there was no wrap and disappear.

**Minimum steps to reproduce**
https://jsfiddle.net/zc3k1f48/42/

**Comment by maxkfranz** [comment]
@PeBraz You can verify whether the fix works for you by building off of master.

**Comment by PeBraz** [comment]
Just tried it, works great!
