### ISSUE TITLE
`line-dash-offset` and `line-dash-pattern` edge style properties

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#2166]
**Issue type**

Feature request

**Description of new feature**

 * **`line-dash-pattern`** : The `dashed` line pattern which specifies alternating lengths of lines and gaps. (e.g. `[6, 3]`).
 * **`line-dash-offset`** : The `dashed` line offset (e.g. `24`). It is useful for creating edge animations.

**Motivation for new feature**

(1) Custom dashed edges.  An app may use different patterns to represent meaning, similar to how colour is often used.

(2) Animations to show edge direction or highlight along part of an edge.

![marching-ants](https://user-images.githubusercontent.com/989043/43916211-ed2fef92-9bda-11e8-8d92-f30b981266ec.gif)

![beam](https://user-images.githubusercontent.com/989043/43916216-f02d933e-9bda-11e8-9dd7-7e569e2c17ae.gif)

**Comment by maxkfranz** [comment]
Ref #2163

**Comment by maxkfranz** [comment]
Ref https://github.com/cytoscape/cytoscape.js/issues/2160

**Comment by manotoor** [comment]
@maxkfranz Interested in #2. animation to show edge direction.
I tried looking online wasn't able to find it. Any suggestions on how to achieve this?
