### ISSUE TITLE
Source and target labels use `text-rotation` rather than `source-text-rotation` and `target-text-rotation` for display

### ISSUE THREAD

**Issue by willbeaufoy** [cytoscape/cytoscape.js#2167]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.15
- Browser version : 
  - Chrome 68.0.3440.84
  - Firefox 52.8.1

**Current (buggy) behaviour**

Source and target labels on edges are truncated if text is rotated 90 degrees. The truncation happens on load, and after zoom or pan. Clicking on a node restores the full labels.

It seems as though the labels are truncated when they fall outside a box formed by the connecting nodes and the main edge label.

**Desired behaviour**

Source and target labels on edges should be fully visible at all times.

**Minimum steps to reproduce**

https://jsfiddle.net/zc3k1f48/58/

**Comment by maxkfranz** [comment]
The bounds are correct.  It's the display that's wrong.  You've specified rotation for the main label, and the same rotation is erroneously applied to the source and target labels for display.  The correct properties are being used for bounds.  The prefixed style properties should be used (e.g. `source-text-rotation`).

*This has the correct bounds but wrong display (unfixed):*

![screen shot 2018-08-14 at 3 01 47 pm](https://user-images.githubusercontent.com/989043/44112422-11b09866-9fd3-11e8-8e17-9158fe37dc2b.png)

With the properties aligned and with the bounds indicated by the cyan overlay:

*This is what you've specified:*

![screen shot 2018-08-14 at 2 53 34 pm](https://user-images.githubusercontent.com/989043/44112266-a2864f4e-9fd2-11e8-855b-cc96a6af43eb.png)

*This is what you intended:*

![screen shot 2018-08-14 at 2 54 08 pm](https://user-images.githubusercontent.com/989043/44112276-a8b1b76e-9fd2-11e8-832c-8395a522ea21.png)

**Comment by maxkfranz** [comment]
@willbeaufoy You can verify whether this works for you by building off of master.

**Comment by willbeaufoy** [comment]
Great, thanks.
