### ISSUE TITLE
Slow style rendering for large graphs

### ISSUE THREAD

**Issue by janithmehta** [cytoscape/cytoscape.js#2169]
**Issue type**
Bug report

**Environment info**
Cytoscape.js version : 3.2.13
Browser/Node.js & version : Chrome

**Current (buggy) behaviour**
Very slow style rendering when updating multiple elements in a large graph

**Desired behaviour**
Faster rendering

**Minimum steps to reproduce**
Here is the [demo](https://jsbin.com/xeranatoli/edit?html,output)

1. Hover over the edges, you will observe that there is considerable delay for the style to change

While I understand that updating every edge on a 'mouseover' and 'mouseout' will be expensive, the corresponding rendering in a d3 graph is very fast

PS - The 'hover' style change is just for demo purposes. Other styles may also be changed. This issue is mainly for large graphs, for smaller graphs it works fine

**Comment by maxkfranz** [comment]
It's the code you've written that's slow -- rather than the style application itself.  There are tips in the docs re. performance, and there are also some more obvious issues in the demo you posted (consider the big-O cost of the code you've written).

**Comment by janithmehta** [comment]
@maxkfranz While I know the code I've written isn't the optimal, d3.js with the same graph and code renders it fast. I was hoping to achieve the same performance from Cytoscape since I want to replace my existing d3 visualization with Cytoscape

**Comment by dlangerenken** [comment]
I'm working with @janithmehta  on this issue. Essentially, the problem is the following:

`
edges = {} 
cy.on("mouseover", "edge", event => {
  cy.edges().forEach(a => {
    if (a.id() === event.target.id()) {
      cy.edges(`#${event.target.id()}`).style("line-color", "black");
      edges[a.id()] = 'black';
    } else {
      if (edges[a.id()] !== 'gray') {
        cy.edges(`#${a.id()}`).style("line-color", "gray");
      }
      // cy.edges(`#${event.target.id()}`).style("line-color", "gray"); // will make rendering slow
    }
  });
});
`

**Comment by dlangerenken** [comment]
```
  updateVertexData(edgeId: string, key: string, value: any) {
    this.updateElement(edgeId, key, value, 'data', 'nodes');
  }

  updateVertexStyle(edgeId: string, key: string, value: any) {
    this.updateElement(edgeId, key, value, 'style', 'nodes');
  }

  updateEdgeData(edgeId: string, key: string, value: any) {
    this.updateElement(edgeId, key, value, 'data', 'edges');
  }

  updateEdgeStyle(edgeId: string, key: string, value: any) {
    this.updateElement(edgeId, key, value, 'style', 'edges');
  }

  updateElement(elementId: string, key: string, value: any, attribute: string, type: string) {
    const cacheId = `${elementId}_${key}_${type}`;
    if (this.styleCache[cacheId] !== value) {
      this.styleCache[cacheId] = value;
      let elements;
      if (type === 'edges') {
        elements = this.cy.edges(elementId);
      } else {
        elements = this.cy.nodes(elementId);
      }
      if (attribute === 'data') {
        elements.data(key, value);
      } else {
        elements.style(key, value);
      }
    }
  }
```

adding this on our side increases the performance significantly...

**Comment by maxkfranz** [comment]
There are several problems with the code you posted.  One of them is using `ele.style()`.  There are very few cases where that should be used.  You wouldn't put all your styles for DOM elements in `style` attributes, right?  The same applies to Cytoscape elements.  From the docs: 

> You should use this function very sparingly for setting, because it overrides the style of an element, despite the state and classes that it has. In general, it’s much better to specify a better stylesheet at initialisation that reflects your application state rather than programmatically modifying style.

If you use some caching scheme, then you'll be calling the problematic (slow) code less -- which as you noticed gives an improvement.  But if you follow all the instructions and performance tips in the docs, caching isn't really necessary.

Unfortunately, I don't have time to help everyone who emails me or posts to the issue tracker looking for code help.  There is the possibility of paid support, if you are looking for hands-on help.
