### ISSUE TITLE
More than 3 labels per edge

### ISSUE THREAD

**Issue by sebthaele** [cytoscape/cytoscape.js#2170]
**Description of new feature**
At the moment there's only the start-, end- and normal label for an edge. For certain use cases more labels per edge are needed. They should be freely placeable based on both absolute (pixel-) length and relative to the length of the edge.

**Motivation for new feature**

I work on a visualization for computer networks, where you have switches and devices. Each edge is a between them. The end-labels are reserved for the port numbers at both sides. The normal label of the edge is used for the line rate/bandwidth. More labels are needed for example CRC error numbers, bottleneck indicators and so on.

**Comment by maxkfranz** [comment]
I can appreciate the want of more labels on edges.  However, that's not something that may not be generally practical.  There are three edge labels, each at predefined positions:

(1) The main label -- at the midpoint

(2) The source label -- at the source intersection

(3) The target label -- at the target intersection

Labels (2) and (3) may be shifted very slightly by using an offset.  This offset *must* be relatively small for it to be accurate, as the mechanism used to shift the label uses an inexpensive approximation for most edge types.  The accuracy is high for small offsets, and the accuracy tends to decrease as the offset increases.

It may be more practical to use the main label with multiple lines.  That's already supported.

Another alternative is allow image rendering over top of edges, like is already allowed for node background images.  These images can be SVGs, which can contain arbitrary text and shapes.  This feature does not yet exist.

**Comment by sebthaele** [comment]
Hello Max, 
Thanks for the reply. I already use multiple edge labels (4+) with another library called jsplumb. But it achieves that by having divs as the nodes and SVG paths as edges. That hybrid-approach comes with some disadvantages when it comes to exporting the state of layout or simply rendering pngs or pdfs out of it. Overlaying SVGs on top of canvas edges would probably go in the same direction then. 
Will think about the next steps... thanks!

**Comment by maxkfranz** [comment]
> Overlaying SVGs on top of canvas edges would probably go in the same direction then.

SVGs are dynamically rasterised by Cytoscape within the canvas, so they're included in any export.

**Comment by maxkfranz** [comment]
For those also interested in label/overlay customisation, consider the `cytoscape-popper` extension: https://github.com/cytoscape/cytoscape.js-popper
