### ISSUE TITLE
Determine, whether there are elements at given point

### ISSUE THREAD

**Issue by toddbarry** [cytoscape/cytoscape.js#2172]
I need to determine whether there are elements at defined point. I use inefficient method for this purpose now in my opinion: I search all existing elements, that has require coordinates on greed.

```
function is_position_empty(eles, grid_x, grid_y, sector){
	var targets = eles.filter(function(ele){
		return ele.position('grid_y') == grid_y && ele.position('grid_x') == grid_x && ele.position('sector') == sector;
	});
	return targets.empty();
}
```

But I think, that this no good solution for many elements.

I think that determines whether anything is rendered at a given point is better. But I can't find this performance on documentation.

Please, tell me, how I can determine, whether anything is rendered at a given point

**Comment by maxkfranz** [comment]
Duplicate : https://github.com/cytoscape/cytoscape.js/issues/1209
