### ISSUE TITLE
Find replacement for heap.js 

### ISSUE THREAD

**Issue by dlangerenken** [cytoscape/cytoscape.js#2176]
Based on your package.json, you have a dependency to heap v0.2.6:

```
  "dependencies": {
    "heap": "^0.2.6",
    "lodash.debounce": "^4.0.8"
  }
```
https://github.com/qiao/heap.js hasn't been maintained in the last 4 years and is potentially (!) vulnerable - although I don't see any open CVEs or similar against it.

I was wondering if there is a chance for you to a)  find a replacement or b) implement the functionality yourself. For some organizations it is hard to get cytoscape.js into a product given the non-maintained old dependency. In addition, that dependency has a weird license which is based on the python-version (PSF LICENSE AGREEMENT FOR PYTHON 2.7.2) which makes cytoscape.js no longer MIT only.

[b] https://codeburst.io/implementing-a-complete-binary-heap-in-javascript-the-priority-queue-7d85bd256ecf

**Comment by maxkfranz** [comment]
The [PSF](https://tldrlegal.com/license/python-license-2.0) license is uncommon, but it's as permissive as [MIT](https://tldrlegal.com/license/mit-license) or [BSD](https://tldrlegal.com/license/bsd-2-clause-license-(freebsd)).  PSF is also [OSI-approved](https://opensource.org/licenses/alphabetical).

I'm not particularly worried about vulnerabilities in the `heap` library.  It's just a binary heap.  For a well written data structure, I would expect its code to change rarely -- if ever beyond a certain point.  It's open-source.  In the unlikely event that a vulnerability is found, someone can fork the project to patch it if the author doesn't want to do so.

Additionally, `heap` seems to be the only heap module on npm that would meet the functional and performance requirements of Cytoscape.js.

It is not a high priority for us to rewrite a heap module, given that `heap` is good, MIT-compatible, and widely-used.

If you are adamant about strict MIT licensing for all dependencies, I think your first step should be to approach [Joe Xu](https://github.com/qiao) and ask him whether he would consider relicensing `heap` as MIT.   You would need Joe and all the collaborators in the repo to agree to the change.

**Comment by maxkfranz** [comment]
Note for future: If the performance of [`@tyriar/fibonacci-heap`](https://www.npmjs.com/package/@tyriar/fibonacci-heap) improves, then we could consider using it in place of [`heap`](https://www.npmjs.com/package/heap).  The last time I tested `@tyriar/fibonacci-heap` in Cytoscape, it dropped performance in places by 10-20%.  Fibonacci heaps don't tend to perform that well in practice, though they look good in theory.
