### ISSUE TITLE
How to add background color to network in .json style file

### ISSUE THREAD

**Issue by JingVT** [cytoscape/cytoscape.js#2178]
I used cytoscape to visualize the network and set the background color. However, the exported .json style file has no background color feature.  
For example, in the below .json style file, I expect the background color feature of the network before "style" .
[ {
  "format_version" : "1.0",
  "generated_by" : "cytoscape-3.6.1",
  "target_cytoscapejs_version" : "~2.1",
**I expect the background color feature of the network here**
  "title" : "PSIMI 25 Style",    
  "style" : [ {
    "selector" : "node",
    "css" : {
      "border-width" : 2.0,
      "font-size" : 12,
      "height" : 65.0,
      "background-opacity" : 0.8627450980392157,
      "shape" : "octagon",
      "font-family" : "Dialog.plain",
      "font-weight" : "normal",
      "color" : "rgb(50,50,50)",
      "background-color" : "rgb(255,102,102)",
      "text-valign" : "center",
      "text-halign" : "center",
      "text-opacity" : 0.9019607843137255,
      "width" : 65.0,
      "border-color" : "rgb(180,180,180)",
      "border-opacity" : 0.9411764705882353,
      "content" : "data(Human_Readable_Label)"
    }
  }, ...............
]

**Comment by maxkfranz** [comment]
Please file a bug report in Redmine: http://chianti.ucsd.edu/cyto_web/bugreport/bugreport.php

This is a Cytoscape desktop issue -- not a Cytoscape.js issue.
