### ISSUE TITLE
Cutrectangle shape is not redered properly for small nodes

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js#2181]
**Environment info**

- Cytoscape.js version : 3.2.16
- Browser/Node.js & version : Google chrome version 68.0.3440.106

**Current (buggy) behaviour**

``cutrectangle`` shape is rendered in an unexpected way when the node dimensions are small.

**Desired behaviour**

I would expect to see the proper ``cutrectangle`` shape being rendered no matter what the dimensions are.

**Minimum steps to reproduce**

See [this js fiddle](http://jsfiddle.net/5379tysh/9/)

**Comment by maxkfranz** [comment]
The cut has a fixed size, so if you make the shape too small then the corners dominate the shape.  This isn't a bug, so no changes can be made related to this for 3.2.

In a feature release, there are the following options:

(1) A console warning.

(2) Automatically change the shape to `rectangle` if the node is too small.

(3) Disallow cut rectangle shapes from being smaller than about 30x30.

**Comment by maxkfranz** [comment]
Planning on having options (1) & (2) for 3.3
