### ISSUE TITLE
  multiple layouts, different layout within compound nodes

### ISSUE THREAD

**Issue by mafar** [cytoscape/cytoscape.js#2183]
**Issue:**
 After i Use dagre layout , i tried to make layout for compound nodes but it resets all elements with new layout while I want to keep parent nodes as dagre positioned them

**JSFIDDLE:** https://jsfiddle.net/bababalcksheep/jwm701oe/

**stackoverflow:** https://stackoverflow.com/questions/52200858/cytoscape-js-multiple-layouts-different-layout-within-compound-nodes

![capture](https://user-images.githubusercontent.com/4101480/45149282-9d06e480-b1e2-11e8-9c65-4552de74d35d.PNG)

**Comment by Does666** [comment]
After search on google, I find there are many questions about this. `different layout within compound nodes` is a common request.

**Comment by tmushayahama** [comment]
any update on this issue? I am facing the same issue
