### ISSUE TITLE
Mismatched target label's direction

### ISSUE THREAD

**Issue by PeBraz** [cytoscape/cytoscape.js#2191]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.16

**Current (buggy) behaviour**

Autorotate labels have different direction for vertical edges.

**Desired behaviour**

The target label should have the same direction as the source and middle labels.

**Minimum steps to reproduce**

In the following example, the target labels (*bar*) have to be read from a different direction
[Example](https://jsfiddle.net/20qop9kc/2/)

**Comment by maxkfranz** [comment]
@PeBraz a2c2c0d should resolve the issue, which will be released in 3.2.17 on Friday.
