### ISSUE TITLE
Cytoscape doesn't follow GraphML standards

### ISSUE THREAD

**Issue by sebkajeka** [cytoscape/cytoscape.js#2192]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version :
- Browser/Node.js & version :

**Current (buggy) behaviour**

Ignoring the desc tags within a GraphML document. A Desc tag should map to a name. Currently a "name" attribute is needed in order to assign to name, which does not conform to GraphML standard and breaks compatibility between different Graph software (Gephi requires a "label" attribute, again non-standard). 

Note the desc tag in the following schema:

http://graphml.graphdrawing.org/specification/schema_element.xsd.htm

**Desired behaviour**

Load a GraphML desc element as a name

**Minimum steps to reproduce**

```
<graphml>
    <graph edgedefault="directed">
        <key id="x" attr.name="x" attr.type="float" for="node"/>
        <key id="y" attr.name="y" attr.type="float" for="node"/>
        <key id="z" attr.name="z" attr.type="float" for="node"/>
        <node id="n0">
            <desc>Node Name One</desc>
            <data key="x">-19.0759</data>
            <data key="y">-27.3243</data>
            <data key="z">38.8582</data>
        </node>
        <node id="n1">
            <desc>Node Name Two</desc>
            <data key="x">-6.64716</data>
            <data key="y">-38.1986</data>
            <data key="z">33.7861</data>
        </node>
        <edge id="e0" source="n0" target="n1">
        </edge>
    </graph>
</graphml>
```

Importing this graphml file will ignore desc tags

**Comment by maxkfranz** [comment]
Cytoscape.js doesn't support GraphML

**Comment by sebkajeka** [comment]
Sorry, I should have posted this on the GraphML extension https://github.com/iVis-at-Bilkent/cytoscape.js-graphml
