### ISSUE TITLE
Option to turn of boxSelection completely? 

### ISSUE THREAD

**Issue by buffpojken** [cytoscape/cytoscape.js#2193]
**Issue type**

Feature request

**Description of new feature**
I'd love an option to turn off boxSelection completely instead of hiding behind a meta-key. 

**Motivation for new feature**
It seems logical to be able to turn it off?

**Comment by buffpojken** [comment]
Sure thing, this turns off the selection itself - but it still draws the selection box?

**Comment by maxkfranz** [comment]
If it's off it's gone completely.
