### ISSUE TITLE
Dynamic changing of animation duration

### ISSUE THREAD

**Issue by kanakl** [cytoscape/cytoscape.js#2195]
Feature request

**Description of new feature**

There is not option how to change duration of animation when animation running. Add for example fucnction for chaging duration to Animation manipulation.

**Motivation for new feature**
I would like to change speed of animation in classic network, but  if animation is set to i.e. to 10000ms and after that change to 100ms, the change is made after the first animation is complete.

**Comment by maxkfranz** [comment]
An animation itself can not be modified.  You can stop a prior animation and start a new one if you want.
