### ISSUE TITLE
Document bezier edge implementation details

### ISSUE THREAD

**Issue by donshikin** [cytoscape/cytoscape.js#2198]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.17
- Browser/Node.js & version :Chrome 68.0.3440.106 (Official Build) (64-bit)

**Current (buggy) behaviour**

Unbundled bezier edges are not rendered correctly. Either they are something else rather than cubic Bezier curves, or there is something amiss with control point or curve calculation

**Desired behaviour**

Either draw proper curve or enhance documentation so that people are not mistaken

**Minimum steps to reproduce**

I composed a small snippet showing the issue: https://codepen.io/donshikin/pen/VEjZRg 

The setup: 2 nodes placed at two corners of a square, at [100, 100] and [200, 200] and a single unbundled bezier edge between them.

The control points are placed at  two other corners of the square [200, 100] and [100, 200] - i.e., in cytoscape.js parlance, if I understand it right, the style options `control-points-weights` are [0.5, 0.5] and `control-points-distances` are [-50 * sqrt(2), 50 * sqrt(2)]

Note that I set `edge-distances` style option  to "node-position" (although using "intersection" doesn't make any difference)

For comparison, I draw green Canvas bezier curve with the same endpoints and control points. Canvas curve, as expected, goes straight down in its middle section. Cytoscape.js for some reason draws an inverted-S shape, as if both control points were shifted horizontally (red Canvas curve with control points at [280, 100] and [20, 200] matches this shape almost exactly)

**Comment by maxkfranz** [comment]
They are a series of quadratic beziers -- one point per curve.

**Comment by donshikin** [comment]
> They are a series of quadratic beziers -- one point per curve.

Thanks Max! Now I understand. That wasn't clear from the doc, though, so maybe it would be good mention it in 'Styles' section?

Just to clarify: if I have two control points, do I understand correctly that endpoint where first segment ends and the second starts is simply intersection between 'straight edge' line and line connecting the  control points?

**Comment by maxkfranz** [comment]
> Thanks Max! Now I understand. That wasn't clear from the doc, though, so maybe it would be good mention it in 'Styles' section?

Yes, for 3.3

> 
> Just to clarify: if I have two control points, do I understand correctly that endpoint where first segment ends and the second starts is simply the midpoint between control points?

Yes, [it seems so](https://github.com/cytoscape/cytoscape.js/blob/79928726c99f7743553d4e7b39ccdd3782b11670/src/extensions/renderer/base/coord-ele-math/edge-control-points.js#L644-L647).  I think that makes most common combinations join fairly smoothly.
