### ISSUE TITLE
Double color for edge filling?

### ISSUE THREAD

**Issue by kuzinmv** [cytoscape/cytoscape.js#2207]
**Double color for edge filling?**

I realize that this is an absolutely special case, but I still think to ask. Do you think adding such a feature would be useful? But I still do not know how to do this for curves, since in my case only straight or segmented edges are needed.

```
line-head-color: lightgreen,
line-head-length: 0.3,
```
![edge-head-color](https://user-images.githubusercontent.com/6621928/47599829-3cbd4380-d9d8-11e8-9e4c-3f75825b1bff.gif)

**Motivation for new feature**

In my case need show queue before the node, an i thought that two different colors it is a easiest way do it.

![2018-09-08 23 36 12](https://user-images.githubusercontent.com/6621928/47599894-c7eb0900-d9d9-11e8-821d-accffcd75597.png)

**Comment by maxkfranz** [comment]
There's already gradient support in 3.3/unstable, which is a superset of the feature you propose.

```js
.selector('edge')
  .css({
    'line-fill': 'linear-gradient',
    'line-gradient-stop-colors': ['blue', 'blue', 'green', 'green'],
    'line-gradient-stop-positions': ['0%', '50%', '50%', '100%']
  })
```

Gradients work for every edge type:

<img width="530" alt="screen shot 2018-10-29 at 11 38 20 am" src="https://user-images.githubusercontent.com/989043/47661361-462ce400-db6f-11e8-94d1-5103f8384ee7.png">

For the simple straight line edge case, it should work exactly as in your example if you use sharp stops.

**Comment by kuzinmv** [comment]
Gradient it is great! Thank you so much it's more than enough.
