### ISSUE TITLE
Style for selector :selected not working after change node style

### ISSUE THREAD

**Issue by kanakl** [cytoscape/cytoscape.js#2215]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.20

**Current (buggy) behaviour**

After change style i.e. backgroudColor:
```
 nodeElement.style({
                backgroundColor:"red",
 });
```
A backgroundColor for selected element probalby is changed too, because after selecting a element, backgroundColor is still same

**Minimum steps to reproduce**
Add to stylesheet: 
```
selector: ':selected',
              css: {
                'background-color': 'black',
                'line-color': 'black',
                'target-arrow-color': 'black',
                'source-arrow-color': 'black'
              },
```
And after that you change color of background of node 
```
 nodeElement.style({
                backgroundColor:"red",
 });
```

**Comment by maxkfranz** [comment]
If you override the style, it's always overridden.  If you don't like that behaviour, you probably should avoid using style overrides (`ele.style()`).  As the documentation says, there are very few valid usecases for using that function.
