### ISSUE TITLE
Positions not updated when refresh is set to zero in CoSE layout

### ISSUE THREAD

**Issue by kinimesi** [cytoscape/cytoscape.js#2218]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js@latest :

**Current (buggy) behaviour**

When `refresh` is set to 0 in CoSE layout, the positions are not updated at all.

**Desired behaviour**

According to the documentation, setting `refresh` to 0 should "only updated on the end".

**Minimum steps to reproduce**

`cy.layout({name: 'cose', refresh: 0}).run();`

I think replacing `f < options.refresh` with `f  <= options.refresh` in the following line should solve the problem.
https://github.com/cytoscape/cytoscape.js/blob/40a1a8f1e9e9e086ff8f4e43fb122194a2252b1f/src/extensions/layout/cose.js#L921

**Comment by maxkfranz** [comment]
3.2.21 will be released on Monday
