### ISSUE TITLE
Export PNG with cytoscape function cy.png does not include popper.js labels

### ISSUE THREAD

**Issue by cescribanohs** [cytoscape/cytoscape.js#2219]
I have tried to export the PNG related to the graph provided as sample for the integration of popper.js with cytoscape.js, but the exported png does not include the popper content when exported.

The reference sample is: https://cytoscape.org/cytoscape.js-popper/

The refence code to export the PNG is the following one:

                var text = window.cy.png({'output': 'blob'});
                var name = "test.png";
                var type = "image/png";
                var a = document.getElementById("downloadpng");
                var file = new Blob([text], { type: type });
                a.href = URL.createObjectURL(file);
                a.download = name;
                a.click();
This is the resulting image when exporting cy.png() included a popper.js content

https://i.stack.imgur.com/Krf8X.png

**Comment by maxkfranz** [comment]
Anything in the DOM is outside of the graph.  Anything outside of the graph can not be rendered to `cy.png()`.

You'll need to use another strategy if you want overlay content in an image.  Popper is DOM-only.

You should probably render your own canvases or create your own svgs, and then combine those images with the cytoscape image.
