### ISSUE TITLE
Cannot query style value when it supports string array

### ISSUE THREAD

**Issue by somedmguy** [cytoscape/cytoscape.js#2221]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : discovered in 3.2.12, reproduced in latest master & unstable branches
- Browser/Node.js & version : n/a

**Current (buggy) behaviour**

ele.style('background-image') returns "NaNpx"

**Desired behaviour**

It returns the appropriate value.

**Minimum steps to reproduce**

This unit test fails:
```js
    it('ele.style(property) works for string array property value', function(){
      cy.$('#n1').style('background-image', '/test/image.png');
      expect( cy.$('#n1').style('background-image')).to.equal('/test/image.png');
    });
```

The style getter doesn't properly handle styles that support array values [here](https://github.com/cytoscape/cytoscape.js/blob/master/src/style/get-for-ele.js#L60).

**Comment by maxkfranz** [comment]
3.2.21 will be released on Monday
