### ISSUE TITLE
render large amount of nodes 

### ISSUE THREAD

**Issue by djy2017** [cytoscape/cytoscape.js#2222]
Simple example:
... ...

cy.add(createNodes(1000))
function createNodes(n){
	let max = 1000
	let min = -1000
	let nodes = []
	for(let i =0;i<n;i++){
		nodes.push({
			group:'nodes',
			data:{id:`'${Math.floor(Math.random()*(100000-0+1)+0)}'`},
			position: {
				x: Math.floor(Math.random()*(max-min+1)+min),
				y:Math.floor(Math.random()*(max-min+1)+min)
			}
		})
	}
	return nodes
}

When I try to render lots of nodes the  page would work slowly , how to solve the problem?

**Comment by maxkfranz** [comment]
Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  Any of the example demos on [js.cytoscape.org](http://js.cytoscape.org) can be forked on JSBin to easily provide a code sample.

**Comment by djy2017** [comment]
I`m sorry ...
- But I try to explore the peformance demo https://cytoscape.org/js-perf/
- When elements reach 20,000 ,it renders slowly, even the chrome( V67.0.3396.87) crash when use dagree layout (20,000 nodes).
- While my work is show more than 20,000 nodes and edges at the graph , and change the layout , so how to overvome the performance limitation.

**Comment by maxkfranz** [comment]
The documentation has a section on this topic: http://js.cytoscape.org/#performance
