### ISSUE TITLE
Function calculation doesn't work

### ISSUE THREAD

**Issue by roberta91** [cytoscape/cytoscape.js#2224]
Hi everyone.
I am visualizing networks on Cytoscape from .graphml files. Those files consist basically in lists of amino acids sequences each one with a certain frequency. Now, I would like to visualize the nodes of my network sized as logarithmic frequency-based, but when I try to calculate the log of the frequency from the f(x) command in Cytoscape, it turns into an error (#ERR: can't convert "frequency [,10]" to a number in a call to LOG()).

Do you know have any idea about what is happening? 
Please, ask me for further information if I haven't been clear enough.

Thanks!

**Comment by maxkfranz** [comment]
Desktop questions should go in the desktop help desk: https://groups.google.com/forum/#!forum/cytoscape-helpdesk
