### ISSUE TITLE
Compound structure not properly changed `cy.json()` in certain cases

### ISSUE THREAD

**Issue by josejulio** [cytoscape/cytoscape.js#2226]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.2.20
- Browser/Node.js & version : chrome Version 70.0.3538.67 (Official Build) (64-bit)

**Current (buggy) behaviour**

When using `cy.json(elements: eles)` with a similar json but adding a compound node and "moving" one  node inside, the compound node is created but the node is not inside that.

The other way around seems to fail, if you have a compound node with a node inside, removing (from the json) the compound node and removing the `parent` from the node do remove the node instead of moving out the node.

**Desired behaviour**

I expected the `cy.json` method to move the elements as needed.

**Minimum steps to reproduce**

## Example 1

Click the cat here:
  https://output.jsbin.com/pusasexopo

When you click the cat, the compound node is added, but only the tiger is inside.

From these elements:
```js
{
   nodes:[
      { data:{ id:'cat' } }
   ],
   edges:[]
}
```

This is run:
```js
cy.json({
   elements:   nodes:[
      { data:{ id:'feline' } },
      { data:{ id:'cat', parent:'feline' } },
      { data:{ id:'tiger', parent:'feline' } }
   ],
   edges:[ ]
});
```

## Example 2

Click the tiger here:
  https://jsbin.com/kegayiwari

When you click the tiger, the compound node is removed but also the children.

From these elements: 
```js
{
   nodes:[
      { data:{ id:'feline' } },
      { data:{ id:'cat', parent:'feline' } },
      { data:{ id:'tiger', parent:'feline' } }
   ],
   edges:[]
}
```

This is run:

```js
cy.json({
   elements:   nodes:[
      { data:{ id:'cat' } },
      { data:{ id:'tiger' } }
   ],
   edges:[]
}
});
```
I expected to see the nodes without the compound.

---

Is this the expected behavior of `cy.json` or could it be improved to handle these cases?

**Comment by josejulio** [comment]
@maxkfranz Let me know if there is anything I could help with.

**Comment by josejulio** [comment]
@maxkfranz There is also the other case: When a compound parent is added via `cy.json`, current parentless nodes could be added to that compound node. Check the example 1.
Should i open other issue or attempt to fix it?

**Comment by josejulio** [comment]
All the code looked good, thanks @maxkfranz

**Comment by maxkfranz** [comment]
@josejulio I'll release tomorrow at the start of the morning rather than now:  In the small chance that anything unforeseen goes wrong with publishing the releases, I'd like to have a good amount of time to address it.

**Comment by josejulio** [comment]
Thank you!
