### ISSUE TITLE
Edge `xxxxx` has invalid endpoints and so it is impossible to draw.

### ISSUE THREAD

**Issue by zy19940510** [cytoscape/cytoscape.js#2230]
Hello!

My Web project recently reported this error:

Edge `1000765104` has invalid endpoints and so it is impossible to draw.  Adjust your edge style (e.g. control points) accordingly or use an alternative edge type.  This is expected behaviour when the source node and the target node overlap.

But the canvas is displayed correctly.I want to know where the problem comes from and how to solve it.

**Comment by aryoxp** [comment]
This message also being reported during cose-bilkent layout animation. I use this layout extension on my graph project. This error can also be reproduced on cose-bilkent [demo page](https://cytoscape.org/cytoscape.js-cose-bilkent/demo-compound.html). Try to click the CoSE-Bilkent button several times, and the message will be shown in browser's console window. (Cytoscape JS 3.3.3)

**Comment by MorayM** [comment]
I'm having this issue too, using the cose-bilkent and random layouts. I'm on 3.3.3.

**Comment by maxkfranz** [comment]
It's just a warning.  Your nodes probably overlap a bit during part of CoSE.

Examine your edges that have warnings carefully.  If they are missing when they shouldn't be, then you may need to change your stylesheet.  If you examine things carefully and everything looks fine, then you can ignore the message.  It's a warning, not an error.
