### ISSUE TITLE
2 small feature requests

### ISSUE THREAD

**Issue by sakopqiu** [cytoscape/cytoscape.js#2234]
**Issue type**

Feature request

**Environment info**

- Cytoscape.js version : 3.2.20
- Browser/Node.js & version :  

**Current (buggy) behaviour**
- I am using  `cy.json(val)` method to restore the state of an old canvas, it works greatly, however I noticed it might be asynchronous while the interface is designed as if it were synchronous.
- There is no way to set a small icon on the top right side of the label,
- @types/cytoscape is severely out of sync. I have to use man `any`s to work around.

**Desired behaviour**
- Pass a "ready" function as the 2nd parameter, as what cytoscape({ready:func} does
- Enable a config to set an extra icon on top of the label or the background image. Consider this scenario:  I set the background-image to the portrait of a person, and I want to put a yellow icon on the top right side to mark him as a criminal.
- update the @types/cytoscape version

**Comment by josejulio** [comment]
Hello, I suggest to create one issue per request/bug for easier tracking. 
Currently you have 3 bugs/requests here :)

**Comment by maxkfranz** [comment]
(1) `cy.json()` is synchronous

(2) It's up to you how many background images you use and how you position them.

(3) We don't maintain Typescript definitions.  That's up to the community for now.
