### ISSUE TITLE
Rendering hints set in the top-level options object are not sent to the renderer's constructor

### ISSUE THREAD

**Issue by pigochu** [cytoscape/cytoscape.js#2240]
My Code on v3.2.X can work zooming speed will be slower , but when I upgrade to v3.3.0 , the mouse scroll zooming speed not change.
~~~javascript
    cy = cytoscape({
                        container: document.getElementById('cy'),
                        wheelSensitivity: 0.05,
~~~

**Comment by maxkfranz** [comment]
Ref https://github.com/cytoscape/cytoscape.js/commit/295f66f7db85681670b03937a8dc6da2130a1f2e#diff-4cbda7cf5642b53f0b4ada2eb9e65229
