### ISSUE TITLE
maxZoom initialisation option has no effect

### ISSUE THREAD

**Issue by Patro** [cytoscape/cytoscape.js#2245]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.3.1
- Browser/Node.js & version : Firefox 64.0 (build 20181206201918)

**Current (buggy) behaviour**

maxZoom option has no effect.

**Desired behaviour**

maxZoom should limit zooming to a maximum.

**Minimum steps to reproduce**

```js
var cy = cytoscape({
  container: document.getElementById('cy'),
  maxZoom: 1,
});
```

It works with version 3.2.22:
https://output.jsbin.com/yunituxuri/1/

It does not work with version 3.3.1, you can increase the zoom factor as you like without any limit: 
https://output.jsbin.com/javesodupe/1

**Comment by pkhera** [comment]
maxZoom is broken for me as well on upgrade to v3.3.1. Is there a work around for this?

**Comment by pkhera** [comment]
Looks like zoomRange function has a bug at line no. 309
`else if( is.number( max ) && min === undefined && max <= _p.minZoom ){`
max should be `>=` _p.minZoom instead of `<=`

**Comment by pkhera** [comment]
> maxZoom is broken for me as well on upgrade to v3.3.1. Is there a work around for this?

I found the workaround to use both minZoom and maxZoom, for maxZoom to come into effect. maxZoom is only broken when there is no minZoom set.
