### ISSUE TITLE
How to create selector for "visibility: visible" and similar style attributes?

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js#2247]
There is an existing ":visible" selector but it matches nodes that are both "display: element" *and* "visibility: visible".
How can I match only one of them? Or how can I create selectors for non-data attributes in general?

**Comment by KonradHoeffner** [comment]
Our application has a filter function that allows the user to hide certain parts of the graph.
It also has several path and neighbor finding functions that hide all graph elements that are not on the path. Those path finding functions should only include elements that are not filtered out.

At first, I used one type of hiding for both filters and paths but this lead to bugs when one finds a path and then changes the filters. For example, if I filtered out all blue nodes and then calculated a path between orange nodes and then made the blue filter visible again, all blue nodes would show up again even though they should be hidden as they are not on the path.

In order for those two types of operations to interact properly, I had to use both types of hiding, display for filters and visibility for path operations. However that was still not enough, because paths between two visible nodes would go over invisible filtered out nodes even though those would not be shown. As I didn't find a selector for filtered out nodes, I had to perform all kinds of contortions to get all path operations to interact properly with the filters, especially as paths can be extended in the application, for example one could change a filter, then calculate a path, then show neighbours of a node on the path, then change the filters again. In order to add more functionality later and increase maintainability, I would like to just use a selector for elements of one kind of visibility.

If you are interested, you can see it at http://www.snik.eu/graph/, the code for the paths is at https://github.com/IMISE/snik-cytoscape.js/blob/61925ccdeb15c5b8c6286b72001d6270800b5fe8/js/graph.js.

**Comment by maxkfranz** [comment]
You should use classes or data fields and you can exclude elements with those classes or data fields from the collection you use for querying for neighbours.
