### ISSUE TITLE
in version3.3.1， webpage become stuck while drawing

### ISSUE THREAD

**Issue by airqqqqq** [cytoscape/cytoscape.js#2251]
**Issue type**

Bug report
Feature request

**Environment info**

- Cytoscape.js version :
- Browser/Node.js & version :

**Current (buggy) behaviour**

**Desired behaviour**

**Minimum steps to reproduce**

**Description of new feature**

**Motivation for new feature**

**Comment by maxkfranz** [comment]
I could not reproduce this on the latest release.  Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  Any of the example demos on [js.cytoscape.org](http://js.cytoscape.org) can be forked on JSBin to easily provide a code sample.
