### ISSUE TITLE
cytoscape fails to layout elements in headless mode?

### ISSUE THREAD

**Issue by sakopqiu** [cytoscape/cytoscape.js#2253]
**Issue type**

Feature request

**Environment info**

- Cytoscape.js version :
- Browser/Node.js & version :

**Current (buggy) behaviour**
If I run cytoscape on the server(with the help of PhantomJS), the resulting layout seems to be always "Grid", no matter what layout I pass to it.

**Desired behaviour**
Nodes are positioned as per the "layout" config.

**Minimum steps to reproduce**

**Description of new feature**

**Motivation for new feature**

**Comment by sakopqiu** [comment]
@maxkfranz Dear author, could you take a look and give me some suggestions? Thank you

**Comment by maxkfranz** [comment]
Layouts work fine in PhantomJS.  Otherwise, the cytosnap package never would have worked.  Post a reproducible test case, and properly follow the issue template.  I'll re-open once a test case is posted.
