### ISSUE TITLE
In v3.3.x label distance to node acts "weird" compared to 3.2.22 for rotated labels

### ISSUE THREAD

**Issue by josejulio** [cytoscape/cytoscape.js#2256]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version : 3.2.22 vs 3.3.1
- Browser/Node.js & version : Version 70.0.3538.67 (Official Build) (64-bit)

**Current (buggy) behaviour**

The label is farther away than it should be:

Using v3.2.22
![bug-label-distance-in-3 2 22](https://user-images.githubusercontent.com/3845764/50849236-00915200-133c-11e9-914b-86003c4392ea.gif)

Using v3.3.1 (same applies for 3.3.0)
![bug-label-distance-in-3 3 1](https://user-images.githubusercontent.com/3845764/50849239-025b1580-133c-11e9-8573-53db63dedd09.gif)

When zooming a lot, the label distance stars showing where it should be.

**Desired behaviour**

v3.3.1 should show the label using the same distance as v3.2.22

**Minimum steps to reproduce**

- Add a label, rotated 90deg and aligned to the right

https://jsbin.com/yuwilafaxu

**Comment by josejulio** [comment]
@maxkfranz Let me know if I can help with this. Will try to find where the code to handle the labels is.

**Comment by josejulio** [comment]
From my tests, It seems to be rendering from the cache [1] when showing the "wrong" behavior, and when zooming, is not [2].

[1] https://github.com/cytoscape/cytoscape.js/blob/7482fdf3c61463ad574b9bea4a85a8efe6acdcbe/src/extensions/renderer/canvas/drawing-elements.js#L43
[2] https://github.com/cytoscape/cytoscape.js/blob/7482fdf3c61463ad574b9bea4a85a8efe6acdcbe/src/extensions/renderer/canvas/drawing-label-text.js#L224

**Comment by josejulio** [comment]
Ok, I'm going to look the code to see how the bounding box is being build, to be able to do the right operations when drawing from the cache.

**Comment by maxkfranz** [comment]
I've got a fix but it needs to be tested more today before merging.  I'll push the branch within the hour so you can try it out if you like.

**Comment by josejulio** [comment]
I'm also wondering if you tested with `text-margin-x` or `text-margin-y`, it looked like they were not taken into account too. 
I'll test with branch `ele-txr-cache-rotpt`
Thanks!

**Comment by josejulio** [comment]
There is still a little, but noticeable difference:

![little-offset](https://user-images.githubusercontent.com/3845764/50921562-f8094c00-140d-11e9-93bc-debc60f04ffc.gif)

**Comment by josejulio** [comment]
There is a little jump that i'm not sure from where is coming:
![peek 2019-01-11 12-56](https://user-images.githubusercontent.com/3845764/51053807-5c5c1500-15a0-11e9-8978-7cb82ec18295.gif)

**Comment by maxkfranz** [comment]
There is a general inaccuracy, because the browser will draw w.r.t. the baseline whereas a cache can not.  This isn't an issue for center-center labels, because they are always drawn relative to the centre of the text.  But even then browsers make different decisions on where the centre really is, and so there are still inaccuracies --- though to a smaller amount.

Another source of inaccuracy is the expansion of the bounding box for labels.  This is necessary to avoid labels getting cut off --- especially for characters with descenders.  This particular issue results in a maximum offset of one model pixel.

Probably both issues are compounded in your example.  For Helvetica, which has nice font metrics, there's only the second, one-pixel issue that's noticeable.

**Comment by josejulio** [comment]
Ok, just wanting to be sure that you are aware of these. 
IIRC it wasn't an issue with https://github.com/cytoscape/cytoscape.js/pull/2261/commits/1a532e4ddb5c074028f7bf23e23b6d3f651d4437 maybe is something else?

**Comment by maxkfranz** [comment]
I think your example might just be a lucky one that lines up in the case of `1a532e4` for the font you have.

I tried 1a532e4 with a different example page, and it still doesn't quite line up.  The only thing that fixes it for me is to remove this line:

https://github.com/cytoscape/cytoscape.js/blob/v3.3.1/src/collection/dimensions/bounds.js#L356

But as I mentioned, that causes labels to get cut off.  For example, the "g" in "Writing" gets cut off when using Helvetica Neue.

**Comment by josejulio** [comment]
I see, thanks for the clarification, no big deal with the "jumpy" label
