### ISSUE TITLE
Bug: weired behaviour when using cy.filter() with nodes vs edges

### ISSUE THREAD

**Issue by steevokovsky** [cytoscape/cytoscape.js#2260]
Issue type
--------
Bug report

Environment info
-------
- Cytoscape.js version :   newest version (3.3.1)
- Browser version :  google chrome 71.0.3578.98 (64 bit)

Current (buggy) behaviour
-------
When I try to filter the elements of the graph with the function 
      
    cy.filter('selector[class =/!= "className"');
i get the opposite behaviour for either node or edge. That means, if I try to find all edges, which have the class `className`, the function will display all edges with said class. If I change the selector `edge` to `node`, the function returns all nodes without the class `className`. 

Desired behaviour
-------
Both cases work the same way

Minimum steps to reproduce
--------

    cy.nodes().addClass("hi");                                    // all nodes have the class hi now
    console.log(cy.filter('node[class != "hi"]'));          // returns all nodes, should contain empty collection
    console.log(cy.filter('node[class = "hi"]'));           // returns empty collection, should contain all nodes
    console.log(cy.filter('edge[class != "hi"]'));          // returns all edges, which is correct
    console.log(cy.filter('edge[class = "hi"]'));           // returns empty collection, which is correct

Here is a [codepen](https://codepen.io/steevokovsky/pen/xQXPVV) with the example.

**Comment by maxkfranz** [comment]
That's not how to do a class selector.  Please read the docs carefully: http://js.cytoscape.org/#selectors/group-class-amp-id
