### ISSUE TITLE
Merging a selected element leads to the other elements being selected as well

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js#2270]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version : 3.3.2
- Browser/version : Firefox Developer Edition 65.0b11

**Current (buggy) behaviour**
Merging a selected node leads to the other nodes being selected as well.

**Desired behaviour**
Merging a selected node should lead to the other nodes not being selected as well.

**Minimum steps to reproduce**

```
const node = .... // a selected node
node.merge(someOtherNodes);
```
Now moving the selected node will not be possible as a multi selection is active which behaves strangely. For example, when unselecting the node and selecting it back again later, the merged nodes become selected again.

**Comment by maxkfranz** [comment]
I could not reproduce this on the latest release.  Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/teworah) can be forked to easily provide a code sample.

**Comment by maxkfranz** [comment]
I tried this out some more, and I can't reproduce this unless I call merge directly on an element.

The docs have a red warning for merge:   Use this function only on new collections that you create yourself, using cy.collection(). This ensures that you do not unintentionally modify another collection.
