### ISSUE TITLE
some arrow heads not showing up in graphs that contain compound nodes (parent nodes)

### ISSUE THREAD

**Issue by jbouecke** [cytoscape/cytoscape.js#2274]
**arrow heads not showing up**

Just compare the screenshot/image (http://js.cytoscape.org/img/demos/compound-nodes.png) of the simple compound graph example with the actual rendering (http://js.cytoscape.org/demos/compound-nodes/). You will see that just one edge shows the desired triangular arrow head.

I observed that there is always only one edge that is displayed correctly, while all others simply miss the arrow (and e.g. also 'target-distance-from-node'). See also: https://beta.observablehq.com/@jbouecke/test-cytoscape

Tested with Chrome (Version 71.0.3578.98 (Offizieller Build) (64-Bit))

**Comment by maxkfranz** [comment]
The screenshot is just out of date.

**Comment by jbouecke** [comment]
Partialy true. But the arrow heads shoud be there according to the code and are not visibel. I observed the problem alos in any other graph with compound nodes.

**Comment by maxkfranz** [comment]
You haven't specified any curve style.  If you want to style edges, you should always be specifying this property.

The demo doesn't specify a style for some edges either, and the screenshot is out of date.

**Comment by maxkfranz** [comment]
Closing this ticket, as it's just user error.  There could be a different ticket for the demo if need be.

**Comment by jbouecke** [comment]
> You haven't specified any curve style. If you want to style edges, you should always be specifying this property.
> 
> The demo doesn't specify a style for some edges either, and the screenshot is out of date.

Thank you very much for that information. I didn't knew becaus there was always a default value named in the documentation, thus I thougth I didn't have to specify it.

Thanks for taking a closer look!!!

**Comment by maxkfranz** [comment]
Basically, if you want to customise edges you need to know exactly what curve style is used.  That affects what other properties are applicable and how some properties behave.  If you're ever not sure whether you are OK with the default, you should set it explicitly.
