### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' 

### ISSUE THREAD

**Issue by sirbris** [cytoscape/cytoscape.js#2275]
**Environment info**

- Cytoscape.js version : 2.7.29
- Browser/Node.js & version : Google Chrome 71.0.3578.98 

**Current (buggy) behaviour**

Sometimes (hard to reproduce) the layouting fails due to following error:
> Uncaught TypeError: Cannot read property 'name' cytoscape.2.7.29.min.js:28

I can't figure out how this can happen... any pointers? Thanks in advance!

![df](https://user-images.githubusercontent.com/664179/51751131-5728bb00-20b4-11e9-9d21-ab555ff83a42.jpg)

**Comment by maxkfranz** [comment]
Regardless, this can't be addressed unless a reproducible test case (preferably a demo) is provided.

Closing until this is reproducible.
