### ISSUE TITLE
Div element appended at the end of the document body

### ISSUE THREAD

**Issue by PioArchiver** [cytoscape/cytoscape.js#2276]
A div element gets appended onto the end of the document. I'm sure this is known behavior, I just wanted to ask if it's a bug issue? [I couldn't find an open one]

Note:  
The presence of the div doesn't effect my program or the applications use of Cytoscape's methods.

**Comment by maxkfranz** [comment]
It's probably the one used to get text metrics.  As far as I know, there's no other way to get those dimensions accurately.  (The [canvas API](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText) is not sufficient.)

**Comment by PioArchiver** [comment]
Below is the element that gets appended to the bottom of the body of the html dom.  Thanks for the quick response :)

Also, so yeah the text content of the Cytoscape node is present there.

```<div style="font-family: Helvetica Neue, Helvetica, sans-serif; font-style: normal; font-size: 16px; font-weight: normal; position: absolute; left: -9999px; top: -9999px; z-index: -1; visibility: hidden; pointer-events: none; padding: 0px; line-height: 1; white-space: normal;">```
Workspace  
```</div>```
