### ISSUE TITLE
How can i get count of nodes in current viewport?

### ISSUE THREAD

**Issue by klysak** [cytoscape/cytoscape.js#2283]
I have a large graph (near by 800 nodes). Also i use plugin `cytoscape-node-html-label` where i placed custom html content in label of node and placed it in center of node. Then i calculate `width` and `height` of these overlays and apply it to nodes `width` and `height` properties like this:

```
placeOverlayFunction = id => {
    let el = document.getElementById(id);
    cy.$(`#${id}`).style({
      width: `${el.offsetWidth}`,
      height: `${el.offsetHeight}`,
    });
  }
```

It looks like this: 

![2019-02-07 17 23 02](https://user-images.githubusercontent.com/5830303/52417835-c9aa8980-2afd-11e9-8db6-acb90c1009d8.png)

When i have 200 nodes with `HTML overlays` it works fine without lags, but with 800 nodes it is `2-3 fps` 😢. I decided that I would hide the overlays at a certain zoom level like this:

```
cy.on('zoom', () => {
      if (this.hiddenOverlays !== null) {
        if (this.cy.zoom() >= 0.5 && this.hiddenOverlays) {
          this.hiddenOverlays = false;
          cy.$('node').forEach(node => {
            this.showOverlayFunction(node.data().id);
          });
        } else if (this.cy.zoom() < 0.5 && !this.hiddenOverlays) {
          this.hiddenOverlays = true;
          cy.$('node').forEach(node => {
            this.hideOverlayFunction(node.data().id);
          });
        }
      }
    });
```

Without `HTML overlays` it looks fine with `30-40 fps` even we have 800 nodes. But if we have `zoom-level 0.5` or greater, i would show `HTML overlays` and it looks bad. I thought, if we could count the number of nodes in `viewport` it would be a powerful optimization for me. Is there opportunity do this? Thank you for CytoscapeJS! It is awesome library!

**Comment by jspautsch** [comment]
This is how I do it, but maybe there's a better way:

```javascript
const ext = cy.extent()
const nodesInView = cy.nodes().filter(n => {
  const bb = n.boundingBox()
  return bb.x1 > ext.x1 && bb.x2 < ext.x2 && bb.y1 > ext.y1 && bb.y2 < ext.y2
})
```

Will check if the entire node body is in view. If all you want is the centerpoint, use `position()` instead of `boundingBox()` and use `x` and `y` on the returned value instead of `x1`, `x2`, `y1`, `y2`.

**Comment by klysak** [comment]
@jspautsch thank you! It works fine for me!
