### ISSUE TITLE
`hideEdgesOnViewport` and `textureOnViewport` are ignored

### ISSUE THREAD

**Issue by jspautsch** [cytoscape/cytoscape.js#2284]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.4.0
- Browser/Node.js & version : Chrome 57

**Current (buggy) behaviour**

Setting hideEdgesOnViewport in the initialization options is ignored, even when set on the "renderer" sub property. Edges are still visible when panning/dragging/zooming.

**Desired behaviour**

When hideEdgesOnViewport is true, edges should be hidden during viewport changes.

**Minimum steps to reproduce**

Set hideEdgesOnViewport to true in the init options

jsbin: https://jsbin.com/yosudid/edit?html,js,output

There seems to be two issues going on:

1) These and other renderer options have been silently moved out of the top-level init options object and into a "renderer" property. That change has not been reflected in the documentation.

2) Even when passed with the renderer options (which fixes other init options like wheelSensitivity), "rendererDefaults" is not setup to provide a default value for hideEdgesOnViewport, and due to the implementation of util.defaults that property is dropped altogether.

**Comment by maxkfranz** [comment]
TODO -- describe more general issue

**Comment by maxkfranz** [comment]
Some renderer options were accidentally removed from being passed to the renderer in the addition of the `cy.mount()` feature.  Whether the options are specified under `options` or `options.renderer` should not matter.

**Comment by maxkfranz** [comment]
Note: This issue affects both `hideEdgesOnViewport` and `textureOnViewport` options.
