### ISSUE TITLE
Texture caches can become stale if they are updated mid-batch

### ISSUE THREAD

**Issue by jspautsch** [cytoscape/cytoscape.js#2285]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.4.0
- Browser/Node.js & version : Chrome 57 & 72

**Current (buggy) behaviour**

Removing a child node from its parent compound node while inside a batch will not update the compound bounds if the batch is ended asynchronously (e.g. inside a timeout)

**Desired behaviour**

Ending a batch should properly update compound node bounds, even when called asynchronously.

**Minimum steps to reproduce**

1. Setup a graph with compound nodes
2. Start a batch
3. Remove a node inside a compound parent
4. Asynchronously end the batch (e.g. inside a timeout)

jsbin, using setTimeout to demonstrate: https://output.jsbin.com/fivehaf

In our case we're not using a timeout, but there are cases where we wait for a promise to resolve before ending a batch.

**Comment by maxkfranz** [comment]
Explanation: During batching, pre-frame hooks (like rendered style calculations, style calculations) should not occur.  Similarly, no frames should be drawn during a batch.  A race condition could occur, for example, where the layer texture cache draws to a texture before the batch cycle is complete.  This would result in an invalid (mid-batch) layer texture that is considered clean, if no events dirty the texture post-batch.  A redraw would then call upon the texture cache, and the cache being marked clean could result in a scene that is not up-to-date.

**Comment by maxkfranz** [comment]
Here's the file I used for testing.  I simplified it by removing CoSE so things could be tracked out more easily.  You can test it by putting the file beside the `cytoscape.js` directory for a clone of the repo, running `npm run watch`:

```html
<!DOCTYPE html>
<!--
Created using JS Bin
http://jsbin.com

Copyright (c) 2019 by jspautsch (http://jsbin.com/fivehaf/2/edit)

Released under the MIT license: http://jsbin.mit-license.org
-->
<meta name="robots" content="noindex">
<html>
<head>
<link href="style.css" rel="stylesheet" />
<meta charset=utf-8 />
<meta name="viewport" content="user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui">
<title>Images</title>
<script src="cytoscape.js/build/cytoscape.umd.js"></script>
  <!-- <script src="https://unpkg.com/cytoscape-cose-bilkent@2.0.2/cytoscape-cose-bilkent.js"></script> -->
<style id="jsbin-css">
body {
  font: 14px helvetica neue, helvetica, arial, sans-serif;
}

#cy {
  height: 100%;
  width: 100%;
  position: absolute;
  left: 0;
  top: 0;
}

</style>
</head>
<body>
<div id="cy"></div>
<script id="jsbin-javascript">
window.addEventListener('DOMContentLoaded', function(){
  var script = document.createElement('script');

  script.src = 'http://' + location.hostname + ':35729/livereload.js';

  document.head.prepend( script );
});



window.addEventListener('DOMContentLoaded', function(){ // on dom ready

var cy = cytoscape({
  container: document.getElementById('cy'),

  elements: {
    nodes: [
      { data: { id: 'cat' } },
      { data: { id: 'bird' } },
      { data: { id: 'ladybug' } },
      { data: { id: 'aphid', parent: 'bird' } },
      { data: { id: 'rose', parent: 'bird' } },
      { data: { id: 'grasshopper' } },
      { data: { id: 'plant' } },
      { data: { id: 'wheat' } }
    ],
    edges: [
      { data: { source: 'cat', target: 'bird' } },
      { data: { source: 'bird', target: 'ladybug' } },
      { data: { source: 'bird', target: 'grasshopper' } },
      { data: { source: 'grasshopper', target: 'plant' } },
      { data: { source: 'grasshopper', target: 'wheat' } },
      { data: { source: 'ladybug', target: 'aphid' } },
      { data: { source: 'aphid', target: 'rose' } }
    ]
  },

  style: cytoscape.stylesheet()
    .selector('node')
      .css({
        'label': 'data(id)'
      }),

  layout: {
    name: 'grid'
  }
}); // cy init


  // test async batch end
  console.log('start batch')
  cy.startBatch()
  var node = cy.getElementById('rose')
  node.remove()

  setTimeout(function(){
    console.log('end batch')

    cy.endBatch()
  }, 1000)



}); // on dom ready
</script>
</body>
</html>
```
