### ISSUE TITLE
Unbundled-bezier does not take effect after 3.3

### ISSUE THREAD

**Issue by sakopqiu** [cytoscape/cytoscape.js#2289]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.3.0 and above
- Browser/Node.js & version : chrome 71.0.3578.98

**Current (buggy) behaviour**
My code uses "unbundled-bezier“ to draw self-loops and it worked fine before 3.2.22, after I upgraded to 3.3.0(I tried all 3.3 and 3.4 versions), "unbundled-bezier" degrades to "bezier".
For example,
`cytoInstance.edges()[0].style().curveStyle` used to be "unbundled-bezier", now it becomes "bezier". 

**Desired behaviour**

**Minimum steps to reproduce**

**Description of new feature**

**Motivation for new feature**

**Comment by maxkfranz** [comment]
How would you specify an unbundled bezier for a loop?  The is the same as the target, so the `control-point-weights` property doesn't make sense.

**Comment by maxkfranz** [comment]
Closing for now
