### ISSUE TITLE
pixelRatio: 'auto' crashes

### ISSUE THREAD

**Issue by ghosttie** [cytoscape/cytoscape.js#2295]
**Issue type**
Bug report

**Environment info**
- Cytoscape.js version : 3.4.1
- Browser/Node.js & version : Chrome 74

**Current (buggy) behaviour**
In LTCp.getLayers the line `lvl = Math.ceil(log2(zoom * pxRatio));` sets lvl to NaN if pxRatio is "auto" which causes CRp$a.makeOffscreenCanvas to crash at `canvas = new OffscreenCanvas(width, height);` because width and height are NaN

**Desired behaviour**
Not crash

**Minimum steps to reproduce**
```js
	window.cy = cytoscape({
		container: $('#cyHolder')[0],
		style: [
			{
				selector: 'node',
				style: {
					'label': 'data(name)',
					'text-valign': 'center',
					'background-color': '#ffffff',
					'shape': 'roundrectangle',
					'border-color': '#666',
					'border-width': '1px'
				}
			},
			{
				selector: 'node:selected',
				style: {
					'line-color': 'blue',
					'target-arrow-color': 'blue',
					'source-arrow-color': 'blue',
					'border-color': 'blue',
					'border-width': '2px',
					'opacity': 1
				}
			},
			{
				selector: 'edge',
				style: {
					'width': 3,
					'label': 'data(name)',
					'line-color': '#ccc',
					'line-style': 'solid',
					'curve-style': 'bezier',
					'target-arrow-color': '#ccc',
					'target-arrow-shape': 'triangle'
				}
			},
			{
				selector: 'edge:selected',
				style: {
					'background-color': 'blue',
					'target-arrow-color': 'blue',
					'line-color': 'blue'
				}
			},
			{
				selector: 'node.nolabel',
				style: {
					'label': ''
				}
			}
		],
		elements: {
			nodes: WorkflowTemplate.AllNodes,
			edges: WorkflowTemplate.AllEdges
		},
		layout: {
			name: 'preset',
			refresh: 0
		},
		zoom: 1,
		pan: { x: 0, y: 0 },
		zoomingEnabled: false,
		userZoomingEnabled: false,
		panningEnabled: true,
		userPanningEnabled: true,
		boxSelectionEnabled: false,
		selectionType: 'single',
		autolock: false,
		autoungrabify: false,
		autounselectify: false,
		// rendering options:
		headless: false,
		styleEnabled: true,
		hideEdgesOnViewport: false,
		hideLabelsOnViewport: false,
		textureOnViewport: false,
		motionBlur: false,
		pixelRatio: 'auto'
	});
```

**Comment by maxkfranz** [comment]
This isn't reproducible without a full example.  You don't even have any elements defined.

Please create a jsbin that reproduces your issue in isolation.  It should not depend on your app.

**Comment by ghosttie** [comment]
Here's a [jsbin](https://jsbin.com/yetuyumoqo/edit?html,output) repo

**Comment by maxkfranz** [comment]
I can't reproduce this on my Mac desktop or on my Macbook Pro.  Generally though, Chrome Canary (currently v74) is not a stable release.

What OS are you using?  What hardware are you using?

**Comment by ghosttie** [comment]
Sorry, looks like the jsbin saved when I had pixelRatio set to 2 not 'auto' - try [this one](https://jsbin.com/joqaratudo/edit?html,output)

I'm on the Chrome dev channel not canary, but you're right that it's not the current stable version.  I don't get the same error on Edge and Firefox but I do get errors when pixelRatio is set to 'auto'

I'm using Windows 10

**Comment by maxkfranz** [comment]
The same thing happens on your demo if you call `node.shift()` after init: `eles.shift({ x })` invalidates `y` #2310
