### ISSUE TITLE
[documentation] EBNF notation for selector syntax

### ISSUE THREAD

**Issue by einsweniger** [cytoscape/cytoscape.js#2320]
**Issue type**
Feature request (more like suggestion/discussion)

**Description of new feature**
Documentation should provide a description of the syntax for the selector in EBNF or similar.

**Motivation for new feature**
Pro:

- Able users can quickly glance valid syntax from EBNF.
- Developers hacking on the parser/tokenizer will have an easier time maintaining/understanding it.
- eliminates ambiguity in documentation, i.e. 
  - are operators `^=`, `$=`, `*=` allowed/unsurprising for numeric comparison?
  - may modifiers `@`, `!` coexist?
  - do state and data mix? (`node[weight>4]:selected`)
- eliminates need to spell out every valid combination

Contra:

- additional overhead keeping documentation and parser logic in sync
- might not be of use for everybody
- initial investment for writing it up

**Comment by einsweniger** [comment]
aside: I really, *really* like that you built a parser instead of lazily calling `eval` on strings, the library in general and the awesome documentation!

**Comment by maxkfranz** [comment]
Re. ambiguity, I think the answer is always "yes":  Combinations should work, for every applicable data type (with the same semantics as JS itself).  You can combine operator modifiers.  Operators like `<` work on strings.  Whether the way JS handles automatic type casting etc. is intuitive or not is another matter, though.

Basically, if you use `<` you get the same semantics as JS `<`.  If you use `@`, both arguments are `toLowerCase()`ed.  If you use `!`, your end result is inverted.
