### ISSUE TITLE
[documentation] add caveat for batch et. al.

### ISSUE THREAD

**Issue by einsweniger** [cytoscape/cytoscape.js#2321]
**Issue type**
Feature request

**Description of new feature**
batch section should feature a warning/caveat to catch exceptions and finally call `cy.endBatch()`

**Motivation for new feature**
Both, synchronous and async styles of batch calls may trigger exceptions, thus unwinding and never calling `cy.endBatch`
Adding a little section to inform users that they could run into problems here might help avoid this.

Example:
```
cy.startBatch();
const dupe = {data: {id: 'dupe'}}
cy.add(dupe); // works
cy.add([dupe,dupe]); // works, returns empty collection
cy.add(dupe); // <-- throws generic Error
cy.endBatch();  // never called, no style updates. Might leave user in unexpected state.
```
edit: Here was a question about wether or not cytoscape.js should have more specific exceptions, this was moved to #2322, just in case somebody get's confused about the answer.

**Comment by maxkfranz** [comment]
The motivation for exceptions within the lib was so that during development, a programmer could identify logical mistakes in his app and amend things appropriately (e.g. sanitise the input).  Those exceptions were originally just warning messages, because ultimately they're all recoverable by just doing nothing.  The reason they were promoted to exceptions is so that a programmer would be more likely to notice and address those issues upfront.

You shouldn't be able to add elements with existing IDs ever.

**Comment by einsweniger** [comment]
would you be interested in a PR for the caveat or do you think that's unnecessary?

**Comment by maxkfranz** [comment]
I think there are longterm and shortterm considerations:

Shortterm: We could update the docs for each function in the API that potentially throws.  There aren't many.  If the dev knows the exact function that throws, then if he really wants he could wrap each individual call in try-catch.

Longterm: We could consider typed exceptions that are exposed as API.  The dev could use instanceof to check the type of exception.

I'm not completely convinced of the utility of the longterm potential solution given the motivation for this lib's use of exceptions, but I'm open to a PR for the shortterm solution.

**Comment by einsweniger** [comment]
Ah, I did not mean the exceptions, rather the warning for batching in the documentation. Sorry for the confusion.

**Comment by maxkfranz** [comment]
The point I'm trying to make is that it's not specific to batching.  That's only one place that the exceptions could be thrown --- based on which functions are used that actually throw (e.g. add).
