### ISSUE TITLE
discussion: specific exceptions

### ISSUE THREAD

**Issue by einsweniger** [cytoscape/cytoscape.js#2322]
**Issue type**
Feature discussion

**Description of new feature**
I'd like it if the exceptions were more specific.

**Motivation for new feature**
Motivating example:

```
cy.startBatch();
const dupe = {data: {id: 'dupe'}}
cy.add(dupe); // works
cy.add([dupe,dupe]); // works, returns empty collection
cy.add(dupe); // <-- throws generic Error
```

With simple examples like this, the generic Error is not a large problem.
My personal preference is to not catch generic run-time Error objects, as this will catch everything else w/o regard to the original problem.
Could be another problem, like a failed fetch, in which case you want might want to abort and revert the batch all-together.

So, this is a little related to #2258, as in `util.error` / `util.warn` are a little too unspecific about the actual problem (read: it's difficult to make programmatic decisions).
As a workaround, I'd have to catch generic Error, check if the error `message.startswith("Can not create second element with ID")`, and then decide based on that. (I'd also have to hope that the message will not change :D)

I'd be in favour of having more specific exceptions deriving from Error (like DuplicateIdError), but that's just me. (I'd rather have contributors adding more cool stuff like Taxi-Edges :3. So, you do you!)

**Comment by maxkfranz** [comment]
See https://github.com/cytoscape/cytoscape.js/issues/2321#issuecomment-469718952

**Comment by einsweniger** [comment]
Ah, it's that way around. That's fine as well.
