### ISSUE TITLE
Offset edge labels with autorotate

### ISSUE THREAD

**Issue by dallemang** [cytoscape/cytoscape.js#2329]
Feature request

I am using cytoscape to layout figures for a book.    Many of my diagrams are boxes-and-arrows where the arrows have labels.  My publisher wants the labels alongside the arrows, rotated with the arrows.  The attached image is almost what I need:

![image](https://user-images.githubusercontent.com/857628/53921158-787ab080-403d-11e9-8dbb-329653fd99ae.png)

I did this in my stylesheet  by saying 

            .css({
                'label': function (label) {console.log(label.data());return (label.data().label + "\n\n .")},
                'curve-style': 'bezier',
		'text-wrap': 'wrap' ,
                'edge-text-rotation': 'autorotate',
                'text-background-opacity': 0,
            })

(I left out a bunch of stuff I think is irrelevant)

Notice the trick here; I am using multi-line labels, and putting blank lines at the end.  I have the "." at the very end, because without it, the trailing whitespace is suppressed, and I lose my blank lines. 

I have tried various tricks using text-margin-x and text-margin-y, but those didn't work out for various reasons. 

**Description of new feature**
The  new feature (or just show me how to do this with existing features) is to allow rotated edge labels to be offset, relative to the edge itself. 

**Motivation for new feature**

The motivation is to make figures that my publisher likes :) Surely this isn't such an odd style request?

**Comment by maxkfranz** [comment]
I think this was captured, albeit with less detail, in https://github.com/cytoscape/cytoscape.js/issues/1185.

Your workaround is interesting, and perhaps for now you could make the "." invisible by replacing it with a non-whitespace character that is invisible.  [Zero-width-space](http://www.fileformat.info/info/unicode/char/200B/index.htm) seems to fit, as [it's not considered to be a whitespace character proper](https://en.wikipedia.org/wiki/Whitespace_character#Unicode).  It seems in JS regex, [it's not matched by `\s`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Special_characters_meaning_in_regular_expressions).  You could try that character, if it doesn't work you could try another one in the table not matched by `\s`.

**Comment by maxkfranz** [comment]
Or maybe even just "\n\n".

**Comment by jri** [comment]
@dallemang thank you for sharing the `\n\n` `text-wrap` trick! @maxkfranz thank you for the `\u2060` hint! Together it unexpectedly solved a long-lasting problem :-)

**Comment by dallemang** [comment]
Thanks, @maxkfranz  - that works like a charm.  And I learned a bit about character sets (I was hunting for something like \u2060, but didn't even know how to google it).

As far as I am concerned, this topic solved, so I'll close it.

**Comment by jelmerjellema** [comment]
For some reason only adding \n\n\u2060 makes the first character of the label looking sort of erased. This worked for me:

` 'label': edge => edge.data('label') ? `\u2060\n${edge.data('label')}\n\u2060` : ''`

It would be great to have an 'offset from line' (or just 'padding').
