### ISSUE TITLE
React when a pan/zoom operation ends

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js#2330]
When a pan/zoom operation ends my app needs to store the new state at the backend. I don't want send requests rapidly as with every `pan`/`zoom` event. How can I achieve this?

**Comment by jri** [comment]
Let me clearify my question: does Cytoscape provide support to let my app detect when the user ended a pan/zoom operation?

**Comment by maxkfranz** [comment]
There is no definitive way to know when it ends.  You have to debounce using a threshold that feels appropriate.

**Comment by jri** [comment]
OK. Thank you!

**Comment by jri** [comment]
Meanwhile I've solved that in my app by debouncing and it works fine. Thanks!
