### ISSUE TITLE
collection animation causes memory leakage

### ISSUE THREAD

**Issue by QuynhNguyen** [cytoscape/cytoscape.js#2331]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.4.2
- Browser/Node.js & version : Chrome / Node v11.9

**Current (buggy) behaviour**
Memory Leak

Increase the browser memory footprint then crash the tab

**Desired behaviour**

Not causing memory leak

**Minimum steps to reproduce**

```js
    graph.ready(() => {
      const animate = () => {
        // graph.edges().stop(true, true);  uncomment this line to fix it

        edgeOffsetRef.current += 5;
        graph.edges().animate({
          style: { 'line-dash-offset': -edgeOffsetRef.current }
        });
        requestAnimationFrame(animate);
      };
      animate();
    });
```

**JSBin** https://jsbin.com/wubuwopeje/edit?js,console,output

**Comment by maxkfranz** [comment]
Please provide a *full* reproducible demo for your issue.  Follow the instructions in the issue template by creating a demo on jsbin.

**Comment by QuynhNguyen** [comment]
> Please provide a _full_ reproducible demo for your issue. Follow the instructions in the issue template by creating a demo on jsbin.

Done - https://jsbin.com/wubuwopeje/edit?js,console,output
Open your chrome task manager and watch the memory footprint.

**Comment by maxkfranz** [comment]
Given the code that you've written, it would be expected that memory usage increases over time.  You could do the same thing with any library that supports animations:  You're creating animation objects many times faster than the speed of the animations themselves.  That makes no sense.

Take a look at the documentation more and read some of the relevant demos.  After that, take a look at the MDN entry for `requestAnimationFrame()` if you're still having trouble understanding why it would be inappropriate to use that function with an animation object.
