### ISSUE TITLE
Edge bundling?

### ISSUE THREAD

**Issue by ar-stackrox** [cytoscape/cytoscape.js#2332]
Thanks for the awesome library. I didn't see any examples, but was wondering if edge bundling is something that is supported or could be achieved in some way today.

https://github.com/upphiminn/d3.ForceBundle

![image](https://user-images.githubusercontent.com/28272783/54102957-ab97a980-4387-11e9-9d54-16f18b04b209.png)

**Comment by maxkfranz** [comment]
It's an interesting idea that's been considered before, but there are several significant drawbacks:

- It's slow.
- It's no longer practical for the graph to be interactive and dynamic.  It's more like Graphviz, where you just get a static result.
- The layout must also be appropriate for bundling.
- It makes a pretty picture, but the interpretation problem is still present.  It can still be ambiguous where an edge begins and ends.  Some edges might even be completely hidden by the algorithm.

Here's a relevant paper:  [Towards Unambiguous Edge Bundling: Investigating
Confluent Drawings for Network Visualization](https://aviz.fr/~bbach/confluentgraphs/Bach2016confluentgraphs.pdf) [(web)](https://aviz.fr/~bbach/confluentgraphs/)

One of the authors is Tym Dwyer, from the University of Melbourne, who also worked on Cola.js.

It's not really a distinct edge type:  It's an algorithm to set bezier control points.  So if you wanted to implement an algorithm, like confluent graphs, you could make an extension those control points.  The result could be set in your stylesheet using a mapper.

**Comment by ar-stackrox** [comment]
All very valid points @maxkfranz 

As for the graph being interactive and dynamic and edges being ambiguous, I do think at a larger scale this issue is present in either case. Without user interaction on a node, it becomes difficult to select or interact with an edge that is above many other edges.

One example for interaction with edge bundling that I found to be useful is here - https://mbostock.github.io/d3/talk/20111116/bundle.html

Mousing over a name highlights its corresponding edges. Also has a slider to let the user decide the degree to which edges are bundled.

And thanks for the tip!

**Comment by maxkfranz** [comment]
> As for the graph being interactive and dynamic and edges being ambiguous, I do think at a larger scale this issue is present in either case.

There are two levels to consider:  The ordinary view is better for granular interpretation, but bundling is better for summarisation.  The ideal would probably be something like the wine and cheese demo, where the overall summary view uses bundling and the circular node detail view uses ordinary edges.

**Comment by ar-stackrox** [comment]
100% agree. I was hoping to create something very similar to that effect. I think implementing it on our end is probably a bit beyond our scope at the moment, but I appreciate the clarification.

**Comment by ar-stackrox** [comment]
Also before I close the issue, @maxkfranz I was hoping if you could tell me if there was an option to click+drag selection of nodes? I understand it pans by default, but maybe that could be binded to a spacebar + click.
