### ISSUE TITLE
TypeError: e.registerBinding is not a function

### ISSUE THREAD

**Issue by wiredgril666** [cytoscape/cytoscape.js#2333]
I can start successfully in my dev_evrionment.But, I got a error,which is  "Uncaught TypeError: e.registerBinding is not a function" , in console . when I build in my test_evrionment.Have someone met this problem?I need your help,thks.

**Comment by maxkfranz** [comment]
Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.

**Comment by wiredgril666** [comment]
https://github.com/rcarcasses/vue-cytoscape/issues/2.
This is same issues with vue-cytoscape.This doesn't seem like a vue-cytoscape issue but a webpack build config.I get this issue with webpack 3.11.0,not vue,is react. Chrome, 62.0.3202.94. 
It alse doesn't seem like with Browser version.My workmate's browser also have this problem.

**Comment by wiredgril666** [comment]
TypeError:e.registerBinding is not a function at trace.250f3d48.js:formatted:165896

function(e,t){
    for(;null!=e;)
      (function(t){
       e.registerBinding(t,'transitionend',m),//  line 165896
}
}

**Comment by wiredgril666** [comment]
Thanks a lot, this problem has been solved, and the introduction method has been changed. Download cytoscap.min.js and import it in index.html
