### ISSUE TITLE
Multilevel compound node expansion with cytoscape-expand-collapse breaks with cytoscape.js version >3.3.6

### ISSUE THREAD

**Issue by utkarshagarwal01** [cytoscape/cytoscape.js#2337]
**Issue type**

Bug report

- Cytoscape.js version : >3.3.6
- Cytoscape Expand collpase version : 3.1.2
- Node.js version : v10.15.0 

**Current (buggy) behaviour**

When we expand a collapsed node having another collapsed node inside it, the code goes into an infinite while loop. The graph stops responding.

**Desired behaviour**

Not hang up and expand the node, please.

**Minimum steps to reproduce**
CodePen reproducing the issue:
https://codepen.io/utkarsh-agarwal/pen/ZPrbzq

**Comment by maxkfranz** [comment]
If you have an issue with an extension, please file an issue in that extension's repo -- as outlined in the instructions in the issue template.  Different groups own different extensions.

**Comment by utkarshagarwal01** [comment]
Because one of the cytoscape library versions was causing the error, I thought i should raise an issue here. Sorry about that.
