### ISSUE TITLE
Style hash collisions for `width:label` or `height:label`

### ISSUE THREAD

**Issue by aryoxp** [cytoscape/cytoscape.js#2348]
Hi Max,

Thanks for developing this great graph library. 
I would like to report a unexpected visual behavior of the library that I use in my current research project.

**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.5.2
- Browser/Node.js & version : Chrome 73, Firefox 66, Safari 12.1
- OS: MacOS X Mojave 10.14.4

**Current (buggy) behaviour**

Border applied around nodes with rounded rectangles (and also the rounded rectangle shape) seems to be distorted for several nodes with different size in a particular zoom level.

<img width="814" alt="Screen Shot 2019-04-06 at 6 06 34 AM" src="https://user-images.githubusercontent.com/649791/55656558-4faf2c00-5832-11e9-8ab6-01c54135811d.png">

The behaviour can be reproduced in the following JSBin demo:
https://jsbin.com/sigixoy/edit?js,output

**Desired behaviour**

A uniform visual as defined in styles definition is expected as seen in the following zoom level.

<img width="815" alt="Screen Shot 2019-04-06 at 6 06 47 AM" src="https://user-images.githubusercontent.com/649791/55656547-41f9a680-5832-11e9-88e2-5afbb2f79830.png">

**Minimum steps to reproduce**

Run the following JSBin demo:
https://jsbin.com/sigixoy/edit?js,output

Do the zooming-in-and-out over the cytoscape canvas to a particular zoom level and notice how the nodes border and rounded rectangles shape become distorted.

--------
Thank you

**Comment by maxkfranz** [comment]
Patch forthcoming:

![Screen Shot 2019-04-11 at 4 59 23 PM](https://user-images.githubusercontent.com/989043/55992720-361b4380-5c7b-11e9-8c76-8219f44453e1.png)
