### ISSUE TITLE
too much nodes cause the function "cy.add" became slow

### ISSUE THREAD

**Issue by Neltharion3927** [cytoscape/cytoscape.js#2354]
**Issue type**

Feature request

**Environment info**

- Cytoscape.js version :3.5.0
- Browser/Node.js & version : Google Chorme  72.0.3626.121

**Current  behaviour**

when i was call 'cy.add' add almost 100 nodes & then call 'cy.add' again,the Browser's performance has a little slowly;i think it's maybe caused by ‘nodes‘ too much to compared immediately.

**Desired behaviour**

i hope no matter how many 'nodes' added by user,the performances all have a short time

**Comment by maxkfranz** [comment]
Please post a reproducible test case.  There is already a benchmark in the repo for `cy.add()` and it seems OK.

**Comment by Neltharion3927** [comment]
after i'm call "cy.add",i try  call 'cy.layout([selector]).run()',so cause the issue 'more nodes to call add() need more time' delete this line,the add() looks well
