### ISSUE TITLE
Compound node bounds including hidden children (regression)

### ISSUE THREAD

**Issue by somedmguy** [cytoscape/cytoscape.js#2355]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : found using 3.5.2
- Browser/Node.js & version : chrome & firefox

**Current (buggy) behaviour**

Hidden child nodes that were previously visible still affect parent's bounding box.

**Desired behaviour**

Parent bounding box is only determined by visible children

**Minimum steps to reproduce**

https://jsbin.com/juguwisaye
Wait for the cat to disappear

**Comment by maxkfranz** [comment]
The reason that this happens is that the bounding box for an element that is hidden shouldn't change for things like the element cache in the renderer.  Before, the compound bounds code relied on display:none children having a zero-area bounding box.  That shortcut is not longer valid.  An explicit filter is now used instead.  Try the snapshot or build from master:

[3.5.4-snapshot2.zip](https://github.com/cytoscape/cytoscape.js/files/3086773/3.5.4-snapshot2.zip)

Feel free to re-open if the patch doesn't resolve this completely.

**Comment by somedmguy** [comment]
Thanks for the fast turnaround, as usual, max.  I'm curious why you didn't use the takesUpSpace member function.  Cache issue, or you didn't want to handle zero width/height nodes?

**Comment by maxkfranz** [comment]
From the commit message:

> The children used to calculate the bounds of the parent should not include nodes that take up no space.  It may make sense in future to remove the zero width and height conditions for the internal `ele.takesUpSpace()` function.  We can't use it here, because calling `height()` or `width()` causes infinite recursion.  The zero width and height cases aren't that important generally, so maybe this could be revised further for a feature release.
