### ISSUE TITLE
Add prominent GitHub links to all demos

### ISSUE THREAD

**Issue by co16353sidak** [cytoscape/cytoscape.js#2357]
Website Related: http://js.cytoscape.org/

Feature Request

**Description of new feature**
The website contains a lot of nice examples with the Cytoscape.js library in action, it would be wonderful that each project had an extra prominent link to their corresponding GitHub repo or location in a repo for ease of access.
It took me a while to find the a particular demo and it's repository and it would be handy for future use to have them linked on the website directly.
also the link at the bottom makes it very hard to distinguish if it will open the demo or the repo link.

**Motivation for new feature**

Ease of access for developers and users who come across the website.

**Comment by maxkfranz** [comment]
The entire caption for each demo is a link, with an accompanying Github logo.  If you can find a better way to make the source code links more salient, I'd welcome a pull request.

None of the demos are built, so you don't really need the Github links.  They're demos:  You can just use the view-source feature or the inspector feature in your browser.

**Comment by maxkfranz** [comment]
I'm closing this to clean up the issue list, but PRs are generally welcomed to improve any part of the documentation.
