### ISSUE TITLE
node type demo is broken

### ISSUE THREAD

**Issue by ar-stackrox** [cytoscape/cytoscape.js#2359]
They used to work but now all show up as circles.

http://js.cytoscape.org/demos/node-types/

![image](https://user-images.githubusercontent.com/28272783/56222801-7d118c00-6021-11e9-8efc-2643505203a8.png)

**Comment by maxkfranz** [comment]
Duplicate of the following:

Node body styles incorrectly cached (regression) #2356

See the referenced patch in that issue.
