### ISSUE TITLE
Cose layout does not respect bounding box when animate is 'end'

### ISSUE THREAD

**Issue by benrudolph** [cytoscape/cytoscape.js#2363]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.5.2
- Browser/Node.js & version : Chrome 73

**Current (buggy) behaviour**

The Cose layout does not respect the boundingBox param when `animate: 'end'`.

**Desired behaviour**

Respect the boundingBox

**Minimum steps to reproduce**

See https://jsbin.com/hiqasiduli/1/edit?html,css,js,output. Currently `animate` is set to `false`. To see the bug behavior change to `'end'`

**Comment by benrudolph** [comment]
Not sure if this is useful, but when determining this behavior I found that `refreshPositions` is not being called (assuming this is because `end` does not animate the in-between positions).

**Comment by maxkfranz** [comment]
The patch should sort this out.

Snapshot: 
[3.5.4-snapshot3.zip](https://github.com/cytoscape/cytoscape.js/files/3089918/3.5.4-snapshot3.zip)

**Comment by benrudolph** [comment]
thank you!
