### ISSUE TITLE
Edge arrow shape not updating properly (regression)

### ISSUE THREAD

**Issue by somedmguy** [cytoscape/cytoscape.js#2364]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : Found using 3.5.2
- Browser/Node.js & version : chrome & firefox

**Current (buggy) behaviour**

Programmatic changes that impact edge styles are not getting properly reflected in the drawing, even after calling ```cy.style().update()```.

**Desired behaviour**

Edge styles can be recalculated.

**Minimum steps to reproduce**

https://output.jsbin.com/pasimumabi/
The edge arrows should toggle on and off, but in order for the styles to be updated, the graph needs user interaction (select, drag, etc).  The exact problem behavior is different for different patches.  In 3.5.2 the arrows will disappear but the edge will not fill in where they were.  In 3.5.3 nothing appears to change (I think the 3.5.4 candidate has this same behavior).

Also, we are using the expand-collapse plugin programmatically, and when a node is expanded or collapsed its edges may not adjust to the node's new size/position, which makes me think this issue may be a duplicate of #2358

**Comment by lukasluecke** [comment]
I have a similar issue: I use the `background-image` property to dynamically generate svg icons for my nodes - on 3.5.2 this works, on 3.5.3 all nodes get the same svg as the first node.

**Comment by maxkfranz** [comment]
> I have a similar issue: I use the background-image property to dynamically generate svg icons for my nodes - on 3.5.2 this works, on 3.5.3 all nodes get the same svg as the first node.

Try the patch https://github.com/cytoscape/cytoscape.js/issues/2356

**Comment by maxkfranz** [comment]
Edge arrow snapshot: 

[3.5.4-snapshot4.zip](https://github.com/cytoscape/cytoscape.js/files/3090077/3.5.4-snapshot4.zip)
