### ISSUE TITLE
Clustering without attributes

### ISSUE THREAD

**Issue by davey561** [cytoscape/cytoscape.js#2368]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.5.3
- Browser/Node.js & version : 10.15.1

**Current (buggy) behaviour**

The custom distance function option in the clustering algorithms k-medoids and hierarchical throws an error. The return value function, which takes two parameters nodeP and nodeQ, cannot depend on either nodeP or nodeQ, as both are undefined. When the return value doesn't depend on the input nodes (e.g., when I set the distance function to return zero regardless of the input parameters), the clustering seems to work fine.

K-means and fuzzy c-means should not allow a two-argument distance function at all, as they are inherently incompatible.

**Desired behaviour**

The custom distance function (function(nodeP, nodeQ)) should have inputs nodeP and nodeQ that are defined references nodes in the graph.

**Minimum steps to reproduce**

The below code throws the error: "cytoscape.esm.js:1825 Uncaught TypeError: Cannot read property '0' of undefined." fw is the array of distances between each pair of nodes in the graph (I tested to make sure the bug is not here; fw works perfectly well). Then, within the function(nodeP, nodeQ), that is supposed to return the distance between any two nodes, no return value can reference nodeP or nodeQ without throwing an error. For some reason, both nodes seemed to be undefined, even if the graph and its elements are well-defined.

```js
    let fw = cy.elements().floydWarshall();
    let clusters = cy.elements().kMedoids({
        k:4, 
        distance: 
            function(nodeP, nodeQ){
                //console.log(nodeP);
                return fw.distance(nodeP, nodeQ);
            }
    });
```

**Comment by maxkfranz** [comment]
Only k-medoids, hierarchical, and affinity propagation make sense to allow for `distance(nodeP, nodeQ)`.  Those are now corrected as needed and verified with tests.  The documentation has been updated to reflect the `distance()` compatibility.

**Comment by maxkfranz** [comment]
Snapshot: [3.5.5-snapshot1.zip](https://github.com/cytoscape/cytoscape.js/files/3113513/3.5.5-snapshot1.zip)
