### ISSUE TITLE
Missing docs for getFitViewport and zoomRange

### ISSUE THREAD

**Issue by smith** [cytoscape/cytoscape.js#2373]
I found the `getFitViewport` and `zoomRange` methods in the source but there is no documentation for them.

I'd be happy to open a PR adding these docs, but would appreciate any assistance in grokking what these methods do.

**Comment by maxkfranz** [comment]
They're not documented because they're private.  If something is not in the [documentation](http://js.cytoscape.org), it's not meant for consumers of the library.

**Comment by smith** [comment]
@maxkfranz ok thanks. I'm trying to set the minZoom for a graph based on its current size. `getFitViewport().zoom` gets me what I need in this case. Is there a better way to do this?

**Comment by maxkfranz** [comment]
I don't think that's a good idea, because the user could rotate the screen or resize the window.

It's usually best to just set a min zoom level empirically.

**Comment by smith** [comment]
Ok thanks. We're setting the minZoom on layoutstop events, so we get a new value when that happens. Thanks for the advice, it makes sense.
