### ISSUE TITLE
Possible TypeError with haystack in dimensions/bounds.js

### ISSUE THREAD

**Issue by manuc66** [cytoscape/cytoscape.js#2374]
Hi

I faced an error at this line:

https://github.com/cytoscape/cytoscape.js/blob/98b61498339455df042e32a7b906083f422d5382/src/collection/dimensions/bounds.js#L506

After looking at the code, it seems that the fallback value for `rstyle.haystackPts` is an empty array, so it can produce an `TypeError: hpts[0] is undefined`

```js
        let hpts = rstyle.haystackPts || [];

        ex1 = hpts[0].x;
        ey1 = hpts[0].y;
        ex2 = hpts[1].x;
        ey2 = hpts[1].y;
```

I have no idea why I get this error

**Comment by maxkfranz** [comment]
Please include a reproducible test case or demo.

**Comment by maxkfranz** [comment]
Closing until the issue template is followed with a reproducible demo or test case.
