### ISSUE TITLE
taxi link become straight when compound node is moved

### ISSUE THREAD

**Issue by Rishi0405** [cytoscape/cytoscape.js#2376]
Hi,

I am using taxi link and when I try to move the compound node the link becomes straight.
http://jsfiddle.net/Rishi0405/3o5jq2zd/51/

Try to move the top level parent and some taxi link will become straight.

Thanks, 
Rishi

**Comment by maxkfranz** [comment]
The edge is routed according to the rules and style properties specified in the docs.  If you specify an impossible configuration (e.g. there is insufficient space), then the edge will be re-routed.

> When a taxi edge would be impossible to draw along the regular turning plan — i.e. one or more turns is too close the source or target — it is re-routed. The re-routing is carried out on a best-effort basis: Re-routing prioritises the specified direction for bundling over the specified turn distance. A downward edge, for example, will avoid going in the upward direction where possible. In practice, re-routing should not take place for graphs that are well laid out.

**Comment by Rishi0405** [comment]
@maxkfranz Thanks. Then the problem is, it is re-routing again when it is clicked. Is it normal behavior. Because when it is rerouted again in click it looks like the link is gone.

Straight line
![wrong_taxi](https://user-images.githubusercontent.com/18022748/57057600-9f650400-6cc7-11e9-8c43-ec285c2abe33.JPG)

hidden when clicked
![hidden_taxi](https://user-images.githubusercontent.com/18022748/57057604-b3a90100-6cc7-11e9-8e62-a508c6915e2f.JPG)

**Comment by Rishi0405** [comment]
Hi @maxkfranz,

I just updated the link type with the bezier, and when I try to move the top-level parent, some links are not updated to the new position. And once I click the link it is rendered correctly. And also in older version 3.2.21, it is working good with bezier link. Please take a look at the updated link below

http://jsfiddle.net/Rishi0405/3o5jq2zd/61/

**Comment by maxkfranz** [comment]
The demo is not clear to me.  There are too many extraneous elements in the graph and too many extraneous blocks within the stylesheet.  It is difficult to see which edges go to which nodes.  I can't tell whether there is a mistake in the stylesheet or whether there is a bug:  There is too much to review, and I don't have time to isolate your issue from such a large demo.

Please provide a demo with the minimal amount of elements and style that clearly reproduces your issue.

**Comment by maxkfranz** [comment]
Possibly related: https://github.com/cytoscape/cytoscape.js/issues/2440

**Comment by Rishi0405** [comment]
@maxkfranz Thanks for the time. It is working fine with the latest 3.8.2 and as well as 3.7.3.

**Comment by maxkfranz** [comment]
Great. Thanks for the information
