### ISSUE TITLE
Removing parallel edges in headless mode

### ISSUE THREAD

**Issue by pvmeijel** [cytoscape/cytoscape.js#2377]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version : 3.5.4
- Browser/Node.js & version : Chrome

**Current (buggy) behaviour**

When I remove two parallel edges in headless mode, the following error is thrown:
`cytoscape.umd.js:11981 Uncaught TypeError: Cannot read property 'value' of undefined
    at Element.<anonymous> (cytoscape.umd.js:11981)
    at selfFn (cytoscape.umd.js:11606)
    at styleCache (cytoscape.umd.js:11590)
    at Element.cachedPrototypeStyleFunction [as isBundledBezier] (cytoscape.umd.js:11613)
    at Collection.elesfn$t.remove (cytoscape.umd.js:13232)
    at untitled.html:46`

**Desired behaviour**

Remove the elements 

**Minimum steps to reproduce**
https://jsbin.com/qizikitano/1/edit?html,css,js,console,output

```js
var cy = cytoscape({
        headless: true,
        elements: [
          { data: { id: 'a' } },
          { data: { id: 'b' } },
          {
            data: {
              id: 'ab2',
              source: 'a',
              target: 'b'
            }
          },
          {
            data: {
              id: 'ab1',
              source: 'a',
              target: 'b'
            }
          }]
      });

      console.log(cy.edges().jsons());

      cy.edges().remove();
```

**Comment by maxkfranz** [comment]
Snapshot: 
[3.5.6-snapshot1.zip](https://github.com/cytoscape/cytoscape.js/files/3133171/3.5.6-snapshot1.zip)
