### ISSUE TITLE
documented node shape `round-rectangle` doesn't work

### ISSUE THREAD

**Issue by tothandras** [cytoscape/cytoscape.js#2383]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version: `3.5.5`
- Browser/Node.js & version: `v11.13.0`

**Current (buggy) behaviour**

Node shape `roundrectangle` works as expected, but `round-rectangle` doesn't.

**Comment by tothandras** [comment]
I'm happy to open a PR.

**Comment by maxkfranz** [comment]
> I'm happy to open a PR.

I'd appreciate that.  Make it on either master or unstable and I'll cherry-pick over to the other once it's merged.

**Comment by maxkfranz** [comment]
Not reproducible.  This issue can be re-opened once it is reproducible.
