### ISSUE TITLE
Multiline edge labels throw an exception

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js#2386]
![image](https://user-images.githubusercontent.com/120337/57299315-877cee00-70d4-11e9-8694-94699178bc9e.png)

In 3.5.6 it works.

Please let me know if you want me to isolate the problem.

**Comment by maxkfranz** [comment]
This looks stylesheet-specific, so I need a stylesheet plus data to reproduce the issue.

**Comment by jri** [comment]
The error occurs when edges make use of `'text-wrap': 'wrap'`
https://codepen.io/jri/pen/gJpQjE

**Comment by maxkfranz** [comment]
Resolved in ac8a9c0.  Snapshot: [3.6.1-snapshot1.zip](https://github.com/cytoscape/cytoscape.js/files/3158088/3.6.1-snapshot1.zip)
