### ISSUE TITLE
Moving around graph using cursor keys

### ISSUE THREAD

**Issue by smarek** [cytoscape/cytoscape.js#2397]
**Issue type**
Feature request

**Description of new feature**
Possibility to use cursor/arrow keys (down,up,left,right) to move around the canvas

**Motivation for new feature**
Having large structure with mouse-dragging enabled, will sometimes become challenging for user to move around the graph. Using cursor keys would enhance the user experience in most of the non-static and/or extensive graphs

**Comment by maxkfranz** [comment]
It's very easy to do this yourself in your app.  If you'd like, you could package the code into a re-usable extension.

**Comment by smarek** [comment]
Well, I did not find any methods regarding working with the canvas render in http://js.cytoscape.org so i wrote this ticket, maybe i'm wrongly looking for API included in cytoscape.js and should be looking for native HTML5 Canvas API ?

Anyway, code-sample would be appreaciated, i'll then gladly provide plugin distribution for others.

**Comment by maxkfranz** [comment]
Listen to keypresses and call `cy.panBy()` or `cy.animate()`.

**Comment by maxkfranz** [comment]
[Mousetrap](https://craig.is/killing/mice) makes it trivial.

**Comment by smarek** [comment]
Ok, thank you very much. Here is the snippet, i've come up with, for others to use. I might later provide this in form of module.

It's missing only preventing default action (cursor keys are handled by browser to scroll in page)

```javascript
let cy; // cytoscape.js instance
let keyboardNavEnabled = false;
// modify following to your context
let containerId = "#cytoscapeContainer";
let xStep = 100;
let yStep = 100;

function panBy(x, y) {
    if (cy && keyboardNavEnabled) {
        cy.panBy({x: x, y: y});
    }
}

$(document).ready(function () {
        cy = cytoscape({...}); // abbreviated, just for 
        $(containerId).mouseenter(function () {
            keyboardNavEnabled = true;
            console.log("keyboardEnable");
        }).mouseleave(function () {
            keyboardNavEnabled = false;
            console.log("keyboardDisble");
        });

        Mousetrap.bind('up', function () {
            panBy(0, yStep);
        });
        Mousetrap.bind('down', function () {
            panBy(0, -yStep);
        });
        Mousetrap.bind('left', function () {
            panBy(-xStep, 0);
        });
        Mousetrap.bind('right', function () {
            panBy(xStep, 0);
        });
        Mousetrap.bind('+', function () {
            if (cy && keyboardNavEnabled) {
                cy.zoom(cy.zoom() * 1.1); // +10% zoom
            }
        });
        Mousetrap.bind('-', function () {
            if (cy && keyboardNavEnabled) {
                cy.zoom(cy.zoom() * 0.9); // roughly -10% zoom
            }
        });
});
```
