### ISSUE TITLE
Integer ID not sanitised as string in `cy.json()`, `ele.json()`, `ele.move()`

### ISSUE THREAD

**Issue by ketysek** [cytoscape/cytoscape.js#2398]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version : 3.6.0
- Browser/Node.js & version : Chrome 74

**Current (buggy) behaviour**
Hi there :) I've updated cytoscape from 3.2.16 to 3.6.0 and accidentally my code stopped working properly. 

I'm using react and when some change in chart occurs (node move, edge create, edge delete), I'm calling my `_renderDag` method which checks all the chart visual settings (according to response from API) and calls `this.cy.json()` to re-render the chart. This approach stopped working after update edgehandles library. It now works only for first time (for example when I do first drag 'n' drop) but with every other chart change the edges remain untouched. Look at the gif animation. What has been changed so the code stopped working?

![edgebug](https://user-images.githubusercontent.com/11921885/57713453-cc73c800-7672-11e9-8ef2-0b08f23e896e.gif)

**Minimum steps to reproduce**
You are free to try it in fiddle here: https://jsfiddle.net/g9krt2su/9/

**Comment by maxkfranz** [comment]
Can you reproduce the issue without using React and Immutable?  The important part looks like `cy.json()`, but there are a lot of moving parts.

**Comment by ketysek** [comment]
@maxkfranz same without Immutable: https://jsfiddle.net/q0w5b2Ls/1/
I'll find some time at the weekend and try to reproduce it also without React, but I'm not sure.

**Comment by maxkfranz** [comment]
Try to focus on just the Cytoscape.js API calls and try to pass the same sort of input as you would with your React demo.  The most salient parts to me are the `cy.json()` call and the `drag` listener, so maybe try to make similar calls without React even if the args are hardcoded.

**Comment by ketysek** [comment]
@maxkfranz here: https://jsfiddle.net/6w7u2p5j/

**Comment by somedmguy** [comment]
I played with the jsfiddle a little bit, and it seems switching to string ids solves the problem.  FYI

**Comment by ketysek** [comment]
@somedmguy hm, I see ... so something with that changed between the mentioned cytoscape versions. I think its bug as docs states: "mandatory (string or number) id for each element". Anyway great debug!!

**Comment by somedmguy** [comment]
>  Cytoscape casts all IDs to strings internally.

I think that's only if it's using your Map polyfill.  I see nothing explicitly converting numeric ids to string ids.

**Comment by somedmguy** [comment]
I think the problem is here in Core.json()
```
          for( let i = 0; i < jsons.length; i++ ){
            let json = jsons[ i ];
            let id = json.data.id;
            let ele = cy.getElementById( id );
```
It doesn't convert the id to a string before trying to find the existing element.  I'm guessing this causes the nodes to get replaced by copies of themselves.  Meanwhile the edge has a string id, so it gets found and left alone (with its original source & target pointers).

**Comment by maxkfranz** [comment]
Yes, if it's not casting in the same way for either of `cy.json()` or `ele.json()`, that could be a problem.
