### ISSUE TITLE
Container does not update properly size when shrinking parent/browser

### ISSUE THREAD

**Issue by Marooned-MB** [cytoscape/cytoscape.js#2401]
**Issue type**
Bug report

**Environment info**
- Cytoscape.js version : 3.5.0
- Browser/Node.js & version : Chrome 73 / Node 8.11.1

**Current (buggy) behaviour**
When expanding browser, canvas container expands too (correct). However, when shrinking, canvas container does not change its dimensions breaking layout and introducing scrollbars.

**Desired behaviour**
Correct resize of container for both: shrinking and expanding of parent.

**Minimum steps to reproduce**
Set parent of the graph to fill browser window and resize the browser.

**My workarounds and observations**
The problem is inside `matchCanvasSize` function. It reads container size via `findContainerClientCoords` and based on width/height set `canvasContainer` width/height. However, parent won't ever be smaller than canvas container so while shrinking it won't read smaller (proper) values but current thus the function won't change the size. It will however expand as parent can go bigger than canvas container.
My dirty check to replace `canvasContainer.style.height = height + 'px'` to `canvasContainer.style.height = '100%'` (the same for width) fixed the issue.
Maybe adding
js
```
ctyoscape({style:
  [{
    selector: 'container',
    style: {
      height: 'auto',
      width: 'auto'
    }
  }]
})
```
and if/else block in `matchCanvasSize` to set width/height to `100%' or leave the current code would be good?

Alternative for fixing current `matchCanvasSize` could be to hide or set to 0 canvas size before checking container boundaries so that canvas is not affecting its size.

**Comment by maxkfranz** [comment]
Not reproducible on the debug page, which does exactly this: 

> Set parent of the graph to fill browser window and resize the browser.

**Comment by maxkfranz** [comment]
Could you create a small demo that reproduces your issue?

**Comment by Marooned-MB** [comment]
Sorry for the late response, I was away.
I will try to extract some simple code to show the issue. Give me some time (catching up).

**Comment by maxkfranz** [comment]
OK, sounds good

**Comment by somedmguy** [comment]
If it helps, I ran into this in a more complex html & css structure.  Cytoscape was on a div that was in a flexbox that was in another flexbox.  Changing the css flexboxes to css grids fixed it.

**Comment by maxkfranz** [comment]
If you don't change a css class on the container itself or resize the entire window, there's no way for cytoscape to know there's a change.  You have to call `resize()`.

**Comment by Marooned-MB** [comment]
In quite simple demo I was preparing for you it seems to be working. I can't share the code where it's not working so I would guess, we have to close this ticket. I've added `100% !important` for height/width of the div cytoscape creates to wrap canvases as a working workaround.

**Comment by maxkfranz** [comment]
Until [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) is universally supported, you have to be pretty careful about how you size the container and call `resize()` accordingly.

Let's close this for now, and we can re-open it if we're able to reproduce a clear problem case.
