### ISSUE TITLE
Uncaught TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by josejulio** [cytoscape/cytoscape.js#2402]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.4.3 - 3.6.1 Not sure if this happens in all the in between versions, but it doesn't happen in 3.4.2.
- Browser/Node.js & version : Google chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Current (buggy) behaviour**

When running a particular code, the following error appears:
`Uncaught TypeError: Cannot read property 'x' of undefined`

(pseudo code):
```
cy.startBatch();
cy.json({elements: stuff}) # Stuff has several nodes, edges and a parent node with at least 1 children
cy.$().each(node => node.boundingBox());
cy.endBatch()
```

**Desired behaviour**

No error, and able to get boundingBox properly

**Minimum steps to reproduce**

Version 3.4.3  Reproducer: https://jsbin.com/qucapupidu/1/edit?html,js,output
It works fine in 3.4.2: https://jsbin.com/mavagapovi/1/edit 
or if you remove the startBatch/endBatch: https://jsbin.com/cekasidibi/1/edit
or if you put the boundingBox call outside the batch https://jsbin.com/kihiyokeme/1/edit

**Comment by maxkfranz** [comment]
You can't read computed style values mid-batch.  I can add a check and return null for bb when batching, but the bb function itself is never going to return good values mid-batch.

**Comment by josejulio** [comment]
> You can't read computed style values mid-batch. I can add a check and return null for bb when batching, but the bb function itself is never going to return good values mid-batch.

Ok, I think an exception makes sense. I think i was doing something wrong but didn't noticed until this error.

**Comment by maxkfranz** [comment]
OK, closing for now.  I don't think returning null would have helped much anyway
