### ISSUE TITLE
falseThread is not defined for cose

### ISSUE THREAD

**Issue by simonmoog** [cytoscape/cytoscape.js#2403]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.5.7
- Browser/Node.js & version : Chrome v74

**Current (buggy) behaviour**

`Uncaught ReferenceError: falseThread is not defined` in `cose.js:168`.

```
function broadcast( message ){
    var e = { type: 'message', message: message };

    falseThread.trigger( e ); // Error here
}
```

**Desired behaviour**

No error

**Minimum steps to reproduce**

Unfortunately given how complicated out setup is, and how specific the reproduction steps are to our product, I'm unable to create minimum steps.

However I'd hope that the error itself is enough to go on, given that it means the `broadcast` function is being invoked before the `falseThread` declaration, which obviously shouldn't be allowed.

**Comment by josejulio** [comment]
Do you have the stack trace?

I gave a quick peek at the code (I'm not a maintainer) and it seems that `falseThread` is defined (line 127) before  `broadcast` so it seems odd that it raises the "not defined" error.

**Comment by simonmoog** [comment]
I've managed to isolate the problem a little more.

This seems to only happen in production mode (which also means the stack trace isn't particularly useful, due to the bundling and minification).

We're using Webpack  v4.28.1, with `uglifyjs-webpack-plugin` v2.1.1 doing the optimisation. 

Here's the config in question

```
optimization: devMode ? {} : {
            minimize: true,

            minimizer: [
                new UglifyJsPlugin({
                    cache: true,
                    parallel: true,
                    sourceMap: true,
                    uglifyOptions: {
                        mangle: false,
                    },
                }),
                new OptimizeCSSAssetsPlugin({}),
            ],
        }
```

If I set `minimize` to `false`, I don't get the error. Obviously this isn't a solution, but it does shed some light on the nature of the problem I think.

**Comment by maxkfranz** [comment]
This can't be addressed until v4, and even then I don't know whether it's worth it to have the builtin cose for v4.  Frankly at this point, the [fcose](https://github.com/iVis-at-Bilkent/cytoscape.js-fcose) layout should be as fast or faster than the bundled cose and it should give better results.  It's probably a good idea to switch regardless of your issue.

**Comment by maxkfranz** [comment]
On second thought, the weaver integration didn't work out all that well generally so let's just remove it in v3.  The layout should still give the same end result, even though it's technically a breaking change to remove the `weaver` option.  It's more important to have it working.

**Comment by simonmoog** [comment]
Sorry I'm a little confused here, as I'm not overly familiar with the Cytoscape ecosystem. What are you suggesting I do to get around this problem?

**Comment by maxkfranz** [comment]
You should probably just switch to fcose, since it's a generally better version of the cose layout.

I don't think I'll have time to patch cose in time for 3.6.3
