### ISSUE TITLE
Not all tests are being exercised

### ISSUE THREAD

**Issue by stephencorwin** [cytoscape/cytoscape.js#2408]
**Issue type**
Bug report

**Environment info**
Travis / CI

**Current (buggy) behaviour**
`npm run test` and `npm run test:build` do not currently exercise any tests within a sub directory of a `./test`.

Specifically, this means that these tests are not enforced on CI builds (travis):
https://github.com/cytoscape/cytoscape.js/blob/master/test/modules/emitter.js
https://github.com/cytoscape/cytoscape.js/blob/master/test/modules/util.js

**Desired behaviour**
In my opinion, `npm run test` and `npm run test:build` (travis) both need to catch any failures for any tests that exist. Otherwise, those tests lose value and will become out of sync.

This can be naively accomplished by adding the `--recursive` argument to these npm scripts.
```diff
- "test": "mocha -r esm",
+ "test": "mocha -r esm --recursive",
- "test:build": "cross-env TEST_BUILD=true mocha",
+ "test:build": "cross-env TEST_BUILD=true mocha -r esm --recursive",
```

## Notes: Part 1
At the time of writing this, **620/637** tests are being exercised.
There is also 1 test failure because the `removeAllListeners` function was removed from the `Emitter` class. This test can probably just be removed.
![image](https://user-images.githubusercontent.com/3931162/58210914-82b16000-7cb8-11e9-93fa-6a12ba0f4205.png)

## Notes: Part 2
@maxkfranz mentioned that the intent was to allow `test:build` to be run on pretty much any version of node -- which means that using `import` statements isn't kosher. This is why those tests currently use the already built version of the library.
https://github.com/cytoscape/cytoscape.js/blob/master/src/test.js#L5-L8

**Comment by maxkfranz** [comment]
They could be part of `test` but not `test:build`.  If, for example, there is a `test:modules` script, then travis could run `test:modules` and `test:build`, since travis is configured to use only node 8 and 10 for now.  We can't use an older version of node with travis, because rollup doesn't work with them.

Summary

- `test:modules` : test everything in test/modules
- `test` : `mocha -r esm --recursive`
- `test:build` : as-is
- `ci` : should also run `test:modules`

**Comment by maxkfranz** [comment]
If it is possible to get travis to build on one version of node and then test in another, then we could add back all the old versions of node to travis.yml.  That would be great, but I don't see how to do that -- or whether it would be too hacky to be worthwhile.  It's the same sort of issue as the OP:  The tests exist for old versions of node, but they don't really get run as often as they should.

**Comment by stephencorwin** [comment]
wouldn't `test` cover `test:modules` if `test` is described as `mocha -r esm --recursive`?
We could leave the `ci` command alone since it already invokes `test`.

**Comment by maxkfranz** [comment]
Not in the case of travis, as it needs the env var set.

**Comment by stephencorwin** [comment]
Im fairly sure the `ci` command exercises the tests in the modules folder twice now. Once because of `npm test` due to the `--recursive` flag. And once for `npm run test: modules` since it points directly to the modules folder
