### ISSUE TITLE
Graph set size to 0x0 when hidden and get update

### ISSUE THREAD

**Issue by Marooned-MB** [cytoscape/cytoscape.js#2434]
I'm periodically calling `graph.nodes().filter(...).classes(newClass);` to adjust visual styles of particular nodes to show their status (running, complete etc).
However, the graph is on one of the tabs (PrimeNG tabs) and when I'm on a different tab (graph is hidden), updating node makes graph to set itself to height/width = 0. This cause that when I switch back to graph tab, graph is not visible until new update comes in and graph resize itself back to proper size.

I've tried to run resize/fit/forceRender/invalidateDimensions after tab switch but it didn't help, size remain 0x0 until new `.classes()` is invoked.

Any way to either
1) disable automatic size update in such situation
or
2) force to resize the graph (after tab showing)
?

**Comment by Marooned-MB** [comment]
Update: well, ok, looks like PrimeNG tabs have have only onChange event that is fired *before* clicked tab is actually shown and they don't have onChanged, so my problem is wrong timing on calling `graph.resize()`. Not being able to run it just in time I've added setTimeout and `graph.resize()` is now restoring proper size of the graph.

I'm still not sure if current behaviour (resizing to 0x0 when parent is hidden) is correct to be honest, so I'll leave it to you to decide and fix or close this ticket.

**Comment by maxkfranz** [comment]
We can't really do anything when the dimensions aren't queryable (e.g. the div is hidden).

You should probably be using a debounce instead of a timeout if you don't have a proper "changed" event to use.

**Comment by Marooned-MB** [comment]
> We can't really do anything when the dimensions aren't queryable (e.g. the div is hidden).

But yet you do something - you update it and set to zero. If you will not do anything when dimensions aren't queryable then there will be not issue. Just saying :)

**Comment by maxkfranz** [comment]
It is not possible to draw if the container bounds are undefined.  In any case, there would be no visual output unless the container is styled properly and `cy.resize()` is called when appropriate.
