### ISSUE TITLE
how to save the note position in cytoscape?

### ISSUE THREAD

**Issue by xinhuiwang** [cytoscape/cytoscape.js#2435]
Dear all, 
I am working with cytoscape and try generate two figures with same note position. The way i used it save all the note position, then load these position in another figure. I know there are layoutsaver and layoutplugin could work with the old version of cytoscape. I am wondering is there any similar tool (app) could work on cytoscape 3.7?
Thanks and with best regards,
Xinhui

**Comment by maxkfranz** [comment]
Ask your question here instead:

https://groups.google.com/forum/#!forum/cytoscape-helpdesk
