### ISSUE TITLE
Support multiple values for background-clip

### ISSUE THREAD

**Issue by stalniy** [cytoscape/cytoscape.js#2441]
**Issue type**
Feature request

**Description of new feature**

Allow to specify multiple values for `background-clip` property, so some background images will be clipped and others not

**Motivation for new feature**

I want to render an background image outside the node. Documentation says that I need to disable `background-clip` but this doesn't work my case, well partially.

What I want is to specify multiple background images, clip the first image but DON'T clip the 2nd

**Additional**

I already tried to do this and it works, requires simple changes in 2 places:
* https://github.com/cytoscape/cytoscape.js/blob/36a3e972fc8a42c484ae6d4d54f0d6ae666e3252/src/extensions/renderer/canvas/drawing-images.js#L28
* https://github.com/cytoscape/cytoscape.js/blob/d5ff8a0152e10b2a615866a828d0a1f8d1ff66b2/src/style/properties.js#L49

So, if you approve, I will send PR.

**Comment by maxkfranz** [comment]
> So, if you approve, I will send PR.

OK, as long as it doesn't break compatibility.  I think `multiple: true` properties allow one values to be used as an implicit array of length 1, so it should probably be OK.

**Comment by maxkfranz** [comment]
You can check how other bg image properties are used.  I think it may be if only one value is specified, then the same value is used for all.

**Comment by stalniy** [comment]
Done.

Adding an example of how this looks, so it's easier to understand the purpose. I have a regular image which is requested by HTTP (`background-clip` is applied to it) and svg image (black circle) which is base64 encoded (`background-clip` is not applied to it):

![example](https://user-images.githubusercontent.com/1159966/59875901-a72d5480-93aa-11e9-9a8b-f00c0b1bf30a.png)
