### ISSUE TITLE
Label style property is invalid.

### ISSUE THREAD

**Issue by kissferenc** [cytoscape/cytoscape.js#2448]
**Issue type**

Bug report

**Environment info**
- Cytoscape.js version : 3.7.2, I don't use any cytoscape extension.
- Browser/Node.js & version : macOS 10.14.5, Safari 12.1.1, Chrome 75.0, node.js 10.15.0

**Current (buggy) behaviour**

The browsers send warnings:
cytoscape.cjs.js:826: The style property `label: data(id)` is invalid

**Comment by maxkfranz** [comment]
I could not reproduce this on the latest release.  Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/teworah) can be forked to easily provide a code sample.
