### ISSUE TITLE
Looking for layout suggestion (I tried with SO but It got downvoted)

### ISSUE THREAD

**Issue by giggioz** [cytoscape/cytoscape.js#2449]
I'm sorry to reach this repo for a suggestion but I posted my question in [stackoverflow](https://stackoverflow.com/questions/56713520/best-cytoscape-layout-to-visualize-my-data-domain) and it was downvoted.

I don't really know where to get help at the moment, my question is straightforward:

"I have a bunch of data representing [gamebook](https://en.wikipedia.org/wiki/Gamebook) nodes.

At first, I found [graphviz](https://graphviz.gitlab.io/) and I liked [this layout](https://graphviz.gitlab.io/_pages/Gallery/directed/world.html) which is basically what I want for displaying my data.

After some research, I stumbled across Cytoscape-js which is the library I want to use.

I'm very new to Cytoscape, so my question is: Which is the closest layout in Cytoscape to represent my data as for graphviz layout?"

If you feel this answer is cluttering the issue repo feel free to close it but, in that case, please address me in another place to get help.
Thank you, guys!

**Comment by maxkfranz** [comment]
Well, that's people sometimes.

You would be the best judge of which layout looks best to you.  Try the demos at the top of the documentation.  The best layouts are all listed: http://js.cytoscape.org/#demos  You can download the demos and just paste in your data to see the result.

Most directed layouts (breadthfirst, dagre, etc.) are very similar, but you should really try as many layouts as you can and experiment.  Sometimes you can find one that works even better than your first guess.

**Comment by giggioz** [comment]
I did not thank you, sorry.
Thanks!
