### ISSUE TITLE
ERROR TypeError: Cannot read property 'h' of undefined at Layout.GridLayout.run

### ISSUE THREAD

**Issue by JakeSmokie** [cytoscape/cytoscape.js#2453]
While loading cytoscape I have this error. What's the reason of it?

```
ERROR TypeError: Cannot read property 'h' of undefined
    at Layout.GridLayout.run (cytoscape.umd.js:21043)
    at setElesAndLayout (cytoscape.umd.js:18640)
    at cytoscape.umd.js:18652
    at loadExtData (cytoscape.umd.js:18599)
    at new Core (cytoscape.umd.js:18643)
    at cytoscape (cytoscape.umd.js:31408)
```

![image](https://user-images.githubusercontent.com/14360046/60515270-eda47c80-9ce3-11e9-9772-a1d7d35dd54d.png)

**Comment by somedmguy** [comment]
>  What's the reason of it?

Most likely an invalid/incomplete bounding box specified in the layout options.  e.g.
```javascript
layout: {
  name: "grid",
  boundingBox: { x1: 0 },
  //...
}
```

`makeBoundingBox()` is just a chain of else/if's and it can fall through to return undefined if none of the if conditions are satisfied.  I had this problem before #2339 was fixed when trying to use grid layout to layout children based on the parent's bounding box.

**Comment by maxkfranz** [comment]
I suppose it could throw an exception using `util.error()` instead of returning an empty value.  It wouldn't always be informative, but it would at least fail fast.

**Comment by maxkfranz** [comment]
Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/teworah) can be forked to easily provide a code sample.

**Comment by maxkfranz** [comment]
This can be re-opened once there's a test case
