### ISSUE TITLE
Call `parent()` for collapsed node not working

### ISSUE THREAD

**Issue by Does666** [cytoscape/cytoscape.js#2465]
**Issue type**
core

Bug report

**Environment info**

- Cytoscape.js version : 3.4.6
- Browser/Node.js & version : Chrome75

**Current (buggy) behaviour**
I use `cytoscape.js` and `cytoscape-expand-collapse.js` extension. When collapse a compond node, the children of this node are hidden. I try to find one node's parent. But the `parent()`  function not work for these nodes. This works well on version 3.3.6.

**Desired behaviour**
The `parent()`  function always work no matter the node is collapsed or expanded.

**Minimum steps to reproduce**
var api = expandCollapse({// Require `cytoscape-expand-collapse.js` extension
  layoutBy : 'cose-bilkent'
});;
var myNode = api.getAllCollapsedChildrenRecursively().nodes('node[id="test"]');
console.log(myNode.parent().length); // 3.3.6 will be 1, but 3.4.6 will be 0. and I have try on the latest version 3.8.1, this issue also exist.

**Comment by maxkfranz** [comment]
Please file an issue under the extension's repo.  If an extension removes elements, then `parent()` should return an empty collection.

**Comment by Does666** [comment]
@maxfranz After a quick debugging , I find the key code finally that is the function `removeChildRef` in `src/collection/index.js`.
It added the code `ele._private.parent = null; // remove child => parent ref` in version 3.4.x while ok before

**Comment by maxkfranz** [comment]
That's not the problem.  As I said: Please file an issue under the extension's repo. If an extension removes elements, then parent() should return an empty collection.
