### ISSUE TITLE
Retrieve array of elements based on hierarchical edges sequence in cytoscape.js

### ISSUE THREAD

**Issue by calebeaires** [cytoscape/cytoscape.js#2474]
**Issue type**
Feature request

**Environment info**

- Cytoscape.js version : 3.8.1
- Browser/Node.js & version : 10

**Description of new feature**
Get a list of elements with a order based on the edges organized on the canvas.

**Motivation for new feature**
Our team need to execute task based on the flow order

The image above represent a cytoscape flow. I would like to retrieve those nodes as an sorted array based on its edges/arrows sequence.

<img width="564" alt="image" src="https://user-images.githubusercontent.com/794195/61393281-093c8500-a897-11e9-93a2-e4b225169759.png">

**Comment by maxkfranz** [comment]
I think that we already support this as much as possible, given that we have a number of search and traversal functions: https://en.wikipedia.org/wiki/Topological_sorting

If you have domain-specific rules for the ordering, then you probably can't use an off-the-shelf function for generating an ordering:  A generic function would give one arbitrary ordering, of many possible orderings.  You need to build your own function that applies your rule set.
