### ISSUE TITLE
No events are fired from straight unbundled-bezier edges

### ISSUE THREAD

**Issue by IfatChitin** [cytoscape/cytoscape.js#2483]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.8.2
- Browser/Node.js & version : Chrome Version 75.0.3770.142 (Official Build) (64-bit)

**Current (buggy) behaviour**

No events (mouseover, mouseout, tap) are fired on straight edges when hovering close to the source node.

**Desired behaviour**

Events should be fired when hovering anywhere on a straight edge

**Minimum steps to reproduce**
In the below example, hover or click on the straight edge. Nothing happens in certain areas of the edge. 

https://codepen.io/anon/pen/NQjaBa
https://jsbin.com/wipabohove/1/edit?html,js,output

Thank you

**Comment by maxkfranz** [comment]
The demo seems OK:

![beam4](https://user-images.githubusercontent.com/989043/62317914-a6d3af00-b468-11e9-9f98-42c54b9e21da.gif)

**Comment by IfatChitin** [comment]
Try hovering from the sides of the edge, as showed in the attached zipped video:
[Cytoscape no events on edge.zip](https://github.com/cytoscape/cytoscape.js/files/3466053/Cytoscape.no.events.on.edge.zip)

**Comment by maxkfranz** [comment]
I can't reproduce what you've shown in the video on Safari, Chrome, or Firefox.

**Comment by maxkfranz** [comment]
Can you reproduce the issue on a different machine or on a different browser?

**Comment by IfatChitin** [comment]
On my machine:
Chrome: reproduced with both jsbin and codepen links.
Edge: reproduced only with the codepen link. 

Different machine:
Chrome: reproduced only with the codepen link.
Edge: reproduced with both jsbin and codepen links.

Hmmm... I'm puzzled. Cannot find a consistency here, except for the codepen link. Could you please try with it? https://codepen.io/anon/pen/NQjaBa
Thanks

**Comment by maxkfranz** [comment]
The codepen.io link works on my Mac.  If the issue is not consistent, then it is likely an OS-specific or configuration-specific issue outside of the control of the library.

**Comment by IfatChitin** [comment]
There is a workaround for this issue. If you set controlPointDistances to '0.001 0.001' or any value close to zero, then the edge will behave like a non straight edge and will receive all event, while being rendered like a straight edge (in some zooms it renders a bit blurry but we can live with that).

Maybe this info can help pointing out the root cause, if it is code related?

**Comment by IfatChitin** [comment]
btw, your graph library is **awesome**! 
We love it as developers (such a convenient and intuitive API with rich ways to customize everything we need) and our customers love it at users (renders super fast and smoothly).
This is the opportunity to say... thank you!

![image](https://user-images.githubusercontent.com/7312074/63081379-232bbf00-bf4c-11e9-8d7f-554bb432c687.png)

**Comment by maxkfranz** [comment]
I was able to reproduce this issue when I copied the codepen graph json into the debug page in the repo.  Try out the cubic-div-by-zero branch.

The best option would be to use `curve-style: straight` for those cases, but maybe the patch is enough.

**Comment by IfatChitin** [comment]
Great, thanks, `curve-style: straight` works!
But I will be happy to use your patch, will wait for a new release.
Thanks!
