### ISSUE TITLE
[Feature request] Collapsible compound nodes

### ISSUE THREAD

**Issue by Ghost---Shadow** [cytoscape/cytoscape.js#2486]
**Issue type**

Feature request

**Description of new feature**

I have a lot of nodes on the screen. Can we have compound nodes which has a + button and it can collapse and expand. Something like tensorboard.

![](https://www.tensorflow.org/images/graph_vis_animation.gif)

**Comment by emiola** [comment]
See [cytoscape-expand-collapse](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse).

**Comment by Ghost---Shadow** [comment]
Thanks!
