### ISSUE TITLE
save nodes position

### ISSUE THREAD

**Issue by shenjichenai** [cytoscape/cytoscape.js#2488]
I want to use this js libraries draw relationship graph.All nodes I had set the position.But when I refresh webpage the node's position would change in the panel ever time.Could you tell me what's wrong,please!

**Comment by Does666** [comment]
Could you please show me you code ? What layout do you use ? 'preset' layout is your case.

**Comment by shenjichenai** [comment]
this is my layout:
`layout: {
                                name: 'cose', idealEdgeLength: 100,
                                nodeOverlap: 20,
                                fit: false,
                                padding: 30,
                                randomize: false,
                                componentSpacing: 100,
                                nodeRepulsion: 400000,
                                edgeElasticity: 100,
                                nestingFactor: 5,
                                gravity: 80,
                                numIter: 1000,
                                initialTemp: 200,
                                coolingFactor: 0.95,
                                minTemp: 1.0
                            },`

**Comment by shenjichenai** [comment]
The problem has been solved.Use the 'preset' layout.Thank you vary much!
