### ISSUE TITLE
Crash due to uninitialized haystack points

### ISSUE THREAD

**Issue by Ghost---Shadow** [cytoscape/cytoscape.js#2490]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version :3.8.2
- Browser/Node.js & version : npm 6.10.2

**Current (buggy) behaviour**
`node_modules/cytoscape/dist/cytoscape.cjs.js`

`ex1 = hpts[0].x;` crashes because `htpts[0]` is undefined

**Desired behaviour**

Change
```
if (styleEnabled && !headless && ele.pstyle('curve-style').strValue === 'haystack') {
        var hpts = rstyle.haystackPts || [];
        ex1 = hpts[0].x;
```
to
```
if (styleEnabled && !headless && ele.pstyle('curve-style').strValue === 'haystack') {
        var hpts = rstyle.haystackPts || [{x:0,y:0},{x:0,y:0}];
        ex1 = hpts[0].x;
```

This fixes the crash

**Comment by Ghost---Shadow** [comment]
https://github.com/cytoscape/cytoscape.js/pull/2491

**Comment by maxkfranz** [comment]
Please post a test case or demo that reproduces your issue.

**Comment by Ghost---Shadow** [comment]
This payload causes the crash on my system. 
https://github.com/Ghost---Shadow/terraform-board/blob/master/src/components/RenderWindow/samples/grouping.js

**Comment by maxkfranz** [comment]
It's working just fine on the debug page: 

![Screen Shot 2019-08-09 at 15 54 28](https://user-images.githubusercontent.com/989043/62805447-04e24100-babe-11e9-8b4d-6ac64839daac.png)


Please provide a demo that reproduces your issue, in the format specified by the issue template.
