### ISSUE TITLE
Feature Request: Radial Tree Layout

### ISSUE THREAD

**Issue by Triet** [cytoscape/cytoscape.js#2493]
**Issue type**

Feature request

**Desired behaviour**
Radial Tree Layout.

**Description of new feature**
While cytoscape.js already has concentric layout, it would be nice to have a radial tree layout where each previous levels are grouped together rather than spread out across the circle. This will greatly reduce edge crossing making the layout look much cleaner.

See example here
https://vega.github.io/vega/examples/radial-tree-layout/

**Comment by maxkfranz** [comment]
This would make a great extension.  Once someone has contributed that extension, it can be added to the list of layout extensions in the documentation.
