### ISSUE TITLE
Consider HTML labels when computing a layout

### ISSUE THREAD

**Issue by josejulio** [cytoscape/cytoscape.js#2497]
**Issue type**

Feature request

**Description of new feature**

Include the HTML labels when running a layout calculation.

I would like to use [HTML labels extension](https://github.com/kaluginserg/cytoscape-node-html-label) and avoid the labels from overlapping other nodes.
Currently the raw labels do take this into account.

I was thinking it could be possible to provide a function to cy that gets triggered by the [boundingBox](http://js.cytoscape.org/#eles.boundingBox) function (I think that's the one used by the layouts to avoid overlap) that receives the raw bounding box, and be able to further extend it depending additional constraints set by the application (in this case, depending the dimensions of the html labels).

The function would look something like:
```javascript
customBoundingBox(
  node, // node for which we are computing its boundingBox
  boundingBox, // current bounding box as reported by **cy**
  options // the same options as eles.boundingBox
) {
  // compute if we need to grown the bounding box
  return boundingBox;
}

// it would work by adding this function to the cy instance, e.g.

cy.boundingBoxDecorator(customBoundingBox); 

```

Would something like this accepted into the code base? any consideration i should take?
If not, what are my alternatives?

**Motivation for new feature**
I want to replace the raw label but still take into account the size of the html labes when computing the layout

**Comment by josejulio** [comment]
I didn't notice that property. I'll check, but from the docs, it seems to only accepts 1 number.,will it grow `n` pixels width and height?
Is the value in pixels size or model position/co-ordinates?

**Comment by maxkfranz** [comment]
> Is the value in pixels or model position/co-ordinates?

Model

> it seems to only accepts 1 number.,will it grow n pixels width and height

Yes

**Comment by josejulio** [comment]
> Does `bounds-expansion` not suffice? http://js.cytoscape.org/#style/background-image

It sorts of works, but not as I would like. It has the following problem:
It adds the `manualExpansion` to both axis on all the directions. For the label, I would like to add a different value on each side (left, right, top, bottom), because the labels are usually wider than taller and it would vary depending on where they are located.

Do you think that it would be possible to implement that `bounds-expansion` behaves something like the css `padding` property?
i.e. If you specify 1 value, it will be for top, right, bottom, and left, but you can specify the 4 in an array: e.g. 
```
bounds-expansion: [1, 2, 2, 1]
```
If more shorthand are needed they could be added.

I would be happy to implement it.

**Comment by maxkfranz** [comment]
That sounds like a great idea.  I considered having two values, but four would be more flexible.  The main thing is that it should not break existing stylesheets, so the single-value shorthand is the most important one to support.

**Comment by josejulio** [comment]
I think we can close this one, bound-expansion support for adding 4 different values is in and we can build other logic around this. thanks!
