### ISSUE TITLE
Configure the modifier key(s) used for (box) selection

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js#2503]
Is it possible to configure the modifier key(s) used for box selection?

For some reason my application wants to use a certain modifier key exclusively for its own purpose. I want this key to have no meaning in Cytoscape.

**Comment by maxkfranz** [comment]
I think it's possible imperatively with something like [Mousetrap](https://craig.is/killing/mice) (or manual listeners) plus `cy.boxSelectionEnabled(false)`.

**Comment by jri** [comment]
OK. I'll see if I can work with that. Feel free to close this ticket.

**Comment by jri** [comment]
This is a more proper description of what I want achieve: I want a certain modifier key not to be used by Cytoscape at all. To my understanding this could be achieved if I could configure 2 things in Cytoscape:

1. The modifier key(s) to be used for additive selection (`addSelectionModKeys`)
2. The modifier key(s) to be used for box selection (`boxSelectionModKeys`)

Do you think Cytoscape should have these config options?

(Alternatively these 2 options could be combined into one: `selectionModKeys`)
