### ISSUE TITLE
Multiple colours for dashed edges

### ISSUE THREAD

**Issue by roballsopp** [cytoscape/cytoscape.js#2508]
**The ability to color an edge or node in a highly custom way**

Currently an edge can only be colored in limited ways. Solid color and gradients are allowed, but the linear gradient can only be made to go one direction, and there is no support for images or repeating patterns, which js canvas is capable of doing. I'm not sure what a good way to include this feature in cytoscape's api would be, but here are a couple ideas:

- Provide a new style property, lets call it `canvasFill`, which is a function that receives the canvas context and returns a valid fill style to be used when coloring an edge or node:
	```javascript
	const styles = [{
	    selector: 'edge',
	    style: {
	        canvasFill: ctx => ctx.createPattern(mySvgImg, 'repeat-x')
	    },
	}]
	```
- Expand the api piecemeal to cover each new case:
	```javascript
	const styles = [{
	    selector: 'edge',
	    // for creating patterns
	    style: {
	        linePatternImg: mySvgImg,
	        linePatternRepeat: 'repeat-x'
	    },
	}, {
	    selector: 'edge',
	    // for creating top to bottom (or any direction) gradients
	    style: {
	        lineFill: 'linear-gradient',
	        ...,
	        lineGradientStopDirection: 'to-bottom'
	    },
	}]
	```
**Motivation for new feature**

I'm using cytoscape.js to draw a type of graph cooked up by some climate change researchers called an "adaptive pathway". In the industry, it seems to be typical to represent the merging of two paths with a dual color, dashed design as seen here:

![image](https://user-images.githubusercontent.com/6366105/63954483-67d15300-ca40-11e9-9035-248cfa010e04.png)

I could also imagine this representation of a merge being drawn as a line that is half one color on top, and half the other color on the bottom, which would be doable with a linear gradient if I could specify the direction of the gradient. There are a couple ways I can think of to hack this sort of functionality with two edges instead of one, but I don't think its quite right to have to alter the structure of my graph to achieve this, and I'd rather it be doable in the style layer.

**Comment by maxkfranz** [comment]
Initial thoughts:

`canvasFill` is an interesting idea, but it's out.  The style properties are renderer agnostic.  We changed rendering technologies early in the project, and I'd really like to keep this ability for future.

I think that a gradient would only work for that usecase if the edges are completely horizontal or completely vertical.  It seems to me that the feature is simply multiple, possibly alternating dashes.  Maybe alternating the multiplicity of some of the dash properties would suffice for that.

Example:

```
line-style: dashed;
line-dash-pattern: [ [1, 1], [1, 1] ];
line-dash-offset: [0, 1]
line-color: [red, blue];
```

**Comment by maxkfranz** [comment]
Out of curiosity, I assume that the vertical tick marks in the figure are nodes?

**Comment by roballsopp** [comment]
Thanks for the response, your dash pattern suggestion would certainly work for me! The vertical ticks are indeed nodes.

**Comment by maxkfranz** [comment]
There are some complications with my example, though:

(1) Each style property is associated with a type.  Each type is defined declaratively.  A type may have attribute `multiple: true` to indicate that it takes on multiple values -- in an array or a space-separated string.  Each multiple (e.g. array) value is assumed to be a primitive type, like a string enum or a integer.  

(2) A string stylesheet doesn't support array notation -- you can only have a single space-separated list.

(3) Each use of `dashed` would have to inspect the inner values to see whether they are arrays or integers.  It might be better to have a separate `line-style: multidashed` value.  This might be more prone to user error, so I'm not sure whether the trade-off would be worth it.

So my original example might look more like this:

```
line-style: multidashed; /* maybe... */
line-dash-pattern: 1 1     1 1;
line-dash-offset:  0,      1;
line-color:        red,    blue;
```

Or in JSON:

```
{
  "line-style": "multidashed",
  "line-dash-pattern": [1,1,    1,1],
  "line-dash-offset":  [0,      1],
  "line-color":        ["red",  "blue"]
}
```

But that doesn't explicitly indicate where the subpatterns terminate.  I suppose we could use a string enum value for this:

```
line-dash-pattern: 1 1 stop 1 1 ;
```

That's in line with the existing specification for types, but it's not as nice visually.
