### ISSUE TITLE
Minor broken link in the edge points docs

### ISSUE THREAD

**Issue by fedarko** [cytoscape/cytoscape.js#2515]
In [this section](http://js.cytoscape.org/#collection/edge-points), the link for `curve-style: unbundled-bezier` leads to `http://localhost:8888/cytoscape.js/documentation/#style/unbundled-bezier-edges`. I'm assuming it's supposed to just lead to `#style/unbundled-bezier-edges`.

Thanks!

**Comment by maxkfranz** [comment]
OK, thanks for posting the issue
