### ISSUE TITLE
When restoring the graph state, labels that contain icons are renamed to 'fn'

### ISSUE THREAD

**Issue by IfatChitin** [cytoscape/cytoscape.js#2516]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.8.4
- Browser/Node.js & version : latest Chrome 

**Current (buggy) behaviour**

When saving the graph state using cy.json() and then restoring the graph state using cy.json(json), labels that contain icons are renamed to 'fn'.

**Desired behaviour**

The state should be restored without changing the labels.

**Minimum steps to reproduce**

In the demo, click on any node and notice the label change.
https://output.jsbin.com/xerowokidu

**Comment by IfatChitin** [comment]
I see, thanks.
I would like to continue setting icons through functions in the style definition, but I also need the zoom , pan and maybe some other properties. 
I believe I will take them from the json and will set them manually.
Thanks!

**Comment by josejulio** [comment]
> I would like to continue setting icons through functions in the style definition, but I also need the zoom, pan and maybe some other properties.

Yes, if only the `styles` are being serialized incorrectly (and you pre-configure them), you can strip it away from the json such as:
```js
const json = cy.json();
delete json.style
// ....
cy.json({'style': preConfiguredStyle});
cy.json(json);
```

That way you save everything but the styles (or anything that can't be serialized) in json format.

**Comment by maxkfranz** [comment]
I would generally avoid calling `cy.json()` with non-serialisable data.  It wouldn’t be congruent with use of `cy.json()` as a getter.  You could replace the `cy.json(style)` call with `cy.style()`.

**Comment by IfatChitin** [comment]
Thanks!
My style doesn't change and it is defined as an object.
This solved my issue in a satisfactory way:

cy.json(json);
cy.style(myPredefinedStyle);
