### ISSUE TITLE
Export network to web page not working correctly.

### ISSUE THREAD

**Issue by bongistka** [cytoscape/cytoscape.js#2517]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.7.2
- Browser/Node.js & version :Chrome

**Current (buggy) behaviour**

when I export to the web page, the styles do not look the same as in the Cytoscape window. I have changed node size to respect the node connectivity, however, when I export, they are all the same size. I tried every browser and have the latest version of each.

**Desired behaviour**

In browser look the same as in the app

**Minimum steps to reproduce**
import any graph
in style change: node size to degree, continuous mapping
export to html

**Comment by maxkfranz** [comment]
For desktop issues, use the desktop site to report a bug: https://cytoscape.org/bug-report.html
