### ISSUE TITLE
Animating an (or along an) edge

### ISSUE THREAD

**Issue by Secretmapper** [cytoscape/cytoscape.js#2518]
- Feature request

**Description of new feature**

It would be great if we can create a label that can be attached/animated along an edge. I think this is not possible right now in the API, though I'd love to be proven wrong!

**Motivation for new feature**

For a project I'm working on, I need to simulate/visualize nodes that are receiving data packets (a network for audio/video), and I need to visualise them. Another example is say trains moving along a network. Here is a good example/animation of the feature:

[On Gfycat](https://gfycat.com/villainousflickeringgrassspider)

![Comp 1 2019-09-14 16_01_09](https://user-images.githubusercontent.com/4077143/64905352-835b7f80-d709-11e9-866d-e9038d841321.gif)

the item should support either text, or maybe shapes as well (i.e. a circle/icon moving)

**Comment by maxkfranz** [comment]
Give cytoscape-canvas or cytoscape-popper a try.

http://js.cytoscape.org/#extensions

**Comment by Secretmapper** [comment]
Hello @maxkfranz, thanks for replying! I've thought of using popper, but my main problem is obtaining the points to position my element.

Looking at the docs, segmentPoints and controlPoints are supported in the API. Is there a utility method that exposes the points along generated by the curve?

**Comment by maxkfranz** [comment]
No, there isn't.  There probably won't be such a function added.  It would be too expensive and inflexible.  Consider a series of quadratic bezier curves.  You can't just use the `t` values as the progression along a curve, as you might want to use the geometric distance instead.  Further, each curve may have a different length.

Different use-cases would require different approximations or approaches, so it's not something that I'd want to make API.  You have access to the resultant points and the equations for beziers and straight lines.  So you have all the information you need to build whatever makes sense for your app.

Further, there are lots of bezier utility libraries on npm and I don't want to duplicate their functionality in this library: https://www.npmjs.com/search?q=bezier

**Comment by Secretmapper** [comment]
Ok, thank you, that makes sense! The references/details are really helpful as well in finding what I need to do
