### ISSUE TITLE
Using Cytoscape.js library with Blazor?

### ISSUE THREAD

**Issue by GeorgeS2019** [cytoscape/cytoscape.js#2519]
Blazor is an up and coming Web technology for C# (Asp.NET.Core - linux & Window) developers

The [video ](https://www.youtube.com/watch?v=4DLS3WflbGE)demonstrate how to integrate a third party JavaScript (**jkanban.js**) into Blazor 

I am posting here perhaps there are developers here who get request to explore interfacing cytoscape.js for c# developers.

**Comment by maxkfranz** [comment]
Thanks for the information.

Things like Blazor and GWT are out of scope for this project.  If those tools want to support Cytoscape.js, that's great.  However, this project won't be adding support for things like GWT or Blazor.

The only language under consideration for support -- other than JS -- is TypeScript.  Eventually, we'll have internally-built TS type definitions.  For now, there are community definitions.

**Comment by GeorgeS2019** [comment]
@maxkfranz 
![msedge_9TK8Zn5xTw](https://user-images.githubusercontent.com/49812372/184341113-b9ee70d4-8c10-4764-8a56-90a60d9f553f.gif)
