### ISSUE TITLE
How to collapse self loop edges?

### ISSUE THREAD

**Issue by git4anjali** [cytoscape/cytoscape.js#2523]
I have multiple self loop edges between same node. I wish to collapse it into one self loop edge. How can I do that?

**Environment info**

- Cytoscape.js version : 3.9.1

I tried following but it displays all the loop edges instead of having just one collapsed one at a distance of 40
```j
         {
            selector: 'edge',
            style: {
              'line-color': 'data(color)',
               width: 3,
              'curve-style':'bezier',
              'control-point-distance':40
            },
          }
```
Please help/guide me.

**Comment by josejulio** [comment]
Have you tried removing the extra edges? Something like (didn't test)
```
const edgemap = {};
cy.$(':loop').forEach(loop => {
   const loopid = `${loop.source().id()}x${loop.target().id()}`;
   if (edgemap[loopid]) {
       loop.remove();
   }
   edgemap[loopid] = true;
});
```
