### ISSUE TITLE
Error when running layout inside a batch

### ISSUE THREAD

**Issue by priomsrb** [cytoscape/cytoscape.js#2528]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.10.0 (latest version)
- Browser/Node.js & version : Chrome + Firefox

**Current (buggy) behaviour**

In certain situations, calling `cy.layout().run()` inside `cy.batch()` causes an error. This specifically happens when a child inside a parent has an edge to another node.

**Desired behaviour**

Running a layout inside a batch shouldn't cause an error. Calling `cy.batch()` should have the same end result as running the commands inside the batch individually.

**Minimum steps to reproduce**

 Here is a minimal example ([codepen](https://codepen.io/priomsrb/pen/LYPXbQK?editors=1001)):

```js
var elements = [
    { data: { id: 'a', parent: 'b' }},
    { data: { id: 'b' } },
    { data: { id: 'c' }},
    { data: { id: 'ac', source: 'a', target: 'c' } },
];

var cy = window.cy = cytoscape({ container: document.getElementById('cy') });

cy.batch(() => {
    cy.add(elements)

    // This next line will cause an error if inside cy.batch()
    cy.layout({ name: 'random' }).run();
});
```

This gives an error message of:

Chrome: `Uncaught TypeError: Cannot read property 'x' of undefined`
Firefox: `TypeError: S[0] is undefined`

**Comment by priomsrb** [comment]
Thank you for the detailed response. I now understand the reasoning for why
this error occurs.

>
Would it be worth updating the documentation of cy.batch() to mention that
layouting should be avoided inside it?

**Comment by maxkfranz** [comment]
Yes, the documentation should be updated.  There should be a whitelist of compatible functions.  There should also be a blacklist that includes functions that are incompatible.  It's probably not practical to make either list exhaustive, but it could at least include the most common ones.
