### ISSUE TITLE
components() method works unexpectedly

### ISSUE THREAD

**Issue by canbax** [cytoscape/cytoscape.js#2533]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.10.0
- Browser/Node.js & version : chrome Version 77.0.3865.90 (Official Build) (64-bit) / v10.16.0

**Current (buggy) behaviour**

I have a collection named `shownElems`. It does not have any element with class named **PRODUCED**. I want to hide disconnected nodes so I execute `let connectedComponents = shownElems.filter(x => x.visible()).components().filter(x => x.length > 1);` After I do that I expect to see subset of the calling. But as could be seen from below image there are elements which does not exist in the original collection `shownElems`
![image](https://user-images.githubusercontent.com/8426741/65491917-ac71d200-deb8-11e9-80a7-2eb32466f874.png)

**Desired behaviour**

`components()` method should give subset of its calling collection

**Minimum steps to reproduce**
I don't know how could I give snapshot of my data to reproduce the issue

**Comment by josejulio** [comment]
When you create an issue, there is a link that you can use to build the reproducer:
http://jsbin.com/fiqugiq

> I don't know how could I give snapshot of my data to reproduce the issue

You can serialize your cy instance by calling `cy.json()`.

**Comment by maxkfranz** [comment]
All I can find is this: https://github.com/cytoscape/cytoscape.js/issues/2538

If you mean something else, you'll have to provide a reproducible test case or demo that shows precisely what you mean.

**Comment by maxkfranz** [comment]
Let's re-open this when the issue is reproducible.
