### ISSUE TITLE
After fetching segments points the edge doesn't update

### ISSUE THREAD

**Issue by DoubleDamn** [cytoscape/cytoscape.js#2537]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version: 3.8.1

**Current (buggy) behaviour**

When selected `curveStyle: segments` add some points on edge, save it, then refresh graph and fetch the saved  segmentDistances, segmentWeights and apply it on edge. The segments are displayed, but impossible move the points or add a new one

**Desired behaviour**

Should be possible to move and add new segment points after fetching saved segments

If this isn't the expected behavior, maybe you know what could be a problem?

**Comment by maxkfranz** [comment]
Please post a reproducible demo of your issue by forking this demo: http://jsbin.com/fiqugiq

**Comment by DoubleDamn** [comment]
Thanks for the answer, the problem was with the plugin 'cytoscape-edge-bend-editing and now it solved!
