### ISSUE TITLE
bounds-expansion only works for first image

### ISSUE THREAD

**Issue by solemnify** [cytoscape/cytoscape.js#2541]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.8.1
- Browser/Node.js & version : 9.11.2

**Current (buggy) behaviour**
When defining background-clip none and defining multiple images that are outside the
bounds of the node's bounding box, only the first offsetted image is properly showing outside the bounds, the rest of the images are still clipped.

**Desired behaviour**
All images that are positioned outside the bounding box should show up.

**Minimum steps to reproduce**
I was able to reproduce this with the following styling:

    {
      'selector': SELECTORS.NODE,
      'style': {
        'shape': 'round-rectangle',
        'content': 'data(label)',
        'border-style': 'solid',
        'background-clip': 'none',
        'bounds-expansion': 20,
        'background-color': 'black'
        'background-offset-x': ['-48%', '48%', '0%'],
        'background-offset-y': [-15, -15, -15],
        'background-image': (element) => {
          return makeNodeBackgroundElements(element);
        },
        'width': 125,
        'height': 25
      },
    },

**Comment by maxkfranz** [comment]
`background-clip: none` is not the same as `background-clip: none none none`.  The first is the same as `['none', undefined, undefined]` and the second is the same as `['none', 'none', 'none']`. 
 Like single-value style properties, multi-value style properties use the default value when unspecified.

In short, explicitly specify your multiple-value style properties.  The indices line up, so if you specify one background image property with three values then all should have three.
