### ISSUE TITLE
Sort a cytoscape collection in place

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js#2545]
**Issue type**
Feature request

**Description of new feature**
Change `eles.sort()` so that it doesn't return a new collection but modifies the old one and returns that.

**Motivation for new feature**
`Array.sort()` works in place and I find it very hard to find errors in my code when some of my collections are arrays, some of them are cytoscape collections, and they have many overlapping methods that have exactly the same name and that work nearly the same but in a slightly different way.

**Comment by maxkfranz** [comment]
All of the API for collections returns a new collection.  The only exception is `merge()` and `unmerge()`, which have strong warnings.  Most people most of the time shouldn't have to use `merge()` and `unmerge()`.

There is `cy.collection()` to get a new collection, so typically you don't have to mix arrays and collections.  You can use only collections.

If you really must mix them, then I think a better solution than modifying the API would be for you to use TypeScript.  That's exactly the sort of benefit that it provides.  There are community type definitions which work in Visual Studio Code.
