### ISSUE TITLE
Release v3.9.3 not appearing in npm

### ISSUE THREAD

**Issue by josejulio** [cytoscape/cytoscape.js#2548]
**Issue type**
Bug report

**Current (buggy) behaviour**

When trying to pull 3.9.3 version from npm, i get the following message

> Couldn't find any versions for "cytoscape" that matches "3.9.3"

**Desired behaviour**

Allow to install version 3.9.3

**Minimum steps to reproduce**

- yarn add cytoscape@3.9.3

I see newer releases, they don't show up on npm as well, but not sure if it is because they were released some minutes ago, but 3.9.3 has over 8 days.

**Comment by maxkfranz** [comment]
It didn't get released to npm last time.  It will be published to npm the
same time as 3.9.4

**Comment by josejulio** [comment]
It appears now, thanks!
