### ISSUE TITLE
When updating a form the edges points position move

### ISSUE THREAD

**Issue by rosaliaam0408** [cytoscape/cytoscape.js#2551]
Bug report

- Cytoscape.js version : 3.11

When updated a form the edges points move a little.

The edges points position is normal in the next image:
![Captura de pantalla 2019-10-02 a la(s) 11 56 34](https://user-images.githubusercontent.com/43282793/66064808-c2604200-e50b-11e9-9ec0-8c69a84a6b82.png)

After updating the form, the edge looks like this:
![Captura de pantalla 2019-10-02 a la(s) 11 56 42](https://user-images.githubusercontent.com/43282793/66064822-cab87d00-e50b-11e9-8101-cb569191dd10.png)

I have verified edge positions, zoom, pan and all the information that nodes and edges have before updating the form and after and they seem to match.

Steps:

I consult two nodes with an edge, I create a bend. Then I update the cytoscape form.

**Comment by josejulio** [comment]
Could you provide a reproducer? https://jsbin.com/fiqugiq/edit?html,css,js,output
