### ISSUE TITLE
JupyterLab support

### ISSUE THREAD

**Issue by anki-code** [cytoscape/cytoscape.js#2552]
Hello Cytoscape Team! Thank you for the great solution!

I want to let you know that [Jupyter project](https://jupyter.org/) is going to replace Jupyter Notebook to more powerful [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) — it is the next-generation web-based user interface for Project Jupyter.

Please update Cytoscape JupyterLab widget - https://github.com/idekerlab/cy-jupyterlab because it is not working now - https://github.com/idekerlab/cy-jupyterlab/issues/5.

Thanks!

**Comment by anki-code** [comment]
😢

**Comment by maxkfranz** [comment]
This library provides a reusable graph component.  That component can be used anywhere on the web, including Jupyter.  You can fairly easily use an HTML code block, for example, to output a visualisation of [data from NetworkX](https://networkx.github.io/documentation/stable/reference/readwrite/generated/networkx.readwrite.json_graph.cytoscape_data.html#networkx.readwrite.json_graph.cytoscape_data).

There are a lot of notebook and notebook-like systems, including Jupyter, Plotly, Polynote, R Notebooks, Observables, Apache Zeppelin, Google Colab, and probably more.  I can't say if or when we will devote resources to support those platforms ourselves, especially considering that the landscape is quickly and constantly changing.  We know that data scientists like notebooks, and we'll take that into consideration in our future planning -- in balance with all of our other priorities and with our available resources.

The Cytoscape.js JSON format is very simple, so it would be great if those platforms took steps to support Cytoscape natively.  [Plotly has done so](https://dash.plot.ly/cytoscape), for example.

If you or anyone else would like to contribute a Jupyter integration for Cytoscape.js, that would be welcome.

Thank you for your interest in Cytoscape.js.

**Comment by anki-code** [comment]
I leave this the link to [QuantStack/ipycytoscape](https://github.com/QuantStack/ipycytoscape) - A Cytoscape Jupyter widget with JupyterLab support.
