### ISSUE TITLE
Feature request: Stop node deselection when clicking the background canvas.

### ISSUE THREAD

**Issue by aledwassell** [cytoscape/cytoscape.js#2553]
**Issue type**
Feature request

**Description of new feature**
Option to stop node deselection when clicking the background canvas.

**Motivation for new feature**
Part of the functionality of my application is to click on a node and a right hand navigation panel opens containing data related to what the node represents.
I have a close button on the panel that also deselects the node.
I am using selectionType: 'additive' and have implemented functionality to click the same node to deselect it but I would like to prevent selected nodes from becoming unselected when clicking the background canvas.

**Comment by josejulio** [comment]
I think you need to handle the selection manually. 
You can manually manage the selections with [eles.unselectify()](https://js.cytoscape.org/#eles.unselectify) and handle the selection from code (with the click/tap events) , [eles.select()](https://js.cytoscape.org/#eles.select) and [eles.selectify()](https://js.cytoscape.org/#eles.selectify)

e.g.

```js
// after cy initialization
cy.elements().unselectify();

// on click, target is our target node.
// turn on the selection
target.selectify();

// if we need to select it
target.select();
// else
target.unselect();

// Ensure we turn off the selection
target.unselectify();
```

See: https://github.com/cytoscape/cytoscape.js/issues/1145#issuecomment-153083828

**Comment by SimonGolms** [comment]
In case someone else comes here and is still looking for a solution - this is my code snippet how I was able to handle it:

```js
// Prevents the unselection of nodes when clicking on the background
cy.on('click', (event) => {
  if (event.target === cy) {
    // click on the background
    cy.nodes().unselectify();
  } else {
    cy.nodes().selectify();
  }
});
```
