### ISSUE TITLE
Edge label still drawn even though edge is completely covered by a node

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js#2563]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.11.0

**Current (buggy) behaviour**

An edge label is still drawn even though the edge is not drawn because completely covered by a node. The edge label is drawn at fixed position 0/0.

The bug occurs only when node size is increased programmatically (in order to cover edge), not when node size is declared in stylesheet.

The bug occurs only when edge style includes both, curve-style `bezier` and text-rotation `autorotate`.

**Desired behaviour**

When an edge is not drawn because completely covered by a node also its label is not drawn.

**Minimum steps to reproduce**

https://codepen.io/jri/pen/qBBPJPR

**Comment by jri** [comment]
@maxkfranz can you confirm this?

**Comment by maxkfranz** [comment]
A patch has been applied to master and unstable.  An issue needs to be created for a 3.11.x backport patch.

**Comment by jri** [comment]
@maxkfranz Fix confirmed. Thank you very much for fixing and releasing!
