### ISSUE TITLE
Edge not drawn anymore when fully covered by a node and then removing the cover

### ISSUE THREAD

**Issue by jri** [cytoscape/cytoscape.js#2566]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.11.0

**Current (buggy) behaviour**

When an edge is visible and then fully covered (by increasing a node's size) and then removing the cover (by decreasing a node's size) the edge is not drawn anymore.

The bug occurs only when all 3 conditions are met:
- the edge gets fully covered
- once the edge is covered a node's position change
- the edge has curve-style `bezier`

**Desired behavior**

Once the cover is removed (by decreasing a node's size) the edge appears again.

**Minimum steps to reproduce**

https://codepen.io/jri/pen/gOOXRyY

**Comment by jri** [comment]
@maxkfranz can you confirm this?

**Comment by maxkfranz** [comment]
A patch has been applied to master and unstable.  An issue needs to be created for a 3.11.x backport patch.

**Comment by jri** [comment]
@maxkfranz Fix confirmed. Thank you very much for fixing and releasing!
