### ISSUE TITLE
wrong link for code release

### ISSUE THREAD

**Issue by jhk0530** [cytoscape/cytoscape.js#2567]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.11.0

**Current (buggy) behaviour**

wrong link

![r](https://user-images.githubusercontent.com/6457691/68044348-80990600-fd1a-11e9-9587-a2e9312ef745.png)

![r2](https://user-images.githubusercontent.com/6457691/68044431-aa522d00-fd1a-11e9-9671-31a4a7ea5a19.png)

**Desired behaviour**

link for version 3.11.0 is wrong 
https://github.com/cytoscape/cytoscape.js/tree/unstable/dist ( 3.5.0 )

which expected link is 
https://github.com/cytoscape/cytoscape.js/tree/master/dist ( 3.11.0 )

**Comment by maxkfranz** [comment]
There is no link to "https://github.com/cytoscape/cytoscape.js/tree/unstable/dist" anywhere in the files in the repo.
