### ISSUE TITLE
Problem while importing in Jest

### ISSUE THREAD

**Issue by gregorybleiker** [cytoscape/cytoscape.js#2570]
I'm trying to write some unit tests with Jest in a project where I am using cytoscapejs. Jest uses CommonJS modules, which is working ok (it is importing cytoscape.cjs.js), but  this file is giving me problems:
`src/heap.js`
When I try to run the tests I get
```
    RangeError: Maximum call stack size exceeded

      at Object.get [as default] (node_modules/cytoscape/src/heap.js:10:20)
      at Object.get [as default] (node_modules/cytoscape/src/heap.js:11:18)
      at Object.get [as default] (node_modules/cytoscape/src/heap.js:11:18)
      at Object.get [as default] (node_modules/cytoscape/src/heap.js:11:18)
      ....
```
I had a look inside and it looks a bit weird to me, as it is importing heap, which should probably import the npm heap package, but the Jest compiler is importing heap.js itsself again which then ends up in a circular (endless) reference loop.
Does anyone know why `heap.js` is at all necessary (why is the referenced module not enough?)

**Comment by maxkfranz** [comment]
This looks like an issue with Jest itself.

**Comment by gregorybleiker** [comment]
Why do you say that, @maxkfranz ? Two infos I should have mentioned in the first post: 
- I am using TypeScript, so the cytoscape libs get imported with the `allowJS` flag set
- If I remove heap.js from the node_modules directory, things seem to work

**Comment by maxkfranz** [comment]
Cytoscape works in CJS environments, and there are automated tests for that.  If you have an issue with Jest, you should file a bug report with Jest.
