### ISSUE TITLE
When I zoom in and out on safari browser of my iphone 7plus, the CY elements disappeared!

### ISSUE THREAD

**Issue by Zfang0620ls** [cytoscape/cytoscape.js#2571]
![demo](https://user-images.githubusercontent.com/16251632/68359386-ada04b00-0156-11ea-8191-3f606741230c.jpg)

**Issue type**

Bug report
Feature request

**Environment info**

- Cytoscape.js version :
- Browser/Node.js & version :

**Current (buggy) behaviour**

**Desired behaviour**

**Minimum steps to reproduce**

**Description of new feature**

**Motivation for new feature**

**Comment by maxkfranz** [comment]
I could not reproduce this on the latest release.  Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.
