### ISSUE TITLE
Feature Request: Providing a overview of the diagram

### ISSUE THREAD

**Issue by binDongKim** [cytoscape/cytoscape.js#2575]
**Issue type**
Feature request

**Description of new feature**
Providing a miniature/overview of the diagram along the diagram.

**Motivation for new feature**
Imagine there are hundreds, thousands of nodes. It probably renders in small size. Users are likely to zoom in to check out certain parts of the diagram. In this case, I think it would be useful to provide a small miniature/overview of the diagram at the same time which could give an info about where you are in the diagram when zooming in so that users don't feel lost in traversing around the diagram.

**Example**
https://gojs.net/latest/samples/orgChartStatic.html

You can see the small piece of the diagram on the top-left corner and it keeps focusing where the user is at that moment.

**Comment by hasanbalci** [comment]
@binDongKim There is a Cytoscape.js extension ([cytoscape-navigator](https://github.com/cytoscape/cytoscape.js-navigator)) for that purpose and here is the [demo](https://raw.githack.com/cytoscape/cytoscape.js-navigator/master/demo.html).
