### ISSUE TITLE
Feature Request: node lvl (ranking)

### ISSUE THREAD

**Issue by tushevskyi** [cytoscape/cytoscape.js#2576]
Issue type
Feature request

Description of new feature
Providing a custom position for nodes in DAG

Motivation for new feature
I'm trying to build a directed acrylic graph with cytoscape.js. The library is perfectly fit for most of the cases, but I need to put node to a specific place that I received from a back-end (it's implemented as a lvl from 0 to n). Is it possible to accomplish with cytoscape?

Example:
https://imgur.com/a/kKg2t0s

**Comment by maxkfranz** [comment]
If the Dagre layout is not sufficient for this use-case, you should contact the developers for that project: https://github.com/dagrejs/dagre

The [dagre layout](https://github.com/cytoscape/cytoscape.js-dagre) is just a wrapper.
