### ISSUE TITLE
Auto close is closing all the good issues

### ISSUE THREAD

**Issue by Triet** [cytoscape/cytoscape.js#2577]
The auto close is closing all the valid enhancement features and doesn't get recorded anywhere.

**Comment by maxkfranz** [comment]
You can still access all of the closed issues by the Github UI: https://github.com/cytoscape/cytoscape.js/issues?q=is%3Aissue+is%3Aclosed

It is more productive to have the issues organised the way they are now:  Active issues are open, and inactive issues are closed.  If an issue is active, then it's either under discussion or in-progress.    A closed issue will be reopened if we implement it or if a third party provides a pull request for it.

By keeping an issue open, it creates the impression that the Cytoscape Consortium is currently working on that issue.  That's a false impression, and that impression discourages third-party contributions.  We're a non-profit group, and we have to consider our resources and priorities in balance with the requests of the community.

Having a lot of open issues also makes it more difficult for someone to see what is active and what is inactive. Having lots of open issues can also be misinterpreted to mean that the library has a lot of reported bugs that aren't fixed.

If there's a particular feature that you think would be a good addition to the library, then in the spirit of open-source software, I encourage you to make a pull request for it.  The Cytoscape Consortium also accepts donations, and those donations could help to allocate more resources to the project.

Thank you for your interest in the library.
