### ISSUE TITLE
Poor animation frame rate on a top end machine.

### ISSUE THREAD

**Issue by jbu4github** [cytoscape/cytoscape.js#2590]
Poor animation frame rate on a top end machine.

Bug report

- Cytoscape.js version : 3.12.1
- Browser/Node.js & version : Chrome 78

I have 6 nodes and have a simple animation that centers the node that I click on using the following code:

```
		cy.on("tap", "node", (event) => {
			cy.animate({
				easing: "ease",
				duration: 1000,
				center: {
					eles: event.target
				},
			})
		})
```

The framerate for said animation is poor. Its very poor. There is noticeable tearing, and I am using a high end gaming machine. I would not expect such a poor framerate for such a basic animation, so I thought there must be something wrong with the way the core lib calls requestAnimationFrame...

A simple pan around the network with a mouse grab demonstrates how canvas panning is updated at a high framerate. What is the animation loop doing that a manual pan is not?

**Minimum steps to reproduce**

http://jsbin.com/fiqugiq

Insert the code snippet above at the end of the js in the jsbin provided, click on a node and notice the poor framerate of the transition.

**Comment by josejulio** [comment]
The link you are using is the "default" one (your changes aren't there) I created a jsbin with your example:

https://jsbin.com/femetetiti

**Comment by jbu4github** [comment]
Thats very helpful thankyou.

I have verified that there are roughly 60 frames being drawn for a 1000s animation (which is what I would expect for a 60fps monitor) which leads me to believe that these frames are not in sync with the refresh cycle of the monitor. requestAnimationFrame function was designed to do this properly, so it must be being delayed incorrectly by the render loop.

**Comment by maxkfranz** [comment]
This isn't reproducible on several machines -- several Macs, a Windows desktop, and a Linux desktop.  Some have Intel integrated graphics, some have AMD discrete graphics.  This sounds like a hardware issue or a driver issue.

We're just using `requestAnimationFrame()` in usual way, which you can verify here:

https://github.com/cytoscape/cytoscape.js/blob/85f0c8dfebc3ed9796651fef43be7ff871db88ce/src/extensions/renderer/base/redraw.js

If you have suggestions to improve the library, pull requests are welcome.

**Comment by jbu4github** [comment]
Hmmm, well I have a gtx 1080Ti and I develop for canvas a lot, and I can visibly see something is wrong with this, where there is not usually.. so I personally think its unlikely a hardware/driver issue. Id get a few more people to have a look at it if I were you :)

**Comment by Dassderdie** [comment]
I tested the animation out of curiosity too on a mid-tier laptop with quite a lot stuff running in the background and didn't noticed any tearing etc. - the animation was very smooth...

**Comment by ksorah1** [comment]
I just downloaded it, it's slower than a simple js, what a pain
