### ISSUE TITLE
Style Error when initializing cytoscape object with JSON config

### ISSUE THREAD

**Issue by javiersoto15** [cytoscape/cytoscape.js#2591]
The issue comes when i want to initialize a cytoscape object, and the JSON configuration fails to parse in the edge selector block. Fails to compile at first try, but if i force a recompilation it works normally (with the error log still in the console)

**Issue type**

Bug report

**Environment info**

- Cytoscape.js version :  3.12.0
- Node.js & version :  13.1

**Current (buggy) behaviour**

The compiler gives me an error in which states that 'text-margin-y' css property is not assignable to property 'Node | Edge | Core' inside the selector case
It goes away once i delete the property
(Happens the same with Klay layout extension)

**Desired behaviour**
For cytoscape to not fail at compiling time, and let me use properties in selector 

**Minimum steps to reproduce**
Create a cytoscape object
```
cy = cytoscape({
container: document.GetElementById('cy')
elements: [
        //nodes
        { data: { id: 'a'} },
{ data: { id: 'b'} },
//edges
    {
      data: {
        id: 'ab',
        source: 'a',
        target: 'b'
      }
    },],
style: [
{
selector: 'edge',
css: {
label: 'data(id)',
'text-margin-y': '-10'}
}]
})
```
Error logs

```
 node_modules/@types/cytoscape/index.d.ts:180:9
    180         style?: Stylesheet[] | Promise<Stylesheet[]>;
                ~~~~~
    The expected type comes from property 'style' which is declared here on type 'CytoscapeOptions'
```
`src/app/graph/graph.component.ts:220:5 - error TS2322: Type '( { selector: string; css: { label: string; 'text-margin-y': string;  }; })[]' is not assignable to type 'Stylesheet[] | Promise<Stylesheet[]>'.`

**Comment by maxkfranz** [comment]
You should file an issue with DefinitelyTyped or tsc, depending on where your issue is.  We don't provide TS definitions.
