### ISSUE TITLE
Compatibility with FontAwesome 5+

### ISSUE THREAD

**Issue by binDongKim** [cytoscape/cytoscape.js#2592]
### Bug report
Icon rendering issue on edge label

### Environment info
- Cytoscape.js version : 3.12.1
- Browser version : Chrome 78.0.3904.108

### Current (buggy) behaviour
Cytoscape.js doesn't seem to be able to render the Font Awesome 5+ icons for edge labels.

### Desired behaviour
Render the icon on edge label

### Minimum steps to reproduce
I've created a simple demonstration about it on [stackblitz](https://stackblitz.com/edit/js-agbuip). And the reason I report this is that I've already referred the [issue](https://github.com/cytoscape/cytoscape.js/issues/1322) and it worked but it just doesn't seem to work with Font Awesome 5+

**Comment by maxkfranz** [comment]
Cytoscape does not do anything special to draw text.  If a particular font does not work, then that's a problem outside of Cytoscape:

- It could be a bug in your app.
- It could be a bug in the font.
- It could be bug in the browser w.r.t. drawing the font in canvas.

Cytoscape works with lots of different fonts, so I can't see this being a problem with Cytoscape.  If there is no bug in your app, then you should file a bug report with Font Awesome or your browser vendor.
