### ISSUE TITLE
No position events are fired for edges

### ISSUE THREAD

**Issue by Dassderdie** [cytoscape/cytoscape.js#2595]
Hi there :)

I want to make something like this: 
```ts
        cy.on('position', 'edge', e => {
            console.log('edge; ' + edge.midpoint().x);
        });
```
I never get any log statements on any graph I tried.

I currently use the following workaround:
```ts
        cy.on('position', 'node', e => {
            (e.target as cytoscape.NodeSingular)
                .connectedEdges()
                .forEach(edge => {
                        // timeout to wait until the new position of the edge has been correctly calculated
                        setTimeout(() => {
                            console.log('edge; ' + edge.midpoint().x);
                        }, 10);
                    }
                });
        });
```

**Comment by maxkfranz** [comment]
An edge has no `position` value or event.  You must listen to nodes instead.

**Comment by maxkfranz** [comment]
@Dassderdie, I believe that the `setTimeout()` ought to be unnecessary.  It indicates a potential issue.  I will investigate tomorrow.

**Comment by maxkfranz** [comment]
@Dassderdie 

The following issue should resolve the issue re. `setTimeout()`: Renderer-calculated style values for an edge may not be fresh on call to getter #2608

**Comment by Dassderdie** [comment]
Thank you for your awesome work :)

I still think such a workaround is not ideal, but I can understand that this library's data model is more about nodes than edges if you can say so.

**Comment by maxkfranz** [comment]
Perhaps in future there could be an event for general dimension changes
(incl. width, position, computed points like control points, etc.).  With
the current API, you have to listen to the nodes for implicit bounds
updates to edges.

The `setTimeout()` bit was definitely a hack and should not be necessary
anymore with the patch.
