### ISSUE TITLE
A label may be cut off if it contains two or more whitespace characters in a row

### ISSUE THREAD

**Issue by IfatChitin** [cytoscape/cytoscape.js#2596]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : latest
- Browser/Node.js & version : latest chrome

**Current (buggy) behaviour**

Node labels get cut when prefixed with an icon and two spaces or more.
Issue doesn't happen when there is only one space between icon and text.

**Desired behaviour**
Node labels shouldn't get cut

**Minimum steps to reproduce**
You can see that the node labels are cut in https://jsbin.com/zazoyodosa.
When changing from two spaces to one, the labels are not cut.

**Comment by maxkfranz** [comment]
Thanks for reporting the issue.  I’ll review it once I’m back on 6 January.

**Comment by IfatChitin** [comment]
Tried with 3.13.0, it works great!
Thank you for your quick fix :)

**Comment by maxkfranz** [comment]
Great.  Thanks for the update
