### ISSUE TITLE
Outside-to-line-or-label intersects towards the centre of label rather than the centre of the node

### ISSUE THREAD

**Issue by AdrienClairembault** [cytoscape/cytoscape.js#2597]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.12.1
- Browser/Node.js & version : Firefox 71.0 (64 bits)

**Current (buggy) behaviour**

`outside-to-line-or-label` rule for `target-endpoint` and/or `source-endpoint` styles behave incorrectly if the path between the node and the label is shorter than the distance between the two nodes:

![image](https://user-images.githubusercontent.com/42734840/71477048-3b5bf680-27e8-11ea-8ccd-75936de2254f.png)

Same problem for the `outside-to-node-or-label` rule.

**Desired behaviour**

Quoting the documentation, the goal of this rule is to ["... avoids overlap of edges with node labels"](https://js.cytoscape.org/#style/edge-endpoints).

In the previous example, there is no possible overlapping as the nodes are side by side with the labels at their top. 

The results should be a "normal" edge like this:

![image](https://user-images.githubusercontent.com/42734840/71477157-c210d380-27e8-11ea-8844-104f613adf61.png)

**Minimum steps to reproduce**

https://jsbin.com/tokuzaw

Use a graph with non-center-center labels and `outside-to-line-or-label` rule in your style.
If the path between the label of a node and another linked node is shorter than the distance between the two nodes themselves then the edge will bind itself to the label without checking if there is an actual overlap of the edge with a label.

**Comment by maxkfranz** [comment]
After 9efdaf2:

![beam15](https://user-images.githubusercontent.com/989043/72018339-74a75400-3235-11ea-9268-3b0078975fed.gif)

**Comment by AdrienClairembault** [comment]
I just tested your fix using the latest release (3.13.0) and I confirm that it works as expected.
Thanks for the quick fix!

**Comment by maxkfranz** [comment]
Great.  Thanks for following up
