### ISSUE TITLE
Hypergraph support

### ISSUE THREAD

**Issue by epideveloper** [cytoscape/cytoscape.js#2604]
Feature request

Is any work being done to add support for hypergraphs?

**Comment by maxkfranz** [comment]
Do you mean hyperedges specifically?  Compound nodes already create a kind
of hierarchical hypergraph.

**Comment by epideveloper** [comment]
@maxkfranz is their native support for compound nodes within cytoscape? If so, are you able to point me to some documentation?

**Comment by maxkfranz** [comment]
It's throughout the documentation: https://js.cytoscape.org

Because the documentation is all one page, you can just control-f to find whatever you want.

https://js.cytoscape.org/#notation/compound-nodes
