### ISSUE TITLE
Consistent node positions between different graphs

### ISSUE THREAD

**Issue by Kryptiique** [cytoscape/cytoscape.js#2605]
**Issue type**

Feature request

**Description of new feature**

This is more of a question than a feature request.

I have many graphs that a user can switch between, each with data updated through a websocket. When the user goes from Graph A to Graph B, then back to Graph A, I want the nodes in the graph to be in the same position as was calculated before. Is there anyway to keep the physics simulation in the layout from completely randomizing the location of every node without having multiple Cytoscape objects in memory? Perhaps maybe giving some sort of seed?

**Motivation for new feature**
With graphs that are visited many times in a short time span, it would be nice to not have to figure out where each node ends up with every iteration

**Comment by maxkfranz** [comment]
You can lock nodes, but that probably will reduce the quality of the second
force-directed layout.  If you overconstrain a force-directed layout, then
the system likely won't reach a desirable equilibrium.

It's usually better to animate the old nodes to the new positions,
especially by `animate: 'end'`.
