### ISSUE TITLE
Allow taxi distance to be specified relative to the target node

### ISSUE THREAD

**Issue by ofir130** [cytoscape/cytoscape.js#2606]
**Issue type**

Feature request

**Description of new feature**

Enhance taxi edges so that **taxi-turn** would accept an absolute distance from the target (could be a negative number as currently, positive number is the absolute distance from the source)
```
{
  selector: 'edge',
  style: {
    'curve-style': 'taxi',
    'taxi-direction': 'rightward',
    'taxi-turn': '-15px', // negative numbers used to denote distance from target
  }
}
```

![www draw io_](https://user-images.githubusercontent.com/58131874/72969528-519ca880-3dce-11ea-992c-cb79a3a1b4f1.png)
* red line is the current implementation while the dotted line is how I wished it would render

**Motivation for new feature**

Have more control over the edges rendering

**Comment by maxkfranz** [comment]
This sounds like an interesting feature.  Would you be interested in making a pull request for it?  I could direct you towards the relevant files and functions.

**Comment by ofir130** [comment]
Sure, thanks

**Comment by herzaso** [comment]
https://github.com/cytoscape/cytoscape.js/pull/2612
