### ISSUE TITLE
Feature Request: circle-shaped compound nodes

### ISSUE THREAD

**Issue by zhjuve** [cytoscape/cytoscape.js#2621]
Hello, would be great to have circle-shaped compound nodes for better display of sets of common objects, no compound internal layout required except may be hexagon-like one for nice ordering. See SemSpect project for example.

**Comment by maxkfranz** [comment]
A compound node's dimensions are defined by the bounding box of its children.  Therefore, the shape of a compound node is restricted to a rectangle.

See also https://github.com/cytoscape/cytoscape.js/issues/2129
