### ISSUE TITLE
Advice: Manual edge drawing: straight + arc + straight  in a concentric layout

### ISSUE THREAD

**Issue by kiryph** [cytoscape/cytoscape.js#2627]
I have created with the LaTeX package **Ti*k*Z** following concentric layout of a Bärnighausen graph:

![Screenshot 2020-02-08 at 17 16 54](https://user-images.githubusercontent.com/371756/74088462-0c979800-4a97-11ea-9d6d-b741705911a0.png)

This is a directed graph indicating symmetry group-subgroup relations in crystallography.

As you can see I have chosen to draw edges with an arc plus a radial pointing straight line
The edges of the most inner nodes are simply straight lines.

Can I draw edges in such a way manually in cytoscape.js?

In tikz this looks like
```tex
\path (nodeA) -- (calculated pos) arc[start angle=, delta angle=] -- (calculated pos) -- (nodeB);
```
I have already calculated all positions and angles for the nodes, straight segments and arcs of the edges and the positions of the edge label.

Possibly, I need only a general drawing lib like d3.js.

I am a completely noob to cytoscape.js.

### *Motivation & Background*

I would like to recreate this picture in an html document to have interactive features (hover, adjust visibility of rings, show/highlight subgraphs, etc.), ultimately in a presentation.

Initial data is a graphml file. Each node has a subgroup index which determines its radius. I have written a python script which determines the angle of each node based on an ordering scheme following crystallographic considerations. Also the script calculates the tikz path based on a few parameters I can give for each edge.

I would add the node pos, edge path and edge label to the graphml file which I might be able to read in with the plugin [cytoscape.js-graphml](https://github.com/iVis-at-Bilkent/cytoscape.js-graphml) or [graphml-moddle](https://github.com/bpmn-io/graphml-moddle).

The edge drawing has been already quite tricky in LaTeX and required many manual adjustments (for edges and edge labels).
Therefore I would like to reuse the paths I have determined in Tikz and draw manually the edges in cytoscape.js. However, I am not yet sure how I should export the paths. The node and edge label position are simple.

**Comment by maxkfranz** [comment]
In Cytoscape, one aim is for things to be as easy and automatic as possible.  It looks like you've put a lot of manual effort into making your graph look a particular way with Tikz.  Given that, I think it would probably take a lot of effort to translate your Latex specification into input that Cytoscape or D3 can use -- especially if the goal is for things to look exactly the same.

Cytoscape is good if you have graph data and you want things to be easy and mostly automatic.  You also get a graph model with Cytoscape, so things like neighbourhood highlighting are easy.   D3 is typically good if you want to build a highly customised SVG visualisation more or less from scratch, with manual control over almost all details.  If you just want your existing figure on the web and it already exists in Latex, then it might be easiest to simply output the figure as SVG using Latex (or convert the postscript/PDF to SVG).

It might be easier in future to start with a web-based tool, like Cytoscape or D3, and then export that web figure to be included in your Latex document.

In terms of Cytoscape features, this could motivate a manual path property for edges, like `edge-path: line(blah, blah) bezier(blah, blah) etc...`.  This may tie in with @herzaso's [comments](https://github.com/cytoscape/cytoscape.js/issues/2607#issuecomment-583019937) regarding more manual edge control.  Though it might work for static graphs, an edge style like that generally wouldn't work well for dynamic graphs.  In any case, it must be agnostic to the underlying rendering technology.

As an aside, is this figure for a paper?  May I read it?
