### ISSUE TITLE
DOM Html labels append in the body 

### ISSUE THREAD

**Issue by Gianlca** [cytoscape/cytoscape.js#2628]
**Environment info**

Cytoscape.js version : 3.10.0
Angular 5

Current behaviour
DOM element append to the body to render labels for node. This DOM elemet is duplicate everytime the component is created  in a SPA.
![example](https://user-images.githubusercontent.com/8105828/74219985-98cfd800-4cae-11ea-9194-2aa921da75e1.png)

Desired behaviour
Remove the DOM element everytime the component that has been used to render a graph is destroyed.

**Comment by maxkfranz** [comment]
I responded to this by email, but I suppose it got dropped by Github.  Do you have a reproducible test case or demo?  This wasn't reproducible on the test pages in the repo.
