### ISSUE TITLE
Configurable background-image error handling

### ISSUE THREAD

**Issue by umdstu** [cytoscape/cytoscape.js#2629]
Issue type:

Feature request

Description of new feature:

1) Disable throwing errors on failed image loads completely.  ...or...
2) Add a configuration option to override whether an error is thrown when an image URL is passed that does not exist. 

Motivation for new feature:

Currently if you pass a bad/missing background-image url for a node, after the graph renders, a DOMException error occurs, breaking the entire graph functionality.

`ERROR DOMException Failed to execute 'drawImage' on 'OffscreenCanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.`

However, if you go into the image.js file and modify the error event listener to set `image.error = false`, the failed images are logged but the graph continues to run properly.

Thanks for the consideration

**Comment by umdstu** [comment]
It seems I may have been mistaken in the solutions prorposed. Even if setting the error to false, errors still happen. The error is a hint of what's happening.

If the graph is suffiiciently zoomed out when the images are rendered, no error is thrown. But if you resize your window so that not all of the canvas is in frame, the error occurrs because the failed image is offscreen, hence **OffscreenCanvasRenderingContext2D** error.

I do not yet have a lead on a solution.

**Comment by maxkfranz** [comment]
If you specify an invalid image, the browser throws an error on invalid images -- not Cytoscape.

It seems the only reliable workaround for invalid input might be be a try-catch around the draw call.  However, using try-catch would negatively impact performance.  I'm not sure whether the convenience to consumers who specify invalid images outweighs the performance impact for consumers who specify proper images.

To consider a change like try-catch, I'd like to see an image-heavy graph benchmark -- one with try-catch and one without.  Maybe performance enhancements to the library made after the addition of the background-image feature would make try-catch's impact minimal.

@umdstu, are you open to making this benchmark?

**Comment by umdstu** [comment]
@maxkfranz Sorry for the delay.

I haven't had a chance yet to  run any performance metrics on how this would work with try/catch blocks.

As a temporary work-around, I ended up creating a 1pixel transparent png that is set by default, and only updated if the image assigned to that node exists. It's not perfect, as a image for for some reason not load, but as I said, it's temporary.

I'll work on that benchmark for sure.
