### ISSUE TITLE
edge.renderedControlPoints for loop do not give true representation of edge

### ISSUE THREAD

**Issue by felicity-iz** [cytoscape/cytoscape.js#2631]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.13.0
- Browser/Node.js & version : 6.13.4

**Current (buggy) behaviour**

I am retrieving the rendered Control Points for a loop edge (2 control points as specified in documentation) with edge.renderedControlPoints() and receive an object array (2) with two points as expected which I want to use to create an svg Path following the loop path cytoscape draws.

my problem:
the documentation states that the loop curve is a quadratic bezier - but that would mean I could use only one control Point which doesn't give me a loop only a curve.

so I am building a cubic bezier curve that takes two control points, and gives a loop edge -
BUT this loop edge doesn't fit the actual loop edge computed by cytoscape. It is too small.
![image](https://user-images.githubusercontent.com/17249253/74731477-b8d43e00-5250-11ea-99f9-11f48d97e0f5.png)

Any pointers as to how the real edge loop is calculated?

**Desired behaviour**

return controlPoints for a cubiq bezier curve that fits the actual loop edge

**Comment by somedmguy** [comment]
> I am retrieving the rendered Control Points for a loop edge (2 control points as specified in documentation) with edge.renderedControlPoints() and receive an object array (2) with two points as expected which I want to use to create an svg Path following the loop path cytoscape draws.

2 control points for 2 line segments (as also specified in the documentation)

> Each bezier edge consists of one **or more** quadratic bezier curves.
> ...
> curve-style: bezier (loop) : 2 points for **two quadratic beziers**
> ...
> Notes:
> ...
> - For an unbundled bezier edge, the point that joins two successive bezier curves in the series is given by the midpoint (mean) of the two control points. That join point specifies P2 for the first bezier, and it specifies P0 for the second bezier.

The note only specifies unbundled bezier, but I suspect it generally applies where n > 1.

**Comment by maxkfranz** [comment]
> The note only specifies unbundled bezier, but I suspect it generally applies where n > 1.

Yes, this might be revised to something like "for a bezier edge with multiple control points".
