### ISSUE TITLE
Is it possible to add a small half circle when 2 edges cross in chart?

### ISSUE THREAD

**Issue by hthuyfedev** [cytoscape/cytoscape.js#2632]
Sometimes user will get confused
Can I add half circle to make edge is not overlap with each other as picture below?
![Screenshot_2](https://user-images.githubusercontent.com/61217426/74899261-f52da880-53ce-11ea-8a22-5562ae91df4a.png)
Thanks!

**Comment by umdstu** [comment]
I think this would be really cool. While researching the feasibility of your question I came across this d3.js demo that i'll leave here for reference: https://bl.ocks.org/bricof/f1f5b4d4bc02cad4dea454a3c5ff8ad7

It seems technically it's possible, however I dont know enough to tell how performant it would be. For some reason I get the feeling it would be expensive, but @maxkfranz would have to weigh in here when his time allows.

**Comment by maxkfranz** [comment]
That kind of feature would be expensive generally, especially so if there are many edges.  It looks simple for right-angled edges, but this library supports many edge types.

If you, @hthuyfedev, are interested in this feature, would you be interested in putting together a proposal?  If you're interested in implementing this feature, then we should start with a specification that includes details about the precise behaviour and the API.

**Comment by maxkfranz** [comment]
Aside: Most people just use semitransparent edges for this use case.
