### ISSUE TITLE
Is the grid layout supposed to link only two nodes?

### ISSUE THREAD

**Issue by marimeireles** [cytoscape/cytoscape.js#2634]
Hi!
I'm using the grid layout and I used [this](https://js.cytoscape.org/demos/linkout-example/) code as a base, but I couldn't like more than two edges together.

This code:
```
data = {
    'nodes': [
      { 'data': { 'id': 'desktop', 'name': 'Cytoscape', 'href': 'http://cytoscape.org' } },
      { 'data': { 'id': 'a', 'name': 'Grid', 'href': 'http://cytoscape.org' } },
      { 'data': { 'id': 'b', 'name': 'Cola', 'href': 'http://cytoscape.org' } },
      { 'data': { 'id': 'c', 'name': 'Popper', 'href': 'http://cytoscape.org' } },
      { 'data': { 'id': 'js', 'name': 'Cytoscape.js', 'href': 'http://js.cytoscape.org' } }
    ],
    'edges': [{
            'data': { 'source': 'desktop', 'target': 'js' },
            'data': { 'source': 'a', 'target': 'b' },
        }]
  }
```

Produces this output:
<img width="623" alt="Screen Shot 2020-02-21 at 4 07 55 PM" src="https://user-images.githubusercontent.com/17600982/75045869-f1c41b00-54bb-11ea-8464-8a155030e888.png">

Is this expected?
Thanks!

**Comment by somedmguy** [comment]
There's an error in your edges json.  You have 1 edge with its 'data' defined twice instead of 2 edges each with their own 'data'.

**Comment by marimeireles** [comment]
Sorry for the stupid issue... Didn't see it.
Thanks a lot!
