### ISSUE TITLE
Adding node to compound node at (x, y) moves/centers the compound node at (x,y) as well

### ISSUE THREAD

**Issue by umdstu** [cytoscape/cytoscape.js#2643]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version : 3.14.0
- Browser/Node.js & version : Chrome 78, Node 10.16

**Current (buggy) behaviour**

When adding a node to a compound node, the compound node will re-center at the child nodes position.

**Desired behaviour**
The added node stays at it's position, and the parent remains centered at it's position.

**Minimum steps to reproduce**

Create a compound node at X,Y, then add a node to a position anywhere in the bounds of that node and set it's parent to the first node.

```js
var parent = this.cy.add({
  group: 'nodes',
  data: {
    parent: undefined
  },
  position: {x: 500, y: 300}
});
this.cy.add({
  group: 'nodes',
  data: {
    parent: parent.id()
  },
  position: {x: 510, y: 300}
});
```
My goal is to ensure the group does not jump on the canvas, and ideally, only grows in the right/downward direction. My guess is this would be possible if position was based on the top left corner rather than the center. I've given up trying to find in the source code that triggers this repositioning (in an effort to prevent it).

**Comment by maxkfranz** [comment]
This looks like expected behaviour.

>  A compound parent node does not have independent dimensions (position and size), as those values are automatically inferred by the positions and dimensions of the descendant nodes.

Ref: https://js.cytoscape.org/#notation/compound-nodes

**Comment by umdstu** [comment]
Hi @maxkfranz 

I do recall reading that, yet the behavior still seems weird. Is there a way to disable this? The documention mentions how expensive compound nodes are, and to not use them if not absolutely necessary. Would it not be practical to have a configuration option to disable the constant watching/drawing to improve performance when they were necessary and many (if one so desired).

**Comment by somedmguy** [comment]
I just want to clarify a potential misunderstanding.
> When adding a node to a compound node, the compound node will re-center at the child nodes position.

That's not true.  Technically, what you have here isn't "adding a node to a compound node" it's "converting a normal node to a compound node by giving it a child".  That difference is important, and it may be the source of your feeling that this is "weird" behavior.  As you add more children, the existing children won't move but the compound node will grow to encompass all of its children.

**Comment by umdstu** [comment]
My apologies for the delay. 

I understand what you're saying, I just worded it poorly. And yes as you add more children it grows as you describe. Perhaps this behavior is part of the core concept of the library, but what I expect, or rather would like to see happen, is the compound node (optionally?) retain its shape to a degree.

For example, in the beautiful sbgn-cytoscape-stylesheet (https://pathwaycommons.github.io/cytoscape-sbgn-stylesheet/), if you move the top-left ca2+ node in the right-most compound node to the right, the compound node shrinks (As you say, intentionally), but it breaks the 'layout' if you will, the padding between the nodes is now inconsistent. I like that the compound 'grows' as you move nodes in either direction, but setting some sort of min width/height would perhaps allow it to remain a size if the node is pulled away from that edge.

Hope that makes sense.

Thanks for reading.

**Comment by maxkfranz** [comment]
That the compound parent’s dimensions are defined by the bounds of its descendants is an invariant.  To constrain the parent, therefore, the descendants must be constrained.

I agree that a change in position of a compound node can potentially ‘break the layout’, but this can happen for any kind of node.  That doesn’t justify, in my opinion, the introduction of specific constraints on compound descendants within the library.  Those constraints are best left to the judgement of the app author, and those constraints may be applied by position rule sets (e.g. via automove).  Re. minimum dimensions, the library already supports padding biases.

**Comment by umdstu** [comment]
Thank you both for weighing in on this, I understand the logic a bit better now. 
I have certainly implemented some of the changes you mention (applying minimum height/width so compartments can be created arbitrarily (without having to add a child to it first), played with the padding some, etc., allow to resize them with the node-resize plugin). The only thing I have been unable to accomplish was the behavior I described above for the sbgn-stylesheet layout 'breaking' as we're calling it (i know it's expected behavior at this point). 

I'm wondering though, if the `locked: true` property could/should perhaps be leveraged to lock a compartment in place, not just from being dragged, but from resizing. Technically it wouldn't be introducing new constraints (locked is already a concept in the library), but expanding an existing one. 

I guess at this point it's safe to say that this is no longer a bug but a feature request, but I get the feeling this is still going to be a 'no'.

Thanks for your consideration. If not, I'll move this to stackoverflow and hope someone has enough understanding of the library (besides you 😓) to point in me to the right place to implement this.

**Comment by maxkfranz** [comment]
I suppose that in a way it may make sense for the semantics of `locked: true` to include compound descendants.  Moving a descendant may change the position of an ancestor:  If the ancestor is locked, you might expect for the dragging to be forbidden.  

It's not black and white, though.  Locking is normally just on or off completely, whereas this proposed behaviour is different:  With the same `locked: true` state on a parent, it can sometimes be OK to drag a child and sometimes not.  It depends on where the child is dragged.

For now though, I'd encourage you to experiment with the automove extension.  I think it includes a built-in rule for restricting a node within a bounding box.  That sounds a lot like what you're talking about.
