### ISSUE TITLE
Configurable modifier keys

### ISSUE THREAD

**Issue by umdstu** [cytoscape/cytoscape.js#2645]
**Issue type**

Feature request

**Description of new feature**

Allow modifier keys for multiSelect to be configurable. Not all three keys need to be taken up. So many options is actually kind of confusing. 

**Motivation for new feature**
Making these configurable would enable developers to use the modifier keys for additional functionality by disabling one or 2 of the three modifier keys used for multiSelect.

I'd be willing to work on this if you would take a PR.

I know this has been asked for more than once in the past, but I still think it would be cleaner to make this configurable within cytoscape.js itself.

**Comment by maxkfranz** [comment]
The complicating problem here is that different systems have different conventions for which modifier keys trigger box selection or additive single-click selection.

On Mac, you use command.  On Windows, you use control.  You can use shift in certain cases on both Mac and Windows.  Some desktop apps, regardless of OS, use shift.  So there are many conventions, and the expectation for which key to use can vary from user to user.  The library currently allows any of those keys to trigger multiple selection mode so that things work as expected for any user.

**Comment by umdstu** [comment]
I totally get it, I develop on both a Mac and a PC as well.
However the environment dramatically changes when you're dealing with an enterprise. I'm currently wrapping an app around cytoscape.js, and I know all of my customers are on the same baseline.

What you describe makes total sense when you have computer/data scientists all using cytoscape.js for their own personal projects, each one would not want to think about which OS they're on and which key to use. But when you control the environment, that scenario is gone.

So as you suggested in another thread, the keyboard events can certainly be captured by ones application and enabling/disabling the multiSelect, but it adds to the complexity of the application and requires additional checks in the code when I want to use those other modifier keys for other things (and I have to some degree done this). But I just think it would be cleaner to build this as a configurable option (not specify a single key by default) into cytoscape.js. I imagine I can't be the only one wrapping something around the cytoscape.js library for users rather than themselves.

Hope this gives you convincing scenario, but if not I understand.

**Comment by maxkfranz** [comment]
I appreciate your motivation for this feature, but I think a line has to be
drawn for what goes in the core library and what does not.  The trade-off
is between having a library that is simple and easy to use and having a
library that has every possible feature someone could want.  I think the
former is more important than the latter, especially for features that
effect a minority of consumers.

That being said, the feature you described could be packaged as an
extension by adding logic on top of existing behaviour:  Disable selection
unless specific modifier keys are pressed.  That way, your feature is
reusable but it does not introduce complexity into the core lib itself.

**Comment by umdstu** [comment]
I understand your position as well. Please go ahead and close this out then.

**Comment by maxkfranz** [comment]
OK, if you end up having a reusable extension, please post it here.  Even if you don't go that far, it would be great if you would post relevant code snippets from your app.  Someone else who's interested in the feature might build an extension based on those snippets, if you're not able to build one.  Thanks
