### ISSUE TITLE
bug: ele.json(obj) removes parent when it's not set in obj.data

### ISSUE THREAD

**Issue by iliazeus** [cytoscape/cytoscape.js#2653]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.14.0
- Browser/Node.js & version : nodejs v12.16.1

**Current (buggy) behaviour**

`ele.json(obj)` removes `parent` if it's not set in `obj.data`. This behavior is unexpected, since in the docs, it sais that `obj` can be a "patch object", where only the fields that  need to be changed are specified.

**Desired behaviour**

Either `ele.json(obj)` should not modify the parent, or it should be documented

**Minimum steps to reproduce**

https://jsbin.com/yemacugohe/edit?js,output

```js
const cy = cytoscape({
  elements: [
    { data: { id: 'parent-node' } },
    { data: { id: 'child-node', parent: 'parent-node' } }
  ]
});

cy.$id('child-node').json({ data: { foo: 'bar' } });
```

**Comment by maxkfranz** [comment]
Assuming the documentation is correct, there should be a distinction between `null` and `undefined`.  Perhaps it’s just checking for a nully value rather than `null`.

This may also affect the `source` and `target` fields.

**Comment by iliazeus** [comment]
For `source` and `target`, `null` and `undefined` are treated equally: the corresponding fields are not modified.

https://github.com/cytoscape/cytoscape.js/blob/88e8e9d574f1c3b0ff162a6b67bb5a46d1df941a/src/collection/index.js#L221

https://github.com/cytoscape/cytoscape.js/blob/88e8e9d574f1c3b0ff162a6b67bb5a46d1df941a/src/collection/index.js#L226

But for the `parent` field, there is something weird going on:

https://github.com/cytoscape/cytoscape.js/blob/88e8e9d574f1c3b0ff162a6b67bb5a46d1df941a/src/collection/index.js#L237-L240

It looks like, for some reason, `undefined` parent is _explicitly_ treated the same as `null`.

**Comment by iliazeus** [comment]
And also, apparently, there are tests that expect this behavior:

https://github.com/cytoscape/cytoscape.js/blob/812a17ed22dd20f5d6286080f5cc1634e7fd644d/test/core-graph-manipulation.js#L693-L719

**Comment by maxkfranz** [comment]
On second thought, the analogy to `source` and `target` is specious.  You should never be able to use null or undefined for those fields in the first place.

I suppose there could be a case to be made for supporting explicit `{ parent: undefined }`, though `null` seems like a more appropriate value.  I could see someone calling `ele.json({ 
parent: undefined })` even though it doesn't make as much sense as `null`.  In any case, it probably doesn't make sense to include the implicitly undefined case (i.e. the `parent` key is undefined). The semantics for `data` in `ele.json()` and more generally in `ele.data()` are to only include specified keys (as in `Object.keys()`), so something like `ele.json({ foo: 'bar' })` shouldn't affect the `parent` field at all.
