### ISSUE TITLE
Zoom broken when panning disabled

### ISSUE THREAD

**Issue by umdstu** [cytoscape/cytoscape.js#2655]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version : 3.14.1
- Browser/Node.js & version : Chrome 79, Node 10.16.0

**Current (buggy) behaviour**

Zooming does not work when panning is disabled. The documentation does mention that when panning is disabled, that boxSelection is the default behavior without modifier keys, so I am assuming if this was expected behavior it would have been similarly documented.

**Desired behaviour**

Zoom should still work even though panning is disabled.

**Minimum steps to reproduce**
Simply set `panningEnabled` to false in the configuration, or call it at any point later on.

```js
var cy = window.cy = cytoscape({
          container: document.getElementById('cy'),
          panningEnabled: false
});
```

```js
cy.panningEnabled(false);
```

**Comment by maxkfranz** [comment]
It’s not possible to zoom about a point without applying both a scale transformation (i.e. zoom) and a translation transformation (i.e. pan).

**Comment by umdstu** [comment]
Seems reasonable. It just wasn’t document so i wasn’t sure if it was intentional or not. Thanks for explaining.
