### ISSUE TITLE
Relatively high cpu usage when idle

### ISSUE THREAD

**Issue by TimNZ** [cytoscape/cytoscape.js#2656]
Chrome latest, OS X, Macbook Pro 2013 quad core 2.3ghz.
View any of the demos from the home page, and CPU is about 4-5% when idle and tab active/visible
Vis Network examples sit below 1% when the tab is active.

Seems high.

**Comment by TimNZ** [comment]
I ran the Chrome DevTools profiler, and narrowed down cpu usage
to redraw.js: startRenderLoop()
https://github.com/cytoscape/cytoscape.js/blob/unstable/src/extensions/renderer/base/redraw.js

As a test I changed code from:

```
} else {
      beforeRenderCallbacks( r, false, requestTime );
    }

    r.skipFrame = false;

    util.requestAnimationFrame( renderFn );
```

to

```
  r.skipFrame = false;
  util.requestAnimationFrame( renderFn );
} else {
      beforeRenderCallbacks( r, false, requestTime );
      setTimeout(function() {
           r.skipFrame = false;
           util.requestAnimationFrame( renderFn );
          },200);
    }
```
My aim being simply to have the tight loop taking less CPU time.
Now drops to 0.7% CPU when idle, 
with little impact on render performance when doing things.

This is the total of my animation experience.
I have no idea what other impact this could have, just wanted to debug CPU utilisation.

**Comment by kawazoe** [comment]
I have noticed the same issue. It is killing battery life on mobile devices as it allocates around 40MB of data per minute and keeps the CPU busy.

Instead of tweaking memory timing, I would suggest that the renderer shouldn't even request a frame unless changes are actually needed.

**Comment by maxkfranz** [comment]
> Seems high.

Ordinary sites -- like the [Wall Street Journal](https://www.wsj.com), [Yahoo Finance](https://finance.yahoo.com), or the [Financial Post](https://business.financialpost.com) -- have higher CPU usage than the Cytoscape demos.  Web apps like Gmail and Google Drive have even higher CPU usage than those web sites.  Given that, I don't think it's a high priority to redesign the standard `requestAnimationFrame()` loop that the library currently has.

If you'd like to do that redesign and put together a pull request, you're welcome to do so.  If you'd like guidance or feedback prior to writing the code, you can post a proposal as a separate Github issue.

> It is killing battery life on mobile devices as it allocates around 40MB of data per minute and keeps the CPU busy.

I've confirmed that the library does not allocate memory in this way, via the Chrome task manager and the Chrome profiler on a clean user profile.  An idle, active tab uses constant memory.  If you have a verifiable bug, create a unique Github issue for it.  Include a reproducible demo.
