### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by marimeireles** [cytoscape/cytoscape.js#2658]
https://js.cytoscape.org/#notation/elements-json

In this part the edge part is not inside a `group:"edges"`, but it should be, right?

```
{ // edge e1
      data: {
        id: 'e1',
        // inferred as an edge because `source` and `target` are specified:
        source: 'n1', // the source node id (edge comes from this node)
        target: 'n2'  // the target node id (edge goes to this node)
        // (`source` and `target` can be effectively changed by `eles.move()`)
      },
```

**Comment by marimeireles** [comment]
Are `nodes` and `edges` inside of their own dictionary or is it really like this:

```
 {      
      group: 'nodes',
      data: { [...]},
      data: {[...]},

      group: 'edges',
      data: { [...]},
}
```

**Comment by mnv936** [comment]
@marimeireles  it is not necessary to specify `group: 'edges'`, it can be inferred as an edge because `source` and `target` are specified.
The structure is like this:-
` elements: 
  [ 
    { // node n1
      group: 'nodes', 
      data: {id: 'n1', parent: 'nparent'},
    },

    { // node n2
      data: { id: 'n2' },
    },

    { // node n3
      data: { id: 'n3', parent: 'nparent' },
    },

    { // node nparent
      data: { id: 'nparent' }
    },

    { // edge e1
      group : 'edges',
      data: {id: 'e1', source: 'n1', target: 'n2'},
    }
  ],
`
Every node/edge is treated as a separate object and which is which can be told by the key value pairs specified inside of `data`.

**Comment by mnv936** [comment]
@marimeireles  it is not necessary to specify `group: 'edges'`, it can be inferred as an edge because `source` and `target` are specified.
The structure is like this:-
```
elements:
  [
    { // node n1
      group: 'nodes',
      data: {id: 'n1', parent: 'nparent'},
    },
    { // node n2
      data: { id: 'n2' },
    },
    { // node n3
      data: { id: 'n3', parent: 'nparent' },
    },
    { // node nparent
      data: { id: 'nparent' }
    },
    { // edge e1
      group : 'edges',
      data: {id: 'e1', source: 'n1', target: 'n2'},
    }
  ],
```
Every node/edge is treated as a separate object and which is which can be told by the key value pairs specified inside of `data`.

**Comment by marimeireles** [comment]
Right!
Thanks for clarifying @mnv936. One more question: the docs says if you add the `group` key it will give you better error messages. Does that means I have to include `group` for each node?
Thanks!

**Comment by mnv936** [comment]
@marimeireles yes, you will have to include `group` for each node/edge for better error messages.

**Comment by marimeireles** [comment]
Alright.
Thanks @mnv936! I still think this deserves a clarification in the documentation, though. If you think it's a good idea I can make a PR.
Cheers.

**Comment by maxkfranz** [comment]
You should be able to specify group keys either within the elements or as group keys above the individual elements in the JSON.  Alternatively, you can omit the group keys and have them inferred.  You can use whatever format you prefer.  Is that not clear from the examples in the documentation?

**Comment by marimeireles** [comment]
@maxkfranz not in my opinion. In my opinion by reading only the docs is not very clear:

1. That you have specify a group for each node and each edge (if you want nice err msgs);
2. That you can either do within the `elements` or in each  node and each edge.

I just thought it was a typo, honestly, and got confused about what I mentioned above.

Thanks! For clarifying though =)

**Comment by maxkfranz** [comment]
If you'd like to make changes to the documentation to clarify things, that would be appreciated.  Thanks
