### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by Duskfall** [cytoscape/cytoscape.js#2659]
**Issue type**: Core

Bug report

**Environment info**

- Cytoscape.js version : 3.14.0
- Browser/Node.js & version : Firefox 74(64-bit)/ v12.13.0

**Current (buggy) behaviour**

When rendering a background image as an svg there is a problem in Firefox causing the following error
```
NS_ERROR_NOT_AVAILABLE: cytoscape.cjs.js:28890
    safeDrawImage cytoscape.cjs.js:28890
    drawInscribedImage cytoscape.cjs.js:29017
    drawImages cytoscape.cjs.js:29549
    drawNode cytoscape.cjs.js:29673
    drawElement cytoscape.cjs.js:28349
    drawElement cytoscape.cjs.js:30900
    drawCachedElementPortion cytoscape.cjs.js:28432
    drawCachedElement cytoscape.cjs.js:28479
    drawCachedElements cytoscape.cjs.js:28508
    drawLayeredElements cytoscape.cjs.js:28543
    render cytoscape.cjs.js:30266
    renderFn cytoscape.cjs.js:26640
    invokeTask zone.js:423
    runTask zone.js:195
    invokeTask zone.js:498
    invoke zone.js:487
    timer zone.js:2281
```

**Desired behaviour**

Render the svg uri normally like Chrome does

**Minimum steps to reproduce**

https://jsbin.com/wazowefobe/1/edit?html,js,output
I wasn't able to reproduce this in the jsbin but as I understand the browser renders the images like it should be and then there is a rerender that causes the error. It seems to me that the image seems that it isn't completely loaded, and if I add a breakpoint inside the safeDrawImage in the context.drawImage line, then it renders it normally so its like a race condition thing. I found a bug reported on Bugzilla as well as several stackoverflow issues:
https://bugzilla.mozilla.org/show_bug.cgi?id=574330
https://stackoverflow.com/questions/17049176/ns-error-not-available-component-is-not-available
https://stackoverflow.com/questions/27352528/ns-error-not-available-drawimage-in-firefox
FIY I am using angular as you can see by zone.js so could this be a problem as well?

**Comment by maxkfranz** [comment]
Ref: https://github.com/cytoscape/cytoscape.js/issues/2629#issuecomment-588301044
