### ISSUE TITLE
Layout does not work if id contains an $

### ISSUE THREAD

**Issue by Instinct408** [cytoscape/cytoscape.js#2666]
If a node has an id with one of the escaped characters, running a layout will give a warning and not execute the layout.

The selector `#PhoneRecord$Call`is invalid

**Comment by maxkfranz** [comment]
This is not reproducible on the debug page for any of the included layouts.  Please amend your issue with all the details in the [issue template](https://raw.githubusercontent.com/cytoscape/cytoscape.js/unstable/.github/ISSUE_TEMPLATE.md), including the reproducible demo.
