### ISSUE TITLE
Unresponsive graph when collapsing nodes recursively

### ISSUE THREAD

**Issue by code247** [cytoscape/cytoscape.js#2668]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.14.0
- Browser & version : Google Chrome (64-bit) 80.0.3987.163

**Current (buggy) behaviour**

The parameter `bb` in `ETCp.getElement` function is null when I'm calling the below `expandCollapseHandler` function on a node. This happens intermittently (3-4 / 10 times) and not consistently. Stack trace:
```
Uncaught TypeError: Cannot read property 'w' of null
    at ElementTextureCache.getElement (cytoscape.umd.js:28000)
    at ElementTextureCache.ETCp.dequeue (cytoscape.umd.js:28336)
    at Object.deq (cytoscape.umd.js:28383)
    at Object.dequeue [as fn] (cytoscape.umd.js:27676)
    at beforeRenderCallbacks (cytoscape.umd.js:27377)
    at renderFn (cytoscape.umd.js:27397)
```
**Desired behaviour**

Parameter `bb` shouldn't be null OR there should be a condition to check if `bb` is null and take appropriate action in such case.

Code details:

Using `cola` layout with `infinite: true` for a graph of about 200 elements (nodes + edges).

Function triggering the bug:

https://pastebin.com/HdCFsgtQ

**Comment by maxkfranz** [comment]
Please post a reproducible demo, like a jsbin.

**Comment by code247** [comment]
Here is the jsbin link: https://jsbin.com/qipisukero/edit?html,js,console,output

(Weirdly, I am observing the issue only in jsbin edit mode and not in demo mode.)

I observe the above `TypeError` in Chrome console if you stay in edit mode and try clicking on `bird` image. The jsbin console just says `"Script error. (line 0)"`. Ideal behavior is everything should collapse except the `bird` node.

**Comment by maxkfranz** [comment]
I'm not able to reproduce your issue in the demo.

**Comment by code247** [comment]
Did you try it in edit mode? May be you can clone the demo if you're not able to get into edit mode. I was able to reproduce the issue in jsbin edit mode. (Pardon if my suggestions sound noob. Haven't used jsbin before.)

**Comment by maxkfranz** [comment]
Yes, I couldn’t reproduce the issue either in jsbin or in a local http server (after using the jsbin download feature).

The layout result itself in the jsbin isn’t good, but maybe that’s a separate issue related to running Cola in infinite mode without addressing the caveats.  You may have better layout results — and sidestep your issue — if you don’t use the infinite mode in Cola.  It’s very simple to use Cola iteratively, and the Cola demo is an example of that: https://js.cytoscape.org/demos/colajs-graph/ <https://js.cytoscape.org/demos/colajs-graph/>

COSE-Bilkent and FCOSE are other examples of layouts that can be used iteratively.
