### ISSUE TITLE
Pie Chart is not cut to node shape

### ISSUE THREAD

**Issue by janhartmann** [cytoscape/cytoscape.js#2671]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version :  ^3.14.1
- Browser/Node.js & version : v13.11.0

**Current (buggy) behaviour**

It appears if I am using another shape than circle, the pie background color is not cut to the shape. 

**Desired behaviour**

The pie background color will be cut to the shape of the node.

**Minimum steps to reproduce**

Style a node like:

```js
{
  selector: "node",
  style: {
    shape: "round-octagon",
    "text-halign": "center",
    "text-valign": "center",
    "text-margin-y": 1,
    "font-weight": 500,
    "font-size": 12,
    "pie-1-background-color": "red",
    "pie-1-background-size": 60,
    width: 35,
    height: 35
  },
},
```

At one zoom level it looks like this:

![image](https://user-images.githubusercontent.com/1107383/79826662-5c56e180-83ad-11ea-8027-d8ea4765fb7b.png)
 And on another zoom level it looks like this:

![image](https://user-images.githubusercontent.com/1107383/79826695-7690bf80-83ad-11ea-9b38-376ef6a1dd5d.png)

I've been playing around with the `pie-size` attribute, if using `100%` it is still not covering the corners of the shape. 

Is there any way to make the shape cut the out the pie chart?

**Comment by maxkfranz** [comment]
The pie properties just create a circular overlay.  They don't have as many options as background images.  If you want more sophisticated features for controlling how charts look, you should use something like Chart.js to generate background images.  The pie properties will be removed in v4.
