### ISSUE TITLE
Changing a label of a node with width: label

### ISSUE THREAD

**Issue by sstenchlak** [cytoscape/cytoscape.js#2678]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.14.2
- Browser/Node.js & version : Google Chrome 81.0.4044.129

**Current (buggy) behaviour**

When a node has style `width: label` and it is created without label data, later modification of label draws a node without possibility to click on it.

**Desired behaviour**
Node should be selectable. 

**Minimum steps to reproduce**

1. Set following style
```js
{
    selector: 'node',
    style: {
        "label": "data(label)",
        "width": "label",
    }
}
```
2. Create a node with `label: ""`. (Node won't be visible because of its zero width)
3. Change the node's label to something non-empty.

The node became visible but you can't click on it or select it by a Shift key.

**Comment by maxkfranz** [comment]
I've reproduced your issue in the debug page
