### ISSUE TITLE
[Question] Patterns for optimizing rendering of large graphs

### ISSUE THREAD

**Issue by dahnny012** [cytoscape/cytoscape.js#2681]
I have a use case where I take the API response of a service call and then construct nodes and edges from it.  This is fed into cytoscape to then create a graph.

Would it be correct to assume if we were to export the graph.json and then load it into cytoscape that this would be more efficient? 

Taking it further perhaps we then can have a backend service thats running cy in headless mode producing the graph.json and caches it for the front-end to store and use?

Thoughts on this? I plan to do some benchmarks to test if this is worth it just wanted to get some feedback.

**Comment by dahnny012** [comment]
Made some progress on this except ran into an issue where if I dont specify a bounding box for the graph, the resulting output is cluttered and not respecting the label size.

However in the browser a bounding box is automatically configured and the layout seems to also account for label dimensions.

Is there anything I could do here besides guessing what would be okay dimension for a graph's bounding box?

**Comment by maxkfranz** [comment]
In addition to the information in the documentation re. layouts, there is a tutorial: https://blog.js.cytoscape.org/2020/05/11/layouts/

**Comment by dahnny012** [comment]
Thanks for the response, I'll look into cytosnap. I was having trouble with JSDom but this looks promising.
