### ISSUE TITLE
Completely disable element interaction with global flag

### ISSUE THREAD

**Issue by jsphstls** [cytoscape/cytoscape.js#2683]
**Issue type**

Feature request

**Description of new feature**

Disable all interaction with nodes by adding a new flag for interaction options.

**Motivation for new feature**

I want to use Cytoscape to create read-only data renderings. Pan and zoom is still needed,  anything else that implies element interactivity should be disabled.

Currently, with `autolock`, `autoungrabify`, and `autounselectify` nodes and edges still respond to taps by briefly showing a highlighted state. Ideally, they would not change state at all.

**Comment by jsphstls** [comment]
Another way to look at this is that the entire canvas should pan when clicking a node and dragging. Currently the node and canvas will not move with `autolock` on.

**Comment by maxkfranz** [comment]
Is there a use case that strongly motivates a global flag versus the fairly standard per-element CSS approach?

https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

https://js.cytoscape.org/#style/events

**Comment by jsphstls** [comment]
`events` style does the trick. Thanks @maxkfranz !

```
selector: 'node',
css: {
   events: 'no'
```
