### ISSUE TITLE
Node's classes order and its result  rendering style

### ISSUE THREAD

**Issue by cheblin** [cytoscape/cytoscape.js#2688]
**bug / maybe feature?**

Bug report

**Environment info**

- Cytoscape.js version : 3.15.0
- Browser/Node.js & version : any

**Current (buggy) behaviour**
Order of adding to node classes does not change the node rendering style
```js
(function(){

  var cy = window.cy = cytoscape({
    container: document.getElementById('cy'),
      style    : [
          {
              selector: 'node',
              style   : {
                  'content'      : 'data(label)',
                  'shape'        : 'round-rectangle',
                  'border-width' : 1,
                  'width'        : 'label',
                  'height'       : 'label',
                  'text-valign'  : 'center',
                  'padding-left' : '3',
                  'padding-right': '3'
              }
          },
          {
              selector: '.blue',
              style   : {
                  'background-color': 'blue'
              }
          },
          {
              selector: '.orange',
              style   : {
                  'background-color': 'orange'
              }
          }
      ]
  });

  cy.ready(function(){ // make taxi nodes better organised
      cy.add({
          group: 'nodes',
          data : { label: ".addClass('blue')"},
      }).addClass('blue')

      cy.add({
          group: 'nodes',
          data : { label: ".addClass('orange')"},
      }).addClass('orange').position().y+=40

      cy.add({
          group: 'nodes',
          data : { label: ".addClass('orange') .addClass('blue')"},
      }).addClass('orange') .addClass('blue').position().y+=80

      cy.add({
          group: 'nodes',
          data : { label: ".addClass('blue') .addClass('orange')"},
      }).addClass('blue') .addClass('orange').position().y+=120

      cy.fit()
  });
})();
```
![image](https://user-images.githubusercontent.com/29354319/82402547-42cdb600-9a8f-11ea-88e0-d0f65032af06.png)

But stylesheet classes selector registration order do. 

```js
(function(){

  var cy = window.cy = cytoscape({
    container: document.getElementById('cy'),


      style    : [
          {
              selector: 'node',
              style   : {
                  'content'      : 'data(label)',
                  'shape'        : 'round-rectangle',
                  'border-width' : 1,
                  'width'        : 'label',
                  'height'       : 'label',
                  'text-valign'  : 'center',
                  'padding-left' : '3',
                  'padding-right': '3'
              }
          },
          {
              selector: '.orange',
              style   : {
                  'background-color': 'orange'
              }
          },
          {
              selector: '.blue',
              style   : {
                  'background-color': 'blue',
                  'color': 'white'

              }
          }
      ]
  });

  cy.ready(function(){ // make taxi nodes better organised
      cy.add({
          group: 'nodes',
          data : { label: ".addClass('blue')"},
      }).addClass('blue')

      cy.add({
          group: 'nodes',
          data : { label: ".addClass('orange')"},
      }).addClass('orange').position().y+=40

      cy.add({
          group: 'nodes',
          data : { label: ".addClass('orange') .addClass('blue')"},
      }).addClass('orange') .addClass('blue').position().y+=80

      cy.add({
          group: 'nodes',
          data : { label: ".addClass('blue') .addClass('orange')"},
      }).addClass('blue') .addClass('orange').position().y+=120

      cy.fit()
  });
})();
```
![image](https://user-images.githubusercontent.com/29354319/82403034-7a892d80-9a90-11ea-80dd-111ff6e4af0a.png)

maybe  this behaviour is good in a performance sense,  but in general, it's nonsense

**Desired behaviour**

I expected later added classes would override earlier.
![image](https://user-images.githubusercontent.com/29354319/82402730-be2f6780-9a8f-11ea-8bc5-befbdf3a1032.png)

**Comment by cheblin** [comment]
my bad

**Comment by somedmguy** [comment]
Perhaps classes are not the right way to model this.  If something can be either A or B but not both, instead of making A and B classes (which are just independent flags and cannot model the mutual-exclusion relationship you want), why not make them different values of a single property?  `node.data('background-color', 'blue')` & `node.data('background-color', 'orange')`

The current behavior allows the developer to choose, if something is both A and B, which styles win...always".  This is a useful level of control for the developer with a comforting deterministic simplicity.  I would not expect this to change.

**Comment by cheblin** [comment]
> which styles win...always.

first or... last. 
The last is better cause API allows only append classes, with call addClass.
If I need to change a node style and the revert back, gust addClass and remove...

What I have to have to do now? Store current styles somewhere, apply new, and then revert all back.
right?

**Comment by maxkfranz** [comment]
It looks like you're having some trouble understanding some CSS concepts.  There are some great tutorials on the [MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS), e.g. ['Cascade and inheritance'](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance).  Once you've understood those concepts, the Cytoscape stylesheet will make more sense.

**Comment by HandsomeTea** [comment]
I think this is a good question. I also encountered this problem. I originally wanted to use class switching to control the style, but it didn’t work at all. Sometimes it is very inconvenient to change each style attribute in detail for different interactions.

For example,there is style set as
```
[{
  selector: 'node',
  style: {
    'background-color':'red'
  }
},{
  selector: '.blue',
  style: {
    'background-color': 'blue'
  }
}]
```
In some cases, I want the background color of the node to be bule, i want to achieve this function like:
```
cy.elements().addClass('blue')
```
and when I run the following code:
```
cy.elements().removeClass('blue')
```
 the background color of the node will be red and I don't need to explicitly set the background color to red. after removing `bule`, the background color will automatically show the original red.

Obviously, the current class design does not support this.
