### ISSUE TITLE
layoutstop event not triggered when a node is not displayed 

### ISSUE THREAD

**Issue by hasanbalci** [cytoscape/cytoscape.js#2693]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.15.0 and before
- Browser/Node.js & version : Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Current (buggy) behaviour**

When there is a node with style `display: none` in a graph, Cytoscape doesn't trigger `layoutstop` event if a layout is called with option `animate = 'end'` for continuous layouts and `animate = true` for discrete layouts (which animates directly to the end result). This event is triggered for other animation types. I tried this in built-in cose and in the extensions euler, dagre and cose-bilkent, and it seems that it is valid for all layouts.

**Desired behaviour**

`layoutstop` event should be triggered after layouts that have a non-displayed node and animate directly to the end result.

**Minimum steps to reproduce**
A sample demo is [here](https://jsbin.com/qotuvasihe/edit?html,css,js,output).

**Comment by maxkfranz** [comment]
The demo reproduces the issue for me.  Thanks for the detailed report
