### ISSUE TITLE
Full description of JSON formats accepted by library

### ISSUE THREAD

**Issue by fenuks** [cytoscape/cytoscape.js#2698]
**Issue type**
Feature request

**Description of new feature**
It's more an improvement than feature request. I am working on generating JSON document that will be consumed by cytoscape.js, and I'm confused about format. Is there anywhere in documentation full description of all possible values that cytoscape.js understands?

[Elements JSON documentation](https://js.cytoscape.org/#notation/elements-json) gives `Examples (…) that outline format of the elements JSON used to load elements into Cytoscape.js`, but as I understand, it's not description of full format, just an example, or am I wrong? [Cytoscape documentation](http://manual.cytoscape.org/en/stable/Supported_Network_File_Formats.html#cytoscape-js-json) contains an example document in Cytoscape.js JSON format, that has more attributes than were mentioned in Cytoscape.js docs.

I tried to search if there is more comprehensible description in readable form somewhere in code, and I've found something in [element.js](https://github.com/cytoscape/cytoscape.js/blob/5b32379c20036670114ac96098d39c470ce962ae/src/collection/element.js#L36) that apparently is used to describe both nodes and edges. That code seems to use properties such as `selectable`, `grabbable`, `locked` which are missing in documentation.

**Comment by maxkfranz** [comment]
It looks like the fields you mentioned are indeed included in the section of the documentation that you linked to.  If you have specific suggestions in mind for what you'd like to see in an improved version of the documentation, please make a pull request with your proposed changes.  Thanks for your feedback

**Comment by fenuks** [comment]
Thank you, I could add information about these fields to documentation, but as I said, I don't know full shape of JSON document, so it's likely documentation would be still incomplete. It would be best if someone with knowledge of format could list here all acceptable fields (I could create MR if wanted).
