### ISSUE TITLE
Click through Cytoscape container/canvas

### ISSUE THREAD

**Issue by janhartmann** [cytoscape/cytoscape.js#2706]
**Issue type**

Feature request

**Description of new feature**
I have a setup where I have a MapBox layer underneath the graph layer. In code, it is just two canvas on each other. They are currently not connected functionality wise.

I would like to be able to interact with the map underneath, for instance panning and clicking items. Is it possible to make the clicks go through to the underneath layer when not clicking a feature on Cytoscape?

**Comment by janhartmann** [comment]
Was able to do some workaround with background click, set pointer-events to none and visa-versa

**Comment by zakjan** [comment]
For anyone looking for a similar integration, there is now a plugin for it: https://github.com/zakjan/cytoscape-mapbox-gl
