### ISSUE TITLE
When using multiple background images with `background-height: [auto]`, nodes are not displaying correctly

### ISSUE THREAD

**Issue by charles-stuart-appdetex** [cytoscape/cytoscape.js#2707]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.13.2
- Browser/Node.js & version :

- Safari Technology Preview, Release 107 (Safari 13.2, WebKit 15610.1.14.1. 
- Firefox Developer Edition, 78.0b4 (64-bit)

**Current (buggy) behaviour**

I'm attempting to badge nodes by using multiple background images. I am currently setting three background images on each node, and if the badge should not be active, I display an empty PNG in it's place.

From what I can tell, the bug is related to having nodes sharing the same width and height dimensions. If I take the width and height and add `Math.random()` to the width and height provided in the elements, the bug does not reproduce.

You can see in the example that all nodes except for one which have a width and height of 20 do not display the correct background images according to the `data.backgroundImage` array on the nodes.

**Desired behaviour**

Display background images according to the data provided.

**Minimum steps to reproduce**

https://jsbin.com/warocen/2/edit?html,css,js,output

**Comment by maxkfranz** [comment]
I can confirm that the issue is reproducible.  It seems to be related to style properties that accept multiple, mixed-type values -- like `background-width`.

**Comment by maxkfranz** [comment]
FYI @charles-stuart-appdetex -- you're missing `bounds-expansion` if you're placing images outside of the normal bounding box.  That's a separate issue that doesn't affect that validity of your bug report, but it's worth noting.

**Comment by maxkfranz** [comment]
@charles-stuart-appdetex, commit 5bc05d1 should resolve your issue.

**Comment by charles-stuart-appdetex** [comment]
@maxkfranz Thanks so much for the fix and the tip regarding `bounds-expansion`.
