### ISSUE TITLE
Keyboard events

### ISSUE THREAD

**Issue by GlitchEclipse** [cytoscape/cytoscape.js#2710]
I did not see any events in the documentation for keyboard events. Delete, backspace being the big ones. I would really like to use this library, but deleting nodes and edges via the keyboard is pretty generic and users will expect it. How can I achieve this? I tried a couple of different ways with no luck. Thank you.

**Comment by GlitchEclipse** [comment]
Reading the comments of other posts I see mousetrap as an option, though I still think this is basic functionality that should exist in the native api.

**Comment by maxkfranz** [comment]
As far as I'm aware, keyboard events are emitted only for widgets like text boxes.  

Would you post a proposal for how your keyboard API would work?  The issue template is a good guide for how to specify a new feature.  If you already have something specific in mind for a new feature, you're welcome to make a pull request.
