### ISSUE TITLE
Background SVG image shrinking on newer versions (on 3.1.2 works ok)

### ISSUE THREAD

**Issue by adaamz** [cytoscape/cytoscape.js#2713]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version : latest (3.15.1)
- Browser/Node.js & version :
 1. Opera 68
 1. Chrome 83
 1. Firefox 68 (doesnt show any background image at all :O)

**Current (buggy) behaviour**
The exclamation icon used for background has different height/width each time text/label changes. Also it is not shown whole, but only some part of background image.

**Desired behaviour**
Nice background image rendering, same height/width as is set in style.
At least as it act in version 3.1.2 https://jsfiddle.net/0r8w5nsc/40/

**Minimum steps to reproduce**
Fork/clone this JSBin demo and reproduce your issue so that your issue can be addressed quickly:
https://jsfiddle.net/0r8w5nsc/38/

btw I have question at the end 😅  Is it possible to have background image positioned to right top corner? thx

**Comment by maxkfranz** [comment]
Thanks for the thorough issue report.

Unfortunately, the `width/height: label` feature  has caused a lot of problems over time, and I haven't seen a use of it that wasn't chartjunk.

I believe that feature came from the community, and though that's generally much appreciated, this particular feature has become a white elephant.  This issue is the straw that broke the camel's back -- to mix animal metaphors -- and so the feature should be deprecated.

Removing `with: label` from the stylesheet resolves the issue in your demo.

**Comment by adaamz** [comment]
Thanks for answer. Removing `width: label` also removes feature of autoscaling (width) of node. Do you have some advice in this issue?

**Comment by Grinnz** [comment]
> Thanks for answer. Removing `width: label` also removes feature of autoscaling (width) of node. Do you have some advice in this issue?

I also use this feature on https://cpandeps.grinnz.com because the node labels are highly variant, so would not like to see it removed unless there is another way to do this. Thank you for this excellent library.

**Comment by Dassderdie** [comment]
> Thanks for the thorough issue report.
> 
> Unfortunately, the `width/height: label` feature has caused a lot of problems over time, and I haven't seen a use of it that wasn't chartjunk.
> 
> I believe that feature came from the community, and though that's generally much appreciated, this particular feature has become a white elephant. This issue is the straw that broke the camel's back -- to mix animal metaphors -- and so the feature should be deprecated.
> 
> Removing `with: label` from the stylesheet resolves the issue in your demo.

We also use this feature in our application. We use cytoscape.js for displaying the structure of a relational database and at the same time make it possible for the user to navigate via the nodes to the tables. Therefore the nodes should be styled like (bootstrap-)buttons...

![image](https://user-images.githubusercontent.com/18506183/95915989-4cdab300-0da8-11eb-8b75-0861cdcfd75e.png)

**Comment by maxkfranz** [comment]
The more I think about it, the less I think that `width: label` should be a built-in feature.  It creates an odd dependency between style calculations, and they should generally be kept as independent, pure functions.

There are now fairly good ways of measuring text within the browser (e.g. [text-metrics](https://github.com/bezoerb/text-metrics)), so a consumer of the library could set up mapper functions with those measurements.  This approach is much more flexible, since you could adjust the calculation (e.g. you want the nodes much wider than the text to accommodate icons).

Try out the mapper approach, and report back here.

**Comment by Grinnz** [comment]
I'm hesitant to add new dependencies for this, and having to determine if enough browsers support this. Would it be possible to provide the current calculation for such mapper functions to use?

**Comment by maxkfranz** [comment]
> I'm hesitant to add new dependencies for this, and having to determine if enough browsers support this. Would it be possible to provide the current calculation for such mapper functions to use?

That would have the same problem as today.  

If you don't want a dependency, you could implement a simple width getter with [`measureText()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText).

**Comment by kumom** [comment]
> > I'm hesitant to add new dependencies for this, and having to determine if enough browsers support this. Would it be possible to provide the current calculation for such mapper functions to use?
> 
> That would have the same problem as today.
> 
> If you don't want a dependency, you could implement a simple width getter with [`measureText()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText).

Shouldn't I need a reference to the underlying canvas element if I want to use `measureText()`? However, you mentioned in [this Stackoverflow question](https://stackoverflow.com/questions/43900625/how-do-i-get-a-reference-to-cytoscape-canvas-context) that it is not necessary. Could you elaborate this solution you hinted?

**Comment by simonmoesorensen** [comment]
As a replacement for `width: 'label'` I've used the following:

```

function getWidth(node) {
    /**
    Calculate the width of a node given its text label `node.data('lbl')`
    */

    // Create element with attributes needed to calculate text size
    const ctx = document.createElement('canvas').getContext("2d");
    const fStyle = node.pstyle('font-style').strValue;
    const size = node.pstyle('font-size').pfValue + 'px';
    const family = node.pstyle('font-family').strValue;
    const weight = node.pstyle('font-weight').strValue;
    ctx.font = fStyle + ' ' + weight + ' ' + size + ' ' + family;

    // For multiple lines, evaluate the width of the largest line
    const lines = node.data('lbl').split('\n')
    const lengths = lines.map(a => a.length);
    const max_line = lengths.indexOf(Math.max(...lengths));

    // User-defined padding
    const padding = 30

    return ctx.measureText(lines[max_line]).width + padding;
}
```

Using it as such:
```
        style: {
            'width': getWidth,
        }
```

It seems to work well for me and is sufficiently fast

**Comment by tensiondriven** [comment]
Note that the above strategy doesn't seem to work for `"text-wrap": "wrap"`, instead it depends on the user injecting newlines themselves.

**Comment by binDongKim** [comment]
`measureText` not working. Any workaround?
