### ISSUE TITLE
[bug] new added node not listen on events via `eles.on()`

### ISSUE THREAD

**Issue by SimonGolms** [cytoscape/cytoscape.js#2714]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : v3.5.1
- Browser/Node.js & version :

**Current (buggy) behaviour**

After a new node is added to the graph, events on e.g. `cy.nodes().on('click')` are not executed, but are available via `cy.on('click', 'node')`. 

**Desired behaviour**

Listen on events after adding a new node to the graph via `cy.nodes().on('click')`

**Minimum steps to reproduce**

1. Click on a node:
```js
// console output
cy.nodes().on(click)
cy.on(click, node)
```
2. Add new node via the button on top
3. Click on new node
```js
// console output
cy.on(cxttap, node)
```

https://jsbin.com/ligesehera/edit?html,js,console,output

**Comment by maxkfranz** [comment]
What is your expectation around the behaviour of `cy.nodes()`?  When you call it, what do you expect to be returned?

**Comment by SimonGolms** [comment]
Oh, I thought I already put that under desired behaviour...

If I add a new node and for example click on it afterwards, the event `cy.nodes().on('click')` will react the same way as `cy.on(click, node)`.

Or have I missed something in the documentation?

**Comment by sgratzl** [comment]
I think it is similar to JQuery `on` and the deprecated `live`. https://api.jquery.com/live/. 

You are looking for that the `.nodes()` collection is always uptodate with the current nodes. However, as far I know it it is just a snapshot of the nodes at the moment you call `.nodes()`.

**Comment by SimonGolms** [comment]
Thanks @sgratzl for the explanation, that sums it up.

@maxkfranz what would be the next step? Is this a bug from your point of view or could the description of the behavior be enough in the documentation?

**Comment by maxkfranz** [comment]
I'm not familiar with any tools that handle collections in an automatically updating way.  How would that work with the set theory operations, or what if you wanted to diff an old set of nodes with a new set of nodes?

Where do you think would be the best place in the documentation to address your issue?  Maybe `eles.on()`?  Would you be open to writing a few sentences that would help to clarify things for people like you, who run into this issue?
