### ISSUE TITLE
Add pill/stadium node shape type

### ISSUE THREAD

**Issue by danail-vasilev** [cytoscape/cytoscape.js#2715]
Improve visually node shape types by adding a pill/stadium type similar to https://www.screencast.com/t/cra0idbejo from https://pathwaycommons.github.io/cytoscape-sbgn-stylesheet/

This is like a round-rectangle but with a larger radius on the y-axes or like an ellipse but with a lower radius on the x-axes.

As far as I can see adding a function that just draws such a shape is not enough but additional logic for handling bounding box and layout. I am not sure whether drawing a polygon is reasonable as there may be many points.

**Comment by maxkfranz** [comment]
If you'd like to put together a proposal for a new node shape, please include the list of affected style properties and their corresponding values.  It's also important to include clear pictures or mockups of the shape itself.

Once we have a clear proposal, we can talk about adding it to the library.
