### ISSUE TITLE
Feature request: A new "line-opacity" style field ?

### ISSUE THREAD

**Issue by GDurrens** [cytoscape/cytoscape.js#2717]
Feature request

When setting the opacity of an edge, the label's opacity is also modified.
Unless I missed that possibility in the documentation, it would be nice to be able to set the edge transparency without altering its label's opacity (text-opacity)
That would for example help in situations where the label gets hidden by another edge.
You can see that issue happening [here](https://gdurrens.github.io/SOAP-project/)

Thanks for your amazing cytoscape.js

**Comment by maxkfranz** [comment]
That sounds like an interesting idea.  Would you be open to documenting your feature more formally in the documentation markdown files and making a pull request with the corresponding implementation?

**Comment by blazespinnaker** [comment]
@maxkfranz Can you provide some pointers on where to make changes for this?  I need this feature as well and I am happy to do a PR with documentation.

**Comment by maxkfranz** [comment]
You'd need a new property: 

https://github.com/cytoscape/cytoscape.js/blob/5f60db5443424f4617d20c86c4361775b3babeed/src/style/properties.js#L317-L322

And you'd need to apply it when drawing:

https://github.com/cytoscape/cytoscape.js/blob/5f60db5443424f4617d20c86c4361775b3babeed/src/extensions/renderer/canvas/drawing-edges.js#L30-L43

**Comment by maxkfranz** [comment]
Style is just documented within the markdown file: 

https://github.com/cytoscape/cytoscape.js/blob/5f60db5443424f4617d20c86c4361775b3babeed/documentation/md/style.md

**Comment by maxkfranz** [comment]
Edge line docs: https://github.com/cytoscape/cytoscape.js/blob/5f60db5443424f4617d20c86c4361775b3babeed/documentation/md/style.md#edge-line

**Comment by blazespinnaker** [comment]
https://github.com/blazespinnaker/cytoscape.js/commit/ee9c2503f97ad1e40004265d2c099b3658c96f5c

Been awhile since I've done a PR, let me know if there is anything else you need.

**Comment by maxkfranz** [comment]
It looks like it's ready to hit the 'make pull request' button on your branch.  I'll try to set aside time to do a review on that upcoming PR this week.

**Comment by maxkfranz** [comment]
Reopening for visibility
