### ISSUE TITLE
create API such that UIextensions can contribute to Image generation

### ISSUE THREAD

**Issue by sgratzl** [cytoscape/cytoscape.js#2718]
**Issue type**

Feature request

**Description of new feature**

I'm creating extensions to cytoscape and wonder whether there is an API that allows me to hook into the PNG/JPG generation. For example, an extension which renders an extra overlay in another canvas which I would like to add into the output image.

**Motivation for new feature**

**Comment by maxkfranz** [comment]
Would you be open to making a proposal for how this API would work?  I can't think of anything easier than just combining images together outside of Cytoscape, but it sounds like you have a better idea of how to streamline things.

**Comment by sgratzl** [comment]
re extending the image: the downside is that you have to parse the image, draw it into an offscreen canvas, render the extension and dump it again. Maybe doing the same thing for each extension that you have. My use case is that I also wanna dump my bubblesets as part of the cytoscape image. 

what I've seen so far, cytoscape itself doesn't have any hooks in which extensions can plug themselves in. It is possible to extend it by adding (independent) functions but not to alter its behavior. 

For example, chart.js provides various hook options in which a plugin can "inject" its behavior into the existing workflow, e.g., `beforeDatasetDraw` is called in each plugin before a dataset are drawn and `afterDatasetDraw` directly after it. This allows extensions to render some additional information for each dataset if they want to.

**Comment by maxkfranz** [comment]
Is there a way to do that without exposing the underlying rendering technology?  Currently, the public API does not expose anything related to canvas.
