### ISSUE TITLE
Feature request `:hover` selector

### ISSUE THREAD

**Issue by sgratzl** [cytoscape/cytoscape.js#2719]
**Issue type**
Feature request

**Description of new feature**

it would be great if similar to a `:selected` or `:active` a `:hover` selector is supported. Similar to CSS it should be triggered when the mouse is over the element.

**Motivation for new feature**

direct feedback when hovering over a node

**Comment by GDurrens** [comment]
Hello sgratzl,
Can't you do that with cy.on ?
for example, to trigger an event on hovering edges :
`cy.on("mouseover", "edge",function(evt){your function}`

**Comment by maxkfranz** [comment]
What would the behaviour be for touch devices?

**Comment by sgratzl** [comment]
> cy.on("mouseover", "edge",function(evt){your function}

yeah I'm currently using a combination of `mouseover` and `mouseout`, tho a "native" support would be great, too. 

> What would the behaviour be for touch devices?

I suppose similar to the one that the CSS specification is stating

**Comment by maxkfranz** [comment]
> I suppose similar to the one that the CSS specification is stating

To be frank, I wasn't impressed with how that spec was handled when it was initially written.  It has resulted in a lot of confusion and issues over time, so it hasn't been successful in my opinion.

For an interactive feature to be added, it should support touch devices well and it should be simple.  The official CSS `:hover` spec does not meet either of those criteria, but perhaps an alternative proposal would.
