### ISSUE TITLE
feature request: edge target arrow opacity 

### ISSUE THREAD

**Issue by GDurrens** [cytoscape/cytoscape.js#2720]
FEATURE REQUEST :

Ubuntu 20.04

- Cytoscape.js version : 3.15.1
- Browser/Node.js & version : chrome & firefox

When setting the opacity of the edge, the target-arrow is not affected.
It would be nice to have a "target-arrow-opacity" field. 

Thanks

**Comment by maxkfranz** [comment]
I could not reproduce this on the latest release.  Opacity affects the arrow and the line.  Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.

**Comment by maxkfranz** [comment]
I tested on Mac 10.15.5.  I don't have access to an Ubuntu machine right now

**Comment by GDurrens** [comment]
> I could not reproduce this on the latest release. Opacity affects the arrow and the line. Please provide a reproducible test case, including:
> 
>     * Browser version
chrome: Version 83.0.4103.116 (Official Build) (64-bit)
firefox: 78.0.1 (64-bit)
> 
>     * OS version
ubuntu 20.04
> 
>     * A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.

https://jsbin.com/xutiqagava/1/edit?html,css,js,output

just move the grasshopper up so that the arrow is on the text. Despite the opacity 0.5 setting, the text won't partially be seen.

![1](https://user-images.githubusercontent.com/17565020/87225904-a211bd80-c390-11ea-80f0-9f2c533d91b9.png)

Thanks

**Comment by maxkfranz** [comment]
Possibly related: https://github.com/cytoscape/cytoscape.js/issues/1542
