### ISSUE TITLE
Performance improvements re. initial load time

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#2723]
Several performance enhancements had been identified that affect the initial load time of the graph.  These enhancements had been prototyped, and they had shown an improvement at first look.  However, the Cytoscape Consortium has other projects that are more highly prioritised than this one, so further investigation or evaluation of these sorts of enhancements are on hold.

Instead of leaving these enhancements to die on the vine, I have decided to release them as-is so that they can benefit the community.  Let us know whether these changes work well for you.

**Comment by dahnny012** [comment]
Is there any benchmarks?

**Comment by maxkfranz** [comment]
Ad-hoc benchmarks were done. The collection/array enhancement would affect a number of existing benchmarks, however.
