### ISSUE TITLE
Using local file for node `background-image`

### ISSUE THREAD

**Issue by DurkoMatko** [cytoscape/cytoscape.js#2725]
I'm trying to set node `background-image` with my local image file with no success. Also, I can't really find anything online about this. In the **Breadthfirst layout & images**, images are loaded from internet. How can I set node background image with an image located in project's assets folder?

I've tried this where icon is absolute/relative path to the image.
```js
style: {               
     'label': 'data(label)',
      'background-image': 'data(icon)',
      'text-wrap': 'wrap',
}
```

I've just read [background-image documentation](https://js.cytoscape.org/#style/background-image) and it let me confused. Does that mean you can't use local assets as node images?

**Comment by sgratzl** [comment]
what do you mean with local file? what type of setup do you have? are you sure that your development webserver is hosting this local file? when you take a look at the network tab of the developer tools, does Cytoscape try to load the file?

**Comment by BenPortner** [comment]
Dear @sgratzl , @maxkfranz , other cytoscape developers,

first off, thanks for your amazing work. I just started using cytoscape.js and I am amazed by the possibilities!

To the question:
Like @DurkoMatko, I am trying to add a `background-image` to my nodes without success. I created a minumum example to demonstrate the issue. You can find the it in the attached [cytoscape-error.zip](https://github.com/cytoscape/cytoscape.js/files/6083140/cytoscape-error.zip). 

The zip contains two files. A html file with a script and an image file. The script tries to add the image as a background to a) a node in a Cytoscape graph and b) a html-div in the body. If I put both the html and the image in the same folder in my filesystem (windows machine, no webserver), and open the html file in Chrome or Firefox, the div has a background image, but the Cytoscape node does not. Moreover, Chrome's console shows an error `Access to image at 'file:///.../img.png' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.` I do not understand why I can load the image view plain Javascript, but not via Cytoscape. Could you let me know how to solve this problem?

error.html:
```html
<html>

<head>
    <style>
        div {
            width: 200;
            height: 200;
        }
    </style>

</head>

<body>
    <div id="bkg"></div>
    <div id="cy"></div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.18.1/cytoscape.min.js"></script>
<script>

    // image to add to cytoscape node and #bkg
    const img = 'url(img.png)'

    // start cytoscape
    var cy = cytoscape({
        container: document.getElementById('cy'),
        // add one node
        elements: [
            {
                data: { id: 'a' }
            },
        ],
        // add background-image (does not work)
        style: [
            {
                selector: 'node',
                style: {
                    'background-image': img,
                }
            },
        ],
    });

    // add background image to #bkg
    document.getElementById('bkg').style.backgroundImage = img;
</script>

</html>
```

**Comment by maxkfranz** [comment]
@BenPortner 

You must not use `file://` URIs.  The browser is meant to be used with HTTP.  Your code and images should be hosted on an HTTP server.
