### ISSUE TITLE
edge `.select()` triggers 'unselect' event

### ISSUE THREAD

**Issue by umdstu** [cytoscape/cytoscape.js#2729]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version : 3.13.0
- Browser/Node.js & version : node@12.14.1, chrome@83

**Current (buggy) behaviour**
Since the box event doesn't currently appear to select edges if no nodes are selected, I began trying to roll my own solution by capturing `boxstart` and `boxend` event positions and then computing whther any edges on the graph fall within the bounds of the box. Once an edge is determined to be in or intersecting the box, I attempt to toggle it's selected state with `edge.select()`. I noticed that this does not actually change the edges `selected` value from false to true, nor does it get highlighted. Further debugging yielded that calling .select() somehow is triggering the `unselect` event on that element, and is perhaps why it doesn't get truely selected. 

**Desired behaviour**
edge.select() should mark the edge as selected and NOT trigger the 'unselect' event.

**Minimum steps to reproduce**

```js
.on('unselect', event => {
   console.log('element was de-selected');
})
.on('boxstart', event => {
   this.boxStart = event.position;
})
.on('boxEnd', event => {
  this.boxEnd = event.position;

  const edges = this.cy.edges();
  const rectangle = Polygon.fromPoints([
    new Point(this.boxStart.x, this.boxStart.y),
    new Point(this.boxEnd.x, this.boxStart.y),
    new Point(this.boxEnd.x, this.boxEnd.y),
    new Point(this.boxStart.x, this.boxyEnd.y)
  ]);
  for ( let edge of edges) {
    const bounds = edge.boundingBox();
    // code excluded for brevity
    if (intersects || endsIn || startsIn) {
      console.log('edge selected');
      console.log(edge);
      edge.select();
      console.log(edge);
    }
  }
});
```
What you end up seeing in the console is upon dragging over an edge on the graph is:
```
edge selected
Re {o: Re, length: 1, _private: {...}}
Re {o: Re, length: 1, _private: {...}}
element was de-selected
```

Thanks for looking at this.

**Comment by maxkfranz** [comment]
A demo may help to clarify your issue.

> Since the box event doesn't currently appear to select edges if no nodes are selected

I think the box uses containment for selection.  Otherwise, it's unwieldy:  It would be difficult to select particular edges, and you'd get more edges selected than you want.

> .on('boxEnd', event => {

What is the order of box* events w.r.t. the gesture's corresponding *select events?  If it's not documented -- I think it's probably not -- then it's undefined and you probably can't depend on a certain order.  Would using the next tick help?

**Comment by umdstu** [comment]
Sorry, I'm not sure I follow your line of thinking (not your fault).

In writing up a demo for #2728, It seems this is an issue with my code somehow. In the demo, Calling .select() on an edge actually selects it, and nothing else is triggered. In mine, .select() is immediately followed up with an unselect(). somehow, i'm attempting to trace through now to find out where.

Thanks
