### ISSUE TITLE
List extension : cytoscape.js-overlays

### ISSUE THREAD

**Issue by sgratzl** [cytoscape/cytoscape.js#2730]
https://github.com/sgratzl/cytoscape.js-overlays

A [Cytoscape.js](https://js.cytoscape.org) plugin for adding layers that shows bars, histograms, sparklines, binary sparklines, symbols (categorical data), or boxplots next to nodes.

![image](https://user-images.githubusercontent.com/4129778/87940972-afb6f980-ca9a-11ea-94ca-a383a2d4dd64.png)

Great for showing numerical attributes such as experimental data of pathways nodes.
![image](https://user-images.githubusercontent.com/4129778/87938105-5220ae00-ca96-11ea-839a-0321990d2171.png)

**Comment by maxkfranz** [comment]
It looks like a great extension.  Thanks for posting it
