### ISSUE TITLE
`eles.style()` bypass erroneously applies same cached property object to all calling `eles`

### ISSUE THREAD

**Issue by perrelle** [cytoscape/cytoscape.js#2732]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.15.2
- Browser/Node.js & version : 78.0.2 (64 bits)

**Current (buggy) behaviour**

The opacity after animations on two distinct set of nodes is not the target opacity.

**Desired behaviour**

The opacity after animations on two distinct set of nodes should be the target opacity.

**Minimum steps to reproduce**

https://jsbin.com/pitecihole/edit?html,css,js,output

**Comment by perrelle** [comment]
Some notes about this report. If we remove the opacity setting to 0, it works as intended. This code was an attempt to actually transition opacity from 0.0 to the opacity defined by a stylesheet ; this is something I did not achieve either with `animate()` or `transition-property`.

**Comment by maxkfranz** [comment]
I would guess that there's probably a cached property object that is erroneously shared between the nodes, perhaps as a result of your `style()` call.

**Comment by perrelle** [comment]
It seems you are right. If I apply the style element by element to prevent sharing, I get the correct behavior : 

https://jsbin.com/romotakupo/edit?html,css,js,output

**Comment by maxkfranz** [comment]
> It seems you are right. If I apply the style element by element to prevent sharing, I get the correct behavior 

@perrelle, thanks for the second demo.  It helped to clarify the issue (i.e. it's a problem with style bypass application rather than style parsing).  Commit 8e0e074 should resolve it.
