### ISSUE TITLE
Removing the container DOM element don't clean hidden div element appended at the end of the document body

### ISSUE THREAD

**Issue by Walkalone13** [cytoscape/cytoscape.js#2735]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.12.1
- React version: 16.12
- Browser/Node.js & version : Chrome 83

**Current (buggy) behaviour**
I'm creating cytoscape instance in React component while opening modal. After removing modal from DOM (i.e. closing it) the hidden div appended at the end remains. Each time I open and close modal another hidden div appended to bottom of body. So I need manually use cy.destroy() or cy.unmount() to clear it.

**Desired behaviour**
As it said in docs: "If you remove the container DOM element from the page, then the instance is cleaned up automatically. Similarly, calling cy.destroy() does this cleanup and removes all the container’s children from the page." I expect that all elements which used by cytoscape should be removed from DOM (not only container’s children).

**Minimum steps to reproduce**

**Comment by r-ba** [comment]
It's unclear to me what specific issue you're facing, though it does sound like it's outside of the scope of this project. You should at the least provide a minimal reproducible example.

On the other hand, based on your description it seems like you might be better off reusing the same cytoscape instance and simply hiding it's container as necessary.

**Comment by maxkfranz** [comment]
@Walkalone13, would you be able to confirm your issue re. https://github.com/cytoscape/cytoscape.js/commit/8b9167d53c77e5560b0e4b81f219d30af8caf6a9 on unstable?

**Comment by Walkalone13** [comment]
https://codesandbox.io/s/react-cytoscape-ritcq?file=/src/Network.jsx

All is seen in console. Or open inspector and see html tree.

Here an example. opening modal with cytoscape cause creating hidden div which is not cleaned up after closing modal div.

**Comment by maxkfranz** [comment]
It's great that you put together a demo.  Would you try it out with a fresh build on the unstable branch?
