### ISSUE TITLE
Attempting to drag multiple nodes at once by appending to a list and using select()

### ISSUE THREAD

**Issue by JROliver3** [cytoscape/cytoscape.js#2737]
Bug request

**Environment info**

- Cytoscape.js version : 3.7.1
- Browser/Node.js & version : 

**Current (buggy) behaviour**

Preface: Not entirely certain if this is a bug or not.

The select() feature when selecting a group of nodes does not select all of the nodes as expected. 

**Desired behaviour**

The nodes should all be selected once activating the select() method on a group of nodes, and they should able to be dragged together as they would if they had all been selected via CTRL + select or using the selection box with the mouse.

**Minimum steps to reproduce**

**Comment by r-ba** [comment]
Can you provide a reproducible example of this behaviour? Seems to be working for me https://codepen.io/r-ba/pen/jOqNYvb
