### ISSUE TITLE
Moving multiple nodes at once by clicking on the nodes without using the modifier key

### ISSUE THREAD

**Issue by mbabatunde** [cytoscape/cytoscape.js#2738]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.7.1
- Browser/Node.js & version : Chrome/v13.8.0

**Current (buggy) behaviour**

This may or may not be a bug.

Currently, if a user wants to select multiple nodes while in the cytoscape container, they have to use a modifier key, such as the control key, to move multiple nodes at once. However, if a user tries to tap on one node and tap on another without using the control key, that is not possible.

**Desired behaviour**

For example, if a user is in a defined mode by selecting a button, the user would like to tap on various nodes and as it taps on said nodes, it wants to move all tapped nodes concurrently.

**Minimum steps to reproduce**

From a previous issue, this [codepen](https://codepen.io/r-ba/pen/jOqNYvb) selects all the nodes at once. However, I would like to press this button, and as I tap on nodes, I can move multiple nodes at the same time.

**Comment by maxkfranz** [comment]
This sounds like an interesting idea for an extension.  Anything in the core library should support the majority of use cases, while extensions can fill in the gaps for more niche use cases.
