### ISSUE TITLE
gradient border-color

### ISSUE THREAD

**Issue by canbax** [cytoscape/cytoscape.js#2742]
**Issue type**

Feature request

Just like gradient background color, I would like gradient colors for border-colors. Below is just an image similar to what I would like to see.
![image](https://user-images.githubusercontent.com/8426741/92325562-87885780-f054-11ea-9e92-d1105d521d60.png)

**Motivation for new feature**
It looks nice.

**Comment by maxkfranz** [comment]
Do you have a proposal for the style properties?
