### ISSUE TITLE
Node label text clipping for certain fonts

### ISSUE THREAD

**Issue by samhuk** [cytoscape/cytoscape.js#2746]
**Issue type**
Bug report

**Environment info**

- Cytoscape.js version 3.15.0
- Browser/Node.js & version : All browsers

**Current (buggy) behaviour**
The "box" that is placed around node labels is not sufficiently wide for certain texts, causing the text to be clipped a small amount on one or both sides.

I cannot seem to reproduce this in a simple jsbin, so I am not sure what could be causing this. I am hoping this is a known pitfall.

Examples:
![](https://i.stack.imgur.com/UFxOG.png)
![image](https://user-images.githubusercontent.com/10605534/93067395-127bda00-f673-11ea-8216-69f371e2fb3d.png)

If I zoom in a lot, the clipped label text appears, however!
![image](https://user-images.githubusercontent.com/10605534/93069068-20325f00-f675-11ea-861b-18dbf0144db0.png)

**Desired behaviour**
Node label text never clips.

**Minimum steps to reproduce**
The node styling is something like as seen in this jsbin: https://jsbin.com/kajabud. However, I don't get the issue. Something in my own environment seems to be causing this issue.

**Comment by maxkfranz** [comment]
It looks like your browser doesn't have proper kerning for the text.  There's probably nothing that can be done on the JS side.  Maybe a different font would work better on your OS/browser combination.

**Comment by samhuk** [comment]
> 
> 
> It looks like your browser doesn't have proper kerning for the text. There's probably nothing that can be done on the JS side. Maybe a different font would work better on your OS/browser combination.

Changing to a different font seems to have fixed it. Ah, that was one thing I didn't try! Thanks.

**Comment by nicklas-delphai** [comment]
I'm having this issue, too. Unfortunately using a different font isn't really possible for us, because of branding. Isn't there anything that could be done?
![2021-01-08_16-36](https://user-images.githubusercontent.com/67684610/104033122-66d13980-51cf-11eb-97f0-b484dbd08d2e.png)
![2021-01-08_16-37](https://user-images.githubusercontent.com/67684610/104033124-6769d000-51cf-11eb-99c6-34f8acf1c63e.png)

**Comment by maxkfranz** [comment]
Isn't the label value deprecated?

**Comment by zzkt** [comment]
I came across something similar and it does seem like a kerning issue. Looks like a simple work-around is adjusting the style  to include `'font-kerning': 'auto'` or `'font-kerning': 'none'` depending on the font. YMMV.
