### ISSUE TITLE
Style updates are faulty after switching to a new stylesheet

### ISSUE THREAD

**Issue by tothandras** [cytoscape/cytoscape.js#2747]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version: `3.16.0`
- Browser/Node.js & version: `Chrome Version 85.0.4183.83`

**Current (buggy) behaviour**

After updating to latest version (`3.16.0` from `3.15.3`) style updates no longer work as expected. Some styles seems to be cached, while the underlying stylesheet is correct (`cy.style().json()`).

**Desired behaviour**

Styles should be updated as in previous versions.

**Minimum steps to reproduce**

https://jsbin.com/zuqucan/2/edit?html,css,js,output

**Comment by maxkfranz** [comment]
Try a build off of master, and let me know if it looks good.

**Comment by tothandras** [comment]
@maxkfranz it seems to be working, thank you!

**Comment by maxkfranz** [comment]
Great; released
