### ISSUE TITLE
live development not working

### ISSUE THREAD

**Issue by CRGavrila** [cytoscape/cytoscape.js#2748]
**Issue type**
Development  yarn watch:fast doesn't build the src file

Bug report

**Environment info**

- Cytoscape.js version : 3.16.0
- Browser/Node.js & version : v12.18.3

**Current (buggy) behaviour**
Rollup is watching src file and complies the build, but changes will not effect

**Desired behaviour**
After saving some code changes in src/index (eg: add console log), 

```
let cytoscape = function( options ){
  console.log('render');

```
accessing http://127.0.0.1:8080/documentation/demos/compound-nodes/ should show in developer tools the console

**Comment by maxkfranz** [comment]
The documentation is a separate build target from building the source:   https://github.com/cytoscape/cytoscape.js#build-instructions

```
npm run build
npm run docs
```
