### ISSUE TITLE
Label alignment : Labels not centered

### ISSUE THREAD

**Issue by arnaudbuy** [cytoscape/cytoscape.js#2749]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.16.1
- Browser/Node.js & version : Google Chrome 85.0.4183.121

**Current (buggy) behaviour**

![Screenshot from 2020-09-22 15-46-22](https://user-images.githubusercontent.com/7791859/93892579-f6b8a980-fcec-11ea-9918-47dabf207d36.png)

**Desired behaviour**

![Screenshot from 2020-09-22 15-47-21](https://user-images.githubusercontent.com/7791859/93892635-089a4c80-fced-11ea-8262-86c585445c3d.png)

**Minimum steps to reproduce**

https://jsbin.com/nokulopoqo/edit?html,css,js,output

**Comment by maxkfranz** [comment]
This looks like a minor issue re. https://github.com/cytoscape/cytoscape.js/issues/2723 and 8b9167d53c77e5560b0e4b81f219d30af8caf6a9.  I'll try to set aside some time for a quick patch on Friday.

**Comment by maxkfranz** [comment]
Try a build off of the master branch to see whether it's resolved for your use case.

**Comment by arnaudbuy** [comment]
The problem is still here.

**Comment by maxkfranz** [comment]
Are you sure that you tested with a fresh build on the latest master branch?  See https://github.com/cytoscape/cytoscape.js#build-instructions

<img width="505" alt="Screen Shot 2020-09-28 at 15 03 19" src="https://user-images.githubusercontent.com/989043/94474654-f06a7780-019b-11eb-942d-645c67f03562.png">

**Comment by arnaudbuy** [comment]
Sorry, confusion on my part between the npm commands and the build and dist directories. the problem is effectively resolved. Thank you !

**Comment by janhartmann** [comment]
I just upgraded and now seeing misaligned edge labels?

![image](https://user-images.githubusercontent.com/1107383/99874776-d1202180-2c03-11eb-8207-aa5ba6793d38.png)
