### ISSUE TITLE
min-zoomed-font-size-show

### ISSUE THREAD

**Issue by blazespinnaker** [cytoscape/cytoscape.js#2751]
<!-

**Description of new feature**

similar to min-zoomed-font-size, would be nice to have a boolean min-zoomed-font-size-show (or something equally effective).  So instead of not showing the label at the zoom level, rather the label is shown at the min font size given by the prior property.

**Motivation for new feature**

The use case is there are certain nodes / edges which you want to show their labels visibly in a very zoomed out  view as they will represent the nodes/edges around them and will assist users in locating the data they are looking for when zoomed out.  

This should also allow for greater use of min-zoomed-font-size and not rendering labels to increase performance, as users will likely just prefer to see the central representative node label anyways.

While in theory it might be possible to simply assign a much greater front size to those nodes, there are circumstances where you don't want to unnecessarily obstruct / overwhelm the viewport when zoomed in with very large fonts.   

Another possibility is having a font zoom adjust rate, so that certain labels don't decrease in font size as fast as other labels as you zoom out.

Hopefully this is a minor change, with minimal backwards compatibility issues, but very significant value proposition (large data navigation enhancement).

**Comment by blazespinnaker** [comment]
If someone can provide a brief overview of where to look and what considerations to keep in mind, I'd be happy to take a stab at a PR.

**Comment by maxkfranz** [comment]
I don't think it's possible to have fixed-size labels.  The zoom is optical, so text scales with the zoom level.

It sounds like you might be better served by creating a responsive design.  Just like you can create breakpoints for CSS+HTML, you could apply different styles at different zoom levels (e.g. show these labels on zoom range [a, b], and show other labels on zoom range [c, d]).

The purpose of the `min-zoomed-font-size` property is just to remove labels that are too small to read.  If you can't read them anyway, there's no point spending time rendering them.

**Comment by blazespinnaker** [comment]
Yes, that was one of the options I was thinking as well and it didn't seem that complicated.  I thought however the feature would be generically useful.  I've used a number of cytoscape demos and I'm always surprised at the lack of visual information when I zoom out.

**Comment by blazespinnaker** [comment]
Found an earlier comment by @maxkfranz with example code:



cy.on('zoom', function(){
  let z = cy.zoom();

  if( z > 2 ){
    cy.elements().removeClass('z-lt-2').addClass('z-gt-2');
  } else {
    cy.elements().removeClass('z-gt-2').addClass('z-lt-2');
  }
});
