### ISSUE TITLE
Label bounds invalid w.r.t. lazy style changes

### ISSUE THREAD

**Issue by Kutkov** [cytoscape/cytoscape.js#2752]
Bug report

- Cytoscape.js version : 3.16.1
- Browser version : Google Chrome 85, Firefox 80

**Current (buggy) behaviour**
When changing the node label, an error occurs in the rendering of the new label.
I change the label like this: ```cy.$('#1').data({ label: 'Label to the cy node, text'})```
There is no such problem in the 3.15 cytoscape version.

Incorrect:
![image](https://user-images.githubusercontent.com/29865209/94162576-88601c80-fe8f-11ea-8ed9-be50f61a1f3e.png)
Correct:
![image](https://user-images.githubusercontent.com/29865209/94162825-cbba8b00-fe8f-11ea-95e5-fafd9bbd5fdb.png)

**Minimum steps to reproduce**
Codepen: https://codepen.io/kutkov/pen/BaKMZGO
Change the label, zoom in, zoom out

**Comment by canbax** [comment]
I also observe a very similar problem. Rendering of labels is not stable. When you zoom in they might get corrupted. When you change the `text-wrap` style they also corrupt.

![Kn4a958Kk7](https://user-images.githubusercontent.com/8426741/94269894-f7994780-ff47-11ea-939d-07c03de9d10a.gif)


[minimum reproducible sample](https://codepen.io/canbax/pen/xxVBGqa)

**Comment by blazespinnaker** [comment]
Probably the same bug - https://github.com/cytoscape/cytoscape.js/issues/2754

**Comment by maxkfranz** [comment]
Try a build off of the master branch to see whether it's resolved for your use case.

**Comment by canbax** [comment]
I couldn't reproduce on [my sample](https://codepen.io/canbax/pen/xxVBGqa) but when I tried my local app, I see the same deformations on labels.

**Comment by Kutkov** [comment]
Build from master branch solves my case.

**Comment by maxkfranz** [comment]
> I couldn't reproduce on my sample but when I tried my local app, I see the same deformations on labels.

Are you certain that your build is using the latest code on master?  You could put a line like this in the Cytoscape source files before building to confirm:

```js
console.log('cytoscape@3.16.2-snapshot');
```

If the build is correct, you should see that log in your app.

**Comment by canbax** [comment]
I didn't see that log. Actually, I'm not sure about how can I "build from master". Here is what I did
- I deleted package-lock.json
- I deleted node_modules/cytoscape folder
- I set my Cytoscape dependency to `"cytoscape": "github:cytoscape/cytoscape.js#master",` inside my package.json file.
- I run `npm install`

Should I fetch cytoscape.js repository and manually build it?

**Comment by maxkfranz** [comment]
> Should I fetch cytoscape.js repository and manually build it?

Yes, that's the correct approach.

**Comment by canbax** [comment]
My problem is also solved now. It is unrelated but I want to ask How can I import ESM module? I'm using angular and import it like `import cytoscape from 'cytoscape';` in my typescript file. I wrote logs to all files under `\dist` folder. I see that I'm using `cjs` file. Can I configure angular to use `esm.js` file? 

Thank you

**Comment by maxkfranz** [comment]
@blazespinnaker, does the commit resolve your issue described in #2754?

**Comment by maxkfranz** [comment]
I've just released 3.16.2.  If @blazespinnaker or anyone else has further issues, post a new issue.
