### ISSUE TITLE
Documentation | Missing changelog

### ISSUE THREAD

**Issue by shaharkazaz** [cytoscape/cytoscape.js#2757]
**Issue type**
Documentation request

I can't seem to find a changelog anywhere, am I missing something? 
If there isn't one currently, is it possible to add one to the library? I want to upgrade my current version but have no idea what changes have been made.

**Comment by maxkfranz** [comment]
Everything's on the website: https://js.cytoscape.org/#introduction/releases

Github just has the code.

**Comment by shaharkazaz** [comment]
Thanks for the quick response 🙂 
I personally find it less convenient since I had to visit around 12 links to see the changes from my current version.
I think that a single CHANGELOG file might provide a better overview. (a common practice in a lot of projects)
