### ISSUE TITLE
Zero-width spaces show up when label text is wrapped

### ISSUE THREAD

**Issue by amitmun** [cytoscape/cytoscape.js#2758]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.16.1
- Browser/Node.js & version : Google Chrome 85.0.4183.83 (Official Build) (64-bit)

**Current (buggy) behaviour**

Labels that contain text with zero-width spaces (\u200b) display these spaces when wrapped by whitespaces (if the label is long enough to exceed the text max width as set in the graph style). When not wrapped (since label is short), the spaces are not visible.
This bug does not occur when text-overflow-wrap is set to 'anywhere'.

**Desired behaviour**

Zero-width spaces should never be displayed.

**Minimum steps to reproduce**

- Create a graph of 'breadthfirst' layout
- In the style, set node label to 'data(id)', text-wrap to 'wrap' and text-max-width to '125px'
- Create 2 nodes with the following IDs:
    - 123\u200b456\u200b7890\u200b123\u200b456\u200b7890
    - 123\u200b456\u200b7890

The result is:
![image](https://user-images.githubusercontent.com/5967464/95317407-d288cb00-089d-11eb-953c-0e5f8d691ebf.png)

- The short label does not display any spaces
- The long label displays the zero-width spaces

**Comment by maxkfranz** [comment]
I think that only normal space-separated words are supported, and the spaces are collapsed to a single space -- like in HTML.  I think that zero width spaces are only hints for CJK character sets.

If you want to support a new feature, this may be a good place to add your new feature in a PR:

https://github.com/cytoscape/cytoscape.js/blob/a0cb418ab125c7fb12b07f513ad280ce708b1d63/src/extensions/renderer/base/coord-ele-math/labels.js#L323-L436

**Comment by maxkfranz** [comment]
See overflow:anywhere re. CJK

**Comment by amitmun** [comment]
Thanks for the information.

How do you explain the difference between the 2 nodes **on the same graph** in my screenshot? Both include zero-width spaces and are displayed differently.
I used zero-width spaces since it should be supported based on the documentation (https://js.cytoscape.org/#style/labels):
> text-wrap : A wrapping style to apply to the label text; may be none for no wrapping (including manual newlines: \n), wrap for manual and/or autowrapping, or ellipsis to truncate the string and append ‘…’ based on text-max-width. Note that with wrap, text will always wrap on newlines (\n) **and text may wrap on any breakable whitespace character — including zero-width spaces (\u200b)**.

**Comment by maxkfranz** [comment]
One has wrapping applied, the other does not.  HTML behaves the same when you turn off wrapping. ZWS is only supported for CJK with `text-overflow-wrap: anywhere`.  See https://github.com/cytoscape/cytoscape.js/issues/2119

If you want to support ZWS generally (e.g. for the Latin alphabet), then that would be a new feature.

**Comment by maxkfranz** [comment]
> I'll give it a try. Shouldn't be too hard.
> Thanks for the link!
> You break words by `wordsRegex` (`/[\s\u200b]+/`), which is great, but then joins them together with `wordSeparator` which is always a single space in case of whitespaces wrapping.
> I'll change that so joining words will be a single space or zws depending on the original separator.

@amitmun, sounds good.  Let me know once you've made your PR and I'll try to set aside time to merge it in for release ASAP.

**Comment by Uneedcode** [comment]
may I ask a question?how can i draw the label over the arrow line ? and how to draw one node with two labels in?

**Comment by maxkfranz** [comment]
@amitmun, how's your progress looking on this issue?

**Comment by amitmun** [comment]
@maxkfranz I plan to fix this during this month

**Comment by maxkfranz** [comment]
Sounds great.  Looking forward to it
