### ISSUE TITLE
panify doesn't work on compound nodes

### ISSUE THREAD

**Issue by blazespinnaker** [cytoscape/cytoscape.js#2759]
fairly easy to repro, just execute panify() in the console on a compound node.  When you click on the compound node and drag it, cy doesn't drag or pan.  Running unpanify() again fixes it so you can drag it.

Note that the panify feature is particularly useful for compound nodes.  We can have large amounts of children in compound nodes and being able to pan while zoomed and pressing (for example) the shift key is very useful, moreso than regular nodes/edges.  In fact, I have not enabled the same behavior for nodes/edges as I felt it would be computationally more expensive to call panify on all elements rather than just parents.   

It might be interesting to support cy.panify (or something similar) which turns off dragging of all elements and everything is passed through to panning, especially if it can be done computationally cheaper than calling cy.elements().panify()

**Comment by blazespinnaker** [comment]
I commented out the code in https://github.com/cytoscape/cytoscape.js/blob/bd4f56ab7fc8b2ff9e5a81c4f1beedda098fb549/src/extensions/renderer/base/load-listeners.js that checks for compound nodes.   Seems to work very well now.

**Comment by ludoo0d0a** [comment]
Pan the whole graph with compounds elements could be very useful

**Comment by maxkfranz** [comment]
> I commented out the code in https://github.com/cytoscape/cytoscape.js/blob/bd4f56ab7fc8b2ff9e5a81c4f1beedda098fb549/src/extensions/renderer/base/load-listeners.js on ~line 115 that checks for compound nodes. Seems to work very well now.

That seems a bit extreme, and I suspect it would affect other cases.  It may be better to be more precise on line 120:

https://github.com/cytoscape/cytoscape.js/blob/bd4f56ab7fc8b2ff9e5a81c4f1beedda098fb549/src/extensions/renderer/base/load-listeners.js#L112-L130

Maybe something like `&& !down.pannable()` to 120.  Would you experiment with that sort of idea and update us here with your results?

**Comment by blazespinnaker** [comment]
Seems to work so far.  Apologize for the naive q - I'm guessing you don't want to pan unless the hierarchy is fully pannable?

There is a slight rapid flash when I go to pan as it switches between trying to drag versus trying to pan.  

(https://imgur.com/a/2yJ9kWu)

**Comment by maxkfranz** [comment]
> There is a small issue when I go to pan as it switches between trying to drag versus trying to pan, though I was getting that by commenting it all out as well.
>
> This is likely because when I go mousedown it still hasn't switched to panify yet and renders the overlay(ghost?). Is there a mouse event I can trap and call panify before the overlay(?) is rendered?

The overlay is shown when any element is `:active`, by the default stylesheet.  You could override that, but it would be useful in that case to have new `:pannable` and `:unpannable` state selectors (e.g. `:active:unpannable { overlay-opacity: 0; }`).

**Comment by maxkfranz** [comment]
Though the overlay is useful for things like giving feedback for tap events, so it depends on the case.

**Comment by maxkfranz** [comment]
> Made the !down.pannable chg. Seems to work so far. Apologize for the naive q - I'm guessing you don't want to pan unless the hierarchy is fully pannable?

Since the event bubbles up the compound hierarchy, it makes sense to restrict things.  The same logic should apply for dragging w.r.t. locked compounds.

If your change is working for you, would you make a PR for it?  If you needed to include anything else apart from the single check, please include that as well.
