### ISSUE TITLE
Ellipsis text wrap option will put ellipsis when the label could fit in full

### ISSUE THREAD

**Issue by msalihaltun** [cytoscape/cytoscape.js#2761]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.16.2
- Browser/Node.js & version : Chrome Version 86.0.4240.75 (Official Build) (64-bit). See JSBin for all else.

**Current (buggy) behaviour**

When `text-wrap` is set to `ellipsis`, cytoscape will put ellipsis at the end of the node label even if the label could have fit at full size. The logic to put ellipsis is [here](https://github.com/cytoscape/cytoscape.js/blob/a0cb418ab125c7fb12b07f513ad280ce708b1d63/src/extensions/renderer/base/coord-ele-math/labels.js#L412) and it tries to put ellipsis and then test if the width with ellipsis and next character exceeds max width, and if it does, it will put the ellipsis. But when the next character is the last character, it won't check whether that character could have fit without adding the ellipsis. It doesn't help that the ellipsis will always be wider than a single character, so we end up with ellipsis and a wider label instead of just the last character.

**Desired behaviour**

Cytoscape should be able to check if the full label will fit when checking the character before the last one, so that the label won't end up putting ellipsis in place of a single character.

**Minimum steps to reproduce**

See the [JSBin output](https://output.jsbin.com/jineyemexi). We have two nodes with the same label, and equal values for `width` and `text-max-width`. One of them has `text-wrap` set to `wrap` and the other has it set to `ellipsis`. The node with `text-wrap: ellipsis` will put ellipsis instead of one character, when it is obvious that the label could fit inside the node as in the node with `text-wrap: wrap`.

**Comment by maxkfranz** [comment]
@msalihaltun, it sounds like you already have a handle on the precise cause of the issue.  You're welcome to make a PR, if you like.  That would help to get the patch released faster.  Thanks

**Comment by blazespinnaker** [comment]
I've run into something similar, I have just worked around it.  @msalihaltun if you don't want to do the builds / testing, you can paste in the code here (or in my repo) and I can do it in my build / test and you can do the PR.  I invited you to my repo.

**Comment by blazespinnaker** [comment]
cool.  a little off topic but is it me, or does this code look a little problematic from a perf point of view:

for( let i = 0; i < text.length; i++ ){
      let widthWithNextCh = this.calculateLabelDimensions( ele, ellipsized + text[i] + ellipsis ).width;	     

Is there a good place to note these concerns?  Don't want to pollute issues

**Comment by msalihaltun** [comment]
@blazespinnaker, I don't know where to note the concerns either, but if it calculates the width for a character that should have been already calculated on a previous call, it could be an issue for long labels. I didn't go too far into the details, but maybe there is some caching/memoization going on?

**Comment by blazespinnaker** [comment]
Hmm, actually, just curious - wouldn't simply increasing max width have been a good workaround on this?   This actually might break a lot of graphs for those people that did.

**Comment by msalihaltun** [comment]
That was my initial thought for a workaround, but we had some concerns regarding how much of an increase in max width was needed exactly, and does that depend on the particular characters etc. Also, does too much increase in max width cause the text to overflow from some nodes in a 'not so nice to look at' way?

**Comment by maxkfranz** [comment]
> cool. a little off topic but is it me, or does this code look a little problematic from a perf point of view:
> 
> for( let i = 0; i < text.length; i++ ){
> let widthWithNextCh = this.calculateLabelDimensions( ele, ellipsized + text[i] + ellipsis ).width;
> 
> Is there a good place to note these concerns? Don't want to pollute issues

It could be using something better like a binary search, but all of the label stuff should only be called when the label changes anyway.  Since that rarely happens, it's not really much of an issue in practise.  So it's probably better to just keep things simple until it's identified empirically as a bottleneck.

**Comment by maxkfranz** [comment]
@blazespinnaker, could you confirm that @msalihaltun's patch works for you?

**Comment by blazespinnaker** [comment]
yes, it works.  It allows for ~3 more characters to be shown, which is especially useful when you have a low max width.

**Comment by maxkfranz** [comment]
Great.  I'll release today
