### ISSUE TITLE
How to set Style 'text-rotation' to 'autorotate' using Typescript? 

### ISSUE THREAD

**Issue by speatzle** [cytoscape/cytoscape.js#2769]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.16.3
- Browser/Node.js & version : v12.18.2

**Current (buggy) behaviour**

When using Typescript i am unable to set the styles `'text-rotation'`, `'source-text-rotation'` and `'target-text-rotation'` to the string `'autorotate'` as described in the [documentation](https://js.cytoscape.org/#style/labels) under the point "Rotating text" because these only accept numbers as values.

**Desired behaviour**

Be able to use the autorotate feature when using Typescript.

**Minimum steps to reproduce**
1) Make a Typescript project.
2) Import Cytoscape,js
3) Try Setting style 'text-rotation', 'source-text-rotation' or 'target-text-rotation' to 'autorotate'
4) Try to Compile and get The Error:` 'TS2322: Type 'string' is not assignable to type 'number | MapperFunction<EdgeSingular, number> | undefined'.'`

Example Style: 
```
import { Stylesheet } from 'cytoscape';
const cyStyle: Stylesheet[] = [{
  selector: 'edge',
  style: {
    label: 'Test Text',
    'text-rotation': 'autorotate',
  },
}]; 
```

**Comment by smith** [comment]
There are definitely some incorrect types (either out of date or that were always incorrect) in [the DefinitelyTyped definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cytoscape/index.d.ts). There are no type definitions in this repository or shipped with the cytoscape.js packages.

You can either open a PR on that repo to fix them or use `@ts-expect-error` in your code with an informative comment about the correct behavior.

**Comment by maxkfranz** [comment]
See also https://github.com/cytoscape/cytoscape.js/issues/1012

**Comment by speatzle** [comment]
I see. Thanks
