### ISSUE TITLE
Node's background image rendering at different zoom levels

### ISSUE THREAD

**Issue by arnaudbuy** [cytoscape/cytoscape.js#2775]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.17.0
- Browser/Node.js & version : Google Chrome Version 86.0.4240.183 (Official Build) (64-bit)

**Current (buggy) behaviour**

![image](https://user-images.githubusercontent.com/7791859/99195896-f8509c00-2788-11eb-9d1e-bbad56be3423.png)

**Desired behaviour**

![image](https://user-images.githubusercontent.com/7791859/99195954-672df500-2789-11eb-8021-0a3a4bfc708b.png)

In my use, it would be cool if I could choose between pixelated or smooth rendering of node background images.

**Minimum steps to reproduce**

https://jsbin.com/genefidara/edit?js,output

**Comment by maxkfranz** [comment]
Could you upload your image in a comment here?  Describe the image and its associated use case in your app.

**Comment by arnaudbuy** [comment]
In my app, i use node's background images to show the underlying node layer function.

![image](https://user-images.githubusercontent.com/7791859/99606883-e847ef00-2a0a-11eb-8fde-dabe4e036ee7.png)

For example in this screenshot, the node represent a network layer which process a vertical edge.

![image](https://user-images.githubusercontent.com/7791859/99608143-9a80b600-2a0d-11eb-8681-c64a8ee26e7c.png)

I build the node image from a canvas for which I can set the dimensions and in which I draw the pixels.

![image](https://user-images.githubusercontent.com/7791859/99608799-ea13b180-2a0e-11eb-8d2d-eac017c1ab72.png)


The node image serve as well as a base to contruct a visualization of the network layer state.

**Comment by arnaudbuy** [comment]
To summarize:
- Currently, the node background image changes from a smooth image to pixelated depending on the zoom level since version 3.17.0, which seems to be a bug.
- In my use case, I would like to be able to set the rendering of the background image of the nodes to smooth or pixelated regardless of the zoom level which seems to be a new feature.

**Comment by arnaudbuy** [comment]
Yes it's true, I could have made even lighter, a 2x1 image, to represent a black side and a white side.

Ok, but I still can't explain the difference in behavior between version 3.16 and 3.17 ?

**Comment by maxkfranz** [comment]
It could just be a coincidence.  [3.17 doesn't contain anything that looks to be related](https://github.com/cytoscape/cytoscape.js/milestone/205?closed=1).  Have you tried using larger images?

**Comment by arnaudbuy** [comment]
It seems that the problem comes from this change ab85d3553cf4e533454740e2824fd41cd7fe263a

Wouldn't it be `ele.removed()` instead of `!ele.removed()` in the test ?

**Comment by arnaudbuy** [comment]
Also, after looking at the code, i think it should be possible to have a user-controlled interpolation using `setImgSmoothing` function on all canvas contexts, including `OffscreenCanvas` ones ?

**Comment by maxkfranz** [comment]
> It seems that the problem comes from this change [ab85d35](https://github.com/cytoscape/cytoscape.js/commit/ab85d3553cf4e533454740e2824fd41cd7fe263a)
> 
> Wouldn't it be `ele.removed()` instead of `!ele.removed()` in the test ?

That's a good catch.  See #2791 



> Also, after looking at the code, i think it should be possible to have a user-controlled interpolation using `setImgSmoothing` function on all canvas contexts, including `OffscreenCanvas` ones ? Or maybe just in the function `safeDrawImage` ?

The main issue I see is that the lib supports IE9 in v3.  That smoothing feature only exists in IE11: https://caniuse.com/?search=imageSmoothingEnabled

User-controlled features should generally be supported in all the browsers that the lib supports.  It looks like the smoothing feature is currently used only for an optional internal enhancement in the caches.  In any case, the library user shouldn't be able to modify how the caches work.

I suppose you could add a style property like `background-image-smoothing: yes | no` for `safeDrawImage()`, but you'd have to note in the docs that it isn't well supported across browsers:  It would be a hint, not a requirement.

**Comment by maxkfranz** [comment]
Resolved via #2794
