### ISSUE TITLE
Bug: Incomplete type declaration for cytoscape.AnimationOptions.zoom

### ISSUE THREAD

**Issue by inregardstometal** [cytoscape/cytoscape.js#2777]
![image](https://user-images.githubusercontent.com/15616033/99564812-e6ddde80-2998-11eb-9764-0cd93ae397a5.png)

As per the attached image, when zooming using cy.animate( ), the zoom property should accept either zoom option or a number as a value, but this is not permitted by @types/cytoscape's type declaration. 

I modified the type definition to include number as an available type, and it enabled the expected behavior.

**Comment by maxkfranz** [comment]
There aren't yet official TS definitions for this project.  You can contribute to the community definitions on DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/90e2cc19bd0c4e3950204aa26e8a00e60f4fc9f6/types/cytoscape

We're working on supporting TS directly in the repo by using JSDoc annotations, but it's not quite ready for public use yet.
