### ISSUE TITLE
Bug: node background image disappear

### ISSUE THREAD

**Issue by Michael101sh** [cytoscape/cytoscape.js#2779]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.15.2
- Browser version : Chrome -  87.0.4280.66
- Node.js & version : 14.15.0

**Current (buggy) behaviour**

When creating new node, with background image, if the user cis licking on the background placeholder before the image done to loading (and then show), it's making the background disappear when clicking on canvas, and when clicking on the background it's showing again and so on.

**Desired behaviour**

Show the background always.

**Minimum steps to reproduce**

Creating new node and before the background finish to load click on the background placeholder.

**Comment by janhartmann** [comment]
What type of background image is this? If SVG, can you please post the SVG code?

**Comment by Michael101sh** [comment]
@janhartmann Yes, it's SVG. But it's happening with any SVG icon (I have a lot).

SVG for example:
<svg id="Layer_1" enable-background="new 0 0 65 65" height="512" viewBox="0 0 65 65" width="512" xmlns="http://www.w3.org/2000/svg"><g><path d="m.5.5h28.8v28.8h-28.8z" fill="#f1786b"/><path d="m35.7.5h28.8v28.8h-28.8z" fill="#5ac8ae"/><path d="m.5 35.7h28.8v28.8h-28.8z" fill="#41b3e2"/><path d="m35.7 35.7h28.8v28.8h-28.8z" fill="#fdc77c"/><path d="m.5 27.4h28.8v1.8h-28.8z" fill="#e0665c"/><path d="m35.7 27.4h28.8v1.8h-28.8z" fill="#4fb79c"/><path d="m.5 62.6h28.8v1.9h-28.8z" fill="#37afd3"/><path d="m35.7 62.6h28.8v1.9h-28.8z" fill="#f2b770"/><path d="m5.7 48h18.3v4.2h-18.3z" fill="#fff"/><path d="m5.7 52.2h18.3v1.6h-18.3z" fill="#37afd3"/><path d="m41 52.2h18.3v4.2h-18.3z" fill="#fff"/><path d="m41 43.9h18.3v4.2h-18.3z" fill="#fff"/><path d="m41 56.3h18.3v1.6h-18.3z" fill="#f2b770"/><path d="m41 48.1h18.3v1.6h-18.3z" fill="#f2b770"/><path d="m24 12.8h-7v-7.1h-4.2v7.1h-7.1v4.2h7.1v7h4.2v-7h7z" fill="#fff"/><g fill="#e0665c"><path d="m12.8 24h4.2v1.6h-4.2z"/><path d="m5.7 17h7.1v1.6h-7.1z"/><path d="m17 17h7.1v1.6h-7.1z"/></g><path d="m58 9.9-2.9-2.9-5 4.9-5-4.9-2.9 2.9 5 5-5 5 2.9 2.9 5-5 5 5 2.9-2.9-4.9-5z" fill="#fff"/><g fill="#4fb79c"><path d="m55 10.3h1.1v5.9h-1.1z" transform="matrix(.707 .707 -.707 .707 25.618 -35.39)"/><path d="m41.7 12.6h5.9v1.1h-5.9z" transform="matrix(-.707 -.707 .707 -.707 67.005 54.027)"/><path d="m55.1 22.8-5-5-5 5-2.1-2.1-.8.8 2.9 2.9 5-5 5 5 2.9-2.9-.8-.8z"/></g></g></svg>

**Comment by maxkfranz** [comment]
@Michael101sh, could you fork this JsBin with your images?

http://jsbin.com/fiqugiq

**Comment by Michael101sh** [comment]
@maxkfranz I tried, but it's not rendering any picture from my server (if I am pasting the url on chrome it's works), it's gray. I tried also with svg from online source and it's the same result.
See: https://jsbin.com/sohijuw/3
The svg is from here: https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/

I think it's having a problem with svg type.

**Comment by maxkfranz** [comment]
> Failed to load resource: FetchEvent.respondWith received an error: TypeError: Origin https://null.jsbin.com is not allowed by Access-Control-Allow-Origin.
