### ISSUE TITLE
Donuts chart on nodes

### ISSUE THREAD

**Issue by EdouardPan** [cytoscape/cytoscape.js#2787]
**Description of new feature**

This demand concerns the property 'Pie chart background'.

Currently you can draw a pie chart for each node. I do not see the possibility to create donut chart (if I am wrong, tell me, I will be delighted!). Would it be possible to consider it?

![image](https://user-images.githubusercontent.com/37474162/100598013-7458f100-32fe-11eb-9130-fbcdf7a9152f.png)

Or would it be possible to have the possibility to set pie drawing behind the basic node. So that, for instance, you can set the style node to:
```
{
   'label': 'xxxx',
   'background-opacity': 100,
   'background-color': 'white',
   'pie-size': '110%',
   'pie-order': 'background',    ##NEW PROPERTY## 
   'pie-1-background-opacity': ...,
   'pie-1-background-color': ...,
   'pie-1-background-size': ...
}
```
Thus the 'normal' node will be over the pie.

Or you could propose a property border for each slice of the pie:
```
{
   'pie-1-border-color': ...,
   'pie-1-border-width': ...
}
```

Thank you in advance.

**Comment by maxkfranz** [comment]
Pie properties will be removed in v4.  See https://github.com/cytoscape/cytoscape.js/issues/2019

There are many charting libraries that generate PNGs or SVGs for pie charts, doughnut charts, etc.  You can use them as background images.
