### ISSUE TITLE
events not working

### ISSUE THREAD

**Issue by nfwyst** [cytoscape/cytoscape.js#2790]
i have code like

window.cy = cytoscape(config)
window.cy.on('layoutready', func)

but the func never called when layout is ready

os: macOS Catalina
chrome: 87.0.4280.67

**Comment by maxkfranz** [comment]
I could not reproduce this on the latest release.  Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.
