### ISSUE TITLE
bug   Cannot read property 'depth' of undefined

### ISSUE THREAD

**Issue by liuzhenxiaoqqq** [cytoscape/cytoscape.js#2795]
**Issue type**

Bug report
Feature request

**Environment info**

- Cytoscape.js version :  3.17.0
- Browser/Node.js & version : 12.18.0

**Current (buggy) behaviour**

Cannot read property 'depth' of undefined
不展示节点

**Desired behaviour**

![image](https://user-images.githubusercontent.com/30256797/101879852-ee298e00-3bcc-11eb-9785-dc1d504f186c.png)

**Minimum steps to reproduce**

**Description of new feature**

**Motivation for new feature**

**Comment by maxkfranz** [comment]
Please provide a reproducible test case, including a code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.
