### ISSUE TITLE
Bounding box is not accurate after changing position of a node

### ISSUE THREAD

**Issue by Ahmed-username** [cytoscape/cytoscape.js#2797]
Hello,
I am using node.boundingBox() for alignment calculations.
However I am getting an explained result after calling position function.
e.g. Given n is a childless node.
console.log(n.boundingBox({}).h; // 100.
n.position(newPos);
console.log(n.boundingBox({}).h; // 400.

Note that when the function call is done the bounding box values return to 100

thanks

**Comment by maxkfranz** [comment]
Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.

**Comment by Ahmed-username** [comment]
Thanks for replying.

Here is the needed details:
- My browser version: Google Chrome version 86.0.4240.198 (Official Build) (64-bit)
- OS version: I use Chrome OS so I believe its the same as browser version
- I have amended the [JSBIN](https://jsbin.com/fivodud/edit?html,js,console,output) link you shared, just click anywhere on the canvas and you'll notice that log values for bounding box are different for before and after
https://jsbin.com/fivodud/edit?html,js,console,output

**Comment by Ahmed-username** [comment]
Sorry I just realised that the jsbin example I have provided proves that it works as intended, I'll try to provide a better example.

**Comment by Ahmed-username** [comment]
Hello again, I was able to replicate the issue on [JSBIN](https://jsbin.com/fivodud/5/edit)
So it is about the label, when a childless node has a label and it is moved through a function, it does not maintain its height/width while the function is still running.
Again please click anywhere on the canvas to see the height has changed (only when the node has been moved which means only the first click in the example I have provided)
https://jsbin.com/fivodud/5/edit

I hope this is clear enough.
Thanks,
