### ISSUE TITLE
Scaling nodes depending on zoom

### ISSUE THREAD

**Issue by NastyaTK** [cytoscape/cytoscape.js#2806]
**Description of new feature**

As an idea for this feature is scaling node depending on zoom. I mean that NOW if I zoom in (making my graph bigger) - nodes became very large and could be as big as graps container, and if I zoom out (making my graph smaller) - nodes became too small so the text on node is no longer visible. It would be great, if nodes will change their size dynamically - if i zoom in node became a little bit smaller, if I zoom out - node became a little bit bigger (so I can read the text on node) 
Here is an a great example of what i mean https://developer.cisco.com/site/neXt/discover/demo/#Basic/base

**Motivation for new feature**

Now in my project I have different Graphs - some of them are a bit small, but some of them are really huge and it will be cool if I have an opportunity to make my graph a bit smaller and still see the text on nodes (ofcourse as long as it possible without nodes and graph deformation)

**Comment by maxkfranz** [comment]
That sounds like an interesting idea.  

Everyone is welcome to make contributions for new features, like your proposed feature.  If you're interested in adding this feature, [we have instructions to help new contributors get started](https://github.com/cytoscape/cytoscape.js/blob/unstable/.github/CONTRIBUTING.md).  If you have any questions about making a pull request or contributing in general, feed free to post a reply in this issue or [in the discussions section](https://github.com/cytoscape/cytoscape.js/discussions).
