### ISSUE TITLE
the compound style could be a circle ?

### ISSUE THREAD

**Issue by steveyang331** [cytoscape/cytoscape.js#2807]
I want to build this https://nivo.rocks/bubble bubble style( circle style), but the compound style is rectangle.

![image](https://user-images.githubusercontent.com/16850883/104442763-7df99800-55d0-11eb-8154-71892a5a4419.png)

Is there a way set a circle style ?

May I request add circle style feature ?

Thank you !

**Comment by steveyang331** [comment]
I'm not good at building code . I can request the feature ,But I can't built it. 
This issue could mark for feature request ?

**Comment by maxkfranz** [comment]
Someone else on your team is free to add a PR for your proposed feature, as is anyone else in the community who is interested in it.  If you're not technically inclined, you could advocate for your feature in your organisation and in the Cytoscape community.
