### ISSUE TITLE
Option for layouts on eles.layout() to ignore nodes not in collection

### ISSUE THREAD

**Issue by Alexithemia** [cytoscape/cytoscape.js#2812]
**Description of new feature**
I would like the ability for layouts to ignore some nodes, specifically just when using eles.layout(), so that elements in the collection would follow the layout and their positioning not be affected by the nodes not in the collection.

**Motivation for new feature**
It may be a small use case, but I am using expand-collapse and after expanding, I want to run an in-place layout of the child nodes, but other nodes nearby affect how it draws.

**Comment by maxkfranz** [comment]
This is how things currently work.  If you want something else, you could give a better sense of what you're looking for with pictures or a demo.  If you already have a good idea of what you want, feel free to open a PR with your new feature.  [Take a look at the contributor's guide to get started.](https://github.com/cytoscape/cytoscape.js/blob/unstable/.github/CONTRIBUTING.md)

**Comment by Alexithemia** [comment]
My apologies, I didn't really explain the difference I am looking for. It currently does not layout nodes not in the collection, but want it to ignore forces and overlap of nodes not in the collection when running the layout, so when I expand a node and run a layout on those nodes, it results in a clean close setup for those nodes, which can then be dragged to an open location.

So it looks like this
![image](https://user-images.githubusercontent.com/44597137/108247639-86d21200-7118-11eb-8bde-2352a45782ed.png)

Instead of this
![image](https://user-images.githubusercontent.com/44597137/108247931-e4fef500-7118-11eb-88ac-3ae673c7b0f0.png)
