### ISSUE TITLE
Text event is not triggered when text is rotated

### ISSUE THREAD

**Issue by Ahmed-username** [cytoscape/cytoscape.js#2813]
Hello,

I am facing a bug where clicking on a node text/label does not trigger when the node has text rotation.
- I am using Google chrome Version 86.0.4240.199.
- This is the [JsBin](https://jsbin.com/bigoqocozi/1/edit?html,js,console,output) link to replicate the bug.
Please click on the Bird label and you'll see a log to confirm that, however clicking on the cat label does not trigger an event.
The only difference between the cat and bird nodes the text rotation

Thanks,

**Comment by Atombuddy** [comment]
Sorry ,But the provided link works fine.

**Comment by Ahmed-username** [comment]
Hello @Atombuddy, 
I have updated my Chrome to  88.0.4324.109 and I'm still facing the same issue.
Basically the 'cat' label is being treated as if its still horizontal.
E.g. If you click on word 'bird', event is being fired. While if you click if the word 'cat' no event being picked up.
Having said that if you click on the right of the cat an event will be triggered although the label is up.
I have amended the [JsBin](https://jsbin.com/nukulidade/1/edit?html,js,console,output) example a bit

Please let me know if you still can't replicate it.

Thanks,
