### ISSUE TITLE
Layout not calculating correctly (breadthfirst, directed)

### ISSUE THREAD

**Issue by daveish** [cytoscape/cytoscape.js#2821]
**Environment info**

- Cytoscape.js version : 3.18.0
- Browser/Node.js & version : Chrome 88.0.4324.150

**Current (buggy) behaviour**

When calculating the percentedWeight while sorting the graph in the layout phase, an access to props of undefined error happens. Due to this, the layout cannot be calculated and the JS errors.

**Desired behaviour**

The layout should be rendered anyway.

**Minimum steps to reproduce**

See comment in line 70:

https://codesandbox.io/s/cytoscape-demo-forked-ndhsq?file=/src/index.js

**Comment by maxkfranz** [comment]
The exception could be swallowed.  In any case, a non-DAG will not get a good result for a DAG layout.
