### ISSUE TITLE
Draw dots at crosspoint : taxi 

### ISSUE THREAD

**Issue by moriakijp** [cytoscape/cytoscape.js#2829]
It would be useful if there a way to draw dots on cross  points, we can know easily whether or not it is the connection point or not.

You can get an image of the perspective in the following posts.
https://stackoverflow.com/questions/65923577/how-is-it-possible-to-draw-no-contact-crossover-edges-in-cytoscape

Options are like 
```diff
 {
  "selector": "edge.taxi",
  "style": {
    "curve-style": "taxi",
    "taxi-direction": "downward",
    "taxi-turn": 20,
    "taxi-turn-min-distance": 5,
+    "contact": "dot",   //  Possible values are "cross", "dot", "separated-dot"
+    "no-contact": "crossover"   //  Possible values are "cross", "crossover"
  }
```
If we know how to the taxi drawing algorithm decide whether cross points or not, it is likely to give a further perspectives.

This feature is beneficial especially for experts who treat crowded Wiring Diagrams. if the feature realize, it can be simplify 2DCAD using cytoscape.js, then transform an initial diagrams and dynamically create variety of arrangements for actual wiring.

**Comment by maxkfranz** [comment]
It looks as though you've got a good handle on the API-facing part of the design of your feature.  If you're interested in this feature, I'm open to reviewing your code once it's posted in a pull request.  For information on getting started, refer to our [contributing file](https://github.com/cytoscape/cytoscape.js/blob/unstable/.github/CONTRIBUTING.md) and its links.
