### ISSUE TITLE
Machine readable schema for core cytoscape

### ISSUE THREAD

**Issue by AZaitzeff** [cytoscape/cytoscape.js#2847]
**Description of new feature**

Machine readable schema for the json that core cytoscape uses for initialization.

**Motivation for new feature**

- Allows for easier interface between cytoscape and graphs specified with other tools.
- Allows for easier building of UI interfaces for building graphs in cytoscape
- Good resource to have with the documentation.

**Comment by AZaitzeff** [comment]
Though if anyone is looking for one, I have one partially typed up using JSON Schema draft 7.

**Comment by AZaitzeff** [comment]
I was thinking of it being made available on the cytoscape.js website. It is a compact form of documentation. If you have a json for inputting into cytoscape then one could use a json validator to see if the json is valid.

**Comment by AZaitzeff** [comment]
For context I am making UI to interface with a database (SQL, noSQL, Elasticnet) and then plot the network in cytoscape.js see https://github.com/twosixlabs/escalation

**Comment by maxkfranz** [comment]
> I was thinking of it being made available on the cytoscape.js website. It is a compact form of documentation. If you have a json for inputting into cytoscape then one could use a json validator to see if the json is valid.

Good idea.  Could you put up your spec on Github somewhere?  Then it could be linked in the extensions section in the docs.  Maybe your readme could include links to JSON schema validation tools etc., since some people may not be familiar.  Or eventually you could build it out to a fully-fledge extension that performs the validation.

**Comment by AZaitzeff** [comment]
For sure.  we have done this for a couple of other visualization packages so we may put multiple up on the same github with how to use them.

**Comment by AZaitzeff** [comment]
@maxkfranz I put the spec at https://github.com/AZaitzeff/cytoscape_js_schema. The read links to JSON schema website and tools for validators.

**Comment by maxkfranz** [comment]
Added to the list.  Thanks
