### ISSUE TITLE
Autorotated source-label alignment

### ISSUE THREAD

**Issue by rendall** [cytoscape/cytoscape.js#2849]
This is half-way between a feature request and a bug report. 

Currently there is no way to style variable-width, _auto-rotated_ edge labels so that they are all a consistent distance from their edge endpoint / source node, as shown here:
![mock](https://user-images.githubusercontent.com/293263/113399786-75338980-93a9-11eb-9195-b1877a91bd3b.png)
_There is no way to get this look_

Autorotated edge labels placed at the source are centered on the source node:
![no-offset](https://user-images.githubusercontent.com/293263/113399879-9d22ed00-93a9-11eb-906b-b5bf658b332a.png)
_This is what it does look like now_

 Off-setting the text moves the labels along the edge away from the label, but each label is moved _from its center_, so that long labels end closer to the node and short labels move farther away.  In this figure, it's not easy to tell at first glance if some of the labels are intended to be a _source_ or _target_ label.
![with-offset](https://user-images.githubusercontent.com/293263/113399917-ad3acc80-93a9-11eb-8995-859bb9b1e082.png)
_Offsetting gives a ragged inconsistent appearance_

**Description of new feature**

Edge labels that are placed at the source (`"source-label"`) and are auto-rotated (`"source-text-rotation": "autorotate"`) need to have a `"text-halign"` property with a value (e.g. `"auto"`) that a) pins the _left_ *or* _right_ side of the label's text to the edge end-point depending on the direction of the edge, and b) responds to `"source-text-offset"` by moving the closest label boundary (left or right) away from the node.

There should probably be a corresponding property-and-value for the `"target-label"`s as well.

**Motivation for new feature**

When a directed graph describes states and transitions, it is natural to label the transitions _from_ a state with labels that are close to, but with a consistent visual gap from, its source node. Currently there is no good way to do this.

**Comment by rendall** [comment]
As an added bonus, a `"text-valign"` that moves the label above or below the edge would be helpful too.

**Comment by maxkfranz** [comment]
For context:  The current intended use case for non-centred edge labels is multiplicity, usually a single digit -- which is well supported now.  Usually designers use other dimensions, like colour, to indicate attributes of the data to minimise clutter.

These are interesting ideas.  I have some questions:

How would they work with all the different edge types?   What if the edge is curved?  What if the edge has multiple lines in it?  What if the line is short?  

How would an accurate offset be calculated for different edge types (e.g. curved) when the text is long or the offset is large?

You're welcome to iterate on your ideas here and spec them out in more detail.  They look ambitious, and they could be useful for some use cases.  Keep in mind how to address the those sorts of different edge cases while you're planning.

Looking forward to seeing your next iteration.

**Comment by insiderinside** [comment]
any update ?

**Comment by rendall** [comment]
Hi @insiderinside .  No.  The project I needed this for is on hiatus.  That said, if you wanted to take this on, I could be a sounding board.
