### ISSUE TITLE
Cytoscape rendered in separate window does not handle events correctly

### ISSUE THREAD

**Issue by lilactown** [cytoscape/cytoscape.js#2851]
**Environment info**

- Cytoscape.js version: 3.18.1
- Browser/Node.js & version: Chrome 89.0.4389.114

**Current (buggy) behaviour**

When rendering cytoscape in a separate window created programmatically, events do not bind correctly. Nodes can be selected but never unselect, clicking on the background continually shows the clicked position (rather than clearing on mouseup), and event listeners bound via `.on` are not called.

**Desired behaviour**

Cytoscape binds events to the window that it is rendered within. Possibly allow a parameter that specifies what window object to bind listeners to if that is untenable.

**Minimum steps to reproduce**

Reproduction: http://jsfiddle.net/nbc7puy4/3/

You may need to allow popups from jsfiddle.net when it first loads in order to see the behavior.

**Comment by maxkfranz** [comment]
I think that the motivation for higher-DOM-level listeners was so that things like dragging are a good experience.  If you listen to the container itself, the node drag and pan experiences are bad at and beyond the edges of the container.

Is there a reason the `cytoscape` library isn't loaded into the new `window` instead?

**Comment by lilactown** [comment]
I'm building a tool for a library that I've written which allows users to visualize the state of their running application. I want to access the internal state running in a window with the users app, and use that state to control a visualization in a separate window.

**Comment by lilactown** [comment]
I suppose I could add a script tag to a CDN w/ cytoscape in the child window and operate on it as a global, rather than including it in the bundle. I'll try that.
