### ISSUE TITLE
Add context table to node for preciser description of nodes

### ISSUE THREAD

**Issue by Stephanevg** [cytoscape/cytoscape.js#2853]
Hi guys, first of all, I love your framework, really nice work what you guys have build so far!

**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

Have the possibility to render 'easily' tables in a graph that can help to give more context to a particular node.

**Motivation for new feature**

_Describe your use case for this new feature._

I have a use case, where I would like to create a graph of my IT servers infrastructure. The idea would be to create a map, and than each node would have the server name displayed (so far, pretty standard). 
The new feature, would reside in beeing able to display a table with additional properties of the server, by clicking on the edge. 

Ideally, I could imagine that a new property would could be added to the 'node' element called something around ```DescriptionData``` or ```ExtendedData```  or ```context``` perhaps? 
That property could receive a json formated document that would represent ultimatley a table with additional descriptive data of the node.

**Comment by maxkfranz** [comment]
It sounds like you have a clear idea in your head of how this should look and work.  You're welcome to publish your idea as an extension so that you have a tight integration with the library and to get feedback from the community.

Feel free to post updates of your progress here or in the discussions area.

**Comment by Stephanevg** [comment]
I can for sure have a look at it, but have really now idea where / how to start as i am really no crazy javascript programmer. (far from it actually).
I Was hoping this could be seen as an added value for the framework by the authors / maintainers of the project.
