### ISSUE TITLE
Edges not removed when tab/window inactive

### ISSUE THREAD

**Issue by tristanidoux** [cytoscape/cytoscape.js#2856]
**Environment info**
- Cytoscape.js version : 3.17.1
- Browser/Node.js & version : Firefox v87 / Node.js v12.22.1

**Current (buggy) behaviour**
I don't know whether it's on me or not so I will explain.

I was wondering how to handle the removal of edges when the tab is inactive ? 

At the moment, I have a loop which, depending on the current time, will remove some edges I've created previously. When the window/tab is active, there is no problem & the edges are removed & disappear. However, when the tab/window is not active, the model of the edges is good (meaning all those who should have been removed are gone) but they still appear on the graph (despite the remove edge function being called).

Any idea on what I'm doing wrong ? Could it be related to `requestAnimationFrame` ?

```typescript
// Called using a setInverval loop.
protected _removeObsoleteEdges (){
    let i: number = this._model.length
    while (i--) {
        if (...) {
             this._removedModelSubject.next(this._model[i].id);
             this._model.splice(i, 1);
       }
    }
 }

// Called when the above is triggered 
private _onEdgeRemoved(id: string): void {
    this.__graph.remove('edge[id="' + id + '"]');
}
```

**Desired behaviour**
When returning on the window/tab, the edges shouldn't exist or disappear fast. 

Let me know if you need any more informations from my part & thanks for your time.

**Comment by maxkfranz** [comment]
Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.

As soon as you provide a reproducible demo, this can be investigated further. Thanks for your feedback
