### ISSUE TITLE
In your  tuto, demo

### ISSUE THREAD

**Issue by TonioParis** [cytoscape/cytoscape.js#2866]
In your tuto (https://blog.js.cytoscape.org/2016/05/24/getting-started/),
for the third graph (https://blog.js.cytoscape.org/public/demos/getting-started/index-addingNodes.html),

1 - when I try to reproduce it, but with the last version of your script (https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.18.2/cytoscape.min.js), it doesn't work = produce weird visualization (screenshot below).
2 - And when I replace the last version or your script by the version of your tuto(https://blog.js.cytoscape.org/public/demos/getting-started/cytoscape.js), it works !  ;-)

![cytoscape problem](https://user-images.githubusercontent.com/12527361/119150504-cd544700-ba4e-11eb-85e5-6e61f6652d99.png)

BTW, thank you for all your work !

**Comment by maxkfranz** [comment]
Follow the inline examples in the tutorial, and build up the code yourself in your editor.  That should be fine.  

It looks like those tutorial demo files use v2.7 and they haven't been updated for v3.   The demo links have been removed.  If anyone wants to bring back those links, they're welcome to go to the tutorial source and make a PR to support v3:  https://github.com/cytoscape/cytoscape.js-blog
