### ISSUE TITLE
Allow control of dashed/dotted line definition for nodes as per edges

### ISSUE THREAD

**Issue by Ben-Pattinson** [cytoscape/cytoscape.js#2869]
Currently you can control the look of the dashes/dots on edges but not on nodes. I need to alter the appearance, however the code does not seem to allow for this: 

### Existing
rc/extensions/renderer/canvas/drawing-nodes.js  line#207

```
 if( context.setLineDash ){ // for very outofdate browsers        
switch( borderStyle ){          
          case 'dotted':            context.setLineDash( [ 1, 1 ] );            break;
          case 'dashed':            context.setLineDash( [ 4, 2 ] );            break;
          case 'solid':          
          case 'double':            context.setLineDash( [ ] );            break;        
}      
}
```

### Proposed
The edge implementation can be found here: 
src/extensions/renderer/canvas/drawing-edges.js line#150

It does work on edges. I propose to basically copy/paste the functionality in along with the relevant properties. 

### Why?
I'm attempting to create a long dash border around a composite group of shapes, it works, just doesn't look as desired.

**Comment by maxkfranz** [comment]
This sounds like an interesting feature.  If you're interested in adding this feature, take a look at our contributing file to help you put together a pull request: https://github.com/cytoscape/cytoscape.js/blob/unstable/.github/CONTRIBUTING.md
