### ISSUE TITLE
Add an option for the layout engines to avoid overlap with edge labels 

### ISSUE THREAD

**Issue by Ben-Pattinson** [cytoscape/cytoscape.js#2872]
Currently when a pair of nodes connected by an edge with a label are laid out, no effort is made to ensure the nodes do not overlap the edge label. In many cases this label is just as important as the nodes themselves. In short, the edge text should be a first-class citizen, and be taken into account by the layout engines. Padding around the label should also be available.

A crude workaround can currently be the increase in desired distance between nodes, however this results in a lot of wasted space, as not all labels are the same length, and different orientations require different amounts of space.

**Comment by maxkfranz** [comment]
That's an interesting idea.  Anyone with ideas on how to approach this is welcome to post their ideas here.  Feel free to also post links to relevant papers.

**Comment by adrianbj** [comment]
This would be really helpful, but in the meantime I went with positing the labels inside the nodes (make the node shape an ellipse and setting their width and height to "label". Not saying this is a solution for all use cases but maybe it will help someone in the meantime.
