### ISSUE TITLE
Saving and exporting layout settings

### ISSUE THREAD

**Issue by lalalagartija** [cytoscape/cytoscape.js#2874]
**Exporting layouts with the exact used parameters**

_There should be a way to find out what exact parameters were used and what layout for a given network as it can change drasticly the shape of the figure. There should be a way to get the name of the algorithm used and if there was any changes in the default parameters. For the moment it seams that you rely on the researcher to remember what layout was used right ? Or maybe I missed something._

**FAIR rules and simplification**

_Useful for : - analysing networks done by others and shared through a .cys file. - Pulishing a network with extensive annotation but that we have forgotten what exact parameters was used long ago. -comparing layouts._

**Comment by maxkfranz** [comment]
Hi,

It looks like you're asking about the Cytoscape desktop software.  You can file issues for that software at the links below.  Please file your issues or questions related to Cytoscape desktop software there in future.

- File a bug: https://cytoscape.org/bug-report.html
- Help: https://cytoscape.org/documentation_users.html

You can achieve reproducible results for your research by using scripting (automation), which Cytoscape supports well (e.g. with Python).

 * introduction to automation: https://cytoscape.org/cytoscape-tutorials/presentations/advanced-automation-2020-ucsf.html#/ 
 * automation publication: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1758-4 
 * automation tutorials: automation.cytoscape.org/
