### ISSUE TITLE
A* algorithm not properly accounting for weight (distance)

### ISSUE THREAD

**Issue by Log-Wall** [cytoscape/cytoscape.js#2880]
**Environment info**

- Cytoscape.js version : 3.19.0
- Browser/Node.js & version : Chrome Version 91.0.4472.77 (Official Build) (64-bit)

**Current (buggy) behaviour**
eles.aStar() is not properly using the weight of edges in determining optimal paths. 
Running aStar and dijkstra for the same graph with edges all edges weight set to 1 returns the same result as expected. 
**aStar**

> cy.elements().aStar({
>         root: `#7604`,
>         goal: `#11828`,
>         weight: function (edge) {
>             return edge.data('weight');
>         },
>         directed: true
>     });

Returns: {found: true, distance: 25, path: pa(51), steps: 9948}

**dijkstra**

> cy.elements().dijkstra({
>         root: `#7604`,
>         weight: function (edge) {
>             return edge.data('weight');
>         },
>         directed: true
>     }).distanceTo(`#11828`)

Returns: 25

Added weight to some edges along the path. An extreme number of 1,000 to ensure they would not be used. A* no longer returns the expected value.
(Same code snippets)
**aStar**
Returns: {found: true, distance: 1066, path: pa(135), steps: 18149}

**dijkstra**
Returns: 109
The dijkstra solution is the expected and correct solution.

**Desired behaviour**
aStar() function should be returning an identical solution to the dijkstra solution.

**Comment by maxkfranz** [comment]
I added preliminary tests to verify that A* and Djikstra are returning the same results, where the heuristic isn't used.  If you have specific problematic test cases, then please add them in a PR similar to 97c2770.
