### ISSUE TITLE
Underlay node style

### ISSUE THREAD

**Issue by zakjan** [cytoscape/cytoscape.js#2882]
**Description of new feature**

Draw a halo below the node. Rendering would be exactly the same as overlay, but below the node instead of above.

Add new `halo-*` properties similar to `overlay-*` properties: `halo-padding`, `halo-color`, `halo-opacity`, `halo-shape` (#2881).

**Motivation for new feature**

Another way to highlight a node without overriding its style, e.g. after it is found by user using a search control.

**Comment by zakjan** [comment]
Hi @maxkfranz, could you let me know your thoughts or concerns about this feature?

It might look similar to ghost nodes, but ghost renders all node features (background images etc.). Halo would be a single color, and always larger than the node.

If you give it a green light, I'm available to implement it. It would plug into node rendering before the ghost at https://github.com/cytoscape/cytoscape.js/blob/unstable/src/extensions/renderer/canvas/drawing-nodes.js#L265

**Comment by maxkfranz** [comment]
A simple and consistent approach for this may be to use "underlay" properties that correspond to the existing "overlay" properties.  The underlay would be underneath the element instead of on top of it.

When I hear the word "halo", I would expect to see a circle, with a gap between the circle and the node.  That may be difficult for some node sizes and shapes, and I don't see how it would fit on edges.

**Comment by zakjan** [comment]
@maxkfranz Thanks for the feedback. `underlay` sounds good. Should there be also `includeUnderlays` option for bounding box calculation?

**Comment by zakjan** [comment]
Once `overlay-shape` implementation is confirmed in #2881, I'll implement it similarly as `underlay-style` here.

**Comment by maxkfranz** [comment]
Pinning while the PR is in review

**Comment by igordata** [comment]
I don't like the current overlay solution to highlight selected objects due to it is drawn over the elements and changes their color.
It would be great to have the same overlay but to be drawn under the element.

**Comment by maxkfranz** [comment]
@zakjan @tirrth 

I'd like to coordinate timelines re. the next release.  Ideally, all of these items would be in the next version:

- [ ] #2897 @tirrth 
- [ ] #2882 @zakjan 
- [x] #2881
- [x] #2883

Could you each share your estimated timelines for #2897 and #2882 so we can coordinate a release?

**Comment by zakjan** [comment]
Thanks for pinging me. I have a WIP branch, and the initial implementation might be ready next week.

**Comment by tirrth** [comment]
Hey. I'd get that done by the end of this weekend.

**Comment by zakjan** [comment]
Actually, I was able to fix finish the initial implementation this morning. Please have a look: #2928

**Comment by tirrth** [comment]
Okay. I know I'm taking longer than I promised😶. But Is it okay if I just
take one more day? I'd for sure get everything done tonight🙂

**Comment by maxkfranz** [comment]
> Okay. I know I'm taking longer than I promised😶. But Is it okay if I just take one more day? I'd for sure get everything done tonight🙂
> […](#)

Great, I'll keep an eye out.  Looking forward to a release with all this great new features
