### ISSUE TITLE
Triangle edge style

### ISSUE THREAD

**Issue by zakjan** [cytoscape/cytoscape.js#2883]
**Description of new feature**

Draw edge segments as triangles between edge points, instead of lines.

Add new `edge-style` property, with possible values `line` (default) and `triangle` (ignores `line-style` and `curve-style`, it's always solid and straight).

Additional property might be needed for triangle direction. `width` can be used for triangle width at the base.

**Motivation for new feature**

More prominently visualize the direction of the edge.

**Comment by zakjan** [comment]
PR is #2892

**Comment by maxkfranz** [comment]
Pinned while PR is w.i.p.
