### ISSUE TITLE
Cytoscape disappearing edges with bezier curves and nodes moving/longer labels in nodes

### ISSUE THREAD

**Issue by danail-vasilev** [cytoscape/cytoscape.js#2884]
I am using cytoscape with bezier curves but edges are disappearing when having a node with longer label or just moving source node next to target node.

* Video: https://www.screencast.com/t/N2f5eZ5M7
* Runnable sample: https://stackblitz.com/edit/web-platform-vpl72r?file=index.html

**Comment by maxkfranz** [comment]
I'm fairly sure this has been answered before.  Make sure you specify valid styles where the point calculations are possible

**Comment by danail-vasilev** [comment]
Thanks Max!
What do you mean by "valid styles where the point calculations are possible" ? I've tried removing "target-arrow-shape" and again the same issue.  I've added a sample and a runnable video, could you please take a look when available ?
