### ISSUE TITLE
Parent node min-width adds 83px redundant space

### ISSUE THREAD

**Issue by danail-vasilev** [cytoscape/cytoscape.js#2885]
Parent node min-width adds 83px redundant space
Runnable sample - https://stackblitz.com/edit/web-platform-mdwpbj
Also min-width-bias-right acts as of 100% value no matter whether value is lower

**Comment by maxkfranz** [comment]
I'd encourage you to review the documentation again to get a better sense of the sizing features.  If you run into a bug and you have a minimally reproducible demo with a corresponding bug report that follows the issue template, you're welcome to post those here or in a new issue.

**Comment by danail-vasilev** [comment]
Thanks max!
I have already read the documentation and see nothing wrong with my setup. I have actually reported 2 issues, one of them is for the additional 83px. You can find a fully runnable sample in the first thread.
