### ISSUE TITLE
Layout can't use label size unless labels are overrides

### ISSUE THREAD

**Issue by saulshanabrook** [cytoscape/cytoscape.js#2888]
I believe I have found a bug, that when if you are using a layout with `nodeDimensionsIncludeLabels` it will think the nodes have no labels unless those labels are override styles.

In the documentation, the recommendation is to use a stylesheet to set the label, like this:

```javascript
  {
    selector: 'node',
    style: {
      label: 'data(text)',
    }
  }
```

However, I found that if I did this, the label would properly render, but the layout wouldn't receive their sizes. Instead, if I set the labels directly in the `style` attribute of each node, then the layout will properly render.

I believe the issues is in this line: https://github.com/cytoscape/cytoscape.js/blob/c469431b374ca242ee430560eb0ce966f5bfb2a3/src/extensions/renderer/base/coord-ele-math/labels.js#L10

It will always return an empty string, if the label is set via a style.

**Comment by maxkfranz** [comment]
It looks like you've done some useful initial investigation on the issue.  Would you comment on which particular layouts are problematic?  Further, would you post a reproducible demo to illustrate your issue?  There's a demo you can fork here: http://jsbin.com/fiqugiq

**Comment by saulshanabrook** [comment]
@maxkfranz I had this issue with the ELK layout.

Thanks for the pointer to the demo. Do you have a suggestion on how I can test the ELK layout on there?

**Comment by maxkfranz** [comment]
You could copy parts of the demo from the cytoscape-elk demo into your demo as a starting point.  Make sure to include data that reproduces your issue (style, elements, etc.)
