### ISSUE TITLE
Node text coming out of the box

### ISSUE THREAD

**Issue by manishbitcot** [cytoscape/cytoscape.js#2894]
If i try to add any text without providing space the node text is coming out of the node box.
![Screenshot from 2021-07-01 13-14-01](https://user-images.githubusercontent.com/77380381/124086001-3f687480-da6e-11eb-8003-4a3fad982464.png)

To fix this i tried to add a css text-overflow-wrap: anywhere that fixed this issue but due to this now i was not able to add any text with space so if i add any text with space for example Hello World it would change it to HelloWorld

Overall i need a solution where in if i put text with space or without space or with special symbols or numbers or whatever it is it should not break and show as it is

Please let me know solution for this Thank You :)

**Comment by manishbitcot** [comment]
Hi, 

Is there any fix available for the issue mentioned above

**Comment by maxkfranz** [comment]
Not a bug.  That property is for CJK.  The history of that property should be documented in some issues and PRs, if you're interested in searching around.

If you'd like to support something like automatic hyphenation in the library, you're welcome to propose an API for that and/or post a PR.

Thanks for your feedback.
