### ISSUE TITLE
Documentation and typings for cy.viewport() outdated/wrong

### ISSUE THREAD

**Issue by timotgl** [cytoscape/cytoscape.js#2896]
**Issue type**

Bug report

**Environment info**

- Cytoscape.js version : 3.15.4
- Browser/Node.js & version : not relevant

**Current (buggy) behaviour**

The [documentation](https://js.cytoscape.org/#cy.viewport) for `cy.viewport(opts)` describes the function as expecting two arguments `pan` and `zoom` (it does however have a correct example that illustrates how the function actually works). Same for the typings:

![typings-viewport](https://user-images.githubusercontent.com/366377/125472962-deb46652-7279-4cac-b215-527e05cdc504.png)

The [actual code](https://github.com/cytoscape/cytoscape.js/blob/e6541de603f5714f572238573ea06ef17503282b/src/core/viewport.js#L421) expects one argument, an object with `pan` and `zoom` as properties.

**Desired behaviour**

The documentation and the typings should reflect that the functions expects one argument.

**Minimum steps to reproduce**

Compare online documentation with source code.

**Comment by maxkfranz** [comment]
The documentation can be updated here unilaterally.  

The typings are community-supported on DefinitelyTyped.  You can file an issue or make a PR to resolve the typings to your satisfaction here: https://github.com/DefinitelyTyped/DefinitelyTyped
