### ISSUE TITLE
Needless cose calculations when gravity set to zero

### ISSUE THREAD

**Issue by kobajder** [cytoscape/cytoscape.js#2898]
**Environment info**
All OSes, all browsers, and nodejs

**Current (buggy) behaviour**

The `calculateGravityForces` method runs all calculations even when the `options.gravity` is set to `0` (zero). 

**Desired behaviour**

At the `calculateGravityForces` method start, there could be some check as 
```
if (options.gravity === 0) {
  return;
}
```
That would make the cose calculation faster in these cases.

**Minimum steps to reproduce**

1. configure `cose` `gravity` to 0 (zero)
2. prepare some nodes and edges
3. execute `cose`

**Comment by maxkfranz** [comment]
This looks like a great optimisation for that edge case.  I believe that most people using the layout -- or similar FD layouts for that matter -- will need to use a gravity to get a good result, as suggested by the default options.  However, the optimisation would be useful to people who prefer to use no gravity.

If you'd like to make a PR for your proposed optimisation, you're welcome to do that.

**Comment by kobajder** [comment]
@maxkfranz , feel free to do the PR. You will be faster than me as I'm going out of computer for 2 weeks now.

**Comment by mdaj06** [comment]
@maxkfranz  can i have a look at this?

**Comment by maxkfranz** [comment]
Naturally

**Comment by kobajder** [comment]
@mdaj06 , can I ask you if you are working on it?

**Comment by mdaj06** [comment]
@kobajder im not currently working on this

**Comment by kobajder** [comment]
@maxkfranz , I have prepared my local branch with code for this issue, but I can't push it. Do you have a list with allowed contributors?
```
>git push --set-upstream origin kobajder/2898-cose-no-gravity
info: please complete authentication in your browser...
remote: Permission to cytoscape/cytoscape.js.git denied to kobajder.
fatal: unable to access 'https://github.com/cytoscape/cytoscape.js.git/': The requested URL returned error: 403
```
Please note, the authentication in my browser was successful

**Comment by maxkfranz** [comment]
We have instructions for contributing here: https://github.com/cytoscape/cytoscape.js/blob/unstable/.github/CONTRIBUTING.md

There's also a blog post that guides you through the process of making GitHub pull request contributions: https://blog.js.cytoscape.org/2017/06/13/contributing/
