### ISSUE TITLE
List extension : cytoscape-dom-node

### ISSUE THREAD

**Issue by mwri** [cytoscape/cytoscape.js#2899]
https://github.com/mwri/cytoscape-dom-node

This extension lets you set DOM elements as nodes. When enabled providing the DOM element by setting the dom node data will cause the DOM element to be rendered on top of the node, and the node will be set to the size of the DOM element.

[Demo (codepen abWdVOG)](https://codepen.io/mwri/pen/abWdVOG)

**Comment by mwri** [comment]
There is also this, not an extension, but the sort of thing you have listed under utility packages:

[https://github.com/mwri/cytoscape-react](https://github.com/mwri/cytoscape-react)

Allows you to make Cytoscape nodes into React Components.

[Demo (codepen WNjoerd)](https://codepen.io/mwri/pen/WNjoerd)
[Demo (codepen qBmbVPg)](https://codepen.io/mwri/pen/qBmbVPg)

**Comment by maxkfranz** [comment]
Added to the docs.  Thanks

It will be visible on the public docs site in the next release
