### ISSUE TITLE
Automatic caching of last layout run

### ISSUE THREAD

**Issue by smarek** [cytoscape/cytoscape.js#2907]
**Description of new feature**

Cytoscape could, if configured so, cache positions of nodes from last layout run in user browser and display the nodes at last-cache positions if available at first, optionally run layout and cache new nodes positions only when forced to do so or when not all nodes already have cached positions

**Motivation for new feature**

I suggest this as part of core library, even though I know it's possible to achieve the same via extension, because running the layout for larger graphs in user browser (starting on nodes count from 50 to 250 depending on chosen layout) gets more expensive with the graph size.

The primary motivation is to achieve very fast rendering once the layout is run once, because in large amount of use-cases (such as presenting graph of static graph data) the data-set does not change drastically or even at all. Being able to turn on the positions caching by simple option (or two) would be great to faster gain more community members (and possibly contributors)

---

If you decide this is not a matter of core ilbrary and should be handled by extension, I'd be glad for update to docs mentioning the possible performance enhancement through caching the positions and before running the desired layout using the `preset` layout to display nodes at last known positions

**Comment by maxkfranz** [comment]
There are a lot of different ways this could potentially work, and it's pretty easy to carry them out with the existing API.

If you're looking to do a collaboration on this topic, I'd suggest you reach out to the authors of the undo-redo extension: https://github.com/iVis-at-Bilkent/cytoscape.js-undo-redo

If you have some ideas for improvements w.r.t. layouts in that extension, I'd be surprised if they weren't open to a pull request.

**Comment by smarek** [comment]
@maxkfranz thank you for your response, is undo-redo the correct way to approach layout caching?
I'm kind of lost here, and I'd appreciate some example of "how to carry it out with existing API", if you'd be so kind

**Comment by smarek** [comment]
I've actually came up with some solution, for anybody who'd need this, snippet uses jquery and localStorage as cache storage

```
    const STORAGE_POSITIONS = 'cytoscape-cache';
    function cachePositions() {
        let positionsData = {};
        $.each(cy.nodes().positions(), function (key, e) {
            positionsData[e.id()] = e.position();
        })
        window.localStorage.setItem(STORAGE_POSITIONS, JSON.stringify(positionsData));
    }

    function restorePositions() {
        let positionsData = window.localStorage.getItem(STORAGE_POSITIONS);
        if (positionsData) {
            positionsData = JSON.parse(positionsData);
        }
        if (typeof positionsData === 'object') {
            cy.layout({
                name: 'preset',
                positions: positionsData,
            }).run();
        } else {
            console.error('cached positions are not object');
            console.error(positionsData);
        }
    }

    function render() {
         cy = cytoscape({
            elements: YOUR_ELEMENTS_HERE,
            container: $("#rendercontainer").get(),
            layout: 'preset'
        });
        cy.on('layoutstop', cachePositions);
        cy.on('position', cachePositions);
    }

    $(function () {
        render();
        restorePositions();
        // run render layout with delay, so the preset gets rendered
        setTimeout(() => { cy.layout(ciseLayout).run(); }, 500);
    })
