### ISSUE TITLE
How to merge the edited KEGG pathways in cytoscape.

### ISSUE THREAD

**Issue by Poovizh** [cytoscape/cytoscape.js#2912]
**I Have learnt to import KEGG pathways to cytoscape and merge the pathways without any edits. but I want to differentiate the nodes of each pathways with different colour to understand the pathways of particular gene or molecule. when I try to merge pathways after editing, only the source data is getting merged not the edited one. could someone please guide me with tips to merging the edited pathways in cytoscape. **

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

**Motivation for new feature**

_Describe your use case for this new feature._

**Comment by maxkfranz** [comment]
If you're looking for Cytoscape 3 desktop support, I think they're using Biostars: https://cytoscape.org/documentation_users.html
