### ISSUE TITLE
node shape rotation style 

### ISSUE THREAD

**Issue by leolumicrosoft** [cytoscape/cytoscape.js#2913]
I have developed this feature for my own project that uses cytoscape.js. I want to use it to draw oil and gas PID diagram so shape rotating is very important. I realize that the feature is almost in the current release. There is a getZeroRotation in drawing-elements though right now it is always returning 0. I have developed code to read a new style property "shape-rotation" and I also enhanced the code (1 correct edge start and end point, 2 overlay shape, 3 mouse pointer in check, 4 label position), like the screenshot below.
Are you still interested in adding new feature in this repository? I can submit a pull request if it is proper. Right now I only did it for polygon shape as that is the only needed shape type in my demand. 

![image](https://user-images.githubusercontent.com/68049677/130325235-2d05b565-ae78-4f7b-8304-8104c8b14f5c.png)

**Comment by maxkfranz** [comment]
This sounds like an interesting feature.  As you suggested, a PR would be a good first step to assess how it would be included in the library.

Looking forward to seeing your PR
