### ISSUE TITLE
Use of Cytoscape.js at https://zubirsaid.sg

### ISSUE THREAD

**Issue by chriskhoosg** [cytoscape/cytoscape.js#2915]
Cytoscape.js is used as a knowledge graph visualization interface to a digital archive collection.
Zubir Said Knowledge Graph: [https://zubirsaid.sg]

Institution: Wee Kim Wee School of Communication & Information, Nanyang Technological University (Singapore)

**Comment by maxkfranz** [comment]
Added, thanks
