### ISSUE TITLE
Allow intrinsic sizing

### ISSUE THREAD

**Issue by oliviercailloux** [cytoscape/cytoscape.js#2940]
**Description of new feature**

I [would like](https://stackoverflow.com/q/69597927/) to invert the logic described in the manual by first rendering the graph, then allowing the container to occupy exactly the height and width required to display the graph. In other words, I’d like the container to be sized according to the natural size of the graph it contains, following the [intrinsic](https://developer.mozilla.org/en-US/docs/Glossary/Intrinsic_Size) sizing strategy. 

I define the natural size of a graph as the size it takes (considering the visible elements only) at zoom factor 1 after being [layed out](https://js.cytoscape.org/#cy.layout). (This definition does not make sense when using layout algorithms that depend on the available size, such as the `random` layout, but I think that many other layout algorithms, such as `breadthfirst`, do not incur such dependency.)

The feature request is to support officially a “let the container size itself automatically” approach, similar to what happens generally to a component when no CSS size is explicitly set.

I’d also suggest that the “intrinsic sizing” strategy could be described in the user manual with an advice of [disabling zooming](https://js.cytoscape.org/#cy.zoomingEnabled), and insisting that it is especially important to use some logic to make sure only a reasonably small part of the graph is visible at any point of time (which is, anyway, the recommended strategy, for very reasonable reasons), so that the “natural size” is kept small enough.

If this is supported, perhaps changing the doc would be useful as it seems currently difficult to find out how to do this(at least, I couldn’t).

**Motivation for new feature**

It seems that this approach is not currently officially supported in Cytoscape.js, or perhaps even not recommended. The author of [this answer](https://stackoverflow.com/a/54480078/) to a similar question seems to consider this a bad idea, for example. This may be true in some cases, but the intrinsic sizing approach seems very natural and reasonable to me, and it certainly is a very common choice when sizing general elements in a web page (one does not generally manually fix the height of a paragraph of text, for example).

**Related question**

If not supported officially, can I implement this myself, perhaps by getting programmatically the [rendered bounding box](https://stackoverflow.com/a/42375987/) and using it to programmatically size the container? Do you see some possible problems that this would entail? Should I call `resize` after doing this (considering that I use a layout that does not depend on the available size, is this unnecessary)?

Thank you for any thought or for considering this feature.

**Comment by maxkfranz** [comment]
I think there are a lot of points to consider in the two strategies, and they deserve more focus than the documentation page could or should provide.  You’re welcome to post your discoveries here re. the pros and cons of each strategy, or perhaps you’d be open to writing a more in-depth blog post on the topic (similar to the layouts post <https://blog.js.cytoscape.org/2020/05/11/layouts/>).  I’m certainly open to the idea of publishing guest posts on the blog, and that post could be linked from the documentation.

**Comment by oliviercailloux** [comment]
I appreciate your open mind set. But TBH I don’t (at least, currently) intend to think about this problem in very general terms (that is, beyond my specific use case); and I wouldn’t feel legitimate writing about it without some more experience than I am (currently) willing to acquire. Plus, I am currently experimenting with [d3-dag](https://github.com/erikbrinkman/d3-dag) (I like that I can draw SVG graphs with this, even though it requires more code than cytoscape).

Thanks for your attention anyway.
