### ISSUE TITLE
Assistance with React Wrapper Development

### ISSUE THREAD

**Issue by baughmann** [cytoscape/cytoscape.js#2941]
**Description of new feature**

I am working on adding the ability for React canvas components (currently using `konva-react`) to be used to render content for a node on top of it.

**Motivation for new feature**

Allowing user to have more complex nodes while maintaining performance

**Request Details**

Basically, I am able to utilize Cytoscape's event listeners to update a separate canvas and keep it and cytoscape "in sync". While this is useful in and of itself, since it's not within Cytoscape's wrapper div (and also, probably because it's not a "known" canvas), users are unable to make use of many built-in and third party extensions. For example:, the output`cy.png()` will not include the content for custom nodes, and third-party extensions such as `cytoscape.js-navigator` will not show a preview that includes the custom nodes.

What I'm asking for is help to figure out where to start looking to add a custom canvas to Cytoscape that can take advantage of all the useful goodies that this library and it's extensions provide.

Thank you in advance for your help, and thank you for maintaining such a wonderful library.

**Comment by maxkfranz** [comment]
We do not expose any rendering technology details to the consumer.  The API is technology-agnostic, and the selection of rendering technology may change in future.  It has already happened once before.

What you describe is best served by extensions.  Take a look at the existing extensions and the extensions API: https://js.cytoscape.org/#extensions <https://js.cytoscape.org/#extensions>

There are opportunities for you to collaborate with existing extension authors in the community or to contribute novel extensions of your own.  If you decide to create new extensions, you are welcome to post them here to have them listed in the official documentation.

**Comment by baughmann** [comment]
@maxkfranz Yep, makes sense. I dived in a bit and made something that worked fairly well without interacting with the canvas. We can close this for now, and I will re-open it and post a gist or lib before closing it again.
