### ISSUE TITLE
Node boundingBox is greater than the provided data by 1 px on each side

### ISSUE THREAD

**Issue by AleksandrSl** [cytoscape/cytoscape.js#2942]
**Environment info**

- Cytoscape.js version : 3.19.1
- Browser/Node.js & version : v14.16.1

**Current (buggy) behaviour**

The bounding box differs from provided data by 1 px on each side

**Desired behaviour**

The bounding box matches provided data

**Minimum steps to reproduce**

```
let cy = cytoscape({
  styleEnabled: true,
  elements: [
    {
      data: { id: '123' },
      position: {
        x: 30,
        y: 30
      },
      style: {
        'width': 20,
        'height': 20,
        'border-width': 0,
        'padding': 0
      }
    }
  ],
  layout: { name: 'preset' }
})
console.debug(
  cy
    .nodes()
    .map(node => [node.id(), node.boundingBox({})])
)
```

prints
```
[ [ '123', { x1: 19, y1: 19, x2: 41, y2: 41, w: 22, h: 22 } ] ]
```

Maybe I miss some other padding that I must remove?

**Comment by maxkfranz** [comment]
Antialiasing, variable screen densities, browser variabilities, etc. result in the requirement of +1.  Otherwise, you’ll randomly chop things off, and that’s never good

**Comment by AleksandrSl** [comment]
Yeap, seen this comment in source code, but I thought it should affect only `renderedBoundingBox`, but `boundingBox` should be of the actual size without corrections for rendering?

**Comment by maxkfranz** [comment]
There are currently only model coordinates and rendered (on-screen) coordinates — and corresponding functions for each.  They are different coordinate spaces, though the conversion between them is simple.  See https://js.cytoscape.org/#notation/position <https://js.cytoscape.org/#notation/position>

If you’d like to propose a new, separate set of functions, which only the renderer would use, you’re welcome to propose the details further in a PR
