### ISSUE TITLE
concentric layout: controlling node level from ipycytoscape

### ISSUE THREAD

**Issue by shadiakiki1986** [cytoscape/cytoscape.js#2945]
**Current (buggy) behaviour**

concentric layout: node levels are controlled from a javascript function through argument named "concentric"
(docs at: https://js.cytoscape.org/#layouts/concentric )

**Desired behaviour**

This default function would check for a field in node `data` first, in case it is set from ipycytoscape, before falling back to using node degrees. `ipycytoscape` cannot send a javascript function to the front-end since `ipywidgets/traitlets` json-serializes all data sent to the front-end.

**Minimum steps to reproduce**

Check issue in ipycytoscape: https://github.com/cytoscape/ipycytoscape/issues/238#issuecomment-962251735

**Comment by maxkfranz** [comment]
This sounds like an ipycytoscape issue.  Have you tried posting your issue there?

**Comment by shadiakiki1986** [comment]
Yes but it's not possible to fix it there because AFAIK ipywidgets doesn't
support sending a javascript function to the front-end.
OTOH it supports sending a string. So the ipycytoscape issue would be fixed
if cytoscape concentric's default function checked a key "concentric" in
the data field before falling back to the degree function.

**Comment by maxkfranz** [comment]
Sounds like ipycytoscape should be converting this potential string option to a function on their JS/TS side.  Have you posted your issue with ipycytoscape?

**Comment by shadiakiki1986** [comment]
It could be fixed on ipycytoscape's side in a complex way, or it could be fixed here in cytoscape.js with 2 lines of code.
The above PR #2951 does the job.

**Comment by joshwatt22** [comment]
Was this issue ever fixed? I am facing the same problems.
