### ISSUE TITLE
Will the CSS `filter` property ever be supported as a styling option?

### ISSUE THREAD

**Issue by shasaur** [cytoscape/cytoscape.js#2946]
**Description of new feature**

I'm referring to this [CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/filter).

Example:
```
filter: hue-rotate(90deg);
```

This can allow users to apply colour effects on top of nodes. 

**Motivation for new feature**

This would make it really nice and easy for programatically adjusting the colour of nodes, eg from green to red. (at the moment I have to essentially manually interpolate R and G colour values to get a change from red to green like in [my video here](https://twitter.com/HeardOfTheStory/status/1457720006582718468)).

This would also mean that if you had images on nodes (which I would also hope to do at some point (not sure on whether that's currently possible / planned)), it would become possible to phase them from one colour to the next programmatically.

**Comment by maxkfranz** [comment]
It sounds like you’re well on your way to completing a feature proposal.  As a next step, we’d need a more detailed specification of what the property modifies and how (both nodes and edges, just node bodies, also including images, etc.).
