### ISSUE TITLE
Style selector on array field with index

### ISSUE THREAD

**Issue by zirkelc** [cytoscape/cytoscape.js#2948]
I'm retrieving my nodes and edges from the graph database Neo4j and this supports multiple labels per node. That means my data contains a field `labels`. I would like to apply certain styles based on a selector for the first label

```
{
  selector: `node[labels.0 = '${label}']`,
  style: { }
} 
```

This actually does seem to work, but I still get a warning in the console:
![image](https://user-images.githubusercontent.com/950244/141487879-e757739e-2e39-4c49-b713-ab0743c40238.png)

I'm also using the notation `labels.0` to read data from the node and it works fine.

**Environment info**

- Cytoscape.js version :    
"cytoscape": "^3.18.0",
"react-cytoscapejs": "^1.2.1",
- Browser/Node.js & version :
 Chrome: Version 95.0.4638.54 (Official Build) (x86_64)

**Comment by maxkfranz** [comment]
I don’t recall any array support, and I don’t see it mentioned in the docs.  It looks like you may be relying on undefined behaviour

You’re welcome to put up a pull request if you’d like explicit selector support for array indices.  That should include unit tests and a consideration of different type scenarios (0 v.s. “0”, array v.s. object, etc.)

See https://github.com/cytoscape/cytoscape.js/blob/845be4bd9b9a738719960bf6541baf9fa0e26ea2/test/selectors.js <https://github.com/cytoscape/cytoscape.js/blob/845be4bd9b9a738719960bf6541baf9fa0e26ea2/test/selectors.js>

**Comment by zirkelc** [comment]
Okay, I will try to come up with a PR in the next few days!
