### ISSUE TITLE
Graph is being crashed when fails to upload a node background image

### ISSUE THREAD

**Issue by Alexandr23** [cytoscape/cytoscape.js#2949]
**Current (buggy) behaviour**

Graph is being crashed when fails to upload a node background image. It fails with `Uncaught DOMException: Failed to execute 'drawImage' on 'OffscreenCanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.`

**Desired behaviour**

A background image is just not displayed, if not loaded properly. Ideally we should retry to upload it on next update/render.

**Minimum steps to reproduce**

It happens often if browser can't load an image. Easiest way to reproduce is to fake an image url, e.g. http://non-existing-image/fake.svg and re-draw a graph few times.

From what I understood after debugging the source code, it relies on `image.complete` which is always `true` after we create an object with `const image = new Image();` Could happen because `src` is not defined in the begining:

```
  var drawImages = function drawImages() {
    var nodeOpacity = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : eleOpacity;
    var inside = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : true;
    var prevBging = _p.backgrounding;
    var totalCompleted = 0;

    for (var _i = 0; _i < image.length; _i++) {
      var bgContainment = node.cy().style().getIndexedStyle(node, 'background-image-containment', 'value', _i);

      if (inside && bgContainment === 'over' || !inside && bgContainment === 'inside') {
        totalCompleted++;
        continue;
      }

      if (urlDefined[_i] && image[_i].complete && !image[_i].error) {
        totalCompleted++;
        r.drawInscribedImage(context, image[_i], node, _i, nodeOpacity);
      }
    }

    _p.backgrounding = !(totalCompleted === numImages);

    if (prevBging !== _p.backgrounding) {
      // update style b/c :backgrounding state changed
      node.updateStyle(false);
    }
  };
```

That leads to a situation that it draws an image when `image.complete` is `true` and `image.error` is not yet `true` (event is not fired yet).

Possibly only applicable for `"background-image-containment": "over"`.

**Posible solution**

We can use `image.addEventListener('load', () => image.loaded = true);` to set `loaded` flag and rely on it instead of `complete`.

**Environment info**

- Cytoscape.js version : 3.19.0
- Browser/Node.js & version : Chrome 95.0.4638.69 (Official Build) (x86_64)

**Comment by maxkfranz** [comment]
Other loading mechanisms were used in the past, including onLoad I believe.  If you have a more robust solution than the current one, you’re welcome to make a pull request for your proposed change

Images can also load, but their dimensions aren’t reported correctly by some browsers for some images.  Lots of things to consider
