### ISSUE TITLE
Not able to generate network diagram if source and target of edge is not present in node

### ISSUE THREAD

**Issue by nikhil12362** [cytoscape/cytoscape.js#2950]
Not able to generate network diagram if source and target of edge is not present in node.

**Comment by jerryIsHere** [comment]
try this
let say the triple is an object in format `{"h_name":"E commerce","r_name":"Has Subtopic","r_value":true,"t_name":"Blockchain"}`
You can test the existence of the head and tail entity and add them in the graph if needed as follow
`triples.forEach(triple => {
                                [triple.h_name, triple.t_name].forEach(name => {
                                    if (cy.getElementById(name).length == 0) {
                                        cy.add(nodeFactory(name))
                                    }
                                })
                                cy.add(workspaceEdgeFactory(triple))
                            })`
