### ISSUE TITLE
Problem with license of cytoscape-klay

### ISSUE THREAD

**Issue by pedroafsouza** [cytoscape/cytoscape.js#2953]
The current layout organizer **cytoscape-klay** uses an internal dependency for a package called klayjs which is under the license of EPL-1.0. This creates a legal issue by commercial software using the layout organizer cytoscape-klay, companies that wish to use this software might be required to publish the code of the component that they are releasing. 

I believe the layout organizer is going against the idea explained on the factsheet documentation:

_Used in commercial projects and open-source projects in production

Actual behavior:
- Commercial software can't use klay-layout.

Expected behavior:
- Commercial software should be able to use klay layout.

**Comment by maxkfranz** [comment]
The Cytoscape.js community accepts related libraries and extensions from a diverse set of contributors -- and third-party contributors and the authors of third-party libraries have the right to choose their preferred license for their work, just as you have the right to choose your preferred licenses in your work.

The code of first-party extensions themselves are MIT, as is the main library.  Separate libraries, like Klay may have different licenses.  As always, developers ought to do their due diligence in evaluating potential dependencies.

If you have questions or requests for the authors of Klay itself, you should reach out to the authors of Klay: https://github.com/kieler/klayjs

If you'd like to make licensing of particular extension dependencies clearer, you're welcome to open up pull requests in the corresponding repos. 

Best of luck with your project
