### ISSUE TITLE
Allow overriding existing functions

### ISSUE THREAD

**Issue by sashokbg** [cytoscape/cytoscape.js#2954]
**Description of new feature**
It would be useful to be able to override existing core and collection functions like neighbors and others.

**Motivation for new feature**
There are cases where a plugin might want to change the way some of the base functions work. For example it will be very convenient to change how neighbors are calculated for the expand-collapse plugin. This plugin removes edges and nodes from the graph and puts them in a separate space where they are not visible to the base traversal functions like predecessors, neighbors etc.

**Comment by maxkfranz** [comment]
It's important that we consider compatibility.  Changing basic traversal functions may create conflicts or unexpected, surprising behaviour.  It would also make managing dependencies more complex.

Would it be possible for extensions to create their own functions under their own objects, if needed?
