### ISSUE TITLE
Implement CSS Rules Specificity

### ISSUE THREAD

**Issue by sashokbg** [cytoscape/cytoscape.js#2955]
**Description of new feature**
It would be very useful to implement proper CSS specificity as described here:
https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

**Motivation for new feature**
When visual representation is important and the number of CSS styles and classes grow it becomes very difficult to properly order everything.
This is especially true when working with classes that are added / removed on the fly (ex: on hover or on click).

Implementing CSS specificity will allow us to easily implement more complex styling scenarios without having to do patch-up work with the styles definitions.

PS: Specificity can allow us to also have the "!important" selector

**Comment by maxkfranz** [comment]
On the other hand, we also need to balance things like ease of use.  Most beginners have trouble with CSS specificity

Additional complexity in the styles may also affect performance

A lot of angles to consider
