### ISSUE TITLE
Chrome crashes on font-family

### ISSUE THREAD

**Issue by matusfaro** [cytoscape/cytoscape.js#2958]
Most likely duplicate of https://github.com/cytoscape/cytoscape.js/issues/2249

**Environment info**
- Cytoscape.js version : Both 3.20.0 and 3.7.2
- Browser/Node.js & version : Mac Chrome 96, Node 14.15.1

Working fine on Firefox on Mac

**Current (buggy) behaviour**
Chrome browser crash
<img width="604" alt="image" src="https://user-images.githubusercontent.com/4206738/144707045-a7386e9f-412a-451f-8056-50aafefc550a.png">

**Desired behaviour**
Not to crash Chrome

**Minimum steps to reproduce**

Setting `stylesheet.style.font-family` and opening in Chrome 96 on Mac

You can see it live on my site (before I deploy a workaround) at: https://clearflask.com/product/analyze
Code that causes the issue: https://github.com/clearflask/clearflask/blob/1.5.0/clearflask-frontend/src/common/config/settings/injects/WorkflowPreviewInternal.tsx#L141

**Comment by maxkfranz** [comment]
Browsers get bugs.  Let's leave this open for other people to reference, and it would be great for you to cross-reference your bug report (or another existing report) from Chromium's issue tracker.

**Comment by matusfaro** [comment]
> @matusfaro, do you have a link to the corresponding bug in the Chromium issue tracker? Has this been fixed by Chromium yet?

I didn't investigate this further, I simply omitted the `font-family`, sorry.
