### ISSUE TITLE
Allow custom styles to invalidate nodes' cache

### ISSUE THREAD

**Issue by arthabus** [cytoscape/cytoscape.js#2964]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

Allow custom style attributes to invalidate cached nodes

**Motivation for new feature**

_Describe your use case for this new feature._

I'm creating a custom renderer that extends `CanvasRenderer` which outputs additional graphics on the nodes depending on style attributes stored in `elem.data()`

Unless I miss something, currently `cytoscape` uses cached nodes that are recalculated only if one of the predefined style properties are changed. So if I add a custom graphics it can randomly either appear on all nodes at once or to not appear at all, depending on which node was cached first.

To overcome that I ended up redefining the source code of `cytoscape` which now triggers an event when `nodeKey` is changed and update the final value of the `nodeKey` as needed in the listener in my application.

That works fine for my use case but I'd love to not mess up with the source code as it makes it hard to upgrade `cytoscape` when a new version comes out.

Here is an example of my workaround:

in src/style/apply.js:

```
styfn.updateStyleHints = function(ele){
...
//right before the last return I've added the below code:
  ele.cy().trigger("nodeKeyChanged", {ele, nodeKey: _p.nodeKey, callback: (nodeKey) => {
      if(nodeKey) {_p.nodeKey = nodeKey;}
  }});
}
```

In my application I listen for the `nodeKeyChanged` event and update `nodeKey` based on my style attributes:

```
		this.cy.on('nodeKeyChanged', (event, {ele, nodeKey, callback}) =>{
			let {customStyle} = ele.data()
                         //update `nodeKey` here as needed

			nodeKey = "" + nodeKey //in my case I force cast to string as the int value approaches max int at this stage
			nodeKey = nodeKey + '_' + hash(customStyle) //then I calculate hash for my style and add the hash to the nodeKey
			callback(nodeKey) // and finally return the updated nodeKey back to the `updateStyleHints` function
		})
```

**Comment by maxkfranz** [comment]
> I'm creating a custom renderer that extends CanvasRenderer which outputs additional graphics on the nodes depending on style attributes stored in elem.data()

I don't think that the canvas renderer was intended to be extended.  Changes in style proper (i.e. w.r.t. the stylesheet) should ensure that nodes are correctly rendered.

If you have general styles that you'd like to have in the library that may be useful to others as well, you're welcome to create a PR that would support those features in a generalised way
