### ISSUE TITLE
Gradient direction for edges

### ISSUE THREAD

**Issue by ethan-keller** [cytoscape/cytoscape.js#2969]
**Description of new feature**
Could a gradient direction option be added for edge line gradients?

For now, nodes can have this style set to a custom value: 
`background-gradient-direction: [to-bottom | to-left | ... ]`

Unfortunately there is no equivalent for edge lines. It would be nice to have:
`line-gradient-direction:  [to-bottom | to-left | ... ]`

I can only manage to get this kind of gradient:
![image](https://user-images.githubusercontent.com/57445943/149162226-eaf0e652-835f-4c0a-aa52-60e7afe68206.png)

But I need the direction of the gradient to be different. Like this (apologies for the inconsistent colors):
![image](https://user-images.githubusercontent.com/57445943/149162929-c3e55dc2-573a-49ec-8dbd-6ba7f0c52470.png)

**Motivation for new feature**
Allows the user to control edge line gradient directions.

Thanks
Ethan

**Comment by maxkfranz** [comment]
(1)
>  ![image](https://user-images.githubusercontent.com/57445943/149162226-eaf0e652-835f-4c0a-aa52-60e7afe68206.png)

(2)
> ![image](https://user-images.githubusercontent.com/57445943/149162929-c3e55dc2-573a-49ec-8dbd-6ba7f0c52470.png)

I think that the current direction is based on the source-target angle.  That approach works perfectly on straight edges, and it works fairly well on other edge types (e.g. curved edges).  That is in line with your example (1).

Would (2) work with other edge types, like curved edges or multiline edges?

You're welcome to start off a PR for your feature.  If there are limitations for some cases, like (2), then they should be noted in the PR's accompanying changes to the documentation.
