### ISSUE TITLE
Firefox Endless Zoom

### ISSUE THREAD

**Issue by sashokbg** [cytoscape/cytoscape.js#2973]
**Environment info**

- Cytoscape.js version : 3.20.0
- Browser : firefox 95.0.1
- Nodejs: v14.18.0

**Current (buggy) behavior**
Endless zoom-out when trying to animate a "fit" action:

chart.animate({
        fit: {
          padding: 500,
          eles: chart.$('#Epic-EP1'),
        },
      });

**Desired behaviour**

Zoom and fit the viewport on the selected element.

**Minimum steps to reproduce**
1) Open firefox
2) Go to https://cytoscape.org/cytoscape.js-automove/
3) Open console and type:
```
cy.animate({
        fit: {
          padding: 500,
          eles: cy.$('#a'),
        },
      });
```

**Comment by maxkfranz** [comment]
It looks like it's doing exactly what you've specified

**Comment by sashokbg** [comment]
@maxkfranz I think I am missing something. Is it the padding that is too big or it does some sort of looping ?

**Comment by maxkfranz** [comment]
It just looks really zoomed out to me
