### ISSUE TITLE
Replace Travis CI with GitHub Actions?

### ISSUE THREAD

**Issue by mbrukman** [cytoscape/cytoscape.js#2981]
The current `README.md` is still referencing Travis CI build status:

https://github.com/cytoscape/cytoscape.js/blob/fff9475bad089560f49b593bd5df6d75ec2afbbe/README.md#L16-L17

but looking at the URL it points to (https://travis-ci.org/github/cytoscape/cytoscape.js), it seems that Travis CI hasn't run on this repo in over 8 months, and there's a message at the top:

> Since June 15th, 2021, the building on `travis-ci.org` is ceased. Please use `travis-ci.com` from now on.

Looking at the `travis-ci.com` equivalent URL (https://app.travis-ci.com/github/cytoscape/cytoscape.js), it looks like this repository hasn't been enabled to work with Travis CI.

**Thus, it appears that no CI has been running on Cytoscape pull requests in the past 8+ months.**

That said, given the [Travis CI changes for open-source projects](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) which have a quota and require regular application for re-enablement, it may be time to move to an alternative solution.

GitHub provides a CI product — [GitHub Actions](https://github.com/features/actions) — which I've moved all of my projects to, and it is free for open-source.

I'm happy to help you migrate from Travis CI to GitHub Actions if you'd like, but wanted to see if you're interested in this, or if you're planning to adopt a different CI solution entirely before spending time working on this.

FWIW, I'm not affiliated with GitHub.

**Comment by maxkfranz** [comment]
I think it would be great to use GH actions
