### ISSUE TITLE
Big canvas breaks saving to image

### ISSUE THREAD

**Issue by arthabus** [cytoscape/cytoscape.js#2992]
**Environment info**

- Cytoscape.js version : 3.21.1
- Browser/Node.js & version : Chrome 98.0.4758.80

**Current (buggy) behaviour**

When graph is big enough (in regards to it's demension), calling `cy.png(opts)` always fails with the following error:

    Error: `canvas.toBlob()` sent a null value in its callback

Example call:

```
   await  this.cy.png({
        output: 'blob-promise',
        bg: 'white',
        full: true,
    })

```

**Desired behaviour**

Cytoscape correctly returns an image with `cy.png()` despite of the dimensions of the graph.

**Minimum steps to reproduce**

- Add two nodes far apart from each other to produce big enough canvas
- call  this.cy.png()
- Observe the error
- If no error is produced, put the nodes further apart from each others and repeat the steps

Example fiddle:
https://jsfiddle.net/atgbqdwx/

**Comment by maxkfranz** [comment]
> Cytoscape correctly returns an image with cy.png() despite of the dimensions of the graph.

That's a great idea.  Do you have a proposal for how to avoid the current browser limitations?

**Comment by arthabus** [comment]
@maxkfranz I was thinking of rendering the graph in tiles but then the problem is that you would still need to merge them somehow together to produce the final image which would again exceed the limitations of the canvas - not sure if there is a solution to that.

Another approach I was thinking about is to check during the render if the final image fits the max canvas size and if it's not, to scale it down accordingly.

What do you think about those?

**Comment by maxkfranz** [comment]
> @maxkfranz I was thinking of rendering the graph in tiles but then the problem is that you would still need to merge them somehow together to produce the final image which would again exceed the limitations of the canvas - not sure if there is a solution to that.

That may work if there's a way to put the bytes of each tile into something like a typed array -- and then export the total bytes as a file.  In any case, this could be expensive and complex.

> 
> Another approach I was thinking about is to check during the render if the final image fits the max canvas size and if it's not, to scale it down accordingly.
> 
> What do you think about those?

That sounds like a tractable option.  

It's surprising behaviour if the returned image does not match the developer-provided spec.  What do you think about incorporating warning messages when your suggested adjustment is applied?  

You could either do (1) a search (e.g. binary search) to find the maximum size supported for the user's current browser, or you could use (2) a hard-coded size that is well supported across browsers (i.e. lowest common denominator).  (1) is more flexible for varying browsers and browsers that change over time, and (2) is cheaper and simpler.  What do you think?

**Comment by arthabus** [comment]
Maybe then to provide an option that will enable this "down-scaling" behavior? So by default it will fail if image is too big, but if the option is enabled, only then to scale it down when needed.

Something like this

```
await  this.cy.png({
        output: 'blob-promise',
        bg: 'white',
        scaleDownIfTooBig: true, //or maybe to accept a callback that should return true or false. in this case the developer will be notified about the possible upcoming scaling and perform any additional operations, like notifying user about quality loss or whatever
        full: true,
    })
```

**Comment by maxkfranz** [comment]
An option could work.  I suspect it should be true by default.

In any case, I think the dev would benefit from some feedback when the downscaling is necessary (i.e. applied when true, but you still want to know the reason for failure when false).

**Comment by maxkfranz** [comment]
@arthabus, could you put up your proposal in a PR?
