### ISSUE TITLE
CSS style selectors with multiple classes are not parsed correctly.

### ISSUE THREAD

**Issue by mkelly1495** [cytoscape/cytoscape.js#2995]
**Environment info**

- Cytoscape.js version : 3.21.0
- Browser/Node.js & version : Chrome/14.19.0

**Current (buggy) behaviour**

When specifying a style selector such as `node.class1.class2 { ... }` in a css file, cytoscape fails to parse the selector correctly. It actually parses the selector as ['node', 'class1.class2'] instead of ['node', 'class1', 'class2']. This appears to be caused by an incorrect regular expression ```^\\.((?:[\\w-.]|(?:\\\\[\\!\\\"\\#\\$\\%\\&\\'\\(\\)\\*\\+\\,\\.\\/\\:\\;\\<\\=\\>\\?\\@\\[\\]\\^\\`\\{\\|\\}\\~]))+)``` being used to match the class. The correct expression is ```^\\.((?:[\\w-]|(?:\\\\[\\!\\\"\\#\\$\\%\\&\\'\\(\\)\\*\\+\\,\\.\\/\\:\\;\\<\\=\\>\\?\\@\\[\\]\\^\\`\\{\\|\\}\\~]))+)``` (i.e. without the `.` after the `[\\w-` part.

**Desired behaviour**
Ability to specify more than one selector class in the css (e.g. `node.class1.class2`).

**Minimum steps to reproduce**
Create a style sheet file called `my-style.css` that defines a style with more than one class as a selector:
```
node.class1.class2 {
  background-fill: solid;
  background-color: #268dae;
}
```

Create a cytoscape graph that specifies the `style: require('./my-style.css')` property in the config (e.g. `var myGraph = cytoscape({ ..., style: require('./my-style.css'), ... })`.

Observe that the `consumeExpr` function in `src/selector/parse.js` fails to correctly parse the `.class1.class2` as two separate classes. Instead in parses it as a single class and therefore fails to match the style properly when the `match[Type.CLASS]` function (in `src/selector/query-type-match.js` is invoked. The class passed into the `match[Type.CLASS]` function is `.class1.class2` and therefore never matches anything since the `node.classes` property is an array with each class as a separate element.

**Comment by maxkfranz** [comment]
@mkelly1495, can you confirm whether 3.20 is affected?  Are earlier versions affected, e.g. 3.10?

@zirkelc, could this be related to #2952?  Assuming this is a recent issue, this looks like the only recent change to selectors.

**Comment by mkelly1495** [comment]
I will try 3.20.0 tomorrow and let you know. I believe I also tried 3.13.0 and had the same issue though. I'll follow up with you tomorrow.

**Comment by mkelly1495** [comment]
OK - I have confirmed that it doesn't work on 3.20 either. The regex for `tokens.className` appears to be incorrect in this version as well.

**Comment by mkelly1495** [comment]
I submitted a pull request with a fix to this bug. Very simple change actually.

**Comment by zirkelc** [comment]
@maxkfranz #2952 could be related to it, because I added the a`.` (dot) to the `token.variable` regex: https://github.com/cytoscape/cytoscape.js/pull/2952/files#diff-e0a5022675e848862c339f74eb902cf1e43002bbb40f6d53dce97cc82a519261L19

This regex was then reused for the class name `tokens.className = tokens.variable;`. 

However, if 3.20.0 has the same issue then it might have been there already.

In any case, let me know if I can help!

**Comment by maxkfranz** [comment]
@zirkelc, could you give #2997 a quick once-over just to confirm there are no red flags re. your feature?  The tests pass locally for me in @mkelly1495's PR.

Would any other tests make sense beyond what we have now?  We definitely have the main cases.  Any important edge cases to consider?

Since @mkelly1495's new test fails pre-3.21, then this patch will be released for both 3.20 and 3.21

**Comment by zirkelc** [comment]
> @zirkelc, could you give #2997 a quick once-over just to confirm there are no red flags re. your feature? The tests pass locally for me in @mkelly1495's PR.

@maxkfranz it looks good to me. One thing I noticed is that the ID selector regex follows the variable name regex: https://github.com/cytoscape/cytoscape.js/pull/2997/files#diff-e0a5022675e848862c339f74eb902cf1e43002bbb40f6d53dce97cc82a519261R22

```js
tokens.variable = '(?:[\\w-.]|(?:\\\\' + tokens.metaChar + '))+'; // a variable name can have letters, numbers, dashes, and periods
tokens.id = tokens.variable; // an element id (follows variable conventions)
```

That means when I added the `.` to `token.variable` it is now implicitly allowed as ID as well. However, the HTML spec allows for dot-chars within element identifiers. 

Maybe it would make sense to either define a separate regex for `tokens.id` or add a test case for selectors like `#n1.bla` and see if it selects the correct element?

**Comment by mkelly1495** [comment]
I added a test that verifies correct behavior when an element has a period in the `id` name and updated the other tests where necessary.

**Comment by mkelly1495** [comment]
Bump. Why has the pull request not yet been merged?

**Comment by maxkfranz** [comment]
Your PR and issue are being used as an example to help onboard new contributors to Cytoscape.js.  It will be merged in and released once that onboarding has completed -- hopefully some time this week.

Thank you for your patience
