### ISSUE TITLE
Underlay gets clipped on pan and zoom

### ISSUE THREAD

**Issue by gianluca-pepe** [cytoscape/cytoscape.js#2998]
**Environment info**

- Cytoscape.js version : 3.21.0
- Browser/Node.js & version : Firefox 98.0

**Current (buggy) behaviour**

Underlay is clipped when panning or zooming the graph.
It happens on last node on an axis direction: top, bottom, left, right.

**Desired behaviour**

Underlay staying intact during interaction.

**Minimum steps to reproduce**
Just pan (or zoom) the graph around.

[https://output.jsbin.com/lawerelaxi/1](https://output.jsbin.com/lawerelaxi/1)

**Comment by maxkfranz** [comment]
Ref : Add underlay node/edge styles #2928

**Comment by maxkfranz** [comment]
@zakjan, could there be issues with the bounding box and your feature in #2928?

**Comment by zakjan** [comment]
Thanks for the demo, I'll investigate it during next week.
