### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'nodesOverlap')

### ISSUE THREAD

**Issue by ryukyokan** [cytoscape/cytoscape.js#3008]
Hi, i am getting Uncaught TypeError: Cannot read properties of undefined (reading 'nodesOverlap') when my nodesJson and edgesJson is in this configuration:
{ data: { id: '4', shape: 'rectangle', color: 'green'}},{ data: { id: '3', shape: 'rectangle', color: 'green'}},{ data: { id: '2', , shape: 'rectangle', color: 'red'}},{ data: { id: '1', shape: 'rectangle', color: 'cyan'}}
{ data: { id: '3,4', source: '3', target: '4'}},{ data: { id: '2,3', source: '2', target: '3'}},{ data: { id: '1,2', source: '1', target: '2'}}

I did some experiment, if i sort my nodesJson by id in accending order, this error will not occur and the graph will load correctly. Can anyone explain what is causing this behavior and how should i resolve it?

**Comment by maxkfranz** [comment]
Please provide a reproducible test case according to the issue template, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  [A JSBin](http://jsbin.com/fiqugiq) can be forked to easily provide a code sample.

It's important to provide a reproducible demo. Without that, it's not practical to verify that there is indeed a bug in the library -- or whether there is a bug in your app. It's easy and quick to create a demo using JSBin if you do indeed have a reproducible issue.
