### ISSUE TITLE
Public API for retrieving node label width

### ISSUE THREAD

**Issue by mkelly1495** [cytoscape/cytoscape.js#3009]
**Description of new feature**

Currently, there is no documented way of retrieving the label width/height of a node. This information can be retrieved using `node._private.labelBounds.main.w`, but this obviously is not preferable since it breaks encapsulation. There is a method called `outerWidth` that returns the width of the node shape and padding, but this does not include the label width. Either a new method should be added for retrieving label  width, or the `outerWidth` method should be updated to take an optional `includeLabel` boolean parameter that optionally includes the labelWidth when determining the outerWidth of the node.

**Motivation for new feature**

When laying out nodes, it is important to factor in the label width to avoid overlapping nodes.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
What's the use case here?  Are you writing a layout?

**Comment by mkelly1495** [comment]
Correct. I'm writing a DFS based layout algorithm and need to retrieve the node widths (including label). Although, I now see that there is a `node.layoutDimensions()` method which has an option to include label widths. Should I just use this method?

**Comment by maxkfranz** [comment]
That’s probably the way to go

**Comment by mkelly1495** [comment]
Alright - sounds like this is a non-issue then. Thanks for the help
.

**Comment by maxkfranz** [comment]
Great

**Comment by uniquejava** [comment]
Hello, @maxkfranz @mkelly1495  I'd like to set title for some nodes to top left corner(inside node not outside), so I need an API to calculate the text width to do some offset. I noticed we can access `node._private.labelBounds.main.w` but per my experiment it always return null, how can I get it.  Thanks!

There is a [stackoverflow question here ](https://stackoverflow.com/questions/60528108/cytoscape-js-compound-node-label-alignment) mentioned the reason, but there is no direct solution to properly calculate the text width

<img width="525" alt="image" src="https://user-images.githubusercontent.com/1049271/211824229-cd182edb-5534-4e89-9021-e8d3c2400cce.png">
