### ISSUE TITLE
FR: Support for 3D networks/graphs

### ISSUE THREAD

**Issue by Peter-Pasta** [cytoscape/cytoscape.js#3011]
**Description of new feature**

Render networks/graphs in 3D. Similar to this example: http://netwonder.net/ex/

**Motivation for new feature**

Allowing the visualisation of topological properties of graphs (see the brain example in the link above).

**Comment by maxkfranz** [comment]
I don't think that 3D support is currently planned, but you're welcome to use this issue to discuss this idea further.
