### ISSUE TITLE
Suggestion: Add a changelog

### ISSUE THREAD

**Issue by matthias-ccri** [cytoscape/cytoscape.js#3017]
Please consider creating a changelog file or curated release notes or upgrade notes.

Currently the release notes are on the website (https://js.cytoscape.org/#introduction/releases) but they're not "notes", they're just links to GitHub filters for PRs merged in each release (e.g. [3.3.0](https://github.com/cytoscape/cytoscape.js/issues?q=milestone%3A3.3.0+is%3Aclosed))

It's really hard to read through all of those, to determine what a changelog would tell you — namely, what are the breaking changes? Breaking changes are the only thing people care about in changelogs, and secondly when a feature was added (which is a breaking change in reverse).

I don't think it's reasonable to expect people to read through PR descriptions. They are mostly helpful, but it is still a burden. It's just a lot of clicking and a lot of reading. I don't want the maintainers to be burdened, but most other projects have a changelog or at least GitHub Release notes with simple bulleted lists.

Previous requests for this:
- https://github.com/cytoscape/cytoscape.js/issues/801
- https://github.com/cytoscape/cytoscape.js/issues/2757

**Comment by maxkfranz** [comment]
Hi Matthias,

> Breaking changes are the only thing people care about in changelogs

Great.  We follow [semver](https://semver.org).  All packages on npm are supposed to follow that.  If you're not already familiar with semver and how it works with npm, [it's worth reading](https://docs.npmjs.com/about-semantic-versioning).  So, there are no breaking changes unless it's a breaking/major version release.  There's also [an extensive upgrade guide for the only breaking release to date](https://blog.js.cytoscape.org/2017/04/11/3.0.0-release/).

As compared to changelogs, many people today are better served by GitHub's search  (e.g. for finding issues related to particular features and for taking part in the community) or simply upgrading to the latest version of the library.

That being said, some people are used to changelogs.  So, if you'd like to add support for them without increasing the maintenance burden -- as you mentioned -- you're welcome to it.  You could manually contribute them for past and future releases, or maybe you'd like to contribute automation for that process.  

Thanks for your feedback

**Comment by kachkaev** [comment]
+1 for getting the changelog. Semver is semver, but it is not always followed. Even if it is, it is useful to know what features have been added and what bugs have been fixed.

“Are we as a team unblocked now?” – that’s the answers that CHANGELOGs can quickly give.

We use [Renovate bot](https://docs.renovatebot.com/) to update deps in the repo. It conveniently scrapes recent changes from CHANGELOG.md or GitHub releases. When approving PRs with bumps, seeing those is very helpful:

<img width="909" alt="Screenshot 2023-08-18 at 18 04 46" src="https://github.com/cytoscape/cytoscape.js/assets/608862/0674e07f-a0b1-4402-9cc1-0d7a7886911b">

<img width="911" alt="Screenshot 2023-08-18 at 18 05 19" src="https://github.com/cytoscape/cytoscape.js/assets/608862/80ceccc5-3374-4639-8e65-cd390faca068">

<br>
Unfortunately, `cytoscape` PRs don’t show the changes, which has brought me here 😁

<img width="916" alt="Screenshot 2023-08-18 at 18 04 37" src="https://github.com/cytoscape/cytoscape.js/assets/608862/aa295435-bbf0-4f5f-b02a-4e912d0058bc">

**Comment by maxkfranz** [comment]
If you have a tool that can automate the change logs, you’re welcome to post a pull request.  I’m looking forward to seeing it.
