### ISSUE TITLE
Allow creation of 'round-polygon' from shape-polygon-points  

### ISSUE THREAD

**Issue by mkelly1495** [cytoscape/cytoscape.js#3018]
**Description of new feature**

Cytoscapejs already has the ability to create rounded polygons using a set of points (internally). However, the functionality is internal and cannot be utilized for custom shapes. I propose adding the ability to specify `shape: round-polygon` with a list of `shape-polygon-points` (similar to what is used for `polygon`). This will allow shapes that require arcs (e.g. `and`, `or` gate symbols) to be drawn without requiring a ton of points.

**Motivation for new feature**

I would like to be able to have graphs that include `and` and `or` [gate symbols](https://www.elprocus.com/basic-logic-gates-with-truth-tables/). These symbols are fairly simple but require arcs that are not easily created using straight line polygons. This issue would be resolved by having the ability to specify the polygon as round-polygon. Then the shapes could be created with only a few points and wouldn't have any jagged edges.

So essentially, I'm asking for support for `shape: round-polygon` that takes the points specified by a `shape-polygon-points` style property and invokes the `node-shapes.js` `generateRoundPolygon` function with the specified points in order to render the desired shape. Currently this function is invoked internally to support the fixed set of rounded shapes (e.g. `round-diamond`).

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by josejulio** [comment]
> The rounded shapes seem to only support rounded, convex corners (#2496). Your suggested shapes have concave curves, and that seems quite a bit different to me. Maybe @josejulio could chime in re. his rounded shapes feature.

That's correct. The PR only introduce support for the rounded corners. Passing the polygon points to `generateRoundPolygon` will only make the curved corners and that won't be useful for the and/or gates.

Referenced PR gives some reference on the needed pieces:
- Drawing the shape
- Testing if a point is inside the shape
- Testing if a line intersects the shape
- Connecting with the lib
