### ISSUE TITLE
Migrate from modularized lodash

### ISSUE THREAD

**Issue by rhuddleston** [cytoscape/cytoscape.js#3043]
**Description of new feature**

Currently lodash functionality is included as a dependency like this:

    "lodash.debounce": "^4.0.8",
    "lodash.get": "^4.4.2",
    "lodash.set": "^4.3.2",
    "lodash.topath": "^4.5.2"

**Motivation for new feature**

  Those packages are deprecated and have had no updates in 6 years included any related security fixes. Please consider using the main lodash package instead. Here is the lodash developers take on using these packages and advice on how to migrate: https://lodash.com/per-method-packages

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [x] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [x] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [x] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [x] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
Would you put up a PR with the proposed changes?  It would be great to get this into the next release

**Comment by rhuddleston** [comment]
Done see above

**Comment by maxkfranz** [comment]
The tests are OK, and they should be exercising the points where Lodash is used.  I quickly verified that our `dist` builds are roughly the same size with this change.

I suppose this could either be classified as a new feature (upgrades) or a fix (security).  What do you think?

**Comment by rhuddleston** [comment]
I'd probably put it under security

**Comment by maxkfranz** [comment]
OK, released in 3.22.1 & 3.21.3
