### ISSUE TITLE
Add multi-line label support

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#305]
Project idea:  This project would entail the implementation of multiline labels in Cytoscape.js.  This would allow for manual breaking of lines using the newline character (i.e. `\n`), or autobreaking based on some maximum line length.

--

Copied from later in the thread, as this is very important to note:

--

I'm going to note in this ticket, as it should have been mentioned here explicitly before, that the want for multiline labels itself is very likely indicative of design issues:  If you find yourself thinking "Gee, I wish I could wrap these labels", then you should consider that your labels themselves are too long.

Labels are meant to label elements, not to fully describe them.  Long labels are -- more often than not -- bad UI.  They clutter the graph and distract the user from the real content, the visual representation of the graph data.

It's near trivial to clip labels with "..." and show more information elsewhere (e.g. a qtip, a panel, etc.).  This, combined with time constraints and performance considerations, has made me hesitant to implement multiline labels.

**Comment by maxkfranz** [comment]
Implemented via #854 and improved with some refactoring.  Performance could be improved further with #593, but it might not be worthwhile right away given that zooming would invalidate that cache.

Anyway, all those interested please try `unstable`.

**Comment by oreenge** [comment]
Is there a way to enable wrapping for labels which have no whitespace? It doesn't work without whitespaces now http://jsbin.com/qefoxe/edit?html,output.

**Comment by maxkfranz** [comment]
Use `\n`

**Comment by oreenge** [comment]
Your suggestion would be to randomly put `\n`'s in the text even though it may or may not have whitespaces?

**Comment by maxkfranz** [comment]
Text wrapping happens on whitespace.  If you don't have whitespace, you'll need to use newlines.
