### ISSUE TITLE
how to make Preset layout graph fit with the canvas.

### ISSUE THREAD

**Issue by simandi434** [cytoscape/cytoscape.js#3051]
I am using preset and dagre layouts to represent the graph. When I switched to dagre it is adjusting its zoom and node size to fit to the screen. when I coming back to preset I am assigning the previous node positions. Its taking the right position but its taking the node size of dagre layout. How can I adjust the zoom size and node size to fit to the screen in preset mode?

**Comment by iAmmarTahir** [comment]
You can call `cy.fit()` when you're in preset mode. It will fit the graph to the screen.

**Comment by simandi434** [comment]
I am calling it. Its fitting the graph to the screen. But, Node size is not changing. where as, node size is changing in other modes like Dagre, circle, grid etc

**Comment by iAmmarTahir** [comment]
Can you create a CodeSandbox of it?

**Comment by simandi434** [comment]
@iAmmarTahir @maxkfranz 

I have created a stackBlitz for the issue. Below is the URL to access it.

https://stackblitz.com/edit/angular-cytoscape-j27hoc?file=src%2Fapp%2Feditor%2Feditor.component.html,src%2Fapp%2Feditor%2Feditor.component.ts,src%2Fapp%2Feditor%2Feditor.component.css,src%2Fapp%2Fapp.component.css,src%2Fapp%2Fapp.component.html

In the above sample app I have a graph and three layouts Preset, Dagre and Circle. Preset is what user created and Dagre, circle are used for other visualization purpose. 

In my case when user click on Dagre or circle layout. the layout is changing to the respective shape and total graph is fit to the screen and its node sizes are also changing according to the screen and number of nodes. But, in the preset mode node size is not changing according to number of nodes.

Repro steps:
In the preset mode zoom out the grapha nd click preset button again. it will arrange the nodes with zoomed out size. When we do the same with Dagre or circle, It is changing the node size respectively. 

In my case I want Preset mode to be also work as Dagre or Circle. It should fit to the screen and node size should be according to the number of nodes and screen size.

**Comment by iAmmarTahir** [comment]
Cytoscape uses `Grid` layout as the default layout when no layout is defined. You are using your custom logic for the preset layout, which is not working properly if you click multiple times on the `Preset` layout button. I think that's related to logic. Solution to your problem is to just pass `grid` in the HTML rather than `preset` layout. It will fix your code.

**Comment by simandi434** [comment]
@iAmmarTahir I am only changing the rendered position of the node before loading the preset layout. I am not changing any sizes of nodes.

**Comment by iAmmarTahir** [comment]
I hope this fixes your issue: https://stackblitz.com/edit/angular-cytoscape-xmd4du?file=src%2Fapp%2Feditor%2Feditor.component.html,src%2Fapp%2Feditor%2Feditor.component.ts,src%2Fapp%2Feditor%2Feditor.component.css,src%2Fapp%2Fapp.component.css,src%2Fapp%2Fapp.component.html

**Comment by simandi434** [comment]
@iAmmarTahir  The issue is when you zoom out and click on the preset again. The node size is not changing. Its not fitting according to the number of nodes and screen size. But, If you zoom out in Dagre or circle layout and click those buttons again it will fit the nodes size according the number of nodes and screen size.

Repro Steps: 

1. Click the preset mode
2. Zoom out the graph and make nodes size smaller
3. again click on the preset button. the node sizes wont change
4. Click the Hierarchy button
5. Zoom out the graph and make nodes size smaller
6. Again click on the hierarchy button. The nodes size will change according to the number of nodes and screen size

I want Preset to be also work like Hierarchy and circle layout in node sizes.
