### ISSUE TITLE
change the wheelSensitivity after initialization

### ISSUE THREAD

**Issue by zoulay** [cytoscape/cytoscape.js#3052]
Hello , 
Is there a possibility to change the wheelSensitivity option after initialization ?
Thank you in advance

**Comment by iAmmarTahir** [comment]
Hey zoulay, you can use `cy.json()` and provide the properties you want to modify after initialization. In your case, it would something like this: 
`cy.json({ wheelSensitivity: (any value from 0 to 1) })`. 
I hope it will help you :).
