### ISSUE TITLE
Unified configuration of overlayShape and nodeShape

### ISSUE THREAD

**Issue by CoderLeoD** [cytoscape/cytoscape.js#3053]
Keep the type of overlayShape consistent with nodeShape

**Comment by maxkfranz** [comment]
There isn’t enough information here for this issue to be actionable.

Provide sufficient context:  Why are you doing this with the shapes?

You should follow the issue template, because it prompts you to provide sufficient information.

**Comment by maxkfranz** [comment]
See also: #2881
