### ISSUE TITLE
Suport extending .png and .jpg via plugins

### ISSUE THREAD

**Issue by sgratzl** [cytoscape/cytoscape.js#3055]
**Description of new feature**

Hi, I'm developing the cystoscape plugin https://github.com/sgratzl/cytoscape.js-layers. However, there is currently no way to such that the layers added by this plugin are part of the exported chart (i.e. via `.jpg` or `.png`). It would be great if there is a extension mechanism such that I can hook my custom export logic when the cytoscape graph is exported to a file.

**Motivation for new feature**

have a custom plugin which content is also exported when calling `.jpg` or `.png`

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
This looks like a great feature to support directly in your extension.  Your extension can combine the Cytoscape PNG with the layers that you control.

Your extension has the privilege of being able to explicitly expose rendering technologies (e.g. SVG, canvas) in your API, whereas the core library must not expose any underlying rendering technology.
