### ISSUE TITLE
cy.layout({<config>}).run() is not working with cytoscape-d3-force

### ISSUE THREAD

**Issue by atiwari2668** [cytoscape/cytoscape.js#3056]
I am not able to add new node and refresh the graph
cy.add([
<node ifnromation>
])
cy.layout({
						name: 'd3-force',
            animate: true,
            collideRadius: 80,
            fixedAfterDragging: true,
            linkId: function id(d) {
              return d.id;
            },
            linkDistance: 200,
            manyBodyStrength: -300,
            xX : function (d) {
              console.log(d.parent);
              console.log(d.group)
              return 500;
            },
            xStrength: 0.2,
            yY : function (d) {
              if (d.group === 1) {
                return 5
              } else if (d.group === 2) {
                return 300
              }else if (d.group === 3) {
                return 600
              }else if (d.group === 4) {
                return 900
              }
            },
            yStrength : 0.9,
            ready: function(){},
            stop: function(){},
            tick: function (){},
            randomize: false,
            infinite: false,
            run : function (d){
              console.log(d)
            },
            radialX: 0, // sets the x-coordinate of the circle center to the specified number
  radialY: 0, // sets the y-coordinate of the circle center to the specified number
						// some more options here...
					},
).run()

when i run the graph then it does not work. graph removed.
can any one help in this case

**Comment by maxkfranz** [comment]
Please file extension issues with the respective extension: https://github.com/shichuanpo/cytoscape.js-d3-force
