### ISSUE TITLE
Special support for iframes

### ISSUE THREAD

**Issue by hellomusa** [cytoscape/cytoscape.js#3062]
**Environment info**

- Cytoscape.js version : 3.20.2
- Browser/Node.js & version : Chrome 104.0.5112.102 | Node.js 16.15.1

**Current (buggy) behaviour**

Mouse events performed outside of an iFrame containing a Cytoscape graph are not recieved by Cytoscape.

**Desired behaviour**

Mouse events should continue to be received when dragging outside the iFrame. For example, drag/pan originating from the iFrame should work even when the mouse moves outside of the iFrame on any browser.

**Minimum steps to reproduce**

Using Chrome, visit https://jsbin.com/fiqugiq/edit (because the output box is an iFrame)

1. Drag a node / pan the graph outside of the iFrame
*drag/pan is stuck on the edge of the frame*
3. Release drag/pan while outside the iFrame
4. Move mouse back inside the iFrame
*drag/pan continues now*

**Possible solution**
On pointerdown and pointerup, use [setPointerCapture](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture) and [releasePointerCapture](https://developer.mozilla.org/en-US/docs/Web/API/Element/releasePointerCapture) to re-target pointer events to the Cytoscape container.

**Comment by maxkfranz** [comment]
If you have suggestions for adding new features like this (i.e. special iframe support), you're welcome to put up a pull request.

Iframes have always been hacky, and it's doubtful that the browser would allow an iframe to capture outside events for security reasons.  That being said, you're welcome to try and we look forward to reviewing your PR.
