### ISSUE TITLE
Right-click dragging to pan

### ISSUE THREAD

**Issue by Revadike** [cytoscape/cytoscape.js#3063]
**Description of new feature**

So currently, only left click dragging either moves nodes around, or clicks through them and allows you to pan, depending on your nodes setting. I'm suggesting (an option) to make right click dragging always pan around and left click dragging always move nodes around.

**Motivation for new feature**

I have large compound nodes in my graph, so you would always drag them if you want to pan (and have dragging nodes functionality enabled).

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
That sounds like a great idea for an extension.  There are lots of different ways that compounds can be handled by apps, and we don’t want to play favourites in the core library.  App-level compound handling features, like the one you suggest, can be implemented fairly simply on top of the core API.  

So if you’d like to make an extension for your feature to make it more reusable, you’re welcome to post a link to it here.  We’ll add your extension to the list in the documentation once it’s available.

**Comment by Revadike** [comment]
> That sounds like a great idea for an extension. There are lots of different ways that compounds can be handled by apps, and we don’t want to play favourites in the core library. App-level compound handling features, like the one you suggest, can be implemented fairly simply on top of the core API. So if you’d like to make an extension for your feature to make it more reusable, you’re welcome to post a link to it here. We’ll add your extension to the list in the documentation once it’s available.
> […](#)
> On Sep 24, 2022, at 19:59, Revadike ***@***.***> wrote: ﻿ Description of new feature So currently, only left click dragging either moves nodes around, or clicks through them and allows you to pan, depending on your nodes setting. I'm suggesting (an option) to make right click dragging always pan around and left click dragging always move nodes around. Motivation for new feature I have large compound nodes in my graph, so you would always drag them if you want to pan (and have dragging nodes functionality enabled). For reviewers Reviewers should ensure that the following tasks are carried out for incorporated issues: Ensure that the reporter has adequately described their idea. If not, elicit more information about the use case. You should iteratively build a spec together. Ensure that the issue is a good fit for the core library. Some things are best done in extensions (e.g. UI-related features that aren't style-related). Some things are best done by app authors themselves -- instead of in Cytoscape libraries. The issue has been associated with a corresponding milestone. The commits have been incorporated into the unstable branch via pull request. The corresponding pull request is cross-referenced. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Would `cxtdrag` event be suitable to implement right click dragging to pan?

**Comment by maxkfranz** [comment]
Yes, that sounds like a good starting point

**Comment by Revadike** [comment]
> That sounds like a great idea for an extension. There are lots of different ways that compounds can be handled by apps, and we don’t want to play favourites in the core library. App-level compound handling features, like the one you suggest, can be implemented fairly simply on top of the core API. So if you’d like to make an extension for your feature to make it more reusable, you’re welcome to post a link to it here. We’ll add your extension to the list in the documentation once it’s available.


I've been thinking, Right click functionality is pretty much unused by core cytoscape. Don't you think this would be great default behavior for core cytoscape? I'm not sure if an extension would be a good idea for this feature. It's quite a small addition to justify a whole extension, while it would fit great as a toggle in core cytoscape.

**Comment by maxkfranz** [comment]
Right clicking is a general gesture that can be used for many things (e.g. context menus).  The behaviour for right click gestures and right click swiping gestures can vary a lot between applications.  Cytoscape exposes the gesture so apps can use whatever makes sense for the particular use case.

Custom right click behaviour is a great fit for an extension, and several extensions (e.g. cxtmenu) expose custom behaviour in a reusable way.

See also: [Why not add an option for that?](https://neugierig.org/software/blog/2018/07/options.html)
