### ISSUE TITLE
line-cap = 'round' + line-style = 'dashed' problem

### ISSUE THREAD

**Issue by xobjects** [cytoscape/cytoscape.js#3064]
cytoscape 3.23

All the styling via selectors has been working very well.  Nice job developers !

However, I noticed an issue today.  I changed the default line-cap for edges to 'round' and all styles that should be dashed are now solid, therefore, ignoring the line-dash setting.

**Comment by maxkfranz** [comment]
Would you include a demo of your issue, like a JSBin?

There’s a number of fields in the issue template that will help you include all the required information so that your issue can be addressed effectively and efficiently.
