### ISSUE TITLE
Adding the be able to add Icons in conjunction with Labels to give additional context clues for Nodes and Edges.

### ISSUE THREAD

**Issue by fallenreaper** [cytoscape/cytoscape.js#3068]
**Description of new feature**

Edges and Nodes should be able to support Icons in conjunction with Labels

**Motivation for new feature**

Generally a Label describes what the Node or Edge is.   The CSS Handles a lot of the look and feel.  With response to the idea of color limited individuals, adding more than just a background change affords users to get more context as actions or events related to a specific node.  While we can change the shape of a node though, It would mess with people who are used to flow charts as maybe a node is shaped a specific way based on a specific purpose.

When attempting to leverage Unicode characters, it seems to vary slightly based on the language pack and browsers as well as what happens to the character when zooming in or out.  I have multiple instances of a Character switching to the black rectangle because it didnt know how to render itself.

The ability to add Icons from existing SVG files or through existing platforms like boostrap, material, or Ionic would give people a greater breadth of things they can accomplish.

While there is a lot of overlap between this suite and D3JS, it already has this sort of support and I can create nodes with custom classes to render icons from Ionic.  This would bring things a bit more inline competition.

Side Note:  Not that this matters, but while I am ok with this being done with Cytoscape.js, i would love for it to be also a part of the CytoscapeScala implementation.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
Usually for nodes, decorations like icons are made using background images.  I don't believe that edges currently support background images.

Would you post example mockups of the kind of decorations, and placements, you're thinking of for edges?  The placement of potential background images for edges may be different than for nodes, perhaps requiring new style properties.

Aside:  Would you link to the particular CytoscapeScala project you mentioned?

**Comment by fallenreaper** [comment]
Hey @maxkfranz thanks for reaching out so quickly. 

Ill add some mock photos below.  I am a webdev primarily, so that is specific to my use cases and use cytoscapejs from within those confines.  The team i am currently a part of is using it as a visualization for Networks.  When looking at a visualization, I think it would be ideal if I could couple an optional image with label text for contextual purposes.  To me, I have a bunch of various Icons I use from various entities, and can inject them through the use of css classes.  ( Examples: IonIcons ).  While this is a canvas, i would love to have a span or something I could access in order to add classes which would assign my icon svg accordingly.  That way if i am building a network I could just say: "Oh these Nodes or Edges have a specific property?  Add a Class reflective of the Icon".  I dont really know how it would work in the Java concept, maybe a list of static icons for a java version or a reference to a svg icon.  

- That isnt my specific forte, but i did think it would be a consideration for other users.   

I specifically like the add/removal of Classes for front end purposes since competing Force Directed Graphs have that in place.  They can let me define what a Node is and similarly with Edges ( or Links in D3JS ).  The issue though, is that there isnt a specific place to me which affords me the ability to apply that specific css. While i can apply css to a node, i kinda think it would make more sense ( in my example you will see ) if you wrap the label with a span so you can do:

```
<span>
  <span class="icon"></span>
  <span class="label">data(label)</span>
</span>
```

It would retain the positioning of where the label is, and place the icon to the left of any label within that specific space.  That way it is always centered and neat, if not applied it auto adjusts, if just an icon, it still follows the flow related to labelling.

![sampleicon](https://user-images.githubusercontent.com/315367/196486876-324a6517-e0e3-4c22-aba0-fe08c9f26e10.png)

For the other project, it looks like it an internal recast, which takes the CytoscapeJS and uses the tool "ScalablyTypedCovertor" ( https://scalablytyped.org/docs/readme ) to create a series of casts which acts as a mask for your Javascript code. There isnt any additional flavor added but allows the older devs to write Scala which compiles and plays well with your cytoscape implementation.  While i cant give the specific code for it at this time, it is not overly difficult to replicate.

**Comment by maxkfranz** [comment]
That looks a lot like this: Icons support for edges ? #1322

Take a look at that, and let me know what you think.

**Comment by fallenreaper** [comment]
Looks a little different than my sample image, BUT it would certainly do the trick.  if it is something that we can manage with CSS it would be great since it means we arent coupled to a specific set, but i noticed that the use cases were using jQuery, so i would make a guess they do have their specific icon packs which would be applied by CSS.

**Comment by fallenreaper** [comment]
not stale.

**Comment by maxkfranz** [comment]
> Looks a little different than my sample image, BUT it would certainly do the trick. if it is something that we can manage with CSS it would be great since it means we arent coupled to a specific set, but i noticed that the use cases were using jQuery, so i would make a guess they do have their specific icon packs which would be applied by CSS.

Great.  That approach generally should work with any icon font.  You can extrapolate from the examples in that issue how that approach would work generally.

**Comment by fallenreaper** [comment]
> @maxkfranz Thank you. it works now as expected/ http://jsfiddle.net/bababalcksheep/ajhnmcrb/8
> 
> But from http://jsfiddle.net/bababalcksheep/ajhnmcrb/8 is it possible that icon of twitter is inside circle and rest of text is below circle

I was notcing @maxkfranz That the first link here, if you zoom in/out will fail to render icons.
