### ISSUE TITLE
Nodes and Edges should be able to Animate flashing

### ISSUE THREAD

**Issue by fallenreaper** [cytoscape/cytoscape.js#3069]
**Description of new feature**

When adding a Class to a Node or Edge, we can change it in a lot of ways.  Similarly, I was noticing that you can animate a collection of nodes.   What I would want is the ability to animate either through CSS or some function, the ability to make a Node or Edge blink to draw the eye if so told to.

**Motivation for new feature**

When Leveraging HCI for visual impairments, a User may have issues with seeing certain colors.  To bypass this in part is to add text to give context the user may read, OR Icons, or something which would otherwise draw the eye.  Those who are color blind of sorts may not see a particular colorscheme, but having the ability to animate the color scheme / background color / fill by creating a blinking feature would change the variations of grey or other colors they are afforded the ability to see.   This would allow them to see more than 1 different static color.

While I was noticing that there is in fact collection.animate, it is to transition from 1 style to another.  I would like to extend this by going from 1 style to another, AND back.  That way we can add classes and colors set through styles, and then pivot to this new style and revert to whatever it was previously at.

This proactive thought process will allow users a greater access to draw their attention to a specific node or edge within larger diagrams.

Similarly, while this is accomplished in javascript, it should also consider supporting keyframes.  as a fundamental, I downloaded the demo at: https://github.com/cytoscape/cytoscape.js-tutorial-demo and updated the demo css file *custom.cycss* and added:

```
node {
  animation: blinkMe 2s linear infinite;
 }

@keyframes blinkMe {
  0% {
   opacity: 0;
  }
  50% {
   opacity: 1;
   fill: yellow;
  }
  100% {
   opacity: 0;
  }
 }
```
but it fails to understand keyframes which would be added for blinking.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
> While I was noticing that there is in fact collection.animate, it is to transition from 1 style to another. I would like to extend this by going from 1 style to another, AND back. That way we can add classes and colors set through styles, and then pivot to this new style and revert to whatever it was previously at.

That sounds a lot like `flashClass()`: https://js.cytoscape.org/#eles.flashClass

**Comment by fallenreaper** [comment]
I think i could use `flashClass`. With the duration as Optional, i was not sure if that meant it goes indefinately, OR it has its default value.  Maybe some clarity in the docs would be nice.  I guess if that is the case, i could just add the class if it is indef until i manually remove it.

I was trying to enable a color flashing to draw attention, so I guess I can create css which leverages keyframes to change backgrounds.  I am not sure if keyframes work in svg or not though.

im not sure if this functionality should be implemented or not in cytoscape natively.

**Comment by maxkfranz** [comment]
Great.  Could you investigate the default value and put up a PR to update the docs so that it's clearer?
