### ISSUE TITLE
Edge selection on Safari

### ISSUE THREAD

**Issue by pydrogo** [cytoscape/cytoscape.js#3072]
Hi
When I try the following example in Safari browser on my mac (macOS version 12.6)
https://ivis-at-bilkent.github.io/cytoscape.js-avsdf/demo.html

When I click on an edge it seems to me that all the edges are selected
![Screenshot 2022-11-11 at 14 59 15](https://user-images.githubusercontent.com/22586475/201355948-56c247ab-0751-4f6d-b7e9-8da0e177fc5e.png)

**Environment info**

- Cytoscape.js version :
- Browser/Node.js & version :

![Screenshot 2022-11-11 at 14 58 49](https://user-images.githubusercontent.com/22586475/201356125-ba9ccac5-db3b-4bdb-8a6c-18fd8fb7f091.png)

**Current (buggy) behavior**

_What does the bug do?_
It highlights all the edges when you click on one edge

**Desired behavior**

_What do you expect Cytoscape.js to do instead?_
only one edge should be selected like on Chrome

**Minimum steps to reproduce**

_What do you need to do to reproduce the issue?_
just open the demo on Safari on mac
https://ivis-at-bilkent.github.io/cytoscape.js-avsdf/demo.html

**Comment by maxkfranz** [comment]
Sometimes, browsers have bugs of their own that affect Cytoscape.  Let's use this issue to track this bug.  To expedite this issue, it would be helpful if you would cross-reference a bug report on Webkit.

**Comment by maxkfranz** [comment]
It looks like this has been fixed in the latest version of Safari (both mobile & desktop)
