### ISSUE TITLE
List extension : cosmos-over-cytoscape

### ISSUE THREAD

**Issue by simCecca** [cytoscape/cytoscape.js#3074]
GitHub: https://github.com/simCecca/cosmosOverCytoscape
npm: https://www.npmjs.com/package/cosmos-over-cytoscape

Description:
force-layout/physics simulation parallel on GPU, designed for big graphs

**Comment by Nicolas-PredictaLab** [comment]
Might provide a demo link ? :)

**Comment by simCecca** [comment]
Hi @Nicolas-PredictaLab, I'm creating a sandbox, unfortunately, it still doesn't see the package published on npm.
I'll add it as soon as it's visible
:)

**Comment by simCecca** [comment]
I added a codesanbox url inside the README, so you can find it both in the npm and the GitHub link :)

**Comment by maxkfranz** [comment]
Great.  It's been added to the docs
