### ISSUE TITLE
Expanding the Demo section regarding Breadthfirst layout & images

### ISSUE THREAD

**Issue by h2oicsaba** [cytoscape/cytoscape.js#3079]
**Description of new feature**

The feature can expand the graph clicking on a previously closed "leaf" element. Nice to have the graph in a closed format as his initially state  (only the highest node is visible )

**Motivation for new feature**
Having this we can use this component like an interactive graph browser (or menu) expanding  in and out the graph. I saw this asking by others , and I need it also. It can be a good promotion having it as demo in the library ... 

Use case :
Clicking on a node that was initially closed it will expand the graph to one level down. 
For that we need to save the removed  elements in the parent node object as a list. 

**For reviewers**
Please guide me what is the issue with the   thisElement.restore(); part . Why is "not working" as i aspect.

**Comment by maxkfranz** [comment]
You're welcome to create a PR if you have a new demo you'd like to add.
