### ISSUE TITLE
Mini viewport that displays where in the over all canvas you are zoomed into

### ISSUE THREAD

**Issue by Czar-Ec** [cytoscape/cytoscape.js#3084]
**Description of new feature**
A small viewport on the corner that displays which part of the over all canvas the user is currently looking at

_What should the new feature do?  For visual features, include an image/mockup of the expected output._
running cy.fit() will show the full network, which is reflected in the mini viewport
![image](https://user-images.githubusercontent.com/32554382/207037165-be7c746b-bd77-42ac-a67f-70da16520f6f.png)

Zooming in should highlight what is in the main canvas
![image](https://user-images.githubusercontent.com/32554382/207037309-234ca5bb-25c8-4d84-9847-cce6e953088d.png)

**Motivation for new feature**

_Describe your use case for this new feature._
Allows for users to be able to see the whole network even when zoomed in. This is helpful for more larger networks e.g. in the Tokyo railway network example, it would help if you knew where in the overall Tokyo network the station you are currently zoomed into is

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by hellomusa** [comment]
Have you checked out https://github.com/cytoscape/cytoscape.js-navigator?
