### ISSUE TITLE
Style: Cannot select edges in a compound node

### ISSUE THREAD

**Issue by rob-gordon** [cytoscape/cytoscape.js#3092]
Cannot select an edge for styling based on its parent node.

Imagine I've created two nodes and an edge between them, and all three elements live inside a compound node with the class `.purple`. The following code snippet shows what does work and what I would expect to work, but doesn't.

```
/* WORKS <------------------------- */
.purple node {
  background-color: purple;
  color: white;
}

/* DOESN'T WORK <-------------------------- */
.purple edge {
  line-color: purple;
}
```

Here is a stack blitz which reproduces the problem.

https://stackblitz.com/edit/js-qd9lzc?file=index.js

**Environment info**

- Cytoscape.js version : 3.23.0
- Browser/Node.js & version : Chrome 108

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by maxkfranz** [comment]
Could you point to where this feature is mentioned in the documentation?

I didn’t notice any mention of edges in these sections:

- https://js.cytoscape.org/#notation/compound-nodes
- https://js.cytoscape.org/#selectors/compound-nodes
