### ISSUE TITLE
text-border overrides text-background-shape

### ISSUE THREAD

**Issue by mssayari** [cytoscape/cytoscape.js#3093]
**Before you post**

**Environment info**

- Cytoscape.js version : 3.23.0
- Browser/Node.js & version : latest

**Current (buggy) behaviour**

Node text-border overrides text-background-shape. 

**Desired behaviour**

I've used `round-rectangle` for text-background-shape but as soon as I add border. the radius gone!

**Minimum steps to reproduce**

```
style: [
            {
                selector: 'node',
                style: {
                    'content': 'data(name)',
                    'background-color': '#ffb400',
                    'border-width': 1,
                    'border-color': '#fdd7d7',
                    'color': '#525252',
                    'min-zoomed-font-size': 10,
                    'font-size': 9,
                    'width': 'data(size)',
                    'height': 'data(size)',
                    "text-background-opacity": 1,
                    "text-background-color": "#e5e5e5",
                    'text-background-shape':'round-rectangle',
                    'text-background-padding': '2px',
                    "text-border-opacity": 1,
                    'text-border-width':1,
                    'text-border-color':'#fdd7d7',
                    'text-wrap': 'wrap',
                }
            },
]
```

Online Demo https://output.jsbin.com/hilikew

**Comment by mssayari** [comment]
Sure,

This is the demo url without border enabled.  [https://output.jsbin.com/cotijum](https://output.jsbin.com/cotijum)
Also you can comment/uncomment `text-border-width` to se the difference.

**Comment by maxkfranz** [comment]
Great, thanks.

It looks to me that both demos have some rounding applied, at least.

Without border:

<img width="503" alt="Screen Shot 2023-01-27 at 17 29 53" src="https://user-images.githubusercontent.com/989043/215218474-be672b98-cad1-4989-9edb-0a5cbaf06626.png">

With border:

<img width="589" alt="Screen Shot 2023-01-27 at 17 29 59" src="https://user-images.githubusercontent.com/989043/215218554-4a860510-7b9d-466f-ac2a-7518a3a743ca.png">

It could be that the exact same border radius isn't applied consistently.  Or it could be that the line join effect of the with-border case simply makes it look more square for a small radius value.  More investigation is needed.

**Comment by mssayari** [comment]
Thanks for replying. 

Yes you're correct, in full zoom it's noticeable but in normal zoom it looks like it doesn't have radius.

Without border (with radius):
![image](https://user-images.githubusercontent.com/39558357/215746331-1529a300-dbdd-4c39-a28c-edd00e76577a.png)

With border (with radius):
![image](https://user-images.githubusercontent.com/39558357/215746049-b2e98399-48b9-43d7-9485-78744a35f393.png)

With border (without radius)
![image](https://user-images.githubusercontent.com/39558357/215747645-88139b87-2222-4d00-b690-cc95b8f916e0.png)

**Comment by maxkfranz** [comment]
Probably will be resolved automatically by:

-  #3128

**Comment by gaginsgagins** [comment]
the problem still remains

**Comment by maxkfranz** [comment]
This would have been resolved by #3128, but the contributor hadn't completed the PR fully. 

You're welcome to pick up and finish off the PR if this issue is important to you.

**Comment by gaginsgagins** [comment]
Unfortunately, I cannot finish the PR. My level of understanding on how to do it is zero. I am a beginner programmer.

**Comment by maxkfranz** [comment]
OK, I'll assign this issue to someone on the team.

**Comment by maxkfranz** [comment]
Since #3128 has not been completed yet, let's revisit this separately.

@mikekucera, would you take a look at this one?  Christian's already got #3005.
