### ISSUE TITLE
Append Styles from String or Stylesheet

### ISSUE THREAD

**Issue by rob-gordon** [cytoscape/cytoscape.js#3098]
**Description**

From my understanding, currently you can only append styles to the existing styles using the `cy.style().selector()...` pattern.

It seems like all the functions are already present to make it possible to append styles using a string or Stylesheet, including 
- [parsing strings](https://github.com/cytoscape/cytoscape.js/blob/89ba5979154a46a942b2fb989782a5b045173e43/src/style/string-sheet.js#L6) into stylesheets, 
- [getting the current styles](https://github.com/cytoscape/cytoscape.js/blob/89ba5979154a46a942b2fb989782a5b045173e43/src/style/json.js#L36), and 
- appending styles.
 
I believe it could be possible to add this functionality by combining and/or exposing some of these pre-existing functions, possibly via a new function, e.g. `cy.style().append()`

(logic flow)
![appending-from-string-or-stylesheet](https://user-images.githubusercontent.com/159949/215194313-0fd8bd2c-35a5-452d-8870-0d45bad9f9ff.png)

**Motivation**

From the standpoint of building user-interfaces to facilitate graphing, style strings are by far the easiest way to give users direct access to custom styling. I would love to expose this functionality to users of flowchart.fun if possible. I even began a PR before reaching this roadblock.

![Screen Shot 2023-01-27 at 3 47 42 PM](https://user-images.githubusercontent.com/159949/215194059-80aaae87-2aa9-44eb-8b52-09797db60a67.png)

**Contributing**

I don't have a lot of experience with this repository but I would be happy to try opening a PR implementing the change outlined here if the maintainers are open to them. Thanks!

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
I think there is the ability to append already, but possibly only in the function format: https://js.cytoscape.org/#cy.style

> Add to the existing stylesheet:

```
cy.style()
  .selector('node')
    .style({
      'background-color': 'yellow'
    })

  .update() // indicate the end of your new stylesheet so that it can be updated on elements
;
```

There might be analogous undocumented functions for the other formats that we could make public, or maybe those functions could be built with what's there without too much trouble.

But frankly, I doubt that there is much benefit to appending in most cases, and in your use case, over simply replacing the entire stylesheet each time.

As a user of Flowchart.fun, I'd want to use a single string stylesheet for the entire graph.  In that case, you're basically replacing the entire stylesheet on each hit of 'apply', anyway.  Personally, I wouldn't really want to use the JSON format in this app.

As an aside, Flowchart.fun is an excellent tool.  I'd really like to see the ability to save manually edited layouts.  The automatic layout is very good most of the time, but sometimes I want to drag one or two of the nodes to make it just right.  If I could save those positions somehow, it would be a neat, differentiating feature -- as compared to tools like Graphviz, where you're captive to whatever the layout algorithm decides.  (Forgive me for the impromptu feature request...)

**Comment by rob-gordon** [comment]
> _Flowchart.fun is an excellent tool. I'd really like to see the ability to save manually edited layouts_

I'm really glad you've found some usefulness in the tool because it's very much indebted to your work on cytoscape. 
Re: manually-edited layouts, we do persist manually edited layouts (video) by using the "preset" layout and saving node positions. 

Are you saying you'd like to see the ability to freeze individual nodes but continue using auto-layouts? (If you'd like to move this discussion out of Issues you can also email me at rob.gordon@tone-row.com)

https://user-images.githubusercontent.com/159949/215531970-c973fa8b-2aad-43a5-9bb4-5b5832c4357c.mov

---

> _As a user of Flowchart.fun, I'd want to use a single string stylesheet for the entire graph_

Flowchart Fun has a number of base styles, utility classes, and then themes which up-to-now have been abstracted away from the user. Hence, the need for appending by string.

However, in the long term I would like styles to be more user-editable and have less maintenance cost. 
Loading an entire stylesheet may actually be the best way to do that. 
Thank you for the suggestion!

> _I doubt that there is much benefit to appending in most cases_

I agree and we can close this issue, but out of curiousity if I could find the time to open a PR to add a way to append-by-string would you consider it?

**Comment by maxkfranz** [comment]
> Are you saying you'd like to see the ability to freeze individual nodes but continue using auto-layouts? (If you'd like to move this discussion out of Issues you can also email me at [rob.gordon@tone-row.com](mailto:rob.gordon@tone-row.com))

I was just thinking out loud.  Maybe something along the lines of a way of editing/saving/exporting the positions via text, kind of like what you showed for style.

> I agree and we can close this issue, but out of curiousity if I could find the time to open a PR to add a way to append-by-string would you consider it?

The feature is there for the function style, so it may as well be there for stylesheet strings and JSON.  Please `@mention` me when you've got your PR so I can set aside some time to review and merge

**Comment by rob-gordon** [comment]
I don't know how I missed it before but I came across this code this evening: https://github.com/cytoscape/cytoscape.js/blob/e6541de603f5714f572238573ea06ef17503282b/src/style/index.js#L160-L162

Looks like it *is* possible to append styles with a string already. It works well / is going to make some fun things possible in Flowchart Fun in the future.

![Screen Shot 2023-02-15 at 11 07 23 PM](https://user-images.githubusercontent.com/159949/219266548-5eaddabd-587a-4fd8-beda-73e8df2c6f5b.png)

We can close this issue 👍🏻

**Comment by maxkfranz** [comment]
Great.  Looks like we should document this to make it public.  Would you add a PR to add an example like that to the docs in the corresponding md file?

It looks like the documentation has examples for `fromJson()` to override the entire stylesheet, but it doesn’t have anything about JSON `append()` : https://js.cytoscape.org/#cy.style <https://js.cytoscape.org/#cy.style>

**Comment by rob-gordon** [comment]
@maxkfranz Sorry I'm dragging my feet on this. I will get a PR in with the updates to the docs this week 👍🏻

**Comment by maxkfranz** [comment]
Looking forward to it
