### ISSUE TITLE
CollapsedChildren method on event's target object returns null even though elements are present inside

### ISSUE THREAD

**Issue by poornima-taranath** [cytoscape/cytoscape.js#3110]
**Environment info** 

- Cytoscape.js version : 3.23
- Browser/Node.js & version : Chrome , 110.0.5481.180

**Current (buggy) behaviour**

_What does the bug do?_
I am trying to use the collapsedChildren method to expand and collapse on double click event. Ideally, it should return a collection of all collapsed children but sometimes even with values present it returns null.
Another related bug is, when children are returned by collapsedChildren() , inside the target object it shows as null, whereas it should have shown children elements in both cases. 

**Desired behaviour**

_What do you expect Cytoscape.js to do instead?_
It should return the collection whenever any children is present. If the target.data() object is opened, we can see that collapsedChildren has values inside of it but when called , it's returning null.

Reproduce the issue :

1. Initialize cytoscape
2. Attach any event handler( dbl click in my case) 
3.   let targetData = event.target;
        console.log(targetData.data() , targetData.data().collapsedChildren)
The 2nd print results in null sometimes, during that you can open the targetData.data() and check for collapsedChildren.

4. Download and Initialize cytoscape-expand-Collapse (optional)

Entire event handler:

`var api = cy.expandCollapse('get') //expand collapse get object to run it's methods.`

```
     cy.on("dblclick", "node",function(event){
        let targetData = event.target;
        console.log(targetData.data() )
        console.log( 'collapsedchildren' , targetData.data().collapsedChildren)
        let collapsedChildrenArray = targetData.data()?.collapsedChildren
        console.log(collapsedChildrenArray?.size())
        if( collapsedChildrenArray !== undefined && collapsedChildrenArray !== null && collapsedChildrenArray.size() > 0)
          api.expand(targetData)
        else if( collapsedChildrenArray === undefined )
           return null 
        else {
          api.collapse(targetData)
        }
          
      })
```

The bug is captured in the below screenshot.  collapsedChildren under the target object which is showing as null is when I have called the  latter part of this code- ```console.log(targetData.data() , targetData.data().collapsedChildren)```
![image](https://user-images.githubusercontent.com/45766772/225053908-1109c574-f019-410d-87ed-dcaf605c8b24.png)

Bug screenshot where collapseChildren() returns elements but shows as null inside target 
![image](https://user-images.githubusercontent.com/45766772/225055044-f8838f42-5b3b-4f4d-9837-92d56dbb7dd2.png)

From what the method's name indicates, it should provide the collapsedChildren when tried to access but the output is behaving exactly in the reverse expected fashion. 
Any comments and updates if I have misunderstood this method, is much appreciated.
Thanks for taking your time to read so far.

**Comment by maxkfranz** [comment]
It looks like this is about an extension.  You should post an issue with a reproducible demo to the extension so that the appropriate team can see it: https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse

**Comment by poornima-taranath** [comment]
I apologise for posting here, I figured out that collapsedChildren property is coming on target object only once expandCollapse is registered.  I shall reach out to the other team. Thank You.
