### ISSUE TITLE
Clean up the repository

### ISSUE THREAD

**Issue by Sagleft** [cytoscape/cytoscape.js#3112]
I've noticed that people working with JS don't understand how to organize repositories.
Repos shouldn't have assemblies. They should be put in releases. It's just bleeding from the eyes when you see things like this

**Comment by maxkfranz** [comment]
> It's just bleeding from the eyes 

Oh my!  You really ought to see an ophthalmologist.  [I don't see how you could have possibly managed to file the issue in that state.](https://fs.blog/chestertons-fence/)

Let's keep things constructive and productive.  In future, you may find that the issue template helps in making productive, actionable proposals.
