### ISSUE TITLE
Allow a cytoscape element to have multiple styles per label.

### ISSUE THREAD

**Issue by Ahmed-username** [cytoscape/cytoscape.js#3116]
**Description of new feature**

Allow an element's label to have multiple styles.
This might mean that an element could have an array of labels, and each label has its own different style.
Or just the label accepting and parsing HTML.
In [this screenshot ](https://ibb.co/VM04FkL) there is a node that has multiple styles applied to its label. 

**Motivation for new feature**

In a detailed graph a label could have a lot of information displayed on the label, so it would be useful to apply a different style for a part of the label to make it stand out.
I have tried [Cytoscape HTML node label](https://github.com/kaluginserg/cytoscape-node-html-label) extension and it works however it is not as stable as Cytoscape.

Thanks

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
I don't think that this would be fitting for the core library.  It begins to border on reimplementing much of the browser's text rendering.

You have an excellent idea for a feature, and it would be best addressed in extensions.
