### ISSUE TITLE
Allow usage of cytoscape js in containers made in WindowProxy

### ISSUE THREAD

**Issue by AdamChlupacek** [cytoscape/cytoscape.js#3129]
**Description of new feature**

Support rendering of cytoscape graph in [WindowProxy](https://developer.mozilla.org/en-US/docs/Glossary/WindowProxy) created via [window.open](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#return_value)

Currently cytoscape can only be used in the window in which is the javascript loaded. If we create a new window and try to render cytoscape in to a container in the new window (see example bellow), many styles / events are incorrectly handled. 

```javascript

var openWindow = window.open("./index.html", "_blank", "popup")

openWindow.addEventListener("load", (event) => {
  var container = openWindow.document.createElement("div")
  openWindow.document.body.appendChild(container);

  cytoscape({
    container: container
  })
})

```

In this use case the new graph cannot be moved and selection highlight gets stuck.

**Motivation for new feature**

The need for this feature raises from ease of use to open a new window for display of a graph without the need to run a full application in the new window which is opened. 

This allows SPA to have one main window which is running the core application, which handles business logic and  an unlimited number of windows  which display data, so that the user can easily compare different graph. 

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [x] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [x] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [x] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [x] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
Merged in #3130
