### ISSUE TITLE
Calling .select() in this.cy.on("click") does not select any nodes

### ISSUE THREAD

**Issue by AlexW00** [cytoscape/cytoscape.js#3132]
**Before you post**

**Environment info**

- Cytoscape.js version : latest (3.23.0)
- Browser/Node.js & version : Firefox, 18 

**Current (buggy) behaviour**

When calling node.select() in the "click" callback, it does not select any nodes.

**Desired behaviour**

The node should be selected.

**Minimum steps to reproduce**
I guess it has something to do with cytoscape performing some selection actions after the click event? When setting a timeout 0 (i.e. moving the function execution to the javascript callback queue), it works.
```ts
this.cy.on("click", (event: any) => {
       const relevantNodeElements = this.cy.elements();
        // This does NOT work:
	relevantNodeElements.forEach((nodeElement) => {
	        nodeElement.select();
	});

       // This DOES work:
        setTimeout(() => {
		relevantNodeElements.forEach((nodeElement) => {
			nodeElement.select();
		});
	}, 0);
});
```

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by maxkfranz** [comment]
> I guess it has something to do with cytoscape performing some selection actions after the click event? 

Yes, it's a common convention -- e.g. native widgets and focus or selection events.
