### ISSUE TITLE
List extension : cytoscape-blink nodes and edges

### ISSUE THREAD

**Issue by simCecca** [cytoscape/cytoscape.js#3134]
description: Give to cytoscape the possibility of blinking nodes and edges so as to highlight and distinguish them as a whole. Given an array of ids, it blinds those nodes and edges on the screen and finally highlights them

repo: https://github.com/simCecca/cytoscape-blink
npm: https://www.npmjs.com/package/cytoscape-blink

live-example: https://lkvc2t-3000.csb.app/
sanbox: https://codesandbox.io/p/sandbox/blazing-fast-lkvc2t?file=%2Fpackage.json%3A1%2C1

**Comment by maxkfranz** [comment]
Your extension has been added to the list, and it will be in the documentation at the time of the next release.
