### ISSUE TITLE
Reset of startPosition leads to issues

### ISSUE THREAD

**Issue by til2000** [cytoscape/cytoscape.js#3137]
When using touch devices and dragging nodes, potentially using two fingers, resizing, then there are errors like `TypeError: null is not an object r.touchData.startPosition[foo]`.

This error is related to this line here:
https://github.com/cytoscape/cytoscape.js/blob/a46764fd7acd91fdd93ce9efcc624e67354290e4/src/extensions/renderer/base/load-listeners.js#L2023C31-L2023C31

and should be reset to it's initial value from: 
https://github.com/cytoscape/cytoscape.js/blob/a46764fd7acd91fdd93ce9efcc624e67354290e4/src/extensions/renderer/base/index.js#L72

**Comment by maxkfranz** [comment]
> When using touch devices and dragging nodes, potentially using two fingers, resizing, then there are errors like `TypeError: null is not an object r.touchData.startPosition[foo]`.

Does dragging a node consistently reproduce this error?  What are the steps exactly?
