### ISSUE TITLE
Panning and box selection do not work simultaniously from exported Cytoscape code.

### ISSUE THREAD

**Issue by WG-** [cytoscape/cytoscape.js#3143]
**Environment info**
- Cytoscape.js version : unsure, HTML export from Cytoscape application (downloaded yesterday)
- Browser/Node.js & version : unsure, export from Cytoscape application (downloaded yesterday)

**Current (buggy) behaviour**
When I set the userPanningEnabled or panningEnabled to true in the generated code. Panning works. However, when boxSelectionEnabled is also true panning doesn't work anymore, only box selection works and is activated with any mouse activity. Pressing shift, ctrl, alt etc does not activate panning.

I checked with a minimal example of Cytoscape.js. There both functionalities do work. User panning works by just dragging and box selection works by holding down shift. For the generated code that comes out of cytoscape that is not the case.

**Desired behaviour**
Both panning and box selection work

**Minimum steps to reproduce**
Export graph from Cytoscape towards html website.

_What do you need to do to reproduce the issue?_
If needed I can provide my complete export. It is quiet a big graph (~4500 nodes)

**For reviewers**
_Reviewers should ensure that the following tasks are carried out for incorporated issues:_
- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by maxkfranz** [comment]
Thanks, @WG-.  I'll bring this up with the desktop app team.  In the meanwhile, would you have anything to add regarding how to reproduce your issue from the desktop app side?  For instance, would you be able to upload your session file?

**Comment by maxkfranz** [comment]
@WG-, the desktop team is aware of the issue and they'll address it in an upcoming update.

It's likely the case that you can resolve your issue by upgrading the version of Cytoscape.js that you're using in your page.  If you have further details to share, just let us know.
