### ISSUE TITLE
Add chevron arrow to the edge-arrows demo in the documentiaton.

### ISSUE THREAD

**Issue by MarkBoyes** [cytoscape/cytoscape.js#3148]
**Description of new feature**

Add chevron arrow to the edge-arrows demo in the documentation.

**Motivation for new feature**

The chevron arrow has been in the library since 2018 but there is no example in the demo. 

This was particulalrly annoying for me as this shape exposed a bug in Firefox 115, and to submit a bug report to Firefox I had to create my own online demo exhibiting the problem rather than citing the cytoscape.js demo.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [x] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [x] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [x] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [x] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
This will be released in 3.26.1
