### ISSUE TITLE
Deterministic force-directed layout results

### ISSUE THREAD

**Issue by k2xl** [cytoscape/cytoscape.js#3150]
I have a graph and setting graph type to cose and randomize to false, but it always seems to still randomize the final positions of the nodes. Basically I'm looking for the nodes to arrange the same way in every page load

**Comment by k2xl** [comment]
Ah got it, was hoping I could keep it deterministic. I guess i'll just keep refreshing until I get a nice layout and then save the positions. Is there an easy way to recall all the positions (even with console log?)

**Comment by rob-gordon** [comment]
@k2xl https://js.cytoscape.org/#nodes.positions

**Comment by maxkfranz** [comment]
As @rob-gordon pointed out, one of the cases where a force-directed layout (e.g. COSE) would require a PRNG is for initial positions.

There are other cases generally, e.g. avoiding divisions by zero when two nodes have the same mid-layout position.

For force-directed layouts to support deterministic results, you'd need to provide a better PRNG than `Math.random()` in the API, perhaps allow API users to set the seed, review the layouts for related issues, and so on.

If anyone is interested in contributing a feature like this, you're welcome to use this issue (or a discussion) to scope it out.
