### ISSUE TITLE
Node outlines

### ISSUE THREAD

**Issue by npedrini** [cytoscape/cytoscape.js#3156]
**Description of new feature**

Following on from a few of the features mentioned in https://github.com/cytoscape/cytoscape.js/discussions/3145#discussioncomment-6644529, this issue proposes the addition of outlines as a new, optional node style, similar to but distinct from borders.

Node outlines would be defined by and support the same properties as borders (`outline-color`, `outline-opacity`, `outline-width` and `outline-style`), with an additional `outline-offset` property for offsetting the outline. 

Outlines wouldn't affect the calculated node size, although bounds calculations would take outlines into account so that larger outlines don't get clipped at lower zoom levels without having to rely on the `bounds-expansion` property. 

Here are a few mock-ups showing what outlines would look like:

_2px outline with no offset:_

<img width="275" alt="Screen Shot 2023-08-21 at 10 26 35 PM" src="https://github.com/kumu/kumu/assets/1434577/02dc0920-1d70-47d0-bff5-1ad4cd5d4a34">

_4px outline with 2px offset:_

<img width="289" alt="Screen Shot 2023-08-21 at 10 28 10 PM" src="https://github.com/kumu/kumu/assets/1434577/bb9febde-0e44-4933-95bc-4a96ddaa1613">

_4px dashed outline with 4px offset:_

<img width="353" alt="Screen Shot 2023-08-21 at 10 57 15 PM" src="https://github.com/kumu/kumu/assets/1434577/afde483a-b785-4a46-9983-b8ae88d434dc">

**Motivation for new feature**

Outlines provide an additional visual indicator that can be used, amongst other things, to signal user interaction, particularly in cases where border style and/or underlays are already being used. Additionally, outlines provide a way to convey interaction in a way that doesn't obscure the node, like overlays do.

 As a relatively new user of the library and first-time proposer, happy to provide additional detail if needed!

**Comment by maxkfranz** [comment]
The screenshots don't seem to work in the OP anymore.

**Comment by maxkfranz** [comment]
Pinned

**Comment by maxkfranz** [comment]
Assigned to the 3.28.0 milestone.
