### ISSUE TITLE
Add support for float numbers in the z-index style property

### ISSUE THREAD

**Issue by d2fong** [cytoscape/cytoscape.js#3160]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

Allow users to specify float numbers for the `z-index` style property.

**Motivation for new feature**

_Describe your use case for this new feature._

Currently, Cytoscape.js allows only integers for the `z-index` style property.  However, in Cytoscape Desktop, there are instances where users would like to specify values like `1.0` or `1.2` including negative numbers like `-1.0` or `-10`.  This change would allow us to avoid another transformation layer when importing networks from Cytoscape Web from Cytoscape Desktop and vice versa.  

The downside I can see is that change would make z-index behave slightly different than the css z-index property.  Integers will still be supported, but users may find it foreign to allow a z-index be a float number.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
Great.  Is there anything else for the use case in the app?  The library has more properties that affect the draw order, and they may need to be accounted for in conversions even if not in the UI.

Are we certain that solely this int=>double change is sufficient for this use case in the app?

**Comment by d2fong** [comment]
Let me verify with the rest of the UCSD team.

**Comment by d2fong** [comment]
I can confirm that this is the only change the UCSD team needs.

**Comment by maxkfranz** [comment]
I'm going to postpone the 3.27.0 release a bit so we can get this feature in for Cyweb ASAP.  I'll aim for a Wed/Thu release.

**Comment by maxkfranz** [comment]
@d2fong, let me know if this is suitable for release.

**Comment by maxkfranz** [comment]
Great, I’ll adjust this tomorrow then.  It should be a straightforward change.

**Comment by maxkfranz** [comment]
Re-opening, as I see now that I should add a note regarding negative values and how they don't work like traditional CSS, by putting things behind the current layer.
