### ISSUE TITLE
Node flags

### ISSUE THREAD

**Issue by danprince** [cytoscape/cytoscape.js#3164]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

Flags would be a new Cytoscape decoration that allowed nodes to visualise multiple value fields with a set of colors around the outside of the node.

<img width="918" alt="image" src="https://github.com/cytoscape/cytoscape.js/assets/1266011/67318f50-816e-475c-bb1e-85e96c07f6c6">

This would involve adding the following style properties to Cytoscape.js.

- `flag-property` (the name of the property to use for indicating the presence of flags).
- `flag-colors` (a list of colors to use)
- `flag-size` (the stroke width of the rendered flag)
- `flag-offset` (the offset distance between the outside of the node and the center of the flag stroke)

There are two additional properties which might make sense to add here too.

- `flag-spacing` or `flag-gap` (control the size of the gap between flag segments)
- `flag-mode: "sparse" | "fill"` (sparse is the default, "fill" ensures that any present flag segments add up to 360 degrees)

<img width="738" alt="image" src="https://github.com/cytoscape/cytoscape.js/assets/1266011/a221ba67-871c-47b5-ade0-251b54747340">

**Additional considerations**

It might also be worth considering a syntax which explicitly maps from values to colors, to reduce ambiguity around which value will be assigned to which color.

```css
flag-property: "tags";
flag-colors: "foo" "red", "bar" "green", "baz" "yellow";
/* nodes where `data("tags").includes("foo")` will get a "red" flag. */
```

It's also worth clearly acknowledging that this is a _similar_ feature to the pie styles mentioned [here](https://github.com/cytoscape/cytoscape.js/issues/2789), but takes a different approach that involves enumerating the values and mapping them to a palette, rather than coding a fixed number of slices statically.

**Edge cases**

- Multiple selectors adding flags to elements (last write wins, never merge sets of flags)
- Number of values exceeding the number of colors (omit flags values that don't have colors)
- Flags around non-circular elements (flags are always rendered as a circle regardless)
- Flag spacing values taking up more than 360

**Motivation for new feature**

_Describe your use case for this new feature._

Given a set of nodes where each node has a multiple value property, flags enable quick scannable visualisation of the presence of values on each element. Here's some example data:

```ts
{
  nodes: [
    { data: { id: "java", tags: ["static", "jvm", "imperative"] } },
    { data: { id: "scala", tags: ["static", "functional", "jvm"] } },
    { data: { id: "clojure", tags: ["dynamic", "functional", "jvm"] } },
  ]
}
```

And here's a suggestion for how flag styles would work:

```css
[tags] {
  flag-property: "tags";
  flag-colors: "red", "green", "blue", "cyan", "magenta", "yellow";
}
```

And a mockup for how they'd look:

<img width="668" alt="image" src="https://github.com/cytoscape/cytoscape.js/assets/1266011/b906a327-f2be-471c-9ae4-0e5c64cf43d1">

As additional context, here's some of the language and framing we've used for introducing Kumu users to flags.

- The blog post we used to launch flags for Kumu: https://blog.kumu.io/introducing-flags-a-new-decoration-for-multiple-value-fields-88fc879889c8
- Our public facing docs for flags: https://docs.kumu.io/guides/decorate/flags

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
@danprince, do you want to schedule a call to discuss some of these issues in more detail?  I'm offline this upcoming week, so we could schedule something for the subsequent week.  My email is maxkfranz@gmail.com.

**Comment by danprince** [comment]
Thanks! Replied by email.

**Comment by maxkfranz** [comment]
Summary of previous discussions:

- There should be separate properties for flags, even if they share a similar implementation to pie charts
- Pie charts should be un-deprecated. A new issue for this will be made.

**Comment by maxkfranz** [comment]
@danprince, do you have an ETA for the PRs for the prior features?

**Comment by danprince** [comment]
Hey @maxkfranz, afraid we're still catching up on work from the end of last year without a ton of breathing room at the moment.

I can drop you a line when we've got some space again, but it's definitely not going to be in the next few weeks.

**Comment by maxkfranz** [comment]
@danprince 

I'll keep these issues pinned, and I'll keep an eye out for your upcoming email.

**Comment by maxkfranz** [comment]
Closing, as this issue has been inactive for some time.  It can be reopened once someone picks it up.
