### ISSUE TITLE
Segment edges dynamic at every edge

### ISSUE THREAD

**Issue by steven-bioinfo** [cytoscape/cytoscape.js#3168]
hello,

I want to specify a segment-distances and segment-weights for all edges in my graph.
These values will be different for each node.

Can we add these values to the edge attributes to apply them automatically ?

I've only success to apply the segments type via styles with a selector.

For example, i add this in the style part:
```
"style": [
        {
            "selector": "edge[ lineType = \"segment1\" ]",
            "css": {
                "curve-style": "segments",
                "segment-distances": [
                    40
                ],
                "segment-weights": [
                    0.50
                ]
            }
        },
```

But with the version, i must create a lineType for each edge with an unique value.

It's possible to specify the segment-distances and the segment-weights in the elements.edge ? 

Thanks,

Steven

**Comment by maxkfranz** [comment]
Yes, generally people use a mapper for that: https://js.cytoscape.org/#style/mappers

If you're familiar with the [Cytoscape desktop software](https://cytoscape.org) and how it uses mappers, the concept is similar here.

The [Cola gene-gene network demo](https://js.cytoscape.org/demos/colajs-graph) has an example of this[ in its source code.](https://github.com/cytoscape/cytoscape.js/tree/master/documentation/demos/colajs-graph)  You can see that [the node width and height is mapped to the `score` data property in nodes](https://github.com/cytoscape/cytoscape.js/blob/b6f5dff291ed5c52c43cfc6a42b008716ac025c0/documentation/demos/colajs-graph/cy-style.json#L11-L12), in this example.
