### ISSUE TITLE
[docs] typo in docs 

### ISSUE THREAD

**Issue by jhk0530** [cytoscape/cytoscape.js#3169]
Hi, thanks for nice work.

https://js.cytoscape.org/#cy.autoungrabify

in this paragraph, 

`Get or set whether nodes are automatically ungrabified (i.e. if true, nodes are ungrabbale despite their individual state).`

I think ungra**bbale** should be fixed as ungra**bbable**

If you want, I can make a PR for this.

Thanks. 

Kim

**Comment by maxkfranz** [comment]
Good catch.  If you would put up a PR to correct the typo, it would be much appreciated and it can go into the soon-upcoming release.  Just mind that the source MD and/or JSON files are amended, rather than the built HTML file.
