### ISSUE TITLE
COSE layout raise a TypeError exception when the collection contains an edge but not both endpoints

### ISSUE THREAD

**Issue by cyrilbouvier** [cytoscape/cytoscape.js#3170]
**Environment info**

- Cytoscape.js version : 2.23
- Browser/Node.js & version : all

**Current (buggy) behaviour**

_What does the bug do?_

When the COSE layout is called on a collection that contains one edge from a node inside the collection to a node outside of the collection, the `layout.run()` command raise a TypeError

```js
TypeError: Cannot read properties of undefined (reading 'id')
    at Ws (cytoscape.min.js:32:75757)
    at Xs.run (cytoscape.min.js:32:72948)
   ...
```

**Desired behaviour**

_What do you expect Cytoscape.js to do instead?_

A execution of the COSE layout without exception.

**Minimum steps to reproduce**

_What do you need to do to reproduce the issue?_

See https://jsbin.com/xibalumaga/edit?js,console,output

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by maxkfranz** [comment]
Thanks for the issue report.  I've verified that your demo reproduces the issue.

Likely, the simplest way to address this is to filter the edges when the layout starts to exclude any that have connected nodes that are not in the set of passed-in nodes to the layout.  That should be a cheap operation, since Cytoscape already supports inexpensive set membership checks.

**Comment by maxkfranz** [comment]
@chrtannus, would you take on this one? It should be easier than the other issues you're assigned on, so it would be an easier intro.

**Comment by maxkfranz** [comment]
@cyrilbouvier, take a look at @chrtannus' pull request and verify that it resolves your issue. 

See PR #3178.

**Comment by cyrilbouvier** [comment]
The PR fixes the issue, thank you very much !

**Comment by maxkfranz** [comment]
Great.  Thanks, @cyrilbouvier
