### ISSUE TITLE
edges cannot be displayed at the top of nodes

### ISSUE THREAD

**Issue by zhangdaoke** [cytoscape/cytoscape.js#3185]
I have a node A that serves as a background, and another node B and node C on top of node A. Now I need to connect B and C, but A covers the line between B and C. I've tried using edge.style('z-index', 9999), but this attempt is ineffective. What should I do?

**Comment by maxkfranz** [comment]
> 
> 
> I have a node A that serves as a background, 

Generally a bad idea

and another node B and node C on top of node A. Now I need to connect B and C, but A covers the line between B and C. I've tried using edge.style('z-index', 9999), but this attempt is ineffective. What should I do?
> 

You have to carefully use all the appropriate display properties, especially the z-* props: https://js.cytoscape.org/#style/visibility

**Comment by maxkfranz** [comment]
Yes, the props are per element and that's not something that can be changed. If you want to create global backgrounds, then you'll either have to create those yourself in your app at the app level -- or you can check out the UI extensions (e.g. layers).
