### ISSUE TITLE
mouseover not firing

### ISSUE THREAD

**Issue by bunsenbeaker** [cytoscape/cytoscape.js#3186]
**Before you post**

A request for help or a requests for a how-to should be directed to [Phind]([url](https://www.phind.com/search?c=I%27m%20using%20the%20Cytoscape.js%20graph%20theory%20JS%20library.&q=How%20do%20I%20create%20a%20graph%20in%20my%20HTML%20page)).

If your issue pertains to an extension, your issue should be filed in that extension's repository -- not here.

**Environment info**

- Cytoscape.js version : 3.27.0
- Browser/Node.js & version : Node 18.13.0 Chrome 119.0.6045.160

**Current (buggy) behaviour** 

_What does the bug do?_
mouseover events are not fired: when subscribing to node mouseover events using on('mouseover', handler) no events are fired whatsoever. When subscribing to core mouseover events (using cy.on('mouseover', handler) - sporadic events are fired at random locations on graph. I also tried registering node by node (using cy.nodes() forEach, with no success. 
I also removed layers extension and gave cy container div higher z-index with no success. Click events are fired properly.
 
**Desired behaviour**

_What do you expect Cytoscape.js to do instead?_
fire all mouseover events

**Minimum steps to reproduce**

_What do you need to do to reproduce the issue?_

merely subscribe to core/node mouseover events.

_Fork/clone this JSBin demo and reproduce your issue so that your issue can be addressed quickly and effectively:_
http://jsbin.com/fiqugiq

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by til2000** [comment]
the link doesnt work:
http://jsbin.com/fiqugiq

**Comment by maxkfranz** [comment]
You have to fork your own copy to create your own demo with issue-specific code. On Nov 16, 2023, at 04:28, til2000 ***@***.***> wrote:﻿
the link doesnt work:
http://jsbin.com/fiqugiq

**Comment by maxkfranz** [comment]
@bunsenbeaker, do you have a demo of your issue?
