### ISSUE TITLE
rotation of node 

### ISSUE THREAD

**Issue by captain-Akshay** [cytoscape/cytoscape.js#3187]
**Description of new feature**
i wanted to rotate the node using a button as other canvas does but cytoscape is not having this style property of "rotation" or "transform" it would be great to have it 

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
What would this proposed feature rotate precisely? Which properties?  Which behaviour?

**Comment by captain-Akshay** [comment]
Sorry for such a short request.. let me elaborate

**Comment by captain-Akshay** [comment]
#2913  elaborated here .
The thing i m saying is that i m working my multiple node for different shapes 
and i want to put a button over the node to rotate it on the z-axis 
but there is no style exposed for the node to rotate here..that's why it would be great and highly appreciated if you could add them in the style!

**Comment by captain-Akshay** [comment]
And i apologies for such short and lame request @maxkfranz

**Comment by captain-Akshay** [comment]
@maxkfranz 
Upon observing other canvases with similar options, I have noted the following commonalities:

   - Nodes typically have the ability to rotate in a fixed position.
   - Labels generally remain in a consistent position.
   - The position of the label (bottom, left, right, or top) is user-dependent.

It is essential to consider the following edge cases:
   
- The edge connected to the node should maintain its position without undergoing rotation. 
- If the label is at the bottom, it should remain in the same position unless the user opts to rotate it along with the node.

To address this, I propose exposing a rotation property in the node style, allowing users to control the degree of rotation while maintaining a fixed position.

P.S.
I'm not good with figma so can't share any mockup sorry.

**Comment by maxkfranz** [comment]
What about all the other, related properties, like background images?If you can’t use Figma, you’re welcome to upload pen and paper mockups, photographed with your mobile phone. On Nov 23, 2023, at 10:41, Akshay Sharma ***@***.***> wrote:﻿
@maxkfranz
Upon observing other canvases with similar options, I have noted the following commonalities:

Nodes typically have the ability to rotate in a fixed position.
Labels generally remain in a consistent position.
The position of the label (bottom, left, right, or top) is user-dependent.

It is essential to consider the following edge cases:

The edge connected to the node should maintain its position without undergoing rotation.
If the label is at the bottom, it should remain in the same position unless the user opts to rotate it along with the node.

To address this, I propose exposing a rotation property in the node style, allowing users to control the degree of rotation while maintaining a fixed position.
P.S.
I'm not good with figma so can't share any mockup sorry.

**Comment by maxkfranz** [comment]
> What about all the other, related properties, like background images?If you can’t use Figma, you’re welcome to upload pen and paper mockups, photographed with your mobile phone. 

@captain-Akshay, any thoughts on the above?

**Comment by captain-Akshay** [comment]
@maxkfranz yes the background Image will rotate itself else what's the point rotating a circular shape :).
For mockup:
we can make the edge fixed or movable based which ever one is easier 


[Screencast from 2023-12-08 00-13-11.webm](https://github.com/cytoscape/cytoscape.js/assets/59491379/e16926d7-0744-45e7-acac-2ddbaaf2dc52)

**Comment by captain-Akshay** [comment]
Oh yes!
there might be cases to rotate only the outer border than the inner image 
if can expose all the aspect then that would be great!

`background-rotation`
`shape-rotation`
`edge-rotation` only if possible 
controlling all the aspect together would be easier too if all of them are exposed.
based on user the top 2 would suffice all the aspect.

**Comment by maxkfranz** [comment]
Unless there's a clear use case for your proposed `edge-rotation`, how about we focus solely on `background-rotation` and `shape-rotation` for now?

**Comment by captain-Akshay** [comment]
yeah `edge-rotation`  have only some particular use cases we can ignore that and focus on the other two!
it's great to have the other two!

**Comment by maxkfranz** [comment]
Great.  I look forward to seeing your PR.  Best to start with `shape-rotation`, as `background-rotation` could be handled in a second PR.

**Comment by captain-Akshay** [comment]
sure let me try doing that!
