### ISSUE TITLE
Add edge <position>-arrow-width for hollow shapes 

### ISSUE THREAD

**Issue by EliotRagueneau** [cytoscape/cytoscape.js#3191]
**Description of new feature**

Hi, we would like cytoscape.js to allow us to customize how wide the stoke of hollow shapes are, because at the moment they do not blend with the rest of our developped style, but we need them to follow SBGN standards. We were thinking of a property like <position>-arrow-width, but of course it can be simpler than that, like using the edge width on the arrow hollow shapes as well.
<img width="1008" alt="Screenshot 2023-11-28 at 11 17 46" src="https://github.com/cytoscape/cytoscape.js/assets/42945601/488cf346-7ec1-4068-9f88-4df61a08cbda">
<img width="506" alt="Screenshot 2023-11-28 at 11 17 55" src="https://github.com/cytoscape/cytoscape.js/assets/42945601/56e39e09-012c-4aac-a1f3-e5bec21cf2a7">

**Motivation for new feature**

We are developing a new [reactome-cytoscape-style](https://github.com/reactome-pwp/PathwayBrowser/tree/main/projects/reactome-cytoscape-style), similar to SBGN-stylesheet, in order to use it for the new Reactome Pathway-Browser we are developing, but also in our new curator tool.

We need to go by the SBGN standards, but we would like to do so without compromising our newly developed visual identity

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
Is the requirement for your app that the stroke with of hollow arrows match the main line width, or do they need to vary?

The simplest option may be to expose another width prop for the arrows. Another option is an enum, with values like 'default' and 'match-line'. 

A hybrid approach would be to support both, i.e. custom px values or a special 'match-line' enum value.

**Comment by maxkfranz** [comment]
It looks like Ugur may be away. Let's move forward with the hybrid approach (px value or 'match-line' enum value). 

@EliotRagueneau, would you put up a PR of this approach?

These are relevant references:

https://github.com/cytoscape/cytoscape.js/blob/bcaf8339af709f6b973d1d38389f77f55da6b6a7/src/style/properties.js#L279

https://github.com/cytoscape/cytoscape.js/blob/bcaf8339af709f6b973d1d38389f77f55da6b6a7/src/extensions/renderer/canvas/drawing-edges.js#L271

**Comment by ugurdogrusoz** [comment]
Sorry, I missed this discussion and question. From SBGN's point of view, the width and other style (e.g., color) of glyphs and arcs do not matter. There might be applications where the size of the arrow might grow independent of the edge width but making them consistent should suffice I think.

**Comment by EliotRagueneau** [comment]
> It looks like Ugur may be away. Let's move forward with the hybrid approach (px value or 'match-line' enum value).
> 
> @EliotRagueneau, would you put up a PR of this approach?
> 
> These are relevant references:
> 
> https://github.com/cytoscape/cytoscape.js/blob/bcaf8339af709f6b973d1d38389f77f55da6b6a7/src/style/properties.js#L279
> 
> https://github.com/cytoscape/cytoscape.js/blob/bcaf8339af709f6b973d1d38389f77f55da6b6a7/src/extensions/renderer/canvas/drawing-edges.js#L271

I just did the PR, it is close enough to your standards.

@ugurdogrusoz  I made it so that by default it matches the line width, but then user can customise it as they wish, I think it should be okay :D
Regarding SBGN-style library, it shouldn't change the default appearance I believe, as in your case the edge lines are of width `1`.

**Comment by EliotRagueneau** [comment]
Hi @maxkfranz , I'm curious, what is the usual release cycle of Cytoscape? Like in how much time do you think this new feature will be added?

**Comment by maxkfranz** [comment]
Usually, a feature release is made during the first week of each month.  Typically, the milestones are tagged with expected release dates.
