### ISSUE TITLE
The img tag in README.md is non-valid HTML5

### ISSUE THREAD

**Issue by zuckschwerdt** [cytoscape/cytoscape.js#3192]
The HTML tag `<img>` is self-closing and in HTML5 the end-tag is not valid.

Compiling with e.g. Vite (via Vuepress) when including Mermaid as dependency (with in turn depends on cytoscape) errors with:
```
[vite:vue] Invalid end tag.
file: .../node_modules/cytoscape/index.html.vue:1:195
✖ Compiling with vite - failed
SyntaxError: Invalid end tag.
```

There are three occurrences in README.md that should be corrected.

_Note this is a fringe case and_ not critical _it only shows when choosing to compile docs with a strictly validating processor, which in my use-case is not default nor recommended._

**Comment by maxkfranz** [comment]
Needs to be cherry picked to unstable

**Comment by zuckschwerdt** [comment]
[CONTRIBUTING.md](https://github.com/cytoscape/cytoscape.js/blob/unstable/CONTRIBUTING.md#how-to-make-your-changes-in-a-pull-request) says
>  Bugfixes go in the master branch for the next bugfix/patch version

should I rebase to `unstable` though?

**Comment by maxkfranz** [comment]
Cherry-picked on unstable.  Closing
