### ISSUE TITLE
border-radius property for node shapes with rounded corners

### ISSUE THREAD

**Issue by EliotRagueneau** [cytoscape/cytoscape.js#3198]
**Description of new feature**

It would be really great if users could easily specify what is the border-radius of all the "rounded" node shapes.
Additionally, adding this property would enable effectively new shapes, such as the pill shape which is just a rounded rectangle with a corner radius of half the height

![corner-radius](https://github.com/cytoscape/cytoscape.js/assets/42945601/a7c00cf0-44cf-4eeb-b889-cd880b1c92d7)

**Motivation for new feature**

In the reactome-cytoscape-style library we're developing, we need bigger border-radius than the ones provided by default . 
At the moment we're using background-image svgs to do it, but that is extremely heavy for something that could just be a simple property of a shape, without impacting too much performances (I believe).   

We would like to boost our performances by using native shape renderers instead of custom SVGs

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by EliotRagueneau** [comment]
This is I guess somehow related to #1167 , but it never got through. 
In my context I don't care about parent nodes specifically, just nodes in general

**Comment by maxkfranz** [comment]
Adding initial thoughts while I'm online just now:  A large border radius on compound parent nodes would be troublesome.  The bounds of the parent are defined by the collective bounds of the descendants -- a rectangle.  A large border radius on a parent would allow a child to visually escape the bounds of the parent at the corners, possibly escaping entirely or possibly only overlapping the border.

For non-parent nodes, large border radii are probably without conflict.

Some initial options:

(1) Forbid custom border radii on parent nodes.
- Inexpensive to implement
- Consumers of the library can't make mistakes

(2) Allow custom border radii on parent nodes and put harsh warnings and mitigations in the documentation.
- Inexpensive to implement
- Consumers of the library can easily make mistakes
- One mitigation: Set a padding that's appropriate to the radius

(3) Implement more complex bounds checking on compound parents.
- Expensive to implement
- May not be practical to support properly in headless environments
- Would allow for more compound parent shapes, e.g. ellipses
- May significantly slow down compound graphs

If you have other options in mind, please list them in this issue's thread.

**Comment by EliotRagueneau** [comment]
In my opinion, option 2 seems like the best solution.
Specially if we set by default a padding equal to the border-radius, in which case it would dodge the issue. This combined with proper documentation of the impact of border-radius on the padding should be enough I assume

**Comment by mikekucera** [comment]
I agree that option 2 seems the best. If we forbid border-radius on compound nodes it might prevent mistakes, but it could just as easily lead to frustrated developers wondering why its not working on compounds. I agree about warnings in the documentation. The documentation should probably include an example of the selector that's needed to apply border-radius to only non-parent nodes.

Re. default padding for compound nodes... It won't affect any existing networks because border-radius would be a totally new property not used by any existing networks. Compound nodes already have a different default style from regular nodes, so it seems like it would be fine, unless I'm missing something. Although the padding would have to grow in relation to the border radius, so pill-shaped compound nodes might end up with a lot of padding, which might not look good. I'm on the fence about this.

**Comment by EliotRagueneau** [comment]
Personally, either solutions works fine as I won't be using border-radius for containers, so we could start with just warning in the documentation warnings, and maybe implement the auto margins in the next breaking changes release.

Are you waiting for an input from me, or further discussion with the rest of Cytoscape team to start tackling this issue? Should I create a PR for this?

**Comment by maxkfranz** [comment]
@EliotRagueneau, feel free to start your PR.  I agree that the fully-manual option is best to start.  Even if we decide to support the automatic enum value, or similar, we'd need to start with the fully-manual implementation anyway.

If anyone has further thoughts on the issue, feel free to post it here in the thread.

**Comment by EliotRagueneau** [comment]
Hi @maxkfranz , I have started working on this, and while I managed to create the property corener-radius property, testing it made me realise 2 things
1. I need to limit the corner radius so that it doesn't take more than half the distance between the previous and the next point, in order to avoid lines going back and forth
2. The current algorithm to create rounded polygons is not so great: it creates artifacts when the polygon is not regular, e.g.
<img width="725" alt="Screenshot 2023-12-13 at 21 01 35" src="https://github.com/cytoscape/cytoscape.js/assets/42945601/905f153a-18c1-471e-b0fd-86efbb63dc50">
I'm gonna try to improve that at the same time

**Comment by EliotRagueneau** [comment]
https://stackoverflow.com/a/56214413/11028828
This algorithm, though it is using quadratic curves instead of proper arcs, looks quite good to me, and is simpler to understand. 
<img width="665" alt="Screenshot 2023-12-13 at 21 21 39" src="https://github.com/cytoscape/cytoscape.js/assets/42945601/b15881ad-246c-41d9-ad59-7170a83e70b6">
The problems arrive with sharp corners though ...
<img width="670" alt="Screenshot 2023-12-13 at 21 22 49" src="https://github.com/cytoscape/cytoscape.js/assets/42945601/0673808a-d60a-4af5-b90c-6dbb4c6797b4">

**Comment by EliotRagueneau** [comment]
This algorithm https://stackoverflow.com/a/44856925/11028828 is closer to your previous one, and is producing great results in my opinion.
<img width="762" alt="Screenshot 2023-12-14 at 09 42 21" src="https://github.com/cytoscape/cytoscape.js/assets/42945601/09fe125b-a570-42d3-b50d-1738f0397c46">

<img width="600" alt="Screenshot 2023-12-14 at 09 43 45" src="https://github.com/cytoscape/cytoscape.js/assets/42945601/37f75bab-e94f-4514-b220-9f4cbe5240ac">

Should I go forward with this algorithm and try to optimise it is within Cytoscape context?
This also implies some modifications to the inersect-line algorithm, as well as to the checkPoint algorithms

**Comment by maxkfranz** [comment]
> This algorithm https://stackoverflow.com/a/44856925/11028828 is closer to your previous one, and is producing great results in my opinion. <img alt="Screenshot 2023-12-14 at 09 42 21" width="762" src="https://private-user-images.githubusercontent.com/42945601/290475567-09fe125b-a570-42d3-b50d-1738f0397c46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzI2OTcsIm5iZiI6MTcwMjU3MjM5NywicGF0aCI6Ii80Mjk0NTYwMS8yOTA0NzU1NjctMDlmZTEyNWItYTU3MC00MmQzLWI1MGQtMTczOGYwMzk3YzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE2NDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNDY0YmEwNjE2ZjI4Y2QyZTYyZDllOGMyZGIxNzRkZjM1YzhiMjE0YzlkODc4NGVmYTZiNDVkZTI3NmJhZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mV830fe52cWY9xUvPPYwDRQOVOu9i0ZRVqUCi3rib0w">
> 
> <img alt="Screenshot 2023-12-14 at 09 43 45" width="600" src="https://private-user-images.githubusercontent.com/42945601/290475997-37f75bab-e94f-4514-b220-9f4cbe5240ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NzI2OTcsIm5iZiI6MTcwMjU3MjM5NywicGF0aCI6Ii80Mjk0NTYwMS8yOTA0NzU5OTctMzdmNzViYWItZTk0Zi00NTE0LWIyMjAtOWY0Y2JlNTI0MGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE2NDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2Yzk4MDRhZmJmMThkMTczODg4MmUxZjFhNmY5YTYwMzMzOTZiN2NjMWIwMjQ3NzYzNjE3YTNjYmE3ZDUyZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N_ZEqVP8bYaI9reYNTqxPMlzbvJPfMXhbP01R36WSu0">

This is probably closer to what people would expect when they think of rounded corners.  This approach would be the same as the `border-radius` in CSS proper for rounded divs, so it sounds sensible.

> Should I go forward with this algorithm and try to optimise it is within Cytoscape context? This also implies some modifications to the inersect-line algorithm, as well as to the checkPoint algorithms

Sounds good

**Comment by EliotRagueneau** [comment]
I've figured out that I could reuse this strategy for #3201 so I'll probably do 1 PR with both new "round" aspects together.

Here's what it looks like when I apply the same roundness to each corner of an edge
<img width="594" alt="Screenshot 2023-12-15 at 12 04 48" src="https://github.com/cytoscape/cytoscape.js/assets/42945601/e284ddf7-b2a6-4d5f-8933-0380cabb1f19">

**Comment by EliotRagueneau** [comment]
Question regarding rounded rectangle: was there a reason why you didn't use  [canvas `roundRect() ` function](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/roundRect) b ut insteadd used your custom polygon function ?

**Comment by maxkfranz** [comment]
Canvas roundrect() is too new, and the lib supports legacy browsers. You'd need the manual implementation anyway as a polyfill.

**Comment by maxkfranz** [comment]
Pinned
