### ISSUE TITLE
Support edge line properties for node borders

### ISSUE THREAD

**Issue by EliotRagueneau** [cytoscape/cytoscape.js#3199]
**Description of new feature**

It would be awesome if we could apply the folowing list of edge-line properties on the node borders

- `width` ==> `border-width` **(already in place)**
- `line-color`  ==> `border-color` **(already in place)**
- `line-style` ==> `border-style` **(already in place)**
- `line-opacity` ==> `border-opacity` **(already in place)**
- `line-cap` ==> `border-cap`
- `line-dash-pattern` ==> `border-dash-pattern`
- `line-dash-offset` ==> `border-dash-offset`
- `line-fill` ==> `border-fill` (More difficult than the original one)
-  *not existing* ==> `border-position`  (*center*, `inside`, `outside`)

**Motivation for new feature**

In reactome-cytoscape-style, we have designed ndoes that should look like this

<img width="723" alt="Screenshot 2023-12-05 at 19 59 10" src="https://github.com/cytoscape/cytoscape.js/assets/42945601/7952c6bf-2277-49a2-a7ad-4c6da4484a08">

But the closest I can get border-wise is this 
![Screenshot 2023-12-05 at 19 59 55](https://github.com/cytoscape/cytoscape.js/assets/42945601/55daa0ba-8858-4f4f-82e4-bf5c0f85597d)

The `border-position` and `border-fill` are more complex to implement, so I don't have much expectation about them, but they would be nice.

Also in our specific case, we don't need the `border-fill`, but the `border-position` is definitely important to achieve the aspect as our mockup

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
Everything that is supported natively by canvas are clearly good things to support -- mostly overlapping with existing edge props.

> The border-position and border-fill are more complex to implement, so I don't have much expectation about them, but they would be nice.

These aren't supported by canvas natively, but they could be supported with more work.  Perhaps, these more complex items would be best saved for future.

What do you think, @EliotRagueneau?

**Comment by maxkfranz** [comment]
Note: The inner and outer borders may be pragmatic, to some degree, with the use of clipping.  Still, it would be more involved than the other features.

**Comment by EliotRagueneau** [comment]
> Everything that is supported natively by canvas are clearly good things to support -- mostly overlapping with existing edge props.
> 
> > The border-position and border-fill are more complex to implement, so I don't have much expectation about them, but they would be nice.
> 
> These aren't supported by canvas natively, but they could be supported with more work. Perhaps, these more complex items would be best saved for future.
> 
> What do you think, @EliotRagueneau?

Yes definetlly, the border-position can be border-fill could be added later on. For the inner and outer, as you said, it is relatively easy to do with clips, but that can also wait a bit .

**Comment by maxkfranz** [comment]
Sounds good
