### ISSUE TITLE
List extension : cytoscape-tidytree

### ISSUE THREAD

**Issue by chuckzel** [cytoscape/cytoscape.js#3204]
https://github.com/chuckzel/cytoscape-tidytree
A layout extension specifically for trees that allows for a non-layered layout.
demo: https://chuckzel.github.io/cytoscape-tidytree/tree-viewer/

**Comment by maxkfranz** [comment]
This is a solid layout.  Thanks for posting it.

It will be listed tomorrow with 3.28.1.

**Comment by chuckzel** [comment]
Is the list of demos listed on the documentation page restricted only to first-party demos? If I made a PR adding mine, would it get accepted?

**Comment by maxkfranz** [comment]
Great layout. Let’s add it
