### ISSUE TITLE
Provide methods to register node shapes

### ISSUE THREAD

**Issue by linghaoSu** [cytoscape/cytoscape.js#3209]
**Description of new feature**

It would be possible to expose `generatePolygon` and `generateRoundPolygon` to the user to register new node shapes, the current polygon is not very easy to use, and there is no way to customise node shapes with rounded corners if that is what is expected.

**Motivation for new feature**

For easy use of custom shapes and the ability to customise the shape of rounded corners

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
Usually, private functions don't get exposed in the API. Style should be through the stylesheet. 

Do you have specific suggestions on how to make custom polygon properties easier for your use case?
