### ISSUE TITLE
Improve quality of plugins

### ISSUE THREAD

**Issue by hoijui** [cytoscape/cytoscape.js#3211]
**Description of new feature**

request basic meta-data for Open Source plugins.

**Motivation for new feature**

I love what you did here with cytoscape, ride on!!! :-)
I would very much like to use it for browsing and editing RDF/OWL data. I found 4 plugins, 3 of this had neither sources nor binaries, and the third one has sources but without a license attached to it, and given it has seen no changes sine 111 years, it will stay so. effectively, this means: there is now nothing.
That is very sad.. a tragic loss of hundreds if not thousands of hours of lifetime. Would it not be possible to encourage some better hygiene when uploading a plugin? encourage to explicitly state the license, and to use a public git repo, if it is an open source plugin.

I bet there are better ways to go at this, but wanted to bring the issue up... in some way.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
Those are good suggestions, and to get the attention of the Cytoscape desktop app team, you should post your query here: https://cytoscape.org/bug-report.html

This repo is for [Cytoscape.js](https://js.cytoscape.org), not [Cytoscape](https://cytoscape.org).

**Comment by hoijui** [comment]
@maxkfranz Thanks!
I tried to do that before comming here, but when clicking the button on that page, nothing happens for me (and I do have javascript enabled), and the desktop repo here on github has issues disabled.

**Comment by maxkfranz** [comment]
Try disabling your ad-blocker or loosening your privacy restrictions.I think there’s a canned form from Jira on that page, and like everything else Jira, it’s flakey.On Jan 11, 2024, at 15:34, hoijui ***@***.***> wrote:﻿
@maxkfranz Thanks!
I tried to do that before comming here, but when clicking the button on that page, nothing happens for me (and I do have javascript enabled), and the desktop repo here on github has issues disabled.

**Comment by AlexanderPico** [comment]
Regarding the bug report tool, you might check to see if you have popups being blocked.
https://cytoscape.org/bug-report.html

If that's not it, then please provide more details about browser, version and what you see.

We reviewed your other suggests. We only do a basic review of apps. We find that most app authors are motivated to  present their app as best they can. If they are not, then I'd shy away from using the app...
