### ISSUE TITLE
Improve getting-started guide

### ISSUE THREAD

**Issue by hoijui** [cytoscape/cytoscape.js#3212]
**Description of new feature**

Make the getting-started guide more newb friendly.
Especially for non-JS devs, explaining all the JS dev world specific terms, abbreviations and project names, but also giving actually usable sample files, instead of only parts of instructions and ideas here and there, that need to be assembled correctly to get started.

**Motivation for new feature**

Allow more people to start using cytoscape.js, and more easily so.

**NOTE**
I plan to implement this mostly by myself in PRs.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [x] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [x] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [x] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [x] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
PR #3213 has been merged.  

Looking forward to your further suggestions.
