### ISSUE TITLE
Docs: Installation via Meteor/Atmosphere has npm code block

### ISSUE THREAD

**Issue by trueberryless** [cytoscape/cytoscape.js#3214]
Under "Getting started -> Including Cytoscape.js" is a section which explains how to install Cytoscape via Meteor/Atmosphere. However, the code block underneath shows the npm installation. I dont know if this is on purpose or just a typical copy + paste mistake:

![image](https://github.com/cytoscape/cytoscape.js/assets/99918022/261b2cbf-68b9-4504-95dd-82b421c33837)

**Comment by maxkfranz** [comment]
Meteor uses nom, unless they've changed yet again. If there's some new process, you're welcome to update that section in a PR.

**Comment by trueberryless** [comment]
Okay, sry, I didn't know that this was correct. I thought there might be another package manager. My mistake!

**Comment by maxkfranz** [comment]
No worries
