### ISSUE TITLE
Adding exports map in package.json

### ISSUE THREAD

**Issue by sidharthv96** [cytoscape/cytoscape.js#3218]
**Environment info**

- Cytoscape.js version : 3.28.1
- Browser/Node.js & version : node v20

**Current (buggy) behaviour**

When using `import cytoscape from 'cytoscape';` and bundling the code in a library, an regarding importing lodash is thrown during build. 

**Desired behaviour**

It should import the right bundle. This can be facilitated by adding an exports map. 

https://github.com/mermaid-js/mermaid/pull/5247/files#diff-f0ed092719ff4df1eac0ddfe6e5cf61e979cbd3bae566ed14cb579290735faa8

**Minimum steps to reproduce**

(I can create the STR if mandatory, I can raise the PR directly with the fix, as the patch provided above is working for us)

_What do you need to do to reproduce the issue?_

_Fork/clone this JSBin demo and reproduce your issue so that your issue can be addressed quickly and effectively:_
http://jsbin.com/fiqugiq

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by sidharthv96** [comment]
In the export map, using `"./dist/cytoscape.esm.js",` also throws similar error.

**Comment by maxkfranz** [comment]
Should be superseded by:

- #3221

**Comment by maxkfranz** [comment]
See:

- #3217
- [9bd7a73](https://github.com/cytoscape/cytoscape.js/commit/9bd7a73d59b64d52f5511bed7cd46aeb5804c8fb)

@sidharthv96, would you follow the steps in https://github.com/cytoscape/cytoscape.js/issues/3217#issuecomment-1955179947 to confirm that the exports map works in your project?

**Comment by maxkfranz** [comment]
You need to make a build of Cytoscape. UMD really shouldn’t be used for import.

**Comment by maxkfranz** [comment]
I've updated the `dist` files on the unstable branch: https://github.com/cytoscape/cytoscape.js/blob/4372a14065ed26aa781f3b563d5907b9fee80054/dist/cytoscape.esm.js

That should make your testing a bit simpler.  You can verify that the ESM file linked above doesn't use any `import` statements whatsoever.

Steps:

0. `git checkout git@github.com:cytoscape/cytoscape.js.git`
1. `cd cytoscape.js`
2. `git checkout unstable && git pull`
5. `npm link`
6. `cd ../my-app`
7. `npm link cytoscape`
8. `npm run watch` or `npm run dev` or `npm run build` -- however you do it
9. Verify your app builds and works

**Comment by sidharthv96** [comment]
@maxkfranz tried it. Didn't work. I forgot to update here then. Will rerun and add the logs.

**Comment by maxkfranz** [comment]
@sidharthv96 

All of the builds on unstable currently have no external dependencies, including CJS now.  There is nothing listed under [`package.json > dependencies`](https://github.com/cytoscape/cytoscape.js/blob/unstable/package.json) anymore, either.  If linking to the unstable branch doesn't work with [the testing steps](https://github.com/cytoscape/cytoscape.js/issues/3218#issuecomment-1966710467), then I suspect that something is off with your build config -- or the `npm link` step.

You'll need to delete your patch file in Mermaid to test the steps.

**Comment by sidharthv96** [comment]
@maxkfranz it's working perfectly now! Thank you!

We also moved to using esbuild as well. 

![image](https://github.com/cytoscape/cytoscape.js/assets/10703445/f0cd93da-0ffc-4f34-b383-c790892bfab9)

Now, one of our major concern is the size. I'll try to see if there are any low hanging fruits related to tree shaking available in cytoscape.

**Comment by maxkfranz** [comment]
> @maxkfranz it's working perfectly now! Thank you!

Great

> 
> We also moved to using esbuild as well.

Also great

> 
> ![image](https://private-user-images.githubusercontent.com/10703445/311259246-f0cd93da-0ffc-4f34-b383-c790892bfab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MTEwMzMsIm5iZiI6MTcwOTkxMDczMywicGF0aCI6Ii8xMDcwMzQ0NS8zMTEyNTkyNDYtZjBjZDkzZGEtMGZmYy00ZjM0LWIzODMtYzc5MDg5MmJmYWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE1MTIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYTA2NDA5NTliNTQxNWVhN2QzMjBiMzViMjQxMzljMjgwMGRkNTIzMDgwOTE2MWM1MTEyMDE1YTcwMDM1ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sxE_qoJ-gYArX4t7wupcA34ZKK9osS21908af2GOQ-E)
> 
> Now, one of our major concern is the size. I'll try to see if there are any low hanging fruits related to tree shaking available in cytoscape.

Cytoscape does a lot.  I has basically a full-blown CSS parser, a renderer, several layouts, etc.  There's a lot there.

This probably couldn't be changed that much in the current v3 line in the main builds.  Possibly in v4.  It would probably require some significant API changes re. extensions.

For your case, you're welcome to add a Rollup build config to the Cytoscape repo that's smaller, if you like.  It could exclude things like the canvas renderer if you're just using it headlessly for the model and layouts.  Something like 'cytoscape.headless.esm.js'.
