### ISSUE TITLE
Compound node padding style not working as expected

### ISSUE THREAD

**Issue by KasperAanstoot** [cytoscape/cytoscape.js#3224]
**Environment info**

- Cytoscape.js version : 3.28.1
- Browser version :  Chrome 121.0.6167.185 (Official Build) (64-bit)

**Current (buggy) behaviour**

In my stylesheet I use the following rules for a compound node (selector: $node > node):
'padding-top': '20px',
'padding-left': '5px',
'padding-right': '5px',
'padding-bottom': '5px',

The result is a padding of '5px' for top, left, right and bottom.

**Desired behaviour**

Set the the padding for top to '20px' and the others to '5px' according to the stylesheet. 

**Minimum steps to reproduce**

https://jsbin.com/bisocidilu/1/edit?html,css,js,output

**Comment by maxkfranz** [comment]
The documentation shows only one `padding` property for all sides, here: https://js.cytoscape.org/#style/node-body

Where did you see a reference to multiple properties?

**Comment by KasperAanstoot** [comment]
Eles.style() shows multiple properties so I thought it would be possible to set them in the stylesheet. I also tried setting padding to "20px, 5px, 5px, 5px" :-)

**Comment by maxkfranz** [comment]
Then someone made a mistake in the community-maintained type definitions on DefinitelyTyped.

You're welcome to put up a pull request on DefinitelyTyped if you'd like to revise it.

**Comment by maxkfranz** [comment]
See also https://github.com/cytoscape/cytoscape.js/issues/3166
