### ISSUE TITLE
Video support for background-image

### ISSUE THREAD

**Issue by EliotRagueneau** [cytoscape/cytoscape.js#3225]
**Description of new feature**

We want to include videos (ideally of webm format) on node backgrounds.
Ideally, we should grant control on how to play / pause them, e.g. on hover

**Motivation for new feature**

Supporting videos would allow many rendering, like 3D structure of Proteins, within protein nodes. We plan to use it in our new Reactome Pathway Browser.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by EliotRagueneau** [comment]
Something like https://stackoverflow.com/questions/4429440/html5-display-video-inside-canvas could be done I think

**Comment by maxkfranz** [comment]
There's always going to be far better performance and feature support by using the native `<video>` within the browser instead.  

This would be great as an extension that creates `<video>`s as layers below or above the nodes.  Or it may make sense to leverage an existing extension, such as:

- https://github.com/sgratzl/cytoscape.js-layers
- https://github.com/BradyDouthit/cytoscape-html
- https://github.com/mwri/cytoscape-dom-node
- https://github.com/classcraft/cytoscape.js-canvas (if you really want a canvas for some reason)
- https://github.com/cytoscape/cytoscape.js-popper

**Comment by EliotRagueneau** [comment]
That sounds like an excellent idea, we'll try those extensions before trying to implement our own, thanks a lot for the advice!

**Comment by EliotRagueneau** [comment]
https://github.com/sgratzl/cytoscape.js-layers does an excellent job for videos, thanks a lot for the recommendation!
