### ISSUE TITLE
'background-image' with REST service image response

### ISSUE THREAD

**Issue by kozo2** [cytoscape/cytoscape.js#3226]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._

The current Cytoscape.js does not display images on nodes when given the response of a REST service that returns an image (as the value for `background-image`).

- The demo: https://kozo2.github.io/cytoscape.js/demos/images-breadthfirst-layout/
- The source code: https://github.com/kozo2/cytoscape.js/blob/gh-pages/demos/images-breadthfirst-layout/code.js#L37
- The image that should be mapped: https://rest.kegg.jp/get/hsa00600/image

Is it possible to display an image returned by a REST service on a node in Cytoscape.js?

**Motivation for new feature**

_Describe your use case for this new feature._

With the packages that convert Python or R code into REST services, such as [FastAPI](https://fastapi.tiangolo.com/) or [plumber](https://github.com/rstudio/plumber), the construction of systems that map complex graphics as node graphics can be mentioned as a use case.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by maxkfranz** [comment]
> Is it possible to display an image returned by a REST service on a node in Cytoscape.js?

Yes.  The response must be correct, including the headers etc.

**Comment by kozo2** [comment]
Thank you for the information, @maxkfranz .
However, I think the header is present in the response from https://rest.kegg.jp/get/hsa00600/image .
I used a tool called Postman to check the headers.

![image](https://github.com/cytoscape/cytoscape.js/assets/12192/9134b5ad-6de2-4f28-9941-166ad57cba22)

If you think there might be any missing headers, could you please let me know which ones you believe are lacking?

**Comment by Myxogastria0808** [comment]
As far as I can see the image [( this image )](https://private-user-images.githubusercontent.com/12192/310578203-9134b5ad-6de2-4f28-9941-166ad57cba22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NTIwOTEsIm5iZiI6MTcwOTc1MTc5MSwicGF0aCI6Ii8xMjE5Mi8zMTA1NzgyMDMtOTEzNGI1YWQtNmRlMi00ZjI4LTk5NDEtMTY2YWQ1N2NiYTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE5MDMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYjg2OWY4ZjY4ZDkwY2Q0Y2U0YjZhYjZjZDUyMTQwNTdiYjE2NWVlNmRjMmNhYjlkNDZiNjM2YmM4MzRmZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dK-my-EFj6g7lyAo-sA3-VmKBYLTacRnmqT3vmR-HR4), I can`t see the Access-Control-Allow-Origin setting.
Unless the Access-Control-Allow-Origin value is appropriate (in this case, appropriate means that the Access-Control-Allow-Origin allows the URL of demo site), I seem that a image cannot be retrieved and displayed.

I am sorry that my English is so bad. I'm glad if it helped you in some way.

**Comment by kozo2** [comment]
@maxkfranz 

@Myxogastria0808 and I identified the missing information in my test.
For example, by writing https://github.com/kozo2/rest4cyjs/blob/main/backend/plumber.R#L14-L28 , 
we properly configured the response for a REST service with R plumber.
Cytoscape.js sucessfully displayed the image obtained from the REST service.
![image (5)](https://github.com/cytoscape/cytoscape.js/assets/12192/5b1c59e4-a841-4085-ad50-adaf152a3cc8)

I will close this issue. 🙏

**Comment by maxkfranz** [comment]
Thanks for posting the solution.  I'm sure others will make use of it.
