### ISSUE TITLE
beginPath(), lineTo()…, endPath()

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#3227]
**Environment info**

- Cytoscape.js version : 3.28.1
- Browser/Node.js & version : TBD 

**Current (buggy) behaviour**

_What does the bug do?_

There is a malformed combination of the path functions with `lineTo()`.

**Desired behaviour**

_What do you expect Cytoscape.js to do instead?_

The use of the path functions should be correct.

**Minimum steps to reproduce**

_What do you need to do to reproduce the issue?_

_Fork/clone this JSBin demo and reproduce your issue so that your issue can be addressed quickly and effectively:_
http://jsbin.com/fiqugiq

More details TBD.  @mikekucera has more information about this.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by maxkfranz** [comment]
@mikekucera, this is stubbed out for the issue that you mentioned.

**Comment by mikekucera** [comment]
Thanks.

My understanding is that when drawing a polygon  it should start by calling beginPath(), the next call should be moveTo(), followed by subsequent calls to lineTo(), then endPath().

Here's an example of this being done correctly: https://github.com/cytoscape/cytoscape.js/blob/unstable/src/extensions/renderer/canvas/drawing-shapes.js#L7-L22

But here it calls beginPath() then immediately calls lineTo(). The canvas API seems to be lenient enough to allow this and treat it as a moveTo(). However pdfkit doesn't like it and nothing is drawn.
https://github.com/cytoscape/cytoscape.js/blob/unstable/src/extensions/renderer/canvas/arrow-shapes.js#L5-L11

I don't know yet if there are more examples of this in cy.js.

This is a minor issue as I've been able to work around it so far.

**Comment by maxkfranz** [comment]
Even some of the arrow shapes with a `moveTo` are wrong.  `circleTriangle`, for example, does a `moveTo` and then a `lineTo` the same, first point.

It should be more like:

```
moveTo(pt[0])
// then
for (let i = 1; i < pts.length; i++) {
  lineTo(pts[i])
}
```
