### ISSUE TITLE
Extensive testing on a Windows tablet

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#323]
There may be some unintended incompatibilities, because Windows tablet supports both touch and mouse-based interactions simultaneously.  The renderer handles those cases well separately thus far, but more testing is required to see how well it works in the intersection case (mouse & touch).

**Comment by maxkfranz** [comment]
Added a compatibility layer for events; needs more testing

**Comment by maxkfranz** [comment]
Touch works well on Surface / Win10 / Chrome

**Comment by maxkfranz** [comment]
There seem to be some preset gestures on Surface / Win10 / Firefox

**Comment by maxkfranz** [comment]
Firefox has weird behaviour on Windows/Surface.  It seems `wheel` events are generated for vertical swipes, making panning very frustrating.  

Ref to Bugzilla : https://bugzilla.mozilla.org/show_bug.cgi?id=1214368

Hopefully, the Firefox guys address this.  As it stands now, I'd have to recommend Chrome over Firefox for Windows touch devices as it seems to have proper touch support.

**Comment by maxkfranz** [comment]
Firefox issue : 

![ff-touch-win-surface](https://cloud.githubusercontent.com/assets/989043/10466931/105ec90e-71c5-11e5-83de-d7a4c499e4cb.gif)

**Comment by maxkfranz** [comment]
Edge/IE working OK but edges don't seem to be tappable

**Comment by maxkfranz** [comment]
Edge/IE now working just as well as Chrome w.r.t. touch

**Comment by simonsarris** [comment]
This bug is closed but still an issue with Firefox, correct?

**Comment by maxkfranz** [comment]
Correct.  I've filed an issue with Bugzilla, but there's nothing I can do on the Cytoscape.js side to fix Firefox's behaviour.
