### ISSUE TITLE
Stop animation 

### ISSUE THREAD

**Issue by timscorbett** [cytoscape/cytoscape.js#3231]
Reported here
https://stackoverflow.com/questions/78130411/react-cytoscape-js-stop-animation

I forked an existing Cytoscape example to test playing and stopping an animation. Playing the animation works on "Add node" button, but stopping it fails to stop the animation without any error in the "Add relationship" button.

You will see an alert followed by

mySubCyRef.stop();
cy.current.stop();
https://codesandbox.io/p/sandbox/react-cytoscape-forked-jc6yky

What would work to stop all animations

(1) without resetting the layout
(2) maintaining the same styles as before the animation started?

**Comment by d2fong** [comment]
Hi @timscorbett.   I apologize for the cytoscape.js team's response to this issue.  I will be working with you to help resolve it.

As a starting point, I need more clarity in how to reproduce your issue. 

These are the first steps I think you are describing, can you correct me if I am wrong?

1. Open your sandbox link
2. Click the add node button


What should I do after that?

**Comment by mikekucera** [comment]
I can't reproduce the issue with the example. Clicking "Add Relationship" stops the animation as expected.

If this issue continues to be a problem for you please reopen this bug with more details on how to reproduce the issue reliably.

Thank you.
