### ISSUE TITLE
Event with namespace specified not triggering

### ISSUE THREAD

**Issue by Ciappone** [cytoscape/cytoscape.js#3237]
- Cytoscape.js version : 3.20.0 ( tested with 3.28.1 too )
- Browser/Node.js & version : Google Chrome v. 123.0.6312.122 / Mozilla Firefox v. 124.0.2

**Current (buggy) behaviour**

If I assign an event ( "select" in this case ) with a namespace specified the event doesn't trigger or the Event object's property "namespace" is null

**Desired behaviour**

The event should trigger normally and have the Event object's property "namespace" valorized with the one assigned

**Minimum steps to reproduce**

I tried assigning the event in two ways: 

- first: in this case the event doesn't trigger
```javascript
 cy.on("select.test","node",(evt) => {
    document.getElementById("log").innerHTML += "Node selected with namespace: " + evt.namespace+"<br />";
  });
``` 

- second: in this case the event trigger but the namespace is null
```javascript
 cy.on("select","node",(evt) => {
    document.getElementById("log").innerHTML += "Node selected with namespace: " + evt.namespace+"<br />";
  },'test');
``` 

I'll add a JSBin where you can see the problem
[JSBin](https://jsbin.com/honokiy/edit?js,output)

**Comment by Ciappone** [comment]
> Both listeners and events can provide a namespace. When the listener specifies a namespace it will only run if the event has the same namespace.

I opened this issue as a bug because Cytoscape namespaces documentation* say that the behaviour is similar to JQuery's
[*Cytoscape.js documentation link](https://js.cytoscape.org/#events/event-object)

The main use of event namespaces in JQuery is being able to give a identifier to one or more event handlers and simplify removing or triggering the events.

I report an example in JQuery's namespace behaviour, below I report the [JQuery documentation's link](https://api.jquery.com/on/)

```javascript
$('selector').on("click", ()=>{ console.log("neutral") });
$('selector').on("click.custom", ()=>{ console.log("first custom") });
$('selector').on("click.custom", ()=>{ console.log("second custom") });
```
and
```javascript
$('selector').off("click.custom");
```

if Cytoscape namespaces behaved like JQuery, the events should work in this way:
for example if I assign three handlers:
```javascript
cy.on("select", ()=>{ console.log("neutral") });
cy.on("select.custom", ()=>{ console.log("first custom") });
cy.on("select.custom", ()=>{ console.log("second custom") });
```
Selecting a cytoscape node should now fire all of these handlers, and the console result should be:
`neutral, first custom, second custom`

by assigning namespaces I can now remove "custom" handlers by doing:
```javascript
cy.removeListener("select.custom");
```
after the remove, you only fire the "neutral" select handler.

As Cytoscape documentation says: the behaviour of Cytoscape's namespace should be similar to JQuery's.

Is there a chance that Cytoscape's behaviour will follow JQuery's logic?

Thanks for your time, I hope to hear from you soon.

**Comment by mikekucera** [comment]
The documentation only says that the event objects that are passed to handler callbacks are similar to JQuery event objects in that they wrap native event objects. It does not say that the behaviour of Cytoscape's namespaces are similar to JQuery.

There are no plans to change the behaviour of event handling in cytoscape.js at the moment.
