### ISSUE TITLE
Requestion: shape of node 

### ISSUE THREAD

**Issue by yealicjswo** [cytoscape/cytoscape.js#3238]
**Description of new feature**

_What should the new feature do?  For visual features, include an image/mockup of the expected output._
 I want to shape a node like a tornado, where multiple edges are added at once to form the shape.(inside red square)
<img width="589" alt="Screen Shot 2024-04-18 at 9 43 08 AM" src="https://github.com/cytoscape/cytoscape.js/assets/80077503/42511ba3-03b3-42c5-93f3-a6bb0ceb5f51">

**Motivation for new feature**

_Describe your use case for this new feature._
I've done the graph visualization guideline for applying into our company's prodicts(graph moedling, analysis/ ETL) or sharing the guide with parterns.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [o] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [o] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [o] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [o] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by mikekucera** [comment]
You can create your own polygon node shapes using the `"shape":"polygon"` and `"shape-polygon-points":[...]` style properties. More details are in the docs here: https://js.cytoscape.org/#style/node-body

**Comment by yealicjswo** [comment]
@mikekucera thanks! will try it.
