### ISSUE TITLE
Dist folder files is not covered in package.json `exports` field

### ISSUE THREAD

**Issue by odeadglaz** [cytoscape/cytoscape.js#3239]
**Environment info**

- Cytoscape.js version : 3.29.0
- Node.js & version : any Node version that supports `exports` field

**Current (buggy) behaviour**

In the current behaviour, this package was added an `exports` field to its package.json which doesn't cover all the `dist` folder consumble outputs.

**Desired behaviour**

I would be able to directly consume any dist file e.g
```
require('cytoscape/dist/cytoscape.umd')
```

**Minimum steps to reproduce**

Use the latest version and have this simple test file:
```
const test = require('cytoscape'); // works

console.log(test);

const testFail = require('cytoscape/dist/cytoscape.umd'); // Fails

console.log(testFail);
```

<img width="1419" alt="image" src="https://github.com/cytoscape/cytoscape.js/assets/49120070/290aaf40-7edd-4400-8b41-6956420bf1bd">

I would expect anything I can consume would be covered over the `exports` field 👍 

For example the following condition would be sufficient -> 
```
    "./dist/*": {
      "import": "./dist/*.js",
      "require": "./dist/*.js"
    }
```

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by cmfadib** [comment]
can confirm this bug, got this error with 3.29.0 - `./node_modules/mermaid/dist/mindmap-definition-44684416.js:4:0-56 - Error: Module not found: Error: Package path
./dist/cytoscape.umd.js is not exported from package`

**Comment by 317brian** [comment]
We're running into a similar issue trying to build/deploy Docusaurus on AWS Amplify:

```
Module not found: Error: Package path ./dist/cytoscape.umd.js is not exported from package /codebuild/output/.../node_modules/cytoscape (see exports field in /codebuild/output/.../node_modules/cytoscape/package.json)
```

**Comment by mikekucera** [comment]
3.29.1 has been released, please let me know if it resolves your issues

**Comment by jan-molak** [comment]
@mikekucera - thanks for looking into this. With `3.29.1`, I'm still getting the following error:
```
Module not found: Error: Can't resolve 'cytoscape/dist/cytoscape.umd.js'  in '/path-to-project/node_modules/mermaid/dist'
```

**Comment by mikekucera** [comment]
Hi @jan-molak
Thank you for the feedback. Max is currently not available to manage the cytoscape.js project like he normally does. I'm managing the release process in the meantime. I apologize, I have very little experience with javascript build systems. I don't know why Mermaid needs to patch cytoscape.js, but it looks like they are patching the exports. Perhaps the latest changes to the exports in 3.29.1 will obviate the need to do that?

**Comment by jan-molak** [comment]
@mikekucera - thanks for getting back to me. No worries, JavaScript build systems are anything but intuitive :-) 

I proposed a fix in https://github.com/cytoscape/cytoscape.js/pull/3241

I believe the issue is caused by Mermaid requiring Cytoscape using:
```
import cytoscape from "cytoscape/dist/cytoscape.umd.js";
```
But Cytoscape defines exports as:
```
    "./dist/*": {
      "import": "./dist/*.js",
      "require": "./dist/*.js"
```
and so:
```
import cytoscape from "cytoscape/dist/cytoscape.umd.js"
```
is translated to:
```
"cytoscape/dist/cytoscape.umd.js.js"
```

Another possible fix could be to drop `.js` from `./dist/*` exports, like so:
```diff
    "./dist/*": {
-      "import": "./dist/*.js",
+      "import": "./dist/*",
-      "require": "./dist/*.js"
+      "require": "./dist/*",      
```
However, this alternative approach may or may not have a negative effect on other consumers of Cytoscape, so perhaps you'd like to review https://github.com/cytoscape/cytoscape.js/pull/3241 as a temporary solution, and the more general solution upon Max's return?

**Comment by silverwind** [comment]
Adding @sidharthv96 regarding those patches in mermaid, hopefully they can be removed after this is resolved.

**Comment by mikekucera** [comment]
3.29.2 has been released, please let me know if it resolves your issues

This issue was auto-closed by the commit in the PR. If there are any further issues please reopen.

**Comment by jan-molak** [comment]
3.29.2 works well, thanks @mikekucera 🚀
