### ISSUE TITLE
Add 'cytoscape-node-edge-html-label' to list of UI extensions

### ISSUE THREAD

**Issue by laikmokashi** [cytoscape/cytoscape.js#3245]
**Description of new feature**

_New feature provide you freedom to create an html and positioned it on any place on edge or on node._

**Motivation for new feature**

_having HTML on edge and on node can provide better ui and similarly can provide better understanding of overall structure. It also help you with having adding events on nodes and lables_
![image](https://github.com/cytoscape/cytoscape.js/assets/87846071/a146a0b4-6d7d-4e47-ae08-06440f34050a)

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has adequately described their idea.  If not, elicit more information about the use case.  You should iteratively build a spec together.
- [ ] Ensure that the issue is a good fit for the core library.  Some things are best done in extensions (e.g. UI-related features that aren't style-related).  Some things are best done by app authors themselves -- instead of in Cytoscape libraries.
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the `unstable` branch via pull request.  The corresponding pull request is cross-referenced.

**Comment by mikekucera** [comment]
Take a look at the cytoscape-layers extension.

https://www.npmjs.com/package/cytoscape-layers

**Comment by laikmokashi** [comment]
@mikekucera  Sorry i am new to open source contribution but can you help me with which UI extension exactly help me to render html on edges rather than just a labeled text. I have seen it is available for nodes but i didn't get anything for edges , hence i have created new Ui library with the help of node-html-label .

url : https://www.npmjs.com/package/cytoscape-node-edge-html-label
sample project : https://github.com/laikmokashi/cytoscape-node-edge-html-lable-example

can you please have a look on it and tell me if we can add it in UI extensions , because i have faced lots of issue to achieve that functionality in my project

**Comment by mikekucera** [comment]
Sorry, I'm not sure what you're asking for. Did you create a new extension or did you modify an existing extension? The repository link on the NPM page is broken so I'm not sure. 

HTML is outside of the scope of cytoscape.js itself, and is best done in an extension. If you have a new extension we can add it to the list of extensions in the docs. But if its a copy of an existing extension (node-html-label?) with modifications then the new functionality should probably be a PR contribution to that extension's repository.

**Comment by laikmokashi** [comment]
yes i have used source code of node-html-lable only but with this fuctionality i thinks it can act as an complete new library because lot many changes are done for that.
what should i do then ? should i add PR contribution or it should add as an new extention only?

**Comment by mikekucera** [comment]
Ideally this should be a modification to node-html-label. However it doesn't look like that repository is being actively maintained, so that might not be an option. If you want I can add this new extension to the list of UI extensions in the docs.

**Comment by laikmokashi** [comment]
Allow me some time i will test all scenario again and will create better project so people can get better idea to use it. 
Thank You . 
Once done can i connect you on this thread only ?

**Comment by laikmokashi** [comment]
Hello @mikekucera 
I have tested the code for extension and also created demo on it. i have published the demo which is visible to everyone.
can you please have a look on it once and if all looks good to you please add this package in UI extension in docs.
npm link :https://www.npmjs.com/package/cytoscape-node-edge-html-label.

please let me know if anything from my side is needed.

Thanks

**Comment by mikekucera** [comment]
Ok I'll take a look soon. Thanks.

**Comment by maxkfranz** [comment]
@laikmokashi, would you link to the github repo?

**Comment by laikmokashi** [comment]
@maxkfranz  where do i need to link it ? Can you please help me with it

**Comment by maxkfranz** [comment]
The link of your github repo with the extension itself
________________________________

**Comment by laikmokashi** [comment]
@maxkfranz  please let me know if anything else is needed
NPM link : https://www.npmjs.com/package/cytoscape-node-edge-html-label
github link extention : https://github.com/laikmokashi/cytoscape-node-edge-html-label
github link example : https://github.com/laikmokashi/cytoscape-node-edge-html-lable-example
Live Demo : https://laikmokashi.github.io/cytoscape-node-edge-html-lable-example/

**Comment by maxkfranz** [comment]
@laikmokashi

This link gives a 404: https://github.com/laikmokashi/cytoscape-node-edge-html-label

**Comment by laikmokashi** [comment]
@maxkfranz  Sorry for that , It was private previously. I have made it public now. I hope you will be able to open that repo now .

Thanks

**Comment by laikmokashi** [comment]
Hi @maxkfranz @mikekucera  is there any update on this ? is there any issue ?

**Comment by mikekucera** [comment]
I've added your extension to the list of extensions in the documentation. It will show up when we release the next version of cytoscape.js. Sorry for the wait. Thank you.
