### ISSUE TITLE
Preset layout with predictable Taxi edges

### ISSUE THREAD

**Issue by UBarodzich** [cytoscape/cytoscape.js#3256]
Is it possible to achieve this result when all nodes are in one column, all connections are on the left side?
**Expected result:** 
<img width="726" alt="image" src="https://github.com/cytoscape/cytoscape.js/assets/148215467/3b91d034-0020-43c6-9de4-5e6cbf12b3bb">

I use "preset" layout with 'taxi' edges

**Current behavior:**
`selector: 'edge',
    style: {
      "curve-style": "taxi"
    }
`
<img width="462" alt="image" src="https://github.com/cytoscape/cytoscape.js/assets/148215467/ef6f7de8-8125-4d27-9c1a-df04366b3b72">

or 
`selector: 'edge',
    style: {
      "curve-style": "taxi",
      'taxi-direction': 'horizontal',
      'source-endpoint': '-50% 0%',
      'target-endpoint': '-50% 0%',
      'taxi-turn-min-distance': '100px',
      "taxi-turn": '100px',`

<img width="407" alt="image" src="https://github.com/cytoscape/cytoscape.js/assets/148215467/b0a781d0-7164-43a6-b429-c10fe1afa289">

**Comment by maxkfranz** [comment]
That style block doesn't make sense.  Try taking a look through the documentation again and experimenting with the properties a bit more.
