### ISSUE TITLE
Many of the demo networks are broken

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/cytoscape.js#3257]
**Current (buggy) behaviour**

Some of the demo networks on js.cytoscape.org are just blank.
This error appears in the console 
```
code.js:6 Uncaught ReferenceError: cytoscape is not defined
    at code.js:6:3
    at code.js:17:3
```

**Minimum steps to reproduce**

Go here:
https://js.cytoscape.org/#demos

These are the networks that are broken:
https://js.cytoscape.org/demos/colajs-graph/
https://js.cytoscape.org/demos/tokyo-railways/
https://js.cytoscape.org/demos/circle-layout/
https://js.cytoscape.org/demos/concentric-layout/
https://js.cytoscape.org/demos/grid-layout/
https://js.cytoscape.org/demos/cose-layout/
https://js.cytoscape.org/demos/images-breadthfirst-layout/
https://js.cytoscape.org/demos/animated-bfs/
https://js.cytoscape.org/demos/node-types/
https://js.cytoscape.org/demos/edge-types/
https://js.cytoscape.org/demos/radius-types/
https://js.cytoscape.org/demos/edge-arrows/
https://js.cytoscape.org/demos/labels/
https://js.cytoscape.org/demos/compound-nodes/
https://js.cytoscape.org/demos/linkout-example/

Also this one gives a 404, which is probably not releated but worth mentioning:
https://ivis-at-bilkent.github.io/cytoscape.js-cise/demo.html

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by mikekucera** [comment]
Can't reproduce this locally from the master branch. Maybe its related to #3255?

**Comment by maxkfranz** [comment]
Yes, likely related
