### ISSUE TITLE
3.30.1 breaks cytoscape.js-context-menus (& cxttap generally)

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js#3262]
**Environment info**

- Cytoscape.js version : 3.30.1
- Browser/Node.js & version : Firefox Developer Edition 129.0b9

**Current (buggy) behaviour**

When there is a certain amount of visible nodes (more than 100 it seems), [iVis-at-Bilkent/cytoscape.js-context-menus](https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus) stops triggering after a while.
This does not occur with Cytoscape.js version 3.30.0, only with 3.30.1 (I went back and forth several times).

**Desired behaviour**

The context menu should open on context menu click (left mouse button for right handed people) as with 3.30.0.

**Minimum steps to reproduce**

_What do you need to do to reproduce the issue?_

Go to <https://jsbin.com/wujijot/edit?html,js,output> and click on the gray circles with the secondary mouse button.
The menu either does not open or stops after a while of clicking.
However when you change cytoscape in the HTML view from 3.30.1 to 3.30.0 it always works.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by maxkfranz** [comment]
3.30.0 failed to be published.  Whatever build you use for `cytoscape@3.30.0` from npm will be no good.

Would you compare 3.30.1 to 3.29.3?

**Comment by maxkfranz** [comment]
Ref: #3255

**Comment by KonradHoeffner** [comment]
@maxkfranz:

* 3.30.1 breaks
* "3.30.0" works
* 3.29.3 breaks
* 3.29.2 works

**Comment by maxkfranz** [comment]
So [3.29.3](https://github.com/cytoscape/cytoscape.js/milestone/251?closed=1) introduces your issue.

Likely related: 

- https://github.com/cytoscape/cytoscape.js/issues/3005

@ugurdogrusoz, who is currently maintaining  cytoscape.js-context-menus?  Could they comment re. #3005?

**Comment by hasanbalci** [comment]
@maxkfranz I think this issue is not related to context-menus extension, but Cytoscape.js. See this [jsbin](https://jsbin.com/socefedaye/edit?html,js,console,output). I added a right-click event to the node. If I initially right click on the node it prints in the console. However, when I click somewhere in the canvas and then right click to node, it stops printing.

**Comment by maxkfranz** [comment]
Prospective fix in PR #3263

**Comment by maxkfranz** [comment]
Fix validated in #3263

**Comment by maxkfranz** [comment]
The fix will be published today (with PR #3263).
