### ISSUE TITLE
Bounding box for nodes recalculated when already cached

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/cytoscape.js#3264]
**Before you post**

This line of code in the cachedBoundBoxImpl function has a logic issue...
https://github.com/cytoscape/cytoscape.js/blob/unstable/src/collection/dimensions/bounds.js#L816

`let needRecalc = !useCache || isDirty(ele) || (isEdge && isDirty(ele.source()) || isDirty(ele.target()));`

An extra set of parenthesis are needed around the `isDirty(ele.source()) || isDirty(ele.target())` part.

If `isEdge` is false it sort circuits the first call to `isDirty(ele.source())`, however the second call `isDirty(ele.target())` still happens, and since the element is a node and has no target the isDirty function returns true and `needRecalc` is always true.

I'm getting a 5fps improvement when panning a 3000 node network in the webgl renderer with this fixed.

**Environment info**

- Cytoscape.js version :
- Browser/Node.js & version :

Chrome, on M1 macbook pro.

**Current (buggy) behaviour**

_What does the bug do?_

Performance issue, eats up about 12ms per frame on 3000 node network on my machine.

**Desired behaviour**

_What do you expect Cytoscape.js to do instead?_

Not recalculate bounding boxes when they are already cached.

**Minimum steps to reproduce**

_What do you need to do to reproduce the issue?_

Nothing, its always happening.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by maxkfranz** [comment]
Good catch

**Comment by AlexanderPico** [comment]
thanks, @mikekucera
