### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.touches[1].clientX'

### ISSUE THREAD

**Issue by UBarodzich** [cytoscape/cytoscape.js#3269]
**Environment info**

- Cytoscape.js version : ^3.30.0
- Browser/Node.js & version : Chrome/Safari , node: 20.5.1

**Current (buggy) behaviour**

_What does the bug do?_

on an iPad or a laptop with a touch screen, make zoom in/out, make other actions like move to the left/right , after that I receive the following error:

<img width="1658" alt="image" src="https://github.com/user-attachments/assets/07e8db20-4e38-49bd-bad3-c62a4b5edad6">

**Minimum steps to reproduce**

_What do you need to do to reproduce the issue?_

Make primitive actions like zoom and move graph to the left/right, maybe hide from viewport using tablet or  laptop with a touch screen

From external libraries I use: 
cytoscape-edgehandles
cytoscape-popper
cytoscape-node-html-label

But I don't think they should affect the current problem.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by mikekucera** [comment]
Can you provide a JSBin that can reproduce the error? I have nothing to go on here.

**Comment by mikekucera** [comment]
I don't know how to reproduce this issue. Please reopen this bug report if you can provide a JSBin or steps to reproduce.
