### ISSUE TITLE
Screen and mouse offset taking half of the Cytoscape container

### ISSUE THREAD

**Issue by FerFrassia** [cytoscape/cytoscape.js#3285]
**Environment info**

- Cytoscape.js version : 3.30.3
- Browser/Node.js & version : Safari Version 17.2.1 (64 bit), Version 130.0.6723.92 (Official Build) (x86_64) (64 bit)

**Current (buggy) behaviour**

_What does the bug do?_

There's a horizontal offset in the container and all networks appear on the right side of the offset. Clicking anywhere in left side of the offset actually clicks the right side of the offset. 
Dragging the graph from the right side of the offset to the left side of the offset shows that the graph goes behind whatever is there and disappears.

https://github.com/user-attachments/assets/af896986-69e1-4023-8398-b06079fc8785

**Desired behaviour**

_What do you expect Cytoscape.js to do instead?_

There should be no offset for the mouse or the UI and the graph should be able to be seen from anywhere in the canvas.

**Minimum steps to reproduce**

_What do you need to do to reproduce the issue?_

1. Click and hold somewhere in the left half of the canvas.
2. Drag to the left and you'll see the graph disappearing behind something. 

_Fork/clone this JSBin demo and reproduce your issue so that your issue can be addressed quickly and effectively:_
http://jsbin.com/fiqugiq

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by mikekucera** [comment]
I've never seen this happen before and I don't know how to reproduce the issue. We are going to need a reproducible demo using jsbin or some other reliable way of reproducing the issue. Thank you.

**Comment by maxkfranz** [comment]
Closing.

This can be reopened when a reproducible demo is posted.
