### ISSUE TITLE
Extra layout fun occurs when clicking on a graph after a layout was run on subset of eles

### ISSUE THREAD

**Issue by SoxMax** [cytoscape/cytoscape.js#3286]
**Before you post**

A request for help or a request for a how-to should be directed to [Phind]([url](https://www.phind.com/search?c=I%27m%20using%20the%20Cytoscape.js%20graph%20theory%20JS%20library.&q=How%20do%20I%20create%20a%20graph%20in%20my%20HTML%20page)).

If your issue pertains to an extension, your issue should be filed in that extension's repository -- not here.

**Environment info**

- Cytoscape.js version : 3.30.3
- Browser/Node.js & version : Chrome 130.0.6723.92

**Current (buggy) behaviour**

When issuing layout on a set of `eles` the same layout fires again as soon a the mouse is clicked anywhere in the graph.

**Desired behaviour**

The layout should on occur only once when instructed to via the run() function.

**Minimum steps to reproduce**

You can see the behavior in action clearly here: https://soxmax.github.io/pathfinder-feat-graph/
I recommend searching `Rapid Shot` in the search bar in the top right to illustrate the issue, but any query has the same issue.

Unable to load the jsbin.com from the instructions however my repo containing the issue is small and located here: https://github.com/SoxMax/pathfinder-feat-graph/tree/node-resize-fix
This branch has some extra diagnostic info enabled so you can see the `layoutstop` event fires multiple times in the console.

**For reviewers**

_Reviewers should ensure that the following tasks are carried out for incorporated issues:_

- [ ] Ensure that the reporter has included a reproducible demo.  They can easily fork this JSBin demo: http://jsbin.com/fiqugiq
- [ ] The issue has been associated with a corresponding [milestone](https://github.com/cytoscape/cytoscape.js/milestones).
- [ ] The commits have been incorporated into the corresponding branches.  Bug-fix patches go on
    - [ ] `master`,
    - [ ] `unstable`, and
    - [ ] the previous feature release branch (e.g. `1.1.x` if the current release is 1.2).
- [ ] The issue has been labelled as a [`bug`](https://github.com/cytoscape/cytoscape.js/labels/bug), if necessary.

**Comment by mikekucera** [comment]
This does not appear to be an issue with cytoscape.js or the extensions used. 

The 'searchFeats' function is being called a second time when you click the background and that causes the layout to run again. You can see this by adding the following code to the top of the 'searchFeats' function.

```
console.log('searchFeats');
console.trace();
```

The 'searchFeats' function is called first from the autoComplete selection handler. The second time its being called from the "change" event listener.

I think whats happening is that the "change" event fires when you take the focus off the search box. In fact if you click the address bar the 'searchFeats' function gets called and the layout runs a second time. If you just comment out the "change" event listener then the problem goes away.

**Comment by SoxMax** [comment]
Doh, thanks for finding this. Sorry for wasting your time

**Comment by mikekucera** [comment]
no worries
