### ISSUE TITLE
Layout are dependent on edges

### ISSUE THREAD

**Issue by Amanyadav12345** [cytoscape/cytoscape.js#3301]
Before adding edges and after edges in a large layout of 500 nodes where nodes are in group node layout and trying to form topology the layout gets disturbed
the nodes get out of the layout and disturb the whole layout and diagram

**Comment by Amanyadav12345** [comment]
![image](https://github.com/user-attachments/assets/922eb6a2-f12c-4c55-be8a-7d8b4ca6638f)



added a reverse edge from lower node to upper node the layout got disturbed

**Comment by nfigay** [comment]
The strategy concerning layout for adding a node then layouting should be revised, in order to prevent such a disturbance. Not really a bug, more something requiring an analysis for improvement.

**Comment by maxkfranz** [comment]
Issues must follow the issue template, and potential bug issues must include a reproducible demo.  This information is essential for issues to be addressed properly and in a timely manner.

Feel free to open a new issue, including the issue template and the reproducible demo.
