### ISSUE TITLE
experiment w/ labels as html w/ css transforms

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#335]
- performance
- would allow icons in labels
- would allow superscript subscript w/ html
- would give behaviour more like client dev expects

**Comment by Sigfried** [comment]
Was this implemented? Is there documentation or an example somewhere?

**Comment by maxkfranz** [comment]
No, there's no point to it.  It would invalidate z-ordering.

**Comment by Sigfried** [comment]
I think I misunderstood what this was for. I'm trying to figure out if I can use HTML or some kind of piece-by-piece formatting in labels: http://stackoverflow.com/questions/41941784/ctyoscape-js-is-there-a-way-to-use-html-in-labels
