### ISSUE TITLE
Add support for edge bends

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#359]
Spec:

For curved edges:

```
line-style: unbundled-bezier;
control-point-distances: 20px 30px 40px;
control-point-weights: 0.5 0.2 0.8;
```

For straight edges:

```
line-style: segments;
segment-distances: 10px 30px;
segment-weights: 0.2 1.2;
```

Tasks:

- `control-point-distances` etc for multiple points instead of one
- `control-point-weights` takes on values beyond [0, 1]
- `control-point-distance` aliased to `control-point-distances` etc for backwards compatibility
- `segment-*` properties
- new renderer line styles : multibezier, segments
- calculating control points in model coords and endpoints
- drawing new edges in renderer
- document that mid arrows don't work on these edges

**Comment by shalinibheemavarapu** [comment]
@gioper86, could you share your workaround?

**Comment by shalinibheemavarapu** [comment]
@gioper86, could you share your workaround? I am looking exactly for the right angled edges

**Comment by vivek542** [comment]
@gioper86 : Can you please your code workaround ... I am looking for orthogonal elbow edges to connect nodes & compound nodes ..
@maxkfranz : Is this feature/BUG already resolved in Cytoscape.js 2.3.11 or do we have plans for version 2.4? Please reply asap ... I see such possibilities with Klayjs library ...

**Comment by maxkfranz** [comment]
Refer to the milestones : https://github.com/cytoscape/cytoscape.js/milestones

If an issue is planned for a particular version, it has an associated milestone.  Obviously, an issue is closed if it is resolved.  New features do not make it into x.y.z releases, only x.y releases.

As for @gioper86's implementation, he's already given it to you.  Just use an extra node with straight bezier or haystack edges.

**Comment by gioper86** [comment]
Sorry everybody for the late response, I did not see the notifications.
I have put together a simple example and created a plunk. Here is the link: http://plnkr.co/edit/ug4mVWGPG7WYZPvChbFr

**Comment by maxkfranz** [comment]
e.g. for 
```
curve-style: unbundled-bezier,
control-point-distances: 20 -20,
control-point-weights: 0.25 0.75;
```
![screen shot 2015-09-25 at 3 48 50 pm](https://cloud.githubusercontent.com/assets/989043/10110730/0b3bcd04-639d-11e5-8c54-f960893f8000.png)

**Comment by maxkfranz** [comment]
Multibeziers done; docs and segments impl TODO

**Comment by maxkfranz** [comment]
Segments implemented

- Docs TODO
- Improvements to mid arrows and labels TODO

**Comment by maxkfranz** [comment]
![screen shot 2015-10-01 at 15 58 20](https://cloud.githubusercontent.com/assets/989043/10232204/4bb21138-6855-11e5-9662-25b9f0dcd20c.png)

Labels and arrows OK
