### ISSUE TITLE
Source and target labels on edges

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#382]
NB: in addition to edge label in the middle; e.g. you may want to label both sides of an edge

**Comment by maxkfranz** [comment]
Deferring; no time and release should not be delayed

**Comment by hh-h** [comment]
any plans?

**Comment by fsedano** [comment]
Hi folks - Any update on this? Currently trying to migrate my app from jsPlumb to Cytoscape, but this is a blocker.

**Comment by maxkfranz** [comment]
Increasing priority, but 2.5 already has a lot planned for it...

**Comment by fsedano** [comment]
Thanks Max - Hope it can be done ;-)

**Comment by maxruby** [comment]
What is the progress on this? I am happy to help implementing this too - it is crucial for my current project.  The labelling now is just not enough... Any update is appreciated.

**Comment by maxkfranz** [comment]
Issues off the top of my head:

**(1) Label placement** : This needs to be consistent for all types of edges.  Similar to the existing labels in the middle of an edge, they should be on the edge stroke.

Edge arrows have a collision point with the node defined, but this probably isn't a good place to put the label.  Instead, you'd probably want the label put along the edge, some distance away from that point.  

That gets more expensive for curved edges.  It becomes a mess for edges with multiple segments (segment edges / multiple bezier points / a.k.a. edge bends).  Then, we also have to take into consideration that edge labels can be autorotated: This makes edge bends even more complex and expensive.

**(2) Properties** : What properties are defined to support this; these probably suffice:

* `source-label` : text for label on source side
* `source-label-offset` : distance from intersection/collision point to place the label
* Do we repeat every single edge styling property for individual control, or do we keep the same style for all edge labels?  Separation would mean almost all of these properties would be duplicated: http://js.cytoscape.org/#style/labels  That's not just a mess in the code, but also in the documentation.  Duplicating the properties would make style calculation much slower.
* and repeat and replace `source` with `target`

**Comment by maxruby** [comment]
Thanks for the detailed explanation.  I would suggest for now, it would be immensely useful to have:

-  label always in the middle of the edge (half-way between nodes) 
- `source-label-offset` : top, bottom
- `rotation`: -90, 0, 90 (relative to the edge vector) 

What would be involved to do this for at least one edge type?
How could I best get started so we can at least test how this works?

**Comment by maxkfranz** [comment]
This quick sketch should clarify.  It uses a straight edge for simplicity.  The curved and semented cases are more complex.

![example](https://cloud.githubusercontent.com/assets/989043/11662066/f57f3844-9da2-11e5-9bf8-7ac83b1a7da5.png)

Rotation would not be relative to the edge direction.  It ought to be manual.  

Similarly, the label offset is along the edge -- not to denote above or below.  That's a completely separate feature that ought to apply to all edge label types, and it should be done separately and after this.

**Comment by maxkfranz** [comment]
Before anything is implemented, there ought to be a full specification of the properties and behaviour.

To start, let's just focus on the source case.  That can be implemented first, and the target case is analogous.

* `source-label` : the text
* `source-label-offset` : the distance as specified 
* `source-text-rotation: autorotate | none`

Edge types:

* straight / single segment : As image above
* multiple segments : As image above, but may be along multiple segments to get to the specified distance.
* single bezier: Calculating the distance along the bezier directly would be very expensive.  Since we use quadratic beziers, it may suffice to use a linear approximation.  We already calculate several points along the bezier for the purposes of bounding boxes.  Those could be used at a starting estimation, and then a binary search could yield a more accurate approximation -- or maybe just a linear interpolation between the points would suffice.
* multiple beziers : The approach is the same as the single bezier case but you first have to find which bezier the label would be on, similar to the multiple segments case.  The existing bound box points are probably enough to estimate each total bezier length for determining which bezier to select.
* bezier loops : This would be the same as the multiple beziers case, as each loop is made of two quadratic beziers.
* haystack : Probably can't support these

It's important to note that in segment/bezier selection, it's more performant to compare distance squares rather than distances.  Squareroots are expensive to calculate.

For the straight/segment cases, the autorotate angle is already calculated for the regular label.  The multiple segments case may need another calculation, because they may not share the same segment.

The bezier angle can be estimated using two points along the curve.  This is already done for multibeziers, and the same approach can be taken here.

**Comment by maxkfranz** [comment]
Everything has been refactored to support the new labels.  What's left is mainly the calculation stuff, which I described above.  You can see all todos with a search of `TODO #382`

**Comment by fsedano** [comment]
Thanks folks - Sorry to be late to the thread.

The use case I had in mine is to replace jsplumb in our application; 
this is the current drawing. So this approach would work nicely I believe.

**Comment by maxruby** [comment]
@maxkfranz 
This is fantastic - thanks for putting in all this effort.  I will have a look today at the TODO #382
