### ISSUE TITLE
options.userZooming

### ISSUE THREAD

**Issue by stanleygu** [cytoscape/cytoscape.js#386]
`options.userZooming`
- `false` => user input zooming is disabled in the renderer
- `true` (default) => user input zooming is enabled (as normal)
## Previously:

cy.zoomingEnabled(false) prevents mousewheel from scrolling

When the mouse is over the graph and zoomingEnabled is false, scrolling with the mouse wheel is blocked. Perhaps a better behavior is to allow mouse scrolling when zooming is turned off.

**Comment by sanlopez** [comment]
> Actually nevermind, everything is working as expected. It turned out to be a CSS issue with body {height:100%; overflow:hidden} where the window.onscroll was not firing and thus window.scrollY was never updated after a scroll event, causing an offset.

Big thanks, this solved my life!
