### ISSUE TITLE
Consider setting z-index: auto on cytoscape div

### ISSUE THREAD

**Issue by aschriner** [cytoscape/cytoscape.js#402]
I see that the cytoscape canvas has its z-index set to 1000.  I understand that is to make sure interactions with the elements and core receive their events, but I think that is maybe a bit too aggressive.  E.g. with Zurb Foundation a Reveal modal dialog has it's Z-index set to 99 automatically, which means if I create such dialogs they end up "behind" cytoscape and I have to go override the z-index on the dialog to be larger than 1000.  I think if you set "z-index: auto" on the cytoscape canvas then you get a new relative indexing system, so that cytoscape elements can have their own ordering, which is basically nested relative to cytoscape.  And hopefully that won't interfere with other dialogs and elements on the page.

**Comment by victoriastuart** [comment]
A late comment but for others searching / finding this issue, this may help (re: positioning additional <div>-elements around the "cy" <div>-element).

https://stackoverflow.com/questions/41180935/chart-doesnt-display-on-using-positionrelative-in-the-div-in-cystoscape-js/67796477#67796477
