### ISSUE TITLE
Directed minimum spanning tree algorithm

### ISSUE THREAD

**Issue by ikavalio** [cytoscape/cytoscape.js#438]
Currently all algorithms in `collection-algorithms.js` have both directed and undirected versions, except Kruskal, since it works only with undirected graph. For consistency, it would be good to have an algorithm that works with directed one as well. The best option from my perspective is to implement Edmonds' algorithm according to Tarjan implementation that runs in `O(m log n)` time based on [this](http://www.cs.princeton.edu/courses/archive/spring13/cos528/directed-mst-1.pdf)

**Comment by mazing** [comment]
Any update on this?
