### ISSUE TITLE
Adding custom shapes requires to change cytoscape.js

### ISSUE THREAD

**Issue by mecitsari** [cytoscape/cytoscape.js#441]
When developer creates a custom shape that is not in cytoscape.js, he needs to add it to <$$('renderer', 'canvas').nodeShapes>. That is ok but is not enough, he also must add this shape to <$$.style.types.nodeShape.enums>. I think developer needs a clear api to add a custom node shape. For now, it is not possible to understand that without deeply looking to cytoscape.js

**Comment by Shicheng-Guo** [comment]
any update for this issue?
