### ISSUE TITLE
Child nodes should be able to be positioned relative to parent or origin

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#530]
* `position: origin` => relative to origin
* `position: parent` => relative to parent node

**Comment by maxkfranz** [comment]
Decision: always specify position absolutely but position relatively w.r.t. UI

**Comment by eallik** [comment]
what does "buy position relatively w.r.t. UI" mean exactly?

**Comment by maxkfranz** [comment]
@eallik From the user's perspective (using the UI), positioning of children is relative.  In the model, the position is always absolute -- with convenience functions that allow you to specify a relative position that sets the absolute position accordingly.

**Comment by jackgeorge21** [comment]
How do I actually position a node within (relative to) its parent?

**Comment by jackgeorge21** [comment]
can you provide a code snippet? I dont see it in the docs
