### ISSUE TITLE
Autoposition nodes

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#628]
@aschriner Relates to #451 but is more generic

A generic way of autopositioning nodes could apply to several real usecases, like visualising circuits, bio pathways, etc.

- Simulating edge-edge hypergraphs with an intermediary node
- Simulating n-ary hypergraph edges
- etc

Common usecase: Average a node's position based on its neighbourhood.

Requirements:
- list of (probably connected) nodes to watch position
- function for setting node position 
- when autopositioned, calls to `node.position()` etc do nothing

Issue: The list of watched nodes can change dynamically as elements are added and removed from the graph.  So rather than specifying the list explicitly, we need to specify another function that generates the list.  That way, every time a node is added or removed from the graph, we can refresh the list.

Another issue: A dynamic list may not be performant.  So, maybe the app side should specify exactly what nodes should be watched.

Maybe something like this?
- `node.autoposition( otherNode )` : add to list
- `node.autoposition( function(nodes){} )` : specify a position function
- `node.unautoposition( otherNode )` : remove from list
- `node.unautoposition()` : turn off autopositioning altogether

**Comment by jtal** [comment]
@maxkfranz Is there a way now to autoposition?

**Comment by maxkfranz** [comment]
https://github.com/cytoscape/cytoscape.js-automove
