### ISSUE TITLE
Auto width for nodes

### ISSUE THREAD

**Issue by IonicaBizau** [cytoscape/cytoscape.js#649]
The nodes contain text.

Is there any setting to autoresize the nodes so the text will be always into rectangles?

**Comment by KristianKarl** [comment]
@IonicaBizau  Where do you set ```width: label.length * 10```?
Could show using this as an example?
https://gist.github.com/KristianKarl/d9ee356295042ef44504

Thanks in advanced.

**Comment by IonicaBizau** [comment]
@KristianKarl Something like this: http://jsbin.com/resuwe/2/

```js
cytoscape.stylesheet()
    .selector('node')
      .css({
        ...
        width: "data(width)"
      })
```

And the nodes are:

```js
[
 { data: { ..., width: ... } }
]
```

**Comment by KristianKarl** [comment]
@IonicaBizau  Works like a charm. Thanks

**Comment by IonicaBizau** [comment]
You're welcome! :smile:

**Comment by Braintelligence** [comment]
I don't want to open a new issue for this, because my request is closely related to this one.

I want the nodes to automatically resize with the amount of child nodes they have. Any ideas on how to accomplish this?

**Comment by MissChocoe** [comment]
In your style, add this information: 
$node > node {   
    width : auto;
    height : auto;
}

This will let node that have children be autosize.

**Comment by Braintelligence** [comment]
I'm sorry, perhaps I didn't specify it clearly enough.

What I want is: Let's say node A has 10 child nodes and another node B has 100 child nodes. I want the size of node B to >automatically< be bigger than node A.

If you add 90 child nodes to node A I want node A and B to be the same size.

If you add 200 child nodes to node A I want it to be the former size of B (big) and node B to be the former size of node A (small).

So as I said: Automatically resize the node related to the amount of child nodes they have.

I don't think I will achieve this with your code, will I? I can't see any relation to the >amount< of child nodes and the size of the parent node. Please tell me where you adress this?

**Comment by MissChocoe** [comment]
In theory the more children you have the more space they will take so the bigger the parent will be. Other than that you could use properties mapper to have a more specific relation between the node size and the amount of children but you will need to put the number of children in the data attribute of the parent.

**Comment by maxkfranz** [comment]
@Braintelligence In 2.4 (or now in `unstable`), you can use functions as style property values.  So, you could return dimensions proportional to `node.children().length`.

The original purpose of this issue is completely aesthetic with respect to labels.  In future, if you have a distinct issue, please file a separate issue.  (I'd rather have potential duplicate issues rather than complicate an existing issue.  Plus, the previous people involved in the ticket are probably only interested in notifications that apply to their specific issue.)  Thanks!

**Comment by Braintelligence** [comment]
Alright, thanks. I'm sorry for derailing this issue.

**Comment by maxkfranz** [comment]
Deferring to later release

**Comment by maxkfranz** [comment]
Supported in 2.5

**Comment by IonicaBizau** [comment]
NIce! :tada:

**Comment by maxkfranz** [comment]
Ref :  Autosized nodes based on label dimensions #1041

**Comment by karlitos** [comment]
I do not want to open new ticket for this so I will post my question here:

The only way I was able to achieve _left-aligned_ labels inside of nodes was to set:
```javascript
'width': '300px',
'text-wrap': 'wrap',
'text-max-width': '300px',
'text-valign': 'center',
'text-halign': 'right',
'text-margin-x': '-300px',
```
How can I set the margin  depending on the label size ? I tried `'-label'` and `'-1*label'`, but this seems to be not working

**Comment by maxkfranz** [comment]
`label` is just an enum; it's not a variable with a value.  If you want spacing around text, you use `padding`.

If you want to set the horizontal typographical alignment differently than the horizontal positional alignment, then a new style property would need to be introduced.  Now, the typographical alignment is implicitly set by the positional alignment.

**Comment by ketys-from-meiro** [comment]
When it's now deprecated, what's alterative?

**Comment by maxkfranz** [comment]
See
https://github.com/cytoscape/cytoscape.js/issues/2713#issuecomment-712247855
