### ISSUE TITLE
Cytoscape.js performance on different browsers

### ISSUE THREAD

**Issue by ggirelli** [cytoscape/cytoscape.js#652]
I find cytoscape.js incredibly slow on Firefox 31.0, while it works perfectly on Chromium 34.
OS: Ubuntu 14.04.
Is this normal?

**Comment by maxkfranz** [comment]
Closing for now

**Comment by maxkfranz** [comment]
Browser performance is more equal in 2.7+, given the renderer architecture is not so bottlenecked on the individual browser performance of specific APIs.  Now, Firefox is even faster than Chrome in a lot of cases.
