### ISSUE TITLE
Cytoscape.js and IE8 or IE10 (IE8 Compatibility mode)

### ISSUE THREAD

**Issue by Giant2** [cytoscape/cytoscape.js#668]
SCRIPT5009: 'cytoscape' undefined

This is the error I reach when use cytoscape in IE8 or IE10 with IE8Compliance.
It seems the error is on the definition of the object cytoscape.
Probably
var cytoscape;
(function(window)...
is not the correct way to define the function in IE8 (c.d.r. cytoscape.js).
Is there someone encoutered the same problem?
Thanks all.

**Comment by geemang2000** [comment]
I have the same error 'cytoscape' undefined with IE10 when I use the cytoscape.min.js 
When I use the non-min js file it works. Is this a bug with the min tool?

**Comment by maxkfranz** [comment]
If you're using "compatibility mode", then there are no guarantees of functionality -- as this is essentially nonstandard/broken IE mode.
