### ISSUE TITLE
Dependency tree visualisation demo

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#738]
Because Cytoscape.js is able to visualise trees effectively, it would be interesting to have a demo that showcases this for an interesting usecase (or perhaps more than one if time permits).

Possible datasources: Linux kernel modules, npm packages, ...

The featureset of the demo beyond visualising the dependency tree would depend on the datasource: It's open ended.

**Comment by mikekucera** [comment]
For bonus points... create an Eclipse Orion plug-in that shows npm package dependencies for an orion project.
