### ISSUE TITLE
Quadtree support

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#760]
A quadtree (ref : https://en.wikipedia.org/wiki/Quadtree) is a datastructure that allows for efficient lookup of sets of spatial co-ordinates.  For Cytoscape.js, this could be applied to element (node and edge) hittests: The quadtree could be queried to determine the closest element to the cursor/mouse or finger in an efficient way.

It might not be warranted for many usecases because of the additional cost of maintaining the tree, but it could be useful in other cases.

This project need not be constrained to quadtrees specifically, as a different particular tree structure may be more appropriate.

**Comment by mikekucera** [comment]
A quadtree might be useful for speeding up layout algorithms. The Fruchterman-Rheingold paper mentions using a spacial grid to avoid computing forces between nodes that are not in the same grid cell.
