### ISSUE TITLE
Add benchmark regression tests

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#770]
Use Benchmark.js : http://benchmarkjs.com/

I'm hoping that it's possible to use Benchmark.js to not only measure the absolute performance (i.e. running x took y ms) but mostly to determine whether one new commit compared to an older commit is faster (i.e. yes or no question).  Because of differences in hardware, testing individually is more useful in this yes|no fashion.

As long as the answer is yes for future commits, this would act as a sort of inductive performance increaser.

**Comment by makc** [comment]
> If you could provide some large test data for benchmark tests, it would help in creating those benchmarks

just use any 3d mesh off the net :wink: e g [this](http://www.123dapp.com/3dsc-Sculpt/rose/1495203) tshirt has 48386 vertices (nodes) and 96768 triangles (so by euler formula that should be around 145 thousands edges) - that's about 8 times more than in my case. should be pretty good for benchmark. also ["obj" format](http://en.wikipedia.org/wiki/Wavefront_.obj_file) is plain text with numbers so you will have no problems to parse.

**Comment by makc** [comment]
oh and fyi, I just compiled https://github.com/polygonal/ai with haxe (this lib is optimized for flash, not js; and, being cross-compiler, haxe does add some overhead on its own). in the case of #904 their A* completes in under 4ms.

**Comment by maxkfranz** [comment]
The benchmark framework has been added and there is an example for A*.

For algorithms specifically : https://github.com/cytoscape/cytoscape.js/issues/936
