### ISSUE TITLE
InvalidStateError on Chrome 39

### ISSUE THREAD

**Issue by miwelc** [cytoscape/cytoscape.js#778]
When a background-image's URL is broken, execution halts with an uncaught InvalidStateError under Chrome 39.
I've tested it on Safari 8.0.2 and it works without issues.

**Versions:**
Cytoscape.js 2.3.5
Chrome 39

**Error Message:**

```
cytoscape.js:15890 Uncaught InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
```

After applying the next diff the problem seems fixed:
![captura de pantalla 2014-12-22 a las 2 19 31](https://cloud.githubusercontent.com/assets/1483856/5520470/907c9cf0-8982-11e4-90d9-8556e48815b9.png)

**Comment by rzec-r7** [comment]
@maxkfranz Did something like this ever get implemented? I am running into weird CORS errors with trying to load images which cause cytoscape to just completely break so it would be nice to have a fallback image that it served locally (like a base64 image you mentioned above) that can be used if that happens to prevent cytoscape from completely crashing (which effectively crashes that application and requires a refresh).

**Comment by coreation** [comment]
@rzec-r7 are you able to reproduce cytoscape breaking consistently? I had a small (and very rare) bugreport of "HtmlImageElement" being in a broken state and that the safeDraw errored with a DOMException, effectively breaking my graph drawing. However, I could even add images that returned a 404, I couldn't reproduce it in any way, not even when CORS throws an error.
