### ISSUE TITLE
Fixed node/edge size - Label disappear after a specific zoom

### ISSUE THREAD

**Issue by markov00** [cytoscape/cytoscape.js#780]
Hi, I'm try to figure out how to draw a graph with fixed node and edge size during zoom.

I'm now using something like the following code enabling also  textureOnViewport to reduce the graph redraw, but happens that after a specific zoom level (after 30.5) all the labels disappear. I've debugged a bit the code and seems that the drawText is called correctly, but the text disappear (the opacity is correct, size is greater then 0 (0 dot something but greater than 0). 
There is also the fact that the labels position is not recalculated correctly until I select a node.
What can I do? Is there another way to achieve the same effect? Thanks

```
cy.on('zoom', function (event) {
        var dim = 10/ cy.zoom();
        var edgeWidth = 1/ cy.zoom();

        cy.$('edge').css({
            width:edgeWidth,
            'font-size': dim
        });
        cy.$('node').css({
            width:dim,
            height:dim,
            'font-size': dim,
            'text-opacity':1,
            'overlay-padding':edgeWidth*2
        });
    });
```

I've also specified the min-zoomed-font-size setting to 0 or less but this is not the case, as already stated the drawText call is always called

**Comment by maxkfranz** [comment]
As for your original enquiry: We could calculate the effective fontsize ourselves and set 1px as the absolute minimum, mimicking the better behaviour of Firefox.

As for your second enquiry:  If I understand correctly, you want a fixed font size regardless of zoom.  If that's the case, would you please create a second ticket for that discussion/workflow?  I think the original enquiry should "own" this ticket.  Thanks

**Comment by markov00** [comment]
@maxkfranz I've just created a new issue #789 with a jsbin demo

**Comment by maxkfranz** [comment]
Can't reproduce on latest browsers; removing from 2.4
