### ISSUE TITLE
Adding a more information over the node in cytoscape.js

### ISSUE THREAD

**Issue by devradhika** [cytoscape/cytoscape.js#786]
adding extra information about the node. For example, adding a circle/rectangle showing the alarm or distance above the node or at specific position of the node.

**Comment by maxkfranz** [comment]
You should be able to do that in any way you want:  You can make an extension that hooks into your own code or another library's code to achieve that purpose, or you can do the same minus the extension bit to be less coupled if you wish.

Features like that which are covered by combining multiple libs in your app are outside of the scope of this project, else Cy.js would become bloated.  Thanks
