### ISSUE TITLE
Missing element property on json()

### ISSUE THREAD

**Issue by curupaco** [cytoscape/cytoscape.js#788]
When you call `json()` to save the graph and load it later, a property for a hidden element is missing.
```javascript
{
    "data": {
        "id": "a"
    },
    "position": {},
    "group": "nodes",
    "removed": false,
    "selected": false,
    "selectable": true,
    "locked": false,
    "grabbed": false,
    "grabbable": true,
    "classes": "highlighted"
}
```
So if you call `eles.hide()` on some elements, and save the json, when you recreate the graph, those elements will be visible

**Comment by maxkfranz** [comment]
You should not assume that calls to `eles.show()` and `eles.hide()` is itself a state.  It's a style bypass, analogous to setting the style attribute on a HTML DOM element.  If you think about it in terms of the traditional MVC model, the bypass would be in the View: The serialised JSON is the Model.

If you want to maintain serialisation state, you can use a `hidden` or `shown` class -- similar to how you've used a `highlighted` class.  Alternatively, you could additionally serialise the style for each element in addition to its JSON model via `ele.style()`, which should return the entire computed style for the element.  However, this style serialisation approach would be very expensive.

Thanks for your interest in Cytoscape.js.  If you have any issues or questions, please let me know.  

Closing for now

**Comment by curupaco** [comment]
Thanks for your explanation Max. It really helped =D
