### ISSUE TITLE
Cytoscape Leaking DOM?

### ISSUE THREAD

**Issue by i2shar** [cytoscape/cytoscape.js#793]
Each time a cytoscape instance is created and destroyed, there are remnant DOM nodes added to the body that are not removed. They seem to correspond to the last node in the graph, "George" in this case.

![image](https://cloud.githubusercontent.com/assets/608265/5689516/2570feea-981b-11e4-952f-cf3c0c025ca7.png)

Here's the plunker: http://run.plnkr.co/plunks/4vKxA6Lqlqm7DxiuE8At/ and code is at http://plnkr.co/edit/4vKxA6Lqlqm7DxiuE8At?p=info

**Comment by markov00** [comment]
Hi, I think I've found the problem and I've issued a PR. The div is used to calculate the dimension of each labels, but it's appended to the body and never removed during the destroy.
I've proposed two way to solve it: removing the element during the destroy or appending the element into the cytoscape container. Either methods works correctly.
