### ISSUE TITLE
Enable zooming on mouseover event in cytoscape.js

### ISSUE THREAD

**Issue by devradhika** [cytoscape/cytoscape.js#796]
I have created a graph using cytoscape.js. I have set cy.zoomingEnabled(true);
It provides the zooming on the mouse scroll event on the node. I want to make it zoom on mouseover event on the node. 
Thanks.

**Comment by markov00** [comment]
Hi,

**Comment by devradhika** [comment]
Thanks @markov00

**Comment by maxkfranz** [comment]
Closing for now; please re-open if needed
