### ISSUE TITLE
Haystack => bezier => haystack edges glitch

### ISSUE THREAD

**Issue by miwelc** [cytoscape/cytoscape.js#797]
I've come into an issue regarding curve-styles. For performance reasons I use 'haystack' as the default edge style and 'bezier' for edges with 'highlighted' class in order to show arrows.

After removing the 'highlighted' class everything seems right until the nodes are moved (e.g. reload layout with different end positions): edges refuse to move accordingly to nodes.

**Version**
Cytoscape 2.3.7

![screenshot](https://cloud.githubusercontent.com/assets/1483856/5720778/3f3f9424-9b29-11e4-8be0-65e7c50925b8.png)

**Comment by maxkfranz** [comment]
I think this should do it.

Snapshot to try: http://js.cytoscape.org/download/cytoscape.js-snapshot-5cbfc36887-1422916071961.zip

**Comment by maxkfranz** [comment]
FYI: Arrows on haystacks may be possible in 2.4, though in this case the haystack edges would need a radius of 100% -- meaning they wouldn't point to the centre points of nodes.

**Comment by maxkfranz** [comment]
Closing for now; please reopen if this is still an issue for you in the snapshot
