### ISSUE TITLE
Edge and arrow not correctly rendered after changing width style property

### ISSUE THREAD

**Issue by markov00** [cytoscape/cytoscape.js#799]
Hi, After the initialization of the style of the graph, I've noticed that if I increase the width of an edge, the renderer ignore the fact that also the width of the arrow is increased and draw the edge with the previous length of the edge calculated with the previous arrow width.
You can see the effect on the two images here:
![schermata 2015-01-14 alle 12 10 49](https://cloud.githubusercontent.com/assets/1421091/5737947/f94e50f4-9be6-11e4-9d21-25cc5d292981.png)
![schermata 2015-01-14 alle 12 10 56](https://cloud.githubusercontent.com/assets/1421091/5737950/fd1fc50a-9be6-11e4-953b-92318df35123.png)
In the first case, I've just added a class with a greater width. Then if i move one of the edge node the edge is correctly redrawn. But then if I remove the class the edge and arrow are drawn like in the second picture. Everything is redrawn again correctly only after moving one of the two node of the edges.
Here there is a jsbin for this: http://jsbin.com/jirodaqeti/1/edit?js,output

**Comment by maxkfranz** [comment]
I think this should do it; snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-7a63386fb4-1422649756798.zip

**Comment by maxkfranz** [comment]
Closing for now; please reopen if it's still an issue for you in the snapshot
