### ISSUE TITLE
Add a Changelog file

### ISSUE THREAD

**Issue by markov00** [cytoscape/cytoscape.js#801]
Hi,
it will be great to have a changelog file to keep track of the differences between the releases.
For example now on 2.3.8 there is a new layout: springy and it will be great to know it without going through the commits, what do you think @maxkfranz ?

**Comment by maxkfranz** [comment]
I think Springy is in all 2.3.x versions.  I've just been using the tracker with the [milestones](https://github.com/cytoscape/cytoscape.js/milestones) to track changes.  That way, you can also see the individual, corresponding commits if you like.

Maybe there's a way to automate a changelog file from the issue titles under each milestone?

**Comment by markov00** [comment]
Hi, I'm sorry you are right, I mixed up unstabled spread layout with the current master springly. Sorry for that. That's fine using the milestones: I wasn't thinking of checking that because I used to have a changelog directly on the repository. I've seen some automatic generator of changelog like  https://gist.github.com/joelittlejohn/5937573  or https://github.com/lalitkapoor/github-changes

**Comment by maxkfranz** [comment]
Thanks; I'll try to integrate one of those scripts for 2.4

**Comment by maxkfranz** [comment]
Can be done after 2.4

**Comment by sylvain-hamel** [comment]
+1
