### ISSUE TITLE
Strict tree flow layout

### ISSUE THREAD

**Issue by devradhika** [cytoscape/cytoscape.js#803]
I have created graph as follows:
![hierarchi](https://cloud.githubusercontent.com/assets/10286985/5814125/ef37c67e-a0ad-11e4-8810-7e9bf3ad1787.png)

Need structure like this:
![hierarchi1](https://cloud.githubusercontent.com/assets/10286985/5814142/0a141a6a-a0ae-11e4-8eca-56ec00660d6b.png)

So that I can add any number of nodes and link them to any hierarchy.
Thanks!

**Comment by devradhika** [comment]
![chart](https://cloud.githubusercontent.com/assets/10286985/5831795/b2672c00-a15f-11e4-99b5-82a1a27aa3d6.png)


also want to know about the padding between nodes, so that the charts will not overlap the other nodes

**Comment by markov00** [comment]
@devradhika how do you have placed the charts over the graph? I'm really interested to see how it works, could you share that?

**Comment by devradhika** [comment]
These charts are only images, I have created it as an example. I have added nodes using the cy.add()

**Comment by maxkfranz** [comment]
I suspect this would require a heavily modified strategy in the breadthfirst layout.  It tries to maximise space rather than tree flow.

It may be even better to have a separate layout solely for trees, though perhaps you may find Dagre more suitable for your purposes.

**Comment by devradhika** [comment]
In first figure above if I need to add new nodes to any branch of the tree I want it to be appear in straight line(i.e. vertically). is it possible?

**Comment by maxkfranz** [comment]
If you add nodes, you can position them manually wherever you like -- underneath a predecessor node if you like.

**Comment by devradhika** [comment]
http://jsfiddle.net/naL1byg8/ 
I have set the position values for first node however, not refecting anything in the output.

**Comment by maxkfranz** [comment]
You specified a layout.  You can't have both, else the layout will override manual positions.

(1) Do manual positioning after layout at init, or

(2) use all manual positions.

**Comment by devradhika** [comment]
Thank you @maxkfranz 
There is another scenario i.e. tree can have any number of branches, for an example I used four branches. but if number of branches changes dynamically then setting the positions manually will not display the layout correctly.

**Comment by maxkfranz** [comment]
In (2), you don't use layout but rather position nodes manually according to your own specifications.

**Comment by maxkfranz** [comment]
Dagre might meet the requirements for this already.

**Comment by maxkfranz** [comment]
Closing for now, as Dagre should do this.
