### ISSUE TITLE
New background-fit type to render image without keeping aspect ratio

### ISSUE THREAD

**Issue by jhonatandarosa** [cytoscape/cytoscape.js#804]
Currently exists these values for `background-fit` property:
- `none` for original size 
- `contain` to fit inside node
- `cover` to cover the node

All of these keeps the aspect ratio.

It would be interesting to have a value that draws the image with the same node width and height regardless of the aspect ratio

**Comment by maxkfranz** [comment]
So maybe a `stretch` value?

**Comment by curupaco** [comment]
That would be nice

**Comment by maxkfranz** [comment]
Not necessary.  In 2.4/unstable, specify:

```
node {
  background-width: 100%;
  background-height: 100%;
}
```

**Comment by maxkfranz** [comment]
Ref : https://github.com/cytoscape/cytoscape.js/issues/705
