### ISSUE TITLE
Flickering when loading elements

### ISSUE THREAD

**Issue by thSoft** [cytoscape/cytoscape.js#805]
If I call load(), the old graph disappears for a short time, then the new one appears. It would be more user-friendly if this flashing did not occur.

**Comment by thSoft** [comment]
(This is not perceivable when motion blur is enabled, but when it is disabled, it is apparent.)

**Comment by maxkfranz** [comment]
Labelling as "bug" because of UI/UX implications; adding to 2.3.9 if it can be resolved without much impact/risk on code

**Comment by maxkfranz** [comment]
Do you have an example?  And could you provide browser/OS info etc?

I can't reproduce this.  I see the new graph replace the old one without flicker, even with `motionBlur: false` and a large number of elements.

**Comment by maxkfranz** [comment]
Removing from 2.3.9 milestone until reproducible

**Comment by thSoft** [comment]
Here is a minimal example with the latest version: http://jsbin.com/pelofoqufa/1/edit?html,js,output

**Comment by maxkfranz** [comment]
Have you tried `cy.batch()` and making your own calls? http://jsbin.com/madiqoqalo/1/edit?js,console,output

It's almost always better not to use `cy.load()` and to make the calls to `cy.add()` and `cy.layout()` etc yourself.

As `cy.load()` had been complained about and caused confusion before, I think it should be removed from the docs and deprecated: https://github.com/cytoscape/cytoscape.js/issues/822

I'll try to add a fix in the meantime, but you may want to avoid `cy.load()` in future.

**Comment by maxkfranz** [comment]
Snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-faf63dac65-1423163894122.zip

Please let me know if this works for you, and if so I'll close this.

**Comment by thSoft** [comment]
Oh, I see, remove() and add() in batch() works nicely: http://jsbin.com/wicune/1/edit?js,output
