### ISSUE TITLE
Is it possible to restrict the width (auto line break) of labels?

### ISSUE THREAD

**Issue by ktei** [cytoscape/cytoscape.js#807]
If a label has long text, such as 'word word word word word word word word word word word word', then it ends up a very long label.

So, instead of having something like
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
is it possible that we could restrict the width of a label and have something like
xxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxx
          xxxxx
?

**Comment by maxkfranz** [comment]
Please see #305
