### ISSUE TITLE
Indicate node selection with persistent grey round rectangle?

### ISSUE THREAD

**Issue by pshannon-bioc** [cytoscape/cytoscape.js#808]
A nice light grey rounded rectangle is displayed when I select a node.  However, it disappears as soon when the mouse click event is over.

Can I control this behavior?  

   a) Can I make the grey rectangle persist as long as the node is indeed selected?
   b) Can I modify the visual attributes of the rectangle?

Thanks!

- Paul

**Comment by ktei** [comment]
@pshannon-bioc I don't think that grey rectangle should be used as a selection indication; its main purpose is just to tell users 'you are selecting it'. However, if you need indication to tell users something, for example, a node has been selected, you can use style, something like this:

```javascript
            style.selector('node:selected')
                .css({
                    'border-color': Settings.NODE_BORDER_COLOR_SELECTED
                });
```
Check the documentation for more information and you'll understand.

**Comment by pshannon-bioc** [comment]
Hi Rui (and Max),

May I disagree, on two fronts?   Hoping I can do so without causing offense...

The user interface idiom of selection is widespread; it has been around for a long time.   And it follows a consistent pattern:  mouse selection typically changes some aspect of the rendering, so that in most regards the object is unchanged, but its selection status is clear.

Selecting text works this way.  The mouse-drag action changes (typically) the background; that change serves as a selection indication; it persists as long as the text is selected.  cytoscape.js is unusual in that the selection indication (a change in local background) disappears immediately.

Your suggestion (one I have used before) has this limitation:  if you manipulate node size, color, or border, then any information those attribute previously carried is gone.   The beauty of the gray rectangle is that it leaves all other visual attributes essentially unchanged -- just as we expect in ui design.

So that's one argument I hope you might find convincing.

The second is a meta-argument.  It is that a library (to my mind, anyway!) should provide mechanisms, and should rarely impose policies.    Policies are very important, but they can vary from application to application, from use to use.  

I think cytoscape.js follows this principle almost all the time, and that is part of its beauty and power.  The developer gets to decide what visual mapping rules to apply, what layout to use, what fonts are appropriate.  

In my work, a programmable, non-destructive, persistent indicator of selection would be a very good thing.  That's why I was so pleased to discover the (new?) grey rectangle.  By "non-destructive" I mean that other visual attributes are not disturbed.  Now all I wish for -- I hope it is not too much -- is to have, as a programmer, some control over the feature.

 - Paul

**Comment by pshannon-bioc** [comment]
Hi Paul & Rui:

I think you can use the box in any state you want.  It's there by default in `:active`, but you could also use `:selected` with another colour, for example:  

:selected {
  overlay-opacity: 0.666;
  overlay-color: blue;
}

I debated over whether `:active` should even have the box by default, but since that seems to be the de facto standard on touch -- I decided to just go with the flow.  You could override that with:

:active {
  overlay-opacity: 0;
}

Thanks,

-Max

**Comment by maxkfranz** [comment]
My comment via email did not go through properly.  Pasting:

--

Hi Paul & Rui:

I think you can use the box in any state you want.  It's there by default in `:active`, but you could also use `:selected` with another colour, for example:

:selected {
  overlay-opacity: 0.666;
  overlay-color: blue;
}

I debated over whether `:active` should even have the box by default, but since that seems to be the de facto standard on touch -- I decided to just go with the flow.  You could override that with:

:active {
  overlay-opacity: 0;
}

Thanks,

-Max

**Comment by pshannon-bioc** [comment]
Dear Max and Rui,

Max's latest suggestions work very well indeed.  Rui -- thanks for your assistance; I hope I was not too tough a customer!  

Thanks to you both,

 - Paul

**Comment by maxkfranz** [comment]
Great; closing for now

**Comment by maxkfranz** [comment]
Ref : http://js.cytoscape.org/#style/overlay
