### ISSUE TITLE
Springy: Nodes are positioned wrong when some nodes are locked?

### ISSUE THREAD

**Issue by Fransooijs** [cytoscape/cytoscape.js#809]
I have come across a possible bug with the springy layout.  It appears that some nodes are positioned wrong when some nodes are locked.  Code linked below.
 
The bug occurs when I have 3 nodes (a,b,c) connected with 2 edges and the outer nodes (a and c) having their positions locked. The middle node (b) remains unlocked.

Bug:
node b appears in a unexpected position.
![springy_locked](https://cloud.githubusercontent.com/assets/10688021/5901044/04c69aac-a567-11e4-8566-393178033ab3.png)

What I expect should happen:
node b is between node a and c.
![springy_expected](https://cloud.githubusercontent.com/assets/10688021/5901050/0fddc0fa-a567-11e4-8c0b-8406cddc06d9.png)

Code:
https://gist.github.com/Fransooijs/f35b3a26e4bda677dd7f

**Comment by maxkfranz** [comment]
Not a bug.  The position is the same.  If you want the viewport to remain unchanged, please set it so in your layout options.
