### ISSUE TITLE
Hold left-click and drag to select multiple nodes

### ISSUE THREAD

**Issue by billduddy** [cytoscape/cytoscape.js#810]
Not sure if this is a bug or a feature change: in older versions (at least for 2.3.5) it was possible to hold left-click and drag to select multiple nodes. In the current version, holding left-click and dragging moves all nodes.

**Comment by curupaco** [comment]
You must enable the property `boxSelectionEnabled` when creating cytoscape.
In older versions this was enabled by default

**Comment by billduddy** [comment]
Thanks
