### ISSUE TITLE
Sometimes can't get out of box selection state

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#816]
i.e. can't get back to pan state

**Comment by maxkfranz** [comment]
Reproducible only on macbook trackpad?

**Comment by maxkfranz** [comment]
A regular mouse doesn't seem to do it; or maybe it was a caching issue on another machine...?

**Comment by maxkfranz** [comment]
Removing from 2.3.9 until confirmed

**Comment by ggirelli** [comment]
with v2.3.10 (and v2.3.9 too) sometimes the panning does not work: i.e.: the gray circle appears but then I can't pan and instead the box selection is triggered...

**Comment by maxkfranz** [comment]
Seems to affect 2.3 in addition to 2.4 (though more easily reproducible in 2.4/unstable)

**Comment by maxkfranz** [comment]
Snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-44169df594-1426787920105.zip

**Comment by maxkfranz** [comment]
@ggirelli Please test the snapshot and see if you can still reproduce the bug.  I can't reproduce it anymore from my testing.

**Comment by ggirelli** [comment]
Tested: the snapshot works perfectly! :D
So, can I assume that this bug will be fixed in the next build?

**Comment by maxkfranz** [comment]
@ggirelli Yes
