### ISSUE TITLE
Some pixels from edge should be clickable

### ISSUE THREAD

**Issue by devradhika** [cytoscape/cytoscape.js#826]
I need to add some functionality to my graph like some pixels from the edge e.g. 5px from the edge(both above and below 5,5), if I click in that area of 5 px the edge should be clicked. Is it possible?
How can I do this?
Thanks !

**Comment by maxkfranz** [comment]
This is already done for you automatically, with a smaller threshold set for mouse input and a larger one for touch input.

If you need to configure this manually, you'll need to modify your [init options](http://js.cytoscape.org/#core/initialisation), including: 

- `touchTapThreshold`
- `desktopTapThreshold`

**Comment by devradhika** [comment]
tapThreshold: defVal( $$.is.touch() ? 8 : 4, $$.is.touch() ? options.touchTapThreshold : options.desktopTapThreshold )

making changes to this line, not working. Am I doing at right place?
