### ISSUE TITLE
IE supported

### ISSUE THREAD

**Issue by magixsource** [cytoscape/cytoscape.js#827]
support ie8 or ie7 ?

**Comment by maxkfranz** [comment]
Outdated browsers that don't support modern web standards are not supported.  IE7 and IE8 neither are standards compliant nor do they have the necessary rendering technology (canvas).

**Comment by thiagosbrito** [comment]
maxkfranz, what about the html5shim , if i force the old browser to render some html5 elements, would the cytoscape work?

**Comment by maxkfranz** [comment]
Stackoverflow: http://stackoverflow.com/questions/10482570/is-there-a-way-to-use-canvas-in-ie7-or-ie8

That being said, I still don't think it would work.  If you have a requirement to support old, broken environments perhaps you should re-evaluate your featureset or reconsider the requirement itself.  IE7 is almost a decade old.

**Comment by maxkfranz** [comment]
See:

- http://www.computerworld.com/article/2508872/desktop-apps/google-to-dump-support-for-microsoft-s-ie7.html
- http://www.computerworld.com/article/2492571/web-apps/google-to-drop-support-for-ie8-on-nov--15.html

If Google can't manage to do it, do you think it's a reasonable requirement for you?  Just a thought.
