### ISSUE TITLE
Add a selection changed event

### ISSUE THREAD

**Issue by MissChocoe** [cytoscape/cytoscape.js#828]
You can be notified when a node or an edge is selected, but you will get notified even if it was already selected. Furthermore, when no more nodes are selected, no select event is raised. For now I use the tap on the cy core element, but this doesn't cover all the case when the selection changed. It can be changed because elements were removed from the graph for example.

**Comment by maxkfranz** [comment]
You can use `select` *and* `unselect` events.

Removing elements ought not to raise a selection event.  That's app-level logic, and dependent on the usecase.

If a previously selected node triggers a `select` event, then that's a separate issue that should be described in another ticket -- as this one seems to be about a collated `selectchange` event or similar.  I am not sure that  a `selectchange` event would be a good idea, considering there could be performance considerations and there are already `select` and `unselect` which you can bind to separately or in combination.

What do you think?

**Comment by MissChocoe** [comment]
I agree that the select event that is triggered more than one is a separate issue since it is a bug. I've had my way around it by selecting a property on the node that I removed when the node is unselected.

If someone call "unselect" on a node, it will be raise the event if that node was never actually selected. This is probably another issue.

Finally, I do something when a node is unselected and something else when no more node are selected. To know that, I rely on the tap on the canvas at this point which means selection is cleared. It would be simpler to have a selectionChange event that is raised event when the selection is cleared. Or maybe the canvas could raise a select event, but that doesn't seem to jive. But if elements that are removed ought not to raise selection event, than it wouldn't be that useful anyway. I guess you do that so if the node is restored it will come back selected? I'm not clear on why having a node not in the graph selected makes sense.

**Comment by maxkfranz** [comment]
> I'm not clear on why having a node not in the graph selected makes sense.

You may want to add it back, for example.

**Comment by maxkfranz** [comment]
You can just listen to `remove` in addition to the other events.  If removed, you can assume the same state as an `unselect` event in your app.

**Comment by maxkfranz** [comment]
> I agree that the select event that is triggered more than one is a separate issue since it is a bug. I've had my way around it by selecting a property on the node that I removed when the node is unselected.
>
> If someone call "unselect" on a node, it will be raise the event if that node was never actually selected. This is probably another issue.

This sounds like the same bug.

**Comment by MissChocoe** [comment]
@maxkfranz  Thanks for the "remove" event, I've missed it! :+1:

**Comment by maxkfranz** [comment]
Closing for now; an additional event would add overhead and isn't necessary to create the same behaviour
