### ISSUE TITLE
Can we have some control over the curvature of nodes?

### ISSUE THREAD

**Issue by ktei** [cytoscape/cytoscape.js#834]
When a node has a few edges connected to another node, the edges will be curved. Can we have some control over how curve those edges are?
Like the image below:
![curve](https://cloud.githubusercontent.com/assets/2195250/6183229/75f4dba6-b3a6-11e4-9c47-9a06a820f6e6.png)

Thank you @maxkfranz

**Comment by maxkfranz** [comment]
Yes, just change the step size CSS property.  Smaller values are closer, and larger more spaced

**Comment by ktei** [comment]
Thank you @maxkfranz
