### ISSUE TITLE
Functions as style property values

### ISSUE THREAD

**Issue by delihiros** [cytoscape/cytoscape.js#836]
We thought it could be great if `mapData` could take a non linear function like logarithm.
Will it be merged if I work on it?

**Comment by maxkfranz** [comment]
Already done in `unstable` for 2.4 but undocumented in the tracker.

e.g.:

```
         'content': 'data(id)',
         // works the same as
         'content': function( n ){ return n.data('id') },
```

**Comment by maxkfranz** [comment]
i.e. you can specify a function in place of the value in a stylesheet

**Comment by maxkfranz** [comment]
Re-opening, because I think the docs need to be updated in `unstable`

**Comment by delihiros** [comment]
Nice. Thanks

**Comment by maxkfranz** [comment]
TODO should be some note of performance and caching (e.g. use Lodash `_.memoize()`)

**Comment by maxkfranz** [comment]
Added docs so closing
