### ISSUE TITLE
Component broke with large amount of data

### ISSUE THREAD

**Issue by thiagosbrito** [cytoscape/cytoscape.js#840]
Hi guys, i did the implementation exactly as you guys said on the docs, but when i called my service and it returned over 70K nodes with its respective edges, the browser died. Could you guys help me out?!

**Comment by maxkfranz** [comment]
You can see the docs re. performance to maximise your performance for large graphs: http://js.cytoscape.org/#performance

Depending on your particular machine, OS, and browser, your machine may not be able to handle the rendering of the entire graph.  You can show subsets of interest using a primary headless graph and a smaller display graph, for example.

**Comment by thiagosbrito** [comment]
Tnx Max. Sorry , but it was an back end issue, we are working with neo4j, and there where a problem. But now it's solved.

Tnx by the way!!
