### ISSUE TITLE
Issue with edge hit detection when removing/adding edges with mappers (ele index out of sync)

### ISSUE THREAD

**Issue by jsalankey** [cytoscape/cytoscape.js#841]
JSBIN: http://jsbin.com/rugexuwife/1/edit?js,console,output

In this JSBIN, I have edge1 and edge2 variables referencing the edges on the graph. I added a mouseover/mouseout handler to add and remove the highlight class. If you type in the console edge1.remove() then edge1.restore(), then hover over the edges, you get erratic behavior. The highlighted style will be applied randomly to both edges. This also appears to affect edge selection in this state.

Looking a little deeper, the renderer seems confused about which edge is where. The renderer.findNearestElement() calls are finding both edge elements, seemingly at random, when hovering over only 1 edge on the graph and triggering events from them that the listener catches and highlights from. The listener is just doing what its told, the incorrect element is occurring earlier in the renderer call (I believe).

Interesting findings:
* It only happens with the first edge in the collection. Starting with a fresh BIN and doing edge2.remove() and edge2.restore() does not cause the problem.
* It only happens with the 'content': 'data(title)' style rule on the highlighted style. It does not happen if the mapper is on the static edge class.

**Comment by maxkfranz** [comment]
Not an easy one to hunt down, but I think this will do it.

Snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-c41469fc3e-1425590577465.zip
