### ISSUE TITLE
Dagre seems to have problems with compound nodes

### ISSUE THREAD

**Issue by Braintelligence** [cytoscape/cytoscape.js#844]
In my source code right now, if I use layout: { name: 'cose' } I can use compound nodes without problem.

If I set it to 'dagre' I get

Uncaught Error: Node 'Test' is not in graph

whereas 'Test' is the parent node of several other nodes.

Without parent nodes however, 'dagre' works.

Any ideas? =/

**Comment by Braintelligence** [comment]
Perhaps this could be related to having parent nodes which have edges to their childs? It seems only 'cose' is able to handle this?

**Comment by maxkfranz** [comment]
Dagre is not a compound layout.  It assumes a traditional graph and ignores compound parent nodes.

You'll have to use some other organisation and/or manual layout applications (e.g. passing only the traditional subgraph to Dagre and then handling compounds yourself).

**Comment by maxkfranz** [comment]
Snapshot that may help with the error message, but won't handle compounds for you: http://js.cytoscape.org/download/cytoscape.js-snapshot-337f380026-1425314100329.zip

**Comment by maxkfranz** [comment]
Closing for now; re-open if further issues

**Comment by Braintelligence** [comment]
Thank you very much. I seem to have missed that not all layouts support compound nodes. From what I gather, I think I won't use compound nodes then.
I will experiment a bit with your snapshot though for broadening my experience with cytoscape.js.

**Comment by maxkfranz** [comment]
It should function correctly more or less, but I think it assumes autosized parent nodes.  Otherwise, there is no way for layouts like this to position parent nodes.

**Comment by Braintelligence** [comment]
I get what you mean. I think I may have misunderstood the concept of compound nodes, anyway. I thought it was a means to visualize trees (with their parent and child nodes and such), but using compound nodes had brought issues up, that I am not yet experienced enough to solve by myself.

Relying on the "traditional" nodes is sufficient for my purpose for now, though. Cytoscape.js is a great tool :).
