### ISSUE TITLE
Doubleclick-Input

### ISSUE THREAD

**Issue by Braintelligence** [cytoscape/cytoscape.js#845]
Is it possible to catch doubleclicks, so a single click triggers a different event than doubleclicks?

**Comment by maxkfranz** [comment]
I think doubleclicks are often bad for modern UI (especially considering there is no good analogue on touch etc.).  If you really want, you could:

(1) Listen to click events.  Store the time and element ID.

(2) If a click event happens with the same ID as previous within your desired time threshold, then `.trigger('dblclick')`.

You can use custom events as much as you like, though I don't think it's a good idea for doubleclicks to be a part of the library.  They're bad UI/UX even on desktop.

**Comment by Braintelligence** [comment]
Thank you very much for answering. In this case I'll implement the needed functionality via cxtmenu.
