### ISSUE TITLE
expanding/collapsing compound nodes in cystoscape,js 

### ISSUE THREAD

**Issue by nellaiiyappan** [cytoscape/cytoscape.js#846]
Hi,

Is there is option of expand  and collapse the compound nodes with the child nodes?
While drag a node  and drop into some compound nodes it does not returns the compound node id on target id
Please advise me on this
Thanks
H.Iyappan.

**Comment by maxkfranz** [comment]
You can do that however you want, e.g. with classes like `collapsed`.  That's app-level functionality, rather than library level.

As for dragging and dropping, that's again app-level functionality that you would have to implement.
