### ISSUE TITLE
Edge crossing point

### ISSUE THREAD

**Issue by devradhika** [cytoscape/cytoscape.js#847]
In cytoscape.js when edges are crossing each other then the crossing point should be a white space or dotted/dashed line should appear only at the cross point location. 
Like:
![demo](https://cloud.githubusercontent.com/assets/10286985/6479208/add6945e-c267-11e4-9318-1db748c174e7.png)

**Comment by maxkfranz** [comment]
That seems like a matter of aesthetic taste, but it could certainly be an option.  Other usecases, like semitransparent edges, would probably be better suited to how things are now.
