### ISSUE TITLE
Reorganize items on zoom changes

### ISSUE THREAD

**Issue by thiagosbrito** [cytoscape/cytoscape.js#848]
Hi Guys,

I was looking on the docs, and i wasn't able to find any solution for when we change the zoom level, either to higher or lower level, we get and image zoom, i expected something like google maps behavior. If you get a zoom with higher level, the cytoscape itself reorganize the items that's is over just like the makers on the g-maps!

Tnx again

**Comment by maxkfranz** [comment]
You could do this by binding on zoom, e.g. with Lodash:

```
cy.on('zoom', _.debounce(function( e ){
  cy.batch(function(){ // for performance
    cy.elements().removeClass('hidden')
      .stdFilter( someFilterFn ).addClass('shown');
  });
}, 1000/30));
```

**Comment by thiagosbrito** [comment]
Max, first of all , thanks for your quick reply.

I'm trying to reorganize the positions and spaces using this:

cy.on('zoom', function (e) {
            
            var dim = 20 / cy.zoom();
            var edgeWidth = 5/ cy.zoom();

            cy.$('edge').css({
                'font-size': dim
            });
            cy.$('node').css({
                width:dim,
                height:dim,
                'text-opacity':1,
                'overlay-padding':edgeWidth*10
            });
          });

But i'm not getting the proper result. What's happens is, i got lots of nodes as result, and they are too close to each other, when i zoom'em  in, the space beetwen them is the same as before the zoom changed.

What you think i could do?

**Comment by maxkfranz** [comment]
Zoom is just a scaling transform, so it can't spread nodes out.  It seems as though you're trying to make nodes smaller on zoom (which may help), but you need to debounce your event callback:  Otherwise, the effect will be slow and expensive to render.

**Comment by thiagosbrito** [comment]
Thanks again, you're right, it works better now, more fluid.

I will keep working on that, and i'll let you know the results.

Tnx
