### ISSUE TITLE
Min-width for nodes

### ISSUE THREAD

**Issue by Braintelligence** [cytoscape/cytoscape.js#852]
Hi there,
I'm adjusting the width of nodes dynamically related to their content.

If the content is very short the nodes look a little bit ridiculous.

I want to set a min-width to nodes, is this implemented? Can't find it in the documentation.

**Comment by ktei** [comment]
@Braintelligence you can adjust your graph by setting zoom level (`cy.zoom(2)` for example).
I think cytoscape automatically adjusts zoom level as per the number of nodes, but it does that in a very generic way.

What I did in my project is to count the nodes of the graph and based on that, I set zoom level. When you see the node size gets ridiculously large, you can check cy.zoom(), and 100% you'll get a very big number, which means you just need to scale it down. Hope this helps ; )

**Comment by maxkfranz** [comment]
@Braintelligence No, because nonparent nodes have fixed size based on your stylesheet specification.  You could calculate the min value and use that manually, or in `unstable`/2.4 you could do that calculation in a functional specification for the `width` style property.

**Comment by Braintelligence** [comment]
I'm not sure if we're talking about the same thing guys.
Let me try to explain:

Right now I have a function that changes all width values of nodes such that their label, that is being displayed within the node, is visible.

What bothers me is that nodes with very short names become very very narrow-elliptic and look strange. I want them to have a minimum width so that they at least are a perfect circle when the content is short.

I could achieve this by making my width function such that it never returns less than width X or with a css min-width that Cytoscape.js does not support. I'm asking whether Cytoscape.js might support this CSS command in the future.

**Comment by maxkfranz** [comment]
I don't think it would support that property, as it would be more flexible to specify a function to `width` in 2.4.

**Comment by Braintelligence** [comment]
Ok then I'll just change my function :). Thanks.
