### ISSUE TITLE
String stylesheet : error message : `core` invalid

### ISSUE THREAD

**Issue by MissChocoe** [cytoscape/cytoscape.js#856]
When using the textureOnViewport option, the background becomes grey when moving the viewport. It would look better if it would be white as the canvas is.

**Comment by maxkfranz** [comment]
You can style this: http://js.cytoscape.org/#style/core

outside-texture-bg-color : The colour of the area outside the viewport texture when initOptions.textureOnViewport === true.
outside-texture-bg-opacity : The opacity of the area outside the viewport texture.

**Comment by MissChocoe** [comment]
I did tried that, but the issue I got the following error message "The selector `core`is invalid". 

In my cycss file I have the following:
core {
 outside-texture-bg-color: #fff;
}
node {
more styling
}

**Comment by MissChocoe** [comment]
In case someone has the same issue than me... it works. You do have an error message in the console telling your the "core" selector is invalid, but changes will be done anyway.

**Comment by maxkfranz** [comment]
Needs error msg fix
