### ISSUE TITLE
Limit graph

### ISSUE THREAD

**Issue by Giant2** [cytoscape/cytoscape.js#857]
I have a graph with preset layout. The user can move the node in the area.
I need to limit the moving area because if a node is positioned out the visible area I cannot move it anymore.
The idea I had is to intercept the mouse after the "drop" and, if the drop is out of the area (position with negative number) cy.resize() and cy.fit()
Is this the correct way to limit the movements? How can I intercept this kind of "drop" event?
Thanks!

**Comment by maxkfranz** [comment]
You can set the position of a node via `node.position()` inside the viewport extent (i.e. `cy.extent()`) on `free` events.

**Comment by Giant2** [comment]
Thanks for the answer, but with the version I use 2.2.12 xy.extent doesn't exist.
Is there any other manner to take the bounds of the viewport?

**Comment by maxkfranz** [comment]
I would either upgrade or copy the implementation for `cy.extent()` as an extension in your app otherwise.

**Comment by Giant2** [comment]
Ok, I upgrade and patch my code. But I see the number passed in node.position() are not taking care of the eventual label (content) displayed with the node.
Is there a manner to take care even of this?

**Comment by maxkfranz** [comment]
http://js.cytoscape.org/#collection/position--dimensions/eles.boundingBox

**Comment by Giant2** [comment]
Good! Is there an example of use?
In my case I need all the 3 options to true, but how can I do?
