### ISSUE TITLE
Recommended layout for large networks; Cose layout not working

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js#858]
Hi, I am using cytoscapeJS to generate network graphs. My usual graphs have 100-200 nodes and edges and can be rendered well using the CoLa, Arbor and Cose layouts. However for larger networks (500+ nodes and edges), Cose layout does <u>not</u> work and the web page with the cytoscapeJS container freezes.

Is there a recommended layout to handle larger networks and is <b>Cose</b> layout not ideal for it ?

**Comment by ktei** [comment]
@AjitPS Layout is very resource-consuming. When the number of nodes reaches to a level like 500+, even if you run the algorithm in a compiled language, Java, C#, etc, they are very slow as well. Maybe the goal is not to find a faster layout, but to find a way to enhance user experience. For example, consider clustering similar nodes into a big node.

**Comment by AjitPS** [comment]
@ktei Thanks for your feedback. I will look into clustering similar nodes into bigger nodes while using Cose layout.
