### ISSUE TITLE
$$.heapfn.delete causing errors on some browsers

### ISSUE THREAD

**Issue by mooshben** [cytoscape/cytoscape.js#860]
$$.heapfn.delete is causing browser exceptions on some browsers since the word "delete" is a special javascript operator.

The error is:
Identifier expected

Please consider maybe using $$.heapfn["delete"] instead.

**Comment by maxkfranz** [comment]
The function just ought to be renamed, e.g. `.del()` or `.remove()`.

**Comment by maxkfranz** [comment]
Renamed to `.remove()`
