### ISSUE TITLE
CytoscapeJS touch devices gestures

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js#861]
Hi, I can use cytoscapeJS to generate and view network graphs on my tablet. However, I cannot perform multi-finger <b>hold+ click</b> Touch gestures.

The cytoscapeJS website states:
<i>'selectionType' is set automatically for you based on the type of input device detected. On touch devices, 'additive' is default — a new selection made by the user adds to the set of currenly selected elements. On mouse-input devices, 'single' is default — a new selection made by the user becomes the entire set of currently selected elements (i.e. the previous elements are unselected).</i>

I also saw the following code at http://js.cytoscape.org/#core/initialisation :
<code>selectionType: (isTouchDevice ? 'additive' : 'single'),</code>

How is the value for 'isTouchDevice', i.e., detecting a touch device, determined ? Can I use it allow for separate gestures and events on both touch and desktop devices ?

**Comment by maxkfranz** [comment]
You tap to select.  You don't tap and hold.  If you want nonstandard behaviour, you can bind to `taphold` and change selections using the API.

**Comment by AjitPS** [comment]
I am using CytoscapeJS along with the circular context menu (<b>cxtmenu</b>) plugin. For desktop users, left click using a mouse shows node ID and other attributes while right click brings up the context menu where they can then select a particular menu item to perform some function. 
For touch devices, tapping on a node brings up its details but I need to to bring up the context menu on <b>taphold</b> and then clicking on a menu item should perform a specific function.

**Comment by AjitPS** [comment]
@maxkfranz Thanks for your reply. I will look into binding actions to <code>taphold</code>
