### ISSUE TITLE
text-max-width style change not triggers calculateLabelDimensions

### ISSUE THREAD

**Issue by ktei** [cytoscape/cytoscape.js#864]
The scenario is like this:
Suppose you have already rendered the graph but later on you changed **text-max-width**, which, in theory should have an effect on how label text gets wrapped, e.g. if the value gets smaller, then wrapped text should have be in more lines, vice versa.

Currently, after applying a new style (`cy.style(....)`), the wrapped text doesn't get changed at all, or we can say it does not respect text-max-width once the graph is rendered.

There are more than one functions mattered here:
`getLabelText`
`recalculateRenderedStyle`
`calculateLabelDimensions`

I have some code to fix this (not sure it's the best fix though) and I'll put up the pull request soon, but I'd like to discuss with you.

@maxkfranz what do you reckon?

**Comment by maxkfranz** [comment]
I think it has to do with the style/label key, so this should probably fix it.

**Comment by maxkfranz** [comment]
Closing; re-open if still an issue

**Comment by ktei** [comment]
Thankx @maxkfranz I think the fix works.
