### ISSUE TITLE
Any way to further improve performance of animation when animating positions of more than a few nodes?

### ISSUE THREAD

**Issue by ktei** [cytoscape/cytoscape.js#867]
Scenario is:
I have about 131 nodes and 143 edges, now I calculate a layout in backend and pass all the positions to front-end, using `animate` function to animate each node to their new position. It's working fine but obviously not as smooth as when there are 20-50 nodes and edges. Note that I do have some styles for the nodes, for example, image background, autorotate labels with background etc. However, I'm wondering if we can still further improve the performance as 120+ nodes/edges are a lot but surely not **that** many.

Is there any way (or even some suggestion to change source code) to improve the animation performance, given the precondition that I won't lose my styles? Thank you

**Comment by maxkfranz** [comment]
The style is the bottleneck, so you can't avoid simplifying the style if you care about performance.

See http://js.cytoscape.org/#performance

Also consider simplifying the style during the animations and then restoring the complex style afterwards -- with a class.

**Comment by ktei** [comment]
@maxkfranz Thank you very much.
