### ISSUE TITLE
Question regarding select/unselect

### ISSUE THREAD

**Issue by ktei** [cytoscape/cytoscape.js#868]
We know that you can do eles.select() and ele.select(), but is there any performance difference?
For example:
Will `eles.select()` be faster than `foreach eles do ele.select()`? I'm assuming `eles.select()` will just do one redraw but `foreach ele.select()` will redraw many times depending on the number of elements?

**Comment by maxkfranz** [comment]
For performance, either

(1) Batch, forEach ele, select

(2) Build a collection, select

Otherwise, you can trigger more than one redraw etc for large graphs.

**Comment by ktei** [comment]
Thank you @maxkfranz
