### ISSUE TITLE
d3 + jsdom + nodejs + cytoscape

### ISSUE THREAD

**Issue by shotlom** [cytoscape/cytoscape.js#873]
Hi 
I managed to get d3.js working with jsdom so I can output an SVG from a terminal window using nodejs.  https://gist.github.com/shotlom/3f2456bc165e087abfab

I've tried adding cytoscape.js from npm as a dependency and require('cytoscape'). I was hoping to use the "window.document.querySelector('#dataviz-container')" selector like the code below for the container.

but cytoscape is expecting  "document.getElementById('cy')"

Excuse my naivety, but what's a way to get this to work?

var cy = cytoscape({
  container:  window.document.querySelector('#cy'),
  style: [
    {
      selector: 'node',
      css: {
        'content': 'data(id)',
        'text-valign': 'center',
        'text-halign': 'center'
      }
    },
    {
      selector: '$node > node',
      css: {
        'padding-top': '10px',
        'padding-left': '10px',
        'padding-bottom': '10px',
        'padding-right': '10px',
        'text-valign': 'top',
        'text-halign': 'center'
      }
    },
    {
      selector: 'edge',
      css: {
        'target-arrow-shape': 'triangle'
      }
    },
    {
      selector: ':selected',
      css: {
        'background-color': 'black',
        'line-color': 'black',
        'target-arrow-color': 'black',
        'source-arrow-color': 'black'
      }
    }
  ],
  
  elements: {
    nodes: [
      { data: { id: 'a', parent: 'b' } },
      { data: { id: 'b' } },
      { data: { id: 'c', parent: 'b' } },
      { data: { id: 'd' } },
      { data: { id: 'e' } },
      { data: { id: 'f', parent: 'e' } }
    ],
    edges: [
      { data: { id: 'ad', source: 'a', target: 'd' } },
      { data: { id: 'eb', source: 'e', target: 'b' } }
      
    ]
  },
  
  layout: {
    name: 'cose',
    padding: 5
  }
});

**Comment by maxkfranz** [comment]
I suspect you have a problem with the canvas: https://github.com/tmpvar/jsdom#canvas

You may have to ask the jsdom guys for further help, as -- unless there's a specific error on the cy.js side -- then the problem is with jsdom config or jsdom itself.

**Comment by maxkfranz** [comment]
Also see https://github.com/tmpvar/jsdom#what-standards-does-jsdom-support-exactly

jsdom seems to be limited in what it supports, so while getting trivial d3/svg output is easy, I suspect that more sophisticated visual output will be difficult for jsdom.

You might have better luck with PhantomJS: http://phantomjs.org/

See also:

- https://github.com/andrey-p/ectoplasm-js
- https://github.com/deanmao/node-chimera
