### ISSUE TITLE
Tuning the breadthfirst layout

### ISSUE THREAD

**Issue by sylvain-hamel** [cytoscape/cytoscape.js#874]
Hi,

Thanks for the library. I'm only getting started but it looks awesome.  

Using `breadthfirst` I get this result:

![bfr](https://cloud.githubusercontent.com/assets/1754010/6742600/6c99318e-ce67-11e4-9362-96a62e297294.png)

I'm looking for something closer to this:

![aftr](https://cloud.githubusercontent.com/assets/1754010/6742602/6f220822-ce67-11e4-9839-72572a1173fb.png)

Are there options (or another type of layout) that will get me there?

**Comment by maxkfranz** [comment]
You may be interested in Dagre : http://js.cytoscape.org/#layouts/dagre

**Comment by maxkfranz** [comment]
Closing for now; re-open if Dagre does not meet your requirements

**Comment by sylvain-hamel** [comment]
@maxkfranz Dagre works great, thanks.
