### ISSUE TITLE
Apply css for nodes and edges from external css file for cytoscape graph

### ISSUE THREAD

**Issue by gsateesh28** [cytoscape/cytoscape.js#879]
I am using angularjs , cytoscapejs to create a network topology graph. I want to use external css file for giving styles for nodes and edges of the graph instead of giving css in controller js file.

for now iam giving like below: 
style: cytoscape.stylesheet()
                        .selector('node')
                        .css({
                            'shape': 'data(typeShape)',
                            'width': '120',
                            'height': '90',
                            'background-color': 'data(typeColor)',
                            'content': 'data(name)',
                            'text-valign': 'center',
                            'color': 'white',
                            'text-outline-width': 2,
                            'text-outline-color': 'data(typeColor)'
                        })
                        .selector('edge')
                        .css({
                            'width': '10',
                            'target-arrow-shape': 'triangle',
                            'source-arrow-shape': 'triangle'
                        })
                        .selector(':selected')
                        .css({
                            'background-color': 'black',
                            'line-color': 'black',
                            'target-arrow-color': 'black',
                            'source-arrow-color': 'black'
                        }).....

is there a way to get css from external css file.

**Comment by maxkfranz** [comment]
Use the string format or JSON format: http://js.cytoscape.org/#style/format

Use AJAX to pull the file down prior to init.  You can use promises in 2.4 to make this more concise.

**Comment by gsateesh28** [comment]
i have tried by giving something like

node {
  background-color: green;
}

in my styles.css file but it doesn't work.

**Comment by maxkfranz** [comment]
See http://jsbin.com/gist/f64e811fc3311414e083?js,output

**Comment by akhilcb** [comment]
I am new to cytoscape and has same issue. Is there a working example? Above URL is not working. 

I would also like to add something like 
```
node {
   background-color: green;
}
``` 
in a .less file but couldn't figure out how to do it. Right now the node's background-color has to be defined in js file.
