### ISSUE TITLE
Zigzag edges

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#882]
Example zigzag broken on the x-axis:

![e829d164-edbc-11e3-86b9-ffdc3729a7d4](https://cloud.githubusercontent.com/assets/989043/6830028/a11ebc46-d2ed-11e4-8813-58e091481541.png)

Ref : https://github.com/cytoscape/cytoscape.js/issues/359#issuecomment-45379591

**Comment by ktei** [comment]
This is really nice! Will developers have the control of the zigzag points? And on a second thought, how would it look like once the user starts to drag its nodes?

**Comment by maxkfranz** [comment]
A zigzag goes straight along the x-axis and the y-axis.  A zigzag is broken along one axis to accomodate movement along the other axis.

Properties:

* `curve-style : zigzag` (add'l value)
* `zigzag-break : long | short | x | y` (breaks the shorter line by default)
* `zigzag-break-position` : distance in px, em, or % to break from source to target

Issue: If multiple zigzags exist between a source and target, then they will perfectly overlap.  Thus, there will probably need to be a `zigzag-step-size` or similar to stagger the zigzag egdes.

**Comment by ugurdogrusoz** [comment]
Why not just implement bend points (arbitrary points that the users can set) as basis and let the users decide and ensure specific styles like zigzags? I mean people might want to have bend points that aren't orthogonal.

**Comment by maxkfranz** [comment]
Unless the edge bends are defined in position relative to the source and target, the behaviour is different:

Whereas a zigzag automatically updates relative the the source and target positions, an edge bend would not (as it would have its own global location).

**Comment by maxkfranz** [comment]
And I'm not sure if the additional expense of the bend points would be good for this case.  I suppose we'll have to see later and benchmark.

**Comment by HopefulLlama** [comment]
What's the plan regarding this issue? This would be a really good feature, and probably the last point of argument around which library to use.

**Comment by maxkfranz** [comment]
The same visual effect for fixed position graphs can be achieved today using straight bends / segment edges.

Zigzag edges need to be explored more in terms of usecases and visual style properties.  The previously proposed properties are probably not sufficient.

**Comment by maxkfranz** [comment]
Here's a preview:

![screen shot 2019-02-19 at 5 12 38 pm](https://user-images.githubusercontent.com/989043/53051347-a8d12500-3469-11e9-8f8f-b4946a007a50.png)

Another ticket will have to be created for this feature, as the API design for the right-angled edge style has changed quite a bit.  There are still some edgecases to consider and general additions to make before this gets merged in.  

To be clear, this particular edge style will mostly be useful for trees (and possibly some types of DAGs) that are well laid out.  It will not allow for an arbitrary number of right-angled corner points.

**Comment by maxkfranz** [comment]
This issue has been superseded by "Taxi edges #2306"
