### ISSUE TITLE
`arrow-scale: multiplier` to control arrow size with a multiplier

### ISSUE THREAD

**Issue by rwu823** [cytoscape/cytoscape.js#884]
In current  feature set the edge's CSS `width` able to adjust line and arrow's size. But how to adjust the arrow's size only?

**Comment by ktei** [comment]
@rwu823 I don't think there is such setting at the moment, but you can simply implement it yourself and even do a pull request ; )

Find this file: src/extensions/renderer.canvas.arrow-shape.js and then find this line:
```javascript
draw: function(context, size, angle, translation) {
```
(around line 341, there are multiple draw functions, so make sure you find the arrow draw function)

Then you can change the `size`. I customized it to fit my project like this: `size = 10`, which might not be your requirement, but you got the idea. After that, remember to rebuild cytoscape using `gulp build`.

**Comment by maxkfranz** [comment]
Currently, there's a bug making this not possible.  I added the feature to the temporary `arrowsize` branch, since the feature itself is simple.  However, the bug makes tapping edge arrows impossible for larger arrows.

If you can fix the branch, it could be merged to unstable for 2.4.  If not, it will have to wait for some later version.

**Comment by maxkfranz** [comment]
The issue has been fixed for 2.5, so it should be possible to add this for 2.6.  Adding to milestone

**Comment by jelmerjellema** [comment]
I implemented this for our project in 3 changes to the 2.7.9 source tree. It just adds a arrow-resize: number style property for general resizing of arrows. I use it as:
`edge {
  arrow-resize: 2.5
}`

So it just gives me bigger arrows all along. 

I see no issues with selecting the edge.

Should I push this somewhere?  It quite trivial anyway.

**Comment by maxkfranz** [comment]
@jelmerjellema Yes, that would be great!  Please make a PR on the `unstable` branch, which is used for new versions.  Maybe it should be called `arrow-scale` rather than `size` or `resize` for clarity?  Thanks

**Comment by jelmerjellema** [comment]
I'm sorry @maxkfranz. This slipped my attention. As a bitbucket mercurial user I don't know how to create a PR or what to put in it. Can I just send a patch or something and work from there. Love to help!

**Comment by maxkfranz** [comment]
@jelmerjellema If you [fork the repo](https://github.com/cytoscape/cytoscape.js/issues/884#fork-destination-box), any changes that you push to your fork's git repo can be made into a pull request on Github.  You just click the pull request button on your repo's page.  [(More info)](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

Thanks!

**Comment by ugurdogrusoz** [comment]
Any progress on this? We really need this feature. Thanks.

**Comment by bruno314** [comment]
@jelmerjellema  Could you please upload (pastebin.com, or any other service) the file you've changed for arrow-resize feature? We would greatly appreciate your feature as we could use it as well. 

Additaionaly, If you want, I can open PR (with you in credit as original author). But it's OK if you prefer not to.

Thanks and good luck!
Bruno

**Comment by jelmerjellema** [comment]
I'm sorry for my incommunicado, I've been very busy lately and as I said, I don't have any experience with GIT or PR's. I'm a mercurial type. 

It's really literally 3 lines of code. So maybe this will work? I attach the files that changed. If you search for <SIHW> you will find the additions that I have done. In this code, the css property I added is called sihw-arrow-resize. (sihw is the abbreviation of my company name Spin in het Web). As @maxkfranz said, maybe arror-scale is a better name?

If that's not enough, maybe you can tell me how to do the PR.

I don't need the credits, but I'm not against them either. Your call ;-)

So here's the "code". Can you work with this? If not, I promise I now will make free some time to do the PR.

Again, sorry for the delay.

Best, Jelmer

[sihw-patches.zip](https://github.com/cytoscape/cytoscape.js/files/584505/sihw-patches.zip)

**Comment by maxkfranz** [comment]
@ugurdogrusoz Would one of your students be able to search/diff @jelmerjellema's zip file and make a pull request from it?

**Comment by jelmerjellema** [comment]
Again: it's 3 lines of code. If you give me the steps, I will do it. I'm just too busy right now to play with it for half a day...



Max Franz <notifications@github.com> schreef op 11 november 2016 21:28:35 CET:
>@ugurdogrusoz Would one of your students be able to search/diff
>@jelmerjellema's zip file and make a pull request from it?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cytoscape/cytoscape.js/issues/884#issuecomment-260048322

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ugurdogrusoz** [comment]
@metincansiper please create a PR for this

**Comment by maxkfranz** [comment]
@jelmerjellema Basically, you create a fork and commit your changes in the fork.  Then use the PR UI: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by metincansiper** [comment]
@ugurdogrusoz , @maxkfranz , @jelmerjellema I created the PR please see #1606. I named the new style property as 'arrow-scale' as @maxkfranz  suggested. However, I could not test it. @jelmerjellema would you check the differences in my commit to see if there is a problem?

**Comment by jelmerjellema** [comment]
@metincansiper Nice, thank you! There seems to be on line missing. In properties.js there is another line (in my zip file line 425) that needs to be added, to add the property to the property map.

**Comment by metincansiper** [comment]
@jelmerjellema thaks for notifing me. I added that line. Please, would you check again to see if it is okey now?

**Comment by JoshB29** [comment]
Hi, Has this been fixed. I am using cytoscape and cannot figure out how to change the arrow size without changing the edge width

**Comment by maxkfranz** [comment]
arrow-scale http://js.cytoscape.org/#style/edge-arrow
