### ISSUE TITLE
Is it possible (to add a feature) to bend edges?

### ISSUE THREAD

**Issue by ktei** [cytoscape/cytoscape.js#885]
I know this won't be an easy feature, but still want to ask:
Is that possible to bend edges? For example, click on an edge and drag it, which will change the curve (making it more curve or less curve)? 

To be honest at first I thought I'd just implement this and contribute it back, but it turns out I don't really know how to do it.

Is there any plan to implement this for cytoscape? That'll be awesome!

Thanks

**Comment by maxkfranz** [comment]
As this is an app-level, editor-like feature, it should be an extension.  There are already properties that allow for manual configuration of the bezier edge control points, so you'd just have to visualise those points and allow for dragging those points.

**Comment by ktei** [comment]
@maxkfranz Thank you. I'll look into the bezier edge control points.

**Comment by maxkfranz** [comment]
Closing for now
