### ISSUE TITLE
Remove eles.show() and eles.hide() from the API

### ISSUE THREAD

**Issue by atiasnir** [cytoscape/cytoscape.js#886]
I've got a few hidden nodes and edges in my network. 

When I serialize the network into a json (`data = cy.json()`) these elements do not serialize their style (in particular `display: none;` is not serialized). Thus, when loading the network again (for instance with `cy.add(data.elements)`), the elements will be visible. 

A hack would be to add the "hidden" attribute to the JSON, for instance:
1. In `$$.elesfn.json` add `hidden: ele.hidden()` to the `var json = $$.util.copy({...})` block.
2. In `$$.Element` add `if( params.hidden ) { this.hide(); }` at the very end of the function.
(in fact, that's my quick workaround for this) 

I'm guessing there's a more refined way of accomplishing this (I'm not even sure if this breaks compatibility with the desktop version regarding the JSON exchange).

**Comment by maxkfranz** [comment]
You shouldn't expect bypassed style to be serialised.  Use a class or data instead.

This has been asked before with others making the same mistake, so to avoid this in future I'm revising this ticket to remove `eles.show()` and `eles.hide()` in the next version.  Those functions are too easily abused.

**Comment by ktei** [comment]
Without eles.hide(), I assume when to hide massive elements, the proper way is:
```javascript
cy.startBatch();
for (var i = 0; i < elesToHide.length; i++) {
    var ele = elesToHide[i];
    ele.hide();
}
cy.endBatch();
```
Is this correct? I'm asking because I'm using eles.hide() in current project... but I'm not abusing it : )

**Comment by maxkfranz** [comment]
`elesToHide.addClass('hidden')` or similar

**Comment by rui-infotrack** [comment]
@maxkfranz Have you done any change about this yet? If so, could you reference the commit number here? I'd like to see the code you changed because if I merge these changes, I need to make it won't break my current project (I've been using eles.hide/show for a few places). Thank you.

**Comment by maxkfranz** [comment]
It's a docs-only change for backwards compatibility.
