### ISSUE TITLE
Show hide node label on nodes in cytoscapejs graph

### ISSUE THREAD

**Issue by gsateesh28** [cytoscape/cytoscape.js#889]
I will add a check box to display id / name as node label or to hide label on nodes in cytoscapejs graph.
but instead of refreashing the cytoscape graph how to change the labels on nodes.

**Comment by maxkfranz** [comment]
Add a class that has `content` with the empty string.

**Comment by mkelly1495** [comment]
This does not work. Setting the content to `''` or `""` in the css file causes `''` and `""` to be displayed as the label.
