### ISSUE TITLE
Nodes and edges overlap after breadthfirst layout

### ISSUE THREAD

**Issue by skasio** [cytoscape/cytoscape.js#891]
Hi - I was looking for an option with the **breadthfirst** layout that would allow me to place child nodes directly below their parents and came across the `strictHierarchy` option.

This appears to do what I want, except that I have found a case where nodes and edges are position on top of each other.

This [jsfiddle](https://jsfiddle.net/nzyygs9c/1/) demonstrates the problem.

I would expect the result of the layout to look something like this:
![expected layout](https://cloud.githubusercontent.com/assets/1262127/6913550/8424fc7e-d7cd-11e4-8c4a-2bac02a20e14.png)

But it ends up looking like this:
![actual layout](https://cloud.githubusercontent.com/assets/1262127/6913553/8765899e-d7cd-11e4-8f2e-d83e81d97d7d.png)

Cheers,

Szymon

**Comment by maxkfranz** [comment]
(1) That option is undocumented and not meant for use.  It was planned but never implemented.

(2) Use `dagre` if you want a different layout like that.  `breadthfirst` is good at what it does -- save a lot of space for DAGs -- but `dagre` is more flexible.  There's no point in bloating the `breadthfirst` layout if `dagre` already does a better job at that usecase.

**Comment by szymonatportland** [comment]
Thanks @maxkfranz - I thought that may have been the case with the `strictHierarchy` option.

The `dagre` layout **looks** exactly like what I need except that I have a requirement to be able to set the root of the graph which is not an option with `dagre`.

**Comment by maxkfranz** [comment]
There used to be support in an early version: https://github.com/cpettitt/dagre/issues/159

It would probably help to show your interest for that feature in that ticket.
