### ISSUE TITLE
Update uglify

### ISSUE THREAD

**Issue by jsalankey** [cytoscape/cytoscape.js#895]
Cytoscape's most recent releases do not work in IE9/10 when using the minified source. I am definitely seeing this in at least 2.3.9 and 2.3.10, I have not tried 2.3.11. I get an immediate syntax error referencing line 18, character 1. I recently upgraded from 2.3.3, and the minified source for that is working in IE9/10. Swapping in the unminified source works properly in both IE versions, so the issue appears to be some incompatibility in IE's Javascript engine resulting from more aggressive minification in more recent versions.

**Comment by maxkfranz** [comment]
This hasn't changed, and [it's just using uglify with basic settings](https://github.com/cytoscape/cytoscape.js/blob/faf63dac6556af1e1afd34b3908fd5ce043b7526/gulpfile.js#L119).

Maybe updating `gulp-uglify` would help you?

Try setting `"gulp-uglify": "^1.1.0",` in `package.json`, and then:

- `npm install`
- `gulp build`

Alternatively, the minified file is just for convenience.  Your app probably ought to have its own concatenation and minification process as a part of building, and that would also give you more control.

**Comment by maxkfranz** [comment]
I've updated uglify and it should be in the next release (though you should still test manually as noted above).  If that doesn't help, perhaps you could file a bug with uglify?

You could investigate using an alternative minification mechanism for your project if you want to support old browsers, or you could serve unminified JS to old browsers.

**Comment by jsalankey** [comment]
We had just been using the dist versions for convenience and hadn't had any issues until now. We will look at building it ourselves to see if we can get around this issue. Thanks for looking at it.

**Comment by elaine-t** [comment]
We also use the dist version for conveience and ran into same issue with version 2.4.6. Did updating uglify and building yourself work for you?

**Comment by maxkfranz** [comment]
`gulp-uglify` is updated to the very latest version for unstable/2.5
