### ISSUE TITLE
Layouts on Network Subsets

### ISSUE THREAD

**Issue by starkfree** [cytoscape/cytoscape.js#896]
I'd like the ability to apply layouts to subsets of the network rather than the entire network as a whole. A couple of use cases where this would be handy:

1) **Filtered Networks** : I have a large network and to make sense of it, I apply several filters (example: hide all nodes of type X) resulting in some edges and nodes being temporarily hidden from view (but not removed permanently). It would be handy to then be able to apply a layout such as concentric, and have it redraw the network using only the subset that's currently visible. This could be done by passing the layout function the set of edges and nodes you want it to generate a layout based on, but by default it applies to the entire network which is current functionality.

2) **Selected Subsets** : If I have a complex network, with say 100 nodes, this could also be used to select a subset (say 25 of the 100 total), and perform a layout just on those 25 nodes, even with all 100 still visible. For example, I want to pull out a highly connected subset (of 25), I would highlight them all and then apply the circle or concentric layout to that subset to make it look nice, totally separate from the rest of the overall network.

**Comment by maxkfranz** [comment]
You can already do this.

See http://js.cytoscape.org/#collection/layout and http://js.cytoscape.org/#layouts/layout-manipulation

**Comment by starkfree** [comment]
Thanks, totally missed that section in the documentation. :)

**Comment by maxkfranz** [comment]
No worries; the main thing is it works for you
