### ISSUE TITLE
Diamond Node Shape?

### ISSUE THREAD

**Issue by jstaehli** [cytoscape/cytoscape.js#897]
There is a diamond shape for arrows (e.g. source-arrow-shape: diamond) but not for nodes. Would it be possible to add this shape for nodes too? This would be very useful to create a BPMN Gateway like node. Thank you very much!

**Comment by danieljue** [comment]
Actually, if we could add our own SVG shapes or FontAwesome shapes, that would be great for everyone!

**Comment by maxkfranz** [comment]
A diamond shape may be possible, though arbitrary shapes are not practical given the hittest expense.  You can use a transparent circle shape with a SVG background to simulate arbitrary shapes.

**Comment by smpaley** [comment]
I second the request for a diamond node shape.  And for the ability to add our own simple polygonal shapes.

**Comment by maxkfranz** [comment]
May be possible with Path2D and a specified SVG path: https://developer.mozilla.org/en-US/docs/Web
/API/Path2D/Path2D

e.g.

```
node.foo {
  shape: svg(M10 10 h 80 v 80 h -80 Z);
}
```

I'm not sure about browser support.  All our uses of Path2D are for performance reasons now, and have non-Path2D fallbacks.

**Comment by smpaley** [comment]
Are you saying this should work now?  I just plugged the above shape line into the Visual Style example linked to from your home page, and it didn't work on either Firefox or Chrome on my Mac.

**Comment by maxkfranz** [comment]
No, that's a proposal for 2.5 #925

**Comment by maxkfranz** [comment]
Sneaking diamond into 2.4 with some refactoring for filesize
