### ISSUE TITLE
Position from label of node with child nodes not updated when updating css-height

### ISSUE THREAD

**Issue by coastk** [cytoscape/cytoscape.js#902]
Hi all,

I need to update the height from a node which contains childs on runtime. When I update this using .css('height', x), the height is updated, but the position of the label keeps the same, and so the label is on the wrong place in the canvas. 

I reproduced the problem on http://jsbin.com/qakifinoho. The issue occures using a timeout after 2,5 seconds. After clicking on the node the label is on the right position. 

Regards,

Tjalling

**Comment by maxkfranz** [comment]
A compound node has its dimensions determined from the positions of its children.  Thus, using a bypass like that is not something that makes sense with a compound node.  In 2.4, this has been fixed such that setting a bypass of height or width on a compound fails.
