### ISSUE TITLE
terrible A* performance

### ISSUE THREAD

**Issue by makc** [cytoscape/cytoscape.js#904]
Hello, I have this graph built from mesh, 6386 nodes, 16764 edges, and trying to use A* on it using cytoscape headless mode. So far it sort of works:

![](http://i.imgur.com/rhTBz7R.png)

although I am not convinced that the path it finds is actually shortest (I did save the distance between nodes on edge.data and using that number as an edge "weight"). The main problem is that a* times are anywhere between 3 to 45 seconds. Another (flash) app they have does the same thing (a* on compareable mesh) instantly, so I don't think the graph is impossibly big.

The question, therefore, is: is there any trick to improve cytoscape performance, or is it for pretty demos only?

**Comment by makc** [comment]
FF profiler seems to suggest the most of the time is spent working with node selectors?

![](http://i.imgur.com/EXD1V1p.png)

Let's see if I can get sane times by finding and passing nodes to a* myself, docs say I can do that...

**Comment by makc** [comment]
Negative, these .filter calls do not come from a* argument selectors, they are called somewhere inside. No way to get rid of them?

**Comment by makc** [comment]
Probably these:
```javascript
      // Main loop 
      while (openSet.length > 0) {
        var minPos = findMin(openSet, fScore);
        var cMin = this.filter("#" + openSet[minPos])[0];
```

**Comment by makc** [comment]
Okaaaay, so doing this
```javascript
    var elements = pathfinder.elements();
    var filter = elements.filter;
    elements.filter = function (str) {
        if (str.charCodeAt && (str.charCodeAt(0) == 35)) {
            return nodes[str]; // my cache
        }
        return filter.call (this, str);
    };

    var result = elements.aStar ({
```
improves my performance by the order of 10x, but still some long paths take up to 4 seconds. I don't know, there seems to be nothing else I can do.

**Comment by maxkfranz** [comment]
Try this snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-cc9a7daba3-1428695297822.zip

This does away with all selectors in all the advanced algorithms.  It also has some other changes that probably should speed things up at least a bit.  The `getElementById()` call in lieu of your change should be even faster, as no iteration is required.

**Comment by maxkfranz** [comment]
For more advanced changes, it would probably be necessary to do some more detailed profiling and make more extensive changes -- if extensive, I would leave those changes to the soon upcoming 2.4.

**Comment by makc** [comment]
This is good improvement, although I feel it could still be better. Magenta and cyan paths here
![](http://i.imgur.com/ccNpXBP.png)
take 0.38 and 0.96 seconds now (roughly 50x speedup). Here is updated profiler screenshot:
![](http://i.imgur.com/DJChVXO.png)

**Comment by maxkfranz** [comment]
So at this point it looks like it's just the cost of creating new collection objects each time one of the API functions like `.filter()` or `.connectedEdges()` is called.  Certainly creating a lot less objects would make this faster, though that would require replacing each API call with a manual replacement using arrays.  Using plain arrays would be cheaper, but it would probably only make at most a 15% overall improvement at the cost of making the code much less readable.  Perhaps in-place filtering could make an improvement in some cases without sacrificing readability.

See also https://github.com/cytoscape/cytoscape.js/issues/770.  If you could provide some large test data for benchmark tests, it would help in creating those benchmarks -- which would be important for performance testing for minute changes.

Closing this ticket for now, as #770 will be necessary for measuring and validating improvements beyond what we have already.  And I don't want to make substantial changes to a bugfix release on 2.3.x.

**Comment by maxkfranz** [comment]
i.e. you want to discuss this case further, please use #770

**Comment by makc** [comment]
> If you could provide some large test data for benchmark tests, it would help in creating those benchmarks

just use any 3d mesh off the net :wink: e g [this](http://www.123dapp.com/3dsc-Sculpt/rose/1495203) tshirt has 48386 vertices (nodes) and 96768 triangles (so by euler formula that should be around 145 thousands edges) - that's about 8 times more than in my case. should be pretty good for benchmark. also ["obj" format](http://en.wikipedia.org/wiki/Wavefront_.obj_file) is plain text with numbers so you will have no problems to parse.
