### ISSUE TITLE
Layout 'dagre' has overlapping compound nodes

### ISSUE THREAD

**Issue by marcpopp** [cytoscape/cytoscape.js#912]
I'm using cytoscape.js to map a network/application layout. The layout 'dagre' is nice an clean and works with most stuff. But there is one use case were it doesn't

It looks like that:
![image](https://cloud.githubusercontent.com/assets/5837636/7296913/40d3ff52-e9c4-11e4-8144-ff6b733feae2.png)
JSBin Source: http://jsbin.com/haguwahanu/5/edit

Idealy the compound nodes should not overlay like this:
![image](https://cloud.githubusercontent.com/assets/5837636/7297029/34767284-e9c5-11e4-8094-a77d35fc8d7f.png)

I'm willing (and I'm getting paid) to help implementing it, but I have no idea where to start and what to do. It would be very nice, if somebody could point me in the right directions.

Thank you very much
Marc

**Comment by maxkfranz** [comment]
The version of dagre that 2.3.x supports does not support compounds.  You'll need to use unstable or wait for 2.4.

**Comment by maxkfranz** [comment]
See https://github.com/cytoscape/cytoscape.js/issues/859
