### ISSUE TITLE
Circle layout - set radius (reducing edge Length)

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js#919]
How do I reduce the radius for the circle layout. My current graph has the circle layout but with a very large radius, leading to very long edges. Is there a way to ensure smaller edge lengths or reduce the radius of the circle layout ?

My current circle layout code is:
` var circLayout= {
       name: 'circle', fit: true,
       padding: 30, avoidOverlap: true, boundingBox: undefined, 
       animate: false, counterclockwise: false,
       radius: function() { return 2; },
       startAngle: 3/2 * Math.PI
 }; `
` cy.layout(circLayout);
`

I want to run the circle layout but with the edgelengths being less, i.e., have the circle layout with a lesser radius value. However, I do not think my code for setting the 'radius' is doing it.
Any feedback would be much appreciated.

**Comment by maxkfranz** [comment]
Use a value, not a function.
