### ISSUE TITLE
Directed graphs fail to lay out in this case

### ISSUE THREAD

**Issue by dehmlowm** [cytoscape/cytoscape.js#922]
I've distilled this case as much as I can: If you have a directed breathfirst graph with three nodes where:
      nodes: [
        { data: { id: 'a' } },
        { data: { id: 'c',parent:'a' } },
        { data: { id: 'u' } },
      ], 
and a single edge
      edges: [
        { data: { id: 'au', weight: 1, source: 'a', target: 'u' } }
      ]

The graph fails to layout on line 20581: 
[Error] TypeError: undefined is not an object (evaluating 'neighbor._private.scratch.breadthfirst.index')
	(anonymous function) (cytoscape.js, line 20581)

There are three nodes:
one parent
one child
One that is not a parent or child
And one edge:
From the parent to the node that is neither a parent or a child.

Code sample:
/////////////////////////////////////////////////////////
$(function(){ // on dom ready

var cy = cytoscape({
  container: document.getElementById('cy'),
  
  style: cytoscape.stylesheet()
    .selector('node')
      .css({
        'content': 'data(id)'
      })
    .selector('edge')
      .css({
        'target-arrow-shape': 'triangle',
        'width': 4,
        'line-color': '#ddd',
        'target-arrow-color': '#ddd'
      })
    .selector('.highlighted')
      .css({
        'background-color': '#61bffc',
        'line-color': '#61bffc',
        'target-arrow-color': '#61bffc',
        'transition-property': 'background-color, line-color, target-arrow-color',
        'transition-duration': '0.5s'
      }),
  
  elements: {
      nodes: [
        { data: { id: 'a' } },
        { data: { id: 'c',parent:'a' } },
//         { data: { id: 'p',parent:'a' } },
        { data: { id: 'u' } },

      ], 
      
      edges: [
        { data: { id: 'au', weight: 1, source: 'a', target: 'u' } }
      ]
    },
  
  layout: {
    name: 'breadthfirst',
    directed: true,
    padding: 10
  }
});
  
var bfs = cy.elements().bfs('#a', function(){}, true);

  
var i = 0;
var highlightNextEle = function(){
  bfs.path[i].addClass('highlighted');
  
  if( i < bfs.path.length ){
    i++;
    setTimeout(highlightNextEle, 1000);
  }
};

// kick off first highlight
highlightNextEle();

}); // on dom ready

**Comment by dehmlowm** [comment]
This Issue goes away if you set 'a' as the root node

**Comment by maxkfranz** [comment]
Thanks. I've pushed the fix to 2.4/unstable, since that will be released in the next day or so.
