### ISSUE TITLE
Enable custom Threshold in findNearestElement

### ISSUE THREAD

**Issue by MauricioDentz** [cytoscape/cytoscape.js#923]
Due my business logic, sometimes when performing mouse/tap events, I need to be very precise or very loose, depending the occasion.

Looking through the code, the function **CanvasRenderer.prototype.findNearestElement** have a Threshold for this but is fixed in the code as follows: 

```javascript
    var edgeThreshold = (isTouch ? 256 : 32) / zoom;
    var nodeThreshold = (isTouch ? 16 : 0) /  zoom;
```
This cause some "issues" when I need to be very precise. 
Shouldn't the findNearestElement consider the **touchTapThreshold** and **desktopTapThreshold** options? or maybe enable some custom Threshold for edges and nodes?
Thanks in advance,

**Comment by maxkfranz** [comment]
Wrong place.  This is for *which* element is tapped -- not *whether* a tap is detected even with some small threshold.  Use these:

touchTapThreshold & desktopTapThreshold : A nonnegative integer that indicates the maximum allowable distance that a user may move during a tap gesture, on touch devices and desktop devices respectively. This makes tapping easier for users. These values have sane defaults, so it is not advised to change these options unless you have very good reason for doing so. Larger values will almost certainly have undesirable consequences.

http://js.cytoscape.org/#core/initialisation

**Comment by MauricioDentz** [comment]
Consider this:

**Comment by MauricioDentz** [comment]
Consider this:

**NodeA** and **NodeB** inside a **ParentNodeC**, and a **NodeD** outside.
When using the *edgehandles* plugin to create an edge between **NodeD** and **ParentNodeC**, the preview edge "flickers" sometimes because the *findNearestElement* keep changing between NodeA, NodeB and ParentNodeC, due the thresholds.
To avoid this, I changed the default values of edgeThreshold and nodeThreshold to a lower value and fixed the issue, but this is not a good solution, because it affects in other operations.
I think it would be nice to have these Thresholds configurable, or maybe I'm doing something wrong?

Ps. I realize that maybe this is a cytoscape.edgehandles plugin issue.
Thanks,

**Comment by maxkfranz** [comment]
That's a plugin issue.  I don't think it considers compounds.

**Comment by maxkfranz** [comment]
Closing for now
