### ISSUE TITLE
Request for a Tee node shape

### ISSUE THREAD

**Issue by smpaley** [cytoscape/cytoscape.js#924]
I was asked to upload an image of the Tee node shape we need.  Here it is as svg:

&lt;svg height="100" width="103"&gt;
  &lt;polygon points="10,10 100,10 100,40 70,40 70,90 40,90 40,40 10,40" style="fill:none;stroke:black;stroke-width:3" /&gt;&lt;/svg&gt;

Since I doubt this particular shape is in great general demand, it would be great if we could define our own simple polygonal shapes.  The problem w/ doing these as svg images is that then the color, thickness, etc. attributes won't take effect in any useful way (and we'll want the ability to map colors to data values, such as by using one of your mappers).

**Comment by smpaley** [comment]
Presumably this will be taken care of by #925

**Comment by maxkfranz** [comment]
Yes, but before 2.5 you could make a small fork that adds a tee node shape to the list.  You should be able to more or less just copy your points and normalise them as per the other shapes.

Closing for now in favour of #925
