### ISSUE TITLE
Polygon points as node shapes in stylesheet

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js#925]
e.g.
```
node.foo {
  shape: 'polygon';
  shape-polygon-points: '-1, -1,   1, -0.5,   1, 1,   -1, 0.5';
}
```

See : Diamond Node Shape? #897

**Comment by maxkfranz** [comment]
e.g.

```
node.foo {
  shape: svg(M10 10 h 80 v 80 h -80 Z);
}
```

**Comment by maxkfranz** [comment]
Generic SVG shapes not practical re. hittests, but polygons are OK.  Don't depend on Path2D but add to some custom node shapes list.

e.g. diamond:
```
node.foo {
  shape: polygon(0, 1, 1, 0, 0, -1, -1, 0);
}
```

**Comment by maxkfranz** [comment]
More practical syntax:

```
node.foo {
  shape: 'polygon';
  shape-polygon-points: '-1, -1,   1, -0.5,   1, 1,   -1, 0.5';
}
```

**Comment by ARBramucci** [comment]
I also want a pentagon node shape, but I am not sure where to add in this code that you posted to fix the issue? How should I go about using your code to insert a new node shape?
thanks!

**Comment by maxkfranz** [comment]
@ARBramucci, I don't know offhand.  But you could ask on Biostars.  See https://cytoscape.org/documentation_users.html
