### ISSUE TITLE
Prevent edges from crossing over

### ISSUE THREAD

**Issue by lmalik12** [cytoscape/cytoscape.js#927]
I am using a breadth first search layout to help make a graph with dynamic addition/deletion of nodes. My nodes make a tree structure which is what i want, however sometimes my edges cross over and it makes it sort of difficult to follow the nodes. 

my layout is initiated with,
({ name: 'breadthfirst',
padding: 30,
roots: ('[name="Data"]')
})

When I add a new node i simply reload the layout with all the nodes. 
I realize some cross-over will happen, but i want to prevent as much as possible.
This is what i have:
![screen shot 2015-05-06 at 11 12 41 am](https://cloud.githubusercontent.com/assets/5714255/7500174/18efc99a-f3e1-11e4-9f09-4a9eb175bda8.png)

This is what i want:
![screen shot 2015-05-06 at 11 13 48 am](https://cloud.githubusercontent.com/assets/5714255/7500189/28309c86-f3e1-11e4-832b-f0c9f7166e30.png)

**Comment by maxkfranz** [comment]
It's probably possible to at least improve this by modifying the weight sort procedure for the levels.

Do you have some sample data that could be used for testing?  It would make sure that the changes work for cases like yours.

**Comment by lmalik12** [comment]
My files are rather large, I did however modify one of the demos on the cytoscape.js page and found the edges cross over just like they do in my project.
Although this is a simplified version i hope it still gives you all the information you need.

http://jsbin.com/cuzujunexa/1/edit?js,output

From the visual (in the link above) you will notice my node View2 and View3 cross over when there is no need to do so. I would like View2 to be underneath the node it is connected(VF2) and the same with View3, just like View1 is under VF1.

**Comment by maxkfranz** [comment]
Should be addressed automatically by https://github.com/cytoscape/cytoscape.js/issues/2004

**Comment by maxkfranz** [comment]
A current refactor I'm working on for 3.3 should cover this.  It automates some cases and simplifies the code a lot.  Here's a picture of the graph that @lmalik12 posted with my latest changes (default layout options):

![screen shot 2017-10-25 at 4 58 31 pm](https://user-images.githubusercontent.com/989043/32022936-d6fbf7b0-b9a5-11e7-9771-aa88d88dc18f.png)
