### ISSUE TITLE
z-index of edges with compound nodes

### ISSUE THREAD

**Issue by kolesnikova-tavi** [cytoscape/cytoscape.js#928]
If I create a nodes' parent, the edges will be drawn on top of the nodes:
![cy1](https://cloud.githubusercontent.com/assets/3088258/7518460/aafc1ac8-f50d-11e4-8ed1-e97124365397.png)
![cy2](https://cloud.githubusercontent.com/assets/3088258/7518461/ab0503ae-f50d-11e4-8b83-4eafd3f3e930.png)

**Comment by maxkfranz** [comment]
Would you please post `cy.json()`?

**Comment by kolesnikova-tavi** [comment]
{"elements":{
    "nodes":[{
        "data":{
            "bg_color":"",
            "position":{"y":131.399993896484,"x":604},
            "name":"",
            "halign":"",
            "text":"",
            "valign":"",
            "id":"node1431016791195",
            "empty":false
        },
        "position":{"x":604,"y":131.399993896484},
        "group":"nodes",
        "removed":false,
        "selected":false,
        "selectable":true,
        "locked":false,
        "grabbed":false,
        "grabbable":true,
        "classes":""
    }, {
        "data":{
            "bg_color":"",
            "position":{"y":190.399993896484,"x":566},
            "name":"",
            "halign":"",
            "text":"",
            "valign":"",
            "id":"node1431016792502",
            "empty":false
        },
        "position":{"x":566,"y":190.399993896484},
        "group":"nodes",
        "removed":false,
        "selected":false,
        "selectable":true,
        "locked":false,
        "grabbed":false,
        "grabbable":true,
        "classes":""
    }, {
        "data":{
            "bg_color":"",
            "position":{"y":157.066660563151,"x":386.333333333333},
            "name":"",
            "halign":"",
            "text":"",
            "valign":"",
            "id":"node1431016824729",
            "empty":false
        },
        "position":{"x":382.5,"y":164.899993896484},
        "group":"nodes",
        "removed":false,
        "selected":false,
        "selectable":true,
        "locked":false,
        "grabbed":false,
        "grabbable":true,
        "classes":""
    }, {
        "data":{
            "bg_color":"",
            "position":{"y":141.399993896484,"x":331},
            "name":"",
            "parent":"node1431016824729",
            "halign":"",
            "text":"",
            "valign":"",
            "id":"nodenode1431016824729_0",
            "empty":false
        },
        "position":{"x":331,"y":141.399993896484},
        "group":"nodes",
        "removed":false,
        "selected":false,
        "selectable":true,
        "locked":false,
        "grabbed":false,
        "grabbable":true,
        "classes":""
    }, {
        "data":{
            "bg_color":"",
            "position":{"y":135.399993896484,"x":434},
            "name":"",
            "parent":"node1431016824729",
            "halign":"",
            "text":"",
            "valign":"",
            "id":"nodenode1431016824729_1",
            "empty":false
        },
        "position":{"x":434,"y":135.399993896484},
        "group":"nodes",
        "removed":false,
        "selected":false,
        "selectable":true,
        "locked":false,
        "grabbed":false,
        "grabbable":true,
        "classes":""
    }, {
        "data":{
            "bg_color":"",
            "position":{"y":194.399993896484,"x":394},
            "name":"",
            "parent":"node1431016824729",
            "halign":"",
            "text":"",
            "valign":"",
            "id":"nodenode1431016824729_2",
            "empty":false
        },
        "position":{"x":394,"y":194.399993896484},
        "group":"nodes",
        "removed":false,
        "selected":false,
        "selectable":true,
        "locked":false,
        "grabbed":false,
        "grabbable":true,
        "classes":""
    }],
    "edges":[{
        "data":{
            "source":"node1431016792502",
            "target":"node1431016791195",
            "id":"edge1431016814928_1",
            "ln_color":"",
            "name":""
        },
        "position":{},
        "group":"edges",
        "removed":false,
        "selected":false,
        "selectable":true,
        "locked":false,
        "grabbed":false,
        "grabbable":true,
        "classes":""
    }, {
        "data":{
            "source":"nodenode1431016824729_0",
            "target":"nodenode1431016824729_1",
            "id":"edge1431016807408_1",
            "ln_color":"",
            "name":""
        },
        "position":{},
        "group":"edges",
        "removed":false,
        "selected":false,
        "selectable":true,
        "locked":false,
        "grabbed":false,
        "grabbable":true,
        "classes":""
    }, {
        "data":{
            "source":"nodenode1431016824729_1",
            "target":"nodenode1431016824729_2",
            "id":"edge1431016807408_2",
            "ln_color":"",
            "name":""
        },
        "position":{},
        "group":"edges",
        "removed":false,
        "selected":false,
        "selectable":true,
        "locked":false,
        "grabbed":false,
        "grabbable":true,
        "classes":""
    }]},
    "style":[{
        "selector":"node",
        "css":{
            "text-valign":"center",
            "text-halign":"right",
            "content":"data(name)",
            "font-size":"14px",
            "height":"20px",
            "width":"20px",
            "background-color":"#dfdfdf",
            "border-color":"#000",
            "border-width":"1px",
            "border-style":"solid"
        }
    },{
        "selector":"edge",
        "css":{
            "color":"#dfdfdf",
            "width":"15px",
            "curve-style":"haystack",
            "haystack-radius":"0"
        }
    },{
        "selector":"node[?empty]",
        "css":{
            "height":"15px",
            "width":"15px",
            "border-width":"0px"
        }
    },{
        "selector":"$node > node",
        "css":{
            "height":"auto",
            "width":"auto",
            "shape":"roundrectangle",
            "background-color":"#ffffff",
            "padding-left":"5px",
            "padding-right":"5px",
            "padding-top":"5px",
            "padding-bottom":"5px"
        }
    },{
        "selector":"node:selected",
        "css":{
            "font-weight":"bold",
            "border-width":"3px"
        }
    },{
        "selector":"edge:selected",
        "css":{
            "line-style":"dashed"
        }
    },{
        "selector":"node[?text]",
        "css":{
            "pie-size":"60%",
            "pie-1-background-color":"#000000",
            "pie-1-background-size":"100%"
        }
    }],
    "zoomingEnabled":true,
    "userZoomingEnabled":true,
    "zoom":1,
    "minZoom":1e-50,
    "maxZoom":1e+50,
    "panningEnabled":true,
    "userPanningEnabled":true,
    "pan":{"x":0,"y":0},
    "boxSelectionEnabled":true,
    "layout":{"name":"preset"},
    "renderer":{"name":"canvas"},
    "wheelSensitivity":0
}

**Comment by maxkfranz** [comment]
This will make it into 2.4

**Comment by maxkfranz** [comment]
Snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-a48f4d2d0a-1431027200494.zip

**Comment by kolesnikova-tavi** [comment]
Thanks! It works. But now the labels are included into the parent.
Before:
![cy3](https://cloud.githubusercontent.com/assets/3088258/7532660/264bf14c-f59c-11e4-916c-dfc7b1af6ce7.png)
After:
![cy4](https://cloud.githubusercontent.com/assets/3088258/7532661/265d4406-f59c-11e4-9698-7dda63f9875f.png)

**Comment by maxkfranz** [comment]
See #931 

This is expected behaviour for 2.4.  I'm releasing on Monday, so if you request further changes it will have to wait to 2.5 (or you'll have to use a 2.5 snapshot).

**Comment by kolesnikova-tavi** [comment]
Excellent! Thanks a lot!
