### ISSUE TITLE
Confused about font-family

### ISSUE THREAD

**Issue by ktei** [cytoscape/cytoscape.js#933]
Been struggling with this for some time. I set 'font-family' of label to `Lato`, like this:
```javascript
css: {
   'color': '#060706',
   'font-family': '"Lato", "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif',
```
But it doesn't work (I have Lato font files and it does work for others).

So I did some search in source code and in `style.js`, I found this:
```javascript
    var fontFamily = 'Helvetica' || this.containerPropertyAsString('font-family') || 'sans-serif';
```

This is a bit strange because it seems it just "hard coded" Helvetica anyway... So I removed 'Helvetica' and then `Lato` started working now.

@maxkfranz Could you have a look at this issue? Thank you very much ; )

**Comment by maxkfranz** [comment]
Workaround : Don't use quotation marks
