### ISSUE TITLE
Prevent edge overlap and cluster connected nodes together ?

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js#934]
Hi, are there any examples of a cytoscape.js network graph with <b>clustering</b> of nodes, i.e., multiple nodes connected to one node being clustered around it, by changing the closeness/ betweenness setting for connected nodes ?

Also, is there a way to prevent <i>edges</i> from <i>overlapping</i> in addition to nodes ?

Would both of these have to be implemented via cytoscape.js or via whichever layout is used ?

**Comment by maxkfranz** [comment]
Both clustering and overlap are layout concerns.  The particular implementation really depends on the particular layout.
