### ISSUE TITLE
Label events

### ISSUE THREAD

**Issue by kolesnikova-tavi** [cytoscape/cytoscape.js#937]
Hello, I've got two questions.
1. How can I detect boxSelection? I need to handle select and boxSelect events separately. 
2. I need to select nodes by clicking on their labels. Is it possible?

**Comment by kolesnikova-tavi** [comment]
1. I'm sorry. It is my mistake. Now It is OK.
2. I'm making an application that builds metro maps. It is uncomfortably to try to select a tiny station (a node) when there is its large name (a label). Maybe is it possible to switch on/off binding events on labels?

**Comment by maxkfranz** [comment]
Accurately checking whether text has been tapped is overly expensive, which is why clicking labels is not supported.  

Could you make your nodes bigger?  

You could alternatively make your nodes bigger and transparent, using SVG background images to represent the station point -- while allowing for a larger click area that would include labels.

**Comment by kolesnikova-tavi** [comment]
>> Could you make your nodes bigger?

Because I have a design.
>> You could alternatively make your nodes bigger and transparent...

Names have different lengths. And my application allows to change the color of stations. So it is not a very good solution.
Anyway, thanks.

**Comment by sylvain-hamel** [comment]
Regarding:
> @ kolesnikova-tavi : 2. I need to select nodes by clicking on their labels. Is it possible?
> @ maxkfranz  : (2) Events on labels are not supported due to expense

I have less then 40 elements to render. Do you think it would affect the performance for such a low number of nodes? If not, can you make it an option `enableSelectUsingLabel : true` that would be `false` by default.

**Comment by maxkfranz** [comment]
It will be expensive, even in small graphs.  When text tapping is needed in UI, generally you'd use the bounding box as an approximate, cheap measure.  That's not possible here, because the font is customisable.  That means we'd need general font hittesting, and that's overly expensive and complex.

Maybe the cheap bounding box check plus a style property could be an option, but I'm not entirely sure.

**Comment by maxkfranz** [comment]
@kolesnikova-tavi 

> Names have different lengths. And my application allows to change the color of stations. So it is not a very good solution.

You could create different coloured SVGs dynamically in your code.  There are libraries that make manipulating SVGs very easy, too.

**Comment by sylvain-hamel** [comment]
@maxkfranz FWIW, I've had two users test my app today and they both tried to select nodes by clicking the text. If you can come up with something cheap I think it would help. Thanks!

**Comment by sylvain-hamel** [comment]
@maxkfranz Thank you for planing this. Today, two new users reported that they can't select elements, just because they tried to click the label instead of on the image.

**Comment by maxkfranz** [comment]
Issue:

![screen shot 2015-06-18 at 3 19 58 pm](https://cloud.githubusercontent.com/assets/989043/8240003/ae9e04da-15cd-11e5-9d9f-977e684c9373.png)

Note the bounding box of the text given by the red box.  A tap anywhere in the box would be a tap on the label, and hence a tap on the element.  However, there are large empty areas on the last line.  Depending on the text and alignment, this isn't limited to the last line.

**Comment by sylvain-hamel** [comment]
That's what I expected. Thanks.

**Comment by sylvain-hamel** [comment]
Hi @maxkfranz, when do you think 2.5.0 will be available?

**Comment by maxkfranz** [comment]
You can follow the milestone to see its progress

**Comment by maxkfranz** [comment]
TODO : Implementation currently doesn't handle rotated labels

**Comment by sylvain-hamel** [comment]
@maxkfranz I patched my 2.4 version with this fix and it works as expected. Thanks

**Comment by maxkfranz** [comment]
That's good, but note that applying commits from `unstable` on `master` builds won't always go well.  It would be more reliable to build off of `unstable`.
