### ISSUE TITLE
Spread layout not working in minified Cytoscape.js

### ISSUE THREAD

**Issue by rmosca** [cytoscape/cytoscape.js#939]
When testing the spread layout with the minified version of cytoscape.js (cytoscape.min.js) it gives an error:

Uncaught ReferenceError: a is not defined

that refers to a variable 'a' that is the minified version of 'foograph'.

My understanding of the problem is that the Foograph library is loaded with the 'require' function (line 182 of layout.spread.js) and assigned to the identifier 'foograph'. This assignment happens dynamically, therefore the minifier has no chance of changing it to 'a'.
Therefore, the code, when executed, cannot find the 'a' variable. The non-minified version works because no change is done to the identifiers.

But I am not sure if this is the reason for the problem...

In any case, at least to me, the spread layout does not work with the minified Cytoscape.js...

**Comment by maxkfranz** [comment]
We could avoid `eval()` if there were a `global` or `self` variable in the threads.

https://github.com/maxkfranz/weaver/issues/2

**Comment by rockshandy** [comment]
Is this actually get fixed? It seems like I still need to exclude the related dependencies for the spread layout form being minified.

**Comment by maxkfranz** [comment]
It should be addressed in 2.4.1

https://github.com/cytoscape/cytoscape.js/blob/master/src/extensions/layout.spread.js#L247

**Comment by maxkfranz** [comment]
If you mean that `Voronoi` and `foograph` when themselves are minified have mangled names, that you may need to elide from your minification process.

**Comment by rockshandy** [comment]
Ah yes, my issue is if I have the dependent libraries (for the spread layout) minified.

**Comment by maxkfranz** [comment]
Probably the issue is that the main variable/entrypoint is mangled.  Maybe there's an option in your minifier to preserve that.  If not, you may need to keep them unminified (unfortunately).
