### ISSUE TITLE
Fit with a max zoom

### ISSUE THREAD

**Issue by sylvain-hamel** [cytoscape/cytoscape.js#941]
I like the automatic fit feature when I have graphs with a lot of nodes and edges. But
I sometimes have small data sets with only a few nodes and egdes. In such case I get a very large rendering of the elements.

I don't want to set a `maxZoom` as I don't want to prevent the user form zooming as much as he wants. 

Would you consider implementing an `fitMaxZoom` property? Or is there a way I can achieve using the existing APIs?

**Comment by maxkfranz** [comment]
Probably this:

```js
var maxZoom = cy.maxZoom();

cy.maxZoom( fitMaxZoom );
cy.fit();
cy.maxZoom( maxZoom );
```

Or:
```js
cy.fit();

if( cy.zoom() > fitMaxZoom ){
  cy.zoom( fitMaxZoom );
  cy.center();
}
```

**Comment by sylvain-hamel** [comment]
@maxkfranz thanks, it works fine. I had to put the code in my `layoutstop` listener for it to work otherwise it never works on the initial layout.

```javascript
graph.on('layoutstop', function() {
    graph.maxZoom(2.5);
    graph.fit();
    graph.maxZoom(100);
});
```

**Comment by maxkfranz** [comment]
@sylvain-hamel Or you could specify that in the ready handler to be more specific for init load.
