### ISSUE TITLE
layout() method sometimes does not work

### ISSUE THREAD

**Issue by sylvain-hamel** [cytoscape/cytoscape.js#942]
Sometimes the `layout()` method stops working. I'm still not able to find the exact sequence but I see two symptoms of the bug:

1. In some cases calling `layout()` does nothing.
2. In some cases switching from `cola` to `dagre` causes error `Cannot set property 'dagre' of undefined` at line 24887 (`cy.getElementById(id).scratch().dagre = n;`).

What I know is that the issue always starts occurring after I have replaced an existing set of elements with a new set using `load()`. Sometimes it's on the first attempt to change the layout and sometimes it takes a few changes before it stops working. Do you have any idea what could be in cause?

Thanks

Sylvain

**Comment by maxkfranz** [comment]
(1) `cy.load()` is deprecated and no longer documented/supported.  It will continue to work as it has in the past (bugs and all) for backwards compatibility.

(2) Use `cy.add()` and call a layout yourself to replicate the functionality of `cy.load()`.

(3) Calling `cy.layout()` with no parameters is also no longer documented/supported.  Use (2).

**Comment by sylvain-hamel** [comment]
@maxkfranz, I changed my code to this based on  https://github.com/cytoscape/cytoscape.js/issues/943#event-310764613. 

I still get the `Uncaught TypeError: Cannot set property 'dagre' of undefined` error but now I can reproduce it easily in my app.

```javascript
graph.remove(graph.elements());
graph.add(newElements);
currentLayout.run();           
```

When the currentLayout is `cola` it works fine but when currentLayout is `dagre` I always get the error.

**Comment by maxkfranz** [comment]
You have to create a new layout for the new elements.  If you call a layout that references nonexisting elements, you'll have problems...

Maybe you just want to save your layout options rather than the layout.

**Comment by sylvain-hamel** [comment]
@maxkfranz yep, works fine. thanks!
