### ISSUE TITLE
How to re-layout the graph and keep the last layout?

### ISSUE THREAD

**Issue by sylvain-hamel** [cytoscape/cytoscape.js#943]
I found out that calling `layout()` without any arguments rearranges the elements. That is perfect after the user has added or removed nodes. My problem is that it uses the initial layout instead of the last layout that was set.

so if you start like this:

```javascript

cytoscape({
  container: ...,
  elements: ...,
  layout: {name:'cola'},
});
```
and then call this

```javascript
  cy.layout({name:'dagre'});
```

and then call 

```javascript
  cy.layout();
```

it reverts to the original layout (cola in this case) instead of keeping the last layout.

Calling `layout` and passing the current layout as an argument does not cause the rearrangement of the elements; the calls seems to be ignored.

**Comment by maxkfranz** [comment]
Use `cy.makeLayout()` to get a new layout and call `layout.run()` whenever you want to apply it.  Keep the `layout` ref as long as you want to use it.

http://js.cytoscape.org/#core/layout/cy.makeLayout

**Comment by sylvain-hamel** [comment]
@maxkfranz : thanks, `layout.run()` works fine!
