### ISSUE TITLE
Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement'

### ISSUE THREAD

**Issue by pedrodelgado81** [cytoscape/cytoscape.js#944]
I'm developing a J2EE application and use cytoscape for draw a diagram. When I try to export to png I've got Uncaught SecurityError.
In cytoscape web works, but  not in my application.

Environment: Weblogic 12c, JSF 2.0, Primefaces 5.1

Thanks

**Comment by maxkfranz** [comment]
I strongly suspect this is an issue with your setup rather than cy.js : https://stackoverflow.com/questions/2390232/why-does-canvas-todataurl-throw-a-security-exception

**Comment by pedrodelgado81** [comment]
Hi, I found the error and was my fault. 
The problem was that the image url in my graph are inconsistent for CORS. I change the source and works!
Thanks.
