### ISSUE TITLE
Is there any way we can render cytoscape on server side?

### ISSUE THREAD

**Issue by ktei** [cytoscape/cytoscape.js#954]
I know this could be challenging but thought it's worth asking anyway.
Our users want a feature that they can directly get the output image of cytoscape (canvas export png/jpg) directly from server side, which means, they post a request and on server side we run cytoscape to render canvas and use cytoscape to get exported image and send it back to client side.

So apparently cytoscape runs in browser, but is there any workaround, even a hack, to let us run cytoscape on server side?

**Comment by dpatte** [comment]
I have not used cytoscape (yet), but what you want may be possible if run from within a javascript server framework such as meteor or node.js.

**Comment by maxkfranz** [comment]
You can use Node.js plus PhantomJS.  This lib would be useful: https://www.npmjs.com/package/phantomjs

The code should be relatively straightforward.  If you modularise your code, it may make a good npm module/library (e.g. just pass some options incl. cy.js init options and get out a png or jpg file).

**Comment by maxkfranz** [comment]
Note that you can use cy.js headlessly in Node.js just fine.  It only because you need screenshots that PhantomJS is needed.

**Comment by rui-infotrack** [comment]
@maxkfranz Thank you very much. This helps a lot.

**Comment by rui-infotrack** [comment]
I'm @ktei by the way.

**Comment by maxkfranz** [comment]
https://github.com/cytoscape/cytosnap
