### ISSUE TITLE
Panning over box selection; selection on shift etc

### ISSUE THREAD

**Issue by danpaulsmith** [cytoscape/cytoscape.js#958]
Hi,

I've enabled box selection as well as panning.

The default way of distinguishing the two modes interaction seems to me to:

- mouse down + mouse movement immediately begins box selection
- mouse down + no mouse movement for 1 second begins panning canvas.

I think they should be the other way around:

- mouse down + mouse move immediately pans the canvas
- mouse down + no mouse movement for 1 second should begin the box selection mode.

I'm pretty sure people are more likely to move the canvas around than to be selecting multiple nodes, which is why the 1 second delay should be for the latter.

**Comment by maxkfranz** [comment]
Alternative option: Box selection only occurs with the shift key pressed

**Comment by maxkfranz** [comment]
Changes to `unstable`: 

- Box selection is enabled by default
- Box selection happens only when one of (shift, ctrl, meta) and drag happens after mousedown

**Comment by maxkfranz** [comment]
The new style of box selection should be additive; re-opening

**Comment by maxkfranz** [comment]
It's additive now
