### ISSUE TITLE
Hollow Edge Rendering Problem (renders line inside)

### ISSUE THREAD

**Issue by istemi-bahceci** [cytoscape/cytoscape.js#960]
Hi,

I have realized that edges whose edge arrow state is set as 'hollow' are rendered as in the image:
![image](https://cloud.githubusercontent.com/assets/8645080/7953311/e7e28e22-09cb-11e5-81ce-f0bcf849f20f.png) I've experienced this problem in the latest cytoscape.js 2.4.0 release.

Regards,
Istemi Bahceci

**Comment by maxkfranz** [comment]
This should fix it, and also a minor rendering issue with hollow arrows that are semitransparent:

![screen shot 2015-06-03 at 11 22 42 am](https://cloud.githubusercontent.com/assets/989043/7963922/2ca146cc-09e3-11e5-8db8-90cee25fbb81.png)

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-fb6523bf26-1433345128819.zip
