### ISSUE TITLE
How to use a web font character as the background-image?

### ISSUE THREAD

**Issue by sylvain-hamel** [cytoscape/cytoscape.js#964]
Is there any way to use a webfont character (from a woff file) as the background-image on my node?

**Comment by maxkfranz** [comment]
Whatever fonts are loaded in the browser/page can be used in labels.  So, you could specify a font hierarchy like `font-family: font-awesome, helvetica` and use the character codes in the labels for the icons you want.

If you want a real background image, you'll have to use the corresponding SVG from the icon font.

Does that make sense?

**Comment by sylvain-hamel** [comment]
I need a real text label as well as an image. So I'd need two different `label` properties on the node with different `font-family`. One for the icon (the web font character) and one for the real label.

I guess I'll have to use the real SVG image.

----

Would it be doable (considering the rendering mechanisms cytoscape uses) to change the library to support custom node templates? Something like this:


```javascript
var cy = cytoscape({
  container: document.getElementById('cy'),
  elementTemplate : '<h1>{{data(title)}}<h1><img src="myimage class="{{data(status)}}"/><div>{{data(name)}}<div>'
});
```

...where one can use `{{data(value)}}` to include data from the source node. 

That would solve this problem and a few other content related issues I have.

**Comment by maxkfranz** [comment]
We can't support HTML, because that doesn't mix with canvas (the rendering technology used)

**Comment by sylvain-hamel** [comment]
I thought so. Would there be a way to provide a call back that one could use to implement custom rendering code?

```javascript
var cy = cytoscape({
  container: document.getElementById('cy'),
  renderElement : function(canvas, element, postion, etc...){
     canvas.font = "48px serif";
     canvas.strokeText(element.Title, 10, 50);
  }
});
```

**Comment by maxkfranz** [comment]
I wouldn't want to do that either.  Right now, it's completely decoupled from the rendering technology.  We may want to add back SVG, for example, for SVG file output.  Or we may use WebGL in future -- or some other tech. (Though WebGL doesn't seem to be any more performant for what we need in 2D).

Does that make sense?

Option with SVG: Because the fonts tend to basically have a SVG spritesheet, maybe you could try using the `background-width`, `background-height`, `background-position-x`, and `background-position-y`?

**Comment by maxkfranz** [comment]
e.g. https://css-tricks.com/css-sprites/

**Comment by sylvain-hamel** [comment]
That may work but if it is not rendered as a font then I can't set the font color and other font-related properties. 

I have already changed my code to use SVG files. But because they are not fonts, I have to have different copies of the SVG in different colors and change the `background-image` based on the element selector. Not as easy but it works.

But this does not solve the need to completely control the rendering of an element. As a client of the library, I'd be willing to use `renderElement` now, knowing that at some point it may no longer be supported. When that happens, I suppose I'll still have a `renderElement` callback. I'll just have to convert my rendering code from canvas to whatever new technology will be used.

You wrote "add back SVG", is there a thread somewhere that explains why SVG was dropped?

**Comment by maxkfranz** [comment]
If you want to use the icon as a background image, then you're going to run into the limitations of background images.  At best, you could use a SVG library to manipulate the SVGs you're using programmatically and then specify those SVGs as the background images of the nodes.

Complete rendering of an element is not practical/possible for other reasons, as well.  It will be possible to have arbitrary polygons in 2.5, though: https://github.com/cytoscape/cytoscape.js/issues/925

**Comment by maxkfranz** [comment]
> You wrote "add back SVG", is there a thread somewhere that explains why SVG was dropped?

That was only a prototype renderer.  The current renderer is a completely different implementation that depends on canvas only for visual output (whereas the old SVG one depended on SVG semantics for hittests, etc...), but SVG output could be added to it.

**Comment by sylvain-hamel** [comment]
I see. Thanks for you fast replies. We can close this issue.

**Comment by djangosdk** [comment]
If anyone wants a sample for reference, using font-awesome http://jsfiddle.net/bababalcksheep/ajhnmcrb/
