### ISSUE TITLE
Add support for label margins

### ISSUE THREAD

**Issue by sylvain-hamel** [cytoscape/cytoscape.js#965]
Properties

`*-text-margin-x` and `*-text-margin-y` for 

* default (e.g. `text-margin-x`)
* `source`
*  `target`

--
Original post:

I'd like to add a `margin-bottom` to the node label to move it up a bit so that it does not show on top of the incoming edge arrow.

![padding](https://cloud.githubusercontent.com/assets/1754010/8011953/70e25b4c-0b8b-11e5-9bb6-5071ac3e1f4a.png)

**Comment by sylvain-hamel** [comment]
About this feature request, I don't think a custom margin is what we really need to solve this problem. I think improving the label placement based on the incoming edges would be better.

The library should automatically set a bottom margin if these two conditions are met:

1 - the node has an incoming edge
2 - the edge has an arrow shape

The margin value should be equal to the height of the arrow shape (plus a small padding).

I think this would benefit all users of the library without adding more options.

**Comment by maxkfranz** [comment]
I don't think it makes sense to make assumptions about style that remove control from the dev.  If this is to be a feature, I think it ought to be explicitly set by the dev.  

Consider that the dev may not position the label the same way as you have such that the margin is unnecessary -- and it could even break their styling.

**Comment by sylvain-hamel** [comment]
It's true that the new feature should not break existing styling. This new would have to be enabled via an option ('smartLabelPlacement'). But don't you think that generally speaking, users of the library will be happier with if the labels don't overlap arrows? 

If you don't what to go ahead with this suggestion then I'll have an issue if you implement my original request: The first node in my graph will always have unnecessary padding (there is no incoming arrow). But I can live with that. That's still better then the current situation.

Another solution would be a callback to compute the label padding (or the label position). This way I could provide this callback

```javascript
function getLabelPosition(node, x, y) {
   var hasIncommingEdgesWithArrow = ...;
   return {
      x: x,
      //add padding is needed
      y : hasIncommingEdgesWithArrow ? y + 20 : y
   }
}
```

**Comment by maxkfranz** [comment]
You can already do it functionally with the stylesheets per property, so it should suffice to add the new property.

**Comment by sylvain-hamel** [comment]
can you please expand on that?

**Comment by maxkfranz** [comment]
e.g. 

```
  'margin-bottom': function( node ){ return whatIWant; }
```

**Comment by sylvain-hamel** [comment]
That's too easy! I'll try it tomorrow. Thanks.

**Comment by maxkfranz** [comment]
Once something like `'margin-bottom'` is implemented...

**Comment by sylvain-hamel** [comment]
Oh right :S

**Comment by maxkfranz** [comment]
Moving to 2.6 because node label rotation support doesn't work as well without margins
