### ISSUE TITLE
Improve styling for selected elements

### ISSUE THREAD

**Issue by sylvain-hamel** [cytoscape/cytoscape.js#967]
My issue is that I can't find a way to properly highlight selected nodes. I can change the appearance of the label and of the node individually but I need to style the outline of the two together. 

Feature request 1: Support `outline` styling for a `:selected` node.
Feature request 2: Support a visible selection box around the selected objects.

It is feature 1 that I need the most, feature 2 is a nice to have.

The result would be:

![untitled_-_paint net_4 0 5_2015-06-08_12-44-06](https://cloud.githubusercontent.com/assets/1754010/8040278/200bdc26-0ddd-11e5-97e8-95c4f9f0c337.png)

I took this styling from Visio:

![2015-06-08_12-52-07](https://cloud.githubusercontent.com/assets/1754010/8040296/3edd9590-0ddd-11e5-9fdd-eaf489ff405b.png)

**Comment by maxkfranz** [comment]
For elements, have you tried the [overlay](http://js.cytoscape.org/#style/overlay)? That would work for both nodes and edges -- and that may even make the part that follows unnecessary:

For groups of elements, you should consider something like an [extension](http://js.cytoscape.org/#extensions).  That's outside of the scope of individual elements.  You will find the [bounding box functions](http://js.cytoscape.org/#collection/position--dimensions/eles.renderedBoundingBox) useful for this.

**Comment by sylvain-hamel** [comment]
`overlay-color` only affects the color while dragging the element (while it is in the `:active` state). I need on overlay on the `:selected` state too.

**Comment by maxkfranz** [comment]
Just set it in your stylesheet:

```
:selected { overlay-color: blue; }
```

**Comment by sylvain-hamel** [comment]
That is what I tried (at least I think) but it does not work. 

See: http://jsbin.com/dunicojeki/2/edit

Although I set the `overlay-color: blue;` for `:selected` it becomes blue only while being moved.

**Comment by maxkfranz** [comment]
You need to set all three properties.  By default, I think the values are (black, 0, 0)

**Comment by sylvain-hamel** [comment]
Hi, it works with all properties set (http://jsbin.com/cejizojina/2/edit), but it does not do what I need because the outline does not include the label. Sometimes my labels are pretty big ( and I use `'text-max-width': '85px'`).

Could you add a new set of styles for this use case?

```
  full-element-bounding-box-color: blue;
  full-element-bounding-box-opacity: 0.5;
  full-element-bounding-box-padding: 5;
```

Thanks

**Comment by maxkfranz** [comment]
It's really only meant to follow the element shape, just like a border wouldn't enclose the text.  You could calculate `node.outerWidth()`, put that value in `node.data()`, and use a mapper with the regular properties.

**Comment by sylvain-hamel** [comment]
What I'm proposing here is not to extend or modify the current `outline` styles. I'm now proposing a new set of styles that I would use for the `:selected` state but that others could use for any other selector.

**Comment by maxkfranz** [comment]
Example of what I mean: http://jsbin.com/tenupopesa/1/edit

**Comment by sylvain-hamel** [comment]
Thanks! That's pretty close to what I need! 

but I'd need two more things: 

1. Make the outline a rectangle (to follow the shape of the node)
2. Be able to set a border style and have no fill color.

```
overlay-color: none
overlay-border-color: blue
```

That would allow me to do what I originally asked. It is possible?

By the way, thanks a lot for your support.
