### ISSUE TITLE
bug: text-background-color for selected nodes does not revert to default when unselected

### ISSUE THREAD

**Issue by sylvain-hamel** [cytoscape/cytoscape.js#968]
If you set a `text-background-color` for the `:selected` state, then it does not revert to transparent when you unselect the element.

**Test case:**
http://jsbin.com/fixekoxese/3/edit
- select a node, selected item turns blue
- select another node
- bug: text color for the previous items revets to back but not its `text-background-color`

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-1f0f307c05-1433966276387.zip

**Comment by sylvain-hamel** [comment]
Thanks!
