### ISSUE TITLE
cytoscapeJS- shadow- visually highlight hidden nodes in neighborhood

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js#969]
Can I display a shadow/ overlay effect of a <b><i>specific shape</i></b> on a node ?

I am using cytoscapeJS to generate small network graphs (of 50-100 nodes, majority of which are hidden when the graph is 1st generated).
In the graph, nodes which have hidden nodes in their neighborhood are <b>highlighted</b> visually. I am using the ````neighborhood()```` to get all the nodes connected to each node and if hidden nodes exist, I am using ````addClass()```` to add a basic <i>shadow</i> effect, for now (was earlier using overlay), on the node.

I noticed an example of the <b>Cola</b> layout (http://marvl.infotech.monash.edu/webcola/examples/browsemovies.html) that uses <i>D3.js</i> to show small, spikes over the nodes, on a ````mouseover```` event, and the number of spikes correspond to the number of nodes connected to the selected node. Can something like this be done with <b>cytoscapeJS</b> ?

If not, is there a way to display the number of hidden nodes (numerical value as a label) alongide the shadow/ overlay effect ?
Thanks.

**Comment by maxkfranz** [comment]
Spike state:

(1) Use a circle layout for the neighbourhood, with a small radius.

(2) Make the neighbourhood nodes `opacity: 0`.

(3) Make the neighbourhood edges `opacity: 0.5` or similar low value.

Closing for now, as this should recreate that effect.

**Comment by AjitPS** [comment]
Hi @maxkfranz , can the layout for my entire graph be different (cose or cola) when I do this, i.e., can I still set a circle layout on a specific neighborhood ?

**Comment by AjitPS** [comment]
Hi Max, I tried what you said. My graph uses the ````cola```` layout but for a node with hidden, connected nodes, I set a ````circle```` layout with small radius on the neighborhood with the node as the ````root````. However, it isn't like the example in the url above where the small spikes show up when hovering over a node with hidden connected nodes.

Here is what my implemented solution looks like:
![neighborhood_spike_attempt](https://cloud.githubusercontent.com/assets/1078989/8104397/58371b4a-1028-11e5-8cf5-6f2ee398267c.png)

**Comment by AjitPS** [comment]
I posted this in the <b>WebCola</b> Git repo as well and was told that the spikes were made using D3.js and are basically <b><i>"rotated rectangles with a small gradient"</i></b>.

**Comment by maxkfranz** [comment]
Try a smaller radius like 10, hide the edge arrows by default, and show the neighbourhood only on mouseover.

**Comment by AjitPS** [comment]
I used the following code to set the ````circle```` layout for the selected element's (<u>ele</u>) ````neighborhood````:

````var neighborhood_Layout= { name: 'circle', roots: ele, radius: '0.1', rStepSize: '0.1' };
     ele.neighborhood().layout(neighborhood_circleLayout);````

**Comment by maxkfranz** [comment]
(1) You've specified numeric values as strings

(2) Circle doesn't take roots.  Use a `boundingBox` centred on your node of interest

**Comment by AjitPS** [comment]
Hi @maxkfranz , I've made the 2 changes you suggested above. But, can I set the layout on just the connected Edges (using ````ele.connectedEdges()````) and Nodes and not the entire neighborhood ?

I have managed to implement showing the hidden, connected edges (with opacity 0.5) on a ````tapdragover````/ ````mouseover```` event with the opacity of hidden, connected nodes set to 0.1.

However, this also affects my radial <b>context menu</b> (using ````cxtmenu````) as using that triggers the ````mouseover```` event first which now causes all connected nodes to become invisible. Is there a way to separate the 2 events or do I need to write the code to re-set the ````style```` for all the connected nodes and edges for all my radial context menu items/ events ?

**Comment by AjitPS** [comment]
Any suggestions ?

**Comment by maxkfranz** [comment]
(1) Use whatever elements you like and `eles.layout()`.

(2) Use the `boundingBox` to limit the layout size

(3) & (4) Hover effects are not effective on touch.  Even if you could get it working, it's probably not worth it.  Similarly, this won't work well if you're using the context menu, because you've overloaded the gesture.

**Comment by AjitPS** [comment]
Regarding (2), i.e., using the ````boundingBox````, I have done that in the code above. Kindly let me know what I'm missing (why isn't it working) ?
