### ISSUE TITLE
A special case about ready event

### ISSUE THREAD

**Issue by rui-infotrack** [cytoscape/cytoscape.js#972]
So the scenario is like this:
When cytoscape drawing is ready, we try to output the png and put the base64 string into a hidden field (sorry, it sounds weird but we do it for a reason). Code is like this:
```javascript
ready: function() {
  var base64 = this.jpg({full: true, scale: 3, bg: '#fff'});
  $('#base64').val(base64);
}
```
Then, we read base64 from the hidden input and convert that into a real image. Unfortunately, we notice that images generated are all like this:
![image_not_loaded](https://cloud.githubusercontent.com/assets/12144265/8101959/802394ee-105f-11e5-969b-7fe03d156f01.PNG)

Please ignore the red scratch. If you pay attention to the image you'll realize that the nodes are NOT there yet. I think this is because that when cytoscape says **ready**, it only means the **drawing** is ready, however the nodes are actually **image nodes**, which means the images are not fully loaded in browser yet. Then we export PNG, which is too early actually, because images are still "empty".

Is there good way that we can work around this issue?

Many thanks!

**Comment by maxkfranz** [comment]
See `initrender` in init: http://js.cytoscape.org/#core/initialisation

Or use [`cy.onRender()`](http://js.cytoscape.org/#core/events/cy.onRender) with [`cy.forceRender()`](http://js.cytoscape.org/#core/viewport-manipulation/cy.forceRender) to guarantee correct PNG output at any time (even after init).

**Comment by rui-infotrack** [comment]
@maxkfranz 

I tried `initrender`, `forceRender`, but still got this sort of image:

![capture](https://cloud.githubusercontent.com/assets/12144265/8200572/177d205e-150a-11e5-8ce1-4e9e76e41a30.PNG)

So what we did is that in the callback of either `initrender` or `ready`, we (even did `forceRender` to force redraw), we call `cy.png` to get base64 encoded string of the output image, and create a hidden field with value of this base64, and append it to document.body.

We also have a PhantomJS server which keeps running and when it receives a request, it goes to cytoscape-related URL and waits for the hidden field to appear, then it retrieves the value (base64 string) from the hidden field and converts it to an image file.

So far we have no clue yet why for some images, their image nodes are not fully rendered.

Could you think of something else that might cause this to happen?

**Comment by rui-infotrack** [comment]
So what I found in source code is this:
``` javascript
        var image = this.getCachedImage(url, function(){
          r.data.canvasNeedsRedraw[CanvasRenderer.NODE] = true;
          r.data.canvasNeedsRedraw[CanvasRenderer.DRAG] = true;
          
          r.redraw();
        });
```
My guessed theory is that: when you trigger `initrender`, the images are not loaded yet, and then later on after some image is loaded, `redraw` is called, but in that `redraw`, initrender flag is set to true already so `initrender` won't be called again. And as you said, `initrender` only means the first frame is drawn.

I think the question is that, I need to do add some code on application layer to keep checking `onRender` event, and until all the 4 images (we have 4 kinds of node images) are loaded, in THAT frame, I can safely say that 'Now I can output canvas'.

Does this make sense?

**Comment by maxkfranz** [comment]
If this is all happening on your server, the images should load very fast -- but not on the first frame probably.  I would just set a small timeout and then grab the image.

If you want very fast images (that should load on the first or second frame or so), use embedded images in the stylesheet.  e.g. http://www.websiteoptimization.com/speed/tweak/inline-images/

**Comment by rui-infotrack** [comment]
Thank you @maxkfranz, I'll try embedded images
