### ISSUE TITLE
tap event does not always fire if there's a slight mouse movement

### ISSUE THREAD

**Issue by sylvain-hamel** [cytoscape/cytoscape.js#974]
I found that if I click an element and my mouse moves by even one pixel while clicking then the event does not fire. With very sensitive mouse this it is quite easy to miss click like that.

You can reproduce it easily by taking your time

- mouse down
- move 1px lower
- release mouse
- result : the event does not fire

I think the event should have a drag tolerance.

-----

As an aside: in that scenario the `tap` event does not fire but the `select` does. My understanding was that `tapstart+drag` would not trigger the selection of the element being dragged. So I tested it again. If I `tapstart+drag` and move two inches, it does not select the element. But if  I `tapstart+drag` and move on pixel, then it does select it.

**Comment by sylvain-hamel** [comment]
A workaround could have been to use the `select` event instead. However I can't differentiate a user triggered selection from an API trigger selection and I need that. So the workaround does not work.

**Comment by maxkfranz** [comment]
Ref https://github.com/cytoscape/cytoscape.js/issues/636

**Comment by maxkfranz** [comment]
Looks like there's a bug, then -- since the threshold I referenced should be for tap.

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-05e5c2297c-1434137542817.zip

**Comment by sylvain-hamel** [comment]
fix confirmed. thanks!

**Comment by rockshandy** [comment]
I think this fix may have introduced a bug where making a box selection also triggers a click event. At least with some light testing a click event isn't fired in 2.4.1, but is fired in 2.4.2. I made a rather large box selection and was surprised to see click events being triggered.

**Comment by maxkfranz** [comment]
@rockshandy Would you create an issue for that and link it to here?  I'm away until 24 Nov, and don't have regular/reliable internet...

**Comment by rockshandy** [comment]
Oops a little late to check my notifications, but will do shortly!
