### ISSUE TITLE
2.4.2 breaks text-border styling for :selected

### ISSUE THREAD

**Issue by sylvain-hamel** [cytoscape/cytoscape.js#977]
Sample with 2.4.0 : http://jsbin.com/dozerajaje/1/
Sample with 2.4.2: http://jsbin.com/kosayasisu/1/

With 2.4.0, selecting an item creates a border around it. In 2.4.2 this no longer works.

**Comment by maxkfranz** [comment]
The original PR for this should have had a `text-border-opacity` property.  The `text-background-opacity` can not be shared.

**Comment by maxkfranz** [comment]
Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-1d2889eb7c-1434474209218.zip
