### ISSUE TITLE
Incremental option for layouts

### ISSUE THREAD

**Issue by ugurdogrusoz** [cytoscape/cytoscape.js#978]
Most layout algorithms (especially force-directed ones) start their work from random initial positions. However, in cases where the user would like to re-layout their graph, simply because there were some (minimal) changes to the topology of the graph and they'd like not to lose their mental maps, there should be an option to start from "current" positions instead. In graph drawing, this is called incremental layout and it should be rather straightforward to implement them in force-directed layout algorithms.

**Comment by maxkfranz** [comment]
The forcedirected layouts have a `random` or `randomize` boolean for randomising the initial node positions.  If falsey, the layouts use the existing node positions.  I think the `spread` layout and `cose2` are the ones that need this added.
