### ISSUE TITLE
Performance concerning recalculateRenderedStyle

### ISSUE THREAD

**Issue by jhonatandarosa** [cytoscape/cytoscape.js#979]
We use cytoscape.js for a network analysis module of our application.
We are having some issues with performance. Some networks have about 10k elements, and the performance is getting extremely bad.
All nodes have background images, rectangle shapes, lots of edges and labels.
After profiling, we noticed that the main point is the first call recalculateRenderedStyle() after loading the graph.

Do you have some sugestion that could help us?

**Comment by maxkfranz** [comment]
There isn't much you can do about the first calculation of style, apart from reducing the size of your stylesheet.  There are optimisations such that subsequent calculations of style are cheaper for the elements, however.

There may be some optimisations that can be made to make this a bit faster, but the initial calculation is necessary.

**Comment by maxkfranz** [comment]
Note: Haystack edges are cheaper than bezier edges, with respect to both rendering and style calculations.

**Comment by maxkfranz** [comment]
I tried to benchmark some small optimisations, but the changes didn't make a difference.

**Comment by jhonatandarosa** [comment]
We have a big performance improvemente with haystack.
Now, we change to bezier only when needed.
We are trying to simplify the stylesheet to see if there's a worthy improvement.

**Comment by maxkfranz** [comment]
Good to hear your performance is improved; closing for now
