### ISSUE TITLE
Specifying handedness of curved edges

### ISSUE THREAD

**Issue by dfsp-spirit** [cytoscape/cytoscape.js#985]
How is the handedness of a curve defined when using 'curve-style': 'unbundled-bezier?

I have created the following graph:
![cy](https://cloud.githubusercontent.com/assets/1061893/8282259/80731da0-18ef-11e5-9b51-c8f9fc029a85.png)

The relevant edge settings are:
    'curve-style': 'unbundled-bezier',
    'control-point-distance': 'data(edgeHeight)',
    'control-point-weight': '0.5'

and the 'edgeHeight' property used for 'control-point-distance' is set to something like '-200px' (depending on the length of the edge).

All edges in the image are from left to right (I added the arrow heads to prove this), and all values for 'edgeHeight' are negative (The full source for that image is here if you need it: http://pastebin.com/CME0bTAt). The problem is that most edges are bent upwards (clockwise), BUT some are bend downwards (counter-clockwise) for some reason.

How can one define the handedness of curved edges? I can of course change the sign of the control point distance ('-200px' to '200px'), but as you can see in the source, it is set to negative values for ALL edges already. Still some behave different than others. 

Is this a bug? Or is there some other way to specify this that I missed from the documentation? I need all edges to behave consistently.

**Comment by maxkfranz** [comment]
Snapshot: http://js.cytoscape.org/download/cytoscape.js-snapshot-9e02b512eb-1434984281382.zip

**Comment by dfsp-spirit** [comment]
Thanks heaps man, that was a fast fix. I gave the snapshot a try & confirmed that it is now working.
