### ISSUE TITLE
Breadthfirst layout- not working with new cytoscapeJS version

### ISSUE THREAD

**Issue by AjitPS** [cytoscape/cytoscape.js#986]
Hi, I am using the latest version of cytoscapeJS. However, the ````breadthfirst```` layout is not working anymore. When I use it in my graph, I get the following error:
````Uncaught TypeError: Cannot read property 'index' of undefined````

This used to work in the previous version of cytoscapeJS.

My code for the <b>breadthfirst</b> layout is below:

````
function set_Breadthfirst_Layout(eles) {
     var bf_Layout= { name: 'breadthfirst', fit: true, directed: true, padding: 10, 
     circle: false, boundingBox: undefined, avoidOverlap: true, handleDisconnected: true,
     maximalAdjustments: 0, animate: false, roots: undefined, ready: 
     undefined, stop: undefined, spacingFactor: 1.75 };

eles.layout(bf_Layout);

**Comment by maxkfranz** [comment]
I can't reproduce this on regular or compound graphs.  I'd need the graph that has problems.

**Comment by maxkfranz** [comment]
Closing until reproducible

**Comment by sasoripathos** [comment]
I also find this problem if I set directed to be true

**Comment by snuup** [comment]
thank you @sasoripathos - i suddenly encountered such 

     Uncaught TypeError: Cannot read property 'index' of undefined

errors and finally concluded that this is a bug in cytoscape. setting directed to false the errors went away. 

@maxkfranz maybe i find the time and can isolate the problem.
