### ISSUE TITLE
Tokyo railways not loading

### ISSUE THREAD

**Issue by Jahzzman** [cytoscape/cytoscape.js#992]
Hello,
Seems to have a little problem loading : http://jsbin.com/gist/f64e811fc3311414e083?output
I tried to download the files to run it locally but it is still loading forever... I also tried in various browser (I work on a Mac) but same issue.

Any idea?
![capture d ecran 2015-07-01 a 17 18 49](https://cloud.githubusercontent.com/assets/13137303/8458085/4e13fc9e-2015-11e5-9d49-b6fb2f983df3.png)

**Comment by maxkfranz** [comment]
Raw Git made a breaking change.  It should be OK now.
