### ISSUE TITLE
calculating centralities and shortest paths

### ISSUE THREAD

**Issue by mktonn** [cytoscape/cytoscape.js#993]
I was trying the functions, which are calculating the centralities and the closeness (cy.$().cc()) seems to give a worng result. Instead of sum(1/dist), which is used in the function, the formula 1/(sum dist) should be used.

When using the function eles.dijkstra(), the function calculates the same distances, when using "true" for the directions, instead of the default "false"

**Comment by maxkfranz** [comment]
(1) The harmonic mean is used by default, which is better for the general case.  You can set the new flag appropriately for the arithmetic mean.

(2) See associated issue for Dijkstra

Snapshot : http://js.cytoscape.org/download/cytoscape.js-snapshot-d1361bfa4c-1435945860146.zip
